# -*- coding: utf-8 -*-

# Form implementation generated from reading myuis file 'Z:/Resource/Support/Python/2.6-x64/Lib/site-packages/idmt/maya/Pluto/PlutoGun/PlutoGunWin.myuis'
#
# Created: Thu Jan 24 18:06:17 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(901, 592)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow{\n"
"background: url(:/myuis/StarWar.jpg);\n"
"\n"
"}\n"
""))
        self.CenterWidget = QtGui.QWidget(MainWindow)
        self.CenterWidget.setAutoFillBackground(False)
        self.CenterWidget.setStyleSheet(_fromUtf8("background-color:transparent"))
        self.CenterWidget.setObjectName(_fromUtf8("CenterWidget"))
        self.widget_left = QtGui.QWidget(self.CenterWidget)
        self.widget_left.setGeometry(QtCore.QRect(20, 30, 561, 451))
        self.widget_left.setObjectName(_fromUtf8("widget_left"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_left)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Left_Layout = QtGui.QVBoxLayout()
        self.Left_Layout.setObjectName(_fromUtf8("Left_Layout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox = QtGui.QComboBox(self.widget_left)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.Low_High = QtGui.QPushButton(self.widget_left)
        self.Low_High.setObjectName(_fromUtf8("Low_High"))
        self.gridLayout.addWidget(self.Low_High, 0, 1, 1, 1)
        self.Refresh = QtGui.QPushButton(self.widget_left)
        self.Refresh.setObjectName(_fromUtf8("Refresh"))
        self.gridLayout.addWidget(self.Refresh, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.Left_Layout.addLayout(self.gridLayout)
        self.tmp_label = QtGui.QLabel(self.widget_left)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.tmp_label.setFont(font)
        self.tmp_label.setStyleSheet(_fromUtf8("color:rgb(255, 255, 0);"))
        self.tmp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_label.setObjectName(_fromUtf8("tmp_label"))
        self.Left_Layout.addWidget(self.tmp_label)
        self.Left_Layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.Left_Layout)
        self.widget_right = QtGui.QWidget(self.CenterWidget)
        self.widget_right.setGeometry(QtCore.QRect(620, 30, 284, 482))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right.sizePolicy().hasHeightForWidth())
        self.widget_right.setSizePolicy(sizePolicy)
        self.widget_right.setObjectName(_fromUtf8("widget_right"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_right)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.widget_right)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet(_fromUtf8(""))
        self.tableWidget.setFrameShape(QtGui.QFrame.WinPanel)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lcdNumber = QtGui.QLCDNumber(self.widget_right)
        self.lcdNumber.setMinimumSize(QtCore.QSize(40, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lcdNumber.setPalette(palette)
        self.lcdNumber.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setMode(QtGui.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 5)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.widget_right)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 60))
        self.horizontalSlider.setStyleSheet(_fromUtf8("            QSlider::groove:horizontal {\n"
"                 border: 1px inset qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #565656, stop:1 #848484);\n"
"                 border-radius: 6px;\n"
"                 height: 10px;\n"
"                 background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #848484, stop:1 #919191);\n"
"                 margin: 2px 6px;\n"
"             }\n"
"\n"
"             QSlider::handle:horizontal {\n"
"                 background-color: rgba(0,0,0,0);\n"
"                 image: url(:/myuis/slider_knob.png);\n"
"                 border: 0px;\n"
"                 width: 40px;\n"
"                 margin: -10px; \n"
"                 border-radius:10px;\n"
"             }"))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(9)
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setProperty("value", 5)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 0, 1, 1)
        self.Shoot_Gun = QtGui.QToolButton(self.widget_right)
        self.Shoot_Gun.setMinimumSize(QtCore.QSize(60, 60))
        self.Shoot_Gun.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Shoot_Gun.setFont(font)
        self.Shoot_Gun.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0);\n"
"border-image: url(:/images/slider_knob.png);\n"
""))
        self.Shoot_Gun.setObjectName(_fromUtf8("Shoot_Gun"))
        self.gridLayout_2.addWidget(self.Shoot_Gun, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.CenterWidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PlutoGun", None, QtGui.QApplication.UnicodeUTF8))
        self.Low_High.setText(QtGui.QApplication.translate("MainWindow", "LOW  /  HIGH", None, QtGui.QApplication.UnicodeUTF8))
        self.Refresh.setText(QtGui.QApplication.translate("MainWindow", "REFRESH", None, QtGui.QApplication.UnicodeUTF8))
        self.Refresh.setProperty("-command", QtGui.QApplication.translate("MainWindow", "\"print \\\"s\\\"\"", None, QtGui.QApplication.UnicodeUTF8))
        self.tmp_label.setText(QtGui.QApplication.translate("MainWindow", "文件中没找到带PlutoGun系统的道具", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "新建行", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Laser", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Vis", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.Shoot_Gun.setText(QtGui.QApplication.translate("MainWindow", "Shoot", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
