$var = `ls -sl` ;

	for($tmp in $var)
	{
	$dup = `duplicate -renameChildren "nGrp"`;
	$sub = substituteAllString($tmp, "_msh","") ;
	$tmpA = stringToStringArray($sub,"|") ;
		if(size($tmpA) > 1)
			$sub = $tmpA[1] ;

	print $dup ;
	rename $dup[0] ($sub +"_grp") ;
	rename $dup[1] ($sub +"_leaf_msh") ;
	rename $dup[2] ($sub +"_stern_msh") ;

	$pa = `parentConstraint $tmp ($sub +"_grp") `;
	delete $pa ;
	$pa = `scaleConstraint  $tmp($sub +"_grp") `;
 	delete $pa ;

    }


	$var = `ls -sl` ;

	for($tmp in $var)
	{
	$list = `listRelatives -fullPath -children -type "transform" $tmp `;
	rename $list[0] ($tmp +"_leaf_msh") ;
	rename $list[1] ($tmp +"_stern_msh") ;

    }