global proc shelf_pipelineCtrl()
{
    python("import maya.cmds as cmds");
    python("import maya.mel as mel");

//前期
    shelfButton
        -width 34
        -height 34
        //-bgc 0.2 0.6 0.2
        -font "smallPlainLabelFont"
        -style "iconOnly"
        //-image "vacantCell.png"
//        -image "do6/do6.png"
//        -highlightImage "do6/do6.png"
        -iol "前期"
        -olc 0 1 0
        -olb 0 0 1 0.25
        -annotation "前期工具集"
        -command "baseShelfChanges_do6 \"Pre\""
    ;
//
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
//        -image "do6/do6.png"
//        -highlightImage "do6/do6.png"
        -annotation "设置工具集"
        -iol "设置"  -olc 0 1 0
        -command "baseShelfChanges_do6 \"Set\""
    ;

//动画
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
//        -image "do6/do6.png"
//        -highlightImage "do6/do6.png"
        -iol "动画"
        -annotation "动画工具集"
         -olc 0 1 0
        -command "baseShelfChanges_do6 \"Ani\""
    ;

//特效
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
//        -image "do6/do6.png"
//        -highlightImage "do6/do6.png"
        -iol "特效"
        -olc 0 1 0
        -annotation "特效工具集"
        -command "baseShelfChanges_do6 \"Eff\""
    ;

//渲染
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
//        -image  "do6/do6.png"
//        -highlightImage "do6/do6.png"
        -iol "渲染"
        -olc 0 1 0
        -annotation "渲染工具集"
        -command "baseShelfChanges_do6 \"Rnd\""
    ;

  //zzj    empty**************************
  //隐藏面板
     shelfButton -width 34 -height 34 -vis 0
//    -i1 (zwGetIcon("wxII/it.xpm"))
     -c "zzjshelf()";
//================= Preproduction ====================

}


global proc baseShelfChanges_do6(string $steps)
{
    string $childArray[] = `shelfLayout -query -childArray do6`;
    int $size = size($childArray);

    int $index = 7;

    for ($i=0; $i<$size; $i++)
    {
        string $docTag = `shelfButton -query -docTag $childArray[$i]`;
        if ($docTag != "")
        {
            if ($docTag == $steps)
            {
                shelfButton -edit -visible 1 $childArray[$i];
                $index ++;
                shelfLayout -edit -position $childArray[$i] $index do6;
            }
            else
            {
                shelfButton -edit -visible 0 $childArray[$i];
            }
        }

        else
        {
            if (match($steps,$childArray[$i]) == $steps)
            {
                shelfButton -e -bgc 0 1 1 $childArray[$i];
            }
            else
                shelfButton -e -ebg 0  $childArray[$i];
        }
    }
    optionVar -stringValue "baseShelfSelected_do6" $steps;
}