global proc cMakerAddObstacle() {
  string $objList[]= `ls -sl`;
  string $currentObject;

  if (size($objList)< 1)
    error "Select an Obstacle";
  
  for ($currentObject in $objList) {
    if (`attributeQuery -node ($currentObject) -exists radius` != 1)
      error ("can't find the attribute RADIUS in "+$currentObject);
      else {
        rename $currentObject ("CMObstacle_"+$currentObject); 
      }
  }

}
