/*
*****  CROWD MAKER v0.6 beta 3 *****

(c) 02.2005, Adriano Rinaldi

rinaldi.adriano@gmail.com



You are free to use this software!
you can simulate maximum 1000 particles.

***** ------------------- *****
*/




global proc cMakerSetupUI() {


  	global string $prefS100;
	$pathIc = substituteAllString($prefS100,";","");
	$pathIc += "/icons/cMakerImages/";

  string $objList[]= `ls -sl`;

  string $scriptDir= $pathIc ;    // Return the user script directory.

  if (size($objList) != 1)
    error "Select the PARTICLE";

  string $partShape[]= `ls -sl -type particle -dag ($objList[0])`;

  if (size($partShape) == 0)
    error "You must select a PARTICLE object";

  if (`attributeQuery -node ($partShape) -exists sepVisRadius` != 1)
     error "You must select a particle with Crowd Maker applied";


  // Create the window.
  if (`window -exists cMakerSetupWindow`)
    deleteUI cMakerSetupWindow;

  window
    -widthHeight 450 500
    -title "CrowdMaker 0.6 beta 3"
    cMakerSetupWindow;

  string $tabs= `tabLayout`;


  string $tab1= `formLayout`;
    string $txtL= `text -label "Cylinder Length (Min/Max)"`;
    string $txtR= `text -label "Cylinder Radius (Min/Max)"`;
    string $txtA= `text -label "Rotation Angle (Min/Max)"`;

    string $floatfield1= `floatField -pre 5 cLengthMin`;
    connectControl cLengthMin ($partShape[0]+".cylinderLengthMin");
    string $floatfield1_2= `floatField -pre 5 cLengthMax`;
    connectControl cLengthMax ($partShape[0]+".cylinderLengthMax");
    string $floatfield2= `floatField -pre 5 cRadiusMin`;
    connectControl cRadiusMin ($partShape[0]+".cylinderRadiusMin");
    string $floatfield2_2= `floatField -pre 5 cRadiusMax`;
    connectControl cRadiusMax ($partShape[0]+".cylinderRadiusMax");
    string $floatfield3= `floatField -pre 5 rAngleMin`;
    connectControl rAngleMin ($partShape[0]+".rotationAngleMin");
    string $floatfield3_2= `floatField -pre 5 rAngleMax`;
    connectControl rAngleMax ($partShape[0]+".rotationAngleMax");
    string $subTab1= `paneLayout -w 400 -h 300`;
    string $image1= `image -image ($scriptDir+"obstacleAvoidance.jpg")`;
  setParent ..;  setParent ..;

  string $tab2= `formLayout`;
    string $txtSepR= `text -label "Visibility Radius (Min/Max)"`;
    string $floatfield4= `floatField -pre 5 sepRadiusMin`;
      connectControl sepRadiusMin ($partShape[0]+".sepVisRadiusMin");
    string $floatfield4_2= `floatField -pre 5 sepRadiusMax`;
      connectControl sepRadiusMax ($partShape[0]+".sepVisRadiusMax");
    string $subTab2= `paneLayout -w 400 -h 300`;
      string $image2= `image -image ($scriptDir+"separation.jpg")`;
  setParent ..;  setParent ..;

  string $tab3= `formLayout`;
    string $txtAlR= `text -label "Visibility Radius (Min/Max)"`;
    string $floatfield5= `floatField -pre 5 alRadiusMin`;
      connectControl alRadiusMin ($partShape[0]+".alVisRadiusMin");
    string $floatfield5_2= `floatField -pre 5 alRadiusMax`;
      connectControl alRadiusMax ($partShape[0]+".alVisRadiusMax");
    string $subTab3= `paneLayout -w 400 -h 300`;
      string $image3= `image -image ($scriptDir+"alignment.jpg")`;
  setParent ..;  setParent ..;

  string $tab4= `formLayout`;
    string $txtF= `text -label "f = [unit (A + B + C)]  *  ScaleValue"`;
    string $txtSeek= `text -label "A =  Seek  *  (Min/Max)"`;
    string $floatfield6= `floatField -pre 5 seekFactorMin`;
      connectControl seekFactorMin ($partShape[0]+".seekFactorMin");
    string $floatfield6_2= `floatField -pre 5 seekFactorMax`;
      connectControl seekFactorMax ($partShape[0]+".seekFactorMax");
    string $txtAl= `text -label "B =  Alignment  *  (Min/Max)"`;
    string $floatfield7= `floatField -pre 5 alFactorMin`;
      connectControl alFactorMin ($partShape[0]+".alignmentFactorMin");
    string $floatfield7_2= `floatField -pre 5 alFactorMax`;
      connectControl alFactorMax ($partShape[0]+".alignmentFactorMax");
    string $txtSep= `text -label "C =  Separation  *  (Min/Max)"`;
    string $floatfield8= `floatField -pre 5 sepFactorMin`;
      connectControl sepFactorMin ($partShape[0]+".separationFactorMin");
    string $floatfield8_2= `floatField -pre 5 sepFactorMax`;
      connectControl sepFactorMax ($partShape[0]+".separationFactorMax");
    string $txtVal= `text -label "Scale Value  (Min/Max)"`;
    string $floatfield9= `floatField -pre 5 scaleFactorMin`;
      connectControl scaleFactorMin ($partShape[0]+".scaleValueMin");
    string $floatfield9_2= `floatField -pre 5 scaleFactorMax`;
      connectControl scaleFactorMax ($partShape[0]+".scaleValueMax");
  setParent ..;  setParent ..;

   string $tab5= `formLayout`;
     string $about= "*****  CROWD MAKER v0.6 beta 3 ***** \n";
     $about+= "\n          (c) 02.2005, Adriano Rinaldi \n";
     $about+= "\n          rinaldi.adriano@gmail.com\n";
     $about+= "\n********************************************";
     $about+= "\n \n \nWhat's new in Crowd Maker 0.6";
     $about+= "\n    - New \"Surface Follow\" function, particles can";
     $about+= "\n      move along a Nurbs surface!";
     $about+= "\n    - New Random attributes.";
     $about+= "\n    - More accurate functions.";
     $about+= "\n \n \nNot compatible with precedent version.";
     string $txtAbout= `text -w 350 -fn "boldLabelFont" -label $about`;
  setParent ..;

  tabLayout -edit
    -tabLabel $tab1 "Obstacle Avoidance"
    -tabLabel $tab2 "Separation"
    -tabLabel $tab3 "Alignment"
    -tabLabel $tab4 "Output Function"
    -tabLabel $tab5 "About"
  $tabs;

  formLayout -edit
    -attachForm $txtAbout "top" 20
    -attachForm $txtAbout "left" 10
  $tab5;

  formLayout -edit
    -attachForm $txtF "top" 20
    -attachForm $txtF "left" 10
    -attachForm $txtSeek "top" 80
    -attachForm $txtSeek "left" 10
    -attachForm $txtAl "top" 120
    -attachForm $txtAl "left" 10
    -attachForm $txtSep "top" 160
    -attachForm $txtSep "left" 10
    -attachForm $txtVal "top" 200
    -attachForm $txtVal "left" 10
  $tab4;

  formLayout -edit
    -attachForm $floatfield6 "top" 75
    -attachForm $floatfield6 "left" 200
    -attachForm $floatfield6_2 "top" 75
    -attachForm $floatfield6_2 "left" 270
    -attachForm $floatfield7 "top" 115
    -attachForm $floatfield7 "left" 200
    -attachForm $floatfield7_2 "top" 115
    -attachForm $floatfield7_2 "left" 270
    -attachForm $floatfield8 "top" 155
    -attachForm $floatfield8 "left" 200
    -attachForm $floatfield8_2 "top" 155
    -attachForm $floatfield8_2 "left" 270
    -attachForm $floatfield9 "top" 195
    -attachForm $floatfield9 "left" 200
    -attachForm $floatfield9_2 "top" 195
    -attachForm $floatfield9_2 "left" 270
  $tab4;

  formLayout -edit
    -attachForm $subTab1 "top" 180
    -attachForm $subTab1 "left" 10
  $tab1;

  formLayout -edit
    -attachForm $subTab2 "top" 180
    -attachForm $subTab2 "left" 10
  $tab2;

   formLayout -edit
    -attachForm $subTab3 "top" 180
    -attachForm $subTab3 "left" 10
  $tab3;

  formLayout -edit
    -attachForm $txtL "top" 20
    -attachForm $txtL "left" 10
    -attachForm $txtR "top" 60
    -attachForm $txtR "left" 10
    -attachForm $txtA "top" 100
    -attachForm $txtA "left" 10
  $tab1;

  formLayout -edit
    -attachForm $floatfield1 "top" 15
    -attachForm $floatfield1 "left" 200
    -attachForm $floatfield1_2 "top" 15
    -attachForm $floatfield1_2 "left" 270
    -attachForm $floatfield2 "top" 55
    -attachForm $floatfield2 "left" 200
    -attachForm $floatfield2_2 "top" 55
    -attachForm $floatfield2_2 "left" 270
    -attachForm $floatfield3 "top" 95
    -attachForm $floatfield3 "left" 200
    -attachForm $floatfield3_2 "top" 95
    -attachForm $floatfield3_2 "left" 270
  $tab1;

  formLayout -edit
    -attachForm $txtSepR "top" 20
    -attachForm $txtSepR "left" 10
    -attachForm $floatfield4 "top" 15
    -attachForm $floatfield4 "left" 200
    -attachForm $floatfield4_2 "top" 15
    -attachForm $floatfield4_2 "left" 270
  $tab2;

  formLayout -edit
    -attachForm $txtAlR "top" 20
    -attachForm $txtAlR "left" 10
    -attachForm $floatfield5 "top" 15
    -attachForm $floatfield5 "left" 200
    -attachForm $floatfield5_2 "top" 15
    -attachForm $floatfield5_2 "left" 270
  $tab3;

  showWindow cMakerSetupWindow;
}
