// upload cache
if ($copyCache)
{
    CheckinCacheFile($project,$destFolder);
    if(`pluginInfo -query -loaded "pgYetiMaya"`){
        print "\n上传yeti缓存\n";
        zwCheckCopyYetiCache($destFolder,$project);
    }
    if (`pluginInfo -query -loaded "shaveNode.mll"`){
        zwCheckCopyShaveCache($destFolder);
    }

    zwCheckCopyAbcCache($destFolder,$project);
}

//// 删除所有ViewSelectedSet
//if (!`about -batch`)
//{
//    $buf = `getPanel -type "modelPanel"`;
//    for ($modelPanel in $buf)
//    {
//        isolateSelect -state false $modelPanel;
//    }
//}

// 线框显示
$buf = `getPanel -type "modelPanel"`;
for($panel in $buf)
    modelEditor -edit -displayAppearance "wireframe" -displayLights "default" $panel;

if ($copyMaps)
{
    string $files[] = `ls -type "file"`;
    for ($file in $files)
    {
        if (`reference -isNodeReferenced $file`)
        {
            continue;
        }

        string $fileTextureName = `getAttr ($file + ".fileTextureName")`;

        //	string $texname = `match "[^/\\]+$" $fileTextureName`;
        //	$upPath = "${OCTV_PROJECTS}/" + $project + "/Project/sourceimages/" + $asset_type + "/" + $idName + "/" + $texname;
        //	$upPath = `substitute "/[^/]+$" $str ""` + "/" + $texname;
        //	$upPath = `substitute "//octvision.com/CG/Themes" $destMapFolder "${OCTV_PROJECTS}"` + "/" + $texname;

        //string $upPath = `substitute "//octvision.com/CG/Themes" $fileTextureName "${OCTV_PROJECTS}"`;
        string $upPath = `substitute "//octvision.com/CG/Themes" $fileTextureName "Z:/Themes"`;
        $upPath = `substituteAllString $upPath "${OCTV_PROJECTS}" "Z:/Themes"`;

        if ($fileTextureName != $upPath)
        {
            setAttr ($file + ".fileTextureName") -type "string" $upPath;
        }
    }

}
// save a temp file for uploading
int $rs_2 = catch(`file -force -prompt false -save -uiConfiguration false`);
if ($rs_2)
{
    sysFile -delete $temp;
    error "不能保存文件，请检查是否D：盘空间不足";
}
print ("\nasset_type:" + $asset_type);
int $tdTest = `getenv "OCTV_TDTEST"`;
if ( $tdTest!= 0)
{
    error ("测试，文件已经另存为：" + $temp);
}
//Upload attached file and maya file
string $bakfList[] = `getFileList -folder ($destFolder + "/" + "Backups/")`;
string $newFile = `file -q -sn`;
string $onlyfilename = basename($newFile, "");
string $headName = `match "[^.]+" $onlyfilename`;

print ("\nnewFile:" + $newFile);
print ("\ndestFile:" + $destFolder);
int $flagCam=false;
string $sysrs = "";
string $bakname = "";
//动画自动导出摄像机组
//相机目标路径
string $camFolder="";
string $camName="";
$bakfList = `getFileList -folder ($destFolder + "/")`;
$headName = `substring $headName 1 (size($headName)-5)`;
print ("\n--------------headename:" + $headName);
string $verhis[];
clear $verhis;
for ($item in $bakfList)
{
    print ("\nitem:" + $destFolder + "/"+ $item);
    print ("\nheadName:" + $headName);
    if (`filetest -f ($destFolder + "/" + $item)` && `gmatch $item ($headName + "*")`)
    {
        $verhis[size($verhis)] = $item;
    }
}
string $sortVerhis[] = `sort $verhis`;
string $lastVerfile = "";
if (size($sortVerhis))
    $lastVerfile = $sortVerhis[size($sortVerhis)-1];

print ("\nlastVerfile:" + $lastVerfile);
string $cver = `match "_c[0-9]{3}." $lastVerfile`;
int $onlyver = int(`substring $cver 3 5`);

int $padding = 3;
string $newNum = `python ("'%0" + $padding + "d' % " + ($onlyver + 1))`;
$bakname = $headName + "_c" + $newNum;

for ($i =1; $i<($onlyver-1); $i++)
{
    string $hisNum = `python ("'%0" + $padding + "d' % " + $i)`;
    string $hisname = $headName + "_c" + $hisNum;
    $sysrs = `zwSysFile "del" ($destFolder + "/" + $hisname + "." + $fileExt) "" 0`;  //删除原来的文件重命名文件名
}

//2016.2.29上传效果图片
//if  ($attached != "")
//{
string $attachedExt = fileExtension($attached);
string $attachedName;
 $attachedName = $headName + "." + $attachedExt;
$sysrs = `zwSysFile "copy" $attached ($destFolder + "/" + $attachedName) 0`;

string $db = "dbo.filesystem_upload";

string $fpath=$destFolder + "/" + $attachedName;

string $buf[];
clear $buf;
tokenize $attachedName "_." $buf;
print $buf[1];
print"\n";
print $buf[2];
python("import octvDB");

string $anim="animation";
python("octvDB.delTextureDB('" + $db + "','" +$attachedName + "')");
python("octvDB.insertAnimationDB('" + $db + "','" + $attachedName + "','" + $fpath + "','" + $project + "','" + $buf[1] + "','" + $buf[2] + "','" + 1 + "','" + $anim + "','" + $mode + "')");

//}

$sysrs = `zwSysFile "fcopy" $newFile $destFolder 0`;  //拷贝一个新的文件在目录下

/*string $msFolder = "";
string $msAnim = "";
if ($mode == "rigging")
{
    $msFolder = `substitute "/rigging" $destFolder "/master"`;
    //2015.12.11
    if(`match "_dy_" $onlyfilename`!="" ){
        $msAnim = `substitute "_dy_rg" $onlyfilename "_h_dy_msAnim"`;

    }else if(`match "_mc_" $onlyfilename`!=""){
        $msAnim = `substitute "_mc_rg" $onlyfilename "_h_mc_msAnim"`;

    }else{
        $msAnim = `substitute "_rg" $onlyfilename "_msAnim"`;
    }

    $sysrs = `zwSysFile "copy" $newFile ($msFolder + "/" + $msAnim) 0`;
}*/


//record for database
string $upUser = `getenv username`;
string $db = "animation";
string $fstate = "0";
string $ftype = "1";
string $fpath = ($destFolder + "/" + $filename);
string $checkState = "1";
string $checkUser = "";

switch($mode)
{
    case "layout":
        $ftype = "5";
        break;
    case "anim":
        $ftype = "0";
        break;
    case "camera":
        if($asset_type=="cameras"){
            $ftype = "2";  //总相机类型
        }else{
            $ftype = "11"; //动画相机类型
        }
        break;
    case "cache":
        $ftype = "1";
        break;
    case "crowd":
        $ftype = "3";
        break;
    case "simulation":
        $ftype = "7";
        break;
    case "effect":
        $ftype = "4";
        break;
    case "render":
        $ftype = "6";
        break;
    case "lighting":
        $ftype = "9";
        break;
}

python("import octvDB");

python("octvDB.insertDB('" + $db + "','" + $filename + "','" + $fstate + "','" + $ftype + "','" + $upUser + "','" + $fpath + "','" + $checkState + "','" + $checkUser  + "','" + $desc + "')");

if ($mode == "anim" && $flagCam==true)
{
    $fstate = "0";
    $fpath = ($camFolder + "/" + $camName);

    //python("octvDB.delDB('" + $db + "','" + $camName + "')");
    $ftype = "11";
    python("octvDB.insertDB('" + $db + "','" + $camName + "','" + $fstate + "','" + $ftype + "','" + $upUser + "','" + $fpath + "','" + $checkState + "','" + $checkUser  + "','" + $desc + "')");
}
//if($project == "JMWC"){
string $upUser = `getenv username`;
string $bufer[];
string $fileNames="";
int $i=`tokenize $filename "_." $bufer`;
if(`match "c" $buf[$i-2]`!=""){
    string $cver = `match "_c[0-9]{3}." $filename`;
    int $newver = int(`substring $cver 3 5`) - 1;
    int $padding = 3;
    string $newNum = `python ("'%0" + $padding + "d' % " + $newver)`;

    for($j=0; $j<$i; $j++){
        if($fileNames==""){
            $fileNames=$bufer[$j];
        }else if($i-2==$j){
            $fileNames=$fileNames+"_c"+$newNum;
        }else if($i-1==$j){
            $fileNames=$fileNames+"."+$bufer[$j];
        }else{
            $fileNames=$fileNames+"_"+$bufer[$j];
        }
    }
    }
string $dbreturn[] = `python("octvDB.queryCheckUserDB('" + $db + "','" + $fileNames +"')")`;
string $checkUser = $dbreturn[0];
if($checkUser==$upUser && strip($checkUser)!= ""){
    python("octvDB.setCheckUserUNLLDB('" + $db + "','" + $fileNames + "')");
}
//}

//inform relative group members
string $newbuf[];
clear $newbuf;

tokenize $filename "_." $buf;
string $prefName = $buf[0] + "_" + $buf[1];

string $OCTV_TECH = `getenv "OCTV_TECH"`;	//OCTV Tech folder
string $invokepath = $OCTV_TECH + "/bin/msg/";
string $cmd = $invokepath + "cmdMsgPush.exe \"" + "sendFileSysNotice"  + "\" \""  +  $prefName + "\" \""  + "文件系统有新的文件上传了,文件名:" + $filename + "\"";
print ("\n------*******---------" + $cmd + "\n");
string $sysCmd = `system $cmd`;


