string $cmdStr = "octvCheckinMain(\"" + $project + "\", \"" + $upfilename + "\", \"" + $destFolder + "\", \"" + $mode + "\", \"" + $destMapFolder + "\", \"" + $asset_type + "\")"
"octvCheckinMain(\"" + $project + "\", \"" + $upfilename + "\", \"" + $destFolder + "\", \"" + $mode + "\", \"" + $destMapFolder + "\", \"" + $asset_type + "\")")`;
string $parameters[] = {$project,$filename,$destFolder,$copyMaps,$copyCache,$optimizeImagePlane,$progress,$optimize,$mode,$destMapFolder,$asset_type,$attached,$desc};

octvCheckinMain("CDSGFC", "CDSGFC_sc02_sh01_an_c001.mb", "E:/All_Projects/Checkin_dest/CDSGFC/Project/scenes/animation/sc02/sh01/anim", "anim", "E:/All_Projects/Checkin_dest/CDSGFC/Project/sourceimages/animation/sc02/sh01/maps", "") //


string $OCTV_PROJECTS = "E:/All_Projects/Checkin_dest";
	$destFolder = $OCTV_PROJECTS + "/" + $project + "/Project/scenes/animation/" + $sceneNum + "/" + $shotNum + "/" + $mode;

if (!`file -q -exists $destFolder`)   sysFile -md $destFolder;

string $project ="CDSGFC";
string $filename =  "CDSGFC_sc02_sh01_an_c001.mb";
string $destFolder = "E:/All_Projects/Checkin_dest/CDSGFC/Project/scenes/animation/sc02/sh01/anim"
string $destMapFolder = "E:/All_Projects/Checkin_dest/CDSGFC/Project/sourceimages/animation/sc02/sh01/maps"
string $mode = "anim"
string $asset_type = ""

int $optimize = `checkBoxGrp -q -value1 oCTCtrlb4`;
int $copyCache = `checkBoxGrp -q -value4 oCTCtrlb4`;
int $optimizeImagePlane = `checkBoxGrp -q -value3 oCTCtrlb4`;
int $copyMaps = `checkBoxGrp -q -value2 oCTCtrlb4`;
int $progress = `intSliderGrp -q -v oCTCtrlb3`;
string $attached = `text -q -label oCTCtrlb6`;
string $desc = `textFieldGrp -q -text oCTCtrlb4a`;

	int $val = zwCheckinPreMel($project, $asset_type, $mode);
	if ($val)
	{
		//source "\\\\octvision.com\\cg\\Tech\\maya_sixteen\\scripts\\checkin\\octvCheckinCleanup.mel";
		string $path = "//octvision.com/cg/Tech/maya_sixteen/scripts/checkin/octvCheckinCleanup.mel";

		eval ("source \"" + $path + "\"");

		string $parameters[] = {$project,$filename,$destFolder,$copyMaps,$copyCache,$optimizeImagePlane,$progress,$optimize,$mode,$destMapFolder,$asset_type,$attached,$desc};
		octvCheckinCleanup($parameters);

		print "Checkin Succeeds!";
	}
	deleteUI ocvtCheckinWindow;
}
