//catch

cmdFileOutput -o "E:/copyTexture_check.txt";

for ($node in $nodes)
	{
		if (!$batchMode)
		{
			if (`progressWindow -query -isCancelled`)
			{
				progressWindow -endProgress;
				error "";
			}
			$progress ++;
			progressWindow -edit -progress $progress -status ($progress + "/" + $max + "\t" + $node);
		}

		if (`reference -isNodeReferenced $node`)
		{
			continue;
		}
		print ("\n---------------node:" + $node+"\n");
		string $file = `getAttr ($node + "." + $attr)`;
		if ($file == "")
		{
			continue;
		}

		$file = `workspace -expandName $file`;


		if (!`filetest -f $file`)
		{
			if ($node == "brush")
			{
				if ($attr == "imageName")
				{
					if (!(`getAttr ($node + ".mapColor")` && `getAttr ($node + ".textureType")` == 4))
					{
						continue;
					}
				}
				if ($attr == "leafImage")
				{
					if (!(`getAttr ($node + ".tubes")` && `getAttr ($node + ".leaves")` && !`getAttr ($node + ".leafUseBranchTex")`))
					{
						continue;
					}
				}
				if ($attr == "flowerImage")
				{
					if (!(`getAttr ($node + ".tubes")` && `getAttr ($node + ".flowers")` && !`getAttr ($node + ".flowerUseBranchTex")`))
					{
						continue;
					}
				}
			}
			$message = "贴图/代理丢失：" + $node + "." + $attr + "\t" + $file;
			if ($errorStop)
			{
				if (!$batchMode)
					progressWindow -endProgress;
				if ($percentage >= 100 && `nodeType $node` != "VRayMesh")
					error $message;
				else
					warning $message;
			}
			else
			{
				warning $message;
				continue;
			}
		}
		$file = `zwFullPath $file`;
		string $texture = $file;

		print ("\n---------------texture:" + $texture + "\n");
		int $except = false;
		if (`gmatch (tolower($file)) (tolower($exceptFolder))`||`gmatch (tolower($texture)) (tolower($OCTV_PROJECTS  + "/" + $project + "/Project/sourceimages/*"))`||`gmatch (tolower($texture)) (tolower("${OCTV_PROJECTS}/" + $project + "/Project/sourceimages/*"))`)
			$except = true;
		print ("\n---------------except:" + $except + "\n");
		clear $buf4;
		//
		string $filename = `match "[^/\\]+$" $file`;
		string $folder = `substring $file 1 (size($file) - size($filename))`;
		$texture = $destFolder + "/" + $filename;
		if(!$except)	// 需要上传
		{
			print ("\n---------------desttexture:" + $texture);
			$buf4[size($buf4)] = $file;
			if (`attributeExists "useFrameExtension" $node`)
			{
				if (`getAttr ($node + ".useFrameExtension")`)
				{
					string $buf2[] = zwGetSequence($folder + "/" + $filename);
					for ($seq in $buf2)
					{
						$buf4[size($buf4)] = $folder + "/" + $seq;
					}
				}
			}

			//

			if (`attributeExists "uvTilingMode" $node`){

				if(`getAttr ($node + ".uvTilingMode")` == 2 || `getAttr ($node + ".uvTilingMode")` == 3){
					string $path = "//octvision.com/cg/Tech/maya_sixteen/scripts/checkin/zwGetUVSequence.mel";

					eval ("source \"" + $path + "\"");

					string $buf3[] = zwGetUVSequence($folder + "/" + $filename);
					for ($seq in $buf3)
					{
						$buf4[size($buf4)] = $folder + "/" + $seq;
					}
					string $buf5[] = zwGetSequence($folder + "/" + $filename);
					for ($seq in $buf5)
					{
						int $f = stringArrayContains($folder + "/" + $seq, $buf4);
						if($f != 1){
							$buf4[size($buf4)] = $folder + "/" + $seq;
						}
					}
				}
			}

			//

			$modifyPath = 1;
		}
		else
			$modifyPath = 0;

		for ($source in $buf4)
		{
			if (!$batchMode)
			{
				if (`progressWindow -query -isCancelled`)
				{
					progressWindow -endProgress;
					error "";
				}
			}

			if(`stringArrayCount $source $all`)
				continue;

			$all[size($all)] = $source;

			string $filename = `match "[^/\\]+$" $source`;
			string $dest = $destFolder;

			print ("\n---------------dest:" + $dest);

			/*$rs = `zwSysFile "fcopy" $source $dest 0`;

			if ($rs != "")
			{
				$message = "拷贝文件出错：" + $node + "." + $attr + "\n" + $rs;
				if ($errorStop)
				{
					if (!$batchMode)
						progressWindow -endProgress;
					if ($percentage >= 100)
						error $message;
					else
						warning $message;
				}
				else
				{
					warning $message;
					continue;
				}
			}
			else
				print ($dest + "\n");*/

			while(true){
			    $rs = `zwSysFile "fcopy" $source $dest 0`;
			    if ($rs != "")
				{
					$message = "拷贝文件出错：" + $node + "." + $attr + "\n" + $rs + "\n" + $source + $dest+ "请检查网络？";
					if ($errorStop)
					{
						if (!$batchMode)
							progressWindow -endProgress;
						if ($percentage >= 100){
							error $message;
							break;
						}else{
						   string $result=`confirmDialog -title "警告" -message $message -button "Continue" -button "stop"`;
						    if($result=="stop"){
						        error $message;
						        break;
						    }
							//warning $message;
						}
					}
					else
					{
					    string $result=`confirmDialog -title "警告" -message $message -button "Continue" -button "stop"`;
			    	    if($result=="stop"){
			    		     error $message;
			    		     break;
			    		}
						//warning $message;
						//continue;
					}
				}
				else{
				   print ($dest + "\n");
				   break;
				}
			}
			pause -sec 3;
		}

		string $sourceUrl = `getAttr ($node + "." + $attr)`;
		$sourceUrl = `substituteAllString $sourceUrl "\\" "/"`;
		string $destUrl = $texture;

		print ("\nmodifyPath:" + $modifyPath);
		print("---------------------------\n");
		//if ($modifyPath && `filetest -f $texture` && tolower($sourceUrl) != tolower($destUrl))

		//2015.6.5
		/*if (`filetest -f $texture`)
		{
				print("node:"+$node);
				print("seting:"+$destUrl+"\n");

				setAttr ($node + "." + $attr) -type "string" $destUrl;
		}*/

		//2016.12.14
		if($modifyPath && `filetest -f $texture`){
			print("node:"+$node);
			print("seting:"+$destUrl+"\n");

			$destUrl = `zwFullPath $destUrl`;
			string $destUrl_tmp = `substitute "//octvision.com/CG/Themes" $destUrl "Z:/Themes"`;
			$destUrl_tmp = `substituteAllString $destUrl_tmp "${OCTV_PROJECTS}" "Z:/Themes"`;

			setAttr ($node + "." + $attr) -type "string" $destUrl_tmp;

		}else if($modifyPath && (!`filetest -f $texture`)){
			$allnoSetNodePath[size($allnoSetNodePath)] = $node;
			$allnoSetNodePath[size($allnoSetNodePath)] = $attr;
			$allnoSetNodePath[size($allnoSetNodePath)] = $destUrl;
		}

	}