global proc HhAOTreeshader()
{
	
	string $done[];
	clear $done;

	string $Selectobj[] = `ls-sl`;
	for ($i=0; $i<size($Selectobj); $i++)
	{
		string $NodeShape[] = `listRelatives -fullPath -shapes $Selectobj[$i]`;
		if (size($NodeShape) == 0)
		{
			continue;
		}
		string $ShadingEngine[] = `listConnections -t "shadingEngine" $NodeShape[0]`;
		if (size($ShadingEngine) == 0)
		{
			continue;
		}
		string $Shader[] = `listConnections ($ShadingEngine[0]+".surfaceShader")`;
		string $Str =$Shader[0]+".transparency";
		if (!`objExists $Str`)
		{
			continue;
		}
		string $FileTexture[] = `listConnections $Str `;
		if(size($FileTexture)==0)
		{
			continue;
		}
		$file= $FileTexture[0];
		string $ftexture =$file + ".fileTextureName";
		string $tx=`getAttr $ftexture`;
		if(`match "sk_spplantexp_leaves_mask_h.iff" $tx`!="")
		{
			source "//file-cluster/GDC/Resource/Support/Maya/scripts/zzjSetMentalrayQuality.mel";
			zzjSetMentalrayQuality("production");
			setAttr "miDefaultOptions.maxRefractionRays" 2;
			setAttr "miDefaultOptions.maxReflectionRays" 2;
			setAttr "miDefaultOptions.maxRayDepth" 4;
			setAttr "miDefaultOptions.finalGather" 1;
			if(!`objExists TreeaoTexture`)
			{
				string $TreeaoTex = `shadingNode -asTexture mib_fg_occlusion -name "TreeaoTexture"`;
			}
			if(!`objExists TreeTrTexture`)
			{
				string $TreeaoTex = `shadingNode -asTexture mib_transparency -name "TreeTrTexture"`;
			}
			if(!`objExists TreetrShader`)
			{
				string $TreetrShader = `shadingNode -asShader lambert -name "TreetrShader"`;
				string $TreetrShaderSG = `sets -renderable true -noSurfaceShader true -empty -name "TreetrShaderSG"`;
				connectAttr -f "TreetrShader.outColor" "TreetrShaderSG.surfaceShader";
			}
			if(!`objExists TreeaoShader`)
			{
				string $TreeaoShader = `shadingNode -asShader lambert -name "TreeaoShader"`;
				string $TreeaoShaderSG = `sets -renderable true -noSurfaceShader true -empty -name "TreeaoShaderSG"`;
				connectAttr -f "TreeaoShader.outColor" "TreeaoShaderSG.surfaceShader";
				connectAttr -f "TreeaoTexture.outValue" "TreeaoShaderSG.miMaterialShader";
				connectAttr -f "TreeTrTexture.outValue" "TreetrShaderSG.miMaterialShader";
				connectAttr -f "TreeaoTexture.outValueA" "TreeTrTexture.inputA";
				connectAttr -f "TreeaoTexture.outValue" "TreeTrTexture.input";
				connectAttr -f ($file+".outAlpha") "TreeTrTexture.transpA";
				connectAttr -f ($file+".outColor") "TreeTrTexture.transp";
				setAttr ($file+".invert") 1;

			}
			select $Selectobj[$i];
			catch(`sets -e -forceElement TreetrShaderSG`);

		}
	}
	select -cl;
}