global proc HHCamIZ()
{
    string $cams[]=`ls -type "camera"`;
    for($cam in $cams)
    {
        if (`match "persp" $cam`==""&&`match "top" $cam`==""&&`match "front" $cam`==""&&`match "side" $cam`==""&&`match "Main" $cam`==""&&`match "Left" $cam`==""&&`match "Right" $cam`==""&&`match "Annotation" $cam`=="")
	{
		string $cShapes[]=`listRelatives -s $cam`;
		string $Int=$cam+".interaxialSeparation";
		if(`objExists $Int`!=0)
		{
			string $I=`getAttr $Int`;
			string $Z=`getAttr ($cam+".zeroParallax")`;
			string $c[]=`listRelatives -p $cam`;
			print($c[0]+":"+"\n");
			print ("Int="+$I+"\n");
			print ("Zero="+$Z+"\n"+"*****************************************************"+"\n");
		}
	}
    }
}