global proc HHCamRender()
{
	HHCamoff;
	source "renderWindowPanel.mel";
	string $camnews[] = `ls -type "camera" `;
	for ($newcamshape in $camnews )
	{
		if (`match "persp" $newcamshape`==""&&`match "top" $newcamshape`==""&&`match "front" $newcamshape`==""&&`match "side" $newcamshape`=="")
		{
			string $newcams[]=`listRelatives -p $newcamshape`;
			setAttr ($newcamshape+".renderable") 1;
			string $buff[];
			$nums=`tokenize $newcams[0] "_" $buff`;
			string $SQ=$buff[1];
			string $SE=$buff[2];
			setMayaSoftwareFrameExt(1, 0);
			//setAttr "miDefaultOptions.minSamples" 0;
			//setAttr "miDefaultOptions.maxSamples" 2;
			setAttr "defaultRenderQuality.shadingSamples" 2;
			setAttr "defaultRenderQuality.maxShadingSamples" 8;
			//setAttr "miDefaultOptions.filter" 2;
			setAttr "defaultRenderGlobals.imageFormat" 32;
			$filename ="sk_"+ $SQ+"_"+$SE+".png";
			string $fileshort = `file -q -sn -shn`;
			string $buffs[];
			$nums=`tokenize $fileshort "_" $buffs`;
			string $EQ=$buffs[1];
			string $path ="//file-cluster/GDC/Projects/Strawberry/Strawberry_Scratch/MasterLighting/Compositiong/Detect/"+$EQ+"/"+$SQ+"/";
			renderWindowRenderCamera "render" "renderView" $newcamshape;
			string $fd = `workspace -q  -rootDirectory` + "scenes/"+$fileshort;
			string $sceneName = `file -query -sceneName`;
			$sceneName = `substituteAllString $sceneName "/" "\\"`;
			string $renderedImageName = `optionVar -query "renderedImageName"`;
			string $f=$path+ $filename;
			sysFile -delete $f;
			sysFile -md $path;
			sysFile -move $f $renderedImageName;

		}
	}
}
global proc HHCamoff()
{
	string $cams[]=`ls -ca`;
	for ($cam in $cams)
	{
	   string $camrenderable = $cam+".renderable";
	   setAttr $camrenderable 0; 
	}
}