//////////////////////////////////////////////////////////
//
//	Script Name: eyeBallSwitch
//	Author: Justin.Chan
//	Created: 2012/08/01 
//
//	Update/Change: 
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////
//////////////////////////////////////////////控制窗口
global proc eyeBallSwitch()
{
if (`window -ex eyeBallSwitchWin`)
    deleteUI eyeBallSwitchWin;
window -title "角色眼球控制器切换" eyeBallSwitchWin;
string $AboutColayout = `columnLayout -adjustableColumn true`;//竖型布局
       menuBarLayout;//菜单栏
	 menu -label "编辑";
           menuItem -label "那个····" -command "eyeBallSwitchEdit" ;
	 menu -label "帮助说明";
           menuItem -label "帮助..." -command "eyeBallSwitchHelp";

			setParent ..;
string $HbAutoTools = `frameLayout -label "角色眼球控制器切换:" -labelAlign "top" -cl 0 -cc "" -borderStyle "etchedIn" `;
		rowColumnLayout -numberOfColumns 2 -cw 1 120 -cw 2 120;
		text " ";
		text " ";
string $button01=`button -height 30 -width 90 -bgc 0.75 0.65 0.65 -label "动画用" -c "Animation1"`;
string $button02=`button -height 30 -width 90 -bgc 0.75 0.65 0.65 -label "渲染用" -c "Rendering1"`;
			setParent ..;
			setParent ..;
string $HbAutoTools = `frameLayout -label "冻结角色毛发模型:" -labelAlign "top" -cl 0 -cc "" -borderStyle "etchedIn" `;
		rowColumnLayout -numberOfColumns 2 -cw 1 120 -cw 2 120;
		text " ";
		text " ";
string $button01=`button -height 30 -width 90 -bgc 0.75 0.65 0.65 -label "冻结" -c "Animation2"`;
string $button02=`button -height 30 -width 90 -bgc 0.75 0.65 0.65 -label "恢复" -c "Rendering2"`;
			setParent ..;			



showWindow eyeBallSwitchWin;
}
eyeBallSwitch;

///////////////////////////////////////////////运行程序
global proc Animation1()
{	 
string $getA[]=`ls "*_*_hi_eyes" "*:*_*_hi_eyes" "*_eye_L" "*:*_eye_L" "*_eye_R" "*:*_eye_R"`;
for ($aa in $getA)
	{
		setAttr ($aa+".visibility") 1;	
	}
string $getB[]=`ls "*_*_hi_eyesnew" "*:*_*_hi_eyesnew" "*_eye_Lnew" "*:*_eye_Lnew" "*_eye_Rnew" "*:*_eye_Rnew"`;
for ($aa in $getB)
	{
		setAttr ($aa+".visibility") 0;	
	}
select -cl  ;
}

global proc Rendering1()
{
string $getA[]=`ls "*_*_hi_eyes" "*:*_*_hi_eyes"  "*_eye_L" "*:*_eye_L" "*_eye_R" "*:*_eye_R"`;
for ($aa in $getA)
	{
		setAttr ($aa+".visibility") 0;	
	}
string $getB[]=`ls "*_*_hi_eyesnew" "*:*_*_hi_eyesnew" "*_eye_Lnew" "*:*_eye_Lnew" "*_eye_Rnew" "*:*_eye_Rnew"`;
for ($aa in $getB)
	{
		setAttr ($aa+".visibility") 1;	
	}
select -cl  ;
}

global proc Animation2()
{	 
string $getA[]=`ls "*_c_an_hair*" "*:*_c_an_hair*" `;
for ($aa in $getA)
	{
		setAttr ($aa+".overrideEnabled") 1;
		setAttr ($aa+".overrideDisplayType") 1;		
	}

select -cl  ;
}

global proc Rendering2()
{	 
string $getA[]=`ls "*_c_an_hair*" "*:*_c_an_hair*" `;
for ($aa in $getA)
	{
		setAttr ($aa+".overrideEnabled") 0;
		setAttr ($aa+".overrideDisplayType") 0;		
	}

select -cl  ;
}




///////////////////////////////////////////////编辑

global proc eyeBallSwitchEdit()
{
string $d = `confirmDialog -title"警告" -message"请不要按 确认 键"
                               -button"确认" -button"确认" 
                                -defaultButton"确认" -cancelButton"取消" -dismissString "取消"`;
     if($d=="确认")
       { error "报错了吧！";  }
     if($d=="取消")
       { error "取消也报错！";  }
}


global proc eyeBallSwitchHelp()
{
     string $d = `confirmDialog -title"帮助说明" 
								-message"如有报错问题请联系：\n设置组：陈嘉伟"
                                -button"OK" 
                                -cancelButton"OK" `;    
}