
global proc SK_HHFrameChe()
{
    string $filename=`file -q -sn -shn`;
    string $buff[];
    tokenize $filename "_" $buff;
    string $EQ="E"+$buff[1];
    string $SE=$buff[2];
    string $startframe=`playbackOptions -q -min`;
    string $endframe =`playbackOptions -q -max`;
    int  $fileId=`fopen "Z:\\Projects\\Strawberry\\Strawberry_Scratch\\TD\\frames_sk3\\EP303_frames list.csv" "r"`;
    while ( !`feof $fileId` ) 
    {
        string $line = `fgetline $fileId`;
        $line = strip($line);
        string $buf[];
        tokenize $line "," $buf;
        if ($EQ ==$buf[0]&&$SE == $buf[1])
        {
            if($buf[2]!=$startframe ||$buf[3] != $endframe)
            {
		float $stars = $buf[2];
		int $star=$stars-12;
		float $ends = $buf[3];
		int $end=$ends+12;
		playbackOptions -minTime $stars -animationStartTime $star;
		playbackOptions -maxTime $ends -animationEndTime $end;
		file -save -type "mayaBinary";
		string $startframenew=`playbackOptions -q -min`;
		string $endframenew =`playbackOptions -q -max`;
		print ("开始帧数="+$startframenew+""+"结束帧数="+$endframenew);
            }
            else
            {
                print "帧数正确";
            }
        }
    }
    fclose $fileId;
}

/*
global proc SK_HHFrameChe()
{
    string $startframe=`playbackOptions -q -min`;
    string $endframe =`playbackOptions -q -max`;
    print $startframe;
    print $endframe;

}
*/