global proc ezAnimCopyCurve()
{
	string $master[] = `ls -sl`;

	//string $buff[];
	//string $preCopy,$prePaste;
	
	string $preCopy = `substring $master[0] 1 (size($master[0])-6)`;
	string $prePaste = `substring $master[1] 1 (size($master[1])-6)`;
	
	/*int $num = `tokenize $master[0] ":" $buff`;
	if ($num == 1)
		$preCopy = "";
	else if ($num == 2)
		$preCopy = ($buff[0]+":");

	int $num = `tokenize $master[1] ":" $buff`;
	if ($num == 1)
		$prePaste = "";
	else if ($num == 2)
		$prePaste = ($buff[0]+":");*/

	
	string $copySet = $preCopy + "set";
	string $copyFset = $preCopy + "facial_set";
	string $copyAset = $preCopy + "accessory_set";
	string $source[];
	if (`objExists $copyFset`)
		$source = `sets -query $copySet $copyFset`;
	if (`objExists $copyAset`)
		$source = `sets -query $copySet $copyFset $copyAset`;

	string $pasteSet = $prePaste + "set";
	string $pasteFset = $prePaste + "facial_set";
	string $pasteAset = $prePaste + "accessory_set";
	string $dest[];
	if (`objExists $pasteFset`)
		$dest = `sets -query $pasteSet $pasteFset`;
	if (`objExists $pasteAset`)
		$dest = `sets -query $pasteSet $pasteFset $pasteAset`;

	for ($obj in $source)
	{
		string $paste = `substitute $preCopy $obj $prePaste`;
		for ($destObj in $dest )
		{
			if ($destObj == $paste )
			{
				//print ($dest+"\n");
				string $attrs[] = `listAttr -keyable -o $obj`;
				for ($attr in $attrs)
				{
					float $value = `getAttr ($obj+"."+$attr)`;
					if (`objExists ($destObj+"."+$attr)`)
						setAttr ($destObj+"."+$attr) $value;
				}
				if (`copyKey $obj`)
				{
					pasteKey -o "replaceCompletely" $destObj;
				}
			}
		}
	}

}