global proc ezEffect_jazari()
{
	string $master[] = `ls "*:cc0120jazari_MASTER"`;
	string $geo[] = `ls "*:cc0120jazari_GEO"`;

	select -r $geo[0];
	select -add $master[0] ;
	enableIsolateSelect modelPanel4 1;
	isolateSelect -state 0 modelPanel4;
	isolateSelect -state 1 modelPanel4;

	string $buff[];
	tokenize $master[0] ":" $buff;
	string $pre = $buff[0];
	
	select -r ($buff[0]+":cc0120jazari_hairSystem1") ;
	setAttr ($buff[0]+":cc0120jazari_hairSystemShape1.simulationMethod") 2;

	select -r ($buff[0]+":cc0120jazari_braidshair1") ($buff[0]+":cc0120jazari_braidshair2") ($buff[0]+":cc0120jazari_braidshair3") ($buff[0]+":cc0120jazari_braidshair4")
		($buff[0]+":cc0120jazari_braidshair5") ($buff[0]+":cc0120jazari_braidshair6") ($buff[0]+":cc0120jazari_braidshair7") ($buff[0]+":cc0120jazari_braidshair8")
		($buff[0]+":cc0120jazari_braidshair9") ($buff[0]+":cc0120jazari_braidshair10") ($buff[0]+":cc0120jazari_braidshair11") ($buff[0]+":cc0120jazari_braidshair12")
		($buff[0]+":cc0120jazari_braidshair13") ($buff[0]+":cc0120jazari_braidshair14") ($buff[0]+":cc0120jazari_braidshair15") ($buff[0]+":cc0120jazari_braidshair_left1")
		($buff[0]+":cc0120jazari_braidshair_left2") ($buff[0]+":cc0120jazari_braidshair_left3") ($buff[0]+":cc0120jazari_braidshair_left4") ($buff[0]+":cc0120jazari_braidshair_left5")
		($buff[0]+":cc0120jazari_braidshair_left6") ($buff[0]+":cc0120jazari_braidshair_left7") ($buff[0]+":cc0120jazari_braidshair_left8") ($buff[0]+":cc0120jazari_braidshair_left9")
		($buff[0]+":cc0120jazari_braidshair_left10") ($buff[0]+":cc0120jazari_braidshair_left11") ($buff[0]+":cc0120jazari_braidshair_left12") ($buff[0]+":cc0120jazari_braidshair_left13")
		($buff[0]+":cc0120jazari_braidshair_left14") ($buff[0]+":cc0120jazari_braidshair_left15") ($buff[0]+":cc0120jazari_braidshair_left16") ($buff[0]+":cc0120jazari_braidshair_left17")
		($buff[0]+":cc0120jazari_braidshair_left18") ($buff[0]+":curve3_joint_17") ($buff[0]+":effector1") ($buff[0]+":follicle1") ($buff[0]+":curve1") ($buff[0]+":cc0120jazari_braidshair_right1")
		($buff[0]+":cc0120jazari_braidshair_right2") ($buff[0]+":cc0120jazari_braidshair_right3") ($buff[0]+":cc0120jazari_braidshair_right4") ($buff[0]+":cc0120jazari_braidshair_right5")
		($buff[0]+":cc0120jazari_braidshair_right6") ($buff[0]+":cc0120jazari_braidshair_right7") ($buff[0]+":cc0120jazari_braidshair_right8") ($buff[0]+":cc0120jazari_braidshair_right9")
		($buff[0]+":cc0120jazari_braidshair_right10") ($buff[0]+":cc0120jazari_braidshair_right11") ($buff[0]+":cc0120jazari_braidshair_right12") ($buff[0]+":cc0120jazari_braidshair_right13")
		($buff[0]+":cc0120jazari_braidshair_right14") ($buff[0]+":cc0120jazari_braidshair_right15") ($buff[0]+":cc0120jazari_braidshair_right16") ($buff[0]+":cc0120jazari_braidshair_right17")
		($buff[0]+":cc0120jazari_braidshair_right18") ($buff[0]+":cc0120jazari_braidshair_right19") ;

	playbackOptions -e -min 0;
	doBakeSimulationArgList 3 { "1","0","10","1","0","0","1","1","0","1","animationList","0" };

	select -r ($buff[0]+":cc0120jazari_hairSystem1") ;
	setAttr ($buff[0]+":cc0120jazari_hairSystemShape1.simulationMethod") 0;

	playbackOptions -e -min 43;
	select -cl;
	isolateSelect -state 0 modelPanel4;
}