global proc ezEffect_roxanne_hair()
{
	currentTime -31;
	file -import -type "mayaAscii" -rpr "roxanne_hair_proxy" -options "v=0;p=17" "//file-cluster/GDC/Resource/Groups/Production/3DEffect/zzw/banizzy/roxanne_hair_proxy.ma";

	string $roxanne_hair[] = `ls "*:roxanne_MASTER"`;
	string $buffer[];
	tokenize $roxanne_hair[0] ":" $buffer;
	string $pref = $buffer[0];

	select -r hair_org ;
	select -tgl ($pref+":roxanne_head") ;
	parent;

	currentTime 0;

	duplicate -rr;
	rename roxanne_hair_sim;
	parent -w;
	makeIdentity -apply true -t 1 -r 1 -s 1 -n 0;

	select -r hair_org ;
	setAttr "hair_org.visibility" 0;

	//select -r ($pref+":roxanne_c_hi_hair") ;
	//parent -w ;

	//create hair sim;
	select -r roxanne_hair_sim ;
	syCreateCloth;

	select -r syCloth1ShapeTrf ;
	syCreateForce syGravity;

	select -r syCloth1ShapeTrf ;
	syCreateForce syDamp;

	select -r syCloth1ShapeTrf ;
	select -tgl ($pref+":roxanne_c_hi_bodyfx") ;
	syCreateCollider;

	select -r syCloth1ShapeTrf ;
	select -tgl ($pref+":roxannea_c_hi_cloth_1") ;
	syCreateCollider;

	select -r syCloth1ShapeTrf.vtx[98:142] syCloth1ShapeTrf.vtx[227:262] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[76:80] syCloth1ShapeTrf.vtx[85:91] syCloth1ShapeTrf.vtx[96:97] syCloth1ShapeTrf.vtx[209:212] syCloth1ShapeTrf.vtx[216:221] syCloth1ShapeTrf.vtx[225:226] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[58:69] syCloth1ShapeTrf.vtx[74:75] syCloth1ShapeTrf.vtx[194:203] syCloth1ShapeTrf.vtx[207:208] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[44:57] syCloth1ShapeTrf.vtx[182:193] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[30:43] syCloth1ShapeTrf.vtx[170:181] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[16:29] syCloth1ShapeTrf.vtx[158:169] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[0:15] syCloth1ShapeTrf.vtx[143:157] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[92:95] syCloth1ShapeTrf.vtx[222:224] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[81:84] syCloth1ShapeTrf.vtx[213:215] ;
	select -add hair_org ;
	syCreateMimic;

	select -r syCloth1ShapeTrf.vtx[70:73] syCloth1ShapeTrf.vtx[204:206] ;
	select -add hair_org ;
	syCreateMimic;

	setAttr "syCloth1.massDensity" 1.1;
	setAttr "syCloth1.stretchStiff" 35;
	setAttr "syCloth1.shearStiff" 2;
	setAttr "syCloth1.bendStiff" 1;
	setAttr "syCloth1.stretchDamp" 0.35;
	setAttr "syCloth1.shearDamp" 0.002;
	setAttr "syCloth1.bendDamp" 0.001;
	setAttr "syGravity1.inGravityY" -0.156;
	setAttr "syDamp1.inDamp" 0.003;
	setAttr "syCollide1.friction" 0.15;
	setAttr "syCollide1.envelope_ext" 0.15;
	setAttr "syCollide2.envelope_ext" 0.03;
	setAttr "syMimic1.stiff" 1;
	setAttr "syMimic1.damp" 0.1;
	setAttr "syMimic2.stiff" 0.9;
	setAttr "syMimic2.damp" 0.09;
	setAttr "syMimic3.distance" 0;
	setAttr "syMimic3.stiff" 0.9;
	setAttr "syMimic3.damp" 0.1;
	setAttr "syMimic4.distance" 0.01;
	setAttr "syMimic4.stiff" 0.03;
	setAttr "syMimic4.damp" 0.003;
	setAttr "syMimic5.distance" 0.02;
	setAttr "syMimic5.stiff" 0.002;
	setAttr "syMimic5.damp" 0.0002;
	setAttr "syMimic6.active" 0;
	setAttr "syMimic7.active" 0;
	setAttr "syMimic8.distance" 0.0001;
	setAttr "syMimic8.stiff" 0.5;
	setAttr "syMimic8.damp" 0.05;
	setAttr "syMimic9.distance" 0.05;
	setAttr "syMimic9.stiff" 0.3;
	setAttr "syMimic9.damp" 0.03;
	setAttr "syMimic10.distance" 0.05;
	setAttr "syMimic10.stiff" 0.1;
	setAttr "syMimic10.damp" 0.01;

	select -r syCloth1Trs syCloth1ShapeTrf syGravity1Trs syDamp1Trs syCollide1Trs syCollide2Trs syMimic1Trs syMimic2Trs syMimic3Trs syMimic4Trs syMimic5Trs syMimic6Trs syMimic7Trs syMimic8Trs syMimic9Trs syMimic10Trs ;
	group; xform -os -piv 0 0 0;
	rename roxanne_syhair;


	string $fileName = `file -q -sn -shn`;
	string $buff[];
	tokenize $fileName "_" $buff;
	string $floder = $buff[1]+"_"+$buff[2];
	sysFile -md ("D:/sy/BI/"+$floder);

	string $syCloth[] = `ls -type syCloth`;
	for ($cloth in $syCloth)
	{
		string $cacheName = `substring $cloth 1 (size($cloth)-9)`;
		setAttr -type "string" ($cloth+".cacheName") ("D:/sy/BI/"+$floder+"/"+$cacheName);
	}
}


global proc ezEffect_roxanne_skirt()
{
	//create roxanne cloth

	currentTime -31;

	file -i "//file-cluster/GDC/Resource/Groups/Production/3DEffect/zzw/banizzy/roxanne_cloth.mb";

	string $roxanne[] = `ls "*:roxanne_MASTER"`;
	string $buffer[];
	tokenize $roxanne[0] ":" $buffer;
	string $pref = $buffer[0];

	select -r ($pref+":roxanne_c_hi_shoes_3") ;
	select -tgl ($pref+":roxanne_c_hi_shoes_4") ;
	select -tgl ($pref+":roxanne_c_hi_shoes_2") ;
	select -tgl ($pref+":roxanne_c_hi_shoes_1") ;
	CombinePolygons;
	rename short_collison;

	select -r roxanne_cloth_group ;
	parent roxanne_cloth_group ($pref+":roxanne_MASTER") ;


	currentTime 0;

	select -r roxanne_cloth_group ;
	parent -w;

	select -r roxanne_c_hi_skirt ;
	syCreateCloth;
	select -r syCloth1ShapeTrf ;
	rename roxanne_cloth1;
	rename "syCloth1Shape" "roxanne_syCloth1Shape";
	select -r syCloth1Trs ;
	rename "syCloth1Trs" "roxanne_syCloth1Trs";
	rename "syCloth1" "   roxanne_syCloth1";

	syCreateForce syGravity;
	rename "syGravity1Trs" "roxanne_syGravity1Trs";
	rename "syGravity1" "   roxanne_syGravity1";

	select -r roxanne_cloth1.vtx[80:119] roxanne_cloth1.vtx[200:219] roxanne_cloth1.vtx[483] roxanne_cloth1.vtx[488] roxanne_cloth1.vtx[492] roxanne_cloth1.vtx[496] roxanne_cloth1.vtx[500] roxanne_cloth1.vtx[504] roxanne_cloth1.vtx[508] roxanne_cloth1.vtx[512] roxanne_cloth1.vtx[516] roxanne_cloth1.vtx[520] roxanne_cloth1.vtx[524] roxanne_cloth1.vtx[528] roxanne_cloth1.vtx[532] roxanne_cloth1.vtx[536] roxanne_cloth1.vtx[540] roxanne_cloth1.vtx[544] roxanne_cloth1.vtx[548] roxanne_cloth1.vtx[552] roxanne_cloth1.vtx[556] roxanne_cloth1.vtx[559:639] roxanne_cloth1.vtx[820:859] ;select -tgl ($pref+":roxanne_c_hi_leg") ;
	syCreatePin;
	select -r syPin1Trs ;
	rename "syPin1Trs" "roxanne_syPin1Trs";
	rename "syPin1" "   roxanne_syPin1";

	select -r roxanne_cloth1 ;
	syCreateForce syDamp;
	select -r syDamp1Trs ;
	rename "syDamp1Trs" "roxanne_syDamp1Trs";
	rename "syDamp1" "  roxanne_syDamp1";

	select -r roxanne_cloth1 ;
	select -add ($pref+":roxanne_c_hi_bodyfx") ;
	syCreateCollider;
	select -r syCollide1Trs ;
	rename "syCollide1Trs" "roxanne_syCollide1Trs_body";
	rename "syCollide1" "roxanne_syCollide1_body";

	select -r roxanne_cloth1 ;
	select -tgl short_collison;
	syCreateCollider;
	select -r syCollide1Trs ;
	rename "syCollide1Trs" "roxanne_syCollide1Trs_short";
	rename "syCollide1" "   roxanne_syCollide1_short";

	setAttr "roxanne_syCloth1.precision" 0.0001;
	setAttr "roxanne_syCloth1.massDensity" 1.2;
	setAttr "roxanne_syCloth1.stretchStiff" 22;
	setAttr "roxanne_syCloth1.shearStiff" 10.5;
	setAttr "roxanne_syCloth1.bendStiff" 5.2;
	setAttr "roxanne_syCloth1.stretchDamp" 0.208;
	setAttr "roxanne_syCloth1.shearDamp" 0.1;
	setAttr "roxanne_syCloth1.bendDamp" 0.1;
	setAttr "roxanne_syCloth1.selfEnvelope" 0.05;
	setAttr "roxanne_syGravity1.inGravityY" -0.155;
	setAttr "roxanne_syDamp1.inDamp" 0.010425;
	setAttr "roxanne_syCollide1_body.bouncing" 0.05;
	setAttr "roxanne_syCollide1_body.friction" 0.02;
	setAttr "roxanne_syCollide1_body.envelope_ext" 0.1;
	setAttr "roxanne_syCollide1_short.bouncing" 0.05;
	setAttr "roxanne_syCollide1_short.friction" 0.02;
	setAttr "roxanne_syCollide1_short.envelope_ext" 0.1;

	syClothUpdateFileName roxanne_syCloth1.cacheName "D:/sy/BI/111" "";

	select -r roxanne_syCloth1Trs roxanne_cloth1 roxanne_syGravity1Trs roxanne_syPin1Trs roxanne_syDamp1Trs roxanne_syCollide1Trs_body roxanne_syCollide1Trs_short ;
	group;
	rename "group1" "roxanne_skirt_group";

	string $fileName = `file -q -sn -shn`;
	string $buff[];
	tokenize $fileName "_" $buff;
	string $floder = $buff[1]+"_"+$buff[2];
	sysFile -md ("D:/sy/BI/"+$floder);

	string $syCloth[] = `ls -type syCloth`;
	for ($cloth in $syCloth)
	{
		string $cacheName = `substring $cloth 1 (size($cloth)-9)`;
		setAttr -type "string" ($cloth+".cacheName") ("D:/sy/BI/"+$floder+"/"+$cacheName);
	}
}
