/// Copyright (C) 2000-2007 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2007/02/26
///
/// Description: ben&izzy项目设置环节自动添加表情控制器连接BlendShape的表达式
///



global proc ezImportBlendshape()
{
	string $master[] = `ls "*MASTER"`;
	if (!`objExists $master[0]`)
		error "角色没有MASTER，请检查";
	string $buffer[];
	tokenize $master[0] "_" $buffer;
	string $char = $buffer[0];


	string $blendshape[] = `ls -type blendShape ($char + "_blendShape")`;
	if (!`objExists $blendshape[0]`)
		error "没有正确的BlendShape，请检查";
	if (`objExists ($char + "_facial_expression")`)
		error ("已存在名为"+$char+"_facial_expression的表达式，请检查");
	
	
	/*
	string $noVoices[]={"gaurda","gaurdb","roxanne","incidentala","incidentalb","incidentalc","incidentald","incidentale","incidentalf"
				,"incidentalg","incidentalh","incidentali","incidentalj","qifti","khalf","cc0044magiciana","cc0045magiciana","cc0053monkey"
				,"cc0054sheep","cc0055shepard"
				,"cc0061sindbad","cc0080sailorA","cc0082sailorC","cc0083sailorD","cc0084sailorE"
				,"cc0093euroinca","cc0094euroincb","cc0095euroincc","cc0096euroincd","cc0097euroince"
				,"cc0098kharainca","cc0099kharaincb","cc0100kharaincc","cc0101kharaincd","cc0102kharaince"};//不说话角色名单
	int $adjVoices = 0;
	for ($temp in $noVoices)
	{
		if (`gmatch $char $temp`)  $adjVoices = 1;
	}
	string $noMix[]={"incidentala","incidentalb","incidentalc","incidentald","incidentale","incidentalf","incidentalg","incidentalh","incidentali","incidentalj"
				,"benb"
				,"cc0093euroinca","cc0094euroincb","cc0095euroincc","cc0096euroincd","cc0097euroince"
				,"cc0098kharainca","cc0099kharaincb","cc0100kharaincc","cc0101kharaincd","cc0102kharaince"};//没有综合表情名单
	int $adjMix = 0;
	for ($temp in $noMix)
	{
		if (`gmatch $char $temp`)   $adjMix = 1;
	}
	*/


	//all
	string $noVoices[]={"cc0131dido","cc0132pygmalion","cc0151ibnsina","cc0152chamberlain","cc0161pearldiver","cc0171biruni","cc0172officer","cc0192securityguard"
						,"cc0191equestrianadmin","cc0193lysippos","cc0201ibnbatouta","cc0202indianguya"};
	
	int $adjVoices = 1;
	int $adjMix = 1;
	for ($temp in $noVoices)
	{
		if (`gmatch $char $temp`)  
		{
			$adjVoices = 0; $adjMix = 0;
		}
	}


	ezImportFacialCurve($char,$adjVoices,$adjMix);

	string $EXP = ezFacialExp($char,$adjVoices,$adjMix);

	expression -s $EXP  -o "" -ae 1 -uc all -n ($char + "_facial_expression");
	parent ($char+"_Facial_Curve") ($char+"_head");
	
	
	setAttr ($char+"_Facial_Curve.tx") -4.36;
	setAttr ($char+"_Facial_Curve.ty") -9.7;
	setAttr ($char+"_Facial_Curve.tz") 0;
	setAttr ($char+"_Facial_Curve.sx") 0.36;
	setAttr ($char+"_Facial_Curve.sy") 0.36;
	setAttr ($char+"_Facial_Curve.sz") 0.36;
}

global proc  ezImportFacialCurve(string $char,int $adjVoices,int $adjMix)
{
	string $facialCurve = (`getenv "DEV_PATH"` + "/Maya/Import/BenAndIzzy/facialPland.mb");
	file -import -type "mayaBinary" -ra true -rpr $char -options "v=0"  -pr $facialCurve;
	if ($adjVoices == 1)
	{
//		setAttr ($char+"_EoShape.template") 1;
		setAttr ($char+"_UShape.template") 1;
		setAttr ($char+"_MShape.template") 1;
		setAttr ($char+"_FVShape.template") 1;
		setAttr ($char+"_OOOShape.template") 1;
		setAttr ($char+"_eetCShape.template") 1;
		setAttr ($char+"_chShape.template") 1;
		setAttr ($char+"_LShape.template") 1;
		setAttr ($char+"_IShape.template") 1;
	}
	if ($adjMix == 1)
	{
		setAttr ($char+"_mouth_control_happyShape.template") 1;
		setAttr ($char+"_mouth_control_angrySurprisedShape.template") 1;
		setAttr ($char+"_mouth_control_shockedConpusedShape.template") 1;
		setAttr ($char+"_mouth_control_openSadESShape.template") 1;
	}
	setAttr ($char+"_eyes_close_control.template") 1;
	setAttr ($char+"_eight_brow_right_control.template") 1;
	setAttr ($char+"_eight_brow_left_control.template") 1;
	setAttr ($char+"_eyes_close_control1.template") 1;
	setAttr ($char+"_mouth_control_sad.template") 1;

}

global proc string ezFacialExp(string $char,int $adjVoices,int $adjMix)
{
	string $blends[] = `ls -type blendShape`;
	string $leftBl;
	string $rightBl;
	for ($blend in $blends)
	{
		if (`objExists ($blend + "." + $char + "_L_hi_brows_sad")`)
			$leftBl = $blend;
		if (`objExists ($blend + "." + $char + "_R_hi_brows_sad")`)
			$rightBl = $blend;
	}
	
	
	
	string $EXP = "// Ctrl_L_Lids \n";
	$EXP += $char+"_LwrLid_left.rotateX=clamp(-30,15,"+$char+"_eyeJoint_left.rotateX*0.2+clamp(0,40,"+$char+"_eyeJoint_left.rotateX/2))+clamp(-5,12,"
		+$char+"_Ctrl_L_Lids.translateX*15); \n ";
	$EXP += $char+"_LwrLid_left.rotateY="+$char+"_eyeJoint_left.rotateY * 0.3; \n";
	$EXP += $char+"_UprLid_A_left.rotateX=clamp(-70,("+$char+"_LwrLid_left.rotateX+14)+(clamp(-1,0,-"+$char+"_Ctrl_L_Lids.translateX)*10),"
		+$char+"_eyeJoint_left.rotateX+(clamp(-1,0.25,"+$char+"_Ctrl_L_Lids.translateY))*70+((-clamp(-1,-0.25,-"+$char+"_Ctrl_L_Lids.translateY)-0.25)*1.34)*("
		+$char+"_LwrLid_left.rotateX+40-"+$char+"_eyeJoint_left.rotateX)); \n";
	$EXP += $char+"_UprLid_A_left.rotateY = "+$char+"_eyeJoint_left.rotateY * 0.3;\n";
	
	$EXP += "// Ctrl_R_Lids \n";
	$EXP += $char+"_LwrLid_right.rotateX = clamp(-30, 15, "+$char+"_eyeJoint_right.rotateX * 0.2 + clamp(0, 40,"+$char+"_eyeJoint_right.rotateX / 2)) + clamp(-5, 12, "
		+$char+"_Ctrl_R_Lids.translateX * 15); \n";
	$EXP +=	$char+"_LwrLid_right.rotateY = "+$char+"_eyeJoint_right.rotateY * 0.3; \n";
	$EXP += $char+"_UprLid_A_right.rotateX = clamp(-70, ("+$char+"_LwrLid_right.rotateX + 14) + (clamp(-1, 0, -"+$char+"_Ctrl_R_Lids.translateX) * 10), "
		+$char+"_eyeJoint_right.rotateX + (clamp(-1, 0.25, "+$char+"_Ctrl_R_Lids.translateY)) * 70 + ((-clamp(-1, -0.25, -"
		+$char+"_Ctrl_R_Lids.translateY) - 0.25) * 1.34) * ("+$char+"_LwrLid_right.rotateX + 40 - "+$char+"_eyeJoint_right.rotateX)); \n";
	$EXP += $char+"_UprLid_A_right.rotateY = "+$char+"_eyeJoint_right.rotateY * 0.3; \n";

	
	$EXP += "// T_L \n";
	$EXP += $char+"_tongue2.rotateZ = 298.531 * clamp(0, 0.2, "+$char+"_T_L.translateY);\n";
	$EXP += $char+"_tongue3.rotateZ = -350 * clamp(0, 0.2, -"+$char+"_T_L.translateY) + 289.808 * clamp(0, 0.2, "+$char+"_T_L.translateY);\n";
	$EXP += $char+"_tongue4.rotateZ = -350 * clamp(0, 0.2, -"+$char+"_T_L.translateY) + 139.716 * clamp(0, 0.2, "+$char+"_T_L.translateY);\n";
	$EXP += $char+"_tongue5.rotateZ = -350 * clamp(0, 0.2, -"+$char+"_T_L.translateY) + 360 * clamp(0, 0.2, "+$char+"_T_L.translateY);\n";


	$EXP += "// L_sneer\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_mouth_sneer = clamp(0, 1, -"+$char+"_L_sneer.translateX + "+$char+"_L_sneer.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_mouth_sad = clamp(0, 1, "+$char+"_L_sneer.translateX + "+$char+"_L_sneer.translateY*0.4 );\n";


	$EXP += "// R_sneer \n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_mouth_sneer = clamp(0, 1, "+$char+"_R_sneer.translateX + "+$char+"_R_sneer.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_mouth_sad = clamp(0, 1, -"+$char+"_R_sneer.translateX + "+$char+"_R_sneer.translateY*0.4 );\n";


	$EXP += "// L_Smile_Sad \n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_mouth_smile = 5.0 * clamp(0, 0.2, "+$char+"_L_Smile_Sad.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_mouth_angry = 5.0 * clamp(0, 0.2, -"+$char+"_L_Smile_Sad.translateY);\n";


	$EXP += "// R_Smile_Sad\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_mouth_smile = 5.0 * clamp(0, 0.2, "+$char+"_R_Smile_Sad.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_mouth_angry = 5.0 * clamp(0, 0.2, -"+$char+"_R_Smile_Sad.translateY);\n";


	$EXP += "// Lip_In_Kiss \n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_lipin = 5 * clamp(0, 0.2, -"+$char+"_Lip_In_Kiss.translateY);\n";
	if ($adjVoices == 0)
		$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_kiss = 5 * clamp(0, 0.2, "+$char+"_Lip_In_Kiss.translateY);\n";


	$EXP += "// Left_Eye \n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_brow_surprise = clamp(0, 1, ("+$char+"_Left_Eye.translateX + "+$char+"_Left_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_brow_down = clamp(0, 1, ("+$char+"_Left_Eye.translateX - "+$char+"_Left_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_brow_angry = clamp(0, 1, (-"+$char+"_Left_Eye.translateX - "+$char+"_Left_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_L_hi_brow_sad = clamp(0, 1, (-"+$char+"_Left_Eye.translateX + "+$char+"_Left_Eye.translateY) / 2);\n";


	$EXP += "// Right_Eye \n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_brow_surprise = clamp(0, 1, (-"+$char+"_Right_Eye.translateX + "+$char+"_Right_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_brow_down = clamp(0, 1, (-"+$char+"_Right_Eye.translateX - "+$char+"_Right_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_brow_angry = clamp(0, 1, ("+$char+"_Right_Eye.translateX  - "+$char+"_Right_Eye.translateY) / 2);\n";
	$EXP += $char+"_blendShape."+$char+"_R_hi_brow_sad = clamp(0, 1, ("+$char+"_Right_Eye.translateX + "+$char+"_Right_Eye.translateY) / 2);\n";


	$EXP += "// CtrlX_Lips\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_lowlipdn = clamp(0, 1, "+$char+"_CtrlX_Lips.translateX);\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_lowliproll = clamp(0, 1, -"+$char+"_CtrlX_Lips.translateX);\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_upliproll = clamp(0, 1, -"+$char+"_CtrlX_Lips.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_uplipup = clamp(0, 1, "+$char+"_CtrlX_Lips.translateY);\n";


	$EXP += "// Lip_Twist_Up_Down\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_uplipout = clamp(0, 1, "+$char+"_Lip_Twist_Up_Down.translateY);\n";
	$EXP += $char+"_blendShape."+$char+"_C_hi_mouth_lowlipout = clamp(0, 1, "+$char+"_Lip_Twist_Up_Down.translateX);\n";


	$EXP += "//phoneme \n";
	if ($adjVoices == 0)
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_extremeopen = 2.5 * "+$char+"_Eo.translateY; // extreme_open \n";
	if ($adjVoices == 0)
	{
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_o = 2.5 * "+$char+"_OOO.translateY; //OOO\n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_vf = 2.5 * "+$char+"_FV.translateY; //FV\n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_mb = 2.5 * "+$char+"_M.translateY; // M \n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_ooqu = 2.5 * "+$char+"_U.translateY; // U \n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_i = 2.5 * "+$char+"_I.translateY; // I \n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_l = 2.5 * "+$char+"_L.translateY; // L \n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_ch = 2.5 * "+$char+"_ch.translateY; // ch\n";
		$EXP += $char+"_blendShape."+$char+"_C_hi_phoneme_eet = 2.5 * "+$char+"_eetC.translateY; // eet \n";
	}


	if ($adjMix == 0)
	{
		$EXP += "//face_add \n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_happy = 5*clamp(0, 0.2, "+$char+"_mouth_control_happy.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_happy = 5*clamp(0, 0.2, "+$char+"_mouth_control_happy.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_veryhappy = 5*clamp(0, 0.2, -"+$char+"_mouth_control_happy.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_veryhappy = 5*clamp(0, 0.2, -"+$char+"_mouth_control_happy.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_angry = 5*clamp(0, 0.2, "+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_angry = 5*clamp(0, 0.2, "+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_surprise = 5*clamp(0, 0.2, -"+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_surprise = 5*clamp(0, 0.2, -"+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_shocked = 5*clamp(0, 0.2, "+$char+"_mouth_control_shockedConpused.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_shocked = 5*clamp(0, 0.2, "+$char+"_mouth_control_shockedConpused.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_confused = 5*clamp(0, 0.2, -"+$char+"_mouth_control_shockedConpused.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_confused = 5*clamp(0, 0.2, -"+$char+"_mouth_control_shockedConpused.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_openmouthsad = 5*clamp(0, 0.2, "+$char+"_mouth_control_openSadES.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_openmouthsad = 5*clamp(0, 0.2, "+$char+"_mouth_control_openSadES.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_extremelyshocked = 5*clamp(0, 0.2, -"+$char+"_mouth_control_openSadES.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_extremelyshocked = 5*clamp(0, 0.2, -"+$char+"_mouth_control_openSadES.translateY);\n";
//		$EXP +=	$char+"_blendShape."+$char+"_C_hi_phoneme_ch = 2.5*clamp(0, 0.4, "+$char+"_ch.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_mouth_sad = 5*clamp(0, 0.2, "+$char+"_mouth_control_sad.translateY);\n";
		$EXP +=	$char+"_blendShape."+$char+"_C_hi_brow_sad = 5*clamp(0, 0.2, "+$char+"_mouth_control_sad.translateY);\n";

		$EXP +=	$leftBl+"."+$char+"_L_hi_brows_sad = clamp(0, 1, (-"+$char+"_Left_Eye.translateX + "+$char+"_Left_Eye.translateY) / 2) + 5*clamp(0, 0.2, "
			+$char+"_mouth_control_sad.translateY);\n";
		$EXP +=	$rightBl+"."+$char+"_R_hi_brows_sad = clamp(0, 1, ("+$char+"_Right_Eye.translateX + "+$char+"_Right_Eye.translateY) / 2) + 5*clamp(0, 0.2, "
			+$char+"_mouth_control_sad.translateY);\n";
		$EXP +=	$leftBl+"."+$char+"_L_hi_brows_surprise = clamp(0, 1, ("+$char+"_Left_Eye.translateX + "+$char+"_Left_Eye.translateY) / 2) + 5*clamp(0, 0.2, -"
			+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$rightBl+"."+$char+"_R_hi_brows_surprise = clamp(0, 1, (-"+$char+"_Right_Eye.translateX + "+$char+"_Right_Eye.translateY) / 2) + 5*clamp(0, 0.2, -"
			+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$leftBl+"."+$char+"_L_hi_brows_angry = clamp(0, 1, (-"+$char+"_Left_Eye.translateX + -"+$char+"_Left_Eye.translateY) / 2) + 5*clamp(0, 0.2, "
			+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$rightBl+"."+$char+"_R_hi_brows_angry = clamp(0, 1, ("+$char+"_Right_Eye.translateX + -"+$char+"_Right_Eye.translateY) / 2) + 5*clamp(0, 0.2, "
			+$char+"_mouth_control_angrySurprised.translateY);\n";
		$EXP +=	$leftBl+"."+$char+"_L_hi_brows_down = clamp(0, 1, ("+$char+"_Left_Eye.translateX + -"+$char+"_Left_Eye.translateY) / 2) ;\n";
		$EXP +=	$rightBl+"."+$char+"_R_hi_brows_down = clamp(0, 1, (-"+$char+"_Right_Eye.translateX + -"+$char+"_Right_Eye.translateY) / 2) ;\n";

	}


	$EXP += "\n// Jaw_Rot \n";
	$EXP += $char+"_jaw.rotateZ = -75.0 * "+$char+"_Jaw_Rot.translateX;\n";
	$EXP += $char+"_jaw.rotateX = 130.0 * "+$char+"_Jaw_Rot.translateY+"+$char+"_eetC.translateY*(8/0.4)+"+$char+"_I.translateY*(14/0.4)+"
		+$char+"_L.translateY*(5.466/0.4)+"+$char+"_OOO.translateY*(7.326/0.4)+2.5*clamp(0, 0.4, "+$char+"_Eo.translateY)*20.906";
	if ($adjMix == 0)
	{
		$EXP +=	"+5*clamp(0, 0.2, "+$char+"_mouth_control_happy.translateY)*12.8+5*clamp(0, 0.2, -"
			+$char+"_mouth_control_happy.translateY)*19+5*clamp(0, 0.2, -"+$char+"_mouth_control_angrySurprised.translateY)*7.56+5*clamp(0, 0.2, "
			+$char+"_mouth_control_openSadES.translateY)*14.548+5*clamp(0, 0.2, "+$char+"_mouth_control_shockedConpused.translateY)*17.788+5*clamp(0, 0.2, -"
			+$char+"_mouth_control_openSadES.translateY)*23";
	}
	$EXP += ";\n";

/*
	$EXP += "//Teeth_G \n";
	$EXP += $char+"_Lower_Teeth_G.translateZ = clamp(-0.05,0,"+$char+"_mouth_control_openSadES.translateY*0.05/0.2);\n";
*/

	return $EXP;

}