/// Copyright (C) 2000-2007 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2007/02/26
///
/// Description: ben&izzy项目模型环节，检查A模命名工具
///


global proc ezModelAnCheck()
{
	string $polys[]=`ls -type mesh`;

	string $subs[] = `ls -type subdiv`;
	string $meshs[]= stringArrayCatenate($polys,$subs);

	string $nurbsSurface[]= `ls -type nurbsSurface`;
	string $nurbsCurve[] = `ls -type nurbsCurve`;
	string $nurbs[]= stringArrayCatenate ($nurbsCurve,$nurbsSurface);

	string $objs[] = stringArrayCatenate ($meshs,$nurbs);

	string $wrong[];
	for ($obj in $objs )
	{
		string $buf[];
		tokenize $obj "_" $buf;
		if ($buf[2] != "an")
		{
			$wrong[size($wrong)] = $obj;
		}


/*		select -r $obj;
		pickWalk -d up;
		pickWalk -d up;
		string $sl[]=`ls -sl`;
		clear $buf;
		tokenize $sl[0] "_" $buf;
		if ($buf[2] != "an")
		{
			$wrong[size($wrong)] = $obj;
		}
*/

	}

	ezOutputWindowForModelA();
	for ($tem in $wrong)
	{
		ezOutputForModelA "\n";
		ezOutputForModelA $tem;
	}
}


global proc ezOutputWindowForModelA()
{
	if(`window -ex ezOutputWindow`) 
	{
		deleteUI ezOutputWindow;
	}
	window 
		-widthHeight 500 400 
		-sizeable 1 
		-title "Ben&Izzy------以下A模命名错误，请检查"  
		-ret
		ezOutputWindow;

	string $form = `formLayout -numberOfDivisions 100`;

	string $a1 =` scrollField -wordWrap false -editable false ezoutput`;

	formLayout 
		-edit 
		-attachForm $a1 "top"    5
		-attachForm $a1 "bottom" 5
		-attachForm $a1 "left"   5
		-attachForm $a1 "right"  5 
		$form;

	showWindow;
}

global proc ezOutputForModelA(string $out)
{
	scrollField -e -ip 0 -it $out ezoutput;
	setFocus ezoutput;
}
