//////////////////////////////////////////////////////////
//
//	Script Name: slAnimRefenceCurves
//	Verision: 0.01 beta
//	Author: wanshoulong
//	Date Created: 01-28-2008
//	Changed Projcet Date: 
//	Last Updated: 01-28-2008
//	Update/Change this file at: wanshoulong
//	Note:动画环节使用，动画文件打开后动画错误或者丢失
//
//////////////////////////////////////////////////////////

global proc slAnimRefenceCurves()
{
	//string $allAnimCurves[] = `ls -type animCurve`;
	
	string $sets[] = `ls -type objectSet`;
	for ($set in $sets)
	{
		if (endsWith($set,"_TSM2Controls") || endsWith($set,"_set"))
		{
			//print ($set+"\n");
			string $controls[] = `sets -q $set`;
			
			for ($con in $controls)
			{
				string $attrs[] = `listAttr -keyable $con`;
				if (size($attrs))
				{
					//print ("\t----------"+$con+"\n");
					for ($attr in $attrs)
					{
						string $conCurve[] = `listConnections -d false -plugs true -type animCurve ($con + "." + $attr)`;
						if (`objExists $conCurve[0]`)
							disconnectAttr $conCurve[0] ($con + "." + $attr);

						string $animCurve[] = `ls ($con + "_" + $attr + "*")`;
						if (`objExists $animCurve[0]`)
						{
							//print ("\t\t==================="+$animCurve[0]+"\n");
							string $dest[] = `listConnections -s false -d true -plugs true ($animCurve[0] + ".output")`;
							//print $dest[0];
							if (`objExists $dest[0]`)
								disconnectAttr ($animCurve[0] + ".output") $dest[0] ;
							connectAttr  -f ($animCurve[size($animCurve)-1] + ".output") ($con + "." + $attr);
						}
					}
				}
			}

		}
	}

}