global proc slOutputWindow(string $inf)
{
	if(`window -ex slOutputWindow`) 
		deleteUI slOutputWindow;
	
	window 	-widthHeight 500 400 	-sizeable 1 	-title $inf  -ret	slOutputWindow;

		string $tab = `tabLayout -tv false slOutputWindow_tab` ;
			
			string $form = `formLayout -numberOfDivisions 100`;
				string $a1 =` scrollField -wordWrap false -editable false slOutputWindow_scr`;

			formLayout 
				-edit 
				-attachForm $a1 "top"    1
				-attachForm $a1 "bottom" 1
				-attachForm $a1 "left"   1
				-attachForm $a1 "right"  1
				$form;

		tabLayout -edit
			-tl	$form		"Ä¬ÈÏµÄ"
		$tab;
		tabLayout -edit -st	$form $tab;

	showWindow slOutputWindow;
}

global proc slOutput(string $out)
{
	scrollField -e -ip 0 -it $out slOutputWindow_scr;
	setFocus slOutputWindow_scr;
}