global proc s100VRRandomize()
{
	float $minRandF = `floatField -q -v    s100VRminRandFG`;
	float $maxRandF = `floatField -q  -v   s100VRmaxRandFG`;


	string $list[] = `listRelatives -ad -type transform "root_ctrl"` ;


		for ($i = 0 ; $i < size($list) ; $i++)
		{
			if(`gmatch $list[$i] "*_ctrl"`)
			{


			float $rand ;
			float $test = abs($minRandF) + abs($maxRandF) ;
			float $randValue = rand(1) ;
			float $mult = 1 ;
				if  ($randValue < .5 )
					$mult = -1 ;

			float $value = (rand($test) / 2) * $mult ;

			setAttr ($list[$i] + ".rx")  $value ;
						float $mult = 1 ;
				if  ($randValue < .5 )
					$mult = -1 ;
			float $value = (rand($test) / 2) * $mult ;
						float $mult = 1 ;
				if  ($randValue < .5 )
					$mult = -1 ;
			setAttr ($list[$i] + ".ry")  $value ;
						float $mult = 1 ;
				if  ($randValue < .5 )
					$mult = -1 ;
			float $value = (rand($test) / 2) * $mult ;

			setAttr ($list[$i] + ".rz")  $value ;

            }



        }




}


global proc s100VRVRDefautPose()
{

	string $list[] = `listRelatives -ad -type transform "root_ctrl"` ;


		for ($i = 0 ; $i < size($list) ; $i++)
		{
			if(`gmatch $list[$i] "*_ctrl"`)
			{

			setAttr ($list[$i] +".rx") 0 ;
			setAttr ($list[$i] +".ry") 0 ;
			setAttr ($list[$i] +".rz") 0 ;

            }
        }

}