# -*- coding: utf-8 -*-

# Form implementation generated from reading myuis file 'D:\food\dataSearch\_eric4project\FWUI_ToolSearch.myuis'
#
# Created: Wed Apr 17 14:36:29 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ToolSearch(object):
    def setupUi(self, ToolSearch):
        ToolSearch.setObjectName(_fromUtf8("ToolSearch"))
        ToolSearch.resize(482, 369)
        ToolSearch.setWindowTitle(QtGui.QApplication.translate("ToolSearch", "ToolSearch", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(ToolSearch)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.formLayout = QtGui.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.FW_searchKey = QtGui.QLineEdit(self.centralwidget)
        self.FW_searchKey.setMinimumSize(QtCore.QSize(360, 28))
        self.FW_searchKey.setMaximumSize(QtCore.QSize(360, 28))
        self.FW_searchKey.setObjectName(_fromUtf8("FW_searchKey"))
        self.horizontalLayout.addWidget(self.FW_searchKey)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FW_searchButton = QtGui.QPushButton(self.centralwidget)
        self.FW_searchButton.setMinimumSize(QtCore.QSize(90, 30))
        self.FW_searchButton.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FW_searchButton.setFont(font)
        self.FW_searchButton.setText(QtGui.QApplication.translate("ToolSearch", "搜    索", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_searchButton.setObjectName(_fromUtf8("FW_searchButton"))
        self.horizontalLayout_2.addWidget(self.FW_searchButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(90, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.FW_checkPart = QtGui.QCheckBox(self.centralwidget)
        self.FW_checkPart.setMinimumSize(QtCore.QSize(80, 20))
        self.FW_checkPart.setMaximumSize(QtCore.QSize(80, 20))
        self.FW_checkPart.setText(QtGui.QApplication.translate("ToolSearch", "搜【环节】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_checkPart.setObjectName(_fromUtf8("FW_checkPart"))
        self.horizontalLayout_4.addWidget(self.FW_checkPart)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(80, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.FW_checkID = QtGui.QCheckBox(self.centralwidget)
        self.FW_checkID.setMinimumSize(QtCore.QSize(80, 20))
        self.FW_checkID.setMaximumSize(QtCore.QSize(80, 20))
        self.FW_checkID.setText(QtGui.QApplication.translate("ToolSearch", "搜【 I D 】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_checkID.setObjectName(_fromUtf8("FW_checkID"))
        self.horizontalLayout_5.addWidget(self.FW_checkID)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(90, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.FW_infoTable = QtGui.QTableWidget(self.centralwidget)
        self.FW_infoTable.setMinimumSize(QtCore.QSize(450, 180))
        self.FW_infoTable.setMaximumSize(QtCore.QSize(450, 180))
        self.FW_infoTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.FW_infoTable.setObjectName(_fromUtf8("FW_infoTable"))
        self.FW_infoTable.setColumnCount(4)
        self.FW_infoTable.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "【1】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "【2】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "【3】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "【4】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "【5】", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "名称", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "环节", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("ToolSearch", "描述", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_infoTable.setHorizontalHeaderItem(3, item)
        self.FW_infoTable.horizontalHeader().setVisible(True)
        self.horizontalLayout_8.addWidget(self.FW_infoTable)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.FW_movePre = QtGui.QPushButton(self.centralwidget)
        self.FW_movePre.setMinimumSize(QtCore.QSize(135, 25))
        self.FW_movePre.setMaximumSize(QtCore.QSize(135, 25))
        self.FW_movePre.setText(QtGui.QApplication.translate("ToolSearch", "前一页", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_movePre.setObjectName(_fromUtf8("FW_movePre"))
        self.horizontalLayout_9.addWidget(self.FW_movePre)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.FW_movePos = QtGui.QPushButton(self.centralwidget)
        self.FW_movePos.setMinimumSize(QtCore.QSize(135, 25))
        self.FW_movePos.setMaximumSize(QtCore.QSize(135, 25))
        self.FW_movePos.setText(QtGui.QApplication.translate("ToolSearch", "下一页", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_movePos.setObjectName(_fromUtf8("FW_movePos"))
        self.horizontalLayout_9.addWidget(self.FW_movePos)
        self.FW_goInfo = QtGui.QLineEdit(self.centralwidget)
        self.FW_goInfo.setMinimumSize(QtCore.QSize(40, 25))
        self.FW_goInfo.setMaximumSize(QtCore.QSize(40, 25))
        self.FW_goInfo.setObjectName(_fromUtf8("FW_goInfo"))
        self.horizontalLayout_9.addWidget(self.FW_goInfo)
        self.FW_gotoInfo = QtGui.QPushButton(self.centralwidget)
        self.FW_gotoInfo.setMinimumSize(QtCore.QSize(65, 25))
        self.FW_gotoInfo.setMaximumSize(QtCore.QSize(65, 25))
        self.FW_gotoInfo.setText(QtGui.QApplication.translate("ToolSearch", "前进", None, QtGui.QApplication.UnicodeUTF8))
        self.FW_gotoInfo.setObjectName(_fromUtf8("FW_gotoInfo"))
        self.horizontalLayout_9.addWidget(self.FW_gotoInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.FW_infoPrint = QtGui.QLabel(self.centralwidget)
        self.FW_infoPrint.setMinimumSize(QtCore.QSize(400, 20))
        self.FW_infoPrint.setMaximumSize(QtCore.QSize(400, 20))
        self.FW_infoPrint.setText(_fromUtf8(""))
        self.FW_infoPrint.setObjectName(_fromUtf8("FW_infoPrint"))
        self.horizontalLayout_10.addWidget(self.FW_infoPrint)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout)
        ToolSearch.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ToolSearch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ToolSearch.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ToolSearch)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ToolSearch.setStatusBar(self.statusbar)

        self.retranslateUi(ToolSearch)
        QtCore.QMetaObject.connectSlotsByName(ToolSearch)

    def retranslateUi(self, ToolSearch):
        item = self.FW_infoTable.verticalHeaderItem(0)
        item = self.FW_infoTable.verticalHeaderItem(1)
        item = self.FW_infoTable.verticalHeaderItem(2)
        item = self.FW_infoTable.verticalHeaderItem(3)
        item = self.FW_infoTable.verticalHeaderItem(4)
        item = self.FW_infoTable.horizontalHeaderItem(0)
        item = self.FW_infoTable.horizontalHeaderItem(1)
        item = self.FW_infoTable.horizontalHeaderItem(2)
        item = self.FW_infoTable.horizontalHeaderItem(3)

