//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change:梁宇
//	Last Updated: 
//	Description:sk4在工程目录下保存lighting文件
//				
//////////////////////////////////////////////////////////


global proc skSceneSave()
{
		
	string $workspace = `workspace -q -fn`;	
	string $fileNmae = `file -q -sceneName -shortName`;
	
	string $buff[] = stringToStringArray($fileNmae,"_");
	string $project = $buff[0];
	string $EP = $buff[1];
	string $SC = $buff[2];

	string $path = $workspace + "\\scenes\\";

	string $filename = "sk_"+$EP+"_"+$SC+"_lighting_c001.mb";

	file -rename ($path+$filename);
	file -save;		
}






global proc sk4_importlight()
{
	
   
	if(`objExists "LT_CHR"`)
	{
	     delete "LT_CHR";
	}
	file -import -type "mayaBinary" -rpr "chlight" -options "v=0;p=17" "Z:/Projects/Strawberry/Strawberry_Scratch/render/template/light/chlight.mb";


	if(`objExists "LT_CHD"`)
	{
	     delete "LT_CHD";
	}
	file -import -type "mayaBinary" -rpr "chshadow_light" -options "v=0;p=17" "Z:/Projects/Strawberry/Strawberry_Scratch/render/template/light/chshadow_light.mb";


	if(`objExists "LT_HAIR"`)
	{
	     delete "LT_HAIR";
	}
	file -import -type "mayaBinary" -rpr "hairlight" -options "v=0;p=17" "Z:/Projects/Strawberry/Strawberry_Scratch/render/template/light/hairlight.mb";
}