string $unknown[]=`ls -type cacheFile`;
string $aas=`file -q -sn -shn`;
string $buffers[];
$num = `tokenize $aas "_" $buffers`;
string $jishus=$buffers[1];
string $changcis=$buffers[2];
string $lujings=("\\"+"\\"+"FILE-CLUSTER\\gdc\\Projects\\Strawberry\\Project\\data\\episode_"+$jishus+"\\scene_"+$changcis+"\\nClothCache");                    

for($xa in $unknown){
setAttr -type "string" ($xa+".cachePath") $lujings;
}
