global proc  HbAutoHideObject()
{
	select -cl;
	string $questLaye[]=`ls  -type "displayLayer" "HideLayer"`;
	if (`size($questLaye)`==0)
	{

		createDisplayLayer -name "HideLayer" -number 1 -nr;

	}
	setAttr "HideLayer.visibility" 0;

	string $questTempGrps[]=`ls -type "transform" "*_TheAngleTemp"`;
	for ($questTempGrp in $questTempGrps)
	{
		delete $questTempGrp;
	}
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbGetTheRightFrame.py\")");
	string $currentCam = `lookThru -q`;
	select -cl;
	select $currentCam;
	pickWalk -d up;
	string $getTheCamName[]=`ls -sl`;
	string $GetTheFrames[]=`python("questTheFrame()")`;
	string $getTheObject[]=`ls -type "transform" "Tree*_c_*_geo*" "GenericHouse*_a*" "*:Tree*_c_*_geo*" 
                                 "*:GenericHouse*_a*" "ivanhome_c_hi_house*" "*:ivanhome_c_hi_house*" "butchershopext_c_hi_house01"
				 "butchershopext_c_hi_house02" "butchershopext_c_hi_house03" "*:butchershopext_c_hi_house01" 
				 "*:butchershopext_c_hi_house02" "*:butchershopext_c_hi_house03" "cakeryext_c_hi_house" 
				 "*:cakeryext_c_hi_house" "OlsenHomeExt" "*:OlsenHomeExt"
	                         "supermarket_c_hi_house"  "*:supermarket_c_hi_house"  "schoolext_c_hi_geo"  "*:schoolext_c_hi_geo"
				 "gymExt_c_hi_geo" "*:gymExt_c_hi_geo" "lamppost2*" "*:lamppost2*" "Garden_Home" "*:Garden_Home"
				  "barriers_c_hi_geo_*" "*:barriers_c_hi_geo_*"
				 "Soendergade_rock"  "*:Soendergade_rock" "bush_c_lo_geo*"  "*:bush_c_lo_geo*" "TREE01" "*:TREE01"
				 "park" "*:park" "barrier_4_*" "*:barrier_4_*" "pSphere*" 
				 "*Position" "*:*Position" "dustheap_c_hi_group" "*:dustheap_c_hi_group" "OttoHouse" "*:OttoHouse" 
				 "bookshopext_c_hi_house" "*:bookshopext_c_hi_house" "border_c_hi_geo*" "*:border_c_hi_geo*"`;
	for ($TheObject in $getTheObject)
	{
	

		catch(`editDisplayLayerMembers -noRecurse defaultLayer $TheObject`);

	}
	string $showObject[]={};
	for ($GetTheFrame in $GetTheFrames)
	{
		string $buffer[];
		$numTokens = `tokenize $GetTheFrame "-->" $buffer`;
		if ($numTokens!=1)
		{
			int $i=10;
			for ($m=int($buffer[0]);$m<int($buffer[1]);$m++)
			{
				if ($m%$i==1)

				{
					currentTime $m ;

					for($TheObject in $getTheObject)
					{
						string $quest=HbQuestObjInCam($getTheCamName[0],$TheObject);
						if ($quest=="1")
						{
						string $new[]={$TheObject};
						appendStringArray($showObject, $new, 1);

						}
					
					}
				
				
				}
			
			}
		
		}

		if ($numTokens==1)
		{
			currentTime (int($GetTheFrame));

			for($TheObject in $getTheObject)
				{
					string $quest=HbQuestObjInCam($getTheCamName[0],$TheObject);
					if ($quest=="1")
						{
						string $new[]={$TheObject};
						appendStringArray($showObject, $new, 1);
						}
					
				}
		
		}



	}
	for ($TheObject in $getTheObject)
	{
	
		int $found = stringArrayContains($TheObject, $showObject);
		if ($found==0)

		{

			if (`match "group" $TheObject`=="" && `match "all" $TheObject`=="")
			{
				catch(`editDisplayLayerMembers -noRecurse HideLayer $TheObject`);
			}
		}
	}


	string $questTempGrps[]=`ls -type "transform" "*_TheAngleTemp"`;
	for ($questTempGrp in $questTempGrps)
	{
		delete $questTempGrp;
	}

}

//HbAutoHideObject;

global proc string HbQuestObjInCam(string $CamName,string $ObjName)
{

	float $CamPos[]=`xform -q -ws -piv $CamName`;
	float $ObjPos[]=`xform -q -ws -piv $ObjName`;
	float $boundBox[] = `xform -q -ws -boundingBox ($ObjName)`;

	string $questTheTempGrp[]=`ls  -type "transform" ($ObjName+"_TheAngleTemp")`;

	if (`size($questTheTempGrp)`==0)
	{
		group -em -n  ($ObjName+"_TheAngleTemp");
		parent ($ObjName+"_TheAngleTemp") $CamName ;
	}

	setAttr ($ObjName+"_TheAngleTemp.translateX") 0;
	setAttr ($ObjName+"_TheAngleTemp.translateZ") 0;
	setAttr ($ObjName+"_TheAngleTemp.translateY") 0;
	setAttr ($ObjName+"_TheAngleTemp.rotateX") 0;
	setAttr ($ObjName+"_TheAngleTemp.rotateZ") 0;
	setAttr ($ObjName+"_TheAngleTemp.rotateY") 0;
	setAttr ($ObjName+"_TheAngleTemp.scaleX") 0;
	setAttr ($ObjName+"_TheAngleTemp.scaleZ") 0;
	setAttr ($ObjName+"_TheAngleTemp.scaleY") 0;	
	int $i=0;
	int $m=0;
	float $TranlateX[]={$ObjPos[0],(($boundBox[0]+$boundBox[3])/2),(($boundBox[0]+$boundBox[3])/2),$boundBox[0],$boundBox[3],(($boundBox[0]+$boundBox[3])/2)};
	float $TranlateY[]={$ObjPos[1],(($boundBox[4]+$boundBox[1])/2),(($boundBox[4]+$boundBox[1])/2),(($boundBox[4]+$boundBox[1])/2),(($boundBox[4]+$boundBox[1])/2),$boundBox[4]};
	float $TranlateZ[]={$ObjPos[2],$boundBox[2],$boundBox[5],(($boundBox[2]+$boundBox[5])/2),(($boundBox[2]+$boundBox[5])/2),(($boundBox[2]+$boundBox[5])/2)};
	for ($s=0;$s<6;$s++)
	{
		xform -ws -t $TranlateX[$s] $TranlateY[$s] $TranlateZ[$s] ($ObjName+"_TheAngleTemp");
		float $TheTempTr[]=`xform -q -t ($ObjName+"_TheAngleTemp")`;
		if ($TheTempTr[2]<0)
			{
			float $TheLang1=sqrt($TheTempTr[0]*$TheTempTr[0]+$TheTempTr[2]*$TheTempTr[2]);
			float $TheLang2=sqrt($TheTempTr[1]*$TheTempTr[1]+$TheTempTr[2]*$TheTempTr[2]);
			if ($TheLang1!=0 && $TheLang2!=0)
				{
					float $TheSin=$TheTempTr[0]/$TheLang1;
					float $TheAngle=`asin ($TheSin)`;

					float $TheSin2=$TheTempTr[1]/$TheLang2;
					float $TheAngle2=`asin ($TheSin2)`;

					select -cl;
					select $CamName;
					pickWalk -d down;

					string $came[]=`ls -sl`;
					select -cl;
					float $focal=`getAttr ($came[0]+".focalLength")`;
					float $aperture=`getAttr ($came[0]+".horizontalFilmAperture")`;
					float $TheCamAngle=  57.29578 *atan ((0.5 * $aperture) / ($focal * 0.03937))+5;



					float $TheRightAngle=$TheAngle*180/-3.1415;
					float $TheRightAngle2=$TheAngle2*180/3.1415;

					float $TheFaceAngle=$TheCamAngle*-1;

					if ($TheRightAngle<$TheCamAngle && $TheRightAngle>$TheFaceAngle&&$TheRightAngle2<$TheCamAngle && $TheRightAngle2>$TheFaceAngle)
						{$i+=1;}
					if ($TheRightAngle>$TheCamAngle || $TheRightAngle<$TheFaceAngle||$TheRightAngle2>$TheCamAngle || $TheRightAngle2<$TheFaceAngle)
						{$m+=1;}
				}

			if ($TheLang1==0 || $TheLang2==0)
				{
					$i+=1;

				
				}

			}

		if ($TheTempTr[2]>=0)
			{$m+=1;}
			


	}

	if ($i>0)
		{
			return 1;
		}
	else 
		return 0;

}

