global proc Jttools()
{
  menu -l "Jt Tools"
       -p MayaWindow
       -to 1
       -aob true
       JtToolsMenu;


  menuItem -l "导入声音" 
           -c JtImportSound;
  menuItem -l "IK/FK" 
           -c JtIkFkBlend;
  menuItem -l "表情库" 
           -c slAnimPoseLibraryJt;

  menuItem -l "面控" 
           -c JtFaceCtrls;
  menuItem -l "相机"
           -c JtCamTools;

  menuItem -l "树"
           -c HbReplaceTreesMel;
  menuItem -l "探照灯"
           -c HbAutoHideObject;
  menuItem -l "拍屏"
           -c performPlayblast 3;;


}

global proc JtImportSound()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/HbJtImportSound.py\")");
}

global proc JtIkFkBlend()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/AnimIKFKUI.py\")");
}

global proc JtFaceTools()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/AnimIKFKUI.py\")");
}
global proc JtFaceCtrls()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/HbSelectFaceCtrl.py\")");
}
global proc JtCamTools()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/HbGtCameraTools.py\")");
}

global proc HbReplaceTreesMel()
{
	python("execfile(\"//file-cluster/support/Maya/projects/JT/HbJtTreeReplace.py\")");
}


