global proc ren_wxII_setlightToRGB()
{
	
}

global proc ysSetlightToRed()
{
	string $redLights[] = `ls -sl`;
	for($item in $redLights)
	{
		setAttr ($item + ".color")	-type double3 1 0 0;
	}		
}

global proc ysSetlightToGreen()
{
	string $greenLights[] = `ls -sl`;
	for($item in $greenLights)
	{
		setAttr ($item + ".color")	-type double3 0 1 0;
	}		
}

global proc ysSetlightToBlue()
{
	string $blueLights[] = `ls -sl`;
	for($item in $blueLights)
	{
		setAttr ($item + ".color")	-type double3 0 0 1;
	}		
}