/// Author: zzj
///
/// Creation Date: 2009/05/19
/// Data collect:
/// Description:
/// Modify: zzj
global proc finishingRenameCam()
{

		if (`window -ex wxIIfinishingRenameCam`) deleteUI wxIIfinishingRenameCam;
		window -title "重命名摄像机————解决个别摄像机不能重命名问题" -s 1 -mxb false wxIIfinishingRenameCam;
			columnLayout -rs 5 -adj 1;
				textFieldButtonGrp -label "重命名为：" -text "" -buttonLabel "确认" -bc "finishingRenameCamCMD()" wxIIfinishingRenameCamText;
		window -e -w 500 -h 60 wxIIfinishingRenameCam;
		showWindow wxIIfinishingRenameCam;


}

global proc finishingRenameCamCMD()
{

	string $content=`textFieldButtonGrp -q -tx wxIIfinishingRenameCamText`;
	string $conAdd=$content+":*";
	if (size(`ls $conAdd`)>0)
	{
	namespace -set ":";
	string $tmp="";
	for ($i = 1;$i<10;$i++)
	{
		string $tp="ares"+$i;
		string $temp="ares"+$i+":*";
		if (size(`ls $temp`)>0)
		{continue;}
		else
		{$tmp=`namespace -add $tp`;break;}
	}
	namespace -mv $content $tmp;
	namespace -rm $content;
	}
	rename `ls -sl` $content;

}