global proc s100VRConnectScaleJoint()
{
$var =`listRelatives -ad -type "joint" "joint_grp"`;
$var2= stringArrayRemoveExact({"VR_root_jnt"} ,$var) ;

	for($vart in $var2)
	{
	$sub = substituteAllString ($vart , "_jnt" , "_an_ctrl" ) ;
	scaleConstraint $sub $vart;
    }

}


global proc s100VRConnectScaleJointToFirstGroup()
{
$var =`listRelatives -c -type "transform" "joint_grp"`;
$var2= stringArrayRemoveExact({"VR_root_jnt"} ,$var) ;

	for($vart in $var2)
	{
	$list = `listConnections ($vart +".scale") `  ;
		if(size($list) == 0)
			connectAttr ("root_ctrl.scale") ($vart +".scale");
    }

}