global proc yeti_tool()
{
    if(`window -ex myTestWin`)
        deleteUI myTestWin;

    window -t "Yeti毛发工具" -wh 500 600 myTestWin ;
    columnLayout -adj 1; 

        text -w 400 -h 30 -l "";
        text -w 400 -h 20 -l  "请选择毛发生长物体，再选择创建好的Set节点";
        button -w 400 -h 50 -l "将maya曲线转换Groom" -c "yeti_wds()";

        text -w 400 -h 30 -l "";
        text -w 400 -h 20 -l "选择 aihair 材质节点后执行 ";
        button -w 400 -h 50 -l "设置材质UV属性" -c "yeti_UV";
        
        text -w 400 -h 30 -l "";
        text -w 400 -h 20 -l "请先选择Groom，再选择要替换的生长Groom的模型 ";
        button -w 400 -h 50 -l "为Groom节点替换模型" -c "yeti_wds_TH";
        
    showWindow myTestWin;
        
}


global proc yeti_wds()

{
string $s[]=`ls -sl`;
string $shapes[] = `listHistory  $s[0]`;
pgYetiConvertGuideSetToGroom ($s[1], $shapes[0]);

}


global proc yeti_UV()
{
string $s[]=`ls -sl`;
for($a in $s)
  {
    setAttr -type "string" ($a + ".uparam") "uparamcoord";
    setAttr -type "string" ($a + ".vparam") "vparamcoord";
  }
}


global proc yeti_wds_TH()

{
    string $G_MD[]=`ls -sl`;
    string $shapes[] = `listHistory  $G_MD[0]`;
    
    connectAttr -f ($G_MD[1]+".worldMesh[0]") ($shapes[0]+".inputGeometry");
}



