global proc string[] s100returnViewList()
{

string $tab[] = {"joints",
				"ikHandles",
				"dynamics",
				"hairSystems",
				"fluids",
				"follicles",
				"nCloths",
				"nParticles",
				"nRigids",
				"dynamicConstraints",
				"locators",
				"dimensions",
				"pivots",
				"handles",
				"textures",
				"nurbsCurves",
				"nurbsSurfaces",
				"polymeshes",
				"subdivSurfaces",
				"planes",
				"deformers",
				"strokes",
				"lights",
				"cameras",
				"manipulators"};

return $tab;
}

global proc string[] s100returnHeadList()
{

string $tab[] = {"selectDetailsVisibility",
				"objectDetailsVisibility",
				"polyCountVisibility",
				"animationDetailsVisibility",
				"subdDetailsVisibility",
				"fbikDetailsVisibility",
				"frameRateVisibility",
				"currentFrameVisibility",
				"currentContainerVisibility",
				"cameraNamesVisibility",
				"focalLengthVisibility",
				"viewAxisVisibility"};

return $tab;
}

global proc string[] s100returnHeadListcmd()
{

string $tab[] = {"setSelectDetailsVisibility",
				"setObjectDetailsVisibility",
				"setPolyCountVisibility",
				"setAnimationDetailsVisibility",
				"setSubdDetailsVisibility",
				"setFbikDetailsVisibility",
				"setFrameRateVisibility",
				"setCurrentFrameVisibility",
				"setCurrentContainerVisibility",
				"setCameraNamesVisibility",
				"setFocalLengthVisibility",
				"setViewAxisVisibility"};

return $tab;
}

global proc string[] s100getHeadUp()
{
$tab =`s100returnHeadList`;
string $return[] ;
$i = 0 ;
	for($i = 0 ; $i < size($tab); $i++)
	{


	$return[$i]	 = ` optionVar -query $tab[$i]  `;

    }

//$return[$i]	 = `viewManip -q -v`;

return $return ;
}

global proc  s100restoreHeadUp(string $value[] )
{
//$value = $head;
int $v  = 0 ;
string $tab[] = `s100returnHeadListcmd `;
$last=  size($value) - 1 ;
$v = $value[$last] ;

	for($i = 0 ; $i < size($tab); $i++)
	{


	eval ( $tab[$i] + " " + $value[$i] ) ;

    }

}

global proc  s100HiddeHeapUp()
{
string $tab[] = `s100returnHeadListcmd `;
string $value[] = `s100getHeadUp `;


	for($i = 0 ; $i < size($tab); $i++)
	{

		if($tab[$i] != "")
		{
		 eval ( $tab[$i] + " 0 ") ;
		}
    }

//viewManip -v 0 ;

}

global proc string[] s100getListForAllPanel()
{
$get = `getPanel -type modelPanel `;
$tab =`s100returnViewList`;
string $return[] ;

	for($i = 0 ; $i < size($get); $i++)
	{
	string $tmpS = "";
		for($j = 0 ; $j < size($tab) ; $j++)
		{
		$tmp = eval("modelEditor -q -" + $tab[$j]  + " " + $get[$i])  ;
		$tmpS += ($tmp + ";"  );

        }
	$return[$i]	 =  $tmpS ;

    }

return $return ;
}

global proc  s100HiddeForAllPanel()
{
$get = `getPanel -type modelPanel `;
$tab =`s100returnViewList`;
	for($i = 0 ; $i < size($get); $i++)
	{
		for($j = 0 ; $j < size($tab) ; $j++)
		{
		$tmp = eval("modelEditor -e -" + $tab[$j]  + " 0  " + $get[$i])  ;

        }

    }


}

global proc  s100RestoreForAllPanel(string $oldPar[] )
{
//$oldPar = $getA ;
$get = `getPanel -type modelPanel `;
$tab =`s100returnViewList`;
string $value[] ;

	for($i = 0 ; $i < size($get); $i++)
	{
	clear $value ;
	$value = stringToStringArray($oldPar[$i] ,";");

		for($j = 0 ; $j < size($tab) ; $j++)
		{
		$tmp = eval("modelEditor -e -" + $tab[$j]  + " " +$value[$j] + "  " + $get[$i])  ;

        }

    }


}
