global proc int s100proxyGetIfLoad(string $proxyNode)
{
//$proxyNode = "MA_L_GroundModule2_01:MA_V_Coprinus_01_HiPM";

$type = `nodeType $proxyNode` ;
string $ref[] ;
$ch = 1 ;

$chR = 0 ;

	if($type == "proxyManager")
	{
	$ref = `listConnections -type reference  ($proxyNode + ".proxyList[*]") `;
		for($i = 0 ; $i < size($ref) ; $i++)
		{
		$path = `referenceQuery -filename $ref[$i]`;
		$ch = `file -rfn   $ref[$i]  -q -deferReference  $path `;
			if($ch == 0)
			{
			$chR = 1 ;

				break ;

            }

        }
	}
//print ("\n"+$chR+"\n" ) ;
return $chR;



}

global proc string s100proxyReturnActiveRef(string $proxyNode)
{
//$proxyNode = $ref[0]


$type = `nodeType $proxyNode` ;
string $ref[] ;
$ch = 0 ;
string $ret ;
	if($type == "proxyManager")
	{
	$ref = `listConnections -type reference  ($proxyNode + ".proxyList[*]") `;
		for($tmp in $ref)
		{
		$ch = `isActiveProxy($tmp )`;
			if($ch == 1)
			{
			$ret = $tmp ;
			break ;

            }

        }
	}

return $ret;



}




///s100GetIfLoad

global proc string[] s100ProxyReturnTagForARef(string $proxyNode)
{
$type = `nodeType $proxyNode` ;
string $ref[] ;
string $tag[] ;
	if($type == "proxyManager")
	{
	$ref = `listConnections -type reference  ($proxyNode + ".proxyList[*]") `;
		for($i = 0 ; $i < size($ref) ; $i++)
		{
		$tag[$i]  =` getAttr ($ref[$i] + ".proxyTag")`;

        }
	}
	return $tag;

}

global proc string[] s100ProxyReturnRefs(string $proxyNode)
{
//$proxyNode = $ref[0]
$type = `nodeType $proxyNode` ;
string $ref[] ;

	if($type == "proxyManager")
	{
	$ref = `listConnections -type reference  ($proxyNode + ".proxyList[*]") `;
	}
	return $ref;

}

