# -*- coding: utf-8 -*-

# Form implementation generated from reading myuis file 'E:\MineScript\pyqt_study\CameraShakeLibrary_MW.myuis'
#
# Created: Wed May 31 10:30:55 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(714, 576)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 551))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.treeWidget = QtGui.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(20, 20, 181, 481))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.listView = QtGui.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(210, 20, 441, 471))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(220, 30, 75, 71))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 30, 75, 71))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 30, 75, 71))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 30, 75, 71))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 30, 75, 71))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 120, 75, 71))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 120, 75, 71))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(400, 120, 75, 71))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 120, 75, 71))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.tab)
        self.pushButton_10.setGeometry(QtCore.QRect(480, 120, 75, 71))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(560, 200, 75, 71))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 200, 75, 71))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(400, 200, 75, 71))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 200, 75, 71))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.tab)
        self.pushButton_15.setGeometry(QtCore.QRect(480, 200, 75, 71))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.tab)
        self.pushButton_16.setGeometry(QtCore.QRect(560, 280, 75, 71))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.tab)
        self.pushButton_17.setGeometry(QtCore.QRect(310, 280, 75, 71))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.tab)
        self.pushButton_18.setGeometry(QtCore.QRect(400, 280, 75, 71))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.tab)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 280, 75, 71))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(self.tab)
        self.pushButton_20.setGeometry(QtCore.QRect(480, 280, 75, 71))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.tab)
        self.pushButton_21.setGeometry(QtCore.QRect(560, 360, 75, 71))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.tab)
        self.pushButton_22.setGeometry(QtCore.QRect(310, 360, 75, 71))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.tab)
        self.pushButton_23.setGeometry(QtCore.QRect(400, 360, 75, 71))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.pushButton_24 = QtGui.QPushButton(self.tab)
        self.pushButton_24.setGeometry(QtCore.QRect(220, 360, 75, 71))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(self.tab)
        self.pushButton_25.setGeometry(QtCore.QRect(480, 360, 75, 71))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.menuFile.addAction(self.actionImport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "摄像机裤裤裤裤裤", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "灾难", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "追逐", None))
        self.pushButton.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_2.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_3.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_4.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_5.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_6.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_7.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_8.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_9.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_10.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_11.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_12.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_13.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_14.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_15.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_16.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_17.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_18.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_19.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_20.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_21.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_22.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_23.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_24.setText(_translate("MainWindow", "抖来抖去", None))
        self.pushButton_25.setText(_translate("MainWindow", "抖来抖去", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "抖啊抖啊抖", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "甩啊甩啊甩", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "help", None))
        self.actionImport.setText(_translate("MainWindow", "import...", None))

