// ===========================================================================
// Copyright 2016 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//
//	Creation Date:  June, 2004
//
//  Procedure Name:
//      removeAllUnusedInfluences
//
//  Description:
//    For all smooth skin objects in the scene, remove any joints or
//    influence objects that have no effect on the skin (i.e. all weights are 0.0).
//    This will improve performance.
//
//  Input Arguments:
//      None.
//
//  Return Value:
//      None.
//
//
//
global proc int removeAllUnusedSkinInfs()
{
	source "removeUnusedInfluences";
	
	string $scs[] = `ls -type skinCluster`;
	int $removeCount = 0;
	for ($sc in $scs) {
		$removeCount += removeUnusedForSkin($sc, 0);
	}
	return $removeCount;
}
