//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2009-5-25
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////


global proc eyAnimRepairColor()
{
	string $default = "initialShadingGroup";
	
	string $objects[] = `ls -type mesh -type nurbsSurface`;
	for ($obj in $objects)
	{
		string $shadingEngines[] = `listConnections -type shadingEngine $obj`;
		$shadingEngines = stringArrayRemove({$default},$shadingEngines);
		if (size($shadingEngines))
		{
			string $connections[] = `listConnections -s 0 -d 1 -type shadingEngine -c 1 -p 1 $obj`;
			for ($i=0;$i<size($connections);$i=$i+2)
			{
				if (startsWith($connections[$i+1],$default))
				{
					disconnectAttr $connections[$i] $connections[$i+1];
				}
			}
		}
	}
	
	
	
	/*string $sg = "initialShadingGroup";
	string $objs[] = `listConnections -s 1 -d 0 -type mesh -sh 1 $sg`;
	for ($o in $objs)
	{
		string $sgs[] = `listConnections -type shadingEngine $o`;
		$sgs = stringArrayRemove({$sg},$sgs);
		if (size($sgs))
		{
			string $cons[] = `listConnections -s 1 -d 0 -type mesh  -c 1 -p 1 $sg`;
			for($i=0;$i<size($cons);$i=$i+2)
			{
				disconnectAttr $cons[$i+1] $cons[$i];
			}
		}
	}*/
}