//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc eyMekeMouth()
{
	string $allObjects[] = `ls -geometry`;
	createRenderLayer -name "CharMouth" -number 1 -makeCurrent -noRecurse $allObjects ;
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	setAttr "defaultRenderLayer.renderable" 0;
	setAttr -type "string" "defaultRenderGlobals.currentRenderer" "mayaSoftware";
	
	ezRenderMainLayoutMaterial_Assign "matte";
	ezRenderMainLayoutMaterial_Assign "colorR";
	ezRenderMainLayoutMaterial_Assign "colorG";
	ezRenderMainLayoutMaterial_Assign "colorB";
	ezRenderMainLayoutMaterial_Assign "colorA";
	
	sets -e -forceElement ez_matteSG  $allObjects;

	
	string $upteeth[] = `ls "*:MSH_teeth_UP_"`;
	sets -e -forceElement ez_colorRSG  $upteeth;

	string $downteeth[] = `ls "*:MSH_teeth_DWN_"`;
	sets -e -forceElement ez_colorGSG  $downteeth;

	string $tongue[] = `ls "*:MSH_tongue_"`;
	sets -e -forceElement ez_colorBSG  $tongue;

	for ($ut in $upteeth)
	{
		string $buff[] = stringToStringArray($ut,":");
		string $pre = `substring $ut 1 (size($ut)-size($buff[size($buff)-1]))`;

		if (gmatch($pre,"*c001*"))
		{
			string $mouth[] = {"MSH_body_.f[6212:6239]","MSH_body_.f[6420:6423]","MSH_body_.f[6452:6455]","MSH_body_.f[6476:6479]","MSH_body_.f[6680:6683]",
						     "MSH_body_.f[12072:12075]","MSH_body_.f[16915:16942]","MSH_body_.f[17123:17126]","MSH_body_.f[17155:17158]","MSH_body_.f[17179:17182]",
						     "MSH_body_.f[17383:17386]","MSH_body_.f[22919:22922]","MSH_body_.f[26469:27044]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c002*"))
		{
			string $mouth[] = {"MSH_body_.f[365:1132]","MSH_body_.f[25602]","MSH_body_.f[25605]","MSH_body_.f[25608]","MSH_body_.f[26269:26270]","MSH_body_.f[26272]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c003*"))
		{
			string $mouth[] = {"MSH_body_.f[32:751]","MSH_body_.f[26247:26278]","MSH_body_.f[26423:26426]","MSH_body_.f[26443:26446]","MSH_body_.f[26463:26466]",
						     "MSH_body_.f[26507:26510]","MSH_body_.f[26555:26558]","MSH_body_.f[26623:26626]","MSH_body_.f[26742]","MSH_body_.f[26751:26754]",
						     "MSH_body_.f[27384:27415]","MSH_body_.f[27576:27579]","MSH_body_.f[27596:27599]","MSH_body_.f[27616:27619]","MSH_body_.f[27660:27663]",
						     "MSH_body_.f[27708:27711]","MSH_body_.f[27772:27775]","MSH_body_.f[27899:27902]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c004*"))
		{
			string $mouth[] = {"MSH_body_.f[0:509]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c005*"))
		{
			string $mouth[] = {"MSH_body_.f[1021:1022]","MSH_body_.f[1025:1026]","MSH_body_.f[1028:1029]","MSH_body_.f[1032:1033]","MSH_body_.f[1036]","MSH_body_.f[1039]",
						     "MSH_body_.f[1252]","MSH_body_.f[1255]","MSH_body_.f[1272]","MSH_body_.f[1275]","MSH_body_.f[1316]","MSH_body_.f[1319]",
						     "MSH_body_.f[1364:1365]","MSH_body_.f[1884:1885]","MSH_body_.f[2052:2053]","MSH_body_.f[3832:4348]","MSH_body_.f[5392:5393]",
						     "MSH_body_.f[5396:5397]","MSH_body_.f[5399:5400]","MSH_body_.f[5403:5404]","MSH_body_.f[5407]","MSH_body_.f[5410]","MSH_body_.f[5623]",
						     "MSH_body_.f[5626]","MSH_body_.f[5643]","MSH_body_.f[5646]","MSH_body_.f[5687]","MSH_body_.f[5690]","MSH_body_.f[5735:5736]",
						     "MSH_body_.f[6255:6256]","MSH_body_.f[6423:6424]","MSH_body_.f[8203:8719]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c006*"))
		{
			string $mouth[] = {"polySurface3.f[24484:25137]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
		if (gmatch($pre,"*c007*"))
		{
			string $mouth[] = {"MSH_body_.f[9869:9892]","MSH_body_.f[10152:10155]","MSH_body_.f[10172:10175]","MSH_body_.f[10216:10219]","MSH_body_.f[10264:10267]",
						     "MSH_body_.f[10855:10858]","MSH_body_.f[11091:11094]","MSH_body_.f[23149:23172]","MSH_body_.f[23432:23435]","MSH_body_.f[23452:23455]",
						     "MSH_body_.f[23496:23499]","MSH_body_.f[23544:23547]","MSH_body_.f[24135:24138]","MSH_body_.f[24371:24374]","MSH_body_.f[26560:27223]"};
			for ($m in $mouth)
			{
				sets -e -forceElement ez_colorASG  ($pre+$m);
			}
		}
	}
}