//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2009-11-4
//
//	Update/Change: WansHoulOng
//	Last Updated: 2009-11-4
//	Description:
//				
//////////////////////////////////////////////////////////

global proc eyRenderOcean()
{
	if (`window -ex eyRenderOceanWin`)
		deleteUI eyRenderOceanWin;
	
	window -title "Ocean  Tools" -s false eyRenderOceanWin;
		columnLayout -adj true;
			separator -st none -h 20;
			frameLayout -l "Ocean" -bs "etchedIn" -la "top";
				rowColumnLayout  -nc 4;
					symbolButton -ann "遥远"	-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"ocean\" \"very far\"";
					symbolButton -ann "远"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"ocean\" \"far\"";
					symbolButton -ann "中"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"ocean\" \"middle\"";
					symbolButton -ann "近"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"ocean\" \"near\"";
				setParent ..;
			setParent ..;
			separator -st none -h 20;
			frameLayout -l "River" -bs "etchedIn" -la "top";
				rowColumnLayout  -nc 4;
					symbolButton -ann "遥远"	-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"river\" \"very far\"";
					symbolButton -ann "远"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"river\" \"very far\"";
					symbolButton -ann "中"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"river\" \"very far\"";
					symbolButton -ann "近"		-image "circle.xpm" -w 80 -h 80 -c "eyRenderOceanCMD \"river\" \"very far\"";
				setParent ..;
			setParent ..;
		setParent ..;
	window -e -w 410 -h 280 eyRenderOceanWin;
	showWindow eyRenderOceanWin;
}

global proc eyRenderOceanCMD(string $type,string $distance)
{
	switch ($type)
	{
		case  "ocean" :
			file -import -type "mayaBinary" -rpr "ocean" -options "v=0"  -pr "//File-cluster/gdc/Resource/Support/Maya/projects/Enyo/lightingStyles/ocean.mb";
			switch ($distance)
			{
				case "very far" :
					print $distance;
					break;
				case "far" :
					print $distance;
					break;
				case "middle" :
					print $distance;
					break;
				case "near" :
					print $distance;
					break;
			}
			break;
		case "river" :
			file -import -type "mayaBinary" -rpr "ocean" -options "v=0"  -pr "//File-cluster/gdc/Resource/Support/Maya/projects/Enyo/lightingStyles/river.mb";
			switch ($distance)
			{
				case "very far" :
					print $distance;
					break;
				case "far" :
					print $distance;
					break;
				case "middle" :
					print $distance;
					break;
				case "near" :
					print $distance;
					break;
			}
			break;
	}
}