//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2009-12-4
//
//	Update/Change: WansHoulOng
//	Last Updated: 2009-12-4
//	Description:
//				
//////////////////////////////////////////////////////////


global proc eyRenderWBCache()
{
	string $sceneName = `file -q -sn -shn`;
	string $buff[];
	tokenize $sceneName "_" $buff;

	if (!($buff[0] == "ey" && $buff[1] == "125"))
		return;
	
	string $cacheFile[] = `ls -type "cacheFile"`;
	string $wrongDir = "X:/Projects_TV/";
	for($file in $cacheFile)
	{
		string $baseDir = `getAttr ($file+".cachePath")`;
		$baseDir = substituteAllString($baseDir,"\\","/");
		if(gmatch($baseDir,($wrongDir+"*")))
		{
			string $newBaseDir = substituteAllString($baseDir,$wrongDir,"//file-cluster/GDC/Projects/");
			//$newBaseDir = substituteAllString($newBaseDir,"/","\\");
			print ($baseDir+"===>>>"+$newBaseDir+"\n");
			setAttr -type "string" ($file+".cachePath") $newBaseDir;
		}
	}
}