//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2009-9-10
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc eyRenderHungaEyesReplaceTexture(string $type)
{
	string $texture[] = `ls -type file "*c001001hunga*:TXT_Iris_c"  "*:*c001001hunga*:TXT_Iris_c"`;

	for ($tx in $texture )
	{
		/*string $filename;	
		if ($type == "new")
			$filename = "ey_c001001hunga_eye120_c_1k.tga.map.tga";
		else 
			$filename = "ey_c001001hunga_eye_c_1k.tga.map";*/

		
		string $oldFile = `getAttr ($tx+".fileTextureName")`;
		string $buff[];
		int $num = `tokenize $oldFile "\/" $buff`;
		//string $path = `substring $oldFile 1 (size($oldFile) - size($buff[$num-1]))`;
		string $filename = $buff[$num-1];
		if ($type == "new")
		{
			if (!`gmatch $filename "*_eye_*" `)
				return ;
			$filename = `substituteAllString $filename "_eye_" "_eye120_"` + ".tga.map";
		}
		else 
		{
			if (!`gmatch $filename "*_eye120_*" `)
				return ;
			$filename = `substituteAllString $filename "_eye120_" "_eye_"`;
			$filename = `substring $filename 1 (size($filename)- size(".tga.map"))`;
		}
		string $newFile = `substituteAllString $oldFile $buff[$num-1] $filename`;

		setAttr -type "string" ($tx+".fileTextureName") $newFile;
	}
}

global proc eyRenderHungaEyes()
{
	if (`window -ex eyRenderHungaEyesWin`)
		deleteUI eyRenderHungaEyesWin;
	
	window -t "Hunga Eyes          WHO" -in "Hunga Eyes" -mnb 0 -mxb 0 eyRenderHungaEyesWin;
		columnLayout -adj 1 -rs 3;
			button -l "ÐÂµÄ" -c "eyRenderHungaEyesReplaceTexture \"new\"";
			button -l "¾ÉµÄ" -c "eyRenderHungaEyesReplaceTexture \"old\"";
	window -e -wh 180 80 eyRenderHungaEyesWin;
	showWindow;
}