global proc ysSetIBLoffInAO ()
{
	string $renderLayers[] = `ls -type "renderLayer"`;
	if (`objExists "IBL_RampShape"`)
	{
		for($item in $renderLayers)
		{
			if($item == "AO")
			{
				editRenderLayerGlobals -currentRenderLayer "AO";
				editRenderLayerAdjustment "IBL_RampShape.emitLight";
				setAttr "IBL_RampShape.emitLight" 0;
			}
			
			if($item == "castAO")
			{
				editRenderLayerGlobals -currentRenderLayer "castAO";
				editRenderLayerAdjustment "IBL_RampShape.emitLight";
				setAttr "IBL_RampShape.emitLight" 0;
			}
			
			if($item == "normal")
			{
				editRenderLayerGlobals -currentRenderLayer "normal";
				editRenderLayerAdjustment "IBL_RampShape.emitLight";
				setAttr "IBL_RampShape.emitLight" 0;
			}
			
			if($item == "selfshadow")
			{
				editRenderLayerGlobals -currentRenderLayer "selfshadow";
				editRenderLayerAdjustment "IBL_RampShape.emitLight";
				setAttr "IBL_RampShape.emitLight" 0;
			}	
			
			if($item == "castShadow")
			{
				editRenderLayerGlobals -currentRenderLayer "castShadow";
				editRenderLayerAdjustment "IBL_RampShape.emitLight";
				setAttr "IBL_RampShape.emitLight" 0;
			}
		}
	}
}

