/// Copyright (C) 2000-2009 IDMT. All rights reserved.
///
/// Author: 黄璧（重庆）
///
/// Creation Date: 2009/04/15
///
/// Description: 把程序纹理转换成贴图

global proc hbConvertTx()
{
 if(`window -ex ConvertTextWin`)
     deleteUI -window   ConvertTextWin;
	window -t "Texture Tool" ConvertTextWin;
          formLayout colOut;
		 frameLayout -label "pixels X:"
			-borderStyle "etchedOut" vauleYLay;
			intSliderGrp  -f 1 -min 128 -max 2048 -v 512 vauleY;
		setParent..;
		 frameLayout -label "pixels Y:"
			 -borderStyle "etchedOut" vauleXLay;
			 intSliderGrp  -f 1 -s 1 -min 128 -max 2048 -v 512 vauleX;
		setParent..;

		frameLayout -label "type"
			-borderStyle "etchedOut" outputworld;

 	
			textScrollList -numberOfRows 6 -allowMultiSelection 1 
			     -append "noise"      
			     -append "fractal"     
			     -append "mountain"
			     -append "cloth"
			     -append "water"

    
 			-selectItem "noise" 
 			-showIndexedItem 4    selection;

			setParent..;
		 frameLayout -label "Option:"
			 -borderStyle "etchedOut" Option;
                         radioButtonGrp -numberOfRadioButtons 2
                               -labelArray2 "All" "Selection" 
                         	-sl 1 OptionV;
		setParent..;  
                            text -l "                     ------------------------"  copyright_one;
                            text -l "                      GDC-IDMT 2009(C)"  copyright_two;

      button -l "Convert and Close" -c "hbConvertTextMain;deleteUI -wnd ConvertTextWin;" OkBtn; 
      button -l "Apply" -c "hbConvertTextMain;" AppBtn;
      button -l "Close" -c "deleteUI -wnd ConvertTextWin;" ClosBtn;
   setParent..;
  formLayout -e
        -af vauleYLay "top" 5
        -af vauleYLay "left" 5
        -af vauleYLay "right" 5
         

        -ac vauleXLay "top" 5 vauleYLay
        -af vauleXLay "left" 5
        -af vauleXLay "right" 5

        -ac outputworld "top" 5 vauleXLay
        -af outputworld "left" 5
        -af outputworld "right" 5

        -ac Option "top" 5 outputworld
        -af Option "left" 5
        -af Option "right" 5

        -ac copyright_one "top" 5 Option 
        -af copyright_one "left" 5
        -af copyright_one "right" 5

        -ac copyright_two "top" 5 copyright_one
        -af copyright_two "left" 5
        -af copyright_two "right" 5



 
        -af OkBtn "bottom" 5
        -af OkBtn "left" 5
        -ap OkBtn "right" 5 50

        -af AppBtn "bottom" 5
        -ac AppBtn "left" 5 OkBtn
        -ap AppBtn "right" 5 80


        -af ClosBtn "bottom" 5
        -ac ClosBtn "left" 5 AppBtn
        -ap ClosBtn "right" 5 100
 colOut;

showWindow ConvertTextWin;

}

hbConvertTx;

global proc hbConvertTextMain()

{
        float $GetVauleY=`intSliderGrp -q -v vauleY`;
	float $GetVauleX=`intSliderGrp -q -v vauleX`;
        string $TypeName[]=`textScrollList  -q -si selection`;
       int $GetRadioButton=`radioButtonGrp -q -sl OptionV`; 
      if($GetRadioButton==1)
       {
           for($aa in $TypeName)
           { 
               string $GetFractalName[]=`ls -type $aa` ;
		string $GetAllName="";
			if(size($GetFractalName)>0)
			{
                           string $PloyPlanName[]=`polyPlane -ch on -o on -w 1 -h 1 -sw 1 -sh 1 -cuv 2 `;
				 for($ss in $GetFractalName)
				{
				string $GetConnectAttr[]=`listConnections -d on -s off -p 1 ($ss+".outColor")`;
				string $GetConnectAttr2[]=`listConnections -d on -s off -p 1 ($ss+".outAlpha")`;
				string $GetConnectName3[]=`listConnections -d off -s on  -p 1 ($ss+".defaultColor")`;
				string $GetConnectName4[]=`listConnections -d off -s on  -p 1 ($ss+".colorGain")`;
				string $GetConnectName5[]=`listConnections -d off -s on  -p 1 ($ss+".colorOffset")`;
				string $GetFileNameNew[]=`convertSolidTx -antiAlias 0 -bm 1 -fts 1 -sp 0 -sh 0 -alpha 0 -doubleSided 0 -componentRange 0 -resolutionX $GetVauleX -resolutionY $GetVauleY -fileFormat "tga"  -fullUvRange  ($ss+".outColor") $PloyPlanName[0]`;
					for($GetConnect in $GetConnectAttr)
					{
						connectAttr -force ($GetFileNameNew[0]+".outColor") $GetConnect;
					}
					for($GetConnect in $GetConnectAttr2)
					{
						connectAttr -force ($GetFileNameNew[0]+".outAlpha") $GetConnect;
					}
					for($GetConnect in $GetConnectName3)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".defaultColor");
					}
					for($GetConnect in $GetConnectName4)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".colorGain");
					}					
					for($GetConnect in $GetConnectName5)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".colorOffset");
					}
				 $GetAllName=$GetAllName+$ss+"@";

				}
				print $GetAllName;
				delete $PloyPlanName[0] ;


				string $buffer[];
					$numTokens = `tokenize $GetAllName "@" $buffer`;
				for($sss in $buffer)
					{
					string $GetConnectName[]=`listConnections -d off -s on  $sss`;
					delete $sss ;
					delete $GetConnectName[0] ;
					print $GetConnectName[0] ;

					
					}



			}



	   }



        }

      if($GetRadioButton==2)
         {
              string $GetFractalName[]=`ls -sl` ;
		string $GetAllName="";
			if(size($GetFractalName)>0)
			{
		            string $PloyPlanName[]=`polyPlane -ch on -o on -w 1 -h 1 -sw 1 -sh 1 -cuv 2 `;

				 for($ss in $GetFractalName)
				{
				string $GetConnectAttr[]=`listConnections -d on -s off -p 1 ($ss+".outColor")`;
				string $GetConnectAttr2[]=`listConnections -d on -s off -p 1 ($ss+".outAlpha")`;
				string $GetConnectName3[]=`listConnections -d off -s on  -p 1 ($ss+".defaultColor")`;
				string $GetConnectName4[]=`listConnections -d off -s on  -p 1 ($ss+".colorGain")`;
				string $GetConnectName5[]=`listConnections -d off -s on  -p 1 ($ss+".colorOffset")`;
				string $GetFileNameNew[]=`convertSolidTx -antiAlias 0 -bm 1 -fts 1 -sp 0 -sh 0 -alpha 0 -doubleSided 0 -componentRange 0 -resolutionX $GetVauleX -resolutionY $GetVauleY -fileFormat "tga"  -fullUvRange  ($ss+".outColor") $PloyPlanName[0]`;
					for($GetConnect in $GetConnectAttr)
					{
						connectAttr -force ($GetFileNameNew[0]+".outColor") $GetConnect;
					}
					for($GetConnect in $GetConnectAttr2)
					{
						connectAttr -force ($GetFileNameNew[0]+".outAlpha") $GetConnect;
					}
					for($GetConnect in $GetConnectName3)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".defaultColor");
					}
					for($GetConnect in $GetConnectName4)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".colorGain");
					}					
					for($GetConnect in $GetConnectName5)
					{
						connectAttr -force $GetConnect ($GetFileNameNew[0]+".colorOffset");
					}
				 $GetAllName=$GetAllName+$ss+"@";
				}
				delete $PloyPlanName[0] ;
				string $buffer[];
					$numTokens = `tokenize $GetAllName "@" $buffer`;
				for($sss in $buffer)
					{
					string $GetConnectName[]=`listConnections -d off -s on  $sss`;
					delete $sss ;
					delete $GetConnectName[0] ;
					print $GetConnectName[0] ;


					
					}
			}




         }

}
