
/// Copyright (C) 2000-2009 IDMT. All rights reserved.
///
/// Author: 黄璧（重庆）
///
/// Creation Date: 2009/07/18
///
/// Description: 批处理特效70几个镜头用


/// Copyright (C) 2000-2009 IDMT. All rights reserved.
///
/// Author: 黄璧（重庆）
///
/// Creation Date: 2009/05/06
///
/// Description: 
global proc hbDODPetool_local()
{

	
	if (`window -ex hbDODPetUI`)
		deleteUI hbDODPetUI;
	
	window -title "DOD2表情库" -in "Petool" -mnb false -mxb false hbDODPetUI;
		string $form = `formLayout -width 200 -numberOfDivisions 200 `;



		string $fra5=`frameLayout -label "表情" `;
		gridLayout -numberOfColumns 6 -cellWidthHeight 64 85 -backgroundColor 125 125 125 bb;
		
                 for ($k=0;$k<20 ;$k++ )
		{
		iconTextButton -width 64 -h 85 -fn  "boldLabelFont"   -style "iconAndTextVertical" -backgroundColor 125 125 125  ("ain"+$k);
		}

			setParent ..;
		setParent ..;


		string $chname	=`textScrollList -selectCommand "hbDODPtoolview_ADD" -w 100 -h 358 Bupetp`;
		string $path ="E:/facialLib/DOD2/";
		string $files[] = `getFileList -fld $path `;

		for ($n in $files) 
		{
		textScrollList -e -append $n Bupetp;
		}

		setParent ..;

        frameLayout -label "口型幅度"
            -borderStyle "etchedOut"   faceScale;
            floatSliderGrp -f 1 -s 1 -min -0 -max 2 -v 1   faceScale;

        setParent..;
        setParent..;

            checkBox -label "key" autoKey;

        setParent..;
             button -l "选择全部控制器" -c "selectAllCon;" OkBtn; 
	     button -l "快照" -c "simpleSnapshot" ADDBtn; 

        setParent..;


formLayout -edit
			-attachForm		$fra5		"top"    5
			-attachForm		$fra5		"left"   5
			-attachControl		$fra5		"right"  5 $chname

			-attachForm		$chname		"top"    5
			-attachNone		$chname		"left"  
			-attachForm		$chname		"right"  5


                        -af faceScale "bottom" 5 
                        -af faceScale "left" 5
                        -ap faceScale "right" 5 130

                        -af autoKey "bottom" 5 
                        -ac autoKey "left" 5 faceScale
                        -ap autoKey "right" 5 150

                        -af OkBtn "bottom" 5
                        -ac OkBtn "left" 5 autoKey
                        -ap OkBtn "right" 5 200

			-af ADDBtn "bottom" 30
                        -ac ADDBtn "left" 5 autoKey
                        -ap ADDBtn "right" 5 200


		$form;

	showWindow hbDODPetUI;
}
global proc hbDODPtoolview_ADD()
  {
           for($mmm=0;$mmm<20;$mmm++)
              {

               iconTextButton -edit -visible off ("ain"+$mmm);


               }
	string $Buicona[]=`textScrollList -q -si Bupetp`;
	string $path ="E:/facialLib/DOD2/"+$Buicona[0]+"/face/";
        string $files[] = `getFileList -fld $path `;
        int $j=0;
       int $c=0;


           for ($ssss=0;$ssss<`size $files`;$ssss++ )
	        { 
	            string $buffer[];
	            $numTokens = `tokenize $files[$ssss] "." $buffer`;
	            string $buffer2[];
	            $numTokens = `tokenize $buffer[0] "（" $buffer2`;
	            string $buffer3[];
	            $numTokens = `tokenize $buffer[0] "）" $buffer3`;
                     if($buffer2[0]=="表")

                      {     
                                   
                      iconTextButton -edit -fn  "boldLabelFont"   -visible on -label $buffer[0] -c ("BuDODPTget_ADD(\""+$buffer[0]+"\")") -image1 ($path+$buffer[0]+".bmp") ("ain"+$buffer3[1]);
    

                      }

                }
                
                
              
}




hbDODPetool_local;
global proc BuDODPTget_ADD(string $name)
  {

      float $getfaceScale=`floatSliderGrp -q -v faceScale`;
      float $getautoKey=`checkBox -q -v autoKey`;
      string $ls[]=`ls -sl`;
      string $buffer3[];
      $numTokens = `tokenize $ls[0] ":" $buffer3`;
      int $time=`currentTime -q`;
      string $lisat[];
      string $num[];
      string $Attr[];


      string $Buicona[]=`textScrollList -q -si Bupetp`;
      string $path ="D:/hb/BubblePuppy/"+$Buicona[0]+"/";
      $exampleFileName =$path+$name+".txt";

      string $Di_zhi  = "type  " + "E:\\facialLib\\DOD2\\"+$Buicona[0]+"\\face\\"+$name;
      print ($Di_zhi+"hahahahahaha");
      string $Lei= `system($Di_zhi)`;

      string $buffer[];
         $numTokens = `tokenize $Lei "\n" $buffer`;
              for($aaa in $buffer)
                { string $back1=`match "poseLibIndexOrder" $aaa`;
                if($back1!="poseLibIndexOrder")
                 {
                         string $buffer2[];
                         $numTokens = `tokenize $aaa " " $buffer2`;
                          string $attrName=$buffer3[0]+":"+$buffer2[0]+"."+$buffer2[1];
                          float $attrTranse=$buffer2[2];
                              if($getautoKey==0)
                                {
                                    setAttr $attrName ($attrTranse*$getfaceScale);
                                 }
                                     else if($getautoKey==1)
                                 {
                                     setKeyframe -t $time -at $buffer2[1] -v ($attrTranse*$getfaceScale) ($buffer3[0]+":"+$buffer2[0]);
                                   setAttr $attrName ($attrTranse*$getfaceScale);
                                 }
                   }

         

               }

}

global proc selectAllCon()
{

   string $ls[]=`ls -sl`;
      string $buffer3[];
      $numTokens = `tokenize $ls[0] ":" $buffer3`;
      select -cl;
      select -r ($buffer3[0]+":Jaw_MN_CTRL");
      select -add ($buffer3[0]+":CtrlRig_*_LowerCheek_****_CTRL");
      select -add ($buffer3[0]+":CtrlRig_*_Mouth_**_CTRL");
      select -add ($buffer3[0]+":CtrlRig_*_LowerCheek_**_**_CTRL");
      select -add ($buffer3[0]+":CtrlRig_***erLip_**_**_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_*_LaughLine_**_**_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_**er_Lip_MA_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_Nose_MN_CTRL  ");
      select -add ($buffer3[0]+":CtrlRig_**_Nose_MI_CTRL  ");
      select -add ($buffer3[0]+":CtrlRig_**_Cheek_MA_CTRL  ");
      select -add ($buffer3[0]+":CtrlRig_*_**erEyeLid_**_**_CTRL");
      select -add ($buffer3[0]+":CtrlRig_**_UpperCheek_**_**_CTRL");
      select -add ($buffer3[0]+":CtrlRig_**_EyeBrow_**_CTRL");
      select -add ($buffer3[0]+":CtrlRig_*_***erEyeLid_MN_CTRL");
      select -add ($buffer3[0]+":CtrlRig_***erLip_**_**_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_*_Cheek_**_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_**er_Lip_MA_CTRL ");
      select -add ($buffer3[0]+":CtrlRig_*_Ear_MN_CTRL ");
}



global proc simpleSnapshot(){
	python("execfile(\"z:/resource/support/maya/python/idmt/yyscripts/yySimpleSnapShot.py\")");
}