#programer:edward
#lastTime:20121206
#used:motionCapture

import maya.cmds as cmds
import maya.mel as mel
#edo_snapMotionBuilderChrJointToGDCrig('mocap_to_gdcRig')
execfile('Z:/Resource/Groups/Production/Modeling/Rigging 2009 Development Plan/BodyRiggingTools/script/RIG/selectProject.py')
execfile('Z:/Resource/Groups/Production/Modeling/Rigging 2009 Development Plan/BodyRiggingTools/script/RIG/edo_ikfkSwitch.py')
def edo_motionBuilderControlGdcRigUI():
    if cmds.window('edo_motionBuilderControlGdcRigUI',ex=1):
        cmds.deleteUI('edo_motionBuilderControlGdcRigUI')
    cmds.window('edo_motionBuilderControlGdcRigUI',t='edo_motionBuilderControlGdcRigUI',w=500,h=100)
    cmds.columnLayout('edo_motionBuilderControlGdcRigUICL',adjustableColumn=True,rs=10)
    cmds.button('mbRigButton',l='change the version to MotionBuilder',ann='',h=25,c='edo_mbRigButtonCmd()')
    cmds.button('IKFK_SWITCH',l='HUMANIK RIG IKFK SWITCH',ann='',h=25,c='edo_ikfkSwitch()')
    cmds.text('===============================================') 
    cmds.button('addHumanIK_SKIN_BUTTON',l='ADD_HUMANIK_SKIN_SKELETON',ann='LOCATION A HUMANIK SKIN SKELETON TO GDCRIG',h=25,c='edo_locationHumanIk_skinSkeletonCmdUI()')
    #cmds.text('first,create a new human ik skeleton(skeleton-->humanIK-->skeleton genarator)')
    #cmds.text('then field the character name to the textField and click the button')
    #cmds.textFieldButtonGrp('motionBuilderControlGdcRig',label='MB character: ',text='',buttonLabel='humanIK control GDCRIG',cw3=[80,160,80],bc='edo_motionBuilderControlGdcRig()')
    cmds.button('HUMANIK_TO_GDCRIG_BUTTON',l='HUMANIK_TO_GDCRIG',ann='CREATE A HUMANIK TO CONTROL OUR RIG',h=25,c='edo_motionBuilderControlGdcRigCmd()')
    #cmds.popupMenu()
    #cmds.menuItem(l='only location humanIk skeleton',c='edo_locationHumanIk_skinSkeletonCmdUI()')
    #cmds.text('finaly,must remenber lock the human ik skeleton')
    cmds.showWindow('edo_motionBuilderControlGdcRigUI')
    cmds.window('edo_motionBuilderControlGdcRigUI',e=1,w=300,h=100)

def edo_mbRigButtonCmd():
    edo_freeAllCtrlAxis()
    edo_connectionHalfJoint()
    edo_createLocation()
    
def edo_motionBuilderControlGdcRig():
    chr=cmds.textFieldButtonGrp('motionBuilderControlGdcRig',q=1,text=1)
    edo_snapMotionBuilderChrJointToGDCrig(chr)
    edo_motionBuilderJointConstraintChrCtrl(chr)
    
def edo_motionBuilderControlGdcRigCmd():
    chr='HUMANIK_TO_GDCRIG'
    filepath='Z:/Resource/Groups/Production/Modeling/Rigging 2009 Development Plan/BodyRiggingTools/script/RIG/template/HUMANIK_TO_GDCRIG.mb'
    mel.eval('HIKSkeletonGenerator;')
    cmds.file(filepath,i=1,uns=False)
    edo_snapMotionBuilderChrJointToGDCrig(chr)
    #edo_saveCharacterSkeletionPosition(chr)
    mel.eval('mayaHIKcharacterLock("'+chr+'",1,1);')
    edo_motionBuilderJointConstraintChrCtrl(chr)
    
def edo_locationHumanIk_skinSkeletonCmdUI():
    if cmds.window('edo_motionBuilderSkeletonUI',ex=1):
        cmds.deleteUI('edo_motionBuilderSkeletonUI')
    cmds.window('edo_motionBuilderSkeletonUI',t='edo_motionBuilderSkeletonUI')
    cmds.columnLayout('edo_motionBuilderSkeletonUICL',adjustableColumn=True,rs=10)
    cmds.text('field the humanIK character name.')
    cmds.textFieldButtonGrp('edo_motionBuilderSkeletonUITFB',label='MB character: ',text='',buttonLabel='humanik_location',cw3=[80,160,80],bc='edo_locationHumanIk_skinSkeletonCmd()')
    cmds.showWindow('edo_motionBuilderSkeletonUI')
    cmds.window('edo_motionBuilderSkeletonUI',e=1,w=300,h=50)
    
    
def edo_tryLocationHumanIkSkeleton(source,target):
    try:
        cmds.delete(cmds.pointConstraint(source,target,mo=0))
        cmds.parentConstraint(source,target,mo=1)
    except:
        print target+'      ---- location to ----     '+source+'         is faild' 
    
def edo_locationHumanIk_skinSkeletonCmd():
    chr=cmds.textFieldButtonGrp('edo_motionBuilderSkeletonUITFB',q=1,text=1)
    #body
    cmds.scaleConstraint('Character',chr+'_Reference',mo=1)
    edo_tryLocationHumanIkSkeleton('Character',chr+'_Reference')
    edo_tryLocationHumanIkSkeleton('spline1_jnt',chr+'_Hips')
    edo_tryLocationHumanIkSkeleton('spline2_jnt',chr+'_Spine')
    edo_tryLocationHumanIkSkeleton('spline3_jnt',chr+'_Spine1')
    edo_tryLocationHumanIkSkeleton('spline4_jnt',chr+'_Spine2')
    edo_tryLocationHumanIkSkeleton('spline5_jnt',chr+'_Spine3')
    edo_tryLocationHumanIkSkeleton('spline6_jnt',chr+'_Spine4')
    edo_tryLocationHumanIkSkeleton('spline7_jnt',chr+'_Spine5')
    edo_tryLocationHumanIkSkeleton('spline8_jnt',chr+'_Spine6')
    edo_tryLocationHumanIkSkeleton('spline9_jnt',chr+'_Spine7')
    edo_tryLocationHumanIkSkeleton('spline10_jnt',chr+'_Spine8')
    edo_tryLocationHumanIkSkeleton('spline11_jnt',chr+'_Spine9')
    edo_tryLocationHumanIkSkeleton('spline12_jnt',chr+'_Spine10')
    edo_tryLocationHumanIkSkeleton('neck1_jnt',chr+'_Neck')
    edo_tryLocationHumanIkSkeleton('neck2_jnt',chr+'_Neck1')
    edo_tryLocationHumanIkSkeleton('neck3_jnt',chr+'_Neck2')
    edo_tryLocationHumanIkSkeleton('neck4_jnt',chr+'_Neck3')
    edo_tryLocationHumanIkSkeleton('neck5_jnt',chr+'_Neck4')
    edo_tryLocationHumanIkSkeleton('neck6_jnt',chr+'_Neck5')
    edo_tryLocationHumanIkSkeleton('neck7_jnt',chr+'_Neck6')
    edo_tryLocationHumanIkSkeleton('neck8_jnt',chr+'_Neck7')
    edo_tryLocationHumanIkSkeleton('neck9_jnt',chr+'_Neck8')
    edo_tryLocationHumanIkSkeleton('neck10_jnt',chr+'_Neck9')
    edo_tryLocationHumanIkSkeleton('head_jnt',chr+'_Head')
    #leg
    edo_tryLocationHumanIkSkeleton('Lf_Leg1_jnt',chr+'_LeftUpLeg')
    edo_tryLocationHumanIkSkeleton('Lf_Leg3_jnt',chr+'_LeftUpLegRoll')
    edo_tryLocationHumanIkSkeleton('Lf_knee_drv_jnt',chr+'_LeftLeg')
    edo_tryLocationHumanIkSkeleton('Lf_Leg7_jnt',chr+'_LeftLegRoll')
    edo_tryLocationHumanIkSkeleton('Lf_Leg9_jnt',chr+'_LeftFoot')
    edo_tryLocationHumanIkSkeleton('Lf_foot_drv',chr+'_LeftToeBase')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_thumb1_jnt',chr+'_LeftFootExtraFinger1')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_thumb2_jnt',chr+'_LeftFootExtraFinger2')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_thumb3_jnt',chr+'_LeftFootExtraFinger3')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_thumb4_jnt',chr+'_LeftFootExtraFinger4')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_index1_jnt',chr+'_LeftFootIndex1')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_index2_jnt',chr+'_LeftFootIndex2')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_index3_jnt',chr+'_LeftFootIndex3')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_index4_jnt',chr+'_LeftFootIndex4')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_mid1_jnt',chr+'_LeftFootMiddle1')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_mid2_jnt',chr+'_LeftFootMiddle2')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_mid3_jnt',chr+'_LeftFootMiddle3')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_mid4_jnt',chr+'_LeftFootMiddle4')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_ring1_jnt',chr+'_LeftFootRing1')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_ring2_jnt',chr+'_LeftFootRing2')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_ring3_jnt',chr+'_LeftFootRing3')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_ring4_jnt',chr+'_LeftFootRing4')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_pinky1_jnt',chr+'_LeftFootPinky1')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_pinky2_jnt',chr+'_LeftFootPinky2')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_pinky3_jnt',chr+'_LeftFootPinky3')
    edo_tryLocationHumanIkSkeleton('Lf_Toe_pinky4_jnt',chr+'_LeftFootPinky4')
    #arm
    edo_tryLocationHumanIkSkeleton('Lf_clavicle1_jnt',chr+'_LeftShoulder')
    edo_tryLocationHumanIkSkeleton('Lf_Arm1_jnt',chr+'_LeftArm')
    edo_tryLocationHumanIkSkeleton('Lf_Arm3_jnt',chr+'_LeftArmRoll')
    edo_tryLocationHumanIkSkeleton('Lf_elbow_drv_jnt',chr+'_LeftForeArm')
    edo_tryLocationHumanIkSkeleton('Lf_Arm7_jnt',chr+'_LeftForeArmRoll')
    edo_tryLocationHumanIkSkeleton('Lf_Arm9_jnt',chr+'_LeftHand')
    edo_tryLocationHumanIkSkeleton('Lf_thumb1_jnt',chr+'_LeftHandThumb1')
    edo_tryLocationHumanIkSkeleton('Lf_thumb2_jnt',chr+'_LeftHandThumb2')
    edo_tryLocationHumanIkSkeleton('Lf_thumb3_jnt',chr+'_LeftHandThumb3')
    edo_tryLocationHumanIkSkeleton('Lf_thumb4_jnt',chr+'_LeftHandThumb4')
    edo_tryLocationHumanIkSkeleton('Lf_index1_jnt',chr+'_LeftHandIndex1')
    edo_tryLocationHumanIkSkeleton('Lf_index2_jnt',chr+'_LeftHandIndex2')
    edo_tryLocationHumanIkSkeleton('Lf_index3_jnt',chr+'_LeftHandIndex3')
    edo_tryLocationHumanIkSkeleton('Lf_index4_jnt',chr+'_LeftHandIndex4')
    edo_tryLocationHumanIkSkeleton('Lf_mid1_jnt',chr+'_LeftHandMiddle1')
    edo_tryLocationHumanIkSkeleton('Lf_mid2_jnt',chr+'_LeftHandMiddle2')
    edo_tryLocationHumanIkSkeleton('Lf_mid3_jnt',chr+'_LeftHandMiddle3')
    edo_tryLocationHumanIkSkeleton('Lf_mid4_jnt',chr+'_LeftHandMiddle4')
    edo_tryLocationHumanIkSkeleton('Lf_ring1_jnt',chr+'_LeftHandRing1')
    edo_tryLocationHumanIkSkeleton('Lf_ring2_jnt',chr+'_LeftHandRing2')
    edo_tryLocationHumanIkSkeleton('Lf_ring3_jnt',chr+'_LeftHandRing3')
    edo_tryLocationHumanIkSkeleton('Lf_ring4_jnt',chr+'_LeftHandRing4')
    edo_tryLocationHumanIkSkeleton('Lf_pinky1_jnt',chr+'_LeftHandPinky1')
    edo_tryLocationHumanIkSkeleton('Lf_pinky2_jnt',chr+'_LeftHandPinky2')
    edo_tryLocationHumanIkSkeleton('Lf_pinky3_jnt',chr+'_LeftHandPinky3')
    edo_tryLocationHumanIkSkeleton('Lf_pinky4_jnt',chr+'_LeftHandPinky4')
    #leg
    edo_tryLocationHumanIkSkeleton('Rt_Leg1_jnt',chr+'_RightUpLeg')
    edo_tryLocationHumanIkSkeleton('Rt_Leg3_jnt',chr+'_RightUpLegRoll')
    edo_tryLocationHumanIkSkeleton('Rt_knee_drv_jnt',chr+'_RightLeg')
    edo_tryLocationHumanIkSkeleton('Rt_Leg7_jnt',chr+'_RightLegRoll')
    edo_tryLocationHumanIkSkeleton('Rt_Leg9_jnt',chr+'_RightFoot')
    edo_tryLocationHumanIkSkeleton('Rt_foot_drv',chr+'_RightToeBase')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_thumb1_jnt',chr+'_RightFootExtraFinger1')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_thumb2_jnt',chr+'_RightFootExtraFinger2')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_thumb3_jnt',chr+'_RightFootExtraFinger3')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_thumb4_jnt',chr+'_RightFootExtraFinger4')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_index1_jnt',chr+'_RightFootIndex1')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_index2_jnt',chr+'_RightFootIndex2')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_index3_jnt',chr+'_RightFootIndex3')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_index4_jnt',chr+'_RightFootIndex4')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_mid1_jnt',chr+'_RightFootMiddle1')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_mid2_jnt',chr+'_RightFootMiddle2')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_mid3_jnt',chr+'_RightFootMiddle3')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_mid4_jnt',chr+'_RightFootMiddle4')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_ring1_jnt',chr+'_RightFootRing1')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_ring2_jnt',chr+'_RightFootRing2')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_ring3_jnt',chr+'_RightFootRing3')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_ring4_jnt',chr+'_RightFootRing4')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_pinky1_jnt',chr+'_RightFootPinky1')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_pinky2_jnt',chr+'_RightFootPinky2')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_pinky3_jnt',chr+'_RightFootPinky3')
    edo_tryLocationHumanIkSkeleton('Rt_Toe_pinky4_jnt',chr+'_RightFootPinky4')
    #arm
    edo_tryLocationHumanIkSkeleton('Rt_clavicle1_jnt',chr+'_RightShoulder')
    edo_tryLocationHumanIkSkeleton('Rt_Arm1_jnt',chr+'_RightArm')
    edo_tryLocationHumanIkSkeleton('Rt_Arm3_jnt',chr+'_RightArmRoll')
    edo_tryLocationHumanIkSkeleton('Rt_elbow_drv_jnt',chr+'_RightForeArm')
    edo_tryLocationHumanIkSkeleton('Rt_Arm7_jnt',chr+'_RightForeArmRoll')
    edo_tryLocationHumanIkSkeleton('Rt_Arm9_jnt',chr+'_RightHand')
    edo_tryLocationHumanIkSkeleton('Rt_thumb1_jnt',chr+'_RightHandThumb1')
    edo_tryLocationHumanIkSkeleton('Rt_thumb2_jnt',chr+'_RightHandThumb2')
    edo_tryLocationHumanIkSkeleton('Rt_thumb3_jnt',chr+'_RightHandThumb3')
    edo_tryLocationHumanIkSkeleton('Rt_thumb4_jnt',chr+'_RightHandThumb4')
    edo_tryLocationHumanIkSkeleton('Rt_index1_jnt',chr+'_RightHandIndex1')
    edo_tryLocationHumanIkSkeleton('Rt_index2_jnt',chr+'_RightHandIndex2')
    edo_tryLocationHumanIkSkeleton('Rt_index3_jnt',chr+'_RightHandIndex3')
    edo_tryLocationHumanIkSkeleton('Rt_index4_jnt',chr+'_RightHandIndex4')
    edo_tryLocationHumanIkSkeleton('Rt_mid1_jnt',chr+'_RightHandMiddle1')
    edo_tryLocationHumanIkSkeleton('Rt_mid2_jnt',chr+'_RightHandMiddle2')
    edo_tryLocationHumanIkSkeleton('Rt_mid3_jnt',chr+'_RightHandMiddle3')
    edo_tryLocationHumanIkSkeleton('Rt_mid4_jnt',chr+'_RightHandMiddle4')
    edo_tryLocationHumanIkSkeleton('Rt_ring1_jnt',chr+'_RightHandRing1')
    edo_tryLocationHumanIkSkeleton('Rt_ring2_jnt',chr+'_RightHandRing2')
    edo_tryLocationHumanIkSkeleton('Rt_ring3_jnt',chr+'_RightHandRing3')
    edo_tryLocationHumanIkSkeleton('Rt_ring4_jnt',chr+'_RightHandRing4')
    edo_tryLocationHumanIkSkeleton('Rt_pinky1_jnt',chr+'_RightHandPinky1')
    edo_tryLocationHumanIkSkeleton('Rt_pinky2_jnt',chr+'_RightHandPinky2')
    edo_tryLocationHumanIkSkeleton('Rt_pinky3_jnt',chr+'_RightHandPinky3')
    edo_tryLocationHumanIkSkeleton('Rt_pinky4_jnt',chr+'_RightHandPinky4')
    
    

    
def edo_saveCharacterSkeletionPosition(chr):
    cmds.setAttr(chr+'.InputCharacterizationLock',True)
    hikjoints=cmds.listConnections(chr,s=1,p=0,type='joint')
    for hj in hikjoints:
        print hj
        #hi=hikjoints[0]
        pl=cmds.listConnections(hj+'.Character',chr,d=1,s=0,p=1,type='HIKCharacterNode')[0]
        attr=pl.split('.')[1]
        cmds.setAttr(chr+'.'+attr+'Tx',cmds.xform(hj,q=1,ws=1,t=1)[0])
        cmds.setAttr(chr+'.'+attr+'Ty',cmds.xform(hj,q=1,ws=1,t=1)[1])
        cmds.setAttr(chr+'.'+attr+'Tz',cmds.xform(hj,q=1,ws=1,t=1)[2])
        cmds.setAttr(chr+'.'+attr+'Rx',cmds.xform(hj,q=1,ws=1,ro=1)[0])
        cmds.setAttr(chr+'.'+attr+'Ry',cmds.xform(hj,q=1,ws=1,ro=1)[1])
        cmds.setAttr(chr+'.'+attr+'Rz',cmds.xform(hj,q=1,ws=1,ro=1)[2])
        cmds.setAttr(chr+'.'+attr+'Sx',cmds.xform(hj,q=1,ws=1,s=1)[0])
        cmds.setAttr(chr+'.'+attr+'Sy',cmds.xform(hj,q=1,ws=1,s=1)[1])
        cmds.setAttr(chr+'.'+attr+'Sz',cmds.xform(hj,q=1,ws=1,s=1)[2])
    

def edo_snapMotionBuilderChrJointToGDCrig(chr):
    pcons=[]
    #body
    pc=cmds.pointConstraint('Master',chr+'_Reference',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('waist_Ctrl',chr+'_Hips',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('waist_FK1_ctrl',chr+'_Spine',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('waist_FK2_ctrl',chr+'_Spine1',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('neck_FK_ctrl',chr+'_Neck',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('head_ctrl',chr+'_Head',mo=0)
    pcons.append(pc[0])
    #leg
    pc=cmds.pointConstraint('LfLeg_Leg_FK',chr+'_LeftUpLeg',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfLeg_Knee_FK',chr+'_LeftLeg',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfLeg_Ankle_FK',chr+'_LeftFoot',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfLegLeg_ball_FK',chr+'_LeftToeBase',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtLeg_Leg_FK',chr+'_RightUpLeg',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtLeg_Knee_FK',chr+'_RightLeg',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtLeg_Ankle_FK',chr+'_RightFoot',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtLegLeg_ball_FK',chr+'_RightToeBase',mo=0)
    pcons.append(pc[0])
    #arm
    pc=cmds.pointConstraint('Lf_shoulder',chr+'_LeftShoulder',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfArm_UpArm_FK',chr+'_LeftArm',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfArm_Elbow_FK',chr+'_LeftForeArm',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfArm_Wrist_FK',chr+'_LeftHand',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('Rt_shoulder',chr+'_RightShoulder',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtArm_UpArm_FK',chr+'_RightArm',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtArm_Elbow_FK',chr+'_RightForeArm',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtArm_Wrist_FK',chr+'_RightHand',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('LfArm_wristMid_FK',chr+'_LeftFingerBase',mo=0)
    pcons.append(pc[0])
    pc=cmds.pointConstraint('RtArm_wristMid_FK',chr+'_RightFingerBase',mo=0)
    pcons.append(pc[0])
    cmds.delete(pcons)
    
#edo_motionBuilderJointConstraintChrCtrl('mocap_to_gdcRig')
def edo_motionBuilderJointConstraintChrCtrl(chr):
    #chr='mocap_to_gdcRig'
    #body
    pc=cmds.parentConstraint(chr+'_Reference','Master',mo=1)
    pc=cmds.parentConstraint(chr+'_Hips','waist_Ctrl',mo=1)
    pc=cmds.parentConstraint(chr+'_Spine','waist_FK1_ctrl',mo=1)
    pc=cmds.parentConstraint(chr+'_Spine1','waist_FK2_ctrl',mo=1)
    pc=cmds.parentConstraint(chr+'_Neck','neck_FK_ctrl',mo=1)
    pc=cmds.parentConstraint(chr+'_Head','head_ctrl',mo=1)
    #Lfleg
    pc=cmds.parentConstraint(chr+'_LeftUpLeg','LfLeg_Leg_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_LeftLeg','LfLeg_Knee_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_LeftFoot','LfLeg_Ankle_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_LeftToeBase','LfLegLeg_ball_FK',mo=1,st=['x','y','z'])
    pc=cmds.pointConstraint(chr+'_LeftLeg','LfLeg_Pole_ctrl',mo=0)
    pc=cmds.parentConstraint(chr+'_LeftFoot','LfLeg_Leg_IK',mo=1)
    cmds.createNode('multiplyDivide',n='LfToe_motionbuilder_multiplyDivide')
    cmds.setAttr('LfToe_motionbuilder_multiplyDivide.input2X',-1)
    cmds.connectAttr(chr+'_LeftToeBase.rx','LfToe_motionbuilder_multiplyDivide.input1X',f=1)
    cmds.connectAttr('LfToe_motionbuilder_multiplyDivide.outputX','LfLeg_Leg_IK.raiseToe',f=1)
    cmds.connectAttr(chr+'_LeftToeBase.ry','LfLeg_Leg_IK.swivelToe',f=1)
    cmds.connectAttr(chr+'_LeftToeBase.rz','LfLeg_Leg_IK.twistToe',f=1)
    #RtLeg
    pc=cmds.parentConstraint(chr+'_RightUpLeg','RtLeg_Leg_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightLeg','RtLeg_Knee_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightFoot','RtLeg_Ankle_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightToeBase','RtLegLeg_ball_FK',mo=1,st=['x','y','z'])
    pc=cmds.pointConstraint(chr+'_RightLeg','RtLeg_Pole_ctrl',mo=0)
    pc=cmds.parentConstraint(chr+'_RightFoot','RtLeg_Leg_IK',mo=1)
    cmds.createNode('multiplyDivide',n='RtToe_motionbuilder_multiplyDivide')
    cmds.setAttr('RtToe_motionbuilder_multiplyDivide.input2X',-1)
    cmds.setAttr('RtToe_motionbuilder_multiplyDivide.input2Y',-1)
    cmds.setAttr('RtToe_motionbuilder_multiplyDivide.input2Z',-1)
    cmds.connectAttr(chr+'_RightToeBase.rx','RtToe_motionbuilder_multiplyDivide.input1X',f=1)
    cmds.connectAttr('RtToe_motionbuilder_multiplyDivide.outputX','RtLeg_Leg_IK.raiseToe',f=1)
    cmds.setAttr('RtToe_motionbuilder_multiplyDivide.input2Z',-1)
    cmds.connectAttr(chr+'_RightToeBase.ry','RtToe_motionbuilder_multiplyDivide.input1Y',f=1)
    cmds.connectAttr('RtToe_motionbuilder_multiplyDivide.outputY','RtLeg_Leg_IK.swivelToe',f=1)
    cmds.connectAttr(chr+'_RightToeBase.rz','RtToe_motionbuilder_multiplyDivide.input1Z',f=1)
    cmds.connectAttr('RtToe_motionbuilder_multiplyDivide.outputZ','RtLeg_Leg_IK.twistToe',f=1)
    #arm
    pc=cmds.parentConstraint(chr+'_LeftShoulder','Lf_shoulder',mo=1)
    pc=cmds.parentConstraint(chr+'_LeftArm','LfArm_UpArm_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_LeftForeArm','LfArm_Elbow_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_LeftHand','LfArm_Wrist_FK',mo=1,st=['x','y','z'])
    pc=cmds.pointConstraint(chr+'_LeftForeArm','LfArm_Pole_ctrl',mo=0)
    pc=cmds.parentConstraint(chr+'_LeftHand','LfArm_Wrist_IK',mo=1)
    pc=cmds.parentConstraint(chr+'_RightShoulder','Rt_shoulder',mo=1)
    pc=cmds.parentConstraint(chr+'_RightArm','RtArm_UpArm_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightForeArm','RtArm_Elbow_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightHand','RtArm_Wrist_FK',mo=1,st=['x','y','z'])
    pc=cmds.pointConstraint(chr+'_RightForeArm','RtArm_Pole_ctrl',mo=0)
    pc=cmds.parentConstraint(chr+'_RightHand','RtArm_Wrist_IK',mo=1)
    pc=cmds.parentConstraint(chr+'_LeftFingerBase','LfArm_wristMid_FK',mo=1,st=['x','y','z'])
    pc=cmds.parentConstraint(chr+'_RightFingerBase','RtArm_wristMid_FK',mo=1,st=['x','y','z'])