global proc s100VRUI()
	{
	s100VRcorrectRotateOrderParented;
		if(`window -ex 	s100VRUI`)
			deleteUI s100VRUI;

		window -title "studio 100 Vegetations AutoRig"  -h 400  s100VRUI;
		columnLayout -adjustableColumn true s100VRUICLMain;


	menuBarLayout s100VRUIMLMain;

		menu -en 0 -label "Edit" -helpMenu true;
			menuItem -en 1 -c s100VRCleanVRUI   -label "clean";


	$cmd = s100openWikiTo("VR") ;



		menu -en 0 -label "Help" -helpMenu true;
			menuItem -en 1 -c s100VRUI   -label "refresh";
			menuItem -en 1 -c $cmd   -label "help";
			menuItem -en 0  -label "About...";

		setParent ..;


			window -e -h 575 -w 460 -sizeable 0  s100VRUI;
		showWindow;


	formLayout s100VRUIFLMain;

		$txLibray = `text -l "Asset Name :"`;
		$prodMenu = `textField -w 200 -ed 0 s100VRUITFAssetName`;
		$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;
		$editAN = `button -en 0 -w 50  -l "edit" -c s100VREditNameUI s100VREditNameBt `;


		$ico1 =`text -label ""  `;
		$ico2= `iconTextButton -annotation "CV Curve Tool" -i "curveCV.xpm" -c CVCurveTool `;
		$ico3= `iconTextButton -annotation "Rebuild Curve" -i "rebuildCurve.xpm" -c RebuildCurveOptions  `;
		$ico4= `iconTextButton -annotation "create locator" -i "locator.xpm" -c CreateLocator  `;


		$tx = `text -label "tools"`;

	$tab = `tabLayout -cc s100VRrefreshUI -innerMarginWidth 5 -innerMarginHeight 5 s100VRUITLMain`;
	formLayout -edit

		 //Prod
		-attachForm $txLibray "top"    10
		-attachForm $txLibray "left"   10
		-attachForm $prodMenu "top"    5
		-attachControl $prodMenu "left"   5 $txLibray
		-attachForm $newAN "top"    5
		-attachForm $editAN "top"    5
		-attachControl $newAN "left"   5 $prodMenu
		-attachControl $editAN "left"   5 $newAN


		-attachControl s100VRUITLMain "top"   5 $prodMenu
		 -attachForm s100VRUITLMain "left"   0
		 -attachForm s100VRUITLMain "bottom" 0
		 -attachForm s100VRUITLMain "right" 50


			 -attachForm $tx "top"   35

			-attachControl $ico1 "top"   0 $tx
			-attachControl $ico2 "top"   0 $ico1
			-attachControl $ico3 "top"   0 $ico2
			-attachControl $ico4 "top"   0 $ico3

			 -attachControl $tx "left"   12 s100VRUITLMain
			 -attachControl $ico1 "left"   0 s100VRUITLMain
			 -attachControl $ico2 "left"   0 s100VRUITLMain
			 -attachControl $ico3 "left"   0 s100VRUITLMain
			 -attachControl $ico4 "left"   0 s100VRUITLMain

			  -attachForm s100VRUITLMain "left"  5


		 s100VRUIFLMain;

		$weBt = 185 ;

		$weTx = 360 ;
		 formLayout -h 450 s100VRFLFlower;




		$textAutoRig = `text -l  "Auto Rig : " `;
		//$txFlSCurv= `text -label "select a curve first, then click on :" `;
		$btAddCurvPip = `button -w $weBt -l "add Curve/loc to Auto Rig or modify it" -c s100VRaddVegetationToAutoRigUI s100VRaddVegetationToAutoRigUIbt`;
		$btRemCurvPip = `button -w $weBt -l "rem Curve/loc from Auto Rig " -c s100VRRemGuideFromAR s100VRRemGuideFromARbt`;
		$sep1 = `separator -w $weTx`;

		$btShowAllAR = `button -w $weBt -l "show all auto rig" -c s100VRShowAllAR s100VRARbtShowAllARbt `;
		$btHideAllAR = `button -w $weBt -l "hide all auto rig" -c s100VRHideAllAR s100VRARbtHideAllARbt`;


		$btIsolateAR = `button -w $weBt -l "Isolate auto rig selected" -c s100VRIsolateSelectedAR s100VRIsolateSelectedARbt`;


		$tx = "select a curve first or a locator , then click on :" ;

		$txFlSCurv = `scrollField  -w $weTx  -editable 0 -wordWrap 1 -text $tx ` ;



		$textRig = `text -l  "Rig : " `;


		$txE = "when you have finish your auto rig" ;
		$txRigIT = `scrollField  -w $weTx  -editable 0 -wordWrap 1 -text $txE ` ;

		$buttonRig = `button -w $weBt -l "rig it!" -c s100VRRigIt s100VRRigItbt`;
		formLayout -e


		-attachForm $textAutoRig "top"    5
		-attachForm $textAutoRig "left"    5

		-attachControl $txFlSCurv "top"    5 $textAutoRig
		-attachForm $txFlSCurv "left"    5


		-attachControl $btAddCurvPip "top"   5 $txFlSCurv
		-attachControl $btRemCurvPip "top"   5 $txFlSCurv
		-attachControl $btRemCurvPip "left"   5 $btAddCurvPip

		-attachControl $sep1 "top"   5 $btRemCurvPip



		-attachControl $btShowAllAR "top"   5 $sep1

		-attachControl $btHideAllAR "top"   5 $sep1
		-attachControl $btHideAllAR "left"   5 $btShowAllAR


		-attachControl $btIsolateAR "top"   5 $btShowAllAR




		-attachForm $textRig "top" 200
		-attachControl $txRigIT "top" 5 $textRig
		-attachControl $buttonRig "top"   5 $txRigIT


		s100VRFLFlower;
	setParent .. ;
	s100VRUISkinLayout ;

	s100VRUIAELayout ;
	s100VRUIUtilsLayout;
	s100VRUITLMainModif ;

	s100VRRZaddLayoutS100 ;
	s100VRrefreshUI;


	}


global proc s100VRcorrectRotateOrderParented()
{
	if(`objExists "parented_grp"`)
	{
	setAttr -l false "parented_grp.rotateOrder";
	setAttr parented_grp.rotateOrder 1;
	setAttr -l true "parented_grp.rotateOrder";

	}

}
global proc s100VRUISkinLayout()
	{

		$weBt = 185 ;
		$weTx = 370 ;

		setParent s100VRUITLMain ;

	if(`formLayout -ex s100VRSkin`)
		{
		deleteUI s100VRSkin ;
		}

		 formLayout -h 450 s100VRSkin;



	$text = `text -l "This will skin all the object"` ;
	$text1 = `text -l "in the deformed_grp to the rig"` ;



	$butRandomize = `button -en 0 -w $weBt  -l "skin All" -c s100VRSkinProc s100VRSkinProcBt`;



	//$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;

		 formLayout -e

		 -attachForm $text "top" 5
		 -attachControl $text1 "top" 5 $text
		 -attachControl $butRandomize "top" 5 $text1



		 s100VRSkin;



	}

global proc s100VRUIAELayout()
{
//s100VRAddmultiAmplitudeOnRig ;
		$weBt = 185 ;
		$weTx = 370 ;

		setParent s100VRUITLMain ;

	if(`formLayout -ex s100VRATEffect`)
		{
		deleteUI s100VRATEffect ;
		}

		formLayout -h 450 s100VRATEffect;

	$prog = `progressBar -w $weTx s100VRUIAELayoutPB`;
	$progS = `progressBar -w $weTx s100VRUIAELayoutPBsmall`;

	$buttonAE1 = `button  -w $weBt  -l "add / refresh AE" -c s100VRcreateAttributControlAE `;
	$buttonDeleteAE = `button -w $weBt  -l "delete AE" -c ("s100VRDeleteAE;s100VRrefreshUI") `;
	$sep = `separator -w $weTx s100VRUIAELayoutSep` ;



	$ctrl = "VRAE_main_ctrl" ;

	//$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;

		 formLayout -e
		 -attachForm $prog "top" 0
			 -attachControl $progS "top" 0 $prog

		 -attachControl $buttonAE1 "top" 0 $progS
		 -attachControl $buttonDeleteAE "top" 0 $progS

		 -attachForm $prog "left" 0
		 -attachForm $buttonAE1 "left" 0
		 -attachControl $buttonDeleteAE "left" 0 $buttonAE1
		 -attachControl $sep "top" 0 $buttonAE1




		 s100VRATEffect;
$cmd = "s100presetAEtoTest( \"s100presetAEtoTestOMVR\",\"VRAE_main_ctrl\" )";
		if(`objExists $ctrl`)
		{


			$textC = `text -w 150 -font "smallBoldLabelFont" -l "Main Controler"` ;
			$btSel = `button  -w $weBt  -l "select ctrl" -c s100VRAESelectAECtrl`;
			$btKey = `button  -w $weBt  -l "key ctrl" -c s100VRAEKeyAECtrl`;


			$fRotY = `attrFieldSliderGrp -min -180 -max 180 -at ($ctrl +".rotateY")`;


			//$fAmp = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".amplitude")`;



			$fAmp = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".amplitude")`;
			$fFreq = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".frequence")`;
			$fRot = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".wingsRot")`;
			$sep1 = `separator -w $weTx ` ;
			$option = `optionMenuGrp -changeCommand $cmd  -label "preset" 	s100presetAEtoTestOMVR `;

			 		menuItem -label "default" ;
			 		menuItem -label "slight wind" ;
					menuItem -label "strong wind" ;
					menuItem -label "storm" ;

			$text3 = `text -w 150 -font "smallBoldLabelFont" -l "object to modify"`;
   			$scrollList = `textScrollList -selectCommand s100refreshAElistObjectSel -h 150 -w 150 s100VRAElistObject`;
			//$col = `button  -w $weBt  -l "key ctrl" -c s100VRAEKeyAECtrl`;


			$text5 = `text -l "multiply :"` ;
			$floatB5 = `floatField -en 0 -minValue .001 -maxValue 10 -precision 2   -changeCommand s100VRchangeMDValue s100VRAEFBMDAMP` ;


		//GRADIENT LAYOUT
			$col = `columnLayout  -adjustableColumn 1 -backgroundColor .1 .1 .1`;
			textField -en 0 s100VRGradientTF ;
			separator -w 220 ;
			text -label "Amplitude by chaine :" ;
			$grad = `gradientControlNoAttr  -dragCommand s100VRGiveValueToAttrFromGradientAmp -h 70 s100VRfalloffCurve `;

			$textGrad = `text -label "OverLap by chaine :" `;

			$grad2 = `gradientControlNoAttr -dragCommand s100VRGiveValueToAttrFromGradientOverLap   -h 70 s100VRfalloffCurve2 `;


			setParent.. ;
			 formLayout -e

			 -attachControl $textC "top" 5 $sep
			 -attachControl $btSel "top" 5 $textC
			 -attachControl $btKey "top" 5 $textC
			 -attachControl $btKey "left" 5 $btSel

			 	 -attachControl $option "top" 5 $btSel


			 -attachControl $fRotY "top" 5 $option
			 -attachControl $fAmp "top" 5 $fRotY


			 -attachControl $fFreq "top" 0 $fAmp
			 -attachControl $fRot "top" 0 $fFreq
			 -attachControl $sep1 "top" 0 $fRot

 			 -attachControl $text3 "top" 0 $sep1

			 -attachControl $scrollList "top" 5 $text3

			 -attachControl $col "top" 5 $text3
			 -attachControl $col "left" 5 $scrollList

			-attachControl $text5 "top" 7 $scrollList
			-attachControl $floatB5 "top" 5 $scrollList
			-attachControl $floatB5 "left" 5 $text5




			 s100VRATEffect;

		}
formLayout -e  -h 450 s100VRATEffect;

}


global proc s100VRUIUtilsLayout()
{

		$weBt = 185 ;
		$weTx = 370 ;

		setParent s100VRUITLMain ;

	if(`formLayout -ex s100VRUIUtilsLayout`)
		{
		deleteUI s100VRUIUtilsLayout ;
		}

		 formLayout -h 450 s100VRUIUtilsLayout;


	$butPose = `button -en 0 -w $weBt  -l "ResetPose" -c s100VRVRDefautPose s100VRVRDefautPoseBt`;
	$sep = `separator -w $weTx` ;

	$text = `text -l "randomize time"` ;
	$tMin =  `text -l "min:"` ;
	$tMax =  `text -l "max:"` ;


	$minRand = `floatField -w 50 -v -10   s100VRminRandFG`;
	$maxRand = `floatField -w 50  -v 10   s100VRmaxRandFG`;

	$butRandomize = `button -en 0 -w $weBt  -l "Randomize Vegetation" -c s100VRRandomize  s100VRRandomizeBt`;
	$sep1 = `separator -w $weTx ` ;


	//$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;

		 formLayout -e

		 -attachForm $butPose "top" 5
		 -attachControl $sep "top" 5 $butPose

		 -attachControl $text "top" 5 $sep

		 -attachControl $tMin "top" 5 $text
 		 -attachControl $minRand "top" 5 $text
 		 -attachControl $minRand "left" 5 $tMin

		 -attachControl $tMax "top" 5 $text
		  -attachControl $tMax "left" 5 $minRand
 		 -attachControl $maxRand "top" 5 $text
 		 -attachControl $maxRand "left" 5 $tMax

		 -attachControl $butRandomize "top" 5 $maxRand








		s100VRUIUtilsLayout;



}

global proc s100VRUIAELayoutRefresh()
{
	$ctrl = "VRAE_main_ctrl" ;
	$sep = "s100VRUIAELayoutSep" ;
	$cmd = "s100presetAEtoTest( \"s100presetAEtoTestOMVR\", \"" +$ctrl +"\" ) ";

	if(`objExists "VMAE_main_ctrl"  `)
	{
		if(`attrFieldSliderGrp -ex s100VMattrFAmp `)
		{
		attrFieldSliderGrp -e -en 1  s100VMattrFAmp;
		attrFieldSliderGrp -e -en 1 s100VMattrFFreq;
		attrFieldSliderGrp -e -en 1 s100VMattrFRot;
        }else{
		$weBt = 185 ;
		$weTx = 370 ;


		$form ="s100VRATEffect";
			$textC = `text -p  $form -w 150 -font "smallBoldLabelFont" -l "Main Controler"` ;
			$btSel = `button -p  $form   -w $weBt  -l "select ctrl" -c s100VMAESelectAECtrl`;
			$btKey = `button -p  $form   -w $weBt  -l "key ctrl" -c s100VMAEKeyAECtrl`;


			$fRotY = `attrFieldSliderGrp  -p  $form -min -180 -max 180 -at ($ctrl +".rotateY")`;


			//$fAmp = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".amplitude")`;



			$fAmp = `attrFieldSliderGrp -p  $form  -min 0 -max 10 -at ($ctrl +".amplitude") s100VMattrFAmp`;
			$fFreq = `attrFieldSliderGrp -p  $form  -min 0 -max 10 -at ($ctrl +".frequence")s100VMattrFFreq`;
			$fRot = `attrFieldSliderGrp -p  $form  -min 0 -max 10 -at ($ctrl +".wingsRot")s100VMattrFRot`;
			$sep1 = `separator -p  $form  -w $weTx ` ;
			$option = `optionMenuGrp -p  $form  -changeCommand $cmd  -label "preset" 	s100presetAEtoTestOMVR `;

			 		menuItem -label "default" ;
			 		menuItem -label "slight wind" ;
					menuItem -label "strong wind" ;
					menuItem -label "storm" ;



			 formLayout -e

			 -attachControl $textC "top" 5 $sep
			 -attachControl $btSel "top" 5 $textC
			 -attachControl $btKey "top" 5 $textC
			 -attachControl $btKey "left" 5 $btSel

			 -attachControl $option "top" 5 $btSel


			 -attachControl $fRotY "top" 5 $option
			 -attachControl $fAmp "top" 5 $fRotY


			 -attachControl $fFreq "top" 0 $fAmp
			 -attachControl $fRot "top" 0 $fFreq
			 -attachControl $sep1 "top" 0 $fRot



			 $form ;

        }

    }

formLayout -e  -h 450 s100VRATEffect;
}

global proc s100VRUITLMainModif()
	{

	//tabLayout -
		 tabLayout -edit
		 -tabLabel s100VRFLFlower "autoRig"
		-tabLabel s100VRSkin "skinning"
		 -tabLabel s100VRATEffect "atmosphereEffectTest"
		 -tabLabel s100VRUIUtilsLayout "utils"

			 s100VRUITLMain;

	}

