/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc nj2015_checkCoincidentCallback(string $floatField)
{
	if (!`pluginInfo -q -loaded -name "checkCoincident.mll"`)
		loadPlugin "checkCoincident.mll";

	// get the tolerance value

	float $tolerance = `floatFieldGrp -q -value1 $floatField`;

	// execute command 

	eval("checkCoincident " + $tolerance);
}

global proc nj2015_checkColliearCallback(string $floatField)
{
	if (!`pluginInfo -q -loaded -name "checkStrayPoint.mll"`)
		loadPlugin "checkStrayPoint.mll";

	// get the tolerance value

	float $tolerance = `floatFieldGrp -q -value1 $floatField`;

	// execute command 

	eval("checkStrayPoint " + $tolerance);
}

global proc nj2015_selectProblemObj()
{
	string $selected[] = `ls -selection`;

	select -clear;

	for ($item in $selected)
	{
		string $buf[];

		if (`tokenize $item "." $buf` > 1)
			select -add $buf[0];
	}
}

global proc nj2015_CheckVertex()
{
	if(!`window -exists nj2015_CheckPointWindow`)
	{
		window -menuBar true -title "检查重叠点与废点" -width 290 -height 103 nj2015_CheckPointWindow;

			menu -label "请看说明";
				menuItem -label "使用帮助..." -command "zjHelpCallback nj2015_CheckVertex";

			columnLayout -rowSpacing 5 -adjustableColumn true;

   				string $formLayout = `formLayout`;
					string $child0 = `text -label "检查重合点 —— —— (请先选中模型)"`;
					string $child1 = `floatFieldGrp -columnWidth 1 80 -label "距离:" -precision 4 -value1 0.001`;
					string $child2 = `button -label "选取点" -command ("nj2015_checkCoincidentCallback " + $child1)`;
					string $child3 = `separator`;
				setParent ..;

				formLayout -edit
					-attachForm $child0 "top" 5 
					-attachForm $child0 "left" 10 

					-attachControl $child1 "top" 5 $child0
					-attachForm $child1 "left" 5 

					-attachControl $child2 "top" 5 $child0
					-attachControl $child2 "left" 5 $child1

					-attachControl $child3 "top" 10 $child1
					-attachForm $child3 "left" 5
					-attachForm $child3 "right" 5
				$formLayout;

   				string $formLayout = `formLayout`;
					string $child0 = `text -label "检查线上废点 —— —— (请先选中模型)"`;
					string $child1 = `floatFieldGrp -columnWidth 1 80 -label "距离:" -precision 4 -value1 0.001`;
					string $child2 = `button -label "选取点" -command ("nj2015_checkColliearCallback " + $child1)`;
					string $child3 = `separator`;
				setParent ..;

				formLayout -edit
					-attachForm $child0 "top" 5 
					-attachForm $child0 "left" 10 

					-attachControl $child1 "top" 5 $child0
					-attachForm $child1 "left" 5 

					-attachControl $child2 "top" 5 $child0
					-attachControl $child2 "left" 5 $child1

					-attachControl $child3 "top" 10 $child1
					-attachForm $child3 "left" 5
					-attachForm $child3 "right" 5
				$formLayout;

				button -label "选点转为选模型" -command "nj2015_selectProblemObj";

			setParent ..;
	}
	showWindow nj2015_CheckPointWindow;
}
