//////////////////////////////////////////////////////////
/// Author: liang
///
/// Creation Date: 2007/01/30
///
/// Description: ik跟随身体运动控制系统自动生成器
/// Modify: liang
//////////////////////////////////////////////////////////

global proc addIkFollowBodyCon(string $charName)
{
	float $tempFloatArray[3];
	
	
	//右手部分
	group -em -n ($charName + "_world_wristConGrp_right");
	$tempFloatArray = `joint -query -position ($charName + "_shoulder_right")` ;
	move -absolute -worldSpace $tempFloatArray[0] $tempFloatArray[1] $tempFloatArray[2] ($charName + "_world_wristConGrp_right") ;
	makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 ($charName + "_world_wristConGrp_right") ;
	parentConstraint -n ($charName + "_world_wristConGrp_right_parentConstraint") -mo -weight 1 ($charName + "_shoulder_right") ($charName + "_world_wristConGrp_right");
	
	rename `pairBlend -input2 -nd ($charName + "_world_wristConGrp_right") -at tx -at ty -at tz -at rx -at ry -at rz` ($charName + "_world_wristConGrp_pairBlend_right");
	addAttr -longName nonBodyFollow_rx ($charName + "_world_wristConGrp_right");
	addAttr -longName nonBodyFollow_ry ($charName + "_world_wristConGrp_right");
	addAttr -longName nonBodyFollow_rz ($charName + "_world_wristConGrp_right");
	addAttr -longName nonBodyFollow_tx ($charName + "_world_wristConGrp_right");
	addAttr -longName nonBodyFollow_ty ($charName + "_world_wristConGrp_right");
	addAttr -longName nonBodyFollow_tz ($charName + "_world_wristConGrp_right");
	
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_tx") ($charName + "_world_wristConGrp_pairBlend_right" + ".inTranslateX2");
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_ty") ($charName + "_world_wristConGrp_pairBlend_right" + ".inTranslateY2");
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_tz") ($charName + "_world_wristConGrp_pairBlend_right" + ".inTranslateZ2");
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_rx") ($charName + "_world_wristConGrp_pairBlend_right" + ".inRotateX2");
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_ry") ($charName + "_world_wristConGrp_pairBlend_right" + ".inRotateY2");
	connectAttr ($charName + "_world_wristConGrp_right.nonBodyFollow_rz") ($charName + "_world_wristConGrp_pairBlend_right" + ".inRotateZ2");
	
	parent ($charName + "_world_wristConGrp_right") ($charName + "_MASTER");
	parent ($charName + "_world_wristCon_right")($charName + "_world_wristConGrp_right");
	addAttr -longName followBodySwitch -attributeType "float" -minValue 0 -maxValue 1 -defaultValue 0 -keyable 1 ($charName + "_world_wristCon_right");
	shadingNode -asUtility reverse -n ($charName + "followBodySwitch_reverse_right");
	connectAttr ($charName + "_world_wristCon_right.followBodySwitch") ($charName + "followBodySwitch_reverse_right.inputX");
	connectAttr ($charName + "followBodySwitch_reverse_right.outputX") ($charName + "_world_wristConGrp_pairBlend_right.weight");

	
	//左手部分
	group -em -n ($charName + "_world_wristConGrp_left");
	$tempFloatArray = `joint -query -position ($charName + "_shoulder_left")` ;
	move -absolute -worldSpace $tempFloatArray[0] $tempFloatArray[1] $tempFloatArray[2] ($charName + "_world_wristConGrp_left") ;
	makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 ($charName + "_world_wristConGrp_left") ;
	parentConstraint -n ($charName + "_world_wristConGrp_left_parentConstraint") -mo -weight 1 ($charName + "_shoulder_left") ($charName + "_world_wristConGrp_left");
	
	rename `pairBlend -input2 -nd ($charName + "_world_wristConGrp_left") -at tx -at ty -at tz -at rx -at ry -at rz` ($charName + "_world_wristConGrp_pairBlend_left");
	addAttr -longName nonBodyFollow_rx ($charName + "_world_wristConGrp_left");
	addAttr -longName nonBodyFollow_ry ($charName + "_world_wristConGrp_left");
	addAttr -longName nonBodyFollow_rz ($charName + "_world_wristConGrp_left");
	addAttr -longName nonBodyFollow_tx ($charName + "_world_wristConGrp_left");
	addAttr -longName nonBodyFollow_ty ($charName + "_world_wristConGrp_left");
	addAttr -longName nonBodyFollow_tz ($charName + "_world_wristConGrp_left");
	
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_tx") ($charName + "_world_wristConGrp_pairBlend_left" + ".inTranslateX2");
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_ty") ($charName + "_world_wristConGrp_pairBlend_left" + ".inTranslateY2");
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_tz") ($charName + "_world_wristConGrp_pairBlend_left" + ".inTranslateZ2");
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_rx") ($charName + "_world_wristConGrp_pairBlend_left" + ".inRotateX2");
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_ry") ($charName + "_world_wristConGrp_pairBlend_left" + ".inRotateY2");
	connectAttr ($charName + "_world_wristConGrp_left.nonBodyFollow_rz") ($charName + "_world_wristConGrp_pairBlend_left" + ".inRotateZ2");
	
	parent ($charName + "_world_wristConGrp_left") ($charName + "_MASTER");
	parent ($charName + "_world_wristCon_left")($charName + "_world_wristConGrp_left");
	addAttr -longName followBodySwitch -attributeType "float" -minValue 0 -maxValue 1 -defaultValue 0 -keyable 1 ($charName + "_world_wristCon_left");
	shadingNode -asUtility reverse -n ($charName + "followBodySwitch_reverse_left");
	connectAttr ($charName + "_world_wristCon_left.followBodySwitch") ($charName + "followBodySwitch_reverse_left.inputX");
	connectAttr ($charName + "followBodySwitch_reverse_left.outputX") ($charName + "_world_wristConGrp_pairBlend_left.weight");

}
