global proc AEHsvAdjustTemplate( string $nodeName )
{

	editorTemplate -beginScrollLayout;
		editorTemplate -beginLayout "Input" -collapse 0;
			editorTemplate -addControl "inputRGB";
			editorTemplate -addControl "inputLuminance";
		editorTemplate -endLayout;
	
		editorTemplate -beginLayout "HSV" -collapse 0;
			editorTemplate -addControl "hueShift";
			editorTemplate -addControl "hueMin";
			editorTemplate -addControl "hueMax";
			editorTemplate -addSeparator;
			editorTemplate -addControl "satMult";
			editorTemplate -addControl "satShift";
			editorTemplate -addSeparator;
			editorTemplate -addControl "valMult";
			editorTemplate -addControl "valShift";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Contrast" -collapse 0;
			editorTemplate -addControl "contrastEnable" "AEHsvAdjustContrastEnable";
			editorTemplate -addControl "contrastR";
			editorTemplate -addControl "contrastG";
			editorTemplate -addControl "contrastB";
			editorTemplate -addSeparator;
			editorTemplate -addControl "contrastBiasR";
			editorTemplate -addControl "contrastBiasG";
			editorTemplate -addControl "contrastBiasB";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Gamma" -collapse 0;
			editorTemplate -addControl "gammaEnable" "AEHsvAdjustGammaEnable";
			editorTemplate -addControl "gammaR";
			editorTemplate -addControl "gammaG";
			editorTemplate -addControl "gammaB";
		editorTemplate -endLayout;

	editorTemplate -suppress "contrastRGB";
	editorTemplate -suppress "contrastBiasRGB";
	editorTemplate -suppress "gammaRGB";

	// include/call base class/node attributes
	AEdependNodeTemplate $nodeName;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
}

global proc AEHsvAdjustContrastEnable( string $nodeName )
{
	int $contrastEnable = 1 - `getAttr ($nodeName + ".contrastEnable")`;
	editorTemplate -dimControl $nodeName "contrastRGB" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastR" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastG" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastB" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastBiasRGB" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastBiasR" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastBiasG" $contrastEnable;
	editorTemplate -dimControl $nodeName "contrastBiasB" $contrastEnable;
}

global proc AEHsvAdjustGammaEnable( string $nodeName )
{
	int $gammaEnable = 1 - `getAttr ($nodeName + ".gammaEnable")`;
	editorTemplate -dimControl $nodeName "gammaRGB" $gammaEnable;
	editorTemplate -dimControl $nodeName "gammaR" $gammaEnable;
	editorTemplate -dimControl $nodeName "gammaG" $gammaEnable;
	editorTemplate -dimControl $nodeName "gammaB" $gammaEnable;
}