// Copyright (C) 1997-2004 Alias,
// a division of Silicon Graphics Limited.
// 
// The information in this file is provided for the exclusive use of the
// licensees of Alias.  Such users have the right to use, modify,
// and incorporate this code into other products for purposes authorized
// by the Alias license agreement, without fee.
// 
// ALIAS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL ALIAS BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.

//
//  Alias|Wavefront Script File
//
//  Creation Date:	May 23, 1997
//  Author:		sw
//
//  Procedure Name:
//	AEsurfaceShaderTemplate
//
//  Description Name;
//	Creates the attribute editor controls for the surfaceShader Node
//
//  Input Value:
//	nodeName 
//
//  Output Value:
//	None
// 


global proc AEsurfaceShaderTemplate ( string $nodeName )
{
	AEswatchDisplay $nodeName;
	editorTemplate -beginScrollLayout;
		editorTemplate -callCustom AEshaderTypeNew AEshaderTypeReplace
					"message";

		editorTemplate -beginLayout "Surface Shader Attributes" -collapse 0;
			editorTemplate -addControl "outColor";
			editorTemplate -addControl "outTransparency";
			editorTemplate -addControl "outGlowColor";
			editorTemplate -addControl "outMatteOpacity";
		editorTemplate -endLayout;

		editorTemplate -beginLayout "Hardware Texturing" -collapse true;
			AEhardwareTextureTemplate $nodeName ("outColor outTransparency");
		editorTemplate -endLayout;

		// mental ray photon shader attributes
		AEmentalrayPhotonAttrs $nodeName;

		// include/call base class/node attributes
		AEdependNodeTemplate $nodeName;
		editorTemplate -beginLayout "Moebius Shader Control Attributes" -collapse 0;
			editorTemplate -addControl "bumpDepth";
			editorTemplate -addControl "ClampLowColor";
			editorTemplate -addControl "ClampHighColor";
			editorTemplate -addControl "ExpandLowColor";
			editorTemplate -addControl "ExpandHighColor";
		editorTemplate -endLayout;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
}
