/* This file downloaded from Highend3d.com
''  
''  Highend3d.com File Information:
''  
''    Script Name: aks_lightRay
''    Author:  
''    Last Updated: Mar 08, 2008
''    Update/Change this file at:
''    http://Highend3d.com/maya/downloads/mel_scripts/lighting/4517.html
''  
''  Please do not alter any information above this line
''  it is generated dynamically by Highend3d.com and will
''  be changed automatically on any updates.
*/

//
//                This script is a part of aks_lightRay v.1.0
//

//installs and deletes scriptJobs- and -Nodes, to update the lightColor over time
global proc aks_doScriptJobs(int $index, string $lightGrp)
{
	if ($lightGrp == "")
	    $lightGrp = `optionMenu -q -v optMenu1`;
	
	
	//installs scriptJobs and scriptNodes 
	if ($index == 1){
	
		     //scriptNode command
		     string $scriptNodeCmd = "scriptJob   -killWithScene -event \"timeChanged\"  \"aks_editLightGRP editColor 0 0 ";
	         $scriptNodeCmd += ( $lightGrp + "\";");
			 
	         eval $scriptNodeCmd;
			 
			 if (`objExists ( "scriptNode" + "_" + $lightGrp)` != 1){
				 
				  //scriptJob command
			      string $scriptNodeCmd = "scriptNode -st 1 -bs \"aks_doScriptJobs 1 ";
			      $scriptNodeCmd += ( $lightGrp + "\"" + " -n  \"scriptNode_" + $lightGrp + "\";");
			   
			      eval  $scriptNodeCmd;
			    }
        }
	else{
		     //lists all the scriptJobs
		     string $currentJobs[] = `scriptJob -listJobs`;
			 
			 //loops through them to find the one created by the script
			 //and deletes them
			 for ($job in $currentJobs){
				 
				 if (`match "aks_LightGrp" $job` == "aks_LightGrp"){
					 
					      string $getJobNum[];
	                      $numTokens =`tokenize $job ":" $getJobNum`;
						  
						  int $jobNum = $getJobNum[0];
						  
						  scriptJob -force -kill $jobNum;
					}
				 }
			 //deletes scriptNode
			 delete ("scriptNode_" + $lightGrp);
		
		}
}
