


global proc anemone_C_tools(string $anemone_C[])
{

	if (`size($anemone_C)`!=0)
	{
		string $paintobj[] =  $anemone_C;

		select $paintobj;

		//string $paintobj[] = `ls -sl`;

		doPaintEffectsToPoly( 1,2,0,1,1000000);

		string $polyobj[] = `ls -sl`;

		int $siz = `size ($paintobj)`;

		int $siz2 = `size ($polyobj)`;

		$shaderExi = `objExists DOD_anemone_C_SG1`;

		$shaderExi1 = `objExists DOD_anemone_C_SG2`;

		$shaderExi2 = `objExists DOD_anemone_C_group`;

	        $shaderExi3 = `objExists all_paint_an_control`;

		if ($shaderExi3 == 0)

            {

            select -cl  ;

		sets -name all_paint_an_control;

		}



		if ($shaderExi == 0 || $shaderExi1 == 0 )

		{

		file -import -type "mayaBinary" -rpr "DOD_anemone_A_texture" -options "v=0"  -pr (substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\shaders\\dod_shaders\\DOD_anemone_C_texture.mb");

		}

		if ($shaderExi2 == 0)

		{

		group -em -n DOD_anemone_C_group;

		}

            
		for ($i=0;$i<$siz;$i++)

		{

			select -r $paintobj[$i];

			string $shapename[] = `listRelatives -s $paintobj[$i]`;

			string $fgobj[] = `listConnections -source true -destination true $shapename[0]`;

			setAttr ($fgobj[1]+".visibility") 1;

			select -r $fgobj[1];

			CenterPivot ;

			string $gupname1 = `group -em -n ("anemone_C_control"+"#")`;


			addAttr -ln globalScale  -at double  -min 0 -max 100 -dv 40 $gupname1;
			addAttr -ln sampleDensity -at double  -min 0 -max 6 -dv 1 $gupname1;
			addAttr -ln petalBend -at double  -min -1 -max 1 -dv 0 $gupname1;
			addAttr -ln uniformForceY  -at double  -min -1 -max 1 -dv 0 $gupname1;
			addAttr -ln petalsInFlower -at double  -min 1 -max 14 -dv 8 $gupname1;
			addAttr -ln numFlowers -at double  -min 1 -max 10 -dv 7 $gupname1;
			addAttr -ln tubeSections -at double  -min 1 -max 16 -dv 10 $gupname1;
			addAttr -ln brushWidth -at double  -min 0 -max 100 -dv 0.207 $gupname1;
                  addAttr -ln an_control -at bool  -dv 1 $gupname1;
			addAttr -ln control -at bool  -dv 1 $gupname1;



			setAttr -e -keyable true ($gupname1+".globalScale ");
			setAttr -e -keyable true ($gupname1+".sampleDensity");
			setAttr -e -keyable true ($gupname1+".petalBend");
			setAttr -e -keyable true ($gupname1+".uniformForceY");
			setAttr -e -keyable true ($gupname1+".petalsInFlower ");
			setAttr -e -keyable true ($gupname1+".numFlowers");
			setAttr -e -keyable true ($gupname1+".tubeSections ");
			setAttr -e -keyable true ($gupname1+".brushWidth ");
	            //setAttr -e -keyable true ($gupname1+".an_control");
      		//setAttr -e -keyable true ($gupname1+".control");



			connectAttr -f ($gupname1 + ".globalScale ") ($fgobj[0]+ ".globalScale");
			connectAttr -f ($gupname1 + ".sampleDensity") ($shapename[0]+ ".sampleDensity");
			connectAttr -f ($gupname1 + ".petalBend") ($fgobj[0]+ ".petalBend");
			connectAttr -f ($gupname1 + ".uniformForceY") ($fgobj[0]+ ".uniformForceY");
			connectAttr -f ($gupname1 + ".petalsInFlower ") ($fgobj[0]+ ".petalsInFlower ");
			connectAttr -f ($gupname1 + ".numFlowers") ($fgobj[0]+ ".numFlowers");
			//connectAttr -f ($gupname1 + ".tubeSections") ($fgobj[0]+ ".tubeSections");
			//connectAttr -f ($gupname1 + ".brushWidth ") ($fgobj[0]+ ".brushWidth ");




			setAttr -lock true ($gupname1+".tx");
			setAttr -lock true ($gupname1+".ty");
			setAttr -lock true ($gupname1+".tz");
			setAttr -lock true ($gupname1+".rx");
			setAttr -lock true ($gupname1+".ry");
			setAttr -lock true ($gupname1+".rz");
			setAttr -lock true ($gupname1+".sx");
			setAttr -lock true ($gupname1+".sy");
			setAttr -lock true ($gupname1+".sz");


			setAttr -lock true ($fgobj[2]+".tx");
			setAttr -lock true ($fgobj[2]+".ty");
			setAttr -lock true ($fgobj[2]+".tz");
			setAttr -lock true ($fgobj[2]+".rx");
			setAttr -lock true ($fgobj[2]+".ry");
			setAttr -lock true ($fgobj[2]+".rz");
			setAttr -lock true ($fgobj[2]+".sx");
			setAttr -lock true ($fgobj[2]+".sy");
			setAttr -lock true ($fgobj[2]+".sz");

			setAttr -lock true ($fgobj[3]+".tx");
			setAttr -lock true ($fgobj[3]+".ty");
			setAttr -lock true ($fgobj[3]+".tz");
			setAttr -lock true ($fgobj[3]+".rx");
			setAttr -lock true ($fgobj[3]+".ry");
			setAttr -lock true ($fgobj[3]+".rz");
			setAttr -lock true ($fgobj[3]+".sx");
			setAttr -lock true ($fgobj[3]+".sy");
			setAttr -lock true ($fgobj[3]+".sz");

			setAttr -lock true ($paintobj[$i]+".tx");
			setAttr -lock true ($paintobj[$i]+".ty");
			setAttr -lock true ($paintobj[$i]+".tz");
			setAttr -lock true ($paintobj[$i]+".rx");
			setAttr -lock true ($paintobj[$i]+".ry");
			setAttr -lock true ($paintobj[$i]+".rz");
			setAttr -lock true ($paintobj[$i]+".sx");
			setAttr -lock true ($paintobj[$i]+".sy");
			setAttr -lock true ($paintobj[$i]+".sz");


			select -r $fgobj[2];

			sets -e -forceElement DOD_anemone_C_SG1;

			select -r $fgobj[3];

			sets -e -forceElement DOD_anemone_C_SG2;

                /*  string $expre = $gupname1 +".control = " + $gupname1 + ".an_control;$control = " + $gupname1 +".control;\r\n\r\n";
                        $expre += "$checkcon = `isConnected " + $paintobj[$i] + ".worldMainMesh[0] "+ $fgobj[2] +".inMesh`;\r\n\r\n";
                        $expre += "if ($control == 0 && $checkcon == 1)\r\n";
                        $expre +=  "{\r\n\r\n";
                        $expre +=  "disconnectAttr " + $paintobj[$i] + ".worldMainMesh[0] "+ $fgobj[2] +".inMesh;\r\n\r\n";
                        $expre +=  "disconnectAttr " + $paintobj[$i] + ".worldFlowerMesh[0] "+ $fgobj[3] +".inMesh;\r\n\r\n";
                        $expre +=  "}\r\n\r\n";
                        $expre +=  "if ($control == 1 && $checkcon == 0)\r\n";
                        $expre +=  "{\r\n\r\n";
                        $expre +=  "connectAttr " + $paintobj[$i] + ".worldMainMesh[0] "+ $fgobj[2] +".inMesh;\r\n\r\n";
                        $expre +=  "connectAttr " + $paintobj[$i] + ".worldFlowerMesh[0] "+ $fgobj[3] +".inMesh;\r\n\r\n";
                        $expre +=  "\r\n}";
                                                         
                        expression -s   $expre  -o "" -ae 1 -uc all ;

                 */


			parent $fgobj[1] $fgobj[2] $fgobj[3] $paintobj[$i] $gupname1;

                  sets -edit -forceElement  all_paint_an_control $gupname1;

			parent $gupname1 DOD_anemone_C_group;

				
		}
            
            setAttr -lock true "DOD_anemone_C_group.tx";
            setAttr -lock true "DOD_anemone_C_group.ty";
            setAttr -lock true "DOD_anemone_C_group.tz";
            setAttr -lock true "DOD_anemone_C_group.rx";
            setAttr -lock true "DOD_anemone_C_group.ry";
            setAttr -lock true "DOD_anemone_C_group.rz";
            setAttr -lock true "DOD_anemone_C_group.sx";
            setAttr -lock true "DOD_anemone_C_group.sy";
            setAttr -lock true "DOD_anemone_C_group.sz";
           
		MLdeleteUnused;
	}
}