/// Author: liang
///
/// Creation Date: 2007/01/23
///
/// Description: 
/// Modify: liang
//global proc auto_add_eyesAim_followCon(string $charNameWrite)
global proc auto_add_eyesAim_followCon()
{
	string $charNameWrite = "";
	//取得角色前缀$charName//
		select "*_MASTER*";
		string $buffer[];
		string $tempListAll[] = `ls -sl`;
		string $tempList = $tempListAll[0];
		tokenize $tempList "_MASTER" $buffer;
		string $charName = $buffer[0];
	//===================//
	string $temp = ($charName+"_eyeAimGrp");
	if(`objExists $temp`)
	{
		print "此角色已添加eyesAim Follow head功能";
		select -cl;
	}
	else
	{
		auto_add_eyesAim_followCon_course($charNameWrite);
	}
}


global proc auto_add_eyesAim_followCon_course(string $charNameWrite)
{
	string $charName;
	float $tempFloatArra[3];
	float $tempFloatArraJoint[3];	
	
	//取得角色前缀$charName//
		select "*_MASTER*";
		string $buffer[];
		string $tempListAll[] = `ls -sl`;
		string $tempList = $tempListAll[0];
		tokenize $tempList "_MASTER" $buffer;
		string $charName = $buffer[0];
	//===================//
	
	//生成附加控制组，并调整轴心//
	select ($charName+"_eyeAim");
	group -n ($charName+"_eyeAimRotate") ($charName+"_eyeAim");
	group -n ($charName+"_eyeAimGrp") ($charName+"_eyeAimRotate");
	$tempFloatArra = `xform -q -worldSpace -rotatePivot ($charName+"_eyeAim")`;
	$tempFloatArraJoint = `joint -query -position ($charName+"_chestA")`;
	xform -worldSpace -pivots $tempFloatArraJoint[0] $tempFloatArraJoint[1] $tempFloatArraJoint[2] ($charName+"_eyeAimRotate");
	xform -worldSpace -pivots $tempFloatArra[0] $tempFloatArra[1] $tempFloatArra[2] ($charName+"_eyeAimGrp");
	//======================//
	
	//约束和连接控制器//
	parentConstraint -mo -weight 1 -n ($charName+"_eyeAimFollow_parentConstraint") ($charName+"_headTip") ($charName+"_eyeAimGrp");
	parentConstraint -mo -weight 1 ($charName+"_upperBodyCon") ($charName+"_eyeAimGrp");
	addAttr -longName followHead -defaultValue 1.0 -minValue 0.0 -maxValue 1.0 -k 1 ($charName+"_eyeAim");
	addAttr -longName eyesAimCircleHeadRotate -defaultValue 0.0 -k 1 ($charName+"_eyeAim");
	
	createNode -n ($charName+"_eyesAimCircleHeadRotateReverse") reverse;
	connectAttr -f ($charName+"_eyeAim.followHead") ($charName+"_eyesAimCircleHeadRotateReverse.inputX");
	connectAttr -f ($charName+"_eyeAim.followHead") ($charName+"_eyeAimFollow_parentConstraint."+$charName+"_headTipW0");
	connectAttr -f ($charName+"_eyesAimCircleHeadRotateReverse.outputX") ($charName+"_eyeAimFollow_parentConstraint."+$charName+"_upperBodyConW1");
	connectAttr -f ($charName+"_eyeAim.eyesAimCircleHeadRotate") ($charName+"_eyeAimRotate.rotateY");
	//=============//
	
	//整理属性的keyable//
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.tx");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.ty");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.tz");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.rx");
	setAttr -lock false -keyable false ($charName+"_eyeAimRotate.ry");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.rz");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.sx");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.sy");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.sz");
	setAttr -lock true -keyable false ($charName+"_eyeAimRotate.v");
	
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.tx");
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.ty");
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.tz");
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.rx");
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.ry");
	setAttr -lock false -keyable false ($charName+"_eyeAimGrp.rz");
	setAttr -lock true -keyable false ($charName+"_eyeAimGrp.sx");
	setAttr -lock true -keyable false ($charName+"_eyeAimGrp.sy");
	setAttr -lock true -keyable false ($charName+"_eyeAimGrp.sz");
	setAttr -lock true -keyable false ($charName+"_eyeAimGrp.v");
	//===============//
	select ($charName+"_eyeAim");
	
	
}
