
global proc cleanprefix()
{
	if (`window -q -exists clnpreWin`)
		return;

	window -title "Remove Prefix" -resizeToFitChildren true clnpreWin;

		formLayout -numberOfDivisions 100 formLayout1;

			textFieldGrp -label "Prefix:" -text "" pref;
			button -label "Remove" -h 27 -command ("docleanpre") remnp;
			button -label "Close"  -h 27 -command "deleteUI -window clnpreWin" cancel;
		
			formLayout -edit
				-attachForm	pref	"top"	5
				-attachForm	pref	"left"	5

				-attachForm	remnp	"left"	5
				-attachControl	remnp	"top"	5	pref
				-attachPosition	remnp     "right"	0       50
				
				-attachControl	  cancel	"left"		5	remnp
				-attachControl	  cancel	"top"	5	pref
				-attachPosition	  cancel      	"right"		0       100

			formLayout1;

	showWindow clnpreWin;
}


global proc string mySubstitute(string $source, string $old, string $new)
{

	string $buf[];
	
	if (`tokenize $source "|" $buf`)
	{
		return ` substitute $old $buf[size($buf)-1]  ""`;
	}
	return "";

}

global proc docleanpre()
{
	string $namesp = `textFieldGrp -q -text pref`;

	string $obj[] = `ls ($namesp+"_*")`;

	for($i in $obj)
	{
		$new = mySubstitute($i,($namesp+"_"),"");
		if (objExists($i)&&$new!=$i && size($new)>0)
			rename $i $new;
	}
}

