//////////////////////////////////////////////////////////
//
//	Script Name: ddBetchRename
//	Verision: 0.01 beta
//	Author: Julii FreeMAN, SZ-CN
//	Date Created: July 20 2003
//	Changed Projcet Date: April 23 2006
//	Last Updated: June 10 2006
//	Update/Change this file at: Julii FreeMAN
//	Note:Batch Rename Function 
//
//////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////
// Procdures Name: ddBatchRename
// 
// 给指定物体增加 前缀、后缀、以及特定字串替换
// 
// Arguments:
//  $objName 根物体（从这个物体之下的物体的名字都会被操作）
//  $prefix 前缀
//  $suffix 后缀
//  $search 被替换的字串
//  $replace 
//////////////////////////////////////////////////////////
global proc ddBatchRename(string $objName,string $prefix,string $suffix,string $search,string $replace)
{
 int $i = 0,$arraySize ;
 string $tmp,$selList[],$selected[],$renamelist,$nametemp,$num,$regularExpr = ".*|";
 
 select -hi $objName ;
 $selList = `ls -sl` ;
 //print $selList ;
 $arraySize = size($selList) ;
 if(`ddGetMayaVersion` < 5)
 {
  $selected[0] = $selList[$arraySize-1] ;
  for($i = 1 ; $i < $arraySize ; $i++)
  {
   $selected[$i] = $selList[$i-1];
  }
 }
 else
 {
  for($i = 0 ; $i < $arraySize ; $i++)
  {
   $selected[$i] = $selList[$i];
  }
 }
 //print $selected;

 //if(size($selList) == 0) error "nothing selected.";
 
 for($i = ($arraySize - 1) ; $i >= 0 ;$i--)
 {
  //print($i);print("\n");
  //print($renamelist+"\n");
  $nametemp = `substitute $regularExpr $selected[$i] ""` ; //去除父物体字符串
  $nametemp = `substitute $search $nametemp $replace` ; //字符串取代
  print($selected[$i]+" -> "+$nametemp+"\n");
  rename $selected[$i] ($prefix + $nametemp + $suffix);
  //print("OK!\n");
 }

}

//End of file.
