//////////////////////////////////////////////////////////
//
//	Script Name: ddOrientBratzJoint
//	Verision: 0.01 beta
//	Author: Julii FreeMAN, SZ-CN
//	Date Created: June 8 2006
//	Changed Projcet Date: 
//	Last Updated: June 8 2006
//	Update/Change this file at: Julii FreeMAN
//	Note: Oreint Joint Axis for Bratz
//
//////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////
// Procdures Name: ddOrientBratzJoint
//
//////////////////////////////////////////////////////////
global proc ddOrientBratzJoint(string $charName)
{
 //将joint全部置为NONE
 select 
 makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 -jointOrient;
 
}

//End of file