//////////////////////////////////////////////////////////
//
//	Script Name: ddRenameTools
//	Verision: 0.91 beta
//	Author: Julii FreeMAN, SZ-CN
//	Date Created: April 9 2003
//	Changed Projcet Date: April 23 2006
//	Last Updated: August 20 2008
//	Update/Change this file at: Julii FreeMAN
//	Note:Batch Rename Function 
//
//////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////
// Produces Name: ddRename
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddRename()
{
 int $i = 0 ;
 string $tmp,$sellist[],$renamelist,$nametemp,$num,$regularExpr = ".*|" ;
 
 string $addfront = `textFieldGrp -q -tx fronttext` ;
 string $addback =  `textFieldGrp -q -tx backtext` ;
 string $search =   `textFieldGrp -q -tx searchtext` ;
 string $replace =  `textFieldGrp -q -tx replacetext` ;

 //clear $sellist ;
 $sellist = `ls -sl` ;
 
 if(size($sellist) == 0) error "nothing selected." ;
 
 for($i=(size($sellist)-1) ;$i>=0 ;$i--)
 {
  /*if(size($namechange) == 0) $nametemp = $renamelist ;
  else
  {
   $num = $i++ ;
   $nametemp = ($namechange+$num) ;
  }
  */
  
  //print($i) ;print("\n") ;
  //print($renamelist+"\n") ;
  $nametemp = `substitute $regularExpr $sellist[$i] ""` ;//去除父物体字符串
  $nametemp = `substitute $search $nametemp $replace` ;//字符串取代
  //print($sellist[$i]+" -> "+$nametemp+"\n") ;
  rename $sellist[$i] ($addfront + $nametemp + $addback) ;
  //print("OK!\n") ;
 }

}

//////////////////////////////////////////////////////////
// Produces Name: ddSerialRename
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddSerialRename()
{
 int $i,$startNumber,$letEn,$capEn ;
 string $temp,$selected[],$serialName,$letter[26] ;

 $letter = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"} ;
 $capitalLetter = {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","W","Y","Z"} ;
//abcdefghijklmnopqrstuvwxyz
 $serialName = `textField -query -tx serialRenameText` ;
 $startNumber = `intField -query -value ddRTstartNumber` ;
 $letEn = `checkBox -query -value ddRTLetter` ;
 $capEn = `checkBox -query -value ddRTCapital` ;
 //print $startNumber ;
 $selected = `ls -sl -l` ;
 
 for($i=(`size($selected)` - 1);$i>=0;$i--)
 {
  print ($selected[$i]+"\n");
  rename $selected[$i] ("SerialName" + $i) ;
  $selected[$i] = ("SerialName" + $i) ;
  //print($selected[$i]);
  //print("\n");
 }

 if( $letEn )
 {
  if($capEn)
  {
   for($i=(`size($selected)`-1);$i>=0;$i--)
   {
    rename $selected[$i] ($serialName + $capitalLetter[$i]) ;
   }
  }
  else
  {
   for($i=(`size($selected)`-1);$i>=0;$i--)
   {
    rename $selected[$i] ($serialName + $letter[$i]) ;
   }
  }
 }
 else
 {
  for($i=(`size($selected)`-1);$i>=0;$i--)
  {
   rename $selected[$i] ($serialName + ($i+$startNumber)) ;
  }
 }
}

//////////////////////////////////////////////////////////
// Produces Name: ddRTCustomRename
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddRTCorrectShapeName()
{
	int $i = 1 ;
	string $selected[],$shapes[],$sel,$tmp ;

	$selected = `ls -sl` ;

	for ($sel in $selected)
	{
		$shapes = `listRelatives  -fullPath -shapes $sel` ;

		if (size($shapes) == 1)
		{
			rename $shapes[0] ($sel+"Shape") ;
		}
		else if (size($shapes)>1)
		{
			for ($tmp in $shapes )
			{
				rename $tmp ($sel+($i++)+"Shape") ;
			}
		}
	}

}

//////////////////////////////////////////////////////////
// Produces Name: ddRTCustomRename
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddRTCustomRename()
{
	int $i=1 ;
	string $segment1,$segment2,$segment3,
		$divided1,$divided2,$divided3,
		$tmp,$newname ;
	string $selected[],$reList[],$child[] ;

	$selected = `ls -sl` ;

	$segment1 = `textField -query -text ddRTSegmentTextField1` ;
	if (size($segment1))
	{
		if (`checkBox -query -value ddRTSegmentCheckBox1`)
		{
			$divided1 = "_" ;
		}
	}
	$segment2 = `textField -query -text ddRTSegmentTextField2` ;
	if (size($segment2))
	{
		if (`checkBox -query -value ddRTSegmentCheckBox2`)
		{
			$divided2 = "_" ;
		}
	}
	$segment3 = `textField -query -text ddRTSegmentTextField3` ;
	if (size($segment3))
	{
		if (`checkBox -query -value ddRTSegmentCheckBox3`)
		{
			$divided3 = "_" ;
		}
	}
	//应A1需求，增加层级下所有物体统一改名的选项
    python("from idmt.maya.py_common import GDC_Tools;reload(GDC_Tools)");
    string $cmd = ("GDC_Tools.GDC_Tools().modelGrpRename([],'"+$segment1+"','"+$segment2+"','"+$segment3+"','"+$divided1+"','"+$divided2+"','"+$divided3+"')");
    print "\n";
    print $cmd;
    print "\n";
    python($cmd);
    /*
    	$newname = `rename $selected[0] ($segment1+$divided1+$segment2+$divided2+$segment3+$divided3)` ;

	if (`checkBox -query -value ddRTSegmentSubRename`)
	{
		$chird = `listRelatives -f -children $newname` ;


		for ( $tmp in $chird )
		{
			print ($tmp+"\n");
			//$tmp = `substitute ".*|" $tmp ""` ;
			if (size($segment3))
			{
				
				rename $tmp ($segment1+$divided1+$segment2+$divided2+$segment3+$i+++$divided3) ;
			}
			
			else if (size($segment2))
			{
				rename $tmp ($segment1+$divided1+$segment2+$i+++$divided2) ;
			}
			
		}
	}
    */
}


//////////////////////////////////////////////////////////
// Produces Name: ddCleartext
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddCleartext()
{
	textFieldGrp -edit -text "" fronttext ;
	textFieldGrp -edit -text "" backtext ;
	textFieldGrp -edit -text "" searchtext ;
	textFieldGrp -edit -text "" replacetext ;
}


//////////////////////////////////////////////////////////
// Produces Name: ddRTPropWordRename
// Arguments: null
//////////////////////////////////////////////////////////
global proc ddRTPropWordRename()
{
	string $selected[],$reList[] ;
	$selected = `ls -sl` ;
	$reList  = `textScrollList -query -selectItem ddRTPrepWorldList` ;

	rename $selected[0] $reList[0] ;
}

//////////////////////////////////////////////////////////
// Produces Name: ddRTPropWordRename
// Arguments: null
//	源自赵志杰的脚本
//////////////////////////////////////////////////////////
global proc int ddRTRemoveNamespace()
{
	int $count = 0;

	print "Remove namespace\n";
	print "----------------\n";

	for ($count =0; $count<3; $count++)
	{
		string $buf[] = `ls -long`;
		for ($i=size($buf)-1; $i>=0; $i--)
		{
			if (`objExists $buf[$i]`)
			{
				if (!`reference -isNodeReferenced $buf[$i]`)
				{
					string $buf1[];
					tokenize $buf[$i] "|" $buf1;
					string $name = $buf1[size($buf1)-1];
					string $sp = `match "([0-9a-zA-Z_]*:)+" $name`;
					if ($sp != "")
					{
						$name = `substitute $sp $name ""`;
						if (!catch(`rename $buf[$i] $name`))
						{
							$count ++;
						}
					}
				}
			}
		}
	}
	print "\n";

	return $count;
}
global proc WinXLowRename(string $oname)
{
	print $oname ;
	print "\n" ;
	string $selected[];
	$selected = `ls -sl` ;
	if (size($selected))
	{
		rename $selected[0] ("LOW_"+$oname) ;
	}
	
}

global proc ddWinXLowRenameWindow()
{
	string $window = "ddRenameWinXLowmodel";
	if (`window -ex $window`)
		deleteUI $window;
	window $window;
	formLayout -nd 1000 ($window + "FormLayout");
		button -l head		-ann "" -c "WinXLowRename(`button -q -l RRControl1`)"	RRControl1 ;
		button -l chest		-ann "" -c "WinXLowRename(`button -q -l RRControl2`)"	RRControl2 ;
		button -l waist		-ann "" -c "WinXLowRename(`button -q -l RRControl3`)"	RRControl3 ;
		button -l pelvis	-ann "" -c "WinXLowRename(`button -q -l RRControl4`)"	RRControl4 ;
		button -l hair		-ann "" -c "WinXLowRename(`button -q -l RRControl5`)"	RRControl5 ;
		button -l thigh_L	-ann "" -c "WinXLowRename(`button -q -l RRControl6`)"	RRControl6 ;
		button -l calf_L	-ann "" -c "WinXLowRename(`button -q -l RRControl7`)"	RRControl7 ;
		button -l ball_L	-ann "" -c "WinXLowRename(`button -q -l RRControl8`)"	RRControl8 ;
		button -l toe_L		-ann "" -c "WinXLowRename(`button -q -l RRControl9`)"	RRControl9 ;
		button -l thigh_R	-ann "" -c "WinXLowRename(`button -q -l RRControl10`)"	RRControl10 ;
		button -l calf_R	-ann "" -c "WinXLowRename(`button -q -l RRControl11`)"	RRControl11 ;
		button -l ball_R	-ann "" -c "WinXLowRename(`button -q -l RRControl12`)"	RRControl12 ;
		button -l toe_R		-ann "" -c "WinXLowRename(`button -q -l RRControl13`)"	RRControl13 ;
		button -l arm_L		-ann "" -c "WinXLowRename(`button -q -l RRControl14`)"	RRControl14 ;
		button -l forearm_L	-ann "" -c "WinXLowRename(`button -q -l RRControl15`)"	RRControl15 ;
		button -l shoulder_L-ann "" -c "WinXLowRename(`button -q -l RRControl16`)"	RRControl16 ;
		button -l hand_L	-ann "" -c "WinXLowRename(`button -q -l RRControl17`)"	RRControl17 ;
		button -l index_a_L -ann "" -c "WinXLowRename(`button -q -l RRControl18`)"	RRControl18 ;
		button -l index_b_L -ann "" -c "WinXLowRename(`button -q -l RRControl19`)"	RRControl19 ;
		button -l index_c_L -ann "" -c "WinXLowRename(`button -q -l RRControl20`)"	RRControl20 ;
		button -l mid_b_L	-ann "" -c "WinXLowRename(`button -q -l RRControl21`)"	RRControl21 ;
		button -l mid_c_L	-ann "" -c "WinXLowRename(`button -q -l RRControl22`)"	RRControl22 ;
		button -l mid_a_L	-ann "" -c "WinXLowRename(`button -q -l RRControl23`)"	RRControl23 ;
		button -l ring_b_L	-ann "" -c "WinXLowRename(`button -q -l RRControl24`)"	RRControl24 ;
		button -l ring_c_L	-ann "" -c "WinXLowRename(`button -q -l RRControl25`)"	RRControl25 ;
		button -l ring_a_L	-ann "" -c "WinXLowRename(`button -q -l RRControl26`)"	RRControl26 ;
		button -l pinky_b_L	-ann "" -c "WinXLowRename(`button -q -l RRControl27`)"	RRControl27 ;
		button -l pinky_c_L	-ann "" -c "WinXLowRename(`button -q -l RRControl28`)"	RRControl28 ;
		button -l pinky_a_L	-ann "" -c "WinXLowRename(`button -q -l RRControl29`)"	RRControl29 ;
		button -l thumb_a_L -ann "" -c "WinXLowRename(`button -q -l RRControl30`)"	RRControl30 ;
		button -l thumb_b_L -ann "" -c "WinXLowRename(`button -q -l RRControl31`)"	RRControl31 ;
		button -l thumb_c_L -ann "" -c "WinXLowRename(`button -q -l RRControl32`)"	RRControl32 ;
		button -l arm_R		-ann "" -c "WinXLowRename(`button -q -l RRControl33`)"	RRControl33 ;
		button -l forearm_R -ann "" -c "WinXLowRename(`button -q -l RRControl34`)"	RRControl34 ;
		button -l shoulder_R -ann "" -c "WinXLowRename(`button -q -l RRControl35`)"	RRControl35 ;
		button -l hand_R	-ann "" -c "WinXLowRename(`button -q -l RRControl36`)"	RRControl36 ;
		button -l index_a_R -ann "" -c "WinXLowRename(`button -q -l RRControl37`)"	RRControl37 ;
		button -l index_b_R -ann "" -c "WinXLowRename(`button -q -l RRControl38`)"	RRControl38 ;
		button -l index_c_R -ann "" -c "WinXLowRename(`button -q -l RRControl39`)"	RRControl39 ;
		button -l mid_b_R	-ann "" -c "WinXLowRename(`button -q -l RRControl40`)"	RRControl40 ;
		button -l mid_c_R	-ann "" -c "WinXLowRename(`button -q -l RRControl41`)"	RRControl41 ;
		button -l mid_a_R	-ann "" -c "WinXLowRename(`button -q -l RRControl42`)"	RRControl42 ;
		button -l ring_b_R	-ann "" -c "WinXLowRename(`button -q -l RRControl43`)"	RRControl43 ;
		button -l ring_c_R	-ann "" -c "WinXLowRename(`button -q -l RRControl44`)"	RRControl44 ;
		button -l ring_a_R	-ann "" -c "WinXLowRename(`button -q -l RRControl45`)"	RRControl45 ;
		button -l pinky_b_R	-ann "" -c "WinXLowRename(`button -q -l RRControl46`)"	RRControl46 ;
		button -l pinky_c_R	-ann "" -c "WinXLowRename(`button -q -l RRControl47`)"	RRControl47 ;
		button -l pinky_a_R	-ann "" -c "WinXLowRename(`button -q -l RRControl48`)"	RRControl48 ;
		button -l thumb_a_R	-ann "" -c "WinXLowRename(`button -q -l RRControl49`)"	RRControl49 ;
		button -l thumb_b_R	-ann "" -c "WinXLowRename(`button -q -l RRControl50`)"	RRControl50 ;
		button -l thumb_c_R	-ann "" -c "WinXLowRename(`button -q -l RRControl51`)"	RRControl51 ;
		button -l neck		-ann "" -c "WinXLowRename(`button -q -l RRControl52`)"	RRControl52 ;
	formLayout -e 
		-attachPosition RRControl1 "left" 0 435
		-attachPosition RRControl1 "right" 0 564
		-attachPosition RRControl1 "top" 0 74
		-attachPosition RRControl1 "bottom" 0 152
		-attachPosition RRControl2 "left" 0 444
		-attachPosition RRControl2 "right" 0 556
		-attachPosition RRControl2 "top" 0 239
		-attachPosition RRControl2 "bottom" 0 287
		-attachPosition RRControl3 "left" 0 460
		-attachPosition RRControl3 "right" 0 539
		-attachPosition RRControl3 "top" 0 302
		-attachPosition RRControl3 "bottom" 0 350
		-attachPosition RRControl4 "left" 0 427
		-attachPosition RRControl4 "right" 0 572
		-attachPosition RRControl4 "top" 0 363
		-attachPosition RRControl4 "bottom" 0 411
		-attachPosition RRControl5 "left" 0 435
		-attachPosition RRControl5 "right" 0 564
		-attachPosition RRControl5 "top" 0 40
		-attachPosition RRControl5 "bottom" 0 66
		-attachPosition RRControl6 "left" 0 535
		-attachPosition RRControl6 "right" 0 596
		-attachPosition RRControl6 "top" 0 448
		-attachPosition RRControl6 "bottom" 0 644
		-attachPosition RRControl7 "left" 0 535
		-attachPosition RRControl7 "right" 0 596
		-attachPosition RRControl7 "top" 0 655
		-attachPosition RRControl7 "bottom" 0 852
		-attachPosition RRControl8 "left" 0 535
		-attachPosition RRControl8 "right" 0 596
		-attachPosition RRControl8 "top" 0 885
		-attachPosition RRControl8 "bottom" 0 933
		-attachPosition RRControl9 "left" 0 634
		-attachPosition RRControl9 "right" 0 696
		-attachPosition RRControl9 "top" 0 885
		-attachPosition RRControl9 "bottom" 0 933
		-attachPosition RRControl10 "left" 0 403
		-attachPosition RRControl10 "right" 0 465
		-attachPosition RRControl10 "top" 0 448
		-attachPosition RRControl10 "bottom" 0 644
		-attachPosition RRControl11 "left" 0 403
		-attachPosition RRControl11 "right" 0 465
		-attachPosition RRControl11 "top" 0 655
		-attachPosition RRControl11 "bottom" 0 852
		-attachPosition RRControl12 "left" 0 403
		-attachPosition RRControl12 "right" 0 465
		-attachPosition RRControl12 "top" 0 885
		-attachPosition RRControl12 "bottom" 0 933
		-attachPosition RRControl13 "left" 0 304
		-attachPosition RRControl13 "right" 0 366
		-attachPosition RRControl13 "top" 0 885
		-attachPosition RRControl13 "bottom" 0 933
		-attachPosition RRControl14 "left" 0 637
		-attachPosition RRControl14 "right" 0 779
		-attachPosition RRControl14 "top" 0 204
		-attachPosition RRControl14 "bottom" 0 243
		-attachPosition RRControl15 "left" 0 812
		-attachPosition RRControl15 "right" 0 954
		-attachPosition RRControl15 "top" 0 202
		-attachPosition RRControl15 "bottom" 0 241
		-attachPosition RRControl16 "left" 0 507
		-attachPosition RRControl16 "right" 0 614
		-attachPosition RRControl16 "top" 0 198
		-attachPosition RRControl16 "bottom" 0 230
		-attachPosition RRControl17 "left" 0 617
		-attachPosition RRControl17 "right" 0 736
		-attachPosition RRControl17 "top" 0 285
		-attachPosition RRControl17 "bottom" 0 386
		-attachPosition RRControl18 "left" 0 749
		-attachPosition RRControl18 "right" 0 820
		-attachPosition RRControl18 "top" 0 368
		-attachPosition RRControl18 "bottom" 0 388
		-attachPosition RRControl19 "left" 0 827
		-attachPosition RRControl19 "right" 0 898
		-attachPosition RRControl19 "top" 0 368
		-attachPosition RRControl19 "bottom" 0 388
		-attachPosition RRControl20 "left" 0 904
		-attachPosition RRControl20 "right" 0 975
		-attachPosition RRControl20 "top" 0 368
		-attachPosition RRControl20 "bottom" 0 388
		-attachPosition RRControl21 "left" 0 827
		-attachPosition RRControl21 "right" 0 898
		-attachPosition RRControl21 "top" 0 340
		-attachPosition RRControl21 "bottom" 0 360
		-attachPosition RRControl22 "left" 0 904
		-attachPosition RRControl22 "right" 0 975
		-attachPosition RRControl22 "top" 0 340
		-attachPosition RRControl22 "bottom" 0 360
		-attachPosition RRControl23 "left" 0 749
		-attachPosition RRControl23 "right" 0 820
		-attachPosition RRControl23 "top" 0 340
		-attachPosition RRControl23 "bottom" 0 360
		-attachPosition RRControl24 "left" 0 827
		-attachPosition RRControl24 "right" 0 898
		-attachPosition RRControl24 "top" 0 310
		-attachPosition RRControl24 "bottom" 0 330
		-attachPosition RRControl25 "left" 0 904
		-attachPosition RRControl25 "right" 0 975
		-attachPosition RRControl25 "top" 0 310
		-attachPosition RRControl25 "bottom" 0 330
		-attachPosition RRControl26 "left" 0 749
		-attachPosition RRControl26 "right" 0 820
		-attachPosition RRControl26 "top" 0 310
		-attachPosition RRControl26 "bottom" 0 330
		-attachPosition RRControl27 "left" 0 827
		-attachPosition RRControl27 "right" 0 898
		-attachPosition RRControl27 "top" 0 280
		-attachPosition RRControl27 "bottom" 0 300
		-attachPosition RRControl28 "left" 0 904
		-attachPosition RRControl28 "right" 0 975
		-attachPosition RRControl28 "top" 0 280
		-attachPosition RRControl28 "bottom" 0 300
		-attachPosition RRControl29 "left" 0 749
		-attachPosition RRControl29 "right" 0 820
		-attachPosition RRControl29 "top" 0 280
		-attachPosition RRControl29 "bottom" 0 300
		-attachPosition RRControl30 "left" 0 666
		-attachPosition RRControl30 "right" 0 754
		-attachPosition RRControl30 "top" 0 413
		-attachPosition RRControl30 "bottom" 0 442
		-attachPosition RRControl31 "left" 0 778
		-attachPosition RRControl31 "right" 0 867
		-attachPosition RRControl31 "top" 0 413
		-attachPosition RRControl31 "bottom" 0 442
		-attachPosition RRControl32 "left" 0 887
		-attachPosition RRControl32 "right" 0 975
		-attachPosition RRControl32 "top" 0 413
		-attachPosition RRControl32 "bottom" 0 442
		-attachPosition RRControl33 "left" 0 220
		-attachPosition RRControl33 "right" 0 362
		-attachPosition RRControl33 "top" 0 204
		-attachPosition RRControl33 "bottom" 0 243
		-attachPosition RRControl34 "left" 0 45
		-attachPosition RRControl34 "right" 0 187
		-attachPosition RRControl34 "top" 0 202
		-attachPosition RRControl34 "bottom" 0 241
		-attachPosition RRControl35 "left" 0 385
		-attachPosition RRControl35 "right" 0 492
		-attachPosition RRControl35 "top" 0 198
		-attachPosition RRControl35 "bottom" 0 230
		-attachPosition RRControl36 "left" 0 263
		-attachPosition RRControl36 "right" 0 383
		-attachPosition RRControl36 "top" 0 285
		-attachPosition RRControl36 "bottom" 0 386
		-attachPosition RRControl37 "left" 0 180
		-attachPosition RRControl37 "right" 0 251
		-attachPosition RRControl37 "top" 0 368
		-attachPosition RRControl37 "bottom" 0 388
		-attachPosition RRControl38 "left" 0 102
		-attachPosition RRControl38 "right" 0 173
		-attachPosition RRControl38 "top" 0 368
		-attachPosition RRControl38 "bottom" 0 388
		-attachPosition RRControl39 "left" 0 25
		-attachPosition RRControl39 "right" 0 96
		-attachPosition RRControl39 "top" 0 368
		-attachPosition RRControl39 "bottom" 0 388
		-attachPosition RRControl40 "left" 0 102
		-attachPosition RRControl40 "right" 0 173
		-attachPosition RRControl40 "top" 0 340
		-attachPosition RRControl40 "bottom" 0 360
		-attachPosition RRControl41 "left" 0 25
		-attachPosition RRControl41 "right" 0 96
		-attachPosition RRControl41 "top" 0 340
		-attachPosition RRControl41 "bottom" 0 360
		-attachPosition RRControl42 "left" 0 180
		-attachPosition RRControl42 "right" 0 251
		-attachPosition RRControl42 "top" 0 340
		-attachPosition RRControl42 "bottom" 0 360
		-attachPosition RRControl43 "left" 0 102
		-attachPosition RRControl43 "right" 0 173
		-attachPosition RRControl43 "top" 0 310
		-attachPosition RRControl43 "bottom" 0 330
		-attachPosition RRControl44 "left" 0 25
		-attachPosition RRControl44 "right" 0 96
		-attachPosition RRControl44 "top" 0 310
		-attachPosition RRControl44 "bottom" 0 330
		-attachPosition RRControl45 "left" 0 180
		-attachPosition RRControl45 "right" 0 251
		-attachPosition RRControl45 "top" 0 310
		-attachPosition RRControl45 "bottom" 0 330
		-attachPosition RRControl46 "left" 0 102
		-attachPosition RRControl46 "right" 0 173
		-attachPosition RRControl46 "top" 0 280
		-attachPosition RRControl46 "bottom" 0 300
		-attachPosition RRControl47 "left" 0 25
		-attachPosition RRControl47 "right" 0 96
		-attachPosition RRControl47 "top" 0 280
		-attachPosition RRControl47 "bottom" 0 300
		-attachPosition RRControl48 "left" 0 180
		-attachPosition RRControl48 "right" 0 251
		-attachPosition RRControl48 "top" 0 280
		-attachPosition RRControl48 "bottom" 0 300
		-attachPosition RRControl49 "left" 0 245
		-attachPosition RRControl49 "right" 0 334
		-attachPosition RRControl49 "top" 0 413
		-attachPosition RRControl49 "bottom" 0 442
		-attachPosition RRControl50 "left" 0 133
		-attachPosition RRControl50 "right" 0 221
		-attachPosition RRControl50 "top" 0 413
		-attachPosition RRControl50 "bottom" 0 442
		-attachPosition RRControl51 "left" 0 24
		-attachPosition RRControl51 "right" 0 113
		-attachPosition RRControl51 "top" 0 413
		-attachPosition RRControl51 "bottom" 0 442
		-attachPosition RRControl52 "left" 0 435
		-attachPosition RRControl52 "right" 0 564
		-attachPosition RRControl52 "top" 0 154
		-attachPosition RRControl52 "bottom" 0 182
	($window + "FormLayout");
	window -e -w 815 -h 925 $window;
	showWindow $window;
}

//////////////////////////////////////////////////////////
//	Produces Name: 返回
//		交互界面
//	Arguments: null
//////////////////////////////////////////////////////////
global proc ddRTAddNameSpace(string $ns)
{
	
}

global proc ddRTAddNameSpace()
{
	$ns = `textField -query -text queryddRTNameSpaceField` ;
}
//////////////////////////////////////////////////////////
//	Produces Name: ddRTReNaGet
//		处理WinX的命名
//	Arguments: null
//////////////////////////////////////////////////////////
global proc ddRTReNaGet()
{
	int $numTokens ;
	string $selField,$buffer[];
	$selField = `optionMenu -query -value ddRTSegmentOption1` ;

	$numTokens = `tokenize $selField " - " $buffer`;

	textField -edit -text$buffer[0] ddRTSegmentTextField1 ;
}
//////////////////////////////////////////////////////////
//	Produces Name: ddRenameToolsUI
//		交互界面
//	Arguments: null
//////////////////////////////////////////////////////////
global proc ddRenameToolsUI()
{
	if(`window -ex ddRenameToolsWin`)
	{
		deleteUI ddRenameToolsWin ;
		if(`windowPref -exists ddRenameToolsWin`)
		{
			windowPref -remove ddRenameToolsWin ;
		}
	}

	window -widthHeight 472 470
		-title "durdur's Rename Tools v0.97 beta"
		ddRenameToolsWin ;

	menuBarLayout ;
		menu -label "Edit" editmenu ;
			menuItem -label "Reset Settings" -command "ddCleartext()";
		menu -label "Help" helpmenu ;
			menuItem -label "Help on Rename Tools..." ;
	setParent .. ;

	columnLayout -columnAlign "center" ;
		frameLayout -label "General" -borderStyle "etchedIn" -collapsable 1 ;
			columnLayout -columnAlign "center" ;
				textFieldGrp -label "Prefix" fronttext ;
				textFieldGrp -label "Suffix" backtext ;
				textFieldGrp -label "Search for" searchtext ;
				textFieldGrp -label "Replace with" replacetext ;

				rowLayout -numberOfColumns 3 
					-columnWidth 1 153
					-columnWidth 2 153
					-columnWidth 3 153
					-columnAlign3 "center" "center" "center"
					;

					button -label "Clear"
						-width 146
						-height 26
						-command "ddCleartext()" ;

					button -label "Apply"
						-width 146
						-height 26
						-command "ddRename()" ;

					button -label "Close"
						-width 146
						-height 26
						-command "deleteUI ddRenameToolsWin" ;
				setParent .. ;

				separator -w 460 ;

				rowLayout -numberOfColumns 6 
					-columnWidth 1 66
					-columnWidth 2 145
					-columnWidth 3 26
					-columnWidth 4 102
				-columnWidth 5 56
				-columnWidth 6 20
				-columnAlign6 "right" "center" "center" "center" "center" "center";
					text -align "right" -label " Serial Name" ;
					textField -w 145 serialRenameText;
					intField -w 26 -value 1 ddRTstartNumber ;
					button -label "Serial Rename" 
						-command "ddSerialRename()"
						-width 100
						-height 22 ;
					checkBox -label "Letter"
						-onCommand "intField -edit -enable false ddRTstartNumber ;checkBox -edit -visible true ddRTCapital;"
						-offCommand "intField -edit -enable true ddRTstartNumber ;checkBox -edit -visible false ddRTCapital;"
						ddRTLetter ;
					checkBox -label "Capital"
						ddRTCapital ;
				setParent .. ;
	
				columnLayout -columnAlign "center" ;
					checkBox -edit -visible false -value true ddRTCapital ;
				setParent .. ;
				separator -w 460 ;
			setParent .. ;
		setParent .. ;
		frameLayout -label "Name Space" -borderStyle "etchedIn" -collapsable 1 -width 464 ;
			columnLayout -columnAlign "center" ;
				rowLayout -numberOfColumns 3
					-columnWidth 1 153
					-columnWidth 2 153
					-columnWidth 3 153
					-columnAlign3 "center" "center" "center"
					;

					textField -width 146 -height 26 ddRTNameSpaceField ;
					button -width 146 -height 26
						-label "Add Name Space(un)"
						-command "ddRTAddNameSpaceCMD()" ;
					button -label "Remove Namespace"
					-width 146
					-height 26
					-command "ddRTRemoveNamespace()" ;
				setParent.. ;
			setParent.. ;
		setParent.. ;

		frameLayout -label "WinX" -borderStyle "etchedIn" -collapsable 1 ;
			columnLayout -columnAlign "center" ;
				textScrollList -width 400
					-numberOfRows 6
					-allowMultiSelection false
					-append MSH_body_
					-append MSH_eye_L_
					-append MSH_eye_R_
					-append MSH_eyeBrows_L_
					-append MSH_eyeBrows_R_
					-append MSH_hair_
					-append MSH_head_
					-append MSH_teeth_UP_
					-append MSH_teeth_DWN_
					-append MSH_tongue_
					-append MSH_eyelashUp_L_
					-append MSH_eyelashDwn_L_
					-append MSH_eyelashUp_R_
					-append MSH_eyelashDwn_R_
					-showIndexedItem 6 
					-doubleClickCommand "ddRTPropWordRename()"
					ddRTPrepWorldList ;

				formLayout ddRTSegmentForm ;

					text -label "_" -width 20 ddRTSegmentSeparator1 ;
					text -label "_" -width 20 ddRTSegmentSeparator2 ;
					text -label "_" -width 20 ddRTSegmentSeparator3 ;

					text -label "Initial Name" -width 160 ddRTSegmentText1 ;
					text -label "Part" -width 60 ddRTSegmentText2 ;
					text -label "Side" -width 60 ddRTSegmentText3 ;
					//text -label "Precision" -width 60 ddRTSegmentText4 ;

					optionMenu -width 160
						-changeCommand "ddRTReNaGet()"
						ddRTSegmentOption1 ;
						menuItem -label "*Modeling Nodes" ;
						menuItem -label "MSH - poly surface " ;
						menuItem -label "GRP – group" ;
						menuItem -label "LTC – lattice" ;
						menuItem -label "LTB - lattice base" ;
						menuItem -label "FFD - ffd lattice node" ;
						menuItem -label "MESH" ;
						menuItem -label "*Setup Nodes" ;
						menuItem -label "JNT - joint" ;
						menuItem -label "JNB - joint (body)" ;
						menuItem -label "CTRL - animation control" ;
						menuItem -label "PIV - animation pivot" ;
						menuItem -label "CRV - curve" ;
						menuItem -label "LOC - locator (anim)" ;
						menuItem -label "LOB - locator (body)" ;
						menuItem -label "LOF - locator (face)" ;
						menuItem -label "CLS - cluster" ;
						menuItem -label "CLH - cluster handle" ;
						menuItem -label "SKC - skin cluster" ;
						menuItem -label "GRP - group" ;
						menuItem -label "GEO - geometry" ;
						menuItem -label "SEL - selection set" ;
						menuItem -label "DSP - display layer" ;
						menuItem -label "STG - standin geometry" ;
						menuItem -label "IKH - ikhandle" ;
						menuItem -label "PAC - parent constraint" ;
						menuItem -label "POC - point constraint" ;
						menuItem -label "ORC - orient constraint" ;
						menuItem -label "SCN - scriptJobNodes" ;
						menuItem -label "EXP - expressions" ;
						menuItem -label "WRP - wrap deformers" ;
						menuItem -label "WIR - wire deformers" ;
						menuItem -label "*HairDress Nodes" ;
						menuItem -label "FLC - follicle" ;
						menuItem -label "HS - hair system" ;
						menuItem -label "OPC - output curve" ;
						menuItem -label "STC - start curve" ;
						menuItem -label "PFX - paintEffect" ;
						menuItem -label "SHN - Shadow Hair Nurbs" ;
						menuItem -label "SLP - scalp geometry" ;
						menuItem -label "BLD - baldness map texture" ;
						menuItem -label "CLH - haircolor texture" ;
						menuItem -label "BSH - paintEffect brush" ;
						menuItem -label "*Maya Nodes" ;
						menuItem -label "PVP - polyVertexPos" ;
						menuItem -label "PMA - plusminusaverage" ;
						menuItem -label "MDI - multiplydivide" ;
						menuItem -label "REV - reverse" ;
						menuItem -label "RMV - remapvalue" ;
						menuItem -label "CLA - clamp" ;
						menuItem -label "CON - condition" ;
						menuItem -label "BLC - blendcolors" ;
						menuItem -label "PCI - pointOnCurveInfo" ;
						menuItem -label "SRP - slerp spine" ;
						menuItem -label "DBT - distance between" ;
						menuItem -label "SRN - set range" ;
						menuItem -label "VPC - vector product" ;
						menuItem -label "*Special Nodes" ;
						menuItem -label "POR - pose reader" ;
					optionMenu -edit -select 2 ddRTSegmentOption1 ;
					optionMenu -width 60
						-changeCommand "textField -edit -text`optionMenu -query -value ddRTSegmentOption2` ddRTSegmentTextField2 ;"
						ddRTSegmentOption2 ;
						menuItem -label "skirt" ;
						menuItem -label "gallus" ;
						menuItem -label "pants" ;
						menuItem -label "shoes" ;
						menuItem -label "flower" ;

					optionMenu -width 60
						-changeCommand "textField -edit -text`optionMenu -query -value ddRTSegmentOption3` ddRTSegmentTextField3 ;"
						ddRTSegmentOption3 ;
						menuItem -label "l" ;
						menuItem -label "r" ;
						menuItem -label "L" ;
						menuItem -label "R" ;
						menuItem -label "left" ;
						menuItem -label "right" ;
						menuItem -label "Left" ;
						menuItem -label "Right" ;
						menuItem -label "m" ;
						menuItem -label "M" ;
						menuItem -label "middle" ;
						menuItem -label "Middle" ;
						menuItem -label "UP" ;
						menuItem -label "DWN" ;

					/*	menuItem -label "hi" ;
						menuItem -label "high" ;
						menuItem -label "High" ;
						menuItem -label "HIG" ;
						menuItem -label "HIGE" ;
						menuItem -label "lo" ;
						menuItem -label "low" ;
						menuItem -label "Low" ;
						menuItem -label "LOW" ;*/

						checkBox -value true -label"" ddRTSegmentCheckBox1 ;
						checkBox -value true -label"" ddRTSegmentCheckBox2 ;
						checkBox -value true -label"" ddRTSegmentCheckBox3 ;
						checkBox -value false -label"rename sub-object(only one level)" ddRTSegmentSubRename ;
						checkBox -value false -label"rename sub-object(all level)" ddRTSegmentSubRenameAllLev ;
                        
						textField -text "MSH" -width 60 ddRTSegmentTextField1 ;
						textField -text "skirt" -width 60 ddRTSegmentTextField2 ;
						textField -editable true -width 60 ddRTSegmentTextField3 ;

				formLayout -edit
					//-attachForm ddRTPrepWorldList "left" 1

					-attachForm ddRTSegmentText1 "left" 1

					-attachControl ddRTSegmentSeparator1 "left" 2 ddRTSegmentText1

					-attachControl ddRTSegmentText2 "left" 12 ddRTSegmentSeparator1

					-attachControl ddRTSegmentSeparator2 "left" 2 ddRTSegmentText2

					-attachControl ddRTSegmentText3 "left" 12 ddRTSegmentSeparator2

					-attachControl ddRTSegmentSeparator3 "left" 2 ddRTSegmentText3

					-attachForm ddRTSegmentOption1 "left" 1
					-attachControl ddRTSegmentOption1 "top" 2 ddRTSegmentText1

					-attachControl ddRTSegmentOption2 "top" 2 ddRTSegmentText2
					-attachControl ddRTSegmentOption2 "left" 8 ddRTSegmentSeparator1

					-attachControl ddRTSegmentOption3 "top" 2 ddRTSegmentText3
					-attachControl ddRTSegmentOption3 "left" 8 ddRTSegmentSeparator2

					-attachForm ddRTSegmentTextField1 "left" 1 
					-attachControl ddRTSegmentTextField1 "top" 2 ddRTSegmentOption1

					-attachControl ddRTSegmentTextField2 "left" 8 ddRTSegmentSeparator1
					-attachControl ddRTSegmentTextField2 "top" 2 ddRTSegmentOption2

					-attachControl ddRTSegmentTextField3 "left" 8 ddRTSegmentSeparator2
					-attachControl ddRTSegmentTextField3 "top" 2 ddRTSegmentOption3

					-attachControl ddRTSegmentCheckBox1 "top" 2 ddRTSegmentSeparator1
					-attachControl ddRTSegmentCheckBox1 "left" 2 ddRTSegmentText1

					-attachControl ddRTSegmentCheckBox2 "top" 2 ddRTSegmentSeparator2
					-attachControl ddRTSegmentCheckBox2 "left" 2 ddRTSegmentText2

					-attachControl ddRTSegmentCheckBox3 "top" 2 ddRTSegmentSeparator3
					-attachControl ddRTSegmentCheckBox3 "left" 2 ddRTSegmentText3

					-attachForm ddRTSegmentSubRename "left" 1
					-attachControl ddRTSegmentSubRename "top" 2 ddRTSegmentTextField1
                    
					-attachForm ddRTSegmentSubRenameAllLev "left" 1
					-attachControl ddRTSegmentSubRenameAllLev "top" 2 ddRTSegmentSubRename
				ddRTSegmentForm ;
			setParent .. ;
			rowLayout -numberOfColumns 3 
				-columnWidth 1 153
				-columnWidth 2 153
				-columnWidth 3 153
				-columnAlign3 "center" "center" "center";
				button -label "Correct Shape Name 囧rz"
					-width 146
					-height 26
					-command "ddRTCorrectShapeName()" ;

				button -label "Apply"
					-width 146
					-height 26
					-command "ddRTCustomRename()" ;

				button -width 146 -height 26 -label "WinX LowModel Rename"
					-command "ddWinXLowRenameWindow()";
			setParent.. ;
			separator -w 460 ;
		setParent.. ;

	showWindow ;

}

//ddRenameToolsUI() ;

//End of file.
