//////////////////////////////////////////////////////////
//
//	Script Name: ddSetAttribTools
//	Verision: 0.02 beta
//	Author: Julii FreeMAN, SZ-CN
//	Date Created: July 01, 2004
//	Changed Projcet Date: April 24 2006
//	Last Updated: April 24 2006
//	Update/Change this file at: Julii FreeMAN
//	Note: Lock & Hide Attribs
//
//////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////
// Procdures Name:ddLockHideAttrib
// Arguments :
//
// $ltx 1 - lock ; 0 - unlock
// $lty 1 - lock ; 0 - unlock
// $ltz 1 - lock ; 0 - unlock
// $lrx 1 - lock ; 0 - unlock
// $lry 1 - lock ; 0 - unlock
// $lrz 1 - lock ; 0 - unlock
// $lsx 1 - lock ; 0 - unlock
// $lsy 1 - lock ; 0 - unlock
// $lsz 1 - lock ; 0 - unlock
// $htx 0 - hide ; 1 - unHide
// $hty 0 - hide ; 1 - unHide
// $htz 0 - hide ; 1 - unHide
// $hrx 0 - hide ; 1 - unHide
// $hry 0 - hide ; 1 - unHide
// $hrz 0 - hide ; 1 - unHide
// $hsx 0 - hide ; 1 - unHide
// $hsy 0 - hide ; 1 - unHide
// $hsz 0 - hide ; 1 - unHide
// $v 0 - hide ; 1 - unHide
// $joint_radius 0 - hide ; 1 - unHide
/////////////////////////////////////////////////////////////
global proc ddLockHideAttrib
(
 string $name,
 int $ltx,int $lty,int $ltz,
 int $lrx,int $lry,int $lrz,
 int $lsx,int $lsy,int $lsz,
 int $htx,int $hty,int $htz,
 int $hrx,int $hry,int $hrz,
 int $hsx,int $hsy,int $hsz,
 int $v,
 int $joint_radius
)
{
 setAttr -lock $ltx ($name + ".tx") ;
 setAttr -lock $lty ($name + ".ty") ;
 setAttr -lock $ltz ($name + ".tz") ;
 setAttr -lock $lrx ($name + ".rx") ;
 setAttr -lock $lry ($name + ".ry") ;
 setAttr -lock $lrz ($name + ".rz") ;
 setAttr -lock $lsx ($name + ".sx") ;
 setAttr -lock $lsy ($name + ".sy") ;
 setAttr -lock $lsz ($name + ".sz") ;
 setAttr -lock false ($name + ".v") ;
 setAttr -e -keyable $htx ($name + ".tx") ;
 setAttr -e -keyable $hty ($name + ".ty") ;
 setAttr -e -keyable $htz ($name + ".tz") ;
 setAttr -e -keyable $hrx ($name + ".rx") ;
 setAttr -e -keyable $hry ($name + ".ry") ;
 setAttr -e -keyable $hrz ($name + ".rz") ;
 setAttr -e -keyable $hsx ($name + ".sx") ;
 setAttr -e -keyable $hsy ($name + ".sy") ;
 setAttr -e -keyable $hsz ($name + ".sz") ;
 setAttr -e -keyable $v ($name + ".v") ;

 if(`attributeExists "radius" $name`)
 {
  setAttr -channelBox $joint_radius ($name + ".radius") ;
 }
}

//End Of File.