global proc Facialcamera()
{
	string $bones[]=`ls -selection`;
	if (size($bones)==1)
	{
		string $buf[];
		tokenize $bones[0] "_" $buf;
		$camname = "cam_"+$buf[0];
		$hd = $buf[0]+"_head";
		string $h[] = `ls -l -type "joint" $hd`;
		$head = $h[0];
		if (`objExists $head`)
		{
			if (`objExists $camname`==0)
			{
				string $cam[]= `camera`;
				rename $cam[0] $camname;
				//viewSet -p $camname; 
				//string $homeName = `cameraView -camera persp`;
				//cameraView -e -camera $camname -sc $homeName;
				
				parent $camname $head;
				setAttr "persp.visibility" 0;	
				setAttr ($camname+".visibility") 0;	

				setAttr ($camname+".tx") 0;
				setAttr ($camname+".ty") -0.1;
				setAttr ($camname+".tz") 2;
				//lock attributes
				setAttr -lock true ($camname+".tx");
				setAttr -lock true ($camname+".ty");
				setAttr -lock true ($camname+".tz");
				setAttr -lock true ($camname+".rx");
				setAttr -lock true ($camname+".ry");
				setAttr -lock true ($camname+".rz");
				setAttr -lock true ($camname+".sx");
				setAttr -lock true ($camname+".sy");
				setAttr -lock true ($camname+".sz");
				setAttr -lock true ($camname+".v");
				setAttr -lock true ($camname+".hfa");
				setAttr -lock true ($camname+".vfa");
				setAttr -lock true ($camname+".fl");
				setAttr -lock true ($camname+".lsr");
				setAttr -lock true ($camname+".fs");
				setAttr -lock true ($camname+".fd");
				setAttr -lock true ($camname+".sa");
				setAttr -lock true ($camname+".coi");
			}
			else warning "A facial camera already existed.";
		}
		else warning "no valid joint";
	}
	else warning "Please select a part of a character.";
}


