/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: hb
///
/// Creation Date: 2006/11/15
///
/// Description: 
///
// 2006.03.20 by hanjiang
//		1.hide all the children of _HairSyetem ,except _head
//		2.changed naming of the children of fx_baked_geo_group 


proc string getShortName(string $longName)
{
	string $buf[];
	tokenize $longName "|:" $buf;
	return $buf[size($buf)-1];
}

proc string[] bakeRing()
{
	string $frameNum ;
		
	string $objects[] = `ls -sl`;

	int $minTime = int(`playbackOptions -query -minTime`);
	int $maxTime = int(`playbackOptions -query -maxTime`);

	int $index = 0;
	int $k = 0;
	string $blendShape[], $base[], $target, $bsName[], $buf[];
	string $bakedObj[] = {""};

	currentTime $minTime;
	refresh;
	for ($obj in $objects)
	{
		//$obj="ring_R";
		//$obj="br_dvdkirsteem006001_r_ms_c000:KirsteemString_L";
		
		
		
		$buf = `duplicate -name ($obj+"ear") $obj`;
		
		string $name = "BAKED_" + getShortName($obj);
		
		print "======================\n";
		print ($buf[0]+"\n"+$name);
		print "\n======================";
		
		$base[$k] = `rename $buf[0] $name`;

		//$bakedObj[$k] = $base;
		

		//$blendShape = $obj + "BS";
		//if (`objExists $blendShape`)
		//	delete $blendShape;
		
		
		$bsName = `blendShape  $base[$k]`;
		$blendShape[$k] = $bsName[0];
		hide $obj;
		$k++;
	}
//now blendshape node created ,name stored in $blendShape[]
	
	
	select -clear;

	for ($i = $minTime; $i <= $maxTime; $i++)
	{
		currentTime $i;
		refresh;
		$k = 0;
		for ($obj in $objects)
		{
			
			
			$buf = `duplicate -name ($obj+"ear") $obj`;
	
			//$base = "BAKED_" + $obj;
			string $name = getShortName($obj) + "_baked_frame_" + $i;
			$target = `rename $buf[0] $name`;
			//$blendShape = $bsName[0];
			blendShape -edit -target $base[$k] $index $target 1.0 $blendShape[$k];

			delete $target;

			if ($i != $minTime)
				setKeyframe -time ($i-1) -value 0 ($blendShape[$k] + "." + $target);
			setKeyframe -time $i -value 1 ($blendShape[$k] + "." + $target);
			if ($i != $maxTime)
				setKeyframe -time ($i+1) -value 0 ($blendShape[$k] + "." + $target);
			$k++;
		}
		$index ++;
		flushUndo;
	}

///////////////////////////////////////////////////	
// what is he doing?	

	/*
	string $targetName;
	
	
	for ($obj in $objects){
		
		$targetName=`match "[^|]*$" $obj`;
		rename $obj ("ORIGINAL_" + $targetName);
	}
	
	print "======================L94\n";
	print ("renamed to ORIGINAL_" + $targetName);
	print "\n======================";

		
	// base is BAKED_ring_R

	string $tmp[];
	$tmp[0] = `substitute "BAKED_" $base[0] ""`;
	$tmp[1] = `substitute "BAKED_" $base[1] ""`;
	

	
	

	// change the dyn earring model name back
	
	$base[0] = `rename $base[0] $tmp[0]`;
	$base[1] = `rename $base[1] $tmp[1]`;
	
	print "======================substitute\n";
	print ("renamed " + $base[1]+" to "+ $tmp[1]);
	print "\n======================";

	
*/	
	
	flushUndo;
	refresh;
	//return $bakedObj;
	return $base;
}

global proc hbBakeEarring()
{
	string $path[] = `ls -long -selection`;
	
	// path[0] is my sel ring
	// |br_m004006jade_r_ms_c000RNgroup|br_m004006jade_r_ms_c000:m004006jade_HAIRSYSTEM|br_m004006jade_r_ms_c000:earRing_dyn|ring_L


	
	if (size($path) != 1)
	{
		error "Please select A RING or A GEOHAIR";
	}
	string $buff[];
	tokenize $path[0] "|" $buff;
/*	
	$buff = br_m002004sasha_r_ms_c000RNgroup
	br_m002004sasha_r_ms_c000:m002004sasha_HAIRSYSTEM
	br_m002004sasha_r_ms_c000:earRing_dyn
	ring_L
	
*/	
	// $dyn="|br_m002004sasha_r_ms_c000RNgroup|br_m002004sasha_r_ms_c000:m002004sasha_HAIRSYSTEM|br_m002004sasha_r_ms_c000:earRing_dyn";
	//now $dyn is |br_m002004sasha_r_ms_c000RNgroup|br_m002004sasha_r_ms_c000:m002004sasha_HAIRSYSTEM|br_m002004sasha_r_ms_c000:earRing_dyn

	// now $dyn is current sel's parent ,say HairSystemGroup
    string $dyn = `substitute  ("|" + $buff[size($buff)-1]) $path[0] ""`;

	tokenize $buff[size($buff)-1] ":" $buff;
	tokenize $buff[size($buff)-1] "_" $buff;
	
	//remove _ : in ring_L
	
	if ($buff[0] != "earring" && $buff[0] != "ring" && $buff[0] != "burdineString" && $buff[0] != "berniceString" && $buff[0] != "KayceemString" && $buff[0] != "KirsteemString" && $buff[0] != "EllaminaString")
	{
		error "Please select A RING or A GEOHAIR";
	}

	string $temp[];
	string $chaName;
	string $longName[];
	
	// the following code seems has no actual use
	// since longName is the same as $path[0]
	
	$longName[0] = `substring $path[0] 1 (size($path[0])-2)` + "_L";
	$longName[1] = `substring $path[0] 1 (size($path[0])-2)` + "_R";
	
	
	tokenize $path[0] "|" $temp;
	$chaName = $temp[0];
	select -cl;
	select $longName;
	
	//here is where problems arise
	
	string $bakedObj[] = `bakeRing`;
	$bakedObj = `ls -l $bakedObj`;
	
	// holyshit
	
	
	string $layerNames[];
	tokenize $dyn "|" $layerNames;
	
	string $layer=`match "^[^:]*" $layerNames[size($layerNames)-1]`;
	
	

			string $chars[];
			tokenize $layer "_" $chars;
			
	for($i=0;$i<=1;$i++)	{	
		// match "[^|]*$" "|fx_baked_geo_group|fx_earing_br|ring_L"
		string $fuck=`match "[^|]*$" $bakedObj[$i]`;
		// now $fuck is ring_L
		
			$fuck=$chars[1]+"_"+$fuck;
			
			$bakedObj[$i]=`rename $bakedObj[$i] $fuck`;
	
			
	}
	
	string $fxGroup;
	if (!`objExists fx_baked_geo_group` )
		$fxGroup = `group  -world -empty -name "fx_baked_geo_group"`;
	else 
		$fxGroup = "fx_baked_geo_group";
	//group -n "BAKED_GEO" -world $bakedObj;

	if ($buff[0] != "ring" && $buff[0] != "earring")
	{
		group -parent $fxGroup -name ("fx_hairbaked_" + `substitute "String" $buff[0] ""`) $bakedObj[0] $bakedObj[1];
		
		
// 2006.03.20 hide all the children of _HairSyetem ,except _head
//delete $temp[0];
		
		
	select $dyn;
	string $char=`match "[^|]*$" $dyn`;
	$char=`match "^[^\:]*" $char`;
	
	
	convertHairSelection "constraints";
	hideKeepSelection `ls -sl -l`;
		
		
	parent ($char+":br_hairCollide_head") $temp[1];
	
	string $hairHides[]=`listRelatives -c -f $dyn`;
	
	for($hairHide in $hairHides){
		
		if(!`endsWith $hairHide "_head"`)
	
		//hideKeepSelection
			
			hide $hairHide;
	
	}
	
	
	//	hideKeepSelection {$dyn};
	//	hideKeepSelection {($char+":hairCollide_GRP")};
		
		
		
		
		
		
		
		
		//hideKeepSelection `ls -sl`;
		
		
		
		
		
		
		select -r $bakedObj;
		print ("Baked GEO Hair");
	}
	else
	{
		string $tmp[];
		tokenize $chaName "_" $tmp;
		group -parent $fxGroup -name ("fx_earing_" + $tmp[0]+"_"+$chars[1] ) $bakedObj[0] $bakedObj[1];
//		delete ("|" + $chaName + "|earRing_dyn");
//	        setAttr ($buff[(size($buff)-2)] + ".visibility") 0;
	        setAttr ($dyn + ".visibility") 0;
			

			
			//now the layer name is    r_ms_:m004006jade_earRing
			string $layerNames[];
			tokenize $dyn "|" $layerNames;
			
			//now $layerNames[THE_LAST_ONE] is br_m002004sasha_r_ms_c000:earRing_dyn
			
    		string $layer=`match "^[^:]*" $layerNames[size($layerNames)-1]`;
			string $chars[];
			tokenize $layer "_" $chars;
			
			string $layerName=$layer+":"+$chars[1];
			
		if (!`objExists ($layerName + "_earRing")`)
		{
			warning ("²ã" + $layerName + "_earRing²»´æÔÚ");
		}
		else
		{
			layerEditorAddObjects ($layerName + "_earRing");
		}
		select -cl;
		print ("Baked " + $layerName + "'s Earring");
	}
}