/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: hb
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc hbHairCacheLink()
{
//get file name
	string $file = `file -q -sceneName`;
	string $fileName = basename($file, "mb") + "mb";
	string $str = `match "^[bB][rR]_[0-9]{3}[a-zA-Z]*_[0-9]{3}[a-zA-Z]*_" $fileName`;
	if ($str == "") error "This is not a valid BRATZ file.";

//get the path relay to the file name
	string $buf[];
	clear($buf);
	tokenize $fileName "_" $buf;
	string $episode = $buf[1];
	string $scene = $buf[2];
	string $sourcePath = "Z:\\Projects\\BRATZ\\Production\\Animation\\episode_" + $episode + "\\scene_" + $scene + "\\cloth\\";

//get and set link info from the cacheLink.rel file
	string $linkFile = $sourcePath + "cacheLink.rel";
	int $fileID = `fopen $linkFile "r"`;
	if (!$fileID)
		error "Fail to open $linkFile";
	string $buffer = `fgetline $fileID`;
	$buffer = substituteAllString($buffer, "\n", "");
	while (size($buffer) > 0) 
	{
		string $temp[];
		clear($temp);
		tokenize $buffer $temp;
		setAttr $temp[0] -type "string" $temp[1];
		$buffer = `fgetline $fileID`;
		$buffer = substituteAllString($buffer, "\n", "");
	}
	fclose $fileID;
	print "Hair cache link success";
}