global proc HhCamMibCreat()
{

	string $cams[]=`ls -sl`;
	for($cam in $cams)
	{
	  string $shape[]=`listRelatives  -s $cam`;
	  string $camt=`match "[^:]+$"$cam`;
	  string $mibv=$camt+"_mib_volume";
	  if(!`objExists $mibv`)
	  {
	      createNode "mib_volume" -n $mibv; 
	  } 
	  string $cammiv=$shape[0]+".mentalRayControls.miVolumeShader";
	  string $mivcon[]=`listConnections -plugs true -connections true -destination false $cammiv`;
	  if(size ($mivcon)!=0)
	  {
	      for ($i=0; $i<size($mivcon); $i+=2)
						{
							evalEcho ("disconnectAttr \"" +  $mivcon[$i+1] + "\" \"" +  $mivcon[$i] + "\"");

						}
	  }
	  connectAttr -f  ($mibv+".message") ($shape[0]+".mentalRayControls.miVolumeShader");
	  setAttr ($mibv+".color") -type double3 1 1 1 ;
  
}
