/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 霍健
///
/// Creation Date: 2006/11/15
///
/// Description: 
///





proc string jayeground()
{
	
	//create matter	
	        string $jayemater[]=`ls -materials "noMatter"`;
			if (`size $jayemater`==0)
			{
			string $sdra = `shadingNode -asShader -name noMatter lambert`;
    		setAttr ($sdra+".color") -type float3 0.5 0.5 0.5;
    		setAttr ($sdra+".hideSource") 1;
    		string $set = `sets -renderable true -noSurfaceShader true -empty`;
    		connectAttr ($sdra+".color") ($set+".surfaceShader");
			
			}
	
	//create ground	
	        string $jayemater[]=`ls -materials "Shadow_useBackground"`;
			if (`size $jayemater`==0)
			{
			string 	$sdrblur 	= `shadingNode -asShader -name Shadow_useBackground useBackground`;
			setAttr ($sdrblur+".specularColor") -type   double3 0.5 0.5 0.5;
			setAttr ($sdrblur+".reflectivity") 	0.0;
			string 	$setblur 	= `sets -name ShadowSG -renderable true -noSurfaceShader true -empty`;
			connectAttr ($sdrblur+".outColor") ($setblur+".surfaceShader");
			
			}
   return "";
}


global proc string jayeshadow()
{         
	        
	//create shadow layer		
			string $hjlistamesh			[]	=`ls -dag -ap -sl -type "mesh" `		;
			string $hjlglistnurber		[]	=`ls -dag -ap -sl -type "nurbsSurface" `;
			string $hjlglistsubdiv		[]	=`ls -dag -ap -sl -type "subdiv" `		;
			string $hjlistameshall		[]	=`ls -dag -ap  -type "mesh" `			;
			string $hjlglistnurberall	[]	=`ls -dag -ap 	-type "nurbsSurface" `	;
			string $hjlglistsubdivall	[]	=`ls -dag -ap  -type "subdiv" `			;
			string $hjlight				[]	=`ls -lights`;
			string $jayemesh			[] 	= stringArrayRemove($hjlistamesh, 	$hjlistameshall);
			string $jayestnurber 		[]	= stringArrayRemove($hjlglistnurber,	$hjlglistnurberall);
			string $jayestsubdiv 		[]	= stringArrayRemove($hjlglistsubdiv,	$hjlglistsubdivall);
			string $hjcrelayer				=`createRenderLayer -name "shadow" -number 1 -makeCurrent -noRecurse $hjlistameshall $hjlglistnurberall $hjlglistsubdivall $hjlight	`;
			string $jayeuseback[]			=`ls -materials "Shadow_useBackground"`;
			string $jayematerls[]			=`ls -materials "noMatter"`				;
			setAttr "defaultRenderLayer.renderable" 0					;
			layerEditorLayerButtonSelect 0 $hjcrelayer					;
		
			
			select 				$hjlistamesh $hjlglistnurber $hjlglistsubdiv	;
			hyperShade  -assign $jayeuseback[0]								;
			select 		-cl;
			
			select 				$jayemesh $jayestnurber $jayestsubdiv 			;
			hyperShade  -assign $jayematerls[0]									;
			select 		-cl;
			
		
			return "";
			
	
}








//return character name
proc string jayereturnname()
{
	string 	$jayeselgroups[]=`ls -sl`;
	string 	$jayeselnames;
    if (`size $jayeselgroups`==0)
	warning "请选择角色GEO和Master组节点";
	for ($jayeselnames in $jayeselgroups)
    {
        string 	$jayegrouplists [ ] ;
        string 	$jayegrouplistes=`tokenize $jayeselnames "_" $jayegrouplists`;
		if (`size $jayegrouplists`>=2)
		{
		string 	$jayegroupreturn=$jayegrouplists[0]+"_"+$jayegrouplists[1];
		return 	$jayegroupreturn;
		}
		else 
		{
		string 	$jayegroupreturn=$jayegrouplists[0]+"_001";
		return 	$jayegroupreturn;	
		}
	}
	
}


//create RGBA shade

global proc string[] jayecreateshade()
	
{
	    string $jayesade		=`jayeground`;
		string $jayeshade[]		=`ls -type shadingEngine`;
		string $jayeshadefind	="Blue_surfaceShaderSG";
		int    $jayeGroupint	=`stringArrayCount $jayeshadefind $jayeshade`;
		if($jayeGroupint!=1)
		
			{
		
				//create blueshade
				string $sdrblur 	= `shadingNode -asShader -name Blue_surfaceShader surfaceShader`;
				setAttr ($sdrblur+".outColor") -type float3 0.0 0.0 1.0;
				setAttr ($sdrblur+".outMatteOpacity") -type float3 0.0 0.0 0.0;
				string $setblur 	= `sets -name Blue_surfaceShaderSG -renderable true -noSurfaceShader true -empty`;
				connectAttr ($sdrblur+".outColor") ($setblur+".surfaceShader");
				
				
				//redshade
				string $sdrred 		= `shadingNode -asShader -name Red_surfaceShader surfaceShader`;
				setAttr ($sdrred+".outColor") -type float3 1.0 0.0 0.0;
				setAttr ($sdrred+".outMatteOpacity") -type float3 0.0 0.0 0.0;
				string $setred 		= `sets -name Red_surfaceShaderSG -renderable true -noSurfaceShader true -empty`;
				connectAttr ($sdrred+".outColor") ($setred+".surfaceShader");
				
				//greenshade
				string $sdrgreen 	= `shadingNode -asShader -name Green_surfaceShader surfaceShader`;
				setAttr ($sdrgreen+".outColor") -type float3 0.0 1.0 0.0;
				setAttr ($sdrgreen+".outMatteOpacity") -type float3 0.0 0.0 0.0;
				string $setgreen 	= `sets -name Green_surfaceShaderSG -renderable true -noSurfaceShader true -empty`;
				connectAttr ($sdrgreen+".outColor") ($setgreen+".surfaceShader");
				
				//alphashade
				string $sdralpha 	= `shadingNode -asShader -name Alpha_surfaceShader surfaceShader`;
				setAttr ($sdralpha+".outColor") -type float3 0.0 0.0 0.0;
				setAttr ($sdralpha+".outMatteOpacity") -type float3 1.0 1.0 1.0;
				string $setalpha 	= `sets -name Alpha_surfaceShaderSG -renderable true -noSurfaceShader true -empty`;
				connectAttr ($sdralpha+".outColor") ($setalpha+".surfaceShader");
				
			}
 
   return $jayeshade;
 } 


//txtname 
proc string[] jayeRGBAtxt ( )
{
		string $jcurscene 		=`file -q -sceneName -shortName `;
		string $jscenelist [ ] ;
		string $jtoscene		=`tokenize $jcurscene "_" $jscenelist`;
		string $jayeselgroup	=`jayereturnname`;
		string $dev_path = `getenv "DEV_PATH"`;
		string $jayaRGBpath		= $dev_path + "/Maya/shaders/"+$jscenelist[0]+"_RGBA/"+$jayeselgroup+"/";
		string $jayefilergb[]	=`getFileList -folder $jayaRGBpath -filespec "*.txt"`;
		return $jayefilergb;
}



// this is RGBAinfo
proc string[] jayeRGBAlist ( )
{
		string $jcurscene 		=`file -q -sceneName -shortName `;
		string $jscenelist [ ] ;
		string $jtoscene		=`tokenize $jcurscene "_" $jscenelist`;
		string $jayeselgroup	=`jayereturnname`;
		string $dev_path = `getenv "DEV_PATH"`;
		string $jayaRGBpath		= $dev_path + "/Maya/shaders/"+$jscenelist[0]+"_RGBA/"+$jayeselgroup+"/";
		string $jayefilergb[]	=`getFileList -folder $jayaRGBpath -filespec "*.txt"`;
		string $jayereturntxt[] ={$jayaRGBpath+$jayefilergb[0],$jayaRGBpath+$jayefilergb[1],$jayaRGBpath+$jayefilergb[2],$jayaRGBpath+$jayefilergb[3]};
		return $jayereturntxt;
}

proc string[] jayeReturnarray(string $jayepath)
{

		string 		$jayestring[];
		int 		$jayenumber	=0;
		int         $fileId		=`fopen $jayepath "r"`;
		string 		$nextLine 	= `fgetline $fileId`;
		while ( size( $nextLine ) > 0 ) 
		{
		$nextLin 				= `substitute "\n" $nextLine ""`;
		$jayestring[$jayenumber]=$nextLin;
		$nextLine 				= `fgetline $fileId`;
		$jayenumber++;
		}	
		
		return $jayestring;
		fclose $fileId; 
 
	}
	 


	
//create Renderlayer
global proc string jayerenderlayer()
	
    {   
		
			string $jayereturntxtname	[] 	=`jayeRGBAtxt`;
			string $jayereturntxtpath	[]	=`jayeRGBAlist`;
			
			string $jayereturnalpha		[]	=`jayeReturnarray $jayereturntxtpath[0]`;
			string $jayereturnred  		[]	=`jayeReturnarray $jayereturntxtpath[1]`;
			string $jayereturngreen		[]	=`jayeReturnarray $jayereturntxtpath[2]`;
			string $jayereturnblur 		[]	=`jayeReturnarray $jayereturntxtpath[3]`;
			string  $jayenameshadea			=`substitute ".txt" $jayereturntxtname[0] ""`;
			string  $jayenameshader			=`substitute ".txt" $jayereturntxtname[1] ""`;
			string  $jayenameshadeg			=`substitute ".txt" $jayereturntxtname[2] ""`;
			string  $jayenameshadeb			=`substitute ".txt" $jayereturntxtname[3] ""`;
		    string $hjlistamesh			[]	=`ls -dag -ap -sl -type "mesh" `;
			string $hjlglistnurber		[]	=`ls -dag -ap -sl -type "nurbsSurface" `;
			string $hjlglistsubdiv		[]	=`ls -dag -ap -sl -type "subdiv" `;
			string $jayenamelayers			=`jayereturnname`+"RGBA";
			string $hjcrelayer				=`createRenderLayer -name $jayenamelayers -number 1 -makeCurrent -noRecurse $hjlistamesh	$hjlglistnurber $hjlglistsubdiv`;
			string $jayerenderlayoutls	[]	=`editRenderLayerMembers -q -fullNames $hjcrelayer`;
			
			string $jayediffa			[] 	= stringArrayRemove($jayereturnalpha, 	$jayerenderlayoutls);
			string $jayediffalpha 		[]	= stringArrayRemove($jayediffa,	$jayerenderlayoutls);
			
			string $jayediffr			[] 	= stringArrayRemove($jayereturnred, $jayerenderlayoutls);
			string $jayediffred 		[]	= stringArrayRemove($jayediffr,	$jayerenderlayoutls);
			string $jayediffg			[] 	= stringArrayRemove($jayereturngreen, $jayerenderlayoutls);
			string $jayediffgreen 		[]	= stringArrayRemove($jayediffg,	$jayerenderlayoutls);
			string $jayediffb			[] 	= stringArrayRemove($jayereturnblur, $jayerenderlayoutls);
			string $jayediffblur 		[]	= stringArrayRemove($jayediffb,	$jayerenderlayoutls);
			setAttr "defaultRenderLayer.renderable" 0;
			layerEditorLayerButtonSelect 0 $hjcrelayer;
			int $hjcheckinbox=`checkBox -q -v jayecheckbox`;
			if($hjcheckinbox==0)
			{
			select 				$jayereturnalpha	;
			hyperShade  -assign $jayenameshadea		;
			select 		-cl;
			select 				$jayereturnred  		;
			hyperShade  -assign $jayenameshader		;
			select 		-cl;
			select 				$jayereturngreen 	;
			hyperShade  -assign $jayenameshadeg		;
			select 		-cl;
			select 				$jayereturnblur		;
			hyperShade  -assign $jayenameshadeb		;
			select 		-cl;
			}
			else
			{
			select 				$jayereturnalpha	;
			hyperShade  -assign $jayenameshadea		;
			select 		-cl;
			select 				$jayediffred 		;
			hyperShade  -assign $jayenameshader		;
			select 		-cl;
			select 				$jayediffgreen 		;
			hyperShade  -assign $jayenameshadeg		;
			select 		-cl;
			select 				$jayediffblur		;
			hyperShade  -assign $jayenameshadeb		;
			select 		-cl;	
				
			}
			return "";
   
     
     }




global proc hjRgbatranstion()
{      
		
	    jayecreateshade;
		if(`window -ex jayeRGBAwindowUI`) deleteUI jayeRGBAwindowUI;
		string $jayewindow_name 		=` window -title "RGBA_append window" jayeRGBAwindowUI`;
		menuBarLayout;
		  menu -label "Help";
		  menuItem -label "Help on RGBlayer " -command "zjHelpCallback hjRgbatranstion";
		columnLayout -adjustableColumn true -columnWidth 10;
		checkBox 	-label "NO object matches name" -value 0 jayecheckbox;
		//button 		-label "RGBAShadowshade" 		-c jayecreateshade 	-align "center" 		hjlayerset;
		button 		-label "RGBLayer"  		-c jayerenderlayer 	-align "center" 		hjrgbinfoset;
		//button 		-label "Shadowshade"  	-c jayerenderlayer 	-align "center" 	hjrgbinfosetf;
		button 		-label "ShadowLayer" 	-c jayeshadow 		-align "center" 		hjrgbinfoseta;	
			setParent ..;
		setParent ..;
		
		
		
		showWindow $jayewindow_name;	
}
