

global proc hqSetLightmapLocal()
{
	
	source "MusterCheckin.mel";

	if (`pluginInfo -query -loaded "Mayatomr.mll"`)
	{
		string $ment[] = `ls -type mentalrayTexture`;
		if (size($ment) > 0)
		{
			string $SSS_Tex = `optionVar -query musterCheckinProject` + `optionVar -query musterCheckinProjectName` + "\\renderData\\mentalray\\lightMap";
			if (!`filetest -d $SSS_Tex`)
			{
				sysFile -makeDir $SSS_Tex;
			}
			string $sceneName = `file -q -sceneName -shortName`;
			$SSS_Tex = $SSS_Tex + "\\" + $sceneName + ".iff";
			if (!`filetest -f $SSS_Tex`)
			{
				int $fileId = `fopen $SSS_Tex "w"`;
				fclose $fileId;
			}
			for ($temp in $ment )
			{
				setAttr -type "string" ($temp + ".fileTextureName") $SSS_Tex;
			}
		}
	}
}