/// Author: liang
///
/// Creation Date: 2007/02/02
///
/// Description: 
///
/// Modify: liang

///////////////////////////////////////////////////////////////////

global proc addNeckLidControl(string $charName)
{
	string $templist[] = `ls -sl`;
	string $tempCurrentList;
	for($tempCurrentList in $templist)
	{
	parent -add -s ($tempCurrentList + "IconShape") $tempCurrentList;
	delete ($tempCurrentList + "Icon");
	
	}
}



