//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: zhaozhongjie
//	Created: 
//
//	Update/Change: zhaozhongjie
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc iRenderCommonToolsUI()
{
	source ezRenderMainLayout.mel;
	source ezRenderMainLayoutMaterial.mel;
	string $path = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\icons\\BenAdnIzzy\\render\\";	
	string $path = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\Import\\PPTools\\icon\\";
	
	separator -style "none" -height 6 iRenderCommonToolsHeader;
	
	//分层工具
	source ezRenderMainLayoutRenderLayer.mel;
	
	//total分层工具
	source "slRenderLayerTotalTools.mel";
		
	frameLayout -l "为材质赋材质" -collapsable true -width 420 materialFL;
		rowLayout -nc 8  -cw 1 50 -cw 2 50 -cw 3 50 -cw 4 50 -cw 5 50 -cw 6 50 -cw 7 50 -cw 8 50 ;
			symbolButton -ann "ColorR" -image ($path+"colorR.bmp") -command "ezRenderMainLayoutMaterial_Assign(\"colorR\")";
			symbolButton -ann "ColorG" -image ($path+"colorG.bmp") -command "ezRenderMainLayoutMaterial_Assign(\"colorG\")";
			symbolButton -ann "ColorB" -image ($path+"colorB.bmp") -command "ezRenderMainLayoutMaterial_Assign(\"colorB\")";
			symbolButton -ann "ColorA" -image ($path+"colorA.bmp") -command "ezRenderMainLayoutMaterial_Assign(\"colorA\")";
			symbolButton -ann "Matte"  -image ($path+"matte.bmp")  -command "ezRenderMainLayoutMaterial_Assign(\"matte\")";
			symbolButton -ann "Depth"  -image ($path+"depth.bmp")  -command "ezRenderMainLayoutMaterial_Assign(\"depth\")";
			symbolButton -ann "Shadow" -image ($path+"shadow.bmp") -command "ezRenderMainLayoutMaterial_Assign(\"shadow\")";
			symbolButton -ann "AO"     -image ($path+"AO.bmp")     -command "ezRenderMainLayoutMaterial_Assign(\"AO\")";
		setParent ..;
	setParent ..;
	separator -style "none" -height 10;
	
	frameLayout -l "常用工具集合" -collapsable true -width 420 commonToolsFL;
		rowColumnLayout -nc 4 -cw 1 100 -cw 2 100 -cw 3 100 -cw 4 100;
			button -l "idPass" -c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjIdPassInfo.mel\";zzjIdPassInfo;" ;
			button -l "自留地" ;
			button -l "自留地" ;
			button -l "自留地" ;
			button -l "自留地" ;
			button -l "自留地" ;
			button -l "自留地" ;
			button -l "自留地" ;
		setParent ..;
	setParent ..;
	separator -style "none" -height 10;
	
	
	
	
		frameLayout -l "灯光工具集合" -collapsable true -width 420 lightingToolsFL;
			rowColumnLayout -nc 4 -cw 1 100 -cw 2 100 -cw 3 100 -cw 4 100;
				button -l "Create Light" ;
				button -l "Lighting_name" ;
				button -l "Lighting List" ;
				button -l "Lighting Render" ;
				button -l "临时" ;
				button -l "临时" ;
				button -l "临时" ;
			setParent ..;
		setParent ..;
		
		separator -style "none" -height 10;
		
}
