//08.01.2005 imput haircache file;


global proc jayehairinput ()
{
	
string $jcurscenepath=`workspace -q -act`;
string $jscencpath = $jcurscenepath+"/data/";

string $jcurscene =`file -q -sceneName -shortName `;
string $jscenelist [ ] ;
string $jtoscene=`tokenize $jcurscene "_" $jscenelist`;
string $jpathscene="//File-cluster/GDC/Projects/BRATZ/Production/Animation/episode_"+$jscenelist[1]+"/scene_"+$jscenelist[2]+"/cloth/";
string $jhairrel = $jpathscene+"cacheLink.rel";




int     $jfileid=`fopen $jhairrel  "r "`;
string $hjfilelistpath []= `getFileList -folder $jpathscene -filespec "*.mchp"`;
int    $hjnamesize =`size $hjfilelistpath`;

string $jcachelistmp[] =`ls -type "diskCache"`;
int $jcachesize=`size $jcachelistmp`;
int $jamount = 0;
string $jlocapatch;

progressWindow

           -title "Haircache_input"

           -progress $jamount

           -status "Complete: 0%"
           
		   -maxValue $hjnamesize
           
		   -isInterruptable true;



  for  ($n=0;$n<$hjnamesize;$n++)
     {    
	
	 float $jamountem=$n;
	 
     if ( `progressWindow -query -isCancelled` ) break;
     if ( `progressWindow -query -progress` >= 100 ) break;
     $jamount =$jamountem/$hjnamesize*100;
     
	 progressWindow -edit 

                    -progress $jamount 

                   -status ("Complete: "+$jamount+"%");

   

           pause -seconds 1;

    

	 //line haircachepath for cacherel;
     string  $hjnamelisttem=` fgetline $jfileid `;
	 string  $hjnamelistnet=substituteAllString($hjnamelisttem,"\n","");
	 string $jcachelistname[];                        
     string $jarmname =` tokenize $hjnamelistnet " " $jcachelistname`;
     string $jnamelongsun[];
	 string $jnamealong = ` tokenize $jcachelistname[1] "/" $jnamelongsun`;
	 int    $jnamelongsize =`size $jnamelongsun`-1;
	 string $jnamecachelong = $jnamelongsun[$jnamelongsize];
	 string $jrelcachename[];    
	 string $jrelcache=`tokenize $jcachelistname[0] "." $jrelcachename`;
	 string $jrelname=$jrelcachename[0];
     

for ($jlocapatch in $jcachelistmp)
{
	
	if (`attributeExists "cacheFile" $jlocapatch`)
	{
	 string $jlocaname=`getAttr ($jlocapatch+".cacheFile")`;
	 
	 string $jayename=$jlocapatch+".cacheName";
	 string $jayenamepatch[];
	 string $jayelong =`tokenize $jlocaname "/" $jayenamepatch`;
	 string $jayecache  =$jscencpath+$jlocaname;
	 int    $jayesize=`size $jayenamepatch`;
	 string $jayecachepatch=$jayenamepatch[$jayesize-1];
	 
	 string $jayenetcache =$jscencpath+$jayecachepatch;
	 print  $jayenetcache;
	 
	 sysFile -copy $jayenetcache $jlocaname;
	 setAttr -type "string" $jayename $jayenetcache;
	 
	 
	 
	
    
	}
    else 
	{
	 

	
	for($j=0; $j<$jcachesize;$j++)
	{
	string $jcachelist =$jcachelistmp[$j];
    
	
	
    
	int $jnamelist =!`strcmp $jcachelist $jrelname`;
    
	if ($jnamelist==1)
	{     
		  string $jalocodname=$jcachelist+".cacheName";
		  string $jnetcache  =$jscencpath+$jnamecachelong;
		  sysFile -copy $jnetcache $jcachelistname[1];
		  setAttr -type "string" $jalocodname $jnetcache;
		  
	        }
	
	     
          }
	  
       }
    }
 

   }
progressWindow -endProgress;
}

