/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcCheckEmptyUV()
{
	string $objs[] = `ls -noIntermediate -long -type mesh`;
   
	select -clear;

	int $flag = false;

	for ($item in $objs)
	{
		int $numUV[] = `polyEvaluate -uv $item`;

		if ($numUV[0] == 0)
		{
			string $parents[] = `listRelatives -parent -path $item`;
			select -add $parents[0];

			print($parents[0] + ": no UV.\n");

			$flag = true;
		}
	}

	if ($flag)
		warning("There are objects with empty UV. Please check Script Editor");
	else
	    print("All objects have UV.\n");
}