/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcCombineSL()

{

    string $selected[] = `ls -type surfaceLuminance`;



    if (size($selected) > 1)

    {

        string $baseClamps[] = `listConnections ($selected[0] + ".outValue")`;



        if ((size($baseClamps) < 1) || (`nodeType $baseClamps[0]` != "clamp"))

            error("Surface luminance node: " + $selected[0] + " is not connected to a clamp node.");



        for ($i = 1; $i < size($selected); $i++)

        {

            string $clamps[] = `listConnections ($selected[$i] + ".outValue")`;



            if ((size($clamps) < 1) || (`nodeType $clamps[0]` != "clamp"))

                error("Surface luminance node: " + $selected[$i] + " is not connected to a clamp node.");



            string $connections[] = `listConnections -source false -destination true -connections true -plugs true $clamps[0]`;



            for ($j = 0; $j < size($connections); $j += 2)

            {

                string $buf[];

                tokenize $connections[$j] "." $buf;

                string $sourceAttr = $buf[1];

    

                connectAttr -force ($baseClamps[0] + "." + $sourceAttr) $connections[$j + 1]; 

            }

 

            delete $selected[$i];

            delete $clamps[0];

        }

    }

}