/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcCrowdCreateFlowField()
{
	// load plugin if not already loaded

	if (!`pluginInfo -q -loaded flowfield`)
		loadPlugin -quiet flowfield;

	if (!`pluginInfo -q -loaded crowdUtility`)
		loadPlugin -quiet crowdUtility;


	// create Flow Field

	string $selected[] = `ls -selection`;

	if ((size($selected) != 1) || (!kcIsType($selected[0], "nurbsSurface")))
		error("Select only a Nurbs surface.");

	string $surf = $selected[0];
	string $flowfield = `createNode flowfield -name flowFieldShape`;

	connectAttr ($surf + ".worldSpace[0]") ($flowfield + ".inputNurbSurf");
}