/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc string [] getLayerSelection(string $type)
//
//	Description:
//		Return the current layer selection for the specified layer type.
//
//	Arguments:
//		$type - Valid values are: "Display", "Render", or
//		        an emtpy string. In the case of an empty string the
//				current layer type displayed in the editor will be used.
//
//	Returns:
//		A string array containing the names of the selected layers.
//
{
	global string $gCurrentLayerEditor;

	string $selectionArray[];
	string $buttonLayout = "", $button, $buttonArray[];
	int    $index = 0;

	//	If type argument not specified then determine it.
	//
	if ("" == $type) {
		$type = getLayerDisplayType();
	}

	//	Set the parent to the current layer editor. We can now use short
	//	names of our controls and be certain they reference the correct
	//	control.
	//
	setParent $gCurrentLayerEditor;

	//	Get the correct layout of layer buttons depending on the type of
	//	layers currently being shown.
	//
	if ("Display" == $type) {
		$buttonLayout = "LayerEditorDisplayLayerLayout";

	} else if ("Render" == $type) {
		$buttonLayout = "LayerEditorRenderLayerLayout";

	} else {
		error ("Invalid layer type: " + $type);
		return $selectionArray;
	}

	//	Get all the buttons in the layout.
	//
	$buttonArray = `layout -query -childArray $buttonLayout`;

	//	For each button check to see if it is selected.
	//
	for ($button in $buttonArray) {
		if (("Display" == $type && `layerButton -query -select $button`)
			|| ("Render" == $type && `renderLayerButton -query -select $button`)) {
			$selectionArray[$index++] = $button;
		}
	}

	return $selectionArray;
}

global proc kcDelSelLayer()
{
	string $layers[] = `getLayerSelection "Display"`;

	for ($item in $layers)
	{
		string $members[] = `editDisplayLayerMembers -fullNames -q $item`;

		delete $members $item;
//		delete $item;
	}
}