/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcHairAssignSelectedParticleWeightUniformDistCB(string $stickPercentSlider, string $minWeightSlider)
{
	float $stickPercent = `floatSliderGrp -q -value $stickPercentSlider`;
	float $minWeight = `floatSliderGrp -q -value $minWeightSlider`;

	string $selected[] = `ls -selection`;

	for ($item in $selected)
		if (kcIsType($item, "particle"))
			kcHairAssignParticleWeightUniformDist($item, $stickPercent, $minWeight);
}

global proc kcHairAssignSelectedParticleWeightUniformDistGUI()
{
	if (`window -q -exists kcHairAssignSelectedParticleWeightUniformDistWnd`)
		return;

	window -title "Hair Main GUI" -resizeToFitChildren true kcHairAssignSelectedParticleWeightUniformDistWnd;
		
		string $formLayout = `formLayout`;

			string $stickPercentSlider = `floatSliderGrp -label "Stick Percentage" -field true -minValue 0.0 -maxValue 1.0 -fieldMinValue 0.0 -fieldMaxValue 1.0 -value 0.4`;
			string $minWeightSlider = `floatSliderGrp -label "Min Particle Weight" -field true -minValue 0.0 -maxValue 1.0 -fieldMinValue 0.0 -fieldMaxValue 1.0 -value 0.5`;
			string $button = `button -label "Apply" -command ("kcHairAssignSelectedParticleWeightUniformDistCB " + $stickPercentSlider + " " + $minWeightSlider)`;

		setParent ..;

		formLayout -edit
			-attachForm		$stickPercentSlider		"top"		5
			-attachForm		$stickPercentSlider		"left"		5
			-attachForm		$stickPercentSlider		"right"		5

			-attachControl	$minWeightSlider		"top"		5	$stickPercentSlider
			-attachForm		$minWeightSlider		"left"		5
			-attachForm		$minWeightSlider		"right"		5

			-attachControl	$button		"top"		5	$minWeightSlider
			-attachForm		$button		"left"		5
			-attachForm		$button		"right"		5
		$formLayout;

	showWindow kcHairAssignSelectedParticleWeightUniformDistWnd;
}