/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcModifyShader()
{
	string $moepass[] = `ls -type "moebiusPass"`;	

	for ($i=0; $i<size($moepass); $i++)
	{
		string $spec[] = `listConnections -source 1 ($moepass[$i]+".specular")`;

		if ((size($spec) > 0) && (`nodeType $spec[0]` == "blinn"))
		{
			string $attr = $spec[0] + ".eccentricity";
			string $dest[] = `listConnections -source true -destination false $attr`;

			if ((size($dest) == 0) && (!`getAttr -lock $attr`))
				setAttr $attr 0.3;

			string $attr = $spec[0] + ".specularRollOff";
			string $dest[] = `listConnections -source true -destination false $attr`;

			if ((size($dest) == 0) && (!`getAttr -lock $attr`))
				setAttr $attr 0.7;
		}

		string $surfaceshader[] = `listConnections -destination 1 ($moepass[$i]+".outColor")`;

		if ((size($surfaceshader) > 0) && (`nodeType $surfaceshader[0]` == "surfaceShader"))
		{
			string $attr = $surfaceshader[0] + ".ClampLowColor";
			string $dest[] = `listConnections -source true -destination false $attr`;

			if ((size($dest) == 0) && (!`getAttr -lock $attr`))
				setAttr $attr 0.5;

			string $attr = $surfaceshader[0] + ".ClampHighColor";
			string $dest[] = `listConnections -source true -destination false $attr`;

			if ((size($dest) == 0) && (!`getAttr -lock $attr`))
				setAttr $attr 0.8;
		}
	}
}
