/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcPanshelLockElbow()
{
	string $names[] = {"panda01",
					   "panda02",
					   "panda03",
					   "panda04",
					   "panda05",
					   "panda06",
					   "panda07",
					   "panda08",
					   "panda09",
					   "panda10",
					   "panshel",
					   "panshenee"};

	for ($item in $names)
	{
		string $node = $item + "_forearm_r";

		if (`objExists $node`)
			setAttr -lock true ($node + ".rotateX");

		string $node = $item + "_forearm_l";

		if (`objExists $node`)
			setAttr -lock true ($node + ".rotateX");

		string $node = $item + "_elbow_r";

		if (`objExists $node`)
			setAttr -lock true ($node + ".rotateX");

		string $node = $item + "_elbow_l";

		if (`objExists $node`)
			setAttr -lock true ($node + ".rotateX");

		string $node = $item + "_elbow_r";

		if (`objExists $node`)
			setAttr -lock true ($node + ".rotateY");
	}
}