/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcPrepLine()
{
	kcEFXPresetCmd;

	// create EFX contour shader

	string $efxContour = `shadingNode -asShader EfxContour`;
	string $efxContourSG = `sets -renderable true -noSurfaceShader true -empty -name EfxContourSG`;
	connectAttr -f ($efxContour + ".outColor") ($efxContourSG + ".surfaceShader");

	// set EFX contour parameters

	setAttr ($efxContour + ".lineWidth") 0.6;
	setAttr ($efxContour + ".thresholdMin") 1;
	setAttr ($efxContour + ".lineWidth") 0.6;
	setAttr ($efxContour + ".thresholdMin") 2;
	setAttr ($efxContour + ".thresholdMin") 1;
	setAttr ($efxContour + ".thresholdMax") 1.2;
	setAttr ($efxContour + ".detectorLimit") 2;
	setAttr ($efxContour + ".detectorFalloff") 1;
	setAttr ($efxContour + ".sampleCount") 15;

	// assign EFX contour shader to all mesh and nurbsSurface

	string $selection[] = `ls -type mesh -type nurbsSurface`;
	sets -e -forceElement $efxContourSG $selection;
}