/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: Kiem Ching
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc kcRenameNode_G(string $item, string $new)
{
	string $temp = `rename $item $new`;
	print("old: " + $item + "\t\tnew: " + $temp + "\n");

	// verify that rename is OK

	string $tokens[];
			
	if (`tokenize $temp "|" $tokens` > 0)
	{
		$temp = $tokens[size($tokens) - 1];

		if ($temp != $new)
			warning($item + " is renamed to " + $temp + " instead of " + $new + "\n");
	}
}
