/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ¿Ó»Ò
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc matrix lr_MatrixMult(matrix $mtx1, matrix $mtx2)
{
   //   $mtx1 * $mtx2
   
   matrix $remtx[4][4];

   float $res = 0.0;
   for($i=0;$i<4;$i++)
   {
      for($j=0;$j<4;$j++)
      {
      	  $res = 0.0;
      	  for($k=0;$k<4;$k++)
      	  {
      	     $res = $res + $mtx1[$i][$k]*$mtx2[$k][$j];      	   
      	  }
      	  
      	  $remtx[$i][$j] = $res;
      }
   }
   return $remtx;
}