/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ¿Ó»Ò
///
/// Creation Date: 2006/11/15
///
/// Description: 
///



global proc int lr_OPTtest()
{
	print "Removing connections between lightLinker1 and hyperGraphLayout or initialShadingGroup\n";
	print "--------------------------------\n";

	int $numDel = 0;

	string $lightLinkers[] = `ls -type "lightLinker"`;
	for ($lightLinker in $lightLinkers)
	{
		string $links[]  = `ls ($lightLinker + ".lnk[*].olnk")`;
		for ($i=0; $i<size($links); $i++)
		{
			string $att = $lightLinker + ".lnk[" + $i + "]"; 
			if(`isConnected "hyperGraphLayout.msg" $links[$i]` || `isConnected "initialShadingGroup.msg" $links[$i]` || `isConnected "defaultLightSet.msg" $links[$i]`)
			{
				removeMultiInstance -b 1 $att;
				$numDel ++;
			}
		}
	}

	cleanUp_Summary( "Removed connections between lightLinker1 and hyperGraphLayout|initialShadingGroup|defaultLightSet", ("Removed " + $numDel + " connections between lightLinker1 and hyperGraphLayout or initialShadingGroup") );

	print "\n";

	return $numDel;
}