/// Author: liang
///
/// Creation Date: 2007/01/23
///
/// Description: 
/// Modify: liang
global proc modify_korrect(string $charName)
{
	delete ($charName + "_headConstrainValue_orientConstraint");
	group -em -name ($charName + "_headConstrainTarget");
	parent ($charName + "_headConstrainTarget") ($charName + "_MASTER");
	orientConstraint -n ($charName + "_headConstrainValue_orientConstraint") -mo -weight 1 ($charName + "_headConstrainTarget") ($charName + "_headConstrainValue");
	//end
}
