//mtUVCheck.mel


global proc mtUVCheck() {


string $sel[]=`ls -sl`;
int $uvs[]=`polyEvaluate -uvcoord`;
select -cl;
select -r ($sel[0]+".map[0:"+(($uvs[0])-1)+"]");
float $maxmins[]=`polyEvaluate -boundingBoxComponent2d`;

if (($maxmins[0]<0) || ($maxmins[1]>1)  || ( $maxmins[2]<0)  || ($maxmins[3]>1  )){
print "  Out of bounds!!!!!!/r/n";}else{ 
print "All is good!/r/n"};

select $sel[0];
error "objects UVS are not within 0,1space,plese check the selected object ";
}