/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: mw
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc mwApplyMap()
{
	$tmp = `ls -sl`;
	string $file = `fileDialog`;
	for($node in $tmp)
	{
		artSetToolAndSelectAttr artAttrCtx ("particle."+$node+"ParticleShape.goalPP");
		artAttrSetFiler "particle" artAttrCtx;
		artImportAttrMapCB artAttrCtx  $file "image";
		print ("IMPORTING FILE: "+$file+" TO: "+$node+"\n");
	}
	select -r $tmp;
}