/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: mw
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc mwAxlyxFix()
{
	for($i=0;$i<2;$i++)
	{
		string $side, $joint, $ring, $grommet1, $grommet2, $cv, $parent;
		if($i==0)
		{
			$side = "l";
			$joint = "axylxwar_c_hi_jiang_7_joint2";
			$ring = "axylxwar_c_hi_jiang_8";
			$grommet1 = "axylxwar_c_hi_jiang_9";
			$grommet2 = "axylxwar_c_hi_jiang_10";
			$cv = "axylx_GEO|axylxwar_c_hi_jiang_7.vtx[248:263]";
			$parent = "axylxwar_c_hi_jiang_7_cluster40Handle_group";
		}
		else
		{
			$side = "r";
			$joint = "axylxwar_c_hi_jiang_7_joint9";
			$ring = "axylxwar_c_hi_jiang_12";
			$grommet1 = "axylxwar_c_hi_jiang_13";
			$grommet2 = "axylxwar_c_hi_jiang_14";
			$cv = "axylx_GEO|axylxwar_c_hi_jiang_7.vtx[120:135]";
			$parent = "axylxwar_c_hi_jiang_7_cluster44Handle_group";
		}

		//CREATE NULL GROUP
		string $group = `group -n ("axlyxwar_ringGroup_"+$side) -empty`;
		if($i==0)
		{
			xform -os -piv 1.623173 8.276993 6.178124 $group;
		}
		else
		{
			xform -os -piv (-1.623173) 8.276993 6.178124 $group;
		}

		//AIM CONSTRAIN NULL GROUP TO SECOND STRAP JOINT ONLY ON ROTATE X
		string $ac[] = `aimConstraint -weight 1 -aimVector 0 0 -1 -upVector 0 1 0 -worldUpType "vector" -worldUpVector 0 1 0 $joint $group`;
		disconnectAttr ($ac[0]+".constraintRotateY") ($group+".ry");
		setAttr ($group+".ry") 0;
		disconnectAttr ($ac[0]+".constraintRotateZ") ($group+".rz");
		setAttr ($group+".rz") 0;

		//UNLOCK RING ATTRIBUTES
		setAttr -l 0 ($ring+".tx");
		setAttr -l 0 ($ring+".ty");
		setAttr -l 0 ($ring+".tz");
		setAttr -l 0 ($ring+".rx");
		setAttr -l 0 ($ring+".ry");
		setAttr -l 0 ($ring+".rz");
		setAttr -l 0 ($ring+".sx");
		setAttr -l 0 ($ring+".sy");
		setAttr -l 0 ($ring+".sz");
		setAttr -l 0 ($ring+".visibility");
		parent -w $ring;
		setAttr ($ring+".rx") -24.5;

		//CREATE GROUP FOR RING
		string $ringGroup = `group -n ("axlyxwar_ring_"+$side) $ring`;
		setAttr ($ringGroup+".rx") 24.5;

		//INSTANCE RING TRANSFORM NODE
		string $instance[] = `instance $ring`;
		setAttr ($instance[0]+".visibility") 0;
		string $ac1[] = `aimConstraint -weight 1 -aimVector 0 0 -1 -upVector 0 1 0 -worldUpType "vector" -worldUpVector 0 1 0 $joint $instance[0]`;

		//ROTATE RING ONLY ON Y
		float $ry = `getAttr ($instance[0]+".ry")`;
		string $val;
		if($ry<0)
		{
			$val = ("\("+$ry+"\)");
		}
		else
		{
			$val = $ry;
		}
		string $exp = `expression -n ("AXLYX_RING_"+$side) -s ($ring+".ry = "+$instance[0]+".ry-"+$val+";")  -o "" -ae 1 -uc all `;

		//PARENT GROMMETS TO RING
		setAttr -l 0 ($grommet1+".tx");
		setAttr -l 0 ($grommet1+".ty");
		setAttr -l 0 ($grommet1+".tz");
		setAttr -l 0 ($grommet1+".rx");
		setAttr -l 0 ($grommet1+".ry");
		setAttr -l 0 ($grommet1+".rz");
		setAttr -l 0 ($grommet1+".sx");
		setAttr -l 0 ($grommet1+".sy");
		setAttr -l 0 ($grommet1+".sz");
		setAttr -l 0 ($grommet1+".visibility");
		setAttr -l 0 ($grommet2+".tx");
		setAttr -l 0 ($grommet2+".ty");
		setAttr -l 0 ($grommet2+".tz");
		setAttr -l 0 ($grommet2+".rx");
		setAttr -l 0 ($grommet2+".ry");
		setAttr -l 0 ($grommet2+".rz");
		setAttr -l 0 ($grommet2+".sx");
		setAttr -l 0 ($grommet2+".sy");
		setAttr -l 0 ($grommet2+".sz");
		setAttr -l 0 ($grommet2+".visibility");
		parent $grommet1 $grommet2 $ring;

		//PARENT RING GROUP TO NULL GROUP
		parent $ringGroup $group;
		setAttr -l 1 ($ringGroup+".tx");
		setAttr -l 1 ($ringGroup+".ty");
		setAttr -l 1 ($ringGroup+".tz");
		setAttr -l 1 ($ringGroup+".rx");
		setAttr -l 1 ($ringGroup+".ry");
		setAttr -l 1 ($ringGroup+".rz");
		setAttr -l 1 ($ringGroup+".sx");
		setAttr -l 1 ($ringGroup+".sy");
		setAttr -l 1 ($ringGroup+".sz");
		setAttr -l 1 ($ringGroup+".visibility");

		//CREATE CLUSTER FOR END OF STRAP
		string $cluster[] = `cluster $cv`;
		reorderDeformers "skinCluster7" $cluster[0] "axylx_GEO|axylxwar_c_hi_jiang_7";

		//CREATE LOCATOR AS WEIGHTED NODE
		string $loc[] = `spaceLocator`;
		string $pc[] = `pointConstraint -weight 1 $ring $loc`;
		orientConstraint -weight 1 $ring $loc;
		delete $pc;
		string $shape[] = `listRelatives -shapes $cluster[1]`;
		cluster -e -bs 1 -wn $loc[0] $loc[0] $shape[0];
		delete $cluster[1];
		$loc[0] = `rename $loc[0] ("AXLYXWAR_RINGLOC_"+$side)`;
		string $locGroup = `group -n ("AXLYXWAR_RINGLOCGROUP_"+$side) -empty`;
		if($i==0)
		{
			xform -os -piv 1.623173 8.276993 6.178124 $locGroup;
		}
		else
		{
			xform -os -piv (-1.623173) 8.276993 6.178124 $locGroup;
		}
		orientConstraint -weight 1 $group $locGroup;
		parent $loc $locGroup;
		parent $locGroup axylx_GEO ;

		//PARENT GROUP INTO HIERARCHY
		parent $group $parent;
	}
}