/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: mw
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


//THIS PROCEDURE IMPORTS ONE FILE WITH ANIM CURVES.
//THEN READS A VALUE FILE AND A CONNECTIONS FILE TO SET EVERYTHING.

global proc mwImportAnim()
{
	$tmp = `ls -sl`;

	//IMPORT ANIM CURVES FILE
	string $file = `fileDialog`;

	string $name_parts[];
	int $tok = tokenize($file, "/", $name_parts);
	string $conFile = ($name_parts[0]+"/");
	for($i=1;$i<$tok-2;$i++)
	{
		$conFile = ($conFile+"/"+$name_parts[$i]);
	}
	$conFile = ($conFile+"/data/"+$tmp[0]+"_CONNECTIONS.txt");
	string $valueFile = `substitute "CONNECTIONS" $conFile "ANIM"`;

	//CHECK TO SEE IF CONNECTION AND VALUE FILES EXIST
	if(`file -q -ex $conFile`&&`file -q -ex $valueFile`)
	{
		file -import $file;

		//SOURCE CONNECTIONS FILE
		int $fileId =`fopen $conFile "r"`;
    		string $nextLine = `fgetline $fileId`;
   		while ( size( $nextLine ) > 0 ) 
		{
 			print ($nextLine+"\n");
    			eval ( $nextLine );
    			$nextLine = `fgetline $fileId`;
    		}
    		fclose $fileId;

		//SOURCE VALUE FILE
		$fileId =`fopen $valueFile "r"`;
    		$nextLine = `fgetline $fileId`;
   		while ( size( $nextLine ) > 0 ) 
		{
			print ($nextLine+"\n");
    			eval ( $nextLine );
    			$nextLine = `fgetline $fileId`;
    		}
    		fclose $fileId;
	}
	else
	{
		print "CONNECTIONS AND/OR VALUE FILE DOES NOT EXIST\n";
	}
}