/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: mw
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


//EXPORT TRANSFORMS FROM LAYOUT
global proc mwLayoutData()
{
	//GET CURRENT FILE NAME
	string $file = `file -q -sn`;
	string $dataFile = `substitute ".mb" $file "_TRANSFORMS.txt"`;
	$dataFile = `substitute "MASTER" $dataFile "WORKING"`;
	$dataFile = `substitute "/approved" $dataFile ""`;
	int $fileId = `fopen $dataFile "w"`;

	//GET ALL MUSHROOM TRANSFORM NAMES
	string $meshList[] = `ls -type mesh`;
	for($mesh in $meshList)
	{
		string $parent[] = `listRelatives -parent -fullPath $mesh`;
		fprint $fileId ($parent[0]+"\n");
	}
	fclose $fileId;

	print "ALL DONE WRITING LAYOUT DATA FILE\n\n";
}