/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: mw
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc mwTransferCharacterSetup()
{
	string $window = `window -title "Transfer Character Setup"
    		-iconName "Transfer Setup"
    		-widthHeight 200 55`;
   	string $parent = `columnLayout -adjustableColumn true`;

     	 	button -label "Export Deformation Data" -command ("mwExportCharacterSetup;");
		separator;

		string $import_cmd = ("string \$dir= \(`workspace -q -act` + \"/scenes/\" + \"*.mb\"\);\n"+
		"string \$file = `fileDialog -dm \$dir`;\n"+
		"file -import -type \"mayaBinary\" -rpr \"z\" -options \"v=0\" \$file;");

  	 	button -label "Import New Character Model" -command $import_cmd;
		separator;

  	 	button -label "Import Deformation Data" -command ("mwImportCharacterSetup \$master \$data \$cluster_list \$mesh_list;");
		separator;

		string $delete_cmd = ("string \$cluster;\nfor\(\$cluster in \$cluster_list\)\n"+
		"{\n\t"+
			"string \$file = \(\$data+\$master+\"_\"+\$cluster+\"_EXPORT_DATA.data\"\);\n\t"+
			"print \(\"DELETING CLUSTER FILE: \"+\$file+\"\\n\"\);\n\t"+
			"sysFile -delete \$file;\n"+
		"}\nsysFile -delete \(\$data+\$master+\"_PARENT_DATA.data\"\);\n"+
		"sysFile -delete \(\$data+\$master+\"_SELECTION_HANDLE_DATA.data\"\);\n");

  	 	button -label "Delete Deformation Data" -command ($delete_cmd);
		separator;

  	 	button -label "Close" -command ("deleteUI -window " + $window);
    setParent ..;
    showWindow $window;
}