global proc NewSaveFilewithIcon()
{
	string $sceneName = `file -q -sn`;
	string $buffer[];
	tokenize $sceneName "/\\" $buffer;
	//path
	string $folder = "";
	for ($i=0;$i<(size($buffer)-1);$i++)
	{
		$folder += $buffer[$i]+"/";
	}
	//file name
	string $tail = $buffer[size($buffer) - 1];
	tokenize $tail "." $buffer;
	$tail = $buffer[0];

	int $snapshotSize = 64, $snapshotOrnam = 0, $snapshotGrid = 0;
	if (`optionVar -exists "snapshotSize"`)
	{
		$snapshotSize = `optionVar -query "snapshotSize"`;
		$snapshotOrnam = `optionVar -query "snapshotOrnam"`;
		$snapshotGrid = `optionVar -query "snapshotGrid"`;
	}

	int $disp = 1;
	SnapshotIcon($folder,$tail,$snapshotSize,$snapshotOrnam, $snapshotGrid,$disp);
}

