
//See help files "automated submission" for an example how to use this script.


global proc RR_Commandsubmitter_SendScene(string $RR_DIR, string $RR_maya_version_to_use )
{
        $RR_result_print = eval(" RR_PrintSetPassValues56(0)");

	$RR_Commline= $RR_DIR + "Submitter_Batch.exe \""+ $RR_result_print[0]  + "\" -NoAutoSceneRead 0";
        $RR_Commline= $RR_Commline + " -ImageOutput \""    + $RR_result_print[9]  +"\"";
        $RR_Commline= $RR_Commline + " -ImageExtention \"" + $RR_result_print[10] +"\"";
        $RR_Commline= $RR_Commline + " -ImageDir \""       + $RR_result_print[7]  +"\"";
        $RR_Commline= $RR_Commline + " -ImageDirAdd \""    + $RR_result_print[8]  +"\"";
        $RR_Commline= $RR_Commline + " -SeqIn " + $RR_result_print[4] + " -SeqOut " + $RR_result_print[5] + " -SeqStep " + $RR_result_print[6] ;
	$RR_Commline= $RR_Commline + " -Setsoftware \"Maya,"+$RR_result_print[18]+",0,0,0," +$RR_maya_version_to_use+ "\"";

	print("EXECUTING " + $RR_Commline +  "\n");
        exec ($RR_Commline);


}


global proc CreateRenderScene( string $Scenename, string $RR_DIR, string $RR_maya_version_to_use )
{	
	print("Saving scene as " + $Scenename + "\n");
        file -rename $Scenename;
        file -s;
	print("Save done" + "\n");


      //Using the RR_PrintSetPassValues56 command does NOT require the plugin submitter to be installed.
	$PluginName = $RR_DIR + "render_settings/maya/RRender_" + substring($RR_maya_version_to_use ,1 , 1) + "_" +substring($RR_maya_version_to_use ,2, 2)+ ".mll";
	print ("loading plugin " + $PluginName + "\n");
	loadPlugin ($PluginName);
        RR_Commandsubmitter_SendScene($RR_DIR, $RR_maya_version_to_use);

}
