/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: анип╨Ц
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc shCenterFocus()
{
	if (`window -q -exists cfwin`)
		return;

	window -title "center focus" -resizeToFitChildren true cfwin;

		formLayout -numberOfDivisions 100 formLayout1;

			floatFieldGrp -label "Object height:" pref;
			button -label "start" -h 27 -command ("computerFocus") start;
			button -label "cancel"  -h 27 -command "deleteUI -window cfwin" cancel;
		
			formLayout -edit
				-attachForm	pref	"top"	5
				-attachForm	pref	"left"	5

				-attachForm	start	"left"	5
				-attachControl	start	"top"	5	pref
				-attachPosition	start     "right"	0       50
				
				-attachControl	  cancel	"left"		5	start
				-attachControl	  cancel	"top"	5	pref
				-attachPosition	  cancel      	"right"		0       100

			formLayout1;

	showWindow cfwin;
};

global proc computerFocus()
{
	float  $objheight;
	string $selected[];
	string $buf[];
	string $cam;
	string $obj;

	$objheight = `floatFieldGrp -query -v1 pref`;
	
	$selected = `ls -selection`;

	if(`size $selected` != 2){
		print "must select a cam and a obj\n";
		return;
	}

	$buf = `listRelatives -s $selected[0]`;
	if(`size $buf` && `nodeType $buf[0]` == "camera")
	{
		$cam = $selected[0];
		$obj = $selected[1];
	}else{
		$buf = `listRelatives -s $selected[1]`;
		if(`size $buf` && `nodeType $buf[0]` == "camera"){
			$cam = $selected[1];
			$obj = $selected[0];
		}
	}

	if(`size $cam` == 0){
		print "must select a camera.\n";
		return;
	}
	
	shCenterCam $cam $obj $objheight;
}