/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 廖尚恒
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc shelf_Bratz () {
	global string $gBuffStr;
	global string $gBuffStr0;
	global string $gBuffStr1;

	string $user = `getenv USERNAME`;
	$user = `tolower $user`;

/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Fix BlendShape Problem"
		-imageOverlayLabel "BSfix"
		-image1 (zwGetIcon("arrowDown.xpm"))
		-style "iconOnly"
		-command "source hbBlendShapeFix.mel; hbBlendShapeFix"
	;
*/
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "添加翅膀表达式" 
		-imageOverlayLabel "翅膀" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "slBrWingsCon" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "动画工具集"
		-imageOverlayLabel "AnTools"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source slAnimationToolsMainLayout.mel; slAnimationToolsMainLayout(\"Bratz\")"
	;
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "解决同一种车出现多次车轮表达式的情况"
		-imageOverlayLabel "车轮"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "brAnimWheelExpression" 
    ;
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "反向选择的角色的关键帧"
		-imageOverlayLabel "反向"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "slAnimMirrorKeys" 
    ;
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "更新Smooth节点"
		-imageOverlayLabel "UpSm"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zjSmoothbratz" 
    ;
 
/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Reposit Global"
		-imageOverlayLabel "Reposition"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source zxGlobalReposition.mel; zxGlobalReposition"
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "select Jade_021_Global and click the button"
		-imageOverlayLabel "Jade021"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source zxCorrectJade004021.mel; zxCorrectJade004021"
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "select Yasmin_001_Global and click the button"
		-imageOverlayLabel "Yasmin001"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source zxCorrectYasmin003001.mel; zxCorrectYasmin003001"
	;
 */

	/*shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "选择MASTER物体"
		-imageOverlayLabel "MASTER"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "string $g[] = `ls -type nurbsCurve \"*MASTER*\"`;select $g;pickWalk -d up;"
	;*/

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "重新建立所选物体的BlendShape节点"
		-imageOverlayLabel "BlendShape"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source zwRebuildBlendShapeSE.mel; zwRebuildBlendShape"
	;
		shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "根据点面数重命名当前场景shape节点"
		-imageOverlayLabel "ShapeMapping"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source czTXMapping.mel; czTXMapping"
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "初始化关键帧" 
		-imageOverlayLabel "Key" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source slEffectKeyInitialization.mel;slEffectKeyInitialization" 
	;
/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "把选择的参考物体变成引入物体"
		-imageOverlayLabel "R2I"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "czImportRefobj"
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动Key标准表情口型"
		-imageOverlayLabel "表情"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "slBrStandardPhoneme"
	;

		shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动分RGBA"
		-imageOverlayLabel "RGBA"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zjSepRGBA"
	;



	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动导入角色口型"
		-imageOverlayLabel "口型"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "slBrAutoloadlips"
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动K翅膀"
		-imageOverlayLabel "翅膀"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "slBrWings"
	;
*/


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "选择dvdbreeanai071003_MASTER 或者 dvdcymbelinei070003_MASTER ， 添加手镯"
		-imageOverlayLabel "手镯"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zxCharmbracelet"
	;

/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "选择Global，导入旧头发"
		-imageOverlayLabel "旧头发"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "old_hbHairImport"
	;


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "在没有set，但有T－pose的情况下，导入头发"
		-imageOverlayLabel "T-pose导头发"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source hbHairImport3 ; hbHairImport3"
	;
*/

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "直接点击工具，修改6个角色的手臂缩小，导入新权重"
		-imageOverlayLabel "elbow"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zxModifyElbow"
	;

/*
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "只能导入Lina的盘发，长发使用原来的工具导入"
		-imageOverlayLabel "Lina盘发"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "hbHairImport2"
	;


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "只能导入 dvdcloem001046 前面的留海"
		-imageOverlayLabel "cloem 留海"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "importdvdcloemfronttp"
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "导进发簪" 
		-imageOverlayLabel "发簪" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "importCymbelineClasp" 
	;
*/

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Add CTRL" 
		-imageOverlayLabel "AddCTRL" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command " zxAddCtrl" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "修复某些群众角色的贴图路径" 
		-imageOverlayLabel "Path" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwGirlMap" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "先选有问题的群组，再选新参考的群组" 
		-imageOverlayLabel "crow2crow" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"zxcrow2crow " 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "先选有问题的群组，再选新参考的群组" 
		-imageOverlayLabel "copyKey" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"copyKey " 
	;

/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动K眨眼" 
		-imageOverlayLabel "眨眼" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"slBrEyesBlink " 
	;
*/
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "删除毛囊" 
		-imageOverlayLabel "毛囊" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"hjfolldel" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "粗模高精模型显示转换" 
		-imageOverlayLabel "显示" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"hjlayoutset" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Bratz 头发导入工具集" 
		-imageOverlayLabel "Hair导入" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"source zxImportRefHairUI.mel ; zxImportRefHairUI" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Bratz 导出头发工具集" 
		-imageOverlayLabel "Hair导出" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command	"source zxExportHairUI.mel ; zxExportHairUI" 
	;
/* commented by huangzhongwei@idmt.org.cn, 20080724
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "检查角色是否是最新版本" 
		-imageOverlayLabel "版本" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwCheckVersion" 
	;
*/
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "角色快捷控制" 
		-imageOverlayLabel "操控" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "ml_selector" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动key帧新程序" 
		-imageOverlayLabel "AuKey" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "hjKeyAuto" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "先选择物体再选择Loctor" 
		-imageOverlayLabel "LocVx" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source slLocatorToVtx.mel;slLocatorToVtx" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "补帧工具" 
		-imageOverlayLabel "FF" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "proc  hjcomfixer()\r\n{\r\nstring $command=\"start \\\\\\\\File-cluster\\\\GDC\\\\Resource\\\\Support\\\\bin\\\\EvenFixer.exe\";\r\nstring $syscommand=`system \t($command)`;\r\n}\r\nhjcomfixer;" 
        -actionIsSubstitute 0
		;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "删除transformGeometry节点" 
		-imageOverlayLabel "DelTG" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "string $tg[] = `ls -type transformGeometry`; for ($item in $tg)	deleteIfNotReferenced $item;" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "设置syCloth 的cacheName" 
		-imageOverlayLabel "syCloth" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwSetSyClothCacheName" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "blendShape_Manager" 
		-imageOverlayLabel "BSM" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "blendShape_Manager091" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "移形换影。先选低模树MASTER，再加选高模树MASTER，应用本按钮以后，两者位置会对调，低模树把动画剪切给高模树" 
		-imageOverlayLabel "树" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwToggleP092708ornamentalmall" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "约束" 
		-imageOverlayLabel "约束" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwDynamicSwitch" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "先选旧车的MASTER，再加新车的MASTER。应用本按钮以后，请手动删掉新车" 
		-imageOverlayLabel "车灯" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "zwRelpaceP008611electrickiddiecar" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "DVD7 角色衣服设置" 
		-imageOverlayLabel "Bratz Cloth" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "hjClothlist" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "沙漠脚印" 
		-imageOverlayLabel "沙漠脚印" 
		-image1 "footPrint.xpm" 
		-style "iconOnly" 
		-command "source zzjFootprintCreator.mel;zzjCreateBumpNode" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "设置Res" 
		-imageOverlayLabel "设置Res" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source hqOverrideRes.mel;hqOverrideRes" 
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Fur路径" 
		-imageOverlayLabel "Fur路径" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly" 
		-command "source changeFurImagePath.mel;changeFurImagePath" 
;
}