global proc shelf_WinxClubII()
{
python("import maya.cmds as cmds");
python("import maya.mel as mel");
//前期
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\pre1_wxII.xpm"
		-imageOverlayLabel "       前"
		-label "前期工具集"
		-command "wxIIShelfChanges \"Pre\""
	;

//设置
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\set1_wxII.xpm"
		-imageOverlayLabel "       设"
		-label "设置工具集"
		-command "wxIIShelfChanges \"Set\""
	;

//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\ani1_wxII.xpm"
		-imageOverlayLabel "       动画"
		-label "动画工具集"
		-command "wxIIShelfChanges \"Ani\""
	;

//特效
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\eff1_wxII.xpm"
		-imageOverlayLabel "       特效"
		-label "特效工具集"
		-command "wxIIShelfChanges \"Eff\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\rnd1_wxII.xpm"
		-imageOverlayLabel "       渲染"
		-label "渲染工具集"
		-command "wxIIShelfChanges \"Rnd\""
	;


  //zzj    empty**************************
  //隐藏面板
	shelfButton -width 34 -height 34 -vis 1
//	-i1 "\wxII\\it.XPM"
	 -c "zzjshelf()";



  //zzj               Pre**************************

		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "角色6套灯光"	-iol "6套灯" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_sixLightsForTx.mel\";sixLightsForTx;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "角色旋转序列"	-iol "序列" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_loopChrForTx.mel\";loopChrForTx;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "道具渲染"	-iol "       渲" -i1 "\wxII\\pre_propRender_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_loopPropFortx.mel\";loopPropFortx;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "删除道具Key帧"	-iol "       删" -i1 "\wxII\\pre_propRender_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_deleteLoopProp.mel\";deleteLoopPropFortx;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "前期优化面板"	-iol "面板" -i1 "\wxII\\pre_panel_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_optimize.mel\";wxIIOptimize4PreUI;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "替换clearCoat节点"	-iol "clear" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_ClearCoatInstance.mel\";wxII_ClearCoatInstance;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "生成TXRNDC文件"	-iol "txrndC" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/zjCreateCacheFile_4WinxII.mel\";zjCreateCacheFile_4WinxII;"
			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "自动生成finishing avi"	-iol "A avi" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwBatchImportFinishing.mel; zwBatchImportFinishing;";




  //zzj               Set**************************

		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Reference 开关"	-iol "Ref开关" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_switchReference;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决关闭TFM角色后不能正常选择物体的问题(点击即可)"	-iol "SEL" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "slRepairTFMSelection;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "创建Shot Content"	-iol "       SC" -i1 "\wxII\\gen_createShotContent.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_commonTools(1);"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Copy animation HRS cache"	-iol "Cache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_copyHRSCache.mel\";wxIICopyHRSCache(\"animation\");"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择非解算物体"	-iol "非解算" -i1 "\wxII\\set_noSim2_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/set_wxII_simToSetInfo.mel\";simulationToSetupInfo;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导动画"	-iol "导动画" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/set_wxII_animClip.mel\";winxII_testAnimClip_IorOUI;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修改\"cache/贴图\"路径"	-iol "       改" -i1 "\wxII\\set_changePath1_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/set_wxII_changePath.mel\";wxII_SetChangePathUI;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择工具"	-iol "       选" -i1 "\wxII\\gen_selectTool_wxII4.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_selectTool.mel\";wxII_GenSelectToolUI;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "材质记录"	-iol "       材" -i1 "\wxII\\set_zzjReturnMatList_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjReturnMatList.mel\";"
			;
			popupMenu -button 1 WxSet1;
//				menuItem -subMenu true -label "CHR" 	-parent WxRender WxRenderChr;
					menuItem -label "记录场景中的材质" 			-parent WxSet1 	-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjReturnMatList.mel\";zzjGetMatList()";
					menuItem -label "赋予场景中的材质" 			-parent WxSet1 	-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjReturnMatList.mel\";zzjSetMatList()";
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "恢复材质——测试版本"  -iol "       回" -i1 "\wxII\\set_zzjReturnMatList_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjMaterialsComeBack.mel\";zzjMaterialsComeBack"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择创建缓存"  -iol "py_createCacheChoice" -i1 "\wxII\\createCacheInMaya.xpm"	-style "iconOnly"
			-c "py_createCacheChoice"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Finishing Tools"  -iol "py_finishingTools" -i1 "\wxII\\finishingTools.xpm"	-style "iconOnly"
			-c "py_finishingTools"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修复回到起始帧错误问题"  -iol "起始" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/eff_wxII_startFrame.mel\";wxIIEffStartFrameError(\"set\");"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修复kiko眼球移动数值"  -iol "kiko眼" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_kikoEyes;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "删除PolyNormalVertex节点" -iol "PNV" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry/slDelHistory.mel\";slDelHistory(\"polyNormalPerVertex\");"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "重命名摄像机" -iol "重命名" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/set_wxII_finishingRenameCam.mel\";finishingRenameCam;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解锁选择物体" -iol "解锁" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_unlockSL;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Winx - 提交网络生成cache"  -iol "Cache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwBatch.mel; zwBatch \"Winx - 提交网络生成cache\" \"musterCheckinForWinxIICacheProc\";"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "自动选中没key过的mainCtrl和move，在950帧key一下"  -iol "Key" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_keyMainCtrlAtFirstFrame;"
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "bake选中物体的动画到locator上"  -iol "Bake" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"zzjUtilityTools\";zzjUtilityTools \"bakeAnim\""
			;
		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "找到因finishing更新cache而丢失的cache"	-iol "Lost C" -i1 "pythonFamily.xpm"	-style "iconOnly"
			-c "python(\"import IDMT.WinxClubII.findLostCache as fLC\");python(\"reload(fLC)\");python(\"fLC.fLC()\")"
			;

		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "ZDP" -iol "共用Cache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "zwOptimizeGeoCache;"
			;
  //zzj               Ani**************************
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决关闭TFM角色后不能正常选择物体的问题(点击即可)"	-iol "SEL" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "slRepairTFMSelection;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "裙子跳转"	-iol "裙子" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/ani_wxII_ani.mel\";wxIIAniSkirtDump;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "取景"	-iol "取景" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "wn2camclip;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "去除取景"	-iol "去景" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "wn2Remcamclip"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Bake Simulation"	-iol "Bake" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "czKeyBake;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "动画面板"	-iol "" -i1 "AnimPanel.xpm"	-style "iconOnly"
			-c "ddAnimationPanelUI"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择角色之间导动画"	-iol "Copy" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "buAnimCopy"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Zoom"	-iol "Zoom" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "zoomerate"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Import Reference"	-iol "Ref" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "kcImportReference"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "动画曲线编辑器"	-iol "GE" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "GraphEditor"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "动作库"	-iol "       库" -i1 "\wxII\\ani_library_wxII.xpm"	-style "iconOnly"
			-c "zwAnimLib \"WinxClubII\";"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "眼球透明以及贴图问题"	-iol "眼球" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/ani_wxII_ani.mel\";wxIIAniEyeFade;wxIIAniEyeFile;"
			;
//		shelfButton -docTag "Ani"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "加载anzovinRigNodes插件"	-iol "临时" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "loadPlugin \"//file-cluster/GDC/Resource/Support/Maya/8.5/modules/anzovin/plug-ins/anzovinRigNodes.mll\""
//			ani_WxIIShelfButton12;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "改正模型黑面"	-iol "黑面" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/ani_wxII_ani.mel\";wxIIAniBlackFace;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修改眼球分辨率"	-iol "低眼球" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/ani_wxII_ani.mel\";zzjLowHardwareRes;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "关闭/开启场景中所有角色的TFM控制"	-iol "TFM" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry/slAnimTFMOnOff.mel\";slAnimTFMOnOff;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择角色mainCtrl自动Key过渡帧"	-iol "过渡帧" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/wxIITSMCtrlFromSet.mel\";wxIITSMCtrlFromSet;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "找回丢失的动画(选择角色的所有控制器点击)"	-iol "Lost" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "yyReconnectAnimNodeWrapper;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "对选择物体Smooth二级，用于检查穿插"	-iol "Smooth" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwCheckSmooth.mel; zwCheckSmooth;";
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "取消Smooth"	-iol "反Smooth" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwCheckSmooth.mel; zwCheckSmoothDel;";
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解锁选择物体" -iol "解锁" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_unlockSL;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "使用$MC作为路径" -iol "变量" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "wxIIAniChangePathConfirm;"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "自动选中没key过的mainCtrl和move，在950帧key一下"  -iol "Key" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_keyMainCtrlAtFirstFrame;"
			;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "关闭解算"  -iol "关解" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"zwWinxDisableDyn.mel\"; zwWinxDisableDyn;"
			;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "找丢失的动画曲线"	-iol "找曲线" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly" -sourceType "python"
			-c "import IDMT.Pluto.FindLostAnimCurve as FLAC\nreload(FLAC)\nFLAC.UI()"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Easy Animation"	-iol "EA" -i1 "pythonFamily.xpm"	-style "iconOnly" -sourceType "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyEasyAnimation2.py')"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "KLR Parenting Tools"	-iol "KLR" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "klr_parentingForAnimatorsUI;";

		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修改贴图路径"	-iol "M:" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source kcModifyMapPathGUI.mel; kcModifyMapPath \".*/sourceimages/\" \"${MC_roma}/sourceimages/\" 1;";



  //zzj               Eff**************************
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决关闭TFM角色后不能正常选择物体的问题(点击即可)"	-iol "SEL" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "slRepairTFMSelection;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "沙漠脚印"	-iol "" -i1 "\wxII\\eff_footPrint1_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjFootprintCreator.mel\";zzjFootprintCreator;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择非解算物体"	-iol "非解算" -i1 "\wxII\\set_noSim2_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/set_wxII_simToSetInfo.mel\";simulationToSetupInfo;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "特效检查工具"  -iol "检查" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/xy/wxII_effTools.mel\";wxII_effToolsUI"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "跟据角色头部的运动为头发控制器添加关键帧"  -iol "" -i1 "//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zb/procIcon_keyHairConTool.bmp"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zb/zb_hairConKeyTool.mel\";zb_hairConKeyTool"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "nCloth 工具"  -iol "" -i1 "//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zb/toolsIcon_nCloth.bmp"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zb/zb_nClothTool_v002.mel\";zb_nClothToolUI"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "创建碰撞体"  -iol "碰撞体" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zwc/HS_Cosntraint/zwcHairsConstraint.mel\";zwcHairsConstraint;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "ballDress"  -iol "大裙子" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Projects/WinxClubII/WinxClubII_Scratch/effect/MEL/zwc/Balldress/zwcBallDressImport.mel\";zwcBallDressImport;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "创建渲染层"  -iol "建层" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/eff_wxII_createRenderLayer.mel\";wxIIEffCreateRenderLayerUI;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修复回到起始帧错误问题"  -iol "起始" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/eff_wxII_startFrame.mel\";wxIIEffStartFrameError(\"eff\");"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "MayaMan渲染Shave加载预置参数及脚本"  -iol "Shave渲染" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "eff_wxII_MShavePsets"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Filter Hair System"  -iol "fHair" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "xy_hairtool;"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "MayaMan渲染毛发设置属性"  -iol "MayaMan渲染" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "eff_wxII_WinxMayamanHF"
			;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "批量playblast"  -iol "MP" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwBatch.mel; zwBatch \"Winx - Playblast(DYN)\" \"zwBatchPlayblastDYN\";"
			;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "恢复材质——解决动画文件"  -iol "       回" -i1 "\wxII\\set_zzjReturnMatList_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjMaterialsComeBack.mel\";zzjMaterialOptimize_LightLinker"
			;
		//shelfButton -docTag "Eff"
		//	-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "客户发来的PRE - CACHED FLUID SET DRESSING"  -iol "RBW-F" -i1 "pythonFamily.xpm"	-style "iconOnly"
		//	-c "python(\"import IDMT.WinxClubII.fluidRetimer_85 as fRt\");python(\"reload(fRt)\");python(\"fRt.fluidRetimer()\")"
		//	;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "fluidAutoResize"  -iol "fluidResize" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"co_fluidAutoResize_UI_8.5.mel\";co_fluidAutoResizeUI";
			;

			shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "importFluidFile"  -iol "importFluidFile" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "py_winxCopyFile";

			shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "setFluidCache"  -iol "setFluidCache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuImportFluidCache.mel;yuImportCityFluidCache();";

			shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "importPartFile"  -iol "importPartFile" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuPythonToMel.mel;yuWinxCopyFile();";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "fluid时间偏移"  -iol "偏移" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwDiskCacheOffset.mel; zwDiskCacheOffset;";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "关闭所有fluid的Self Shadow"  -iol "关Self Shadow" -i1 "//file-cluster/GDC/Resource/Support/Maya/icons/false.xpm"	-style "iconOnly"
			-c "zwSetIntAttrAll \"fluidShape\" \"selfShadowing\" 0";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "打开所有fluid的Self Shadow"  -iol "开Self Shadow" -i1 "//file-cluster/GDC/Resource/Support/Maya/icons/true.xpm"	-style "iconOnly"
			-c "zwSetIntAttrAll \"fluidShape\" \"selfShadowing\" 1";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导入悬崖fog"  -iol "导入悬崖fog" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuPythonToMel.mel;yuWinxCopyCliffFluidFile()";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "断开不是雾的材质链接"  -iol "断雾" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxDisconnectFluidShader.mel\"; zwWinxDisconnectFluidShader;";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导入地面fog"  -iol "导入地面fog" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuPythonToMel.mel;yuWinxCopyGroundFluidFile()";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择Fluid，缩放其Texture Scale"  -iol "雾精" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwFluidTextureScale.mel\"; zwFluidTextureScale;";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "复制Fluid工具"  -iol "复制Fluid工具" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuPythonToMel.mel;yuCopyFluidTool()";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导入SquareFog"  -iol "导入SquareFog" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source yuPythonToMel.mel;yuWinxSquareFluidFile()";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "左右"  -iol "左右" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/LeftRightEyerRenderLayerConvert.mel\";LeftRightEyerRenderLayerConvertControl;";

  //zzj               Rnd**************************



		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Reference 开关"	-iol "Ref开关" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_switchReference;"
			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决关闭TFM角色后不能正常选择物体的问题(点击即可)"	-iol "SEL" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "slRepairTFMSelection;"
			;


		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "lighting工具集2"	-iol "工具2" -i1 "pythonFamily.xpm"	-style "iconOnly"
			-c "python(\"import IDMT.WinxClubII.lightingUI as lUI\");python(\"reload(lUI)\");python(\"lUI.lUI()\")"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "lighting工具集3"	-iol "工具3" -i1 "pythonFamily.xpm"	-style "iconOnly" -sourceType "python"
			-c "import IDMT.WinxClubII.lightingUI_III as lUI_III\nreload(lUI_III)\nlUI_III.lUI()"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "右眼"	-iol "右眼" -i1 "pythonFamily.xpm"	-style "iconOnly"
			;
		popupMenu -button 1 Buantime22;
		menuItem  -parent Buantime22 -l "转右眼工具" -c "yyRightEyeSwith" ;
		menuItem  -parent Buantime22 -l "本地“补”不改参数" -c "localFix2" ;
		menuItem  -parent Buantime22 -l "网渲“补”不改参数" -c "netFix2" ;

//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Copy finishing HRS cache"	-iol "Cache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_copyHRSCache.mel\";wxIICopyHRSCache(\"finishing\");"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "save Lighting"	-iol "存文件" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "py_saveLighting();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导入渲染用摄像机"	-iol "CAM" -i1 "view.xpm"	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_RenderTools.mel\";wxII_ImportRenderCam();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "set for rendering"	-iol "建层" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "py_autoSetForRendering();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "IDPass"	-iol "       ID" -i1 "\wxII\\rnd_idPass_wxII.xpm"	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjIdPassInfo.mel\";zzjIdPassInfo;"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "设置smooth"	-iol "Smooth" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "zjTDSmooth"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "贴图尺寸转换"	-iol "       剪" -i1 "\wxII\\rnd._toogleMaps.xpm"	-style "iconOnly"
//			-c "source zwToggleMaps.mel; zwToggleMaps \"WinxClubII\";"
//			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "前期优化面板"	-iol "面板" -i1 "\wxII\\pre_panel_wxII.xpm"	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_optimize.mel\";wxIIOptimize4PreUI;"
			;


//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "各种补丁"	-iol "补" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c ""
//			;
//			popupMenu -button 1 WxRnd1;
//					menuItem -label "Shave补" 			-parent WxRnd1
//						-c "eff_wxII_MShavePsets";
//					menuItem -label "本地补" 			-parent WxRnd1
//						-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_FixBeforeRender.mel\";wxII_FixBeforeRender(\"project\");";
//					menuItem -label "网渲补" 			-parent WxRnd1
//						-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_FixBeforeRender.mel\";wxII_FixBeforeRender(\"online\");";
//


//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "关闭灯光的漫反射"	-iol "关漫反射" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_RenderTools.mel\";wxII_TurnOffEmitDiffuse();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "摄像机的Far Clip Plane"	-iol "Far Clip" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_RenderTools.mel\";wxII_SetFarClipOfCamera();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导入Kiko灯"	-iol "Kiko" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_RenderTools.mel\";importKikoLight();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "找到因finishing更新cache而丢失的材质"	-iol "Lost S" -i1 "pythonFamily.xpm"	-style "iconOnly"
//			-c "python(\"import IDMT.WinxClubII.findLostShader as fLS\");python(\"reload(fLS)\");python(\"fLS.fLS()\")"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "找到因finishing更新cache而丢失的cache"	-iol "Lost C" -i1 "pythonFamily.xpm"	-style "iconOnly"
//			-c "python(\"import IDMT.WinxClubII.findLostCache as fLC\");python(\"reload(fLC)\");python(\"fLC.fLC(type=1)\")"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "lighting工具集"	-iol "工具" -i1 "pythonFamily.xpm"	-style "iconOnly"
//			-c "python(\"execfile(\\\"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_lightingTools_UI.py\\\")\");python(\"wxII_LightingToolsUI()\")"
//			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "赋给白模材质 / 恢复原来材质"	-iol "白模" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly";
			popupMenu -button 1;
				menuItem -label "赋给白模材质" -command "source zwBackupSurfaceShader.mel; zwBackupSurfaceShader false;";
				menuItem -label "恢复原来材质" -command "source zwBackupSurfaceShader.mel; zwBackupSurfaceShader true;";
			popupMenu -button 3;
				menuItem -label "赋给白模材质" -command "source zwBackupSurfaceShader.mel; zwBackupSurfaceShader false;";
				menuItem -label "恢复原来材质" -command "source zwBackupSurfaceShader.mel; zwBackupSurfaceShader true;";
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "删除物体的点位移" -iol "点位移" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_removeVTXtranslate();"
			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "共用Cache节点" -iol "共用Cache" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "zwOptimizeGeoCache;"
//			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导出、导入灯的位置" -iol "LightIO" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source zwKeyLightIO.mel; zwKeyLightIO;";

//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "删除所有MM额外层"	-iol "删MM层" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/rnd_wxII_RenderTools.mel\";wxII_DeleteMMExtraChannels();"
//			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "test"	-iol "" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_wxII_commonTools.mel\";wxII_selectReferenceByObj();"
//			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择一盏灯作为模板，应用本按钮，会复制到每个灯罩，模板等修改以后，需要重新点本按钮"	-iol "灯泡" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"zwWinxLight.mel\"; zwWinxLight;"
			;
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "删除MayaManNugget、MayaManNuggetDeleteScript"	-iol "删Nugget" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
//			-c "source zwWinxDelNugget.mel; zwWinxDelNugget;"
//			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决Fur闪动" -iol "Fur闪" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "ysMarionFur"
			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决Shave渲染不出来的问题哦" -iol "Shave渲" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "wx_ysFixShaveRendering"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallBoldLabelFont"	-l "断开、恢复eraklion_avram_biggerBlocks的displacementShader" -iol "Blocks" -i1 "RENDER_DISPLACEMENTSHADER.XPM"	-style "iconOnly";
			popupMenu -button 1;
				menuItem -label "断开" -command "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxDisconnectDisplacementShader.mel\"; zwWinxDisconnectDisplacementShader false;";
				menuItem -label "恢复" -command "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxDisconnectDisplacementShader.mel\"; zwWinxDisconnectDisplacementShader true;";
			popupMenu -button 3;
				menuItem -label "断开" -command "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxDisconnectDisplacementShader.mel\"; zwWinxDisconnectDisplacementShader false;";
				menuItem -label "恢复" -command "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxDisconnectDisplacementShader.mel\"; zwWinxDisconnectDisplacementShader true;";

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "给小组长检查未Checkin的lighting文件" -iol "查文件" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwCheckLighting.mel\"; zwCheckLighting;"
			;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "解决马鞍smooth后，装饰物旋转错误问题" -iol "peg转" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"  -sourceType "python"
			-c "import IDMT.WinxClubII.wxII_RenderTools as wIIRT\nreload(wIIRT)\nwIIRT.pegSmoothProblem()"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "Mayaman渲染树叶Alpha通道问题，需要手动选择透明贴图的file节点" -iol "树叶Alpha" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zwWinxOutTransparency.mel\";zwWinxOutTransparency;"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "设置飞船场景的置换强度，需要手动选择置换节点" -iol "船置换" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "ysSetDisplacementShdr;"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "ZDP" -iol "zdp" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Groups/Production/Modeling/个人目录/孙望/sw_script/edo_zdpAutoCreate.mel\";edo_zdpAutoCreate;"
			;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修复客户右眼相机与IDMT左眼不匹配问题" -iol "修右眼相机" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/ncStereoCamSolve.mel \";"
			;  // niuchuang

wxIIShelfChanges `optionVar -query "wxIIShelfSelected"`;
}



global proc wxIIShelfChanges(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray WinxII`;
	int $size = size($childArray);

	int $index = 7;

	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible 1 $childArray[$i];
				$index ++;
				shelfLayout -edit -position $childArray[$i] $index WinxII;
			}
			else
			{
				shelfButton -edit -visible 0 $childArray[$i];
			}
		}
	}
	optionVar -stringValue "wxIIShelfSelected" $steps;
}


//zzj     虞丰盛工具 ▼▼▼▼▼▼▼▼▼
global proc py_createCache()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yuCreateCache.py\")");
	python("yuCreateCache()");
}
//global proc py_importCache()
//{
//	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yuImportCache.py\")");
//	python("yuImportCache()");
//}

global proc py_createCacheChoice()
{
	python("from IDMT.yuCreateCacheInMaya import *");
	python("yuCreateCacheUI()");
}

global proc wxIIShelfSourceZwSetImageFilePrefix()
{
	source zwSetImageFilePrefix.mel;
	zwSetImageFilePrefix;
}
global proc py_finishingTools()
{
	python("from IDMT.yuFinishingTools import *");
	python("finishingToolsUI()");
}


global proc yyReconnectAnimNodeWrapper()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyReconnectAnimNode.py\")");
}
//zzj     虞丰盛工具▲▲▲▲▲▲▲▲▲


global proc wxIIAniChangePathConfirm()
{
string $confirm=`confirmDialog -message "Are you sure?" -button "Yes" -button "No" -defaultButton "Yes"
    -cancelButton "No" -dismissString "No"`;
    if ($confirm=="Yes")
    {
    	zwWinxClubIIFix;
    	print "Done";
    	}

}

global proc py_winxCopyFile()
{
	python("from IDMT.yuWinxCopyFile import *");
	python("winxCopyFluidFile()");
	source yuImportFluidCache.mel;yuImportCityFluidCache();
	//setAttr "defaultRenderGlobals.preMel" -type "string" "source yuImportFluidCache.mel;yuImportFluidCache();";

}

global proc zzjshelf()
{
	string $userName=`getenv "USERNAME"`;
	if ($userName=="zhaozhongjie")
	{
		evalDeferred("loadNewShelf \"//file-cluster/GDC/Resource/Support/Maya/scripts/shelf_zzj.mel\"");
	}
}

global proc ysMarionFur()
{
	python("import IDMT.WinxClubII.ysMarionFur as ysMarionFur");
	python("reload(ysMarionFur)");
	python("ysMarionFur.ysMarionFur()");
}

global proc wx_ysFixShaveRendering()
{
	python("import IDMT.WinxClubII.wx_ysFixShaveRendering as fixshaveRendering");
	python("reload(fixshaveRendering)");
	python("fixshaveRendering.fixLostTexture()");
}

global proc ysSetDisplacementShdr()
{
	python("import IDMT.WinxClubII.ysSetDisplacementShdr as ysSetDisplacement");
	python("reload(ysSetDisplacement)");
	python("ysSetDisplacement.ysScaleAlphaGainUI()");
}

global proc yyRightEyeSwith()
{
	python("execfile('//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyWinx2LightingExtra.py')");
	python("Winx2L2RCamWrapper()");
}

global proc localFix2()
{
	python("execfile('//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyWinx2LightingExtra.py')");
	python("localFix2()");
}

global proc netFix2()
{
	python("execfile('//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyWinx2LightingExtra.py')");
	python("netFix2()");
}

global proc yyEasyAnimation()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/yyScripts/yyEasyAnimation.py\")");
}