global proc shelf_LORDoftheRINGS()
{
python("import maya.cmds as cmds");
python("import maya.mel as mel");
//前期
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\pre1_wxII.xpm"
		-imageOverlayLabel "       前"
		-label "前期工具集"
		-command "lrShelfChanges \"Pre\""
	;

//设置
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\set1_wxII.xpm"
		-imageOverlayLabel "       设"
		-label "设置工具集"
		-command "lrShelfChanges \"Set\""
	;

//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\ani1_wxII.xpm"
		-imageOverlayLabel "       动画"
		-label "动画工具集"
		-command "lrShelfChanges \"Ani\""
	;

//特效
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\eff1_wxII.xpm"
		-imageOverlayLabel "       特效"
		-label "特效工具集"
		-command "lrShelfChanges \"Eff\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "wxII\\rnd1_wxII.xpm"
		-imageOverlayLabel "       渲染"
		-label "渲染工具集"
		-command "lrShelfChanges \"Rnd\""
	;


  //zzj    empty**************************
  //隐藏面板
	shelfButton -width 34 -height 34 -vis 1
//	-i1 "\wxII\\it.XPM"
	 -c "";



  //zzj               Pre**************************

//		shelfButton -docTag "Pre"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "前期优化面板"	-iol "面板" -i1 "\wxII\\pre_panel_wxII.xpm"	-style "iconOnly"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_optimize.mel\";wxIIOptimize4PreUI;"
//			;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "设置说明文档"	-iol "Help" -i1 "commandButton.xpm"	-style "iconOnly"
			-c ";"
			;


  //zzj               Set**************************

		shelfButton -docTag "Set"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "bake选中物体的动画到locator上"  -iol "Bake" -i1 (zwGetIcon("commandButton.xpm"))	-style "iconOnly"
			-c ""
			;


  //zzj               Ani**************************
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "导动画工具"	-iol "导" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "slAnimExportImportForSetMainLayout"
			;		


  //zzj               Eff**************************


//		shelfButton -docTag "Eff"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "导入SquareFog"  -iol "导入SquareFog" -i1 "commandButton.xpm"	-style "iconOnly"
//			-c "source yuPythonToMel.mel;yuWinxSquareFluidFile()";

		shelfButton -docTag "Eff"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "选择地面+移动物体"  -iol "痕迹" -i1 "commandButton.png"	-style "iconOnly"
			-c "source \"zwNinjagoTrail.mel\"; zwNinjagoTrail;";

  //zzj               Rnd**************************

				
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "群组粒子精简"	-iol "群精简" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "source \"//file-cluster/GDC/Projects/Ninjago/Ninjago_scratch/Crowd/syx_particle_vis.mel\";"
			;			
			
//		shelfButton -docTag "Rnd"
//			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "上传cache"	-iol "cache" -i1 "commandButton.xpm"	-style "iconOnly" 
//			-command "python (\"try:\\n\\treload(idmt.maya.cache)\\nexcept:\\n\\timport idmt.maya.cache\\nidmt.maya.cache.UploadCacheFileForNinjago()\")";

lrShelfChanges `optionVar -query "lrIIShelfSelected"`;
}


global proc lrShelfChanges(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray LORDoftheRINGS`;
	int $size = size($childArray);

	int $index = 7;

	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible 1 $childArray[$i];
				$index ++;
				shelfLayout -edit -position $childArray[$i] $index LORDoftheRINGS;
			}
			else
			{
				shelfButton -edit -visible 0 $childArray[$i];
			}
		}
	}
	optionVar -stringValue "lrIIShelfSelected" $steps;
}

global proc ysTSRendering()
{
	python("import sys");
	python("sys.path.append(\"//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/TTMS\")");
	python("import BD_ysRenderUI as bdrnUI");
	python("reload(bdrnUI)");
	python("bdrnUI.BD_ysRenderUI()");
}

global proc RR_attachCarOnFround()
{
	python("execfile('//file-cluster/GDC/Resource/Support/Maya/extra/Rigging_Simulation/python/edo/project/ninjago/edo_allCarSnap.py')");
	return;
	python("import sys");
	python("sys.path.append(\"//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/RR\")");
	python("import RR_ysAniTools as ANT");
	python("reload(ANT)");
	python("ANT.attachCarOnGround()");
}



global proc nj_Rnd_WireFrameDisplayInstancer(string $type)
{

	
	string $instancers[]=`ls -type instancer`;
	for ($ins in $instancers)
	{
		if ($type == "h") setAttr ($ins+".levelOfDetail") 0;
		if ($type == "l") setAttr ($ins+".levelOfDetail") 1;
		if ($type == "b") setAttr ($ins+".levelOfDetail") 2;
	}
}

//global proc createGeoCacheSet()
//{
//	if (`objExists "GEO_CACHE_SET"`)
//	{
//	    delete GEO_CACHE_SET;
//	}
//	sets -name "GEO_CACHE_SET";
//	select -r -ne "GEO_CACHE_SET";	
//}



global proc nj_Ani_bakeSelectGeo()
{
//		隐藏modelPanel
		string $scripts = "";
		string $modelPanels[] = `getPanel -visiblePanels`;
		for ($modelPanel in $modelPanels)
		{
			if (`getPanel -typeOf $modelPanel` == "modelPanel")
			{
				if (!`isolateSelect -query -state $modelPanel`);
				{
					isolateSelect -state true $modelPanel;
					$scripts += "isolateSelect -state false \"" + $modelPanel + "\";\n";
				}
			}
		}
		
		source cyBakeClothMain.mel;
		cyBakeCloth;	


	//		恢复显示	
		if ($scripts != "")
		{
			eval $scripts;
		}
}