/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc shelf_previs () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;

	string $ext = ".xpm";
	if(`about -nt`){
		$ext = ".bmp";
	}

    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "previs HUD" 
	-image1 ("hud"+$ext)
        -style "iconOnly" 
        -command "source \"previs_hud.mel\";\r" 
    ;
    string $dev_path = `getenv "DEV_PATH"`;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "235 mask" 
	-image1 ("235m"+$ext)
        -style "iconOnly" 
        -command ("source \"mask.mel\";\rcreateMask(\"" + $dev_path + "/Maya/Icons/mask235.tga\")\r") 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "235 reticle"
	-image1 ("235r"+$ext) 
        -style "iconOnly" 
        -command ("source \"mask.mel\";\rcreateMask(\"" + $dev_path + "/Maya/Icons/reticle235.tga\")\r")
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "185 mask"
	-image1 ("185m"+$ext) 
        -style "iconOnly" 
        -command ("source \"mask.mel\";\rcreateMask(\"" + $dev_path + "/Maya/Icons/mask185.tga\")\r")
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "185 reticle" 
	-image1 ("185r"+$ext)
        -style "iconOnly" 
        -command ("source \"mask.mel\";\rcreateMask(\"" + $dev_path + "/Maya/Icons/reticle185.tga\")\r")
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "silhouette"
	-image1 ("silouette"+$ext) 
        -style "iconOnly" 
        -command "source silhouette.mel;\rsilhouette;\r" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "thirds overlay" 
	-image1 ("thirds"+$ext)
        -style "iconOnly" 
        -command ("source \"mask.mel\";\rcreateMask(\"" + $dev_path + "/Maya/Icons/thirds.tga\")\r")
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "flip ortho camera" 
	-image1 ("flip"+$ext)
        -style "iconOnly" 
        -command " source \"flipcam.mel\";\rflipCam;\r" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "create zoom camera;\r" 
	-image1 ("zoom"+$ext)
        -style "iconOnly" 
        -command "source \"zoomCamera.mel\";\rzoomCamera;\r" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "model clipping planes\r" 
        -image1 ("clip"+$ext) 
        -style "iconOnly" 
        -command "source \"modelClipPlanes.mel\";\rmodelClipPlanes();\r" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "create camera dummy" 
        -image1 ("dummy"+$ext) 
        -style "iconOnly" 
        -command "source \"cameraDummy.mel\";\rcameraDummy;\r" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "create object camera"  
        -image1 ("object"+$ext) 
        -style "iconOnly" 
        -command "source \"objectCam.mel\";\rmakeObjectCam;\r"
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "create floating camera view"  
        -image1 ("window"+$ext) 
        -style "iconOnly" 
        -command "source \"windowCamera.mel\";\rwindowCamera;\r"
    ;


} 
