global proc shelf_XFrog4 () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Load XFrog" 
        -image1 "redo.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==0) loadPlugin \"Xfrog4Maya\";" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Close XFrog" 
        -image1 "undo.xpm" 
        -style "iconOnly" 
        -command "file -f -new;\r\nunloadPlugin \"Xfrog4Maya\"; if (`window -exists \"XfrogVisor\"`) deleteUI -window \"XfrogVisor\";" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "CurveNurbs" 
        -image1 "curvature.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreateCurveNurbs;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Branch" 
        -image1 "branch.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreateBranch;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Hydra" 
        -image1 "hydra.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreateHydra;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Phyllotaxis" 
        -image1 "phyllotaxis.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreatePhyllotaxis;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Variation" 
        -image1 "variation.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreateVariation;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Tropism" 
        -image1 "tropism.xpm" 
        -style "iconOnly" 
        -command "if(`pluginInfo -q -l Xfrog4Maya`==1) XFCreateTropism;" 
    ;
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -label "Visor" 
        -image1 "hypergraph.xpm" 
        -style "iconOnly" 
        -command "source XFVisor.mel;" 
    ;

} 
