global proc shelf_DOD2()
{
/*
	boldLabelFont
	smallBoldLabelFont
	tinyBoldLabelFont
	plainLabelFont
	smallPlainLabelFont
	obliqueLabelFont
	smallObliqueLabelFont
	fixedWidthFont
	smallFixedWidthFont
*/

//前期
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "前期"
		-command "do2ShelfChange \"Pre\""
	;

//设置
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "设置"
		-command "do2ShelfChange \"Set\""
	;

//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "动画"
		-command "do2ShelfChange \"Ani\""
	;

//特效
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "特效"
		-command "do2ShelfChange \"Eff\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "渲染"
		-command "do2ShelfChange \"Rnd\""
	;

//隐藏面板
	//空
		shelfButton
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"    -l ""	-iol ""	-style "iconOnly"	-c ""
			emp_do2ShelfButton1;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Pre-Productioin
	

	


		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Help" -iol "Help" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "system(\"load //file-cluster/GDC/Resource/Support/Maya/docs/dod2shelf.mht\")"
			pre_do2ShelfButtonX;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把程序纹理转换成贴图" -iol "转换" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hbConvertTx"
			pre_do2ShelfButton20;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "模型Local坐标清零" -iol "P->0" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyAllLocal2ZeroSel()"
			pre_do2ShelfButton12;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "所有模型Local坐标清零" -iol "allP->0" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyAllLocal2Zero()"
			pre_do2ShelfButton123;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "替换模型为动态水草" -iol "水草" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hjModlereplace"
			pre_do2ShelfButton1;
		
		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "生成多种颜色的鱼" -iol "颜色" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hbFishColor"
			pre_do2ShelfButton8;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "批量修改文件或图片名字" -iol "改名" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "jm_BR_mainWin"
			pre_do2ShelfButton2;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "带历史复制（动态水草）" -iol "复制!" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "duplicate -rr -ic;"
			pre_do2ShelfButton3;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改为DOD1的正确贴图路径" -iol "图Pth" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2ImagePath;"
			pre_do2ShelfButton4;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "几种树进行替换" -iol "换树" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbReplaceTree.mel\";HbReplaceTree;"
			pre_do2ShelfButton16;

		shelfButton -docTag "Pre"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Pfx海藻工具" -iol "Pfx-" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			pre_do2ShelfButton5;
			popupMenu -button 1 DOD2Alga; 
				menuItem -label "试图修复Pfx海藻连接" -parent DOD2Alga -c "yyDOD2AlgaReconnect";
				menuItem -label "屏蔽Pfx效果（整个场景）" -parent DOD2Alga -c "yyDOD2OffPfx";
				menuItem -label "打开Pfx效果（整个场景）" -parent DOD2Alga -c "yyDOD2OnPfx";
//					menuItem -label "屏蔽纹理" -parent DOD2Algasub -c BuDisplayeyeOn;
//					menuItem -label "显示纹理" -parent DOD2Algasub -c BuDisplayeyeOff;
//					menuItem -label "显示选择物体纹理" -parent Budiplayeyex -c BuDisplayeyeOnsel;
		
		shelfButton -docTag "Pre"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "海藻转换工具" -iol "海藻" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			pre_do2ShelfButton6;
			popupMenu -button 1 DOD2Alga2; 
				menuItem -label "海藻A" -parent DOD2Alga2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/2008/scripts/float_grass_A.mel\"";
				menuItem -label "海藻A->转模型" -parent DOD2Alga2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/floatgrass_A_tools.mel\"";
				menuItem  -parent DOD2Alga2 -divider true;
				menuItem -label "海藻B" -parent DOD2Alga2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/2008/scripts/float_grass_B.mel\"";
				menuItem -label "海藻B->转模型" -parent DOD2Alga2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/floatgrass_B_tools.mel\"";
		
		shelfButton -docTag "Pre"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "海葵转换工具" -iol "海葵" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			pre_do2ShelfButton7;
			popupMenu -button 1 DOD2Anm2; 
				menuItem -label "海葵A" -parent DOD2Anm2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/2008/scripts/anemone_A.mel\"";
				menuItem -label "海葵A->转模型" -parent DOD2Anm2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/anemone_A_tools.mel\"";
				menuItem  -parent DOD2Anm2 -divider true;
				menuItem -label "海葵B" -parent DOD2Anm2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/2008/scripts/anemone_B.mel\"";
				menuItem -label "海葵B->转模型" -parent DOD2Anm2 -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/anemone_B_tools.mel\"";

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "skinCluster 和 blendshape修复工具" -iol "skin" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyCorrectiveBS"
			pre_do2ShelfButton9;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "shading Engine重命名" -iol "SG" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "renameSG"
			pre_do2ShelfButton10;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "参考该场景的所有动画相机（必须动画先checkin）" -iol "camAni" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2PreEPCamRef"
			pre_do2ShelfButton11;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导出动画提供的该场景的所有动画相机" -iol "camImp" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2PreEPCamImp"
			pre_do2ShelfButton11_2;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "参考回来" -iol "refBac" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2PreEPCamImpRef"
			pre_do2ShelfButton11_3;


		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除历史" -iol "delCH" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDelCH"
			pre_do2ShelfButton122;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "海草朝向相机" -iol "草Aim" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2LookAtCamera"
			pre_do2ShelfButton13;



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Rigging
	/*
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Reference 开关"	-iol "Ref开关" 	-style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_do2_commonTools.mel\";do2_switchReference;"
			set_do2ShelfButton1;
		*/

		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "添加smooth连接"	-iol "Smooth" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2SmoothPipelineTool"
			set_do2ShelfButton2;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择点添加毛囊"	-iol "毛囊" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "createFollicle"
			set_do2ShelfButton3;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Animation
		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Assets Database 访问参考内容"	-iol "Info" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "zwAssetFile"
			ani_do2ShelfButton1;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "打开表情库"	-iol "公用" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hbDODPetool"
			ani_do2ShelfButton2;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "打开表情库"	-iol "本地" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hbDODPetool_local"
			ani_do2ShelfButton2_1;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "打开表情库"	-iol "制作" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/gdc/Resource/Support/Maya/modules/FBP/scripts/poseLib_0441.mel\";"
			ani_do2ShelfButton2_2;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "快照口型库"	-iol "shot" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyLipSyncSnapShot"
			ani_do2ShelfButton22;

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Lip Sync Tool口型同步工具" -iol "Sync" -style "iconOnly" -i1 "pythonFamily.xpm"
			-c "yyDOD2LipSyncRD"
			ani_do2ShelfButton3;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "纹理显示与屏蔽" -iol "纹理" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			ani_do2ShelfButton4;
			popupMenu -button 1 DODantimex; 
				menuItem -subMenu true -label "屏蔽纹理显示" -parent DODantimex Budiplayeyex;
					menuItem -label "屏蔽纹理" -parent Budiplayeyex -c BuDisplayeyeOn;
					menuItem -label "显示纹理" -parent Budiplayeyex -c BuDisplayeyeOff;
					menuItem -label "显示选择物体纹理" -parent Budiplayeyex -c BuDisplayeyeOnsel;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "hjBaker" -iol "Bake" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm")) 
			-c "hjBakerobject"
			ani_do2ShelfButton5;

		//shelfButton -docTag "Ani"
			//-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "拍屏的时候屏蔽高光" -iol "高光" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm")) 
			//-c "hbMaterialTool"
			//ani_do2ShelfButton100;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动导入声音，帧率，标准相机" -iol "导入" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "yyDOD2ImportSound"
			ani_do2ShelfButton6;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "电视框" -iol "4:3" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm")) 
			-c "yycamclip"
			ani_do2ShelfButton61;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入录像机挡板" -iol "REC" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "yyImportCamClipRecoderGUI"
			ani_do2ShelfButton6000;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Easy Animation Toolkit" -iol "EA" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "yyEasyAnimation18"
			ani_do2ShelfButton7;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "过渡帧工具，950TPose表演位，0：TPose原点" -iol "过渡" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "yyDOD2Post5FramesKey"
			ani_do2ShelfButton8;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择全身控制器" -iol "选择" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			ani_do2ShelfButton9;
			popupMenu -button 1 DOD2antimex;
				menuItem -label "Olly" -parent DOD2antimex -c "yyDOD2SelectOlly";
				menuItem -label "Beth" -parent DOD2antimex -c "yyDOD2SelectBeth";
				menuItem -label "Skid" -parent DOD2antimex -c "yyDOD2SelectSkid";
				menuItem -label "Walterscooterglasses" -parent DOD2antimex -c "yyDOD2SelectWalterscooterglasses";
				menuItem -label "Bobsieseaotter" -parent DOD2antimex -c "yyDOD2SelectBobsieseaotter";

		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动关闭 Smooth " -iol "SmOff" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOff"
			ani_do2ShelfButton10;

/*
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动关闭 Smooth " -iol "SmOff" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOn"
*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Eff
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "群组动画工具" -iol "群集" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/DODFishSchool.mel\";DODFishSchool;"
			eff_do2ShelfButton1;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "鱼群组填加障碍" -iol "障碍" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "cMakerAddObstacle"
			eff_do2ShelfButton5;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "显示Geometry Cache" -iol "shwCh" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hjDPCache"
			eff_do2ShelfButton2;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建特效泡泡" -iol "泡泡" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yy_zjBubbleSetup"
			eff_do2ShelfButton3;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "设置粒子初始" -iol "初始" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "setParticleStartFrame"
			eff_do2ShelfButton10;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建特效水草" -iol "水草" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source Pfx_model.mel; Pfx_model"
			eff_do2ShelfButton4;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建海面 水花 泡沫" -iol "Splash" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyDO2MuliSameRef;source \"//file-cluster/GDC/Resource/Support/Maya/scripts/cxDOD2SplashWakeFoam.mel\";\
				cxDOD2SplashWakeFoam;"
			eff_do2ShelfButton6;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "调节粒子初始位置" -iol "初始" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hjParticleLoc"
			eff_do2ShelfButton7;

		shelfButton -docTag "Eff"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "pfx连接" -iol "pfx" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			eff_do2ShelfButton8;
			popupMenu -button 1 DOD2antimex; 
				menuItem -label "激活pfx连接" -parent DOD2antimex -c yyDOD2OnPfx;
				menuItem -label "关闭pfx连接" -parent DOD2antimex -c yyDOD2OffPfx;
				//menuItem -label "激活pfx连接" -parent Budiplayeyexx -c BuDisplayeyeOn;
				//menuItem -label "关闭pfx连接" -parent Budiplayeyexx -c BuDisplayeyeOff;


		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "GeoHair 缓存转换" -iol "Hair" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "python( \"import sys\\nsys.path.append(\\\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT\\\")\\nfrom HfollistCon  import *\" );\rpython(\"HfollistCon()\");\r"
			eff_do2ShelfButton9;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "屏蔽1001帧前面的渲染画面" -iol "空镜" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "HBPlane"
			eff_do2ShelfButton11;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "目前拷贝流体cache到网上" -iol "cache" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2CopyCache"
			eff_do2ShelfButton12;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "ocean层上添加一个复制物体的matte层" -iol "oMatte" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AddBlackHole"
			eff_do2ShelfButton13;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "新的海面" -iol "海2" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDO2MuliSameRef; source \"//file-cluster/GDC/Resource/Support/Maya/scripts/yyzzcxDOD2SplashWakeFoam.mel\";\
				yyzzcxDOD2SplashWakeFoam;"
			eff_do2ShelfButton14;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动开启 Smooth " -iol "SmOn" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOn"
			eff_do2ShelfButton15;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动关闭 Smooth " -iol "SmOff" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOff"
			eff_do2ShelfButton16;	
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动添加emitter" -iol "emitter" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AddEmitter"
			eff_do2ShelfButton17;	
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "给海草添加自动摇动" -iol "AuGrass" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbAutoGrass.mel\";HbAutoGrass;"
			eff_do2ShelfButton18;	

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "闪烁特效" -iol "LE" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "HbEfLightTool"
			eff_do2ShelfButton19;
			
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "调节植物摆动的大小" -iol "摆动" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "HbGrassT"
			eff_do2ShelfButton20;

//yyDOD2CopyCache  yyDO2MuliSameRef
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


	//Rnd

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "提取相机" -iol "Cams" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyExtractCam"
			rnd_do2ShelfButton0;

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "特殊场景分层模版" -iol "特殊" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			rnd_do2ShelfButton1;
			popupMenu -button 1 DOD2RndLayerTemple; 
				menuItem -subMenu true -label "特殊场景分层模版" -parent DOD2RndLayerTemple Budiplayeyekk;
					menuItem -label "e001002学校内景" -parent Budiplayeyekk -c Buschoolset;
					menuItem -label "Green" -parent Budiplayeyekk;
					menuItem -label "Green" -parent Budiplayeyekk;

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "分层渲染组合" -iol "分层" -style "iconOnly" -i1 (zwGetIcon("arrowDown.xpm")) 
			rnd_do2ShelfButton2;
			popupMenu -button 1 DOD2LayerCombine; 
				menuItem -subMenu true -label "分层渲染组合" -parent DOD2LayerCombine DOD2lcO;
					menuItem -label "CgPass 设置" -parent DOD2lcO -c CgpassRenderGlobal;
					menuItem -label "MR多通道输出color Occ" -parent DOD2lcO -c "python(\"execfile(\\\"//file-cluster/GDC/Resource/Support/Maya/Python/IDMT/HJBufferPass.py\\\")\");\rpython(\"HJFBpassUI()\");" ;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "断开shader.color属性" -iol "断开" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "hjcolorbreak"
			rnd_do2ShelfButton3;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "黄壁测试" -iol "测试" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "myTest"
			rnd_do2ShelfButton4;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除参考历史信息"	-iol "refRm" 	-style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyReferenceSNR"
			rnd_lvShelfButton6;
/*
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "202整集Caustic Effect生成"	-iol "caustic" 	-style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyAllCaustic"
			rnd_lvShelfButton7;
*/

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "吴敏鱼儿贴图路径修改"	-iol "HTW" 	-style "iconOnly" -i1 "pythonFamily.XPM"
			-c "HbToWuMin"
			rnd_lvShelfButton9;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "渲染工具集" 	-style "iconOnly" -image "yyrender.bmp"
			-c "yyDOD2RenderToolkit"
			rnd_lvShelfButton8;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "牛头渲染的批量方式"		-style "iconOnly" -image "brbatch.bmp"
			-c "bfrenderBatch"
			rnd_lvShelfButton10;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "海面" -iol "海面" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "yyDO2MuliSameRef;source \"//file-cluster/GDC/resource/support/maya/scripts/cxDOD2SplashWakeFoam.mel\";\
			    source \"//file-cluster/GDC/resource/support/maya/scripts/zzDOD2SplashWakeFoam.mel\";\
			    layertool;"
			rnd_do2ShelfButton11;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "李锐建层" -iol "建层" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/layertool.mel\";\
			    layertool;"
			rnd_do2ShelfButton12;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "分割文件" -iol "分割" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/renderlayertoolNew.mel\";\
			   HbRenderTools;"
			rnd_do2ShelfButton23;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建浮尘" -iol "浮尘" -style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/LrCreatDustLayer.mel\";\
			   DustLayer;"
			rnd_do2ShelfButton24;


		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改namespace" -iol "修命名" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyD2SNS"
			rnd_do2ShelfButton13;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改namespace for all characters" -iol "NSAll" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyD2SNSAll"
			rnd_do2ShelfButton13_2;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动设置大浪参数" -iol "大浪" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyBigWake"
			rnd_do2ShelfButton14;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动添加漂浮约束" -iol "飘" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDO2Floating"
			rnd_do2ShelfButton15;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "s2150402场景自动添加漂浮约束" -iol "海带" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDO2FloatingRibbon"
			rnd_do2ShelfButton16;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动开启 Smooth " -iol "SmOn" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOn"
			rnd_do2ShelfButton17;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动关闭 Smooth " -iol "SmOff" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AutoSmoothOff"
			rnd_do2ShelfButton18;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动添加emitter" -iol "emitter" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2AddEmitter"
			rnd_do2ShelfButton19;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "试图恢复海面暗淡效果" -iol "灰海" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "yyDOD2GrayOcean"
			rnd_do2ShelfButton20;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "替换鱼儿颜色" -iol "CFC" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "HbChangeFishColor"
			rnd_do2ShelfButton21;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "立体摄像机" -iol "SC" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "HbCreateSC"
			rnd_do2ShelfButton22;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "更换鱼群贴图路径" -iol "path" -style "iconOnly" -i1 "pythonFamily.XPM"
			-c "python(\"from IDMT.twwScript.DODII.changeFishMapPath import *;DODII_ChangeFishPath()\")"
			;
		
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "更换鱼群贴图路径"	-iol "fish" 	-style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "doRenderReplacePath"
			rnd_lvShelfButton24;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "解决267部分镜头离原点太远而闪动的问题"	-iol "闪动" 	-style "iconOnly" -i1 (zwGetIcon("commandButton.xpm"))
			-c "HbRepairMel"
			rnd_lvShelfButton25;
//yyDOD2AddEmitter yyDOD2GrayOcean
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



	do2ShelfChange `optionVar -query "do2ShelfSelected"`;
}

global proc do2ShelfChange(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray DOD2`;
	int $size = size($childArray);
	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible true $childArray[$i];
			}
			else
			{
				shelfButton -edit -visible false $childArray[$i];
				shelfLayout -edit -position $childArray[$i] $size DOD2;
			}
		}
	}
	optionVar -stringValue "do2ShelfSelected" $steps;

}
global proc qhz_ClearLocalPoint(){
	$selObj = `ls - sl`;
	FreezeTransformations;
	makeIdentity -apply true -t 1 -r 1 -s 1 -n 0;
	DeleteHistory;
	transferAttributes -transferPositions 0 -transferNormals 0 -transferUVs 2 -transferColors 2 -sampleSpace 0 -flipUVs 0 -colorBorders 1 ;
	select $selObj; 
	DeleteHistory;
}
global proc yyDOD2LipSyncRD(){

	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LipSyncRD.py\")");
	python("yyDOD2LipSyncRDGUI()");
}

global proc yyDOD2ImportSound(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ImportSound.py\")");
}

global proc yyEasyAnimation18()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyEasyAnimation2.py\")");
	//python("yyEnyoLipsyncGUI()");
}

global proc yyDOD2Post5FramesKey(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2Post5FramesKey.py\")");
}

global proc yyLipSyncSnapShot(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LipSyncExt.py\")");
	python("yyEnyoLipsyncGUI()");
}

global proc yyDOD2ImagePath(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReplacePath.py\")");
}

global proc yyDOD2AlgaReconnect(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2ReconnectAlga()");
	python("yyDOD2ReconnectAnemone()");
}

global proc yyDOD2OffPfx(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2TurnOffStroke()");
}
global proc yyDOD2OnPfx(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2TurnOnStroke()");
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yyDOD2SelectOlly(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectOlly()");
}
global proc yyDOD2SelectBeth(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectBeth()");
}
global proc yyDOD2SelectSkid(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectSkid()");
}
global proc yyDOD2SelectWalterscooterglasses(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectWalterscooterglasses()");
}
global proc yyDOD2SelectBobsieseaotter(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectBobsieseaotter()");
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc yyCorrectiveBS(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCorrectShapeForSkinCluster.py\")");

}
global proc yyDOD2SmoothPipelineTool(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SmoothPipelineTool.py\")");
}
global proc yyReferenceSNR(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yySearchNReplaceReferenceEdits.py\")");
	python("yySearchNReplaceReferenceEditsGUI()");
}
global proc yyAllCaustic(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2TotalRenderCausticFX.py\")");

}

global proc yyDOD2RenderToolkit(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2RenderToolkit.py\")");
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2RenderToolkitFunc.py\")");
	python("yyDOD2RTGUI()");

}
global proc yyDOD2CopyCache(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2CopyCache.py\")");
	python("yyCopyCacheWarpper()");

}
global proc renameSG(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyRenameShadingEngine.py\")");
}
global proc bfrenderBatch(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyBatchBuffaloRender.py\")");
	python("yyBatchBuffaloRender()");
}
global proc yyDOD2AddBlackHole(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2AddBlackHole.py\")");
	python("yyDOD2AddBlackHole()");
}
global proc yyDOD2PreEPCamRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreReferenceCamForSet.py\")");
	python("yyDOD2PreRefEpCamForSetWrapper()");
}
global proc yyDOD2PreEPCamImp(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreImportCamForSet.py\")");
	python("yyDOD2PreRefEpCamForSetWrapper()");
}
global proc yyDOD2PreEPCamImpRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreImportCamForSet.py\")");
	python("referenceBack()");
}


global proc yyImportCamClipRecoderGUI(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2CamClipRecoder.py\")");
	python("yyDOD2CamClipRecorderGUI()");
}

global proc yyDelCH(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyAutoDeleteHistoryWithoutDeform.py\")");
}

global proc yyExtractCam(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyBatchExtractCam.py\")");
	python("yyBatchExtractCam()");
}
global proc cxSplash(){
	source "//file-cluster/GDC/resource/support/maya/scripts/cxDOD2SplashWakeFoam.mel";
	cxDOD2SplashWakeFoam;
}
global proc yyzzcxSplash(){
	source "//file-cluster/GDC/resource/support/maya/scripts/yyzzcxDOD2SplashWakeFoam.mel";
	yyzzcxDOD2SplashWakeFoam;
}
global proc yyD2SNS(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2DoubleNamespaceToSingle.py\")");
	python("yyDOD2DoubleNamespaceToSingle()");
}
global proc yyBigWake(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SetBigOceanWake.py\")");
}
global proc yyzzcxSplashOld(){
	source "//file-cluster/GDC/resource/support/maya/scripts/cxDOD2SplashWakeFoam.mel";
	source "//file-cluster/GDC/resource/support/maya/scripts/zzDOD2SplashWakeFoam.mel";
	zzDOD2SplashWakeFoam;
}
global proc yyD2SNSAll(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2DoubleNamespaceToSingle.py\")");
	python("yyImportNCoverNamespace()");
}

global proc yyDO2FloatingRibbon(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2OceanRibbon.py\")");
	python("yyDOD2OceanRibbon()");
}
global proc yyDO2Floating(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2OceanRibbon.py\")");
	python("yyDOD2CreateOceanWaveMark()");
}

global proc yyDO2MuliSameRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2AutoMakeNamespace.py\")");
}

global proc yyDOD2AutoSmoothOn(){
	python("execfile(\"//file-cluster/GDC/resource/support/maya/python/idmt/yyScripts/yyAutoSmooth.py\")");
	python("yyAutoSmoothOn()");
}
global proc yyDOD2AutoSmoothOff(){
	python("execfile(\"//file-cluster/GDC/resource/support/maya/python/idmt/yyScripts/yyAutoSmooth.py\")");
	python("yyAutoSmoothOff()");
}
global proc yyDOD2AddEmitter(){
	python("execfile(\"//file-cluster/GDC/resource/support/maya/python/idmt/yyScripts/yyDOD2EasyAddEmitterPost.py\")");
	python("yyDOD2CxAddEmitterFromSelect()");
}
global proc yyDOD2GrayOcean(){
	python("execfile(\"//file-cluster/GDC/resource/support/maya/python/idmt/yyScripts/yyDOD2GrayOceanFix.py\")");
}

global proc yyDOD2LookAtCamera()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LookAtCamera.py\")");
	python("yyLVLookAtCameraWrapper()");
}

global proc yyAllLocal2Zero()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCleanUpLocalCoo.py\")");
	python("yyCleanUpLocalCoo()");
}
global proc yyAllLocal2ZeroSel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCleanUpLocalCoo.py\")");
	python("yyCleanUpLocalCooSel()");
}

global proc HbEfLightTool()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbEfLight.py\")");
	python("HbEfLightUI()");
}

global proc HbChangeFishColor()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbFishColorUI.py\")");
	python("HbFishColorUI()");
}
global proc HbCreateSC()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbStereoCameraUI.py\")");
	python("StereoCameraUI()");
}

global proc HbGrassT(){
	python("from IDMT.twwScript.DODII.HbGrassT import *;HbGrassT()");
}
global proc HbRepairMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbRepair.py\")");
}

