global proc shelf_JT()
{
/*
	boldLabelFont
	smallBoldLabelFont
	tinyBoldLabelFont
	plainLabelFont
	smallPlainLabelFont
	obliqueLabelFont
	smallObliqueLabelFont
	fixedWidthFont
	smallFixedWidthFont
*/

//前期
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "ARROWDOWN.XPM" 
		-imageOverlayLabel "前期"
		-command "JTShelfChange \"Pre\""
	;

//设置
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 "ARROWDOWN.XPM" 
		-imageOverlayLabel "设置"
		-command "JTShelfChange \"Set\""
	;

//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 "ARROWDOWN.XPM" 
		-imageOverlayLabel "动画"
		-command "JTShelfChange \"Ani\""
	;

//特效
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 "ARROWDOWN.XPM" 
		-imageOverlayLabel "特效"
		-command "JTShelfChange \"Eff\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"

		-image1 "ARROWDOWN.XPM" 
		-imageOverlayLabel "渲染"
		-command "JTShelfChange \"Rnd\""
	;

//隐藏面板
	//空
		shelfButton
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"    -l ""	-iol ""	-style "iconOnly"	-c ""
			emp_JTShelfButton1;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Pre-Productioin
	

	


		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "解锁前期模型" -iol "UR" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbUnReferenceMel"
			pre_JTShelfButton1;



		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "所有模型Local坐标清零" -iol "allP->0" -style "iconOnly" -i1 "commandButton.xpm"
			-c "yyAllLocal2Zero()"
			pre_JTShelfButton123;



		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "批量修改文件或图片名字" -iol "改名" -style "iconOnly" -i1 "commandButton.xpm"
			-c "jm_BR_mainWin"
			pre_JTShelfButton2;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动修改材质节点和贴图的名字" -iol "RMAT" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbRenameMatNodeMell"
			pre_JTShelfButton3;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "模型组整理的材质库" -iol "材质库" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbMaterialsLibMel"
			pre_JTShelfButton4;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "前期导出参考相机并截图" -iol "ECAM" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbExceptCamMel"
			pre_JTShelfButton5;
		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "前期导出参考相机并截图" -iol "ACAM" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbAnExceptCamMel"
			pre_JTShelfButton6;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "简化底模树" -iol "LoTree" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HbLowerTreeMel"
			pre_JTShelfButton7;

		shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建GeoCache Set" -iol "Set" -style "iconOnly" -i1 "commandButton.xpm"
			-c "createGeoCacheSet"
			pre_JTShelfButton8;


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Rigging
	/*
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Reference 开关"	-iol "Ref开关" 	-style "iconOnly" -i1 "commandButton.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/gen_do2_commonTools.mel\";do2_switchReference;"
			set_JTShelfButton1;
		*/



		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "曲线骨骼工具"	-iol "JOC" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/tail.bmp"
			-c "HbJointOnCvTools;"
			set_JTShelfButton6;

		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "附在表面上"	-iol "POS" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/rivet.bmp"
			-c "HbPointOnSurface;"
			set_JTShelfButton7;

		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动创建控制器"	-iol "控制器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/eye.bmp"
			-c "HbADDCtrl;"
			set_JTShelfButton8;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "AutoRIG插件"	-iol "工具" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/abAutoRig.mel\""
			set_JTShelfButton9;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "添加簇为二级控制器"	-iol "控制器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/attr.bmp"
			-c "HbAddCluster"
			set_JTShelfButton10;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择点添加毛囊"	-iol "毛囊" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/createFollicle.mel\""
			set_JTShelfButton11;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "曲面跟随"	-iol "跟随" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "HbCtrlFollowSurface"
			set_JTShelfButton12;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "控制器"	-iol "器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "createCtrl"
			set_JTShelfButton13;						
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	//Animation
		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Assets Database 访问参考内容"	-iol "Info" -style "iconOnly" -i1 "commandButton.XPM"
			-c "zwAssetFile"
			ani_JTShelfButton1;









		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动导入声音，帧率，标准相机" -iol "导入" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbJtImportSoundMel"
			ani_JTShelfButton6;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "电视框" -iol "4:3" -style "iconOnly" -i1 "commandButton.xpm" 
			-c "yycamclip"
			ani_JTShelfButton61;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "两个角色间导动画" -iol "CTC" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "slAnimCopyAnimations"
			ani_JTShelfButton6000;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Easy Animation Toolkit" -iol "EA" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "yyEasyAnimation18"
			ani_JTShelfButton7;

		/*shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "JT项目拍屏工具" -iol "拍屏" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/eye.bmp" 
			-c "HbPlayBlast"
			ani_JTShelfButton8;*/

		/*shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "950,980Tpose" -iol "TPOSE" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbTposeTool"
			ani_JTShelfButton9;*/
		/*shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "解决车轮自转问题" -iol "CAR" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "slAnimWheelExpreesion"
			ani_JTShelfButton10;*/

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "添加tsm菜单" -iol "TSM" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "slAminTSMControlUI"
			ani_JTShelfButton11;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "面部控制器选择" -iol "面控" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbJTSelectFaceCtrlMel"
			ani_JTShelfButton12;


		/*shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "批量拍屏测试" -iol "BPB" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbPlayBlastManageMel"
			ani_JTShelfButton13;*/

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "客户提供的相机文件" -iol "CAM" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbGtCameToolsMel"
			ani_JTShelfButton13;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "表情库" -iol "Face" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/slAnimPoseLibraryJt.mel\";slAnimPoseLibraryJt;"
			ani_JTShelfButton14;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "IKFK转换" -iol "IKFK" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "JTAnimIKFKUIMel "
			ani_JTShelfButton15;



		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "相机bake" -iol "bake" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"zwCameraImportExport.mel\";zwBakeCamera;"
			ani_JTShelfButton17;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "AT工具" -iol "AT" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/autoTangent.mel\";autoTangentUI;"
			ani_JTShelfButton18;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "JT项目拍屏工具" -iol "拍屏" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/eye.bmp" 
			-c "HbPlayBlast"
			ani_PPShelfButton19;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "树高低模替换" -iol "树" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbReplace"
			ani_PPShelfButton20;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "隐藏卡的物体" -iol "卡" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoGreatHairLayer.mel\""
			ani_PPShelfButton21;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "把角色换为没有特效设置版本" -iol "E>A" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbAnEfReplaceRfMel"
			ani_PPShelfButton22;		
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "或得layout的特效文件，请关掉当前文件" -iol "EF" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbExceptEfMel"
			ani_PPShelfButton23;	
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Eff
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "nCloth的初始状态" -iol "nCloth" -style "iconOnly" -i1 "commandButton.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/JTEffectNclothLink.mel\";JTEffectNclothLink;"
			eff_JTShelfButton1;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "优化场景" -iol "优化" -style "iconOnly" -i1 "commandButton.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbOptimize.mel\""
			eff_JTShelfButton2;
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把角色转换成有特效设置的" -iol "A>E" -style "iconOnly" -i1 "commandButton.XPM"
			-c "HbAnEfReplaceRfMel"
			eff_JTShelfButton3;
//yyDOD2CopyCache  yyDO2MuliSameRef
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


	//Rnd

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "清除参考的坏历史" -iol "RFM" -style "iconOnly" -i1 "commandButton.XPM"
			-c "yyReferenceSNR;"
			rnd_JTShelfButton0;


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "树朝向摄像机，默认面片朝向X轴." -iol "树" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbTreeAnim"
			
			rnd_JTShelfButton2;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "植物笔刷" -iol "PE" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/slHbRenderPlanting.mel\"; slHbRenderPlanting"
			
			rnd_JTShelfButton3;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除头发系统" -iol "Hair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/DeleteHair.mel\"; DeleteHair"
			
			rnd_JTShelfButton4;

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "关闭头发系统" -iol "OHair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCloseHair"
			
			rnd_JTShelfButton5;*/
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "渲染工具集" -iol "RTOOL" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/JT/logo/logo02.bmp" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJtRenderTools.mel\"; HbJtRenderTools"
			
			rnd_JTShelfButton6;

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "整理整集参考图片" -iol "CPM" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCopyMapTZ"
			
			rnd_JTShelfButton7;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "高低模树的切换使用" -iol "HML" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbSkReplaceTreeToolsMel"
			
			rnd_JTShelfButton8;*/


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入当前场景的所有摄像机" -iol "getAll" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbImportCamMel"
			
			rnd_JTShelfButton9;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入参考场景" -iol "ITG" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbImportTempGroudMel"
			
			rnd_JTShelfButton11;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入当前场景的所有摄像机" -iol "DeSmooth" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbDeleteSmoothMel"
			
			rnd_JTShelfButton12;*/


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "关掉所有头发" -iol "CHair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCloseTheHairSysMel"
			
			rnd_JTShelfButton13;


		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把头发开始祯设置为980" -iol "980" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbSetHairStartMel"
			
			rnd_JTShelfButton14;*/

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "转换map贴图" -iol "MAP" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Woodlies/LRmap.mel\"; LRmapUI"

			
			rnd_JTShelfButton15;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建FG光子图" -iol "FG" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRFGmap.mel\"; LRFGmapUI"

			
			rnd_JTShelfButton16;


		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "刷草的工具" -iol "grass" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "GrassToolMel"

			
			rnd_JTShelfButton17;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把场景替换为有材质版本" -iol "sets" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "HbJTReplaceRfMel"

			
			rnd_JTShelfButton18;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "面片树朝向摄像机" -iol "LookAt" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "yyhbJTLookAtCameraMel"

			
			rnd_JTShelfButton19;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动隐藏看不见的树和房子" -iol "探照灯" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoHideObject.mel\"; HbAutoHideObject"
			
			rnd_JTShelfButton20;

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动替换中模和房子" -iol "ATH" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoReplace.mel\"; HbAutoReplace"
			
			rnd_JTShelfButton21;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改相机bug" -iol "ReCam" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "HbJtRenderCamMel"
			
			rnd_JTShelfButton22;


		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "树高低模替换" -iol "树" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbReplace"
			rnd_PPShelfButton23;

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择能看见的物体" -iol "Select" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "HbSelectObjMel"
			rnd_PPShelfButton24;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "透明通道物体操作" -iol "SelT" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRFselect.mel\"; LRselectTUI"
			rnd_PPShelfButton25;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改贴图闪动" -iol "Filter" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRfileFilter.mel\"; LRbumpfileUI"
			rnd_PPShelfButton26;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "关闭辉光" -iol "Glow" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "setAttr shaderGlow1.glowType 0;setAttr shaderGlow1.haloType 0;"
			rnd_PPShelfButton27;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除所有渲染层" -iol "删" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRdelAllLayer.mel\"; LRdelAllLayer"
			rnd_PPShelfButton28;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "一键分层工具" -iol "分层" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/CJWRenderlLayersTool.mel\""
			rnd_PPShelfButton29;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择物体创建透明z层" -iol "z层" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/CreatDepthLayerSel.mel\"; CreatDepthLayerSel"
			rnd_PPShelfButton30;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除材质（可不删除带透明通道的物体）" -iol "删材质" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRshadeclear.mel\"; LRshadeclearUI"
			rnd_PPShelfButton31;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "渲染工具集" -iol "渲" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "gtRenderToolsLayout"
			rnd_PPShelfButton32;
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "witch和ivan渲染慢的时候可以先制作geocache再渲" -iol "Cache" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "gtRenderGeoCacheTools"
			rnd_PPShelfButton33;

//yyDOD2AddEmitter yyDOD2GrayOcean
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



	JTShelfChange `optionVar -query "do2ShelfSelected"`;
}

global proc JTShelfChange(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray JT`;
	int $size = size($childArray);
	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible true $childArray[$i];
			}
			else
			{
				shelfButton -edit -visible false $childArray[$i];
				shelfLayout -edit -position $childArray[$i] $size JT;
			}
		}
	}
	optionVar -stringValue "do2ShelfSelected" $steps;

}
global proc qhz_ClearLocalPoint(){
	$selObj = `ls - sl`;
	FreezeTransformations;
	makeIdentity -aJTly true -t 1 -r 1 -s 1 -n 0;
	DeleteHistory;
	transferAttributes -transferPositions 0 -transferNormals 0 -transferUVs 2 -transferColors 2 -sampleSpace 0 -flipUVs 0 -colorBorders 1 ;
	select $selObj; 
	DeleteHistory;
}
global proc yyDOD2LipSyncRD(){

	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LipSyncRD.py\")");
	python("yyDOD2LipSyncRDGUI()");
}

global proc HbJTImportSound(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbJTImportSound.py\")");
}

global proc yyEasyAnimation18()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyEasyAnimation2.py\")");
	//python("yyEnyoLipsyncGUI()");
}

global proc yyDOD2Post5FramesKey(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2Post5FramesKey.py\")");
}

global proc yyLipSyncSnapShot(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LipSyncExt.py\")");
	python("yyEnyoLipsyncGUI()");
}

global proc yyDOD2ImagePath(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReplacePath.py\")");
}

global proc yyDOD2AlgaReconnect(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2ReconnectAlga()");
	python("yyDOD2ReconnectAnemone()");
}

global proc yyDOD2OffPfx(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2TurnOffStroke()");
}
global proc yyDOD2OnPfx(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2ReconnectAlga.py\")");
	python("yyDOD2TurnOnStroke()");
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
global proc yyDOD2SelectOlly(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectOlly()");
}
global proc yyDOD2SelectBeth(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectBeth()");
}
global proc yyDOD2SelectSkid(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectSkid()");
}
global proc yyDOD2SelectWalterscooterglasses(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectWalterscooterglasses()");
}
global proc yyDOD2SelectBobsieseaotter(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SelectAllCtrs.py\")");
	python("yyDOD2SelectBobsieseaotter()");
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

global proc yyCorrectiveBS(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCorrectShapeForSkinCluster.py\")");

}
global proc yyDOD2SmoothPipelineTool(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SmoothPipelineTool.py\")");
}
global proc yyReferenceSNR(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yySearchNReplaceReferenceEdits.py\")");
	python("yySearchNReplaceReferenceEditsGUI()");
}
global proc yyAllCaustic(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2TotalRenderCausticFX.py\")");

}

global proc yyDOD2RenderToolkit(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2RenderToolkit.py\")");
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2RenderToolkitFunc.py\")");
	python("yyDOD2RTGUI()");

}
global proc yyDOD2CopyCache(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2CopyCache.py\")");
	python("yyCopyCacheWarJTer()");

}
global proc renameSG(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyRenameShadingEngine.py\")");
}
global proc bfrenderBatch(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyBatchBuffaloRender.py\")");
	python("yyBatchBuffaloRender()");
}
global proc yyDOD2AddBlackHole(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2AddBlackHole.py\")");
	python("yyDOD2AddBlackHole()");
}
global proc yyDOD2PreEPCamRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreReferenceCamForSet.py\")");
	python("yyDOD2PreRefEpCamForSetWraJTer()");
}
global proc yyDOD2PreEPCamImp(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreImportCamForSet.py\")");
	python("yyDOD2PreRefEpCamForSetWraJTer()");
}
global proc yyDOD2PreEPCamImpRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2PreImportCamForSet.py\")");
	python("referenceBack()");
}


global proc yyImportCamClipRecoderGUI(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2CamClipRecoder.py\")");
	python("yyDOD2CamClipRecorderGUI()");
}

global proc yyDelCH(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyAutoDeleteHistoryWithoutDeform.py\")");
}

global proc yyExtractCam(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyBatchExtractCam.py\")");
	python("yyBatchExtractCam()");
}
global proc cxSplash(){
	source "//file-cluster/GDC/resource/Support/maya/scripts/cxDOD2SplashWakeFoam.mel";
	cxDOD2SplashWakeFoam;
}
global proc yyzzcxSplash(){
	source "//file-cluster/GDC/resource/Support/maya/scripts/yyzzcxDOD2SplashWakeFoam.mel";
	yyzzcxDOD2SplashWakeFoam;
}
global proc yyD2SNS(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2DoubleNamespaceToSingle.py\")");
	python("yyDOD2DoubleNamespaceToSingle()");
}
global proc yyBigWake(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2SetBigOceanWake.py\")");
}
global proc yyzzcxSplashOld(){
	source "//file-cluster/GDC/resource/Support/maya/scripts/cxDOD2SplashWakeFoam.mel";
	source "//file-cluster/GDC/resource/Support/maya/scripts/zzDOD2SplashWakeFoam.mel";
	zzDOD2SplashWakeFoam;
}
global proc yyD2SNSAll(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2DoubleNamespaceToSingle.py\")");
	python("yyImportNCoverNamespace()");
}

global proc yyDO2FloatingRibbon(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2OceanRibbon.py\")");
	python("yyDOD2OceanRibbon()");
}
global proc yyDO2Floating(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2OceanRibbon.py\")");
	python("yyDOD2CreateOceanWaveMark()");
}

global proc yyDO2MuliSameRef(){
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2AutoMakeNamespace.py\")");
}

global proc yyDOD2AutoSmoothOn(){
	python("execfile(\"//file-cluster/GDC/resource/Support/maya/python/idmt/yyScripts/yyAutoSmooth.py\")");
	python("yyAutoSmoothOn()");
}
global proc yyDOD2AutoSmoothOff(){
	python("execfile(\"//file-cluster/GDC/resource/Support/maya/python/idmt/yyScripts/yyAutoSmooth.py\")");
	python("yyAutoSmoothOff()");
}
global proc yyDOD2AddEmitter(){
	python("execfile(\"//file-cluster/GDC/resource/Support/maya/python/idmt/yyScripts/yyDOD2EasyAddEmitterPost.py\")");
	python("yyDOD2CxAddEmitterFromSelect()");
}
global proc yyDOD2GrayOcean(){
	python("execfile(\"//file-cluster/GDC/resource/Support/maya/python/idmt/yyScripts/yyDOD2GrayOceanFix.py\")");
}

global proc yyDOD2LookAtCamera()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyDOD2LookAtCamera.py\")");
	python("yyLVLookAtCameraWraJTer()");
}

global proc yyAllLocal2Zero()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCleanUpLocalCoo.py\")");
	python("yyCleanUpLocalCoo()");
}
global proc yyAllLocal2ZeroSel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyCleanUpLocalCoo.py\")");
	python("yyCleanUpLocalCooSel()");
}

global proc HbEfLightTool()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbEfLight.py\")");
	python("HbEfLightUI()");
}

global proc HbChangeFishColor()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbFishColorUI.py\")");
	python("HbFishColorUI()");
}
global proc HbCreateSC()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/DODII/HbStereoCameraUI.py\")");
	python("StereoCameraUI()");
}
global proc HbBodyRigTools()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbBodyRig.py\")");
	python("HbBodyRigUI");
}
global proc HbFacialRigTools()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HBFacialRIGUI.py\")");
	python("HbFacialRIGUI()");
}

global proc HbPointOnSurface()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Lionelville/HbCtrlFollowSurface.py\")");
}
global proc HbADDCtrl()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/scripts/YJcreateCtrl.py\")");
	python("YJcreateCtrl()");
}
global proc HbCreatPreGRP()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbCreatGroup.py\")");
}

global proc HbPlayBlast()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAnDyn.py\")");
}

global proc HbDynInMaya()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbCreateGeoCache.py\")");
}

global proc HbCloseHair()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbSetDYN.py\")");
}

global proc HbCopyMapTZ()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbCopyMaps.py\")");

}

global proc HbTposeTool()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbTopse.py\")");

}


global proc HbSkReplaceTreeToolsMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbSkTreeReplace.py\")");

}


global proc HbImportCamMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbImportCam.py\")");

}



global proc HbCopyPassMb()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbCopyFlie.py\")");

}

global proc HbImportTempGroudMel()
{

	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/HbImportTempGroud.py\")");



}
global proc HbTreeAnim()
{

	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/yyhbJTLookAtCamera.py\")");



}

global proc HbRenameMatNodeMell()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbRenameMatNode.py\")");


}

global proc HbMaterialsLibMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbMaterialsLib.py\")");


}
global proc HbJTFaceCtrlToolsMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbJTFaceCtrlTools.py\")");


}
global proc HbExceptCamMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbExceptCam.py\")");


}

global proc HbAnExceptCamMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbAnExceptCam.py\")");


}


global proc HbDeleteSmoothMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbDeleteSmooth.py\")");


}

global proc HbAnExceptSetDressCamMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbExceptSetDressCam.py\")");


}



global proc HbCloseTheHairSysMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/CloseTheHairSys.py\")");


}


global proc HbSetHairStartMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbSetHairStart.py\")");


}



global proc HbPlayBlastManageMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/HbPlayBlastManage.py\")");


}
global proc HbUnReferenceMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbUnReference.py\")");


}



global proc HbGtCameToolsMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbGtCameraTools.py\")");


}

global proc HbJTSelectFaceCtrlMel ()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbSelectFaceCtrl.py\")");


}
global proc JTAnimIKFKUIMel ()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/AnimIKFKUI.py\")");


}
global proc HbPlayBlast()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJTAutoDynOffOrOn.py\")");
}
global proc HbReplace()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJTTreeReplace.py\")");
}

global proc GrassToolMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbGrassToolLib.py\")");
}


global proc HbJTReplaceRfMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJTReplaceRf.py\")");
}



global proc yyhbJTLookAtCameraMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/yyhbJTLookAtCamera.py\")");
}
global proc HbJtRenderCamMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJtRenderCam.py\")");
}
global proc HbLowerTreeMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbLowerTree.py\")");
}



global proc HbJtImportSoundMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJtImportSound.py\")");
}

global proc HbSelectObjMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbSelect.py\")");
}


global proc HbAnEfReplaceRfMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAnEfReplaceRf.py\")");
}
global proc HbEfAnReplaceRfMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbEfAnReplaceRf.py\")");
}


global proc HbExceptEfMel()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbExceptEf.py\")");
}


global proc HbAddCluster()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAddCluster.py\")");
}


global proc HbCtrlFollowSurface()
{
	python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbCtrlFollowSurface.py\")");
}

global proc createCtrl()
{
python("execfile(\"//file-cluster/GDC/Resource/Support/Maya/projects/JT/YJcreateCtrl.py\")");
python("YJcreateCtrl()");
}

global proc createGeoCacheSet()
{
	if (`objExists "GEO_CACHE_SET"`)
	{
	    delete GEO_CACHE_SET;
	}
	sets -name "GEO_CACHE_SET";
	select -r -ne "GEO_CACHE_SET";	
}