global proc shelf_OTTO()
{
python("import maya.cmds as cmds");
python("import maya.mel as mel");
//前期
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 ("Calimero/pre_calimero.png")
		-imageOverlayLabel "       前"
		-label "前期工具集"
		-command "OTTOShelfChanges \"Pre\""
	;

//设置
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 ("Calimero/set_Calimero.png")
		-imageOverlayLabel "       设"
		-label "设置工具集"
		-command "OTTOShelfChanges \"Set\""
	;

//动画
//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 ("Calimero/ani_calimero.png")
		-imageOverlayLabel "       动画"
		-label "动画工具集"
		-command "OTTOShelfChanges \"Ani\""
	;

//特效
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 ("Calimero/eff_calimero.png")
		-imageOverlayLabel "       特效"
		-label "特效工具集"
		-command "OTTOShelfChanges \"Eff\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 ("Calimero/rnd_calimero.png")
		-imageOverlayLabel "       渲染"
		-label "渲染工具集"
		-command "OTTOShelfChanges \"Rnd\""
	;

 //zzj               Pre**************************
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "前期工具集" -iol "tools" -style "iconOnly" -i1 "commandButton.xpm"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\"; ot_Pretools()";
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入摄像机" -iol "ICAM" -style "iconOnly" -i1 "commandButton.xpm"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_ImportRenderCam.mel\"; ot_ImportRenderCam";
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动参考" -iol "SET" -style "iconOnly" -i1 "commandButton.xpm"
			-c "ot_set";
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导出物体" -iol "IMod" -style "iconOnly" -i1 "commandButton.xpm"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_modReplace.mel\"; ot_expmod()";
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "冻结点位移信息" -iol "冻结" -style "iconOnly" -i1 "commandButton.xpm"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_freezeVTX.mel\";";
	shelfButton -docTag "Pre"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Cam解锁"	-iol "Unlock" -style "iconOnly" -i1 "commandButton.xpm"
			-c "HHUnlock";





			 //zzj               Rigging**************************
       shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "曲线骨骼工具"	-iol "JOC" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/tail.bmp"
			-c "HbJointOnCvTools;"
			set_JTShelfButton6;

		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "附在表面上"	-iol "POS" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/rivet.bmp"
			-c "HbPointOnSurface;"
			set_JTShelfButton7;

		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动创建控制器"	-iol "控制器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/eye.bmp"
			-c "HbADDCtrl;"
			set_JTShelfButton8;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "AutoRIG插件"	-iol "工具" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/abAutoRig.mel\""
			set_JTShelfButton9;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "添加簇为二级控制器"	-iol "控制器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/attr.bmp"
			-c "HbAddCluster"
			set_JTShelfButton10;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择点添加毛囊"	-iol "毛囊" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/createFollicle.mel\""
			set_JTShelfButton11;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "曲面跟随"	-iol "跟随" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "HbCtrlFollowSurface"
			set_JTShelfButton12;
		shelfButton -docTag "Set"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "控制器"	-iol "器" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp"
			-c "createCtrl"
			set_JTShelfButton13;	
	
			;

 //zzj               Ani**************************
		shelfButton -docTag "Ani"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "Assets Database 访问参考内容"	-iol "Info" -style "iconOnly" -i1 "commandButton.XPM"
			-c "zwAssetFile"
			ani_JTShelfButton1;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动导入声音，帧率，标准相机" -iol "导入" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/HbJtImportSound.py')"
			
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "电视框" -iol "4:3" -style "iconOnly" -i1 "commandButton.xpm" 
			-c "yycamclip"
			ani_JTShelfButton61;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "两个角色间导动画" -iol "CTC" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "slAnimCopyAnimations"
			ani_JTShelfButton6000;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Easy Animation Toolkit" -iol "EA" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yyEasyAnimation2.py')"
			;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "添加tsm菜单" -iol "TSM" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "slAminTSMControlUI"
			ani_JTShelfButton11;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "面部控制器选择" -iol "面控" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbSelectFaceCtrl.py')"
			ani_JTShelfButton12;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "客户提供的相机文件" -iol "CAM" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_CameraTools.py')"
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "表情库" -iol "Face" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_AnimPoseLibrary.mel\"; ot_slAnimPoseLibrary()"
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "IKFK转换" -iol "IKFK" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/AnimIKFKUI.py')"
			ani_JTShelfButton15;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选中任意角色的某个模型，将会独立显示该模型;什么都不选时，将显示所有角色" -iol "IsoDisplay" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_Ani_IsolateDisplay.py')"
			;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "相机bake" -iol "bake" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"zwCameraImportExport.mel\";zwBakeCamera;"
			ani_JTShelfButton17;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "AT工具" -iol "AT" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/autoTangent.mel\";autoTangentUI;"
			ani_JTShelfButton18;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "OT项目拍屏工具" -iol "拍屏" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/eye.bmp" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJTAutoDynOffOrOn.py')"
			;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "树高低模替换" -iol "树" -style "iconOnly" -i1 "pythonFamily.xpm"  
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\";ot_MeshReplace();"
			;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "隐藏卡的物体" -iol "卡" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoGreatHairLayer.mel\""
			ani_PPShelfButton21;

		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "把角色换为没有特效设置版本" -iol "E>A" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAnEfReplaceRf.py')"
			;
					
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "或得layout的特效文件，请关掉当前文件" -iol "EF" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbExceptEf.py')"
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "动作库" -iol "P-L" -style "iconOnly" -i1 "commandButton.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry/slAnimPoseLibraryNew.mel\"; slAnimPoseLibraryNew()"
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "导动画曲线工具" -iol "curve" -style "iconOnly" -i1 "commandButton.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/slAnimExportImportForSetMainLayout.mel\"; slAnimExportImportForSetMainLayout()"
			;
		shelfButton -docTag "Ani"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Q0440场道具形态切换" -iol "Q0440" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/icons/face.bmp" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/Q0440scene.mel\";"
			;				
 //zzj 			 Eff**************************
		//shelfButton -docTag "Eff"
		//	-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "制作Geocache" -iol "Geocache" -style "iconOnly" -i1 "commandButton.xpm"
		//	-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_GeoCacheHighend.mel\"; ot_GeocacheHighend";
		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "解算工具面板" -iol "FxTools" -style "iconOnly" -i1 "commandButton.xpm"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\"; ot_Fxtools()";
		
		/*shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "nCloth的初始状态" -iol "nCloth" -style "iconOnly" -i1 "commandButton.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/JTEffectNclothLink.mel\";JTEffectNclothLink;"
			eff_JTShelfButton1;

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "优化场景" -iol "优化" -style "iconOnly" -i1 "commandButton.XPM"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbOptimize.mel\""
			eff_JTShelfButton2;
		*/
	
		//		shelfButton -docTag "Eff"
//			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动出Geocache" -iol "GeoChe" -style "iconOnly" -i1 "commandButton.XPM"
//			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_GeoCacheHighend.mel\""
//			ot_GeoCache_Batch();

		shelfButton -docTag "Eff"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "topper戴帽子时头发隐藏" -iol "头发" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/icons/TopperHair.png"
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_topperHair.mel\"; ";
			
			
			
 //zzj               Rnd**************************
 	//Rnd

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "清除参考的坏历史" -iol "RFM" -style "iconOnly" -i1 "commandButton.XPM" -stp "python"
			-c  "execfile('//file-cluster/GDC/Resource/Support/Maya/python/idmt/yyscripts/yySearchNReplaceReferenceEdits.py');yySearchNReplaceReferenceEditsGUI()";



		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "树朝向摄像机，默认面片朝向X轴." -iol "树" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbTreeAnim"
			
			rnd_JTShelfButton2;
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "植物笔刷" -iol "PE" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Strawberry2/slHbRenderPlanting.mel\"; slHbRenderPlanting"
			
			rnd_JTShelfButton3;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除头发系统" -iol "Hair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/DeleteHair.mel\"; DeleteHair"
			
			rnd_JTShelfButton4;

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "关闭头发系统" -iol "OHair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCloseHair"
			
			rnd_JTShelfButton5;*/
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "渲染工具集" -iol "RTOOL" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/JT/logo/logo02.bmp" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJtRenderTools.mel\"; HbJtRenderTools"
			
			rnd_JTShelfButton6;

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "整理整集参考图片" -iol "CPM" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCopyMapTZ"
			
			rnd_JTShelfButton7;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "高低模树的切换使用" -iol "HML" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbSkReplaceTreeToolsMel"
			
			rnd_JTShelfButton8;*/


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入当前场景的所有摄像机" -iol "getAll" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbImportCamMel"
			
			rnd_JTShelfButton9;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入参考场景" -iol "ITG" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbImportTempGroudMel"
			
			rnd_JTShelfButton11;*/

		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "导入当前场景的所有摄像机" -iol "DeSmooth" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbDeleteSmoothMel"
			
			rnd_JTShelfButton12;*/


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "关掉所有头发" -iol "CHair" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbCloseTheHairSysMel"
			
			rnd_JTShelfButton13;


		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把头发开始祯设置为980" -iol "980" -style "iconOnly" -i1 "commandButton.XPM"
			-c  "HbSetHairStartMel"
			
			rnd_JTShelfButton14;*/

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "转换map贴图" -iol "MAP" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Woodlies/LRmap.mel\"; LRmapUI";
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "创建FG光子图" -iol "FG" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRFGmap.mel\"; LRFGmapUI";
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "刷草的工具" -iol "grass" -style "iconOnly" -i1 "commandButton.XPM" -stp "python"
	  	 -c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbGrassToolLib.py')";

			
		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "把场景替换为有材质版本" -iol "sets" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "HbJTReplaceRfMel"
		*/

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "面片树朝向摄像机" -iol "LookAt" -style "iconOnly" -i1 "commandButton.XPM" -stp "python"
		-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/yyhbJTLookAtCamera.py')";

		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动隐藏看不见的树和房子" -iol "探照灯" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoHideObject.mel\"; HbAutoHideObject";


		/*shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动替换中模和房子" -iol "ATH" -style "iconOnly" -i1 "commandButton.XPM"
	  	-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbAutoReplace.mel\"; HbAutoReplace"
		*/
			
		shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改相机bug" -iol "ReCam" -style "iconOnly" -i1 "commandButton.XPM" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbJtRenderCam.py')";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "树高低模替换" -iol "树" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\";ot_MeshReplace();";

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择能看见的物体" -iol "Select" -style "iconOnly" -i1 "pythonFamily.xpm" -stp "python"
			-c "execfile('//file-cluster/GDC/Resource/Support/Maya/projects/JT/HbSelect.py')";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "透明通道物体操作" -iol "SelT" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRFselect.mel\"; LRselectTUI";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "修改贴图闪动" -iol "Filter" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRfileFilter.mel\"; LRbumpfileUI";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "关闭辉光" -iol "Glow" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "setAttr shaderGlow1.glowType 0;setAttr shaderGlow1.haloType 0;";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除所有渲染层" -iol "删" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRdelAllLayer.mel\"; LRdelAllLayer";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "一键分层工具" -iol "分层" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/PatchPillows/icon/face.bmp" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/CJWRenderlLayersTool.mel\"";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "选择物体创建透明z层" -iol "z层" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/CreatDepthLayerSel.mel\"; CreatDepthLayerSel";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "删除材质（可不删除带透明通道的物体）" -iol "删材质" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/JT/LRshadeclear.mel\"; LRshadeclearUI";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "渲染工具集" -iol "渲" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "otRenderToolsLayout";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "参考相机" -iol "GetCamera" -style "iconOnly" -i1 "commandButton.XPM" 
			-c "source \"zwCameraImportExport.mel\"; zwGetCameraUI";

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "MS单帧检查" -iol "MS" -style "iconOnly" -i1 "commandButton.XPM" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\"; ot_hhMsCamera";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "MS单帧检查(屏渲）" -iol "刷屏" -style "iconOnly" -i1 "commandButton.XPM" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_Tools.mel\"; ot_hhRenderCam()";

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "修正距离原点远的物体渲染速度过慢的问题" -iol "加速" -style "iconOnly" -i1 "commandButton.XPM" 
			-c "ot_Reocc";
		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "自动替换立体值正确的相机" -iol "ReplaceCam" -style "iconOnly" -i1 "commandButton.XPM" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/HHCamReplaceRenderOT.mel\"; HHCamReplaceRenderOT()";
		
		/*shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "witch和ivan渲染慢的时候可以先制作geocache再渲" -iol "Cache" -style "iconOnly" -i1 "commandButton.XPM" 
			-c  "gtRenderGeoCacheTools";
			*/                  

		shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "警察角色身上配件显示" -iol "配件显示" -style "iconOnly" -i1 "//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/icons/Policeman.png" 
			-c  "source \"//file-cluster/GDC/Resource/Support/Maya/projects/OTTO/ot_PolicemanVisibility.mel\"";
//yyDOD2AddEmitter yyDOD2GrayOcean
        
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   
	                


OTTOShelfChanges `optionVar -query "OTTOShelfSelected"`;
}



global proc OTTOShelfChanges(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray OTTO`;
	int $size = size($childArray);

	int $index = 7;

	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible 1 $childArray[$i];
				$index ++;
				shelfLayout -edit -position $childArray[$i] $index OTTO;
			}
			else
			{
				shelfButton -edit -visible 0 $childArray[$i];
			}
		}
	}
	optionVar -stringValue "OTTOShelfSelected" $steps;
}


 global proc ot_set()
 {
	setProject "//file-cluster/gdc/Projects/OTTO/Reference/FTP Download/FTP_Material/Maya";
  }
  global proc ot_Reocc()
  {
	setAttr "mentalrayGlobals.accelerationMethod" 0;
	setAttr "mentalrayGlobals.bspSize" 5;
	setAttr "mentalrayGlobals.bspDepth" 60;
  }
  global proc HHUlock()
  {
	lockNode -l false  Cam;
  }
 ///
