global proc shelf_PollyPocket()
{
/*
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "标签" 
		-label "提示" 
		-command "命令" 
	;
*/
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "解决打开文件或者存盘慢的问题"
		-imageOverlayLabel "慢"
		-image1 (zwGetIcon("arrowDown.xpm"))
		-style "iconOnly"
		-command "source slOptimizeTools.mel;slOptimizeLightLinker;slOptimizeReferenceNode;slOptimizeSpecifiedNode \"groupId\";slOptimizeSpecifiedNode \"groupParts\";slOptimizeSpecifiedNode \"animCurve\";slOptimizeSpecifiedNode \"polyBridgeEdge\";"
	;

	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "换Z:" 
		-label "将Z:替换为file-cluster" 
		-command "slRepairZToFileCluster" 
	;
	
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-imageOverlayLabel "Render" 
		-label "渲染工具集" 
		-command "pyRenderToolsLayout" 
	;
}