global proc shelf_Deadline () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;
 	source "Z:/Netrender/Repository/submission/Maya/Client/DeadlineMayaClient.mel";
 	source "Z:/Netrender/Repository/submission/Maya/Main/SubmitMayaToDeadline.mel";
	python("sys.path.append('Z:/Netrender/Repository/submission/Maya/Main')");
	python("sys.path.append('Z:/Netrender/Repository/scripts/Submission')");
	python("sys.path.append('Z:/Netrender/Repository/submission/MayaVRayDBR/Main')");
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 35
        -height 35
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Submit To Deadline" 
        -enableBackground 0
        -align "center" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "Z:/Netrender/Repository/submission/Maya/Main/Submit.png"
        //-image1 "Z:/Netrender/Repository/submission/Maya/Main/Submit.png"
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "SubmitJobToDeadline" 
        -sourceType "mel" 
        -commandRepeatable 1
        -flat 1
    ;

    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 35
        -height 35
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "Setup VRay DBR With Deadline" 
        -enableBackground 0
        -align "center" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "Z:/Netrender/Repository/submission/MayaVRayDBR/Main\\SubmitVRay.png"
        -image1 "Z:/Netrender/Repository/submission/MayaVRayDBR/Main\\SubmitVRay.png"
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "import SubmitMayaVRayDBRToDeadline\nSubmitMayaVRayDBRToDeadline.SubmitToDeadline()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
