global proc shelf_LR()
{
python("import maya.cmds as cmds");
python("import maya.mel as mel");
//动画
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "commandButton.xpm"
		-imageOverlayLabel "   动画"
		-label "动画工具集"
		-command "maShelfChanges \"Ani\""
	;

//渲染
	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "commandButton.xpm"
		-imageOverlayLabel "   CG"
		-label "CG工具集"
		-command "maShelfChanges \"CG\""
	;

//渲染
	/*shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		-image1 "arrowDown.xpm"
		-imageOverlayLabel "   TD"
		-label "获取指定权限"
		-command "maTDRight"
	;*/

	shelfButton
		-width 34
		-height 34
		-font "smallPlainLabelFont"
		-style "iconOnly"
		//-image1 ""
		-imageOverlayLabel ""
		-label ""
		-command ""
	;



  //动画

		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "导动画工具"	-iol "导" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "slAnimExportImportForSetMainLayout"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "动画库"	-iol "库" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "slAnimPoseLibraryLR"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "表情库"	-iol "Face" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "slAnimPoseLibraryNew"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "auto tangent"	-iol "AT" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"autoTangent.mel\";autoTangentUI();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "DK Anim"	-iol "DK" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "dkAnim"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "找丢失的动画曲线"	-iol "找曲线" -i1 "commandButton.xpm"	-style "iconOnly" -sourceType "python"
			-c "import IDMT.Pluto.FindLostAnimCurve as FLAC\nreload(FLAC)\nFLAC.UI()"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "选中任意角色的某个模型，将会独立显示角色。如果什么都不选时，将显示所有角色"	-iol "单独显示" -i1 "commandButton.xpm"	-style "iconOnly" -stp "python"
			-c "execfile(r'//file-cluster/GDC/Resource/Support/Python/2.6/Lib/site-packages/idmt/maya/MayaTheBee/maAnimShowSelected.py')\nmaAnimShowSelected()"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "替換blocking的參考"	-iol "RR" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"lrRepairReferenceNew.mel\";lrRepairReferenceUI();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "選擇Asset_root組，替換參考并導動畫"	-iol "換" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"lrAnimRepairBlocking.mel\";lrAnimRepairBlocking();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "替換所有舊參考并導動畫"	-iol "全換" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"lrAnimReplaceAnimation.mel\";lrAnimReplaceAnimation();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "选择camera sequence中的shot，拆分文件"	-iol "切" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"lrAnimCameraSequence.mel\";lrAnimCameraSequenceSplitSelected();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "修正或者導入聲音"	-iol "Audio" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "source \"lrAnimRepairSound.mel\";lrAnimRepairSound();"
			;
		shelfButton -docTag "Ani"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "可以bake师傅的胡须，或者旗帜等解算物体"	-iol "解算物体" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "lr_Ani_bakeSelectGeo();"
			;		
  //CG
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "相机Zoom"	-iol "Zoom" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "zoomerate"
			;
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-l "直接打開客戶blocking文件"	-iol "Open" -i1 "commandButton.xpm"	-style "iconOnly"
			-c "lrModelOpenClientFiles"
			;
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "改变场景时间段"	-iol "换时间" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/njEnvMaterialChange.mel\";njEnvMaterialChangeWindow();"
			;	
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "导入渲染用摄像机"	-iol "导相机" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/LORDoftheRINGS/zzjImportRenderCam.mel\";zzjImportRenderCam();"
			;	
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "渲染工具集"	-iol "工具" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/LORDoftheRINGS/zzjRenderToolsCMD.mel\";	nj_RenderTools();"
			;			
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "用线框显示群组的模型"	-iol "群组显" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "nj_Rnd_WireFrameDisplayInstancer(\"b\")"
			;
		shelfButton -docTag "CG"
			-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "为群组角色加上手印"	-iol "手印" -i1 "commandButton.xpm"	-style "iconOnly" 
			-c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/LORDoftheRINGS/zzjSubstituteHead.mel\";	zzjSubstituteHead();"
			;			

maShelfChanges `optionVar -query "maShelfSelected"`;
}

global proc nj_Rnd_WireFrameDisplayInstancer(string $type)
{

	
	string $instancers[]=`ls -type instancer`;
	for ($ins in $instancers)
	{
		if ($type == "h") setAttr ($ins+".levelOfDetail") 0;
		if ($type == "l") setAttr ($ins+".levelOfDetail") 1;
		if ($type == "b") setAttr ($ins+".levelOfDetail") 2;
	}
}

global proc maShelfChanges(string $steps)
{
	string $childArray[] = `shelfLayout -query -childArray LR`;
	int $size = size($childArray);

	int $index = 5;

	for ($i=0; $i<$size; $i++)
	{
		string $docTag = `shelfButton -query -docTag $childArray[$i]`;
		if ($docTag != "")
		{
			if ($docTag == $steps)
			{
				shelfButton -edit -visible 1 $childArray[$i];
				$index ++;
				shelfLayout -edit -position $childArray[$i] $index LR;
			}
			else
			{
				shelfButton -edit -visible 0 $childArray[$i];
			}
		}
	}
	optionVar -stringValue "maShelfChanges" $steps;
}


global proc lr_Ani_bakeSelectGeo()
{
//		隐藏modelPanel
		string $scripts = "";
		string $modelPanels[] = `getPanel -visiblePanels`;
		for ($modelPanel in $modelPanels)
		{
			if (`getPanel -typeOf $modelPanel` == "modelPanel")
			{
				if (!`isolateSelect -query -state $modelPanel`);
				{
					isolateSelect -state true $modelPanel;
					$scripts += "isolateSelect -state false \"" + $modelPanel + "\";\n";
				}
			}
		}
		
		source cyBakeClothMain.mel;
		cyBakeCloth;	


	//		恢复显示	
		if ($scripts != "")
		{
			eval $scripts;
		}
}