global proc shelf_Ninjago()
{
python("import maya.cmds as cmds");
python("import maya.mel as mel");
    shelfButton
        -width 34
        -height 34
        -annotation "Update"
        -label "Update"
        -font "plainLabelFont"
        -imageOverlayLabel "Update"
        -image "vacantCell.png"
        -image1 "vacantCell.png"
        -style "iconOnly"
        -command "zwUpdateShelf \"Ninjago\" \"shelf_Ninjago\""
    ;
//前期
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
        -image1 "wxII\\pre1_wxII.xpm"
        -imageOverlayLabel "       前"
        -label "前期工具集"
        -command "njShelfChanges \"Pre\""
    ;
 
//设置
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
        -image1 "wxII\\set1_wxII.xpm"
        -imageOverlayLabel "       设"
        -label "设置工具集"
        -command "njShelfChanges \"Set\""
    ;

//动画
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
        -image1 "wxII\\ani1_wxII.xpm"
        -imageOverlayLabel "       动画"
        -label "动画工具集"
        -command "njShelfChanges \"Ani\""
    ;

//特效
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
        -image1 "wxII\\eff1_wxII.xpm"
        -imageOverlayLabel "       特效"
        -label "特效工具集"
        -command "njShelfChanges \"Eff\""
    ;

//渲染
    shelfButton
        -width 34
        -height 34
        -font "smallPlainLabelFont"
        -style "iconOnly"
        -image1 "wxII\\rnd1_wxII.xpm"
        -imageOverlayLabel "       渲染"
        -label "渲染工具集"
        -command "njShelfChanges \"Rnd\""
    ;


  //zzj    empty**************************
  //隐藏面板
    shelfButton -width 34 -height 34 -vis 1 -stp "python"
//  -i1 "\wxII\\it.XPM"
     -c "import idmt.maya.Pluto.Utility.EclipseToMaya as etm;reload(etm);etm.main()";



  //zzj               Pre**************************

//      shelfButton -docTag "Pre"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "前期优化面板"   -iol "面板" -i1 "\wxII\\pre_panel_wxII.xpm"   -style "iconOnly"
//          -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_optimize.mel\";wxIIOptimize4PreUI;"
//          ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "设置说明文档"   -iol "Help" -i1 "commandButton.xpm" -style "iconOnly"
            -c "njAnimLoadRiggingHelp;"
            ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -l "前期优化面板" -iol "面板" -i1 "\wxII\\pre_panel_wxII.xpm"   -style "iconOnly"
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/WinxClubII/pre_wxII_optimize.mel\";wxIIOptimize4PreUI;"
            ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "Instance模型组"  -iol "Instance" -i1 "commandButton.xpm" -style "iconOnly"
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/scripts/zzjInstanceModelingGroup.mel\";zzjInstanceModelingGroup;"
            ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "整理参考" -iol "Ref" -i1 "commandButton.xpm"  -style "iconOnly"
            -c "njAnimReplaceRef"
            ;       
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "查找数据库上的镜头连接并替换正确的角色版本"    -iol "网" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "njAnimGetAssetReference"
            ;   
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "删除选择的角色对应的参考" -iol "删" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "njAnimRemoveRef"
            ;   

        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "删除所有的MentalraySubdivApprox"   -iol "MSA" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "string $slMSA[] = `ls -type mentalraySubdivApprox`;if(size($slMSA)) delete $slMSA;"
            ;   
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "断开车贴地"    -iol "Break" -i1 "commandButton.xpm"    -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/RR/RR_detachCarConnection.py')"
            ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "前期直接打开客户Blocking文件（不包含角色道具）"  -iol "Open" -i1 "commandButton.xpm" -style "iconOnly" 
            -c "njModelOpenClientFiles"
            ;
        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "操作选择的参考物体"    -iol "RT" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source referencetools.mel;slReferenceToolsWindow;"
            ;   

        shelfButton -docTag "Pre"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "RoadKill" -iol "RK" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source RoadKill.mel;RoadKill;"
            ;   

//      shelfButton -docTag "Pre"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "创建GeoCache Set"   -iol "Set" -i1 "commandButton.xpm"  -style "iconOnly" 
//          -c "createGeoCacheSet"
//          ;   

  //zzj               Set**************************

        shelfButton -docTag "Set"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "bake选中物体的动画到locator上"  -iol "Bake" -i1 (zwGetIcon("commandButton.xpm"))   -style "iconOnly"
            -c "source \"zzjUtilityTools\";zzjUtilityTools \"bakeAnim\""
            ;


  //zzj               Ani**************************
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "导动画工具"    -iol "导" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "slAnimExportImportForSetMainLayout"
            ;       
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "表情面板" -iol "P-L" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "slAnimPoseLibraryNew"
            ;       
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "找丢失的动画曲线" -iol "找曲线" -i1 "commandButton.xpm"  -style "iconOnly" -sourceType "python"
            -c "import IDMT.Pluto.FindLostAnimCurve as FLAC\nreload(FLAC)\nFLAC.UI()"
            ;
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "Rigging Selecting Tools"  -iol "Rig" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "execfile('//file-cluster/gdc/Resource/Support/Maya/extra/Rigging_Simulation/python/edo/general/edo_EasyCtrlPlaneUI_v1.01.py')"
            ;                   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "动作及pose库" -iol "库" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "slAnimPoseLibraryYD(\"Ninjago\")"
            ;       
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "动作及pose库" -iol "新库" -i1 "commandButton.xpm"    -style "iconOnly" -stp "python"
            -c "import idmt.maya.Pluto.Maya.Ani.AniLib.AnimLibrary as aniLib;reload(aniLib);aniLib.main()"
            ;  
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "IK/FK转换工具"    -iol "IK/FK" -i1 "commandButton.xpm"    -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/RR/AnimIKFKUI.py')"
            ;               
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "切换场景高低模"  -iol "场景" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "njAnimRemoveRef"
            ;   
        popupMenu;
            menuItem -l "高=》低"  -c "njAnimReferenceSwitch \"notex\"";
            menuItem -l "低=》高"  -c "njAnimReferenceSwitch \"tex\"";
            
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "修复不能选择物体的问题"  -iol "Tem" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "slRenderRepaireTemplate;"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "" -iol "Ghost" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "source klrGhosting.mel;klrGhostingUI;"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "替换客户blocking的角色为内部角色" -iol "换" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "njAnimRepairBlocking"
            ;       
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "加载面部选择功能" -iol "SL" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "python(\"import IDMT;import IDMT.twwScript.AnimSelect.WD_LoadScript as WDface;WDface.loadFaceSript('Ninjago')\")"
            ;               
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "修正参考" -iol "RR" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source slRepairReferenceNew.mel;slRepairReferenceUI;"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "" -iol "AT" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source autoTangent.mel;autoTangentUI;"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "EA"   -iol "EA" -i1 "commandButton.xpm"   -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/RR/yyEasyAnimation_01.py')"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "汽车贴地" -iol "车贴地" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "RR_attachCarOnFround"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "先选择车轮控制器，鼠标右键单击，bake或者重置车轮"   -iol "车轮" -i1 "commandButton.xpm"   -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_BakeWheel.py')"
            ;           
        popupMenu -button 1;
            menuItem -l "bake车轮"    -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_BakeWheel.py')\\nnj_BakeWheel('bake')\")";
            menuItem -l "bake履带型车轮" -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_BakeWheel.py')\\nnj_BakeWheel('bake_apronWheel')\")";
            
            menuItem -l "重置车轮"  -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_BakeWheel.py')\\nnj_BakeWheel('reset')\")";
            menuItem -l "重置履带型车轮"   -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_BakeWheel.py')\\nnj_BakeWheel('reset_apronWheel')\")";

        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "可以bake师傅的胡须，或者旗帜等解算物体"    -iol "解算物体" -i1 "commandButton.xpm" -style "iconOnly"
            -c "nj_Ani_bakeSelectGeo"
            ;       
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "先选择师傅的胡须模型，再点这个按钮，bake"   -iol "设胡须" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "execfile('//file-cluster/GDC/Resource/Support/Maya/extra/Rigging_Simulation/python/edo/project/ninjago/edo_bakeMustacheDynCtrl.py')"
            ;           
        
                
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "先选车MIS控制器，再选现贴地地面，最后选要换贴地面"   -iol "换地面" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "execfile('//file-cluster/gdc/Resource/Support/Maya/projects/Ninjago/edo_changeTheCarSnapPlane.py')"
            ;       
            
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "全新的高低模替换，卸载工具"    -iol "高/低" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')"
            ;           
        popupMenu -button 1;
            menuItem -l "高模"                                -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('h')\")";
            menuItem -l "低模"                                -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('l')\")";
            menuItem -l "=============" -c "";
            menuItem -l "Unload Reference"      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('unload')\")";
            menuItem -l "Remove Reference"      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('remove')\")";
            menuItem -l "高亮显示"                      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('highLight')\")";
        
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "表情控制面板显示/影藏开关"    -iol "on/off" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source \"//file-cluster/gdc/Resource/Support/Maya/projects/Ninjago/nj_Ani_UtilityTools.mel\";nj_Ani_UtilityTools_Hide_Deforms();"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "选中任意角色的某个模型，将会独立显示角色。如果什么都不选时，将显示所有角色"    -iol "单独显示" -i1 "commandButton.xpm" -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_Ani_IsolateDisplay.py')"
            ;                   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "动画纠错工具"   -iol "补" -i1 "commandButton.xpm"    -style "iconOnly"
            -c "source \"//file-cluster/gdc/Resource/Support/Maya/projects/Ninjago/nj_Ani_FixBeforeAnim.mel\";nj_Ani_FixBeforeAnim();"
            ;
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "Bake Low Model Proxy Display" -iol "Low Model" -i1 "commandButton.xpm"    -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_Ani_BakeChrAnim.py')"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "exchange to A Model"  -iol "A Model" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source \"//file-cluster/gdc/Resource/Support/Maya/projects/Ninjago/nj_Ani_UtilityTools.mel\";nj_Ani_Exchange_To_A_Model;"
            ;
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "断开车与地面的连接"    -iol "Break" -i1 "commandButton.xpm"    -style "iconOnly" -stp "python"
            -c "execfile('//file-cluster/GDC/Resource/Support/Maya/extra/Rigging_Simulation/python/edo/project/ninjago/edo_breakeSnapCar.py')"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "旧设置角色导动画给新设置角色"   -iol "旧>新" -i1 "commandButton.xpm"  -style "iconOnly"
            -c "njAnimCpoyAnimationWithControls"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "动画checkin前的优化"    -iol "优Checkin" -i1 "commandButton.xpm" -style "iconOnly" -stp "python"
            -c "import idmt.maya.Ninjago.zzjAnimCleanupScene as zzjACS\nreload(zzjACS)"
            ;
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "Head&Shoulder"    -iol "H&S" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "import idmt.maya.Pluto.GdcP2.Ani.Header_Shoulder_Ctrl as hsc;reload(hsc);hsc.main()"
            ;
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "隐藏场景中看不到的物体（选择相机中的物体点击）"  -iol "Hide" -i1 "commandButton.xpm" -style "iconOnly"
            -c "source slSceneViewTool.mel;slSceneViewHideNonSelected;"
            ;   
        shelfButton -docTag "Ani"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "激光枪武器工具"  -iol "Gun" -i1 "YODA\\PlutoGun2.bmp"    -style "iconOnly" -stp "python"
//            -c "import idmt.maya.Pluto.PlutoGun.PlutoGun3 as PlutoGun\nreload(PlutoGun)\nPlutoGun.main()"
			-c "import ninjago.PlutoGun._Main as Main\nreload(Main)\nMain.main()"
            ;
	shelfButton -docTag "Ani"
		-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "找回动画曲线"	-iol "丢动画" -i1 "commandButton.xpm"	-style "iconOnly" -stp "python"
		-c "execfile('//file-cluster/gdc/Resource/Support/Maya/projects/Ninjago2015/nj_2015_retrieval_AnimCurve.py')\nCJW_retrieval_AnimCurve()"
		;

	shelfButton -docTag "Ani"
		-en 1	-m 1	-w 34 -h 34	-font "smallPlainLabelFont"	-ann "传递动画曲线"	-iol "传动画" -i1 "commandButton.xpm"	-style "iconOnly" -stp "python"
		-c "from idmt.maya.Ninjago import trance_animation_testA\nreload(trance_animation_testA)\ntrance_animation_testA.xiong_window()"
		;
  //zzj               Eff**************************


//      shelfButton -docTag "Eff"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "导入SquareFog"  -iol "导入SquareFog" -i1 "commandButton.xpm"  -style "iconOnly"
//          -c "source yuPythonToMel.mel;yuWinxSquareFluidFile()";
    shelfButton -docTag "Eff"
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "使一个模型(或者一部分)变形成另一个指定的模型" 
        -align "center" 
        -labelOffset 0
        -font "smallPlainLabelFont" 
        -imageOverlayLabel "fitVertice" 
        -image "commandButton.xpm" 
        -image1 "commandButton.xpm" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "source \"Z:/Resource/Support/Maya/Import/PPTools/scripts/fitVertices.mel\";\r\nfitVertices;" 
        -sourceType "mel" 
        -actionIsSubstitute 0
    ;

        shelfButton -docTag "Eff"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "选择地面+移动物体"  -iol "痕迹" -i1 "commandButton.png" -style "iconOnly"
            -c "source \"zwNinjagoTrail.mel\"; zwNinjagoTrail;";

  //zzj               Rnd**************************

//      shelfButton -docTag "Rnd"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "右眼"   -iol "右眼" -i1 "pythonFamily.xpm"    -style "iconOnly"
//          ;
//          popupMenu -button 1 Buantime22;
//              menuItem  -parent Buantime22 -l "转右眼工具" -c "yyRightEyeSwith" ;
//              menuItem  -parent Buantime22 -l "本地“补”不改参数" -c "localFix2" ;
//              menuItem  -parent Buantime22 -l "网渲“补”不改参数" -c "netFix2" ;
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "渲染设置" -iol "Render" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "ysTSRendering;"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "Zoom" -iol "Zoom" -i1 "commandButton.xpm" -style "iconOnly" 
            -c "zoomerate;"
            ;               
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "改变场景时间段"  -iol "换时间" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/njEnvMaterialChange.mel\";njEnvMaterialChangeWindow();"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "导入渲染用摄像机" -iol "导相机" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_ImportRenderCam.mel\";nj_ImportRenderCam();"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "720集角色换龙袍"    -iol "换衣服" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_ReplaceCHR720Reference.mel\";nj_ReplaceCHR720Reference();"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "骷髅群组眼球"   -iol "群组眼球" -i1 "commandButton.xpm" -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_RenderSkeletonEyesAlpha.mel\";nj_RenderSkeletonEyesAlpha();"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "要选中原始模型所在的那个大组，才能正常使用此工具创建眼球的R通道" -iol "蛇眼群组" -i1 "commandButton.xpm" -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/rnd_eye4crowd.py')"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "MentalRay渲染出错，点下重置"   -iol "MR" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "slRenderMentalrayNodes"
            ;   
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "渲染前优化"    -iol "补" -i1 "commandButton.xpm"    -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_FixBeforeRendering.mel\";nj_FixBeforeRendering();"
            ;
//      shelfButton -docTag "Rnd"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "全新的GeoCache系统"    -iol "GeoCache" -i1 "commandButton.xpm" -style "iconOnly" 
//          -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_Rnd_GeoCacheBuilder.mel\";nj_Rnd_GeoCacheBuilder();"
//          ;               
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "全新的高低模替换，卸载工具"    -iol "高/低" -i1 "commandButton.xpm"  -style "iconOnly" -stp "python"
            -c "execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')"
            ;   

        popupMenu -button 1;
            menuItem -l "高模"                                -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('h')\")";
            menuItem -l "低模"                                -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('l')\")";
            menuItem -l "RGB"                               -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('a')\")";
            menuItem -l "灯光D版本"                             -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('d')\")";
            menuItem -l "=============" -c "";
            menuItem -l "二级参考整场替换"      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('o')\")";
            menuItem -l "Unload Reference"      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('unload')\")";
            menuItem -l "Remove Reference"      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('remove')\")";
            menuItem -l "高亮显示"                      -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('highLight')\")";




//          menuItem -l "AO"    -c "python(\"execfile('//File-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_SwichBG.py')\\nnj_SwichBG('o')\")";
//          menuItem -l "导入场景"  -c "file -import -type \"mayaAscii\" -options \"v=0\"  -pr -loadReferenceDepth \"all\" \"//file-cluster/GDC/Projects/Ninjago/Project/scenes/sets/City/s059001MegaMonsterAmusementParkExt/master/nj_s059001MegaMonsterAmusementParkExt_h_ms_tex.ma\";";
    
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "渲染工具集"    -iol "工具" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/nj_RenderToolsCMD.mel\"; nj_RenderTools();"
            ;
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "用线框显示群组的模型"   -iol "群组显" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c ""
            ;
        popupMenu;
            menuItem -l "高精"    -c "nj_Rnd_WireFrameDisplayInstancer(\"h\")";
            menuItem -l "粗略"    -c "nj_Rnd_WireFrameDisplayInstancer(\"l\")";
            menuItem -l "盒子"    -c "nj_Rnd_WireFrameDisplayInstancer(\"b\")";
                
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "群组粒子精简"   -iol "群精简" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source \"//file-cluster/GDC/Projects/Ninjago/Ninjago_scratch/Crowd/syx_particle_vis.mel\";"
            ;
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "道具P421001在E0260的颜色"   -iol "P421001" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "njRenderP421001Color"
            ;           
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "改变贴图路径"   -iol "贴图" -i1 "commandButton.xpm"   -style "iconOnly" 
            -c "FileTextureManager"
            ;               
//      shelfButton -docTag "Rnd"
//          -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "上传cache"  -iol "cache" -i1 "commandButton.xpm"    -style "iconOnly" 
//          -command "python (\"try:\\n\\treload(idmt.maya.cache)\\nexcept:\\n\\timport idmt.maya.cache\\nidmt.maya.cache.UploadCacheFileForNinjago()\")";

        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "虫子群组RGB"  -iol "虫RGB" -i1 "commandButton.xpm" -style "iconOnly" 
            -c "njCGBugRGB"
            ;
        shelfButton -docTag "Rnd"
            -en 1   -m 1    -w 34 -h 34 -font "smallPlainLabelFont" -ann "导入Layout相机"   -iol "CAM" -i1 "commandButton.xpm"  -style "iconOnly" 
            -c "source njExportCamTools;njImportCam;"
            ;
        
        shelfButton -docTag "Rnd"
			-en 1 -m 1	-vis 0	-font "smallPlainLabelFont"	-l "Motion Vector Pass" -iol "MVP" -style "iconOnly" -i1 "pythonFamily.xpm" 
			-c "python(\"execfile(r'//file-cluster/gdc/Resource/Support/Maya/projects/\Ninjago/doMotionVectorPassProc.py');doMotionVectorPassProc()\")"	;	         
        shelfButton -docTag "Rnd"
			-en 1	-m 1	-vis 0	-font "smallPlainLabelFont"
			-l "" -iol "Mb/Ma" -style "iconOnly"
			 -i1 "pythonFamily.xpm"
			-ann "Mb2Ma" -stp "python"
			-c "import idmt.maya.DOD.DODIV.Maya.do4_Mb2Ma as dmb2ma\ndmb2ma.do4_Mb2Ma()"
			rnd_sb_mb2ma;
njShelfChanges `optionVar -query "njIIShelfSelected"`;
}


global proc njShelfChanges(string $steps)
{
    string $childArray[] = `shelfLayout -query -childArray Ninjago`;
    int $size = size($childArray);

    int $index = 7;

    for ($i=0; $i<$size; $i++)
    {
        string $docTag = `shelfButton -query -docTag $childArray[$i]`;
        if ($docTag != "")
        {
            if ($docTag == $steps)
            {
                shelfButton -edit -visible 1 $childArray[$i];
                $index ++;
                shelfLayout -edit -position $childArray[$i] $index Ninjago;
            }
            else
            {
                shelfButton -edit -visible 0 $childArray[$i];
            }
        }
    }
    optionVar -stringValue "njIIShelfSelected" $steps;
}

global proc ysTSRendering()
{
    python("import sys");
    python("sys.path.append(\"//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/TTMS\")");
    python("import BD_ysRenderUI as bdrnUI");
    python("reload(bdrnUI)");
    python("bdrnUI.BD_ysRenderUI()");
}

global proc RR_attachCarOnFround()
{
    python("execfile('//file-cluster/GDC/Resource/Support/Maya/extra/Rigging_Simulation/python/edo/project/ninjago/edo_allCarSnap.py')");
    return;
    python("import sys");
    python("sys.path.append(\"//File-cluster/GDC/Resource/Support/Maya/Python/IDMT/RR\")");
    python("import RR_ysAniTools as ANT");
    python("reload(ANT)");
    python("ANT.attachCarOnGround()");
}



global proc nj_Rnd_WireFrameDisplayInstancer(string $type)
{

    
    string $instancers[]=`ls -type instancer`;
    for ($ins in $instancers)
    {
        if ($type == "h") setAttr ($ins+".levelOfDetail") 0;
        if ($type == "l") setAttr ($ins+".levelOfDetail") 1;
        if ($type == "b") setAttr ($ins+".levelOfDetail") 2;
    }
}

//global proc createGeoCacheSet()
//{
//  if (`objExists "GEO_CACHE_SET"`)
//  {
//      delete GEO_CACHE_SET;
//  }
//  sets -name "GEO_CACHE_SET";
//  select -r -ne "GEO_CACHE_SET";  
//}



global proc nj_Ani_bakeSelectGeo()
{
//      隐藏modelPanel
        string $scripts = "";
        string $modelPanels[] = `getPanel -visiblePanels`;
        for ($modelPanel in $modelPanels)
        {
            if (`getPanel -typeOf $modelPanel` == "modelPanel")
            {
                if (!`isolateSelect -query -state $modelPanel`);
                {
                    isolateSelect -state true $modelPanel;
                    $scripts += "isolateSelect -state false \"" + $modelPanel + "\";\n";
                }
            }
        }
        
        source cyBakeClothMain.mel;
        cyBakeCloth;    


    //      恢复显示    
        if ($scripts != "")
        {
            eval $scripts;
        }
}