/// Copyright (C) 2000-2007 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2007/02/26
///
/// Description: 
///


global proc shelf_BenAndIzzy () {
	global string $gBuffStr;
	global string $gBuffStr0;
	global string $gBuffStr1;

	string $user = `getenv USERNAME`;
	$user = `tolower $user`;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "删除物体无用附加属性" 
		-imageOverlayLabel "DelEA" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezDelExtraAttr.mel; ezDelExtraAttr" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "改名前备份物体原命名" 
		-imageOverlayLabel "Name" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezInitialNameModel.mel; ezInitialNameModel" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "检查A模命名" 
		-imageOverlayLabel "A模" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezModelAnCheck.mel; ezModelAnCheck" 
	;


  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "检查表情target的命名规范" 
		-imageOverlayLabel "Target" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezFacialName.mel; ezFacialName" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动替换指定目录下的贴图" 
		-imageOverlayLabel "Texture" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezModelTransTex.mel; ezModelTransTex" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "转贴图格式" 
		-imageOverlayLabel "ImgCvt" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source slImgConverFormat.mel; slImgConverFormat" 
	;

	shelfButton
		-annotation "Separator"
		-enable false
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "角色间导动画(先选择导出动画角色的master，再选择需要导入角色的master)" 
		-imageOverlayLabel "动画" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAnimCopyCurve.mel; ezAnimCopyCurve" 
	;
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "设置表情表达式连接" 
		-imageOverlayLabel "BlendShape" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezImportBlendshape.mel; ezImportBlendshape" 
	;
	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "增加切换高低模显示" 
		-imageOverlayLabel "Display" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAniamationDisplay.mel; ezAniamationDisplay" 
	;


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "根据Master选择角色" 
		-imageOverlayLabel "Sel" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAnimSelMaster.mel; ezAnimSelMaster" 
	;
	
	/*shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "IKFK转换" 
		-imageOverlayLabel "IK/FK" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezIKFKSwitch.mel; ezIKFKSwitch" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "IK（或者FK）时FK（或者IK）会自动对其到IK（或者FK）位置（测试版）" 
		-imageOverlayLabel "I<=>F" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source slIKFKTranslate.mel; slIKFKTranslate" 
	;

	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "角色表情库" 
		-imageOverlayLabel "表情" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source jm_facial2facial_v2.mel; jm_F2F_mainWin" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "动作库" 
		-imageOverlayLabel "动作库" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAnimLib.mel; ezAnimLib" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "角色整体控制" 
		-imageOverlayLabel "角色" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAllCharCon.mel; ezAllCharCon" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "自动替换Reference并导动画" 
		-imageOverlayLabel "Replace" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source slAnimCopyForRef.mel; slAnimCopyForRef" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "导出动画为*.sla文件；同时提供导入功能" 
		-imageOverlayLabel "测试" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source slAnimExportImportForSetMainLayout.mel; slAnimExportImportForSetMainLayout" 
	;
*/
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Ben&Izzy项目动画工具集合" 
		-imageOverlayLabel "AnTools" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source slAnimationToolsMainLayout.mel; slAnimationToolsMainLayout(\"Ben&Izzy\")" 
	;

	shelfButton
		-annotation "Separator"
		-enable false
	;

/*
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "修正mentalrayGlobals" 
		-imageOverlayLabel "MR" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezDelMentalRenderSetting.mel; ezDelMentalRenderSetting" 
	;
*/	

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "渲染分层工具集合" 
		-imageOverlayLabel "RenderTools" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderMainLayout.mel;ezRenderMainLayout" ;
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "面片树场景工具" 
		-imageOverlayLabel "Tree" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderTreeTools.mel; ezRenderTreeTools" 
	;


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "解决个别镜头角色曝光问题" 
		-imageOverlayLabel "曝光" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderExposure.mel; ezRenderExposure" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "隐藏动画用眼睛面片" 
		-imageOverlayLabel "EYES" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderHideEyes.mel; ezRenderHideEyes" 
	;

/*	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "导入fxcloth并替换原模型" 
		-imageOverlayLabel "FxCloth" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderReplaceFxCloth.mel;ezRenderReplaceFxCloth" ;
	;
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "分层工具" 
		-imageOverlayLabel "分层" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAutoCreateRL.mel; ezAutoCreateRL" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "渲染层另存" 
		-imageOverlayLabel "另存" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderLayerScene.mel; ezRenderLayerScene" 
	;


	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "修改hair的层阴影属性" 
		-imageOverlayLabel "hair" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezHairBrowsShadow.mel; ezHairShadowCheck" 
	;

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "运动模糊" 
		-imageOverlayLabel "BLUR" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderBlur2D.mel; ezRenderBlur2D" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "链接" 
		-imageOverlayLabel "重建灯光链接" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezLightingLink.mel;" 
	;


  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "渲染用场景中多镜头切换" 
		-imageOverlayLabel "Cam" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderCam.mel;ezRenderCam" 
	;
*/
  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "角色控制器" 
		-imageOverlayLabel "" 
		-image1 "charCon.xpm"
		-style "iconOnly"
		-command "source IDMT_CharacterControl.mel; IDMT_CharacterControl" 
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "Asset" 
		-imageOverlayLabel "Asset" 
		-image1 "asset.xpm" 
		-style "iconOnly"
		-command "zwAssetFile" 
	;

	shelfButton
		-annotation "Separator"
		-enable false
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "本机补帧工具" 
		-imageOverlayLabel "补帧" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezRenderRepair.mel ;ezRenderRepair"
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "特效工具集" 
		-imageOverlayLabel "Effect" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezEffectTools.mel;ezEffectTools"
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "批量修改文件或图片命名" 
		-imageOverlayLabel "重命名" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source jm_BR_mainWin.mel ;jm_BR_mainWin"
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "批量改文件内物体属性" 
		-imageOverlayLabel "文件" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "kcBatchRun"
	;

  	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "magic工具" 
		-imageOverlayLabel "magic" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezEffectParticleTools.mel;ezEffectParticleTools"
	;
	
  	shelfButton									///07.12.28 by hq
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "设置本地lightmap" 
		-imageOverlayLabel "lightmap" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source hqSetLightmapLocal.mel;hqSetLightmapLocal"
	;

	shelfButton
		-annotation "Separator"
		-enable false
	;

	
	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "分层工具" 
		-imageOverlayLabel "分层" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "source ezAutoCreateRL.mel; ezAutoCreateRL" 
	;
	/*shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "LightEYE" 
		-imageOverlayLabel "Lighteye" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "LightEyesLayer" 
	;*/

	shelfButton
		-enableCommandRepeat 1
		-enable 1
		-width 34
		-height 34
		-manage 1
		-visible 1
		-font "smallPlainLabelFont"
		-label "修正BU动画文件某些角色显示异常" 
		-imageOverlayLabel "Lambert1" 
		-image1 (zwGetIcon("arrowDown.xpm")) 
		-style "iconOnly"
		-command "buAnimLambert1" 
	;

	string $version = `about -version`;
	$version = `match "[0-9]+(\.[0-9]){0,1}" $version`;
	if ((float)$version > 7.0)
	{
    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 34
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "使用步骤：1。选择眼球上的两个定位的edge，使用创建loc；2。选择眼球使用创建层" 
        -align "center" 
        -label "eyes" 
        -labelOffset 0
        -font "tinyBoldLabelFont" 
        -imageOverlayLabel "LightEyes" 
        -image (zwGetIcon("arrowDown.xpm")) 
        -image1 (zwGetIcon("arrowDown.xpm")) 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "print \"囧  请点右键\\n\";" 
        -sourceType "mel" 
        -actionIsSubstitute 0
        -mi "创建Loc" ( "source slRenderLayerEyes.mel;slRenderLayerEyesLoc;" )
        -mi "创建层" ( "source slRenderLayerEyes.mel;slRenderLayerEyes;" )
    ;
	}
}