/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: анип╨Ц
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc shotmovekeys()
{
	if (!`window -exists movekeysWin`)
	{
		window -title "Move keys" -resizeToFitChildren true movekeysWin;
			columnLayout -adjustableColumn true;
				floatFieldGrp -l "frame" -v1 31 shot_frame;
				floatFieldGrp -l "offset" -v1 31 shot_offset;
				button -l "move" -c "movekeysfunc";
		showWindow movekeysWin;
	}
}



//add shot
global proc movekeysfunc()
{
	cycleCheck -e off;
	float $fr = `floatFieldGrp -q -v1 shot_frame`;
	float $of = `floatFieldGrp -q -v1 shot_offset`;
	string $obj[] = `ls`;
	for ($i=0;$i<size($obj);$i++)
	{
		string $anim[] = `listAnimatable $obj[$i]`;
		for ($j=0;$j<size($anim);$j++)
			keyframe -e -includeUpperBound true -relative -option over -time ($fr+":") -timeChange $of $anim[$j];
	}
}