/// Copyright (C) 2000-2007 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2007/03/24
///
/// Description: bratz项目修正因非正常修改权重（没有修改ms的角色权重）引起的变形
///



global proc slBrCopySkinweight()
{
	currentTime -31;
	
	string $sl[]= `ls -sl`;

	if (!`objExists $sl[0]`)
		error "请选择错误物体";
	
	string $buffer[];
	tokenize $sl[0] ":" $buffer;
	string $body = $buffer[size($buffer)-1];
	string $sbody = "skinWeight" + ":" + $body;

	string $master[] = `ls ($buffer[0]+":*MASTER")`;

	string $base = `getBasegroup $sl[0]`;
	string $ref[] = `listConnections $base`;
	string $path = `referenceQuery -f $ref[0]`;
	file -r -gr -ns "skinWeight" $path;
	
	
	string $his[]= `listHistory $sbody`;
	string $sskin[];
	for ($temp in $his)
	{
		if (`nodeType $temp` == "skinCluster") $sskin[size($sskin)]=$temp;
	}
	
	clear $his;
	$his= `listHistory $sl[0]`;
	string $dskin[];
	for ($temp in $his)
	{
		if (`nodeType $temp` == "skinCluster") $dskin[size($dskin)]=$temp;
	}

	setAttr ($master[0]+".translateX")  0;
	setAttr ($master[0]+".translateY")  0;
	setAttr ($master[0]+".translateZ")  0;
	setAttr ($master[0]+".rotateX")  0;
	setAttr ($master[0]+".rotateY")  0;
	setAttr ($master[0]+".rotateZ")  0;

	copySkinWeights -ss  $sskin[0] -ds $dskin[0] -noMirror;

	file -rr -rfn skinWeightRN;
	delete skinWeightRNgroup;
}


