//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slRenderReferenceEditor(string $load,string $rfn)
{
	string $file = `referenceQuery -f $rfn`;
	
	string $referenceFiles[] = `file -q -r`;

	for ($rf in $referenceFiles)
	{
		string $referenceNode = `referenceQuery -rfn $rf`;

		string $buff[];
		int $num = `tokenize $rf "{}" $buff`;
		string $sourceFile = $buff[0];

		if ($sourceFile == $file)
		{
			string $cmd = "file -"+$load+" \""+$referenceNode+"\"";

			print ($cmd+"\n");
		}
	}
}