global proc stMirrorSkinWeights ()
{
	 $win=`window -menuBar true -t "Mirror Skin Weights" msw`;

		menu -label "Help";
			menuItem -label "Help on Mirror Skin Weights..." -command "zjHelpCallback stMirrorSkinWeight";

		columnLayout -adjustableColumn true;
			string $radioGroup = `radioButtonGrp -select 1 -numberOfRadioButtons 3 -label "Mirror Mode" -labelArray3 "XY" "XZ" "YZ" radGrp`;
			button  -al "center" -rs 1 -label "Mirror" -c stMirrorSkinWeightsMain;
	showWindow $win;
}
global proc stMirrorSkinWeightsMain ()
{
	string $shapes[] = `ls -sl -dag -hd 5`;
	string $skinCluster1[] = `listConnections -t skinCluster $shapes[1]`;
	string $skinCluster2[] = `listConnections -t skinCluster $shapes[4]`;
	int $condt =`radioButtonGrp -q -sl radGrp`;
	if ($condt == 1)
	{
		copySkinWeights -ss $skinCluster1[0] -ds $skinCluster2[0] -mm XY -mi;
	}
	if ($condt == 2)
	{
		copySkinWeights -ss $skinCluster1[0] -ds $skinCluster2[0] -mm XZ -mi;
	}
	if ($condt == 3)
	{
		copySkinWeights -ss $skinCluster1[0] -ds $skinCluster2[0] -mm YZ -mi;
	}
}