global proc wsRectifyPolygonNormal()
{
        if(`window -ex "rectifyNormalWindow"` == yes)
		return;
	if(`pluginInfo -q -loaded normalConform` == no)
	        loadPlugin normalConform;
	string $commandStr0="xws_normalConform 0";
	string $commandStr1="xws_normalConform 1";
	string $commandStr2="xws_normalConform 2";
	string $commandStr3="xws_normalConform 3";
	$window = `window -wh 200 180 -t "Rectify Polygon Normal v2.0 (c)2002.9   By xws|IDMT" -menuBar true   rectifyNormalWindow`;
	menuBarLayout;
		menu -label "Help";
		menuItem -label "Help on Apply check normal..." -command "zjHelpCallback wsRectifyPolygonNormal";
	setParent ..;
	columnLayout -columnAlign "center" -rowSpacing 2;
	        
		rowLayout -nc 2 -cw 1 2 -cal 2 "center";
        	        text " ";
                       	$closePolygonBtn = `button -l "Select Close Polygon" -w 200 -h 35 -align "center" -command "source ycClosePolygonCheck.mel;ycClosePolygonCheck" `;
		setParent ..;
		rowLayout -nc 2 -cw 1 2 -cal 2 "center";
        	        text " ";
                       	$checkPolygonBtn = `button -l "Select first  facets" -w 200 -h 35 -align "center" -command $commandStr0 `;
		setParent ..;
		rowLayout -nc 2 -cw 1 2 -cal 2 "center";
		        text " ";
 		        $reverseSelectedBtn = `button -l "Show different Orientation Normal" -w 200 -h 35 -align "center" -c $commandStr1 `;
		setParent ..;
		rowLayout -nc 2 -cw 1 2 -cal 2 "center";
		        text " ";
 		        $reverseSelectedBtn = `button -l "Reverse selected facet normal" -w 200 -h 35 -align "center" -c $commandStr2 `;
                setParent ..;
		rowLayout -nc 2 -cw 1 2 -cal 2 "center";
 		        text " ";
 		        $rectifyNormalBtn = `button -l "Rectify  Normal" -w 200 -h 35 -align "center" -c $commandStr3 `;
		setParent ..;
        setParent ..;
	showWindow $window;

	setFocus $checkPolygonBtn;
}