/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: “¸Í…
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


ycNamePrefixCheck;
global proc ycNamePrefixCheck()
{
	if( `window -exists ycNamePrefixCheck` ) 
	{
		deleteUI ycNamePrefixCheck;
	}
 	window -menuBar true -title "Name Prefix Check" -width 445 -height 200 ycNamePrefixCheck;
		menu -label "Help";
			menuItem -label "Help on Name Prefix Check..." -command "zjHelpCallback ycNamePrefixCheck";
		formLayout formLayout1;
			
			/*text -label "Prefix:" textName;
			optionMenu PrefixName;
				menuItem -label "agentpo";
				menuItem -label "alchemist";
				menuItem -label "allana";
				menuItem -label "allanayoung";
				menuItem -label "animal";
				menuItem -label "arthur";
				menuItem -label "bethpeople";
				menuItem -label "boatpilot";
				menuItem -label "bodkus";
				menuItem -label "caroline";
				menuItem -label "chiefprospector";
				menuItem -label "deeter";
				menuItem -label "earthpeople";
				menuItem -label "ess";
				menuItem -label "giantbaby";
				menuItem -label "giantguard";
				menuItem -label "humansoldier";
				menuItem -label "jac";
				menuItem -label "kingespar";
				menuItem -label "kingmorep";
				menuItem -label "kingoda";
				menuItem -label "kingodawife";
				menuItem -label "kingtor";
				menuItem -label "li";
				menuItem -label "nanny";
				menuItem -label "ragis";
				menuItem -label "ragisyoung";
				menuItem -label "rebelguard";
				menuItem -label "sailor";
				menuItem -label "shepway";
				menuItem -label "simon";
				menuItem -label "simonyoung";
				menuItem -label "templedancer";
				menuItem -label "templedrummer";
				menuItem -label "vela";
				menuItem -label "wirrel";*/
			textFieldGrp -adjustableColumn 2 -columnWidth2 60 200 -label "Prefix:" -enable 1 PrefixName;
			
			separator -style "in" Line1;
			textScrollList 
				-allowMultiSelection	true			//Specify multi or single selection mode. 
				-selectCommand		"SelectObject"
				-doubleClickCommand	"RemoveObjectName"	//executed when an item is double clicked. 
				ObjectList;
	
			separator -style "in" Line2;
			
			string $button1 = `button  -label "Check"		-command	"CheckObject"`;
			string $button2 = `button  -label "Rename Prefix"	-command	"RenamePrefix;"`;
			string $button3 = `button  -label "Remove"		-command	"RemoveObjectName"`;
			string $button4 = `button  -label "Close"		-command	"deleteUI ycNamePrefixCheck;"`;
		
		formLayout -edit
			-attachForm	PrefixName	"top"	5	
			-attachForm	PrefixName	"left"	5	
			-attachForm	PrefixName	"right"	60

			-attachControl	Line1		top	5	PrefixName
			-attachForm	Line1		right	0 
			-attachForm	Line1		left	0

			-attachControl	ObjectList	"top"	5	Line1
			-attachForm	ObjectList	"left"	5
			-attachForm	ObjectList	"right"	5	
			-attachControl	ObjectList	"bottom"	5	Line2
			    
			-attachForm	Line2		left		0
			-attachForm	Line2		right		0
			-attachForm	Line2		bottom	30	
			
			-attachForm	$button1	"left"		5
			-attachForm	$button1	"bottom"	5
			-attachPosition	$button1	"right"		5	25
			
			-attachControl	$button2	"left"		5	$button1
			-attachForm	$button2	"bottom"	5
			-attachPosition	$button2	"right"		5	50

			-attachControl	$button3	"left"		5	$button2
			-attachForm	$button3	"bottom"	5
			-attachPosition	$button3	"right"		5	75

			-attachControl	$button4	"left"		5	$button3
			-attachForm	$button4	"bottom"	5
			-attachForm	$button4	"right"		5
		formLayout1;
	showWindow;
}

global proc CheckObject()
{
	select -cl;
	string $ObjectShapeList[]=`ls -g`;
	string $ObjectList[]=`listRelatives -p $ObjectShapeList`;
	textScrollList -edit -removeAll ObjectList;
//	string $OptionMenuPrefix=`optionMenu -q -v PrefixName`;
	string $OptionMenuPrefix=`textFieldGrp -q -text PrefixName`;
	if (size($ObjectList)==0)
	{
		warning "Item is empty!";
		return;
	}
	else
	{
		for ($i=0;$i<size($ObjectList);$i++)
		{
			string $NameBuffer[];
			int $NameBufferSize=`tokenize $ObjectList[$i] "_" $NameBuffer`;
			if ($NameBuffer[0]!=$OptionMenuPrefix)
			{
				textScrollList -edit -append $ObjectList[$i] ObjectList;
			}
		}
	}
}

global proc RemoveObjectName()
{
	string $SelFile[] = `textScrollList -query -selectItem ObjectList`;
	for ($item in $SelFile )
	{
		textScrollList -edit -removeItem $item ObjectList;
	}
}

global proc SelectObject()
{
	string $SelFile[] = `textScrollList -query -selectItem ObjectList`;
	select -cl;
	for ($i=0;$i<size($SelFile);$i++)
	{
		select -add $SelFile[$i];
	}
}

global proc RenamePrefix()
{
	string $AllItems[]=`textScrollList -query -allItems ObjectList`;
//	string $OptionMenuPrefix=`optionMenu -q -v PrefixName`;
	string $OptionMenuPrefix=`textFieldGrp -q -text PrefixName`;
	if ($OptionMenuPrefix=="")
	{
		warning "Prefix can't empty!";
		return;
	}
	for ($i=0;$i<size($AllItems);$i++)
	{
		string $ItemBuffer[];
		int $ItemBufferSize=`tokenize $AllItems[$i] "_" $ItemBuffer`;
		string $NewPrefixName;
		if (size($ItemBuffer)>1)
		{
			$NewPrefixName=$OptionMenuPrefix;
			for ($j=1;$j<size($ItemBuffer);$j++)
			{
				$NewPrefixName=$NewPrefixName+"_"+$ItemBuffer[$j];
			}
		}
		else
		{
			$NewPrefixName=$OptionMenuPrefix;
		}
		rename $AllItems[$i] $NewPrefixName;
		textScrollList -edit -removeItem $AllItems[$i] ObjectList;
	}
}