global proc yuPartCombine_separateTool()
{

	if(`window -exists yuPartCombine_separateUI`)
		deleteUI yuPartCombine_separateUI;
	window -title "Combine Separate Particle Tool"
	       -width 200 -height 74  yuPartCombine_separateUI;
	//scrollLayout  -w 200;
	columnLayout -adjustableColumn true -cw 160;

	button -l "Combine Particle" -c zjComParticle;
	button -l "Separate Particle" -c "yuPartTool()";
	button -l "Follow Locator Move" -c "source yuCrtParticleLoc.mel;yuCrtParticleLoc()";


	showWindow yuPartCombine_separateUI;
}

global proc yuPartTool()
{
    python("import sys");
    python("sys.path.append(\"//idmt-filer/Support/Maya/Python/IDMT/yfsScripts\")");
    python("from yuSeparatePartCmd import *");
    python("separateCmd()");
}