//////////////////////////////////////////////////////////
//
//	Script Name: do4_lyCam_export
//	Author: zhangben
//	Created: 2013.11.19
//
//	Description:用于maya批处理，bake镜头文件里的对应摄像机，并导出。
//					
//////////////////////////////////////////////////////////


global proc zbLyCamExp()
{
    string $fileNameStr = `file -q -sn -shn`;
    string $fnArray[] = stringToStringArray($fileNameStr,"_");
    
    string $shotCam = "cam_"+ $fnArray[1] + "_" + $fnArray[2];
    
    string $allStereoCame[] = `ls -type "stereoRigTransform"`;
    string $bakedCam;
    string $eachCam;
    for ($eachCam in $allStereoCame)
    {
        if (`match  $shotCam $eachCam` == $shotCam)
           {
               select -r $eachCam;
               source "zwCameraImportExport.mel";
               zwBakeCamera;
               string $sel[] = `ls -sl`;
               $bakedCam = $sel[0];
           }
    }
    
    string $tutleNode[] = `ls "Turtle*"`;
    for ($eachTN in $tutleNode)
    {
	    lockNode -l 0 $eachTN;
	    delete $eachTN;
     }
   


    string $ly_camExportPath = "//file-cluster/GDC/Projects/MiniTiger/MiniTiger_Scratch/Layout/cam_export/";
    
    string $episode = "episode_" + $fnArray[1];
    
    string $ep_cam_dir = $ly_camExportPath + $episode;
    
    sysFile -makeDir $ep_cam_dir;
    
    string $camFileName = $fnArray[0] +"_" + $fnArray[1] +"_" + $fnArray[2] + "_cam.mb";
    
    string $finalCamFileFullName = $ep_cam_dir +"/"+ $camFileName;
    select -r $bakedCam;
    file -force -options "v=0" -typ "mayaBinary" -pr -es $finalCamFileFullName;
    print ("+++++Camera is exported+++++TO:"  + $ep_cam_dir) ;
}
