/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zjAddAnnotation()
{
	displayColor -dormant "annotationShape" 17;
	string $sl[] = `ls -sl -tr`;
	for ($item in $sl)
	{
		select -r $item;
		float $pos[]=`xform -q -ws -t`;
		string $buffer[];
		clear $buffer;
		tokenize $sl[0] "_" $buffer;
		$name = $buffer[0];
		string $an = `annotate -tx $name -p $pos[0] ($pos[1]+15) $pos[2]`;
		string $obj = getTransform($an);
		parent $obj $item;
	}
}