/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


proc WriteSwitches(int $fileId, string $sw[], int $type)
{
	string $in;

	for ($i=0; $i<size($sw); $i++)
	{
		string $con[] = `ls ($sw[$i] + ".input[*].inShape")`;
		for ($j=0; $j<size($con); $j++)
		{
			string $source[] = `listConnections -source true -destination false ($sw[$i] + ".input[" + $j + "].inShape")`;
			if (`objExists $source[0]`)
			{
				string $getshape[] = getShapes($source[0]);
				if ($type == 3)
					$in = "].inTriple";
				if ($type == 2)
					$in = "].inDouble";
				if ($type == 1)
					$in = "].inSingle";
				string $dest[] = `listConnections -source true -destination false -plugs true ($sw[$i] + ".input[" + $j + $in)`;
				if(`objExists $getshape[0]`&&`objExists $dest[0]`)
					fprint $fileId ($sw[$i] + " " + $getshape[0] + " " + $dest[0] + "\n");
			}
		}
	}
}

global proc zjAMOutput_Switches(string $folder)
{
	string $file = $folder + "tmpswitch.txt";
	sysFile -delete $file;
	int $fileId = `fopen $file a`;
	if ($fileId == 0)
		error("Fail to open " + $file);

	string $tripleSw[] = `ls -type tripleShadingSwitch`;
	if (size($tripleSw))
		WriteSwitches $fileId $tripleSw 3;
	string $douSw[] = `ls -type doubleShadingSwitch`;
	if (size($douSw))
		WriteSwitches $fileId $douSw 2;
	string $sinSw[] = `ls -type singleShadingSwitch`;
	if (size($sinSw))
		WriteSwitches $fileId $sinSw 1;

	fclose $fileId;
}