/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zjHelpCallback(string $scriptname)
{
	string $path, $buf[];

	string $str = `getenv "MAYA_SCRIPT_PATH"`;
	tokenize $str ";" $buf;
	for ($str in $buf)
	{
		$str = substituteAllString($str, "\\", "/");
		$str = `substitute "/$" $str ""`;
		if (zwHelpCallbackProc(`substitute "[^/]+$" $str "docs"` + "/" + $scriptname))
		{
			return;
		}
		if (zwHelpCallbackProc(`substitute "[^/]+$" $str "docs"` + "/" + $scriptname + ".mht"))
		{
			return;
		}
		if (zwHelpCallbackProc(`substitute "[^/]+/[^/]+$" $str "docs"` + "/" + $scriptname))
		{
			return;
		}
		if (zwHelpCallbackProc(`substitute "[^/]+/[^/]+$" $str "docs"` + "/" + $scriptname + ".mht"))
		{
			return;
		}
	}
}

global proc int zwHelpCallbackProc(string $path)
{
	if (!`filetest -f $path`)
	{
		return false;
	}

	$path = substituteAllString($path, "/", "\\");
	system ("load " + $path);

	return true;
}