
global proc zjLineofsight ()
{
	string $sel[] = `ls -sl`;
	if (`size($sel)`!=2)
		warning "请先选择2个点";
	string $buf[];
	clear $buf;
	tokenize $sel[0] "." $buf;
	string $obj = $buf[0];
	float $pos1[] = `xform -q -ws -t $sel[0]`;
	float $pos2[] = `xform -q -ws -t $sel[1]`;
	string $cuv = `curve -d 1 -p $pos1[0] $pos1[1] $pos1[2] -p $pos2[0] $pos2[1] $pos2[2] -k 0 -k 1`;
        xform -ws -piv $pos1[0] $pos1[1] $pos1[2] $cuv;
	parentConstraint -mo -weight 1 $obj $cuv;
}
