global proc zjNormalmap()
{
	setAttr -type "string" defaultRenderGlobals.currentRenderer "mentalRay";

	string $shadinggrp[] = `ls -type shadingEngine`;
	string $mt[];
	clear $mt;
	for ($eng in $shadinggrp)
	{
		string $cons[] = `listConnections -s 1 -d 0 ($eng+".surfaceShader")`;
		$cons = stringArrayRemoveDuplicates($cons);
		if (`objExists $cons[0]`&&`nodeType $cons[0]` == "lambert")
			$mt[size($mt)] = $cons[0];
	}
	string $mib = `mrCreateCustomNode -asTexture "" mib_amb_occlusion`;
	setAttr ($mib+".output_mode") 3;
	for ($item in $mt)
	{
		setAttr ($item + ".diffuse") 0.5;
		setAttr ($item + ".color") -type double3 0.8 0.8 0.8;
		catch(`connectAttr -f ($mib+".outValue") ($item+".incandescence")`);
	}
	catch(`setAttr "miDefaultOptions.maxSamples" 2`);
	catch(`setAttr "miDefaultOptions.contrastR" 0.02`);
	catch(`setAttr "miDefaultOptions.contrastG" 0.02`);
	catch(`setAttr "miDefaultOptions.contrastB" 0.02`);
	catch(`setAttr "miDefaultOptions.contrastA" 0.02`);
	catch(`setAttr miDefaultOptions.filter 1`);
	catch(`setAttr "miDefaultOptions.maxReflectionRays" 1`);
	catch(`setAttr "miDefaultOptions.maxRefractionRays" 1`);
	catch(`setAttr "miDefaultOptions.maxRayDepth" 1`);
}