/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zjObjectAddAttr(string $object, string $attr, string $attrtype, float $df, float $min, float $max)
{
	if (!`attributeExists $attr $object`)
	{
		addAttr -longName $attr -attributeType $attrtype -defaultValue $df -minValue $min -maxValue $max -keyable true $object;

		print("Add attribute \"" + $attr + "\" to " + $object + "\n");
	}
}