/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zjResetJoints()
{
/*	string $joints[] = `ls -type joint`;
	for ($item in $joints)
	{
		catch(`setAttr ($item + ".rx") 0`);
		catch(`setAttr ($item + ".ry") 0`);
		catch(`setAttr ($item + ".rz") 0`);
		catch(`setAttr ($item + ".sx") 1`);
		catch(`setAttr ($item + ".sy") 1`);
		catch(`setAttr ($item + ".sz") 1`);
	}
*/
/*
	string $ctrls[] = `ls -sl -tr`;
	for ($item in $ctrls)
	{
		catch(`setAttr ($item + ".tx") 0`);
		catch(`setAttr ($item + ".ty") 0`);
		catch(`setAttr ($item + ".tz") 0`);
		catch(`setAttr ($item + ".rx") 0`);
		catch(`setAttr ($item + ".ry") 0`);
		catch(`setAttr ($item + ".rz") 0`);
	}
*/
	string $attrs[] = {"tx", "ty", "tz", "rx", "ry", "rz"};
	string $ctrls[] = `ls -sl -tr`;
	for ($item in $ctrls)
	{
		for ($attr in $attrs)
		{
			if (!`getAttr -lock ($item + "." + $attr)`)
			{
				string $all[] = `listConnections -destination false ($item + "." + $attr)`;
				string $key[] = `listConnections -destination false -type "animCurve" ($item + "." + $attr)`;
				if (size($all) == size($key))
				{
					catch(`setAttr ($item + "." + $attr) 0`);
				}
			}
		}
	}
}