//About Goomoo Utilities Copyright(C) 2002/05/01-2002/07/15 China

global proc zjsAbout()
{	;	}	//do nothing
global proc zjsAboutUI()
{
	if(`window -ex zjsAboutWindow`) deleteUI zjsAboutWindow;
	window -t "About Goomoo Utilities" -w 320 -h 120 zjsAboutWindow;
	columnLayout -adj true;
	text -label "\nGoomoo Utilities V0.63 English Version\nCopyright Goomoo Studio 2002/07/15\nAuthor: Goomoo (Wuhan,HuBei,China)\nHomepage: http://goomoo.diy.163.com\nEMail: zengjinsong@263.net\nzjs3d@hotmail.com\n";
	showWindow zjsAboutWindow;
}

global proc zjsNotes()
{	if(`window -ex zjsNotesWindow`) deleteUI zjsNotesWindow;
	window -t "IMPORTANT! PLZ READ FIRST" zjsNotesWindow;
	columnLayout -adj 1;
	text -l "\nDo not do any other operation except navigating the views before \nyou decide your parameters and close the parameters-adjust window, \nor the result is unpredictable(Except the items that marked #).\n";
	showWindow zjsNotesWindow;
}
