/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 
///
/// Description: 
///

//set user_defined attribute 
proc gp_setAttr(string $obj,int $level) 
{
	string $lS[] = `listAttr -userDefined -string subdiv $obj`;

	if (size($lS) == 0)   
	{
		addAttr -keyable true -longName subdiv -attributeType long  -min 0 -max 10 -defaultValue 2 $obj;
		string $var = $obj+".subdiv";
		setAttr $var $level $obj;
	}
	else if (size($lS) == 1)
	{
		deleteAttr ($obj+".subdiv");
		addAttr -keyable true -ln subdiv -at long  -min 0 -max 10 -dv 2 $obj;
		string $var = $obj+".subdiv";
		setAttr $var $level $obj;
	}
	print "\n";

}

global proc zjSetDefaultSubdiv()
{
	string $gp[] = `ls -tr `;
	for ($item in $gp)
	{
		if (`objExists ($item + ".subdiv")`)
		{
			gp_setAttr($item,1);
		}
	}

}

