global proc zjsAddToMainMenu()
{
	string $allMenu[] = `lsUI -m`;
	for ($i=0;$i<size($allMenu);$i++) 
	{
	    string $tbName = $allMenu[$i];
	    //print $tbName;
	    if("GoomooUtilities" == $tbName)
	       {
	           deleteUI -m $tbName;
	       }
	}
	
	menu -label "Goomoo Utilities" -tearOff true -p MayaWindow "GoomooUtilities";
	//important notes
	menuItem -d 1; 
	menuItem -l "¡ïIMPROTANT¡ïPLZ READ FIRST¡ï" -c "zjsNotes();";
	menuItem -d 1;
	//create curves
	menuItem -l "Sin Curve..." -i "sinCurve.bmp" -c "zjsSinCurveUI();";
	menuItem -l "2D Noise Curve..." -i "2dNoise.bmp" -c "zjs2DNoiseCurveUI();";
	menuItem -l "3D Noise Curve..." -i "3dNoise.bmp" -c "zjs3DNoiseCurveUI();";
	menuItem -l "Zigzag Curve..." -i "ZCurve.bmp" -c "zjsZCurveUI();";
	menuItem -l "NGon..." -i "NGon.bmp" -c "zjsNGonUI();";
	menuItem -l "Spiral..." -i "spiral.bmp" -c "zjsSpiralUI();";
	menuItem -l "Snail..." -i "snail.bmp" -c "zjsSnailCurveUI();";
	menuItem -l "Spiral Along Curve..." -i "spiralAlngCurve.bmp" -c "zjsSpiralAlongCurveUI();";
	menuItem -l "Fillet Rectangle..." -i "filletRect.bmp" -c "zjsFilletRectUI();";
	menuItem -l "Lane Curve..." -i "laneCurve.bmp" -c "zjsLaneCurveUI();";
	menuItem -l "Star..." -i "star.bmp" -c "zjsStarUI();";
	menuItem -l "Gear..." -i "gear.bmp" -c "zjsGearUI();";
	menuItem -d 1;
	//create objects
	menuItem -l "Create Pipe..." -i "pipe.bmp" -c "zjsPipeUI();";
	menuItem -l "Create BallStick..." -i "ballStick.bmp" -c "zjsBallStickUI();";
	menuItem -l "Create Wall..." -i "wall.bmp" -c "zjsWallUI();";
	menuItem -d 1;
	//duplicator
	menuItem -l "Duplicate Along Curve..." -i "dupAlngCurve.bmp" -c "zjsDupAlgCurveUI();";
	menuItem -l "Advance Duplicate Along Curve" -i "advDupAlngCurve.bmp" -c "zjsDupAlngCurveAdvUI();";
	menuItem -l "Duplicate to Polygon Vertices..." -c "zjsDupToPlgVtxUI();";
	menuItem -d 1;
	//curves edit
	menuItem -l "Fillet CV..." -i "guFilletCV.bmp" -c "zjsFilletCVUI();";
	menuItem -l "Sharpen CV..." -i "guSharpenCV.bmp" -c "zjsSharpenCVUI();";
	menuItem -l "Curves Booleans..." -i "curvesBools.bmp" -c "zjsCurvesBoolUI();";
	menuItem -d 1;
	//polygon edit
	menuItem -l "Extrude Polygon Facet Along Curve..." -i "xtrudFacetsAlngCurve.bmp" -c "zjsXtrudAlngCurveUI();";
	menuItem -l "Random Extrude..." -i "greeble.bmp" -c "zjsGreebleUI();";
	menuItem -l "Polygon Smooth Proxy..." -i "smoothProxy.bmp" -c "zjsPolygonSmoothProxyUI();";
	menuItem -d 1;
	//object edit
	menuItem -l "# Randomize..." -i "guNoise.bmp" -c "zjsNoiseUI();";
	menuItem -d 1;
	//animation
	menuItem -l "# Camera Switch" -sm 1 -to 1;
	menuItem -l "Create Camera Switch..." -c "zjsCameraSwitchUI();";
	menuItem -l "Delete Switching Cameras" -c "zjsDeleteSwitchCameras();";
	setParent -menu ..;
	menuItem -l "# Locate DOF" -c "zjsLocateDOF();";
	menuItem -d 1;
	//rendering
	menuItem -l "# Double-Sided Shader" -i "guDblSidedShader.bmp" -c "zjsDblSidedShader();";
	menuItem -l "# Toon Shader..." -i "guToonShader.bmp" -c "zjsCreateToonShaderUI()";
	menuItem -l "# Camera Switch" -sm 1 -to 1;
	menuItem -l "Object Light..." -i "guObjLight.bmp" -c "zjsObjectLightUI();";
	menuItem -l "Delete Light Objects" -c "zjsDelObjLights();";
	setParent -menu ..;
	menuItem -l "File Texture Package..." -c "zjsImagesPackager();";
	menuItem -d 1;
	//about Goomoo Utilities
	menuItem -l "About Goomoo Utilities..." -c "zjsAboutUI();";
}
zjsDefinedProc();
zjsAbout();
zjsCreateCurve();
zjsObject();
zjsDuplicator();
zjsEditCurve();
zjsEditPolygon();
zjsAnimation();
zjsRendering();
