/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ’‘÷æΩ‹
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zjSnapshotOption()
{
	if(!`window -exists snapshotWin`)
	{
		int $snapshotSize = 64, $snapshotOrnam = 0, $snapshotGrid = 0;
		int $snapshotSave = `optionVar -query "snapshotSave"`;
		if (`optionVar -exists "snapshotSize"`)
		{
			$snapshotSize = `optionVar -query "snapshotSize"`;
			$snapshotOrnam = `optionVar -query "snapshotOrnam"`;
			$snapshotGrid = `optionVar -query "snapshotGrid"`;
		}
		else
		{
			optionVar -intValue "snapshotSize" $snapshotSize;
			optionVar -intValue "snapshotOrnam" $snapshotOrnam;
			optionVar -intValue "snapshotGrid" $snapshotGrid;
		}

		window -title "Snapshot" -width 300 -height 200 snapshotWin;
    		columnLayout -adjustableColumn true;
			menuBarLayout;
				menu -label "Help";
					menuItem -label "Help on Snapshot..." -command "zjHelpCallback zjSnapshotOption";
				setParent ..;
			formLayout formLayout1;
				checkBox -visible false -label "Create When Save" snapshotSave;
				separator -visible false separator1;
				optionMenuGrp -label "Size:" -columnWidth 1 40 optionMenuGrp1;
					menuItem -label "64";
					menuItem -label "128";
				checkBox -label "Grid" snapshotGrid;
				checkBox -label "World Axis" snapshotOrnam;
				button -label "Snapshot" -command "NewSaveFilewithIcon" ok;
				button -label "Close" -command "deleteUI snapshotWin" Cancel;

			formLayout -edit
				-attachForm	snapshotSave	"top"		10
				-attachForm	snapshotSave	"left"		100
				-attachNone	snapshotSave	"bottom"
				-attachNone	snapshotSave	"right"

				-attachControl	separator1	"top"		10	snapshotSave
				-attachForm	separator1	"left"		0
				-attachNone	separator1	"bottom"
				-attachForm	separator1	"right"		0

				-attachControl	optionMenuGrp1	"top"		10	separator1
				-attachForm	optionMenuGrp1	"left"		100
				-attachNone	optionMenuGrp1	"bottom"
				-attachNone	optionMenuGrp1	"right"

				-attachControl	snapshotGrid	"top"		10	optionMenuGrp1
				-attachForm	snapshotGrid	"left"		100
				-attachNone	snapshotGrid	"bottom"
				-attachNone	snapshotGrid	"right"

				-attachControl	snapshotOrnam	"top"		10	snapshotGrid
				-attachForm	snapshotOrnam	"left"		100
				-attachNone	snapshotOrnam	"bottom"
				-attachNone	snapshotOrnam	"right"

				-attachForm	ok		"left"		5
				-attachControl	ok		"top"		5	snapshotOrnam
				-attachPosition	ok		"right"		5	50

				-attachControl	Cancel		"left"		5	ok
				-attachControl	Cancel		"top"		5	snapshotOrnam
				-attachForm	Cancel		"right"		5
			formLayout1;

			checkBox -edit -value $snapshotSave -changeCommand "snapshotOptionVar" snapshotSave;
			optionMenuGrp -edit -value $snapshotSize -changeCommand "snapshotOptionVar" optionMenuGrp1;
			checkBox -edit -value $snapshotGrid -changeCommand "snapshotOptionVar" snapshotGrid;
			checkBox -edit -value $snapshotOrnam -changeCommand "snapshotOptionVar" snapshotOrnam;
	}
	showWindow snapshotWin;
}

global proc snapshotOptionVar()
{
	setParent snapshotWin;
	int $snapshotSize = (int)`optionMenuGrp -query -value optionMenuGrp1`;
	menuItem -edit -label ("Snapshot (" + $snapshotSize + "°¡" + $snapshotSize + ")") snapshotMenu;
	optionVar -intValue "snapshotSave" `checkBox -query -value snapshotSave`;
	optionVar -intValue "snapshotSize" $snapshotSize;
	optionVar -intValue "snapshotGrid" `checkBox -query -value snapshotGrid`;
	optionVar -intValue "snapshotOrnam" `checkBox -query -value snapshotOrnam`;
}
