/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwAssignMatte()
{
	string $sceneName = `file -query -sceneName`;
	sysFile -delete $sceneName;

	if (!`objExists "lambertMatte"`)
	{
		string $lambertMatte = `shadingNode -asShader lambert`;
		rename $lambertMatte "lambertMatte";
		setAttr lambertMatte.matteOpacityMode 0;
		sets -renderable true -noSurfaceShader true -empty -name lambertMatteSG;
		connectAttr -force lambertMatte.outColor lambertMatteSG.surfaceShader;
	}
	select -clear;
	
	string $file = `internalVar -userTmpDir` + "exporMatte.txt";
	int $fileId = `fopen $file "r"`;
	if ($fileId == 0)
		return;
	while ( !`feof $fileId` )
	{
		string $obj = strip(`fgetline $fileId`);
		if (`objExists $obj`)
			select -add $obj;
	}
	fclose $fileId;
	
	string $SG[] = `listConnections lambertMatte.outColor`;
	sets -edit -forceElement $SG[0];
	file -save;
}