/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwCameraReference(string $path)
{
	string $buf[];

	zwImportModule("idmt.maya.path", true);
	$path = `python ("idmt.maya.path.GetDollarPath(r'" + $path + "')")`;

	string $namespace = "CAM";
	int $i;
	for ($i=0; ; $i++)
	{
		if ($i != 0)
		{
			$namespace = "CAM" + $i;
		}
		$buf = `ls $namespace ($namespace + "_*")`;
		if (!size($buf))
		{
			break;
		}
	}

	file -ignoreVersion -reference -groupReference -groupName $namespace -renamingPrefix $namespace $path; 
	$buf = `listRelatives -children $namespace`;
	if (size($buf) == 1)
	{
		ungroup $namespace;
	}
	else
	{
		setAttr ($namespace + ".visibility") false;

		$buf = {"translateX", "translateY", "translateZ", "rotateX", "rotateY", "rotateZ", "scaleX", "scaleY", "scaleZ"};
		for ($attr in $buf)
		{
			setAttr -keyable false -lock true ($namespace + "." + $attr);
		}
	}
}