global proc zwCheckinCalimeroLayout(string $path)
{
	if (catch(`zwCheckinCalimeroLayoutProc $path`))
	{
		quit -force -exitCode 99;
	}
}

global proc zwCheckinCalimeroLayoutProc(string $path)
{
	eval "source \"zwCameraImportExport.mel\"";

//	file -force -open $path;

	string $filename = `match "[^\\/]+$" $path`;
	string $episode = `match "_ep[0-9]+_" $filename`;
	$episode = `match "[0-9]+" $episode`;
	string $shot = `match "_sh[0-9]+_" $filename`;
	$shot = `match "[0-9]+" $shot`;

	string $temp = `internalVar -userTmpDir` + "cl_" + $episode + "_" + $shot + "_ly_001.ma";
	sysFile -delete $temp;
	sysFile -copy $temp $path;
	file -rename $temp;

//	rename ("sh" + $shot) ("cam_" + $episode + "_" + $shot);
//	string $buf[] = `listRelatives -shapes ("cam_" + $episode + "_" + $shot)`;
//	rename $buf[0] ("cam_" + $episode + "_" + $shot + "Shape");
//	select ("cam_" + $episode + "_" + $shot);
//	zwBakeCamera;
//	zwCheckinCamera;
//
//	file -force -prompt false -save;
//
//	idmtFile -edit -modified $path $temp;

	putenv "USERNAMExxx" "hibee";
	if (!`idmtProject -checkin -description ""`)
	{
		quit -force -exitCode 99;
	}

	sysFile -delete $temp;
}