/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 黄仲维
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwCheckin()
{
	string $sceneName = `file -query -sceneName`;
	$sceneName = `match "[^/\\]+$" $sceneName`;

	//if (`match "_TXRND[._]" $sceneName` != "" || `match "_TXRNDC[._]" $sceneName` != "")
	//{
	//	confirmDialog -message "请查看是否使用了最新模型" -button "OK";
	//}

	string $project = zwGetProject($sceneName);
	string $mode = zwGetMode($sceneName);
	float $pluginVer = `zwLoadPlugin "idmtCmd"`;
	//if (`match "^tf_l" (tolower($sceneName))` != "" && $mode == "rigging" && $pluginVer < 210)
	//{
	//	confirmDialog -message "Checkin工具刚做了一个的修正，需要重启maya才生效" -button "OK";
	//	return;
	//}
	if ($project == "XiaoWangZi")
	{
		confirmDialog -message "暂时不支持XiaoWangZi项目" -button "OK";
		return;
	}

	eval "source zwCheckinPreMel.mel";
	eval "source zjCheckinClean.mel";
	eval "source zwCheckinPostMel.mel";

	if (($project == "DiveollyDive2" || $project == "Lionelville" || $project == "Strawberry") && $mode == "texture")
	{
		if (!zwPreCheckinCheckTx())
		{
			return;
		}
	}

//	if ($project == "Calimero" && ($mode == "model" || $mode == "rigging" || $mode == "texture" || $mode == "master") && `about -is64`)
//	{
//		confirmDialog -icon "warning" -message "由于64位maya在缩小贴图的时候会崩溃，所以...\n\n最好用32位maya来上传文件" -button "OK";
//	}

	eval "idmtCheckin";
}