/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc int zwCloseCacheDmap()
{
	int $dirty = false;

	string $files[] = `ls -type file`;
	for ($file in $files)
	{
		if (`getAttr ($file + ".useCache")`)
		{
			setAttr ($file + ".useCache") 0;
			$dirty = true;
		}
	}

	string  $Dlights[] = `ls -type light`;
	for($Dlight in $Dlights)
	{
		if(`objExists ($Dlight + ".useDepthMapShadows")`)
		{
			if((`getAttr ($Dlight + ".reuseDmap")` != 0) || (`getAttr ($Dlight + ".writeDmap")` != 0))
			{
				setAttr  ($Dlight + ".reuseDmap") 0;
				setAttr ($Dlight + ".writeDmap") 0;
				$dirty = true;
			}
		}
	}

	return $dirty;
}