global proc zwCreateShotContents()
{
	if(`window -exists zwCreateShotContents`)
	{
		deleteUI zwCreateShotContents;
	}

	string $folder = `optionVar -query zwCreateShotContents`;
	if (!`filetest -d $folder`)
	{
	//	$folder = workspace;
	}

	window -title "create_Shots_Contents" -width 500 -height 150 zwCreateShotContents;
		columnLayout -adjustableColumn true;
			textFieldButtonGrp -label "Location" -fileName $folder -adjustableColumn 2 -buttonLabel "Browse" -buttonCommand "zwCreateShotContentsBrowse" textFieldButtonGrpCSC;
			textFieldGrp -label "sequence number" -text "0" textFieldGrpCSCSeq;
			textFieldGrp -label "number of shots" -text "0" textFieldGrpCSCShot;
			button -label "create shots folders" -command "zwCreateShotContentsProc";

	showWindow zwCreateShotContents;
}

global proc zwCreateShotContentsBrowse()
{
	string $folder = `textFieldGrp -query -fileName textFieldButtonGrpCSC`;
	$folder = `idmtFolderDialog -initialDir $folder`;
	if($folder != "")
	{
		optionVar -stringValue zwCreateShotContents $folder;
		textFieldGrp -edit -fileName $folder textFieldButtonGrpCSC;
	}
}

global proc zwCreateShotContentsProc()
{
	string $folder = `textFieldGrp -query -fileName textFieldButtonGrpCSC`;
	if ($folder == "")
	{
		return;
	}
	string $seq = `textFieldGrp -query -text textFieldGrpCSCSeq`;
	string $shot = `textFieldGrp -query -text textFieldGrpCSCShot`;
	
	string $dest = $folder + "/winxII_sq_" + $seq + "_sc_" + $shot;
	sysFile -md $dest;
	string $source = "//file-cluster/GDC/Resource/Support/Maya/Import/projects/SHOT_winxII";
	myXcopy $source $dest;
	if (`filetest -d $dest`)
	{
	//	workspace -openWorkspace $dest;
		setProject $dest;
		deleteUI zwCreateShotContents;
	}
}

global proc myXcopy(string $source, string $dest)
{
	int $useProxy = false;//(`match "/CONTENT_4_GLOBAL/PRJ_winxII/SHOT_winxII/" $dest` != "");

	string $buf[] = `getFileList -filespec ($source + "/*.*")`;
	for ($file in $buf)
	{
		string $sourceFile = $source + "/" + $file;
		string $destFile = $dest + "/" + $file;
		if (`filetest -f $sourceFile`)
		{
			if (!`filetest -f $destFile`)
			{
				if ($useProxy)
				{
					zwSysFile "copy" $sourceFile $destFile $useProxy;
				}
				else
				{
					sysFile -copy $destFile $sourceFile;
				}
			}
		}
		else if (`filetest -d $sourceFile`)
		{
			if (!`filetest -d $destFile`)
			{
				if ($useProxy)
				{
					zwSysFile "md" $destFile "" $useProxy;
				}
				else
				{
					sysFile -makeDir $destFile;
				}
			}
			myXcopy $sourceFile $destFile;
		}
	}
}