/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwDeleteTearOffPanel()
{
	string $buf1[];

	string $buf[] = `getPanel -allPanels`;
	for ($panel in $buf)
	{
		if (`panel -query -tearOff $panel`)
		{
			string $control = `panel -query -control $panel`;
			tokenize $control "|" $buf1;
			deleteUI $buf1[0];
		}
	}
}