/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwDisplayPlace3dTexture()
{
	string $buf[] = `ls -long -type "place3dTexture"`;
	for ($place3dTexture in  $buf)
	{
//		int $lock = `getAttr -lock ($place3dTexture + ".visibility")`;
		
		editDisplayLayerMembers "defaultLayer" $place3dTexture;
		setAttr -lock false ($place3dTexture + ".visibility");
		setAttr ($place3dTexture + ".visibility") true;
	}
}