/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 黄仲维
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwExportCamera()
{
// commented by huangzhongwei 20060712
// this tool is out, the alternate function is zwCheckinCleanCheckinCamera() in zjCheckinClean.mel
// re-checkin to export camera, please!
/*
	string $version;

	source zjCheckinClean.mel;

	string $buf[] = `ls -long -dagObjects -cameras -sl`;
	if (size($buf) != 1)
		error "请选择一个摄像机";
	string $shape = $buf[0];
	setAttr ($shape + ".renderable") 1;

	$buf = `listRelatives -fullPath -parent $shape`;
	string $parent = $buf[0];

	tokenize $parent "|" $buf;
	string $name = $buf[size($buf)-1];

	string $str = `match "cam_[0-9]{3}[a-zA-Z]*_[0-9]{3}[a-zA-Z]*" $name`;
	if ($str != $name)
		error ("摄像机命名错误：" + $name);

	if (`camera -query -startupCamera $shape`)
		error "请选择一个摄像机";

	if (`reference -isNodeReferenced $shape`)
		error ($name + " 已经是参考摄像机");
	
	string $buf[],$project;
	string $currentfile = `file -query -sceneName`;
	tokenize $currentfile "/" $buf;
	$currentfile = tolower($buf[size($buf)-1]);
	string $str = `match "^[a-zA-Z][a-zA-Z]_[0-9]{3}[a-zA-Z]*_[0-9]{3}[a-zA-Z]*_" $currentfile`;
	if ($str != "")
	{
		tokenize $str "_" $buf;
		$project = $buf[0];
	}
	
	tokenize $name "_" $buf;
	string $episode = $buf[1];
	string $scene = $buf[2];
	
	string $projectFolder = "";
	if ($project == "br")
		$projectFolder = "BRATZ";
	else if ($project == "do")
		$projectFolder = "DOD";
	else if ($project == "ta")
		$projectFolder = "TAOWA";
	else error "该项目不存在";

	string $folder = "//File-cluster/GDC/Projects/" + $projectFolder + "/Production/Animation/episode_" + $episode + "/episode_camera";
	$buf = `getFileList -filespec ($folder + "/" + $project + "_" + $episode + "_" + $scene + "_cam_??_c???.mb")`;
	int $ver = 0;
	for ($file in $buf)
	{
		$str = `substring $file (size($file)-5) (size($file)-3)`;
		int $verTemp = int($str);
		if ($verTemp > $ver)
			$ver = $verTemp;
	}
	$ver ++;
	if ($ver < 10)
		$version = "c00" + $ver;
	else if ($ver < 100)
		$version = "c0" + $ver;
	else
		$version = "c" + $ver;

	string $sceneName = `file -query -sceneName`;

	string $filename = $project + "_" + $episode + "_" + $scene + "_cam_an_" + $version + ".mb";

	if (`confirmDialog -title "Export Camera" -message ("输出" + $name + "  到" + $filename + " ？") -button "Yes" -button "No" -defaultButton "Yes" -cancelButton "No" -dismissString "No"` == "No")
		return;

	if (!`objExists ($shape + ".history")`)
		addAttr -longName "history" -dataType "string" $shape;
	setAttr -type "string" ($shape + ".history") $sceneName;

	zwCheckinCleanLockCamera;
	zwCheckinCameraLock $shape;

	string $temp = `internalVar -userTmpDir` + $filename;
	sysFile -delete $temp;
	if(`objExists camclip`)
	{
		if (`objExists camclipShader`)
			delete camclipShader;
		delete camclip;
	}
	select $name;
	file -exportSelected -type "mayaBinary" $temp;

	string $dest = "\\\\File-cluster\\GDC\\Projects\\" + $projectFolder + "\\Production\\Animation\\episode_" + $episode + "\\episode_camera\\" + $filename;
	string $cmd = "idmtCheckin.exe \"move\" \"" + $temp + "\" \"" + $dest + "\"";
	string $rs = `system $cmd`;
	if ($rs != "")
		error ("复制文件错误：" + $rs + "\nSOURCE: " + $temp + "\nDEST: " + $dest);

//	string $namespace = "CAM";
	string $namespace = `zwCameraNamespace`;
//	file -reference -namespace $namespace $dest;
	file -reference -renamingPrefix $namespace $dest; 
	delete $parent;

	confirmDialog -title "Export Camera" -message ("输出" + $name + "  成功：" + $filename) -button "OK";
*/
}