/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwExportMaterial(string $file)
{
	string $folder = `internalVar -userTmpDir` + "zwExportMaterial";
	string $cmd = "rd /s/q " + `substituteAllString $folder "/" "\\"`;
	system $cmd;
	sysFile -md $folder;

	zjAMbatchOutput ($folder + "/");

	string $buf[];
	tokenize $file "/" $buf;
	string $filename = `substring $buf[size($buf)-1] 1 (size($buf[size($buf)-1])-3)` + "mb";
//	string $filename = `dirname $file`;
//	$filename = `substring $file (size($filename)+2) (size($file)-3)` + "mb";

	select -noExpand `ls -type shadingEngine`;
	file -exportSelected -type "mayaBinary" ($folder + "/" + $filename);

	sysFile -delete $file;
	$cmd = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Others\\WinRar\\Rar.exe a -ep -ed \"" + `substituteAllString $file "/" "\\"` + "\" \"" + `substituteAllString $folder "/" "\\"` + "\"";
	system $cmd;

	$cmd = "rd /s/q " + `substituteAllString $folder "/" "\\"`;
	system $cmd;
}