/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc string zwFullPath(string $path)
{
	string $str = `workspace -expandName $path`;
	$str = `encodeString $str`;
	if (catch($path = `eval ("idmtFile -fullPath \"" + $str + "\"")`))
	{
//		$path = `substituteAllString $path "/" "\\"`;
//		string $cmd = "fullPath.exe \"" + $path + "\"";
//		chdir "C:";
//		$path = `system $cmd`;
//		$path = `substitute "\"$" $path ""`;
//	//	zwTestPlugin "zwFullPath";
	}
	$path = `substituteAllString $path "\\" "/"`;
	$path = `substitute "//file-cluster/GDC/SW_S3_Pipeline/" $path "Z:/SW_S3_Pipeline/"`;

	return $path;
}