global proc int zwGetProjectGeneration(string $project)
{
	if ($project == "Bratz")
	{
		return 1;
	}
	else if ($project == "BubbleGuppies" || $project == "RainbowRiders" || $project == "Strawberry" || zwIsRainbowProject($project))
	{
		return 2;
	}

	int $generation = 2;

	global string $idmtProjects;
	if ($idmtProjects == "")
	{
		$idmtProjects = `eval "idmtService \"GetProjects\" \"\""`;
	}
	string $buf[];
	tokenize $idmtProjects "|" $buf;
	int $count = 7;
	for ($i=0; $i<size($buf); $i+=$count)
	{
		if ($buf[$i+1] == $project)
		{
			$generation = $buf[$i+6];
			break;
		}
	}

	return $generation;
}