/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwHymoEyeball()
{
	string $buf[] = `ls -long "hymo_l_lo_eyeball"`;
	for ($node in $buf)
	{
		xform -centerPivots $node;
		int $lockX = `getAttr -lock ($node + ".scaleX")`;
		int $lockY = `getAttr -lock ($node + ".scaleY")`;
		int $lockZ = `getAttr -lock ($node + ".scaleZ")`;
		setAttr -lock false ($node + ".scaleX");
		setAttr -lock false ($node + ".scaleY");
		setAttr -lock false ($node + ".scaleZ");
		setAttr ($node + ".scale") 0.97 0.97 0.97;
		setAttr -lock $lockX ($node + ".scaleX");
		setAttr -lock $lockY ($node + ".scaleY");
		setAttr -lock $lockZ ($node + ".scaleZ");
	}
	$buf = `ls -long "hymo_r_lo_eyeball"`;
	for ($node in $buf)
	{
		xform -centerPivots $node;
		int $lockX = `getAttr -lock ($node + ".scaleX")`;
		int $lockY = `getAttr -lock ($node + ".scaleY")`;
		int $lockZ = `getAttr -lock ($node + ".scaleZ")`;
		setAttr -lock false ($node + ".scaleX");
		setAttr -lock false ($node + ".scaleY");
		setAttr -lock false ($node + ".scaleZ");
		setAttr ($node + ".scale") 0.97 0.97 0.97;
		setAttr -lock $lockX ($node + ".scaleX");
		setAttr -lock $lockY ($node + ".scaleY");
		setAttr -lock $lockZ ($node + ".scaleZ");
	}
}