/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


// $type: iff2Bot ªÚ’ﬂ bot2Iff

global proc int zwIff2Bot(string $type)
{
	int $dirty = false;

	string $iff, $bot;

	string $file[] = `ls -type file`;
	for ($node in $file)
	{
		string $image = `getAttr ($node + ".fileTextureName")`;
		if (`gmatch $image "*.iff"`)
		{
			$iff = $image;
			$bot = `substring $image 1 (size($image)-3)` + "bot";
		}
		else if (`gmatch $image "*.bot"`)
		{
			$iff = `substring $image 1 (size($image)-3)` + "iff";
			$bot = $image;
		}
		else
			continue;
		
		if ($type == "iff2Bot" && `filetest -f $bot` && $image != $bot)
		{
			evalEcho ("setAttr " + $node + ".fileTextureName -type \"string\" \"" + $bot + "\"");
			$dirty = true;
		}
		else if ($type == "bot2Iff" && `filetest -f $iff` && $image != $iff)
		{
			evalEcho ("setAttr " + $node + ".fileTextureName -type \"string\" \"" + $iff + "\"");
			$dirty = true;
		}
	}

	return $dirty;
}

//iff conversion map or map conversion iff $type iff2map or map2iff
global proc int jaiff2map(string $type)
{
	int $dirty = false;

	string $iff, $map;

	string $file[] = `ls -type file`;
	for ($node in $file)
	{
		string $image = `getAttr ($node + ".fileTextureName")`;
		if (`gmatch $image "*.iff"`)
		{
			$iff = $image;
			$map = `substring $image 1 (size($image)-3)` + "map";
		}
		else if (`gmatch $image "*.map"`)
		{
			$iff = `substring $image 1 (size($image)-3)` + "iff";
			$map = $image;
		}
		else
			continue;
		
		if ($type == "iff2map" && `filetest -f $map` && $image != $map)
		{
			evalEcho ("setAttr " + $node + ".fileTextureName -type \"string\" \"" + $map + "\"");
			$dirty = true;
		}
		else if ($type == "map2iff" && `filetest -f $iff` && $image != $iff)
		{
			evalEcho ("setAttr " + $node + ".fileTextureName -type \"string\" \"" + $iff + "\"");
			$dirty = true;
		}
	}

	return $dirty;
}

