global proc zwImportTopReference(int $mode)
{	
//	changed to detect possible props parented to nested reference
//	if there r such props, they'll jump to the root level of hierarchy after imported top reference
//	2007.03.22 by hanjiang 



//	$mode 0 just import top ref
//	$mode 1 consider parented obj

	
if($mode==1){	
	
	if(size(hjChangeParentToConstraint(1))){
	
	string $warning;
	$warning=
		"在导入头发之前\n有些道具可能需要从父子关系改为父子约束\n"+
		"---------------------------------------------------------------\n"+
		"（有危险，完成后看看script editor的输出）\n";

	string $parentToConstraint=`confirmDialog -title "检测到可疑的道具物体" -message $warning
 		-button "Continue" -button "Exit" -defaultButton "Exit"
 		-cancelButton "Exit" -dismissString "Exit"`;
	if($parentToConstraint=="Continue")

		hjChangeParentToConstraint(0);
		
		return;
		
	}
	else
	{	
		
			if(`window -q -exists hjTextScrollListWnd`) deleteUI hjTextScrollListWnd;
		
			string $buf[] = `ls -type "reference"`;
		
			for ($reference in $buf)
			{
				if (`objExists $reference`)
				{
		
					if (!catchQuiet(`referenceQuery -topReference -referenceNode $reference`))
					{// if no error
						
		
						string $parent = `referenceQuery -topReference -referenceNode $reference`;
		
						if ($reference != $parent)
		
						{
						
							
							file -importReference -referenceNode $parent;
						}
					}
				}
			}
	
		
		
		
		
		
		
		print ("Nothing has been done to ur scene...Just imported top ref...\n");
		
				
	//	return;
	}
}

else{

	if(`window -q -exists hjTextScrollListWnd`) deleteUI hjTextScrollListWnd;

	string $buf[] = `ls -type "reference"`;

	for ($reference in $buf)
	{
		if (`objExists $reference`)
		{

			if (!catchQuiet(`referenceQuery -topReference -referenceNode $reference`))
			{// if no error
				

				string $parent = `referenceQuery -topReference -referenceNode $reference`;

				if ($reference != $parent)

				{
				
					
					file -importReference -referenceNode $parent;
				}
			}
		}
	}

	}//else
	
}