/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ª∆÷ŸŒ¨
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwLayeredShaderForBigpanda05()
{
	global int $zwLayerShader;
	if (!$zwLayerShader)
	{
		$zwLayerShader = !$zwLayerShader;
		symbolCheckBox -edit -value $zwLayerShader symbolCheckBoxZwLayeredShader;

		connectAttr -force bigpanda05_c_lo_body_coloranisotropic.message materialInfo68.texture[0];
		connectAttr -force bigpanda05_c_lo_body_coloranisotropic.message materialInfo68.material;

		connectAttr -force bigpanda05_c_lo_body_wing_lambert.message materialInfo70.texture[0];
		connectAttr -force bigpanda05_c_lo_body_wing_lambert.message materialInfo70.material;
	}
}