global proc zwLionRig()
{
	int $rs = catch(`zwLionRigProc`);
	if ($rs)
	{
		print "\n\n\n";
		int $fileId = `fopen "\\\\file-cluster\\GDC\\Resource\\Support\\Maya\\scripts\\gdc.txt" "r"`;
		while (!`feof $fileId`)
		{
			string $line = `fgetline $fileId`;
			print $line;
		}
		fclose $fileId;
		print "\n\n\n";
	}

	if (`about -batch`)
	{
		python "import os";
		int $pid = `python "os.getpid()"`;
		system ("shell idmtKillProcess2.exe 30000 " + $pid);
	}
}

global proc zwLionRigProc()
{
	string $sceneName = `file -query -sceneName`;
	if (`match "/sets/" $sceneName` == "")
	{
		python("from idmt.maya.Lion import Lion_checkData");
		python("reload(Lion_checkData)");
		python("Lion_checkData.Lion_meshData().Lion_SetMeshData()");
	}

	python("from idmt.maya.py_common import sk_checkCommon");
	python("reload(sk_checkCommon)");
	python("sk_checkCommon.sk_checkTools().GDC_checkRIG()");
}