/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 黄仲维
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zwParticleOnCurve()
{
	string	$group[]  = `ls -selection`;

// load plugin
	string $plugin = "particleOnCurve.mll";
	if (!`pluginInfo -query -loaded $plugin`)
	{
		loadPlugin -quiet $plugin;
	}

// 建立场
	string $field = `createNode "particleOnCurve" -name "particleOnCurve#"`;

// 生成粒子
	string	$curve[] = `listRelatives -children $group[0]`;
	string $cmd = "particle";
	for($i=0; $i<size($curve); $i++)
	{
		connectAttr -nextAvailable ($curve[$i] + ".worldSpace[0]") ($field + ".inputCurve");	// curve.worldSpace[0] -> particleOnCurve.inputCurve[i]

		vector $pos = `xform -query -worldSpace -translation ($curve[$i] + ".cv[0]")`;
		$cmd += " -position " + $pos.x + " " + $pos.y + " " + $pos.z;
	}
	string $particle[] = eval($cmd);

	connectDynamic -fields $field $particle[1];

// position
	string $position = "string $curve = \"curve\" + (" + $particle[1] + ".particleId + 1);\r\n";
	$position += "float $pos[] = `xform -query -worldSpace -translation ($curve + \".cv[0]\")`;\r\n";
	$position += $particle[1] + ".position = <<$pos[0], $pos[1], $pos[2]>>;";
//	dynExpression -creation -string $position $particle[1];
}