global proc zwRemoveNamespace(string $namespace)
{
	catch(`zwRemoveUnusedNamespace ":"`);

	string $buf[] = `ls ($namespace + ":*") ($namespace + ":*:*")`;
	for ($obj in $buf)
	{
		if (`objExists $obj` && !`referenceQuery -isNodeReferenced $obj`)
		{
			string $name = `match "[^|]+$" $obj`;
			$name = `substitute ($namespace + ":") $name ""`;
		//	string $name = `match "[^|:]+$" $obj`;
			rename $obj $name;
		}
	}

	catch(`zwRemoveUnusedNamespace ":"`);

	namespace -removeNamespace $namespace;
}