global proc zwRemoveMultiNamespace()
{
	string $buf[] = `file -query -reference`;
	for ($file in $buf)
	{
		string $node = `file -query -referenceNode $file`;
		string $str = `substitute ":[^:]+$" $node ""`;
		$namespace = `file -query -namespace $file`;
		if (`namespace -exists ($str + ":" + $namespace)`)
		{
			namespace -setNamespace $str;
			file -edit -namespace ($str + ":temp") $file;
			namespace -setNamespace ":";
			file -edit -namespace $namespace $file;
		}
	}
}