global proc string[] zwSearch(string $folder, string $ext)
{
	string $rs[];
	clear $rs;
	zwRecursiveFile $folder $ext $rs;
	return $rs;
}

global proc zwRecursiveFile(string $folder, string $ext, string $result[])
{
	string $buf[] = `getFileList -filespec ($folder + "/*.*")`;
	for ($file in $buf)
	{
		string $path = $folder + "/" + $file;
		if (`filetest -f $path`)
		{
			string $str = `match "[^.]+$" $file`;
			if (tolower($str) == tolower($ext))
			{
				$result[size($result)] = $path;
			}
		}
		else if (`filetest -d $path`)
		{
			zwRecursiveFile($path, $ext, $result);
		}
	}
}