global proc zwSQ_071()
{
	string $shots[] = `getFileList -folder "//Serverone/CONTENT_4_GLOBAL/PRJ_winxII/SHOT_winxII/SQ_071/"`;
	for ($shot in $shots)
	{
		int $find = false;

		string $files[] = `getFileList -filespec ("//Serverone/CONTENT_4_GLOBAL/PRJ_winxII/SHOT_winxII/SQ_071/" + $shot + "/scenes/animation/*_ANI.mb")`;
		for ($file in $files)
		{
			string $path = "//Serverone/CONTENT_4_GLOBAL/PRJ_winxII/SHOT_winxII/SQ_071/" + $shot + "/scenes/animation/" + $file;
			file -force -loadReferenceDepth "none" -open $path;
			string $references[] = `file -query -reference`;
			for ($i=0; $i<size($references); $i++)
			{
				if (`match "/characters/" $references[$i]` != "")
				{
					string $str = `substitute "[^_]+$" $references[$i] ""`;
					for ($j=$i+1; $j<size($references); $j++)
					{
						if (`match $str $references[$j]` != "")
						{
							$find = true;
							break;
						}
					}
				}
				if ($find)
				{
					break;
				}
			}
			if ($find)
			{
				break;
			}
		}

		if ($find)
		{
			int $fileId = `fopen "Z:\\Scratch\\TD\\SQ_071.txt" "a"`;
			if ($fileId != 0)
			{
				fprint $fileId ($shot + "\n");
				fclose $fileId;
			}
		}
	}
}