global proc zwTemp090d()
{
	string $scene = "//serverone/CONTENT_4_GLOBAL/PRJ_winxII/SHOT_winxII/SQ_090d";
	string $shots[] = `getFileList -folder ($scene + "/")`;
	for ($shot in $shots)
	{
		string $files[] = `getFileList -filespec ($scene + "/" + $shot + "/scenes/animation/*_ANI.mb")`;
		for ($file in $files)
		{
			string $path = $scene + "/" + $shot + "/scenes/animation/" + $file;
			print $path;

			file -force -open $path;

			int $fileId = `fopen "D:/090d.txt" "a"`;
			fprint $fileId (`substituteAllString $path "/" "\\"` + "\r\n");

			string $groups[] = `ls -long -transforms`;
			for ($group in $groups)
			{
				if (`match "^|[^|]+$" $group` == "")
				{
					continue;
				}
				string $shapes[] = `listRelatives -shapes $group`;
				if (size($shapes) != 0)
				{
					continue;
				}
				fprint $fileId (`substitute "|" $group ""` + "\r\n");
			}

			fprint $fileId "\r\n\r\n\r\n";
			fclose $fileId;
		}
	}
}