global proc zwTemp20100428()
{
	string $cacheFiles[] = `ls -type "cacheFile"`;
	for ($cacheFile in $cacheFiles)
	{
		string $cachePath = `getAttr ($cacheFile + ".cachePath")`;
		string $cacheName = `getAttr ($cacheFile + ".cacheName")`;
		string $newName = `substitute "^py_P001002PollyPocket1_MSH_eyebrow_L_Shape$" $cacheName "py_P001002PollyPocket1_MSH_eyebrow_L"`;
		if ($newName != $cacheName)
		{
			if (`filetest -f ($cachePath + "/" + $newName + ".xml")`)
			{
				evalEcho ("setAttr -type \"string\" \"" + $cacheFile + ".cacheName\" \"" + $newName + "\"");
			}
		}
	}
}