/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 李兆兴
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zxCharmbracelet()

{
	string $selected[] = `ls -l -sl`;
	
	string $selectedLN = $selected[0]; 
	string $tem[];
	tokenize $selected[0] "|" $tem;
	tokenize $tem[size($tem)-1] ":" $tem;

	string $prefix;
	if(size($tem)==2)
		$prefix = ($tem[0] + ":");

	else if(size($tem)<2)
		$prefix = "";
	else 
		error "MASTER 命 名 不 规 范 ";

	$masterName = $tem[size($tem)-1];  

	if ( ($masterName == "dvdbreeanai071003_MASTER"||
	      $masterName == "dvdcymbelinei070003_MASTER")



	     &&  size($selected) == 1 )                       
	                                                        

	{

		string $temp[];

		string $chaName = `substitute "_MASTER" $masterName ""`;  
		string $ns_hair = $chaName + "_hairNS";                   

		string $chkChaName = substituteAllString($chaName, "_", ""); 
		
										
		if(objExists ($prefix + $chaName + "_set"))
		{
			select -noExpand ($prefix + $chaName + "_set");

			slResetPose;

		}

		else error ("没 有 发 现 " + ($prefix + $chaName + "_set")  );



		if($chaName == "dvdcymbelinei070003")
		{


			string $str[] = `ls "dvdcymbelinei070003charmbracelet_MASTER"`; 

			if (size($str) != 0)  
			{
				error ($chaName + "'s charmbracelet had Imported Already!");
			}

			if(objExists ($prefix + "dvdcymbelinei070003_forearm2_l") && objExists ($prefix + "dvdcymbelinei070003_GEO") )
			{

				$fileList = `getFileList -folder "Z:\\Resource\\Support\\Maya\\Import\\" -filespec ("dvdcymbelinei070003_charmbracelet_export.mb")`;

				if(`size $fileList`==0)
				error "No find the import file";

				file -import -type "mayaBinary" -ra off "Z:\\Resource\\Support\\Maya\\Import\\dvdcymbelinei070003_charmbracelet_export.mb";

			}

			else error ("没 有 发 现 " + ($prefix + "dvdcymbelinei070003_forearm2_l")  + " " + ($prefix + "dvdcymbelinei070003_GEO") );
		
			parent dvdcymbelinei070003charmbracelet_MISC ($prefix + "dvdcymbelinei070003_GEO");

			parent dvdcymbelinei070003charmbracelet_MASTER ($prefix + "dvdcymbelinei070003_forearm2_l");

		}



		if($chaName == "dvdbreeanai071003")
		{

			string $str[] = `ls  "dvdbreeanai071003charmbracelet_MASTER"`; 

			if (size($str) != 0)  
			{
				error ($chaName + "'s charmbracelet had Imported Already!");
			}


			if(objExists ($prefix + "dvdbreeanai071003_forearm2_l") && objExists ($prefix + "dvdbreeanai071003_GEO") )
			{

				$fileList = `getFileList -folder "Z:\\Resource\\Support\\Maya\\Import\\" -filespec ("dvdbreeanai071003_charmbracelet_export.mb")`;

				if(`size $fileList`==0)
				error "No find the import file";

				file -import -type "mayaBinary" -ra off "Z:\\Resource\\Support\\Maya\\Import\\dvdbreeanai071003_charmbracelet_export.mb";

			}

			else error ("没 有 发 现 " + ($prefix + "dvdbreeanai071003_forearm2_l")  + " " + ($prefix + "dvdbreeanai071003_GEO")  );
		
			parent dvdbreeanai071003charmbracelet_MISC ($prefix + "dvdbreeanai071003_GEO");

			parent dvdbreeanai071003charmbracelet_MASTER ($prefix + "dvdbreeanai071003_forearm2_l");

		}






	}




	else error "invalid selection";


}

