global proc zxEHstep8()
{

	string $tokenBuf[],$jointCodes[],$jCodeLns[],$buf1[],$hairSysChi[];

	string $chaCode,$jointCode;

	string $master[] = `ls -l -type transform  "*MASTER"`;  //列出场景有“MASTER”字符的transform物体
	if(size($master)==0)
	error " 场 景 里 没 有 发 现 MASTER ！ ";
	else if(size($master)>1)
	{
		select $master;
		outlinerEditor -e -sc 1  outlinerPanel1;

		confirmDialog -title "Warning"
			      -message " 场景里发现多个MASTER , 请保证场景里只有一个Master物体！ "
			      -button "OK";

		error " 场 景 里 发 现 多 个 MASTER , 请 保 证 场 景 里 只 有 一 个 Master 物 体！ ";			//场景里只能有一个角色！！！！
	}
	else	// if(`size($master)`==1)
	{

		$tokenNum = `tokenize $master[0] "|" $tokenBuf`;
		$tokenNum = `tokenize $tokenBuf[($tokenNum-1)] "_" $tokenBuf`;
		if($tokenNum!=2)
		{
			select $master[0];
			outlinerEditor -e -sc 1  outlinerPanel1;

			confirmDialog -title "Warning"
			      -message ( $master[0] + " 命 名 不 规 范 ！ ")
			      -button "OK";


			error ($master[0] + " 命 名 不 规 范 ！");
		}

		$chaCode = $tokenBuf[0];	//获取角色编号
	}



	string $colCodes[] = {"br_hairCollide_root" , "br_hairCollide_spine" , "br_hairCollide_neck" , "br_hairCollide_head" , "br_hairCollide_armLeft" , 
			      "br_hairCollide_elbowLeft" , "br_hairCollide_armRight" , "br_hairCollide_elbowRight" , "br_hairCollide_hipLeft" , "br_hairCollide_hipRight"};




	string $hairSys[] = `ls "*_HAIRSYSTEM*"`;

//select -cl;
	if(size($hairSys)==0)
	{
		group -em -n ($chaCode + "_HAIRSYSTEM");
		confirmDialog -title "Warning"
		-message ( " 请 将 hairsystem Follicles pfxHair 等 节 点 放 置 在 " + $chaCode + "_HAIRSYSTEM" + "里 面 ！")
		-button "OK";
		 error  " 请 将 hairsystem Follicles pfxHair 等 节 点 放 置 在 ($chaCode + \"_HAIRSYSTEM\") 里 面 ！";
	}
	else if (size($hairSys)>1)
	{

		confirmDialog -title "Warning"
		-message ( " 场 景 里 有 多 个 HAIRSYSTEM 组 , 请 删 除 多 余 的 HAIRSYSTEM 重 复 第 八 步 ！")
		-button "OK";

		select $hairSys;
		outlinerEditor -e -sc 1  outlinerPanel1;

		 error  "  场 景 里 有 多 个 HAIRSYSTEM 组 , 请 删 除 多 余 的 HAIRSYSTEM 重 复 第 八 步 ！";

	}
	else
	{
			if( $hairSys[0] != ($chaCode + "_HAIRSYSTEM"))
			{
				select $hairSys[0];
				outlinerEditor -e -sc 1  outlinerPanel1;

				string $returnVal = `confirmDialog -title "Warning"
						     -message ($hairSys[0] + "命 名 不 正 确，是 否 需 要 改 为" + ($chaCode + "_HAIRSYSTEM") + "！")
						     -button "Yes"
						     -button "No"
						     -button "I'm not sure"
						     -defaultButton "Yes"
						     -cancelButton  "I'm not sure"`;

				if($returnVal == "Yes")
				{
					rename $hairSys[0] ($chaCode + "_HAIRSYSTEM");
					$hairSys[0] =($chaCode + "_HAIRSYSTEM");

				}
			        if ($returnVal == "I'm not sure")
				{
					 error  ($hairSys[0] + " 命 名 不 正 确，应 该 改 为" + ($chaCode + "_HAIRSYSTEM") + "！");
				}
			        if ($returnVal = "No")
				{
				}




	}


			$bufGrp =`group -w $colCodes`;
			

	//检测是否有hairCollide_GRP。


			string $GRP[] = `ls "*hairCollide_GRP"`;

			if(`objExists $GRP[0]`)

			{

	//			for($j=0;$j<size($makeColNum);$j++)
	//			{

					parent $colCodes $GRP[0];

	//			}

			}
			else
			{
				group -em -n "hairCollide_GRP";


	//			for($j=0;$j<size($makeColNum);$j++)
	//			{

					parent $colCodes hairCollide_GRP;

	//			}
			}

			string $upGRP[] = `listRelatives -p "hairCollide_GRP"`;
			if($hairSys[0] != $upGRP[0])
			parent "hairCollide_GRP" $hairSys[0];

			delete $bufGrp;

//检查场景是否有（$chaCode ＋ HAIR）显示层。

		string $layer[] = `ls -l -type displayLayer "*_HAIR"`;

		string $hairSysChi[] = `listRelatives -c -f ($chaCode + "_HAIRSYSTEM")`;

		if(`size($layer)` ==1)
		{
			rename $layer[0] ($chaCode + "_HAIR");

			layerEditorEmpty $layer[0];

			select -r ($hairSysChi) hairCollide_GRP;
			
			editDisplayLayerMembers $layer[0] `ls -selection`;
		}

		else if(`size($layer)` >1)
		{

			confirmDialog -title "Warning"
			-message ( " 场 景 里 有 多 个 HAIR 现 示 层 , 请 删 除 多 余 的 HAIR 现 示 层 并 重 复 第 八 步 ！")
			-button "OK";

			select $layer;

			outlinerEditor -e -sc 1  outlinerPanel1;

			 error  "  场 景 里 有 多 个 earRing 现 示 层 , 请 删 除 多 余 的 HAIR 现 示 层 并 重 复 第 八 步 ！";

		}
		
		else //$layer == 0
		{


			string $hairLayer = `createDisplayLayer -name ($chaCode + "_HAIR") -number 1 -empty`;

			select -r ($hairSysChi) hairCollide_GRP;
			
			editDisplayLayerMembers $hairLayer `ls -selection`;

			int $col = rand(1,31);

			setAttr ($chaCode + "_HAIR.color") $col;

		}

		select ($chaCode + "_HAIRSYSTEM");

		confirmDialog -title "完 成"
		-message "  头 发 文 件 整 理 完 成 ，导 出 HAIRSYSTEM 组 ！"
		-button "OK";

		print " 导 出 头 发 整 理 完 成 ！";

	}

}
