global proc zxExportHairUI()
{
	string $path = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\icons\\Bratz\\";
	
	if(`window -exists zxexportHair`)
		deleteUI zxexportHair;

//	windowPref -remove zximportHair;
	window -menuBar true -title "Bratz Export Hair" -resizeToFitChildren 1 -width 260 -height 360 zxexportHair;
//		menu -label "Edit";
//			menuItem -label "Reset Setings" ;//-command "zxImportHairReset"
		menu -label "Help";
			menuItem -label "Help on Export Hair..." -command "zjHelpCallback zxExportHair";



		string $formLayout = `formLayout`;
			
			image -w 300 -h 59 -image($path+"/bratz.jpg") bratzTitleImage;

			text -l "  1.  打开网上带设置的角色texture文件 ( 不使用参考角色 )" zxEHtext1;

			button -l "  2.  检查texture文件是否符合制作规范 ( 选择master )" -rs 1 -al left -h 50 -c "source zxEHstep2.mel ; zxEHstep2" zxEHbutton1 ;

			text -l "  3.  在texture文件上导入及整理头发" zxEHtext2;

			button -l "  4.  创建碰撞体组,Link到对应的骨骼下面" -rs 1 -al left -h 50 -c "source zxEHstep4.mel ;zxEHstep4 "zxEHbutton2;

			text -l "  5.  将碰撞体Link到对应的碰撞体组下面"  zxEHtext3;

			button -l "  6.  检查在碰撞体组以外的碰撞体" -rs 1 -al left -h 50 -c "source zxEHstep6.mel ; zxEHstep6 " zxEHbutton3;

			text -l "  7.  检查一下是否把上一步检测到的碰撞体Link到标准的碰撞体组下面"  zxEHtext4;

			button -l "  8.  将整理好的 头发 导出保存 (角色有耳环的，需要继续下面的步骤) " -rs 1 -al left -h 50 -c "source zxEHstep8.mel ; zxEHstep8" zxEHbutton4;

			text -l "  9.  角色需要添加耳环的,在texture文件上导入及整理耳环"  zxEHtext5;

			button -l "  10.  将整理好的 头发/耳环 导出保存" -rs 1 -al left -h 50 -c "source zxEHstep10.mel ; zxEHstep10 " zxEHbutton5;


		setParent ..;


		formLayout -edit

			-attachForm	bratzTitleImage top 0
			-attachForm	bratzTitleImage left 0
			-attachForm	bratzTitleImage right 0

			-ac		zxEHtext1	"top"		30      bratzTitleImage
			-attachForm	zxEHtext1	"left"		2
			-attachForm	zxEHtext1	"right"		0



			-attachControl	zxEHbutton1	"top"		30      zxEHtext1
			-attachForm	zxEHbutton1	"left"		0
			-attachForm	zxEHbutton1	"right"		0



			-attachControl	zxEHtext2	"top"		30      zxEHbutton1
			-attachForm	zxEHtext2	"left"		2
			-attachForm	zxEHtext2	"right"		0


			-attachControl	zxEHbutton2	"top"		30      zxEHtext2
			-attachForm	zxEHbutton2	"left"		0
			-attachForm	zxEHbutton2	"right"		0


			-attachControl	zxEHtext3	"top"		30      zxEHbutton2
			-attachForm	zxEHtext3	"left"		2
			-attachForm	zxEHtext3	"right"		0


			-attachControl	zxEHbutton3	"top"		30	zxEHtext3
			-attachForm	zxEHbutton3	"left"		0
			-attachForm	zxEHbutton3     "right"		0


			-attachControl	zxEHtext4	"top"		30      zxEHbutton3
			-attachForm	zxEHtext4	"left"		2
			-attachForm	zxEHtext4	"right"		0


			-attachControl	zxEHbutton4	"top"		30	zxEHtext4
			-attachForm	zxEHbutton4	"left"		0
			-attachForm	zxEHbutton4     "right"		0


			-attachControl	zxEHtext5	"top"		30      zxEHbutton4
			-attachForm	zxEHtext5	"left"		2
			-attachForm	zxEHtext5	"right"		0


			-attachControl	zxEHbutton5	"top"		30	zxEHtext5
			-attachForm	zxEHbutton5	"left"		0
			-attachForm	zxEHbutton5     "right"		0


		$formLayout;

 	showWindow zxexportHair;


}
