/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ÀîÕ×ÐË
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zxSmokeTail()

{

	string $sl[] = `ls -tr -sl -l`;  

	if (size($sl) == 1)
	{

		string $cloc[] = `spaceLocator -p 0 0 0 -name "dir_ctr#"`;

		select -cl;

		string $emit[] = `emitter  -type volume  -name "smoke_emitter#" -r 100  -cye none -cyi 1 -spd 20 -nsp 1 -tsp 0.1 -dx 0 -dy 1  -vsh torus  -vsw 360 -tsr 0.5 -afc 1  -arx 3 -drs 20 `;

		parent $emit[0] $cloc[0];

		float $bbcoord[]=`xform -q -ws -bb $sl[0]`;
		select $cloc[0];
		move  (($bbcoord[0]+$bbcoord[3])/2) (($bbcoord[1]+$bbcoord[4])/2) (($bbcoord[2]+$bbcoord[5])/2);
		pointConstraint -mo -weight 1 $sl[0] $cloc[0];
		orientConstraint -mo -weight 1 $sl[0] $cloc[0];

		string $perEmit =`group -n "emitter_smoke#" -w`;

		setAttr -keyable 0 -lock 1 ($perEmit + ".tx");
		setAttr -keyable 0 -lock 1 ($perEmit + ".ty");
		setAttr -keyable 0 -lock 1 ($perEmit + ".tz");
		setAttr -keyable 0 -lock 1 ($perEmit + ".rx");
		setAttr -keyable 0 -lock 1 ($perEmit + ".ry");
		setAttr -keyable 0 -lock 1 ($perEmit + ".rz");
		setAttr -keyable 0 -lock 1 ($perEmit + ".sx");
		setAttr -keyable 0 -lock 1 ($perEmit + ".sy");
		setAttr -keyable 0 -lock 1 ($perEmit + ".sz");
		setAttr -keyable 0 -lock 1 ($perEmit + ".visibility");


		zjObjectAddAttr($perEmit, "rate", "double", 45, 0, 100000);
		zjObjectAddAttr($perEmit, "speed", "double", 20, 0, 100);
		zjObjectAddAttr($perEmit, "speedRandom", "double", 0, 0, 100000);
		zjObjectAddAttr($perEmit, "tangentSpeed", "double", 0.1, 0, 100);
		zjObjectAddAttr($perEmit, "normalSpeed", "double", 1, 0, 100);
		zjObjectAddAttr($perEmit, "emitTx", "double", 8.5, -100000, 100000);
		zjObjectAddAttr($perEmit, "emitTy", "double", 27.8, -100000, 100000);
		zjObjectAddAttr($perEmit, "emitTz", "double", -1.6, -100000, 100000);
		zjObjectAddAttr($perEmit, "emitSx", "double", 0.7, 0, 100);
		zjObjectAddAttr($perEmit, "emitSy", "double", 0.8, 0, 100);
		zjObjectAddAttr($perEmit, "emitSz", "double", 0.8, 0, 100);
		zjObjectAddAttr($perEmit, "emitRx", "double", -90.5, -100000, 100000);
		zjObjectAddAttr($perEmit, "emitRy", "double", -15.8, -100000, 100000);
		zjObjectAddAttr($perEmit, "emitRz", "double", 0, -100000, 100000);

		connectAttr -f ($perEmit + ".rate") ($emit[0] + ".rate");
		connectAttr -f ($perEmit + ".speed") ($emit[0] + ".speed");
		connectAttr -f ($perEmit + ".speedRandom") ($emit[0] + ".speedRandom");
		connectAttr -f ($perEmit + ".tangentSpeed") ($emit[0] + ".tangentSpeed");
		connectAttr -f ($perEmit + ".normalSpeed") ($emit[0] + ".normalSpeed");
		connectAttr -f ($perEmit + ".emitTx") ($emit[0] + ".tx");
		connectAttr -f ($perEmit + ".emitTy") ($emit[0] + ".ty");
		connectAttr -f ($perEmit + ".emitTz") ($emit[0] + ".tz");
		connectAttr -f ($perEmit + ".emitSx") ($emit[0] + ".sx");
		connectAttr -f ($perEmit + ".emitSy") ($emit[0] + ".sy");
		connectAttr -f ($perEmit + ".emitSz") ($emit[0] + ".sz");
		connectAttr -f ($perEmit + ".emitRx") ($emit[0] + ".rx");
		connectAttr -f ($perEmit + ".emitRy") ($emit[0] + ".ry");
		connectAttr -f ($perEmit + ".emitRz") ($emit[0] + ".rz");
 


		if(!size(`ls -type transform "smoke_emitter_group"`))
		{
			group -n "smoke_emitter_group" -w;

			setAttr -keyable 0 -lock 1 smoke_emitter_group.tx;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.ty;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.tz;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.rx;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.ry;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.rz;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.sx;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.sy;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.sz;
			setAttr -keyable 0 -lock 1 smoke_emitter_group.visibility;



		}
		else parent $perEmit "smoke_emitter_group";

		if(!size(`ls -type transform "fx_group_smoke"`))
		{
			group -n "fx_group_smoke" -w;

			setAttr -keyable 0 -lock 1 fx_group_smoke.tx;
			setAttr -keyable 0 -lock 1 fx_group_smoke.ty;
			setAttr -keyable 0 -lock 1 fx_group_smoke.tz;
			setAttr -keyable 0 -lock 1 fx_group_smoke.rx;
			setAttr -keyable 0 -lock 1 fx_group_smoke.ry;
			setAttr -keyable 0 -lock 1 fx_group_smoke.rz;
			setAttr -keyable 0 -lock 1 fx_group_smoke.sx;
			setAttr -keyable 0 -lock 1 fx_group_smoke.sy;
			setAttr -keyable 0 -lock 1 fx_group_smoke.sz;
			setAttr -keyable 0 -lock 1 fx_group_smoke.visibility;


		}
	//	else parent $perEmitGp "fx_group_dust";


		string $volAxis[] =`volumeAxis -pos 0 0 0  -name "smoke_volumeAxisField#" -m 10 -att 1 -ia 0 -afc 1 -afx 1 -arx 0 -alx 0 -drs 0 -dx 1 -dy 0 -dz 0 -trb 0 -trs 0.2 -tfx 1 -tfy 1 -tfz 1 -tox 0 -toy 0 -toz 0 -dtr 0  -mxd -1  -vsh sphere -vof 0 0 0 -vsw 360 -tsr 0.5`;

		pointConstraint  -weight 1 $emit[0] $volAxis[0];
		orientConstraint -weight 1 $emit[0] $volAxis[0];

		parent $volAxis[0] $emit[0];

		zjObjectAddAttr($perEmit, "volumeAxisFieldSx", "double", 7, -1000, 1000);
		zjObjectAddAttr($perEmit, "volumeAxisFieldSy", "double", 7, -1000, 1000);
		zjObjectAddAttr($perEmit, "volumeAxisFieldSz", "double", 7, -1000, 1000);
		zjObjectAddAttr($perEmit, "volumeMagnitude", "double", 7, -1000, 1000);

		connectAttr -f ($perEmit + ".volumeAxisFieldSx") ($volAxis[0] + ".sx");
		connectAttr -f ($perEmit + ".volumeAxisFieldSy") ($volAxis[0] + ".sy");
		connectAttr -f ($perEmit + ".volumeAxisFieldSz") ($volAxis[0] + ".sz");
		connectAttr -f ($perEmit + ".volumeMagnitude") ($volAxis[0] + ".magnitude");




		
		if(!(`objExists group_smoke`))
		{
			string $pt_smoke[] = `particle -n smoke_particle`;

			connectDynamic -em $emit[0] $pt_smoke[0];      //connect particle to emitter


			setAttr ($pt_smoke[1] + ".inheritFactor") 0.15;
		 
			setAttr ($pt_smoke[1] + ".lifespanMode") 2;

			setAttr ($pt_smoke[1] + ".lifespan") 2;

			setAttr ($pt_smoke[1] + ".lifespanRandom") 1;

			setAttr ($pt_smoke[1] + ".depthSort") 1;

			setAttr ($pt_smoke[1] + ".particleRenderType") 8;

			//setAttr ($pt_smoke[1] + ".startFrame") -31;

		//add per particle attr

			kcParticleAddAttr($pt_smoke[1], "opacityPP", "doubleArray");
			kcParticleAddAttr($pt_smoke[1], "radiusPP", "doubleArray");


			string $cmd = "arrayMapper -target " + $pt_smoke[1] + " -destAttr opacityPP -inputV ageNormalized -type ramp";
			string $amp[] = eval($cmd);
			string $ramp[] = `listConnections -source true -destination false $amp[0]`;
			rename $amp[0] "smoke_opacityPP_arrayMapper";
			rename $ramp[0] "smoke_opacityPP_ramp";


			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[0].position") 0;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[0].color") -type double3 0.876 0.876 0.876 ;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[1].position") 0.3;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[1].color") -type double3 0.347 0.347 0.347 ; 
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[2].position") 0.6;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[2].color") -type double3 0.124 0.124 0.124 ;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[3].position") 1;
			setAttr ("smoke_opacityPP_ramp" + ".colorEntryList[3].color") -type double3 0 0 0 ; 

			shadingNode -asUtility particleSamplerInfo -n "smoke_opacityPP_SamplInfo";
			connectAttr -f smoke_opacityPP_SamplInfo.outUvCoord smoke_opacityPP_ramp.uvCoord;

			string $cmd = "arrayMapper -target " + $pt_smoke[1] + " -destAttr radiusPP -inputV ageNormalized -type ramp";
			string $amp[] = eval($cmd);
			string $ramp[] = `listConnections -source true -destination false $amp[0]`;
			rename $amp[0] "smoke_radiusPP_arrayMapper";
			rename $ramp[0] "smoke_radiusPP_ramp";

			setAttr "smoke_radiusPP_arrayMapper.maxValue" 5;

			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[0].position") 0;
			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[0].color") -type double3 0.595 0.595 0.595 ;
			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[1].position") 0.58;
			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[1].color") -type double3 0.874 0.874 0.874 ; 
			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[2].position") 1;
			setAttr ("smoke_radiusPP_ramp" + ".colorEntryList[2].color") -type double3 0.992 0.992 0.992 ;

			shadingNode -asShader particleCloud -n "smoke_particleCloud";

			setAttr "smoke_particleCloud.blobMap" -type double3 0.14 0.14 0.14 ;
			setAttr "smoke_particleCloud.roundness" 0.504;



			if( !((`objExists vapor_transparency_ramp`) && (`objExists vapor_transparency_place2dTexture`) && (`objExists vapor_transparency_particleSamplerInfo`) ))

			{


				shadingNode -asTexture ramp -n "vapor_transparency_ramp";

				shadingNode -asUtility place2dTexture -n "vapor_transparency_place2dTexture";

				shadingNode -asUtility particleSamplerInfo -n "vapor_transparency_particleSamplerInfo";


				connectAttr vapor_transparency_place2dTexture.outUV vapor_transparency_ramp.uv;

				connectAttr vapor_transparency_place2dTexture.outUvFilterSize vapor_transparency_ramp.uvFilterSize;
				
				connectAttr -f vapor_transparency_particleSamplerInfo.outUvCoord vapor_transparency_place2dTexture.uvCoord;


				setAttr ("vapor_transparency_ramp" + ".colorEntryList[0].position") 0;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[0].color") -type double3 0.678 0.678 0.678 ;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[1].position") 0.040;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[1].color") -type double3 0.15 0.15 0.15 ;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[2].position") 0.155;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[2].color") -type double3 0.15 0.15 0.15 ;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[3].position") 1;
				setAttr ("vapor_transparency_ramp" + ".colorEntryList[3].color") -type double3 1 1 1 ; 

			}

			
			connectAttr -f vapor_transparency_ramp.outColor smoke_particleCloud.transparency;



			shadingNode -asTexture cloud -n "smoke_color_cloud";

			shadingNode -asUtility place3dTexture -n "smoke_color_place3dTexture";

			setAttr "smoke_color_place3dTexture.scaleX" 3;
			setAttr "smoke_color_place3dTexture.scaleY" 3;
			setAttr "smoke_color_place3dTexture.scaleZ" 3;


			connectAttr smoke_color_place3dTexture.wim[0] smoke_color_cloud.pm;

			connectAttr -force smoke_color_cloud.outColor smoke_particleCloud.color;


			setAttr "smoke_color_cloud.color1" -type double3 0.519 0.525 0.5 ;
			setAttr "smoke_color_cloud.color2" -type double3 0.699 0.687 0.671 ;
			setAttr "smoke_color_cloud.contrast" 1;
			setAttr "smoke_color_cloud.amplitude" 0.579;
			setAttr "smoke_color_cloud.depthMax" 15;
			setAttr "smoke_color_cloud.transpRange" 1;
			setAttr "smoke_color_cloud.ratio" 0.9;
			setAttr "smoke_color_cloud.defaultColor" -type double3 0.5 0.5 0.5 ;
			setAttr "smoke_color_cloud.colorGain" -type double3 0.741 0.811 0.934 ;



			
			select $pt_smoke[0];

			hyperShade -assign smoke_particleCloud;

	//___________________________________________________________________________

			select -cl;


			turbulence -pos 0 0 0  -name "smoke_turbulence" -m 20 -att 0 -f 0.2 -phaseX 0 -phaseY 0 -phaseZ 0 -noiseLevel 0 -noiseRatio 0.707  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5;

			connectDynamic -f smoke_turbulence  $pt_smoke[0];

			select -r smoke_turbulence smoke_color_place3dTexture smoke_particle ;

			group -n "group_smoke" -w;

			parent group_smoke fx_group_smoke ;

			select -cl;


			setAttr -keyable 0 -lock 1 group_smoke.tx;
			setAttr -keyable 0 -lock 1 group_smoke.ty;
			setAttr -keyable 0 -lock 1 group_smoke.tz;
			setAttr -keyable 0 -lock 1 group_smoke.rx;
			setAttr -keyable 0 -lock 1 group_smoke.ry;
			setAttr -keyable 0 -lock 1 group_smoke.rz;
			setAttr -keyable 0 -lock 1 group_smoke.sx;
			setAttr -keyable 0 -lock 1 group_smoke.sy;
			setAttr -keyable 0 -lock 1 group_smoke.sz;
			setAttr -keyable 0 -lock 1 group_smoke.visibility;

			zjObjectAddAttr("group_smoke", "SmokeLifespan", "double", 2, 0, 100);
			zjObjectAddAttr("group_smoke", "SmokeLifespanrandom", "double", 1, 0, 100);
			zjObjectAddAttr("group_smoke", "SmokeTurbulence", "double", 20, -10000, 10000);
			
			connectAttr -f ("group_smoke" + ".SmokeLifespan") ($pt_smoke[1] + ".lifespan");
			connectAttr -f ("group_smoke" + ".SmokeLifespanrandom") ($pt_smoke[1] + ".lifespanRandom");
			connectAttr -f ("group_smoke" + ".SmokeTurbulence") ("smoke_turbulence" + ".magnitude");






		}

		else  connectDynamic -em $emit[0] "smoke_particle";      //connect particle to emitter



		connectDynamic -f $volAxis[0]  smoke_particle;

		select $perEmit;

		

	}

	else error"please select one object";

}