/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ÀîÕ×ÐË
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc zxweightsimport (string $body)

{

string $usersel[] = `ls -sl` ;

//string $location_n_wildcard = (`workspace -q -act` + "/pwt/" + "*.pwt");

//string $file2use = "E:/setup file/bratz/modify elbow/pwt/" + $body + ".pwt";

string $file2use = "Z:\\Resource\\Support\\Maya\\Import\\pwt\\" + $body + ".pwt";

int $countVtx = 0;
int $SkinClusterConnectionCount = 0;
for ($element in $usersel)
	{	
		string $ShapeOfElement[] = `ls  -dagObjects -sl -hd 1 -type mesh $element`;
		
		string $vtxrange[] = `polyListComponentConversion -tv $ShapeOfElement[0]`;string $vtxUnit[]=`filterExpand -ex true -sm 31 $vtxrange[0]`;
		int $vtxCount =  `size $vtxUnit`;

		
		if ($ShapeOfElement[0] != "")
		{	
			
			string $jjunk[] = `listHistory $ShapeOfElement[0]`;
			string $isBound[] = `ls -typ skinCluster $jjunk`;
			int $totalSkinClustersFound = `size $isBound`;
			if  ($totalSkinClustersFound != 0)
			{	
				
				int $normalizeWeightsStatus = `getAttr ($isBound[0] + ".normalizeWeights")`;
				string $SkinClusterConnections[] = `listConnections ($isBound[0] + ".matrix")`;

				$fileId=`fopen $file2use "r"`;
				int $nextLineArray = 0;
				string $nextLine[];
				$nextLine[0] = `fgetline $fileId`;
				while ( size ($nextLine[$nextLineArray]) != 0 )
				{
					$nextLineArray++;
					$nextLine[$nextLineArray] = `fgetline $fileId`;
				}
				
				int $howManyJoints = ((`size $nextLine`) -1);

				if ($normalizeWeightsStatus == 1)
				setAttr ($isBound[0] + ".normalizeWeights") false;

				int $count;
				waitCursor -state on;
				skinPercent -rtd $isBound[0];
				int $ii;
				for ($ii = 0; $ii <= 1; $ii++)
					for ( $count=0;  $count < ($howManyJoints); $count++ )
					{
						
						
						string $currentPaintOnConnection[] = `listConnections ($isBound[0] + ".ptt")`;
						
						if (`size $currentPaintOnConnection` != 0)
						disconnectAttr ($currentPaintOnConnection[0]+ ".message") ($isBound[0] + ".ptt");
						string $jjjunk[];
						tokenize $nextLine[$count] "\n" $jjjunk;
						connectAttr ($jjjunk[0] + ".message") ($isBound[0] + ".ptt");
						$count++;
						
						
						$runThis = ("setAttr " + $isBound[0] + ".ptw -type doubleArray " + $vtxCount + " " + $nextLine[$count]);
						eval $runThis;
						refresh;
						currentTime `currentTime -q`;		//just another way of refreshing
 						
					}

				

			if ($normalizeWeightsStatus == 1)
			setAttr ($isBound[0] + ".normalizeWeights") true;
			refresh;
					
			fclose $fileId;
			}
		
		}
	}
	hilite -u "*";
	waitCursor -state off;
}