//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-9-7
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-9-7
//	Description:
//				
//////////////////////////////////////////////////////////

global proc oiGetAnimCamera()
{
	source "zwCameraImportExport.mel"; 
	
	string $exportPath = "D:/Cam/";
	string $sceneName = `file -query  -shortName -sceneName`;
	string $name = `zwGetPath "cameraName" $sceneName`;
	string $cameras[] = `ls -cameras`;
	string $allBaked[]={};
	for ($shape in $cameras)
	{
		string $parent[] = `listRelatives -fullPath -parent $shape`;
		if (size($parent))
		{
			//print ($parent[0]+"\n");
			string $camera = `match "[^|]+$" $parent[0]`;
			if (match(tolower($name),tolower($camera))!="")
			{
				select -r $parent[0];
				$allBaked[size($allBaked)] = zwBakeCamera();
				//select -r `zwCheckinGetBakedCamera`;

				//file -op "v=0" -typ "mayaBinary" -pr -es ($exportPath+$name+".mb");
			}
		}
	}
	select -r $allBaked;
	file -op "v=0" -typ "mayaBinary" -pr -es ($exportPath+$name+".mb");
}