global proc s100VRNewName()
{
$file = `file -q -shortName -sn `;
$start = startString($file,2) ;
string $name  ="";
	if($start == "MA")
	{
	$tmpA = stringToStringArray ($file,"_");
	$name = $tmpA[2];
    }

	if(`window -ex 	s100VRNewNameUI`)
		deleteUI s100VRNewNameUI;

	window -title "studio 100 Vegetations AutoRig"  -h 400  s100VRNewNameUI;
	columnLayout -adjustableColumn true s100VRUICLMain;

	text -l "name : ";
	textField -tx $name s100VRTFNewName ;
	button -l "create name" -c s100VRNewNameAdd;

	window -e -w 100 -h 100  s100VRNewNameUI;

	showWindow;

}

global proc s100VREditNameUI()
{
$file = `textField -q -tx    s100VRUITFAssetName `;
$name = substituteAllString($file,"VR_", "") ;
$name = substituteAllString($name,"_scN", "") ;


	if(`window -ex 	s100VREditNameUI`)
		deleteUI s100VREditNameUI;

	window -title "studio 100 Vegetations AutoRig"  -h 400  s100VREditNameUI;
	columnLayout -adjustableColumn true s100VREditNameCLMain;

	text -l "name : ";
	textField -tx $name s100VREditNameTFNewName ;
	button -l "modify name" -c s100VREditName;

	window -e -w 150 -h 100  s100VREditNameUI;

	showWindow;

}


global proc s100VREditName()
{
$file = `textField -q -tx    s100VRUITFAssetName `;
$nName = `textField -q -tx  s100VREditNameTFNewName` ;
rename $file ("VR_" + $nName + "_scN") ;
deleteUI s100VREditNameUI;
s100VRrefreshUI;

}





global proc s100VRNewNameAdd()
{

$text = `textField -q -tx s100VRTFNewName `;

	if ($text != "")
	{
	createNode -n ("VR_" + $text +"_scN") script;
	deleteUI s100VRNewNameUI;
	s100VRCreateNameAndNode;
	s100VRrefreshUI;


    }else{
	warning "name is empty, put a name for the asset";
    }


}


global proc s100VRCreateNameAndNode()
{
s100VRCreateBaseFT;
}