global proc s100VRaddVegetationToAutoRigUI()
{

string $var[] = `ls -sl`;

	if(`window -ex 	s100VRaddVegetationToAutoRigUI`)
		deleteUI s100VRaddVegetationToAutoRigUI;

$weight = 200;
$w2 = ($weight -15);
	window -title "s100VR add curve to Auto Rig" -w $weight -h 600  s100VRaddVegetationToAutoRigUI;

menuBarLayout s100VRUIMLMain;


    menu -en 1 -label "Help" -helpMenu true;
        menuItem -en 1   -label "help";

    setParent ..;
	formLayout s100VRAddCurveToAutoRigFL;


//select

	$text1 = `text -l "curve to add : "`;
	$textFd1 = `textField -en 0 -w $w2 -tx $var[0] S100VRAddCurveTF`;
	$buttonRefreshC = `button -w $w2 -label "refresh selection" -c s100VRaddVegetationToAutoRigRefreshSelect `;

	$sep1 = `separator -w $w2`;


//name

	$text2 = `text -l "give a name for the autoRig : "`;
	$textFd2 = `textField -en 1 -w $w2  S100VRNameCurveTF`;

	$sep2 = `separator -w $w2`;


//parent

	$text3 =  `text -l "choose a parent : "`;
	$textFd3 = `textField -en 1 -w $w2  S100VRChooseParentTF`;
	$buttonChooseParent = `button -w $w2 -label "choose Parent" -c S100VRAddCChooseParent s100VRAddCParentRootBt`;
	$subParent = `checkBox -v 1 -changeCommand  "s100VRAddCRefreshUI"  -label "parenting on root" s100VRAddCParentRootCb`;



	$sep3 = `separator -w $w2`;

//class

$text4 = `text -l "choose a class : "`;
$sub1 = `checkBox -onCommand "s100VRAddToARunCheckBoxClass(0)" -label "stern" s100VRCBStern`;
$sub2 = `checkBox -onCommand "s100VRAddToARunCheckBoxClass(1)" -label "leaf" s100VRCBLeaf`;
$sub3 = `checkBox -onCommand "s100VRAddToARunCheckBoxClass(2)" -label "flower" s100VRCBFlower`;
$sub4 = `checkBox -onCommand "s100VRAddToARunCheckBoxClass(4)" -label "fruit" s100VRCBfruit`;


	$sep4 = `separator -w $w2`;

//animation
$text5 = `text -l "option for animation : "`;

$textND = `text -l "divisions :"`;
$intNumber = `intField -v 10 -minValue 2 -maxValue 50 s100VRAddCNumberOfDivInt `;
$Asub1 = `checkBox   -v 1 -label "controllers for animator" s100VRCBControllerForAnim`;
$Asub2 = `checkBox   -label "connected To world(wind effect)" s100VRCBconnectedToW`;

	$sep5 = `separator -w $w2`;

//add

	$butAdd= `button -w $w2 -label "add //modify to autoRig" -c s100VRAddCToARCheck` ;

	formLayout -e

//select
	-attachForm $text1 "top" 5
	-attachForm $text1 "left" 20
	-attachControl $textFd1 "top" 5 $text1
	-attachControl $buttonRefreshC "top" 5 $textFd1

	-attachControl $sep1 "top" 5 $buttonRefreshC


//name
	-attachForm $text2 "left" 20

	-attachControl $text2 "top" 5 $sep1
	-attachControl $textFd2 "top" 5 $text2



	-attachControl $sep2 "top" 5 $textFd2

//parent

	-attachForm $text3 "left" 20
	-attachControl $text3 "top" 5 $sep2
	-attachControl $textFd3 "top" 5 $text3
	-attachControl $buttonChooseParent "top" 5 $textFd3
	-attachControl $subParent "top" 5 $buttonChooseParent


	-attachControl $sep3 "top" 5 $subParent

//class
	-attachForm $text4 "left" 20
	-attachControl $text4 "top" 5 $sep3
	-attachControl $sub1 "top" 5 $text4
	-attachControl $sub2 "top" 5 $sub1
	-attachControl $sub3 "top" 5 $sub2
	-attachControl $sub4 "top" 5 $sub3


	-attachControl $sep4 "top" 5 $sub4

//animation
	-attachForm $text5 "left" 20
	-attachControl $text5 "top" 5 $sep4
	-attachControl $textND "top" 5 $text5
	-attachControl $intNumber "top" 5 $text5
	-attachControl $intNumber "left" 5 $textND
	-attachControl $Asub1 "top" 5 $intNumber
	-attachControl $Asub2 "top" 5 $Asub1

	-attachControl $sep5 "top" 5 $Asub2

//add

	-attachControl $butAdd "top" 5 $sep5


	s100VRAddCurveToAutoRigFL;


	window -e  -w $weight -h 540  -s 0  s100VRaddVegetationToAutoRigUI;
	showWindow;
s100VRAddCRefreshDivisionUI;
s100VRAddCRefreshUI;

}

//s100VRaddVegetationToAutoRigUI;

global proc S100VRAddCChooseParent()
{

$var = `ls -sl`;
	if (size($var) > 0)
	{


	textField -e -tx $var[0]  S100VRChooseParentTF ;

    }else{
	warning "select at the object that will be parent" ;
    }

}


global proc s100VRAddCRefreshUI()
{
//check box parent
int $subParent = `checkBox -q -v s100VRAddCParentRootCb`;
int $modify = abs($subParent -1 ) ;

	textField -e -en $modify  S100VRChooseParentTF;
	button -e -en $modify s100VRAddCParentRootBt ;

string $obj = `textField -q -tx S100VRAddCurveTF `;
if ($obj != "")
	{
	$start = startString ($obj , 4) ;

		if($start == "VRAR" )
		{

		$name = substituteAllString ($obj , "VRAR_","");
		$name = substituteAllString ($name  , "_curv","");
		$name = substituteAllString ($name  , "_loc","");

		textField -e -tx $name  S100VRNameCurveTF;

		string $listP[] = `listRelatives -p $obj`;
		string $fListP[] = `listRelatives -f -p $obj`;
			if(`gmatch $fListP[0] "*autoRigCurve_grp*"`)
			{
				if( $listP[0] !=  "autoRigCurve_grp")
				{
				textField -e -tx $listP[0]  S100VRChooseParentTF;
				checkBox -e -v 0 s100VRAddCParentRootCb;
				button -e -en 1 s100VRAddCParentRootBt;


                }




            }
		$nameLocGrp = substituteAllString ($obj , "_curv","_grp");
			if (`objExists $nameLocGrp`)
				{
				$lit = `listRelatives -c $nameLocGrp`;
				$v = size($lit) -1 ;
				intField -e -v $v  s100VRAddCNumberOfDivInt ;
                }

			if (`attributeExists "class" $obj`)
				{
				$at  = `addAttr  -q -enumName   ($obj +".class")`;
				$cap = `s100capitalizeFirstLetter($at) `;
				$ckBox = "s100VRCB" + $cap ;
				checkBox -e -value 1  $ckBox;
				}

			if (`attributeExists "ctrlAnim" $obj`)
				{
				$v = `getAttr ($obj +".ctrlAnim" ) `;
				checkBox -e -value $v  s100VRCBControllerForAnim;
                }
			if (`attributeExists "connectToWorld" $obj`)
				{
				$v = `getAttr ($obj +".connectToWorld" ) `;
				checkBox -e -value $v  s100VRCBconnectedToW;
                }





		}
    }

}

global proc s100VRAddCRefreshDivisionUI()
{
string $obj = `textField -q -tx S100VRAddCurveTF `;
if ($obj != "")
	{
	string $list[] = `listRelatives -s $obj`;

		if (size($list[0])>0)
		{
		$type = `nodeType $list[0]`;
			if ($type == "nurbsCurve")
			{

			$length = `getCurveDistance($obj) `;
			$nValue = $length / 10 ;
   			int $test = $nValue + 1 ;
			intField -e -v $test s100VRAddCNumberOfDivInt ;
			select $obj ;
            }

        }
    }
}
global proc s100VRAddToARunCheckBoxClass(int $int)
{
string $cBox[3] = {"s100VRCBStern","s100VRCBLeaf","s100VRCBFlower","s100VRCBfruit"};


	for($i = 0 ; $i < size($cBox); $i++)
	{
		if ($i != $int)
				checkBox -e -value 0 $cBox[$i];

    }



}

global proc s100VRaddVegetationToAutoRigRefreshSelect()
{
string $var[] = `ls -sl`;

textField -e -tx $var[0] S100VRAddCurveTF;

}