global proc s100FileManagerUI()
{
global string  $base_script_path;
global string $base_prodFilesSystem ;
$path = substituteAllString ($base_script_path , ";","");


$base_prodFilesSystem = $path + "/prodFilesSystem/" ;
$pas = $base_prodFilesSystem  + "password.s100" ;
$fileList = `getFileList -fld $base_prodFilesSystem -filespec "*.s100"`;


	if(size($fileList) > 0)
	{

	if(`window -ex 	s100FileManagerUI`)
		deleteUI s100FileManagerUI;

	window -title "studio 100 Animation Files Manager"  -h 400  s100FileManagerUI;
	columnLayout -adjustableColumn true s100FileManagerUICLMain;
	s100FileManagerUIMenu ;
	s100FileManagerUIFormLayout ;

	window -e -h 575 -w 680 -sizeable 0  s100FileManagerUI;
	showWindow;
	s100FileManagerUIRefreshProd ;

	s100FileManagerUIChangeProd ;

    }else{
	s100FileManagerCreatePasswordUI ;

    }
}





global proc s100FileManagerUIFormLayout()
{



formLayout s100FileManagerUIFLMain;

	$txLibray = `text -l "PROD"`;
	$prodMenu = `optionMenu -cc s100FileManagerUIChangeProd s100FileManagerUIOMProd`;

$tab = `tabLayout -innerMarginWidth 5 -innerMarginHeight 5 s100FileManagerUITLMain`;
formLayout -edit

	 //Prod
    -attachForm $txLibray "top"    10
    -attachForm $txLibray "left"   10
	-attachForm $prodMenu "top"    5
	-attachForm $prodMenu "left"   60

    -attachControl s100FileManagerUITLMain "top"   5 $prodMenu
     -attachForm s100FileManagerUITLMain "left"   0
     -attachForm s100FileManagerUITLMain "bottom" 0
     -attachForm s100FileManagerUITLMain "right"  0


     s100FileManagerUIFLMain;

s100FileManagerUIShootLayout ;
s100FileManagerUIAssetLayout ;


     tabLayout -cc s100FileManagerRefreshUI -edit
         -tabLabel s100FileManagerUIFLShot "Shots" -tabLabel s100FileManagerUIFLAsset "Assets"
         s100FileManagerUITLMain;
//	tabLayout -e -selectTab s100FileManagerUIFLAsset s100FileManagerUITLMain;
    setParent ..;



}






global proc s100FileManagerUIMenu()
{
menuBarLayout s100FileManagerUIMLMain;
menu -label "File";
        menuItem -c s100ProdManagerUI -label "Prod Manager";
	    menuItem -c s100FileManagerUI -label "refresh";




    menu -label "Edit";
        menuItem -en 0  -label "Preference";




    menu -en 0 -label "Help" -helpMenu true;
        menuItem -en 0   -label "help";
        menuItem -en 0  -label "About...";

    setParent ..;

}


s100FileManagerUI;