global proc s100ProdManagerAddSqPre()
{
$selectItem  = `textScrollList -q -selectItem  s100ProdManagerUITSProd `;
	if (size($selectItem) > 0 )
	{
	s100ProdManagerAddSqUI ;

    }else{
	warning "select a prod" ;
    }
}

global proc s100ProdManagerAddSqUI()
{
if(`window -ex 	s100ProdManagerAddSqUI`)
	deleteUI s100ProdManagerAddSqUI;

$ep = `optionMenu -q -v s100ProdManagerUIFormLayoutOPEP`;
$selectItem  = `textScrollList -q -selectItem  s100ProdManagerUITSProd `;
$prod = $selectItem[0] ;


$test = s100ASGetAllSqFolders( $prod ,  $ep);
$si = size($test) - 1  ;
string $last ;
	if(size($test) >0)
		$last = substituteAllString($test[$si] , "Sq" ,"") ;


int $heigh = 96 ;
int $width = 100;
window -title "s100 ADD Seq"   s100ProdManagerAddSqUI;
columnLayout -adj 1 s100ProdManagerAddSqUIFLMain;


$textName = `text -label "Choose a name"` ;
$textFieldName = `textField -tx $last -w  ($width * .8 ) s100ProdManagerAddSqUITFName  `;

$separator = `separator -w ($width *.91)`;


$butCrea = `button -c s100ProdManagerAddSq -label "add Seq" -w ($width *.8)` ;

$side = 5 ;
window -e -h $heigh  -w $width  -sizeable 0  s100ProdManagerAddSqUI;
	showWindow;

}


global proc s100ProdManagerAddSq()
{
$toCreate = `textField -q -tx s100ProdManagerAddSqUITFName  `;
s100ProdManagerAddSqSt($toCreate ) ;

}


global proc s100ProdManagerAddSqSt(string $toCreate )
{

$ep = `optionMenu -q -v s100ProdManagerUIFormLayoutOPEP`;
$selectItem  = `textScrollList -q -selectItem  s100ProdManagerUITSProd `;
$prod = $selectItem[0] ;

$dept = `optionMenu -q -v s100ProdManagerUIFormLayoutOPDepartment`;

global string $base_prodFilesSystem ;

$file = s100assetManagerGetEpPath($prod)   ;

$path = $file;
$path +=  $ep +"/"+$dept +"/" ;

$path += "Sq" + $toCreate+"/" ;



	if(size($toCreate) > 0 )
	{
	sysFile -md $path ;
	deleteUI s100ProdManagerAddSqUI;
	s100ProdManagerUIRefresh ;
	optionMenu -e -v ("Sq" + $toCreate) s100ProdManagerUIFormLayoutOPSeq ;

    } else{
	warning "choose a name !" ;
    }





}
