global proc s100VRandomizeSprite()
{
	$var = `ls -type "transform" "*:root_ctrl"`;

		for($vart in $var)
		{
		$obj = ($vart +".spriteNumber") ;
			if(`attributeExists "spriteNumber" $vart`)
			{

			float  $query = `addAttr -q -maxValue $obj ` ;

			int $rand = rand($query ) + 1;
			setAttr ($vart +".spriteNumber") $rand;
			}

        }

}


global proc s100VRandomizeSpritePlacement()
{
	$var = `ls -type "transform" "*:root_ctrl"`;

		for($vart in $var)
		{
		float $randX = rand(400) -200 ;
		setAttr ($vart +".tx") $randX ;
		float $randX = rand(200) -100 ;
		setAttr ($vart +".tz") $randX ;



        }


}



global proc s100VRandomizeSpriteScale()
{
	$var = `ls -type "transform" "*:root_ctrl"`;

		for($vart in $var)
		{
		float $randX = rand(.5) + 0.8  ;
		setAttr ($vart +".sx") $randX ;
		setAttr ($vart +".sy") $randX ;
		setAttr ($vart +".sz") $randX ;



        }


}



global proc s100VRandomizeRootRotRoot()
{
	$var = `ls -type "transform" "*:root_ctrl"`;

		for($vart in $var)
		{
		float $randX = rand(360)  ;
		setAttr ($vart +".ry") $randX ;




        }


}
