//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 4/10/2013
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slFilesConvertToMap(string $project,string $path)
{
	if ($project=="")
	{
		$project =zwGetProject("");
	}

	string $mayaLoc = `getenv MAYA_LOCATION`;
	string $cmd=$mayaLoc+"/bin/imf_copy.exe";
	string $mapFolder=$path+"/"+$project+"/map/";

	string $files[] = `ls -type file`;

	int $amount=0;
	progressWindow -title "Doing Nothing" -progress $amount -status "Sleeping: 0%" -isInterruptable true;

	for ($file in $files)
	{
		if ( `progressWindow -query -isCancelled` ) break;
		if ( `progressWindow -query -progress` > size($files) ) break;		
		$amount++;
		int $percent=$amount/size($files);
		progressWindow -edit  -progress $amount  -status ("Convert Map: "+$percent+"%");
		
		string $image= `getAttr ($file+".fileTextureName")`;
		$image = substituteAllString($image,"\\","/");
		string $map;
		if (endsWith($image,".map"))
			$map=$mapFolder+match(($project+".*$"),$image);
		else
			$map=$mapFolder+match(($project+".*$"),$image)+".map";

		//string $mapName=basename($image,"\\/")+".map";
		//string $map=$mapFolder+match("01_main_pack.*$",$image)+".map";
		print ($map+"\n");
		string $folder = substituteAllString($map,basename($map,"\\/"),"");
		sysFile -md $folder;
		if(!`filetest -r $map`)
			system($cmd+" "+$image+" "+$map);
		setAttr -type "string" ($file+".fileTextureName") $map;
	}
	progressWindow -endProgress;
}