//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////


global proc vvCGRepairTexturePathMA()
{
	if (`window -q -exists vvCGRepairTexturePathMAWin`)
		deleteUI -window vvCGRepairTexturePathMAWin;

	window -title "Batch Run" -resizeToFitChildren true -h 210 vvCGRepairTexturePathMAWin;
		
		columnLayout -adj true ;
			text -label "FILES:";
			textScrollList -numberOfRows 8 -allowMultiSelection true -w 400 vvCGRepairTexturePathMAWin_fileList;
			string $form = `formLayout `;
				string $butadd = `button -label "Add"  -command "vvCGRepairTexturePathMAAddFile" `;
				string $butrem = `button -label "Remove" -command "vvCGRepairTexturePathMARemoveFile" `;
			setParent ..;
			formLayout -edit
			-af		$butadd		"left"	5
			-ap		$butadd		"right"	0	49
			-ac		$butrem		"left"	10	$butadd
			-af		$butrem		"right"	5
			$form;
			separator -st "doubleDash" -h 10;
			button -label "Run" -h 20 -command "vvCGRepairTexturePathMARun" ;
		setParent ..;	
	showWindow vvCGRepairTexturePathMAWin;
}

global proc vvCGRepairTexturePathMAAddFile()
{
	string $buf[] = `idmtFileDialog -filter "Maya Scene (*.mb;*.ma)|*.mb;*.ma||" -m`;

	string $objFiles[] = `textScrollList -q -ai vvCGRepairTexturePathMAWin_fileList`;
	for ($item in $buf)
	{
		if (!stringArrayCount($item,$objFiles))
		{
			textScrollList -e -a $item vvCGRepairTexturePathMAWin_fileList;
		}
	}
}

global proc vvCGRepairTexturePathMARemoveFile()
{
	string $selected[] = `textScrollList -q -selectItem vvCGRepairTexturePathMAWin_fileList`;

	for ($item in $selected)
		textScrollList -edit -removeItem $item vvCGRepairTexturePathMAWin_fileList;
}

global proc vvCGRepairTexturePathMARun()
{
	string $allFiles[] = `textScrollList -q -ai vvCGRepairTexturePathMAWin_fileList`;
	for ($file in $allFiles)
	{
		vvCGRepairTexturePathCMD $file;
	}

}

global proc vvCGRepairTexturePathCMD(string $file)
{
	string $buff[] = stringToStringArray($file,"\\/");
	string $filename = $buff[size($buff)-1];
	
	string $dir = "D:/RenderBus/";
	sysFile -md $dir;
	
	string $newFile = $dir+$filename;
	$fileId = `fopen $newFile w`;	
	fprint $fileId "" ;
	fclose $fileId;

	$fileId = `fopen $newFile w`;	
	$fileIdOld=`fopen $file r`;
	string $nextLine = `fgetline $fileIdOld`;
	while(size($nextLine)>0)
	{
		string $new;
		string $temp="";
		if (`gmatch $nextLine "*01_main_pack*sourceimages*"`)
		{
			clear $buff;
			$buff=stringToStringArray($nextLine,"\"");
			string $old="";
			for ($rep in $buff)
			{
				if (`gmatch $rep "*01_main_pack*sourceimages*"`)
				{
					$old=$rep;
				}
			}
			string $match=`match "01_main_pack.*$" $old`;
			$temp=substituteAllString($nextLine,$old,$match);
		}
		else
			$temp = $nextLine;

		fprint $fileId $temp;

		//print $temp;
		//print "\n";
		$nextLine = `fgetline $fileIdOld`;
		$temp="";
	}
	fclose $fileIdOld;
	fclose $fileId;
}