




global proc vvSceneOpenScripts()
{
	

	string $turtleNodess[] = `ls "Turtle*"`;

	for ($node in $turtleNodess){
	    lockNode -lock 0 $node;
	    delete $node;
	}
	
	string $cameraShapes[] = `ls -long -cameras`;
	for ($cameraShape in $cameraShapes)
	{
		if (`match "|[cC][aA][mM]_[^|]+|[^|]+$*" $cameraShape` != "")
		{
			zwSetAttrInt ($cameraShape + ".renderable") true;
			break;
		}
		else
		{
			zwSetAttrInt ($cameraShape + ".renderable") false;
		}
	}
	
	if (!`pluginInfo -query -loaded "Mayatomr.mll"`)
		loadPlugin "Mayatomr.mll";
	
	miCreateDefaultNodes();
	miCreateOtherOptionsNodesForURG();
	setAttr defaultRenderGlobals.currentRenderer -type "string" "mentalRay" ;
	//setAttr "defaultRenderGlobals.imageFormat" 7;


	setAttr "defaultResolution.width" 1280;
	setAttr "defaultResolution.height" 720;
	setAttr "defaultResolution.deviceAspectRatio" 1.777;
	setAttr "defaultResolution.pixelAspect" 1.0;
	
	setAttr -type "string" "defaultRenderGlobals.currentRenderer" "mentalRay" ;
	setAttr "miDefaultOptions.minSamples" 0;
	setAttr "miDefaultOptions.maxSamples" 2;
	setAttr "miDefaultOptions.contrastR" 0.02;
	setAttr "miDefaultOptions.contrastG" 0.02;
	setAttr "miDefaultOptions.contrastB" 0.02;
	setAttr "miDefaultOptions.maxReflectionRays" 1;
	setAttr "miDefaultOptions.maxRefractionRays" 1;
	setAttr "miDefaultOptions.maxRayDepth" 2;
	setAttr "miDefaultOptions.maxShadowRayDepth" 3;
	setAttr "miDefaultOptions.jitter" 1;
	setAttr "miDefaultOptions.filter" 2;
	setAttr "miDefaultFramebuffer.datatype" 16;
	//setAttr "defaultRenderGlobals.imageFormat" 51;
	//setAttr -type "string" "defaultRenderGlobals.imfPluginKey" "exr";
	
	
	

	python("execfile(r'//file-cluster/gdc/Resource/Support/Maya/projects/VickytheViking/vv_sop.py')");
  zwSceneOpenedScriptJobStartEnd();
	//设置贴图相对路径，renderbus使用
	//vvCGTextureRelativePathForRB();
	
}