//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-7-19
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc rrGeocacheEnableSwitch(int $enable)
{
	string $cacheNodes[] = `ls -type cacheFile`;
	for ($cn in $cacheNodes)
	{
		setAttr ($cn+".enable") $enable;
	}
}

global proc rrGeocacheEnable()
{
	if (`window -ex rrGeocacheEnableWin`)
		deleteUI rrGeocacheEnableWin;
	
	window -title "Cache开关" rrGeocacheEnableWin;
		columnLayout -adj 1 ;
			button -l "开" -h 30 -c "rrGeocacheEnableSwitch 1";
			button -l "关" -h 30 -c "rrGeocacheEnableSwitch 0";
		setParent ..;
	showWindow rrGeocacheEnableWin;
}