//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc rrRenderRepairTaidragonUV()
{
	string $sel[] = `ls -sl`;
	if (size($sel) == 1)
	{
		file -import -type "mayaAscii" -ra true -namespace "Repair_UV" -options "v=0"  -pr "//file-cluster/GDC/Resource/Support/Maya/projects/RainbowRiders/import/MSH_body.ma";

		select -r Repair_UV:MSH_body ;
		select -tgl $sel[0];
		transferAttributes -transferPositions 0 -transferNormals 0 -transferUVs 2 -transferColors 0 -sampleSpace 4 -sourceUvSpace "map1" -targetUvSpace "map1" -searchMethod 3-flipUVs 0 -colorBorders 1 ;

		setAttr Repair_UV:MSH_body.v 0;
	}
}