global proc s100VSMcreatePresetCh()
{
$name = `textFieldGrp -q -text  s100VSRMTextName`;
$vers = `s100returnDifferentAttributForLightAmbiance`;
float $values[] ;
	for($i = 0 ; $i < size($vers) ; $i++)
	{
	$values[$i] = `getAttr ($vers[$i])`;
    }

	if(size($name) >0)
	{
	$cap = capitalizeString($name) ;
	$paht = `s100VSMlocatePresetFolder`;
 	string $file =$paht + $cap +".vsmp";
	$ch = `filetest -e $file`;
		if($ch == 0 )
		{
		s100VSMcreatePreset($cap,$values);
        }else{

		$message = "preset already exists, delete it ?";
		$returnConf = `confirmDialog -title "delete existing preset?" -message $message
			-button "Yes" -button "No" -button  "Cancel" -defaultButton "Yes"
			-cancelButton "cancel" -dismissString "No"`;

			if($returnConf == "Yes")
			{
			sysFile -delete $file ;
			s100VSMcreatePreset($cap,$values);
			}
			if($returnConf == "No")
			{
			s100VSMcreatePreset($cap,$values);
			}
		}



    }else{
	warning "name is empty" ;
    }

}




global proc s100VSMcreatePreset(string $name, float $values[])
{
//$name = $cap

s100VSMwritePresetFile($name,$values);
$pathImage = `s100VSMlocateImageFolder `;
$im = $pathImage + $name +".bmp" ;
setAttr  -type "string" "defaultRenderGlobals.imageFilePrefix" $im;
setAttr "defaultRenderGlobals.animation" 0;

$test1 = `Mayatomr -cam "render_cam" -pv -xResolution 115 -yResolution 115`;
sysFile -rename $im $test1 ;



print "preset created" ;
s100VSMUI;
}

global proc  s100VSMwritePresetFile(string $name, float $values[])
{
$paht = `s100VSMlocatePresetFolder`;
string $file =$paht + $name +".vsmp";
string $toWrite = "";
	for($i = 0 ; $i < size($values) ; $i++)
	{
	string $st = 	$values[$i] ;
	$toWrite += $st ;
	$toWrite += ";";

    }

$fileId=`fopen $file "w"`;


	fwrite $fileId $toWrite;


fclose $fileId;


}
//$name = "Day" ;

global proc string[] s100VSMreadPresetFile(string $name)
{
$paht = `s100VSMlocatePresetFolder`;
string $file =$paht + $name +".vsmp";

$fileId=`fopen $file "r"`;
string $s;
$s=`fread $fileId $s`;
fclose $fileId;

string $valuesS[]  = stringToStringArray($s ,";");
return $valuesS ;

}