//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////


global proc slWinxShowHideCons(string $part)
{
	string $sl[] = `ls -sl`;
	if (size($sl) == 0)
		return ;
	string $buff[];
	int $num = `tokenize $sl[0] ":" $buff`;
	string $char = `substring $sl[0] 1 (size($sl[0])-size($buff[$num-1]))`;	

	
	string $buff[];
	string $scenename = `file -q -sn -shn`;
	tokenize $scenename "_" $buff;
	$scenename = $buff[0];
	
	switch ($part)
	{
		case "keyTsm" :
			slSelTSMCtrlFromSet;
			source performSetKeyframeArgList;
			performSetKeyframeArgList 1 {"0", "animationList"};
			break;
		case "initTsm" :
			slSelTSMCtrlFromSet;
			string $ctrls[] = `ls -sl`;
			for ($ctrl in $ctrls)
			{
				if (!`gmatch $ctrl "*:Character"`)
				{
					string $attrs[] = `listAttr -k $ctrl`;
					for ($item in $attrs)
					{
						if ($item == "translateX" ||$item == "translateY" ||$item == "translateZ" ||$item == "rotateX" ||$item == "rotateY" ||$item == "rotateZ")
						{
							setAttr ($ctrl + "." + $item ) 0;
						}
						if (($scenename=="bu"||$scenename=="BU"||$scenename=="Bu"||$scenename=="bU") && (endsWith($ctrl,"Tail_ctrl") || endsWith($ctrl,"finger_control")))
						{
							if ($item != "scaleX" && $item != "scaleY" && $item != "scaleZ")
							{
								setAttr ($ctrl + "." + $item ) 0;
							}
						}
					}
				}
			}
			break;
	}
}

global proc slSelTSMCtrlFromSet()
{
	string $sl[] = `ls -sl`;
	if (size($sl) == 0)
		return ;
	string $buff[];
	int $num = `tokenize $sl[0] ":" $buff`;
	string $char = `substring $sl[0] 1 (size($sl[0])-size($buff[$num-1]))`;	


	select -cl;
	string $ctrl;
	$ctrls=`sets -q ($char+"TSM2Controls")`;
	for ($ctrl in $ctrls)
	{
		select -tgl $ctrl;
		if (`objExists ($char + "LeftArm_Arm_IK_ORIENT")`)
		{
			select -add ($char + "LeftArm_Arm_IK_ORIENT");
			select -add ($char + "RightArm_Arm_IK_ORIENT");
		}
	}
	
	string $buff[];
	string $scenename = `file -q -sn -shn`;
	tokenize $scenename "_" $buff;
	$scenename = $buff[0];
	if ($scenename=="bu"||$scenename=="BU"||$scenename=="Bu"||$scenename=="bU")
	{
		select -add ($char + "Tail_ctrl");
	}
}

global proc slTransTSMCtrl()
{
	string $sl[] = `ls -sl`;
	if (size($sl) == 0)
		return ;
	string $buff[];
	int $num = `tokenize $sl[0] ":" $buff`;
	string $char = `substring $sl[0] 1 (size($sl[0])-size($buff[$num-1]))`;	


	currentTime 1001;
	slWinxShowHideCons("keyTsm");
	slSelTSMCtrlFromSet;
	timeSliderCopyKey;
	currentTime 980;
	evalEcho "timeSliderPasteKey false";
	currentTime 950;
	slWinxShowHideCons("initTsm");
	slWinxShowHideCons("keyTsm");
}
