/// Copyright (C) 2000-2008 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2008/05/19
///
/// Description: 

global proc slPPToolsWin()
{
    string $tipsPath = "D:/backup_mel/pic/tips/";
	string $tipsFiles[] = `getFileList -filespec ($tipsPath+"*.bmp")`;
	int $tipsIndex = rand(size($tipsFiles));


	if (`window -exists PPToolsWindow`) {
        deleteUI -window PPToolsWindow;
    }
	
    // PPTools Window
    window -menuBar true -resizeToFitChildren false -sizeable true -title "P-P Tools 1.0.0" -in "P-P Tools" PPToolsWindow;
		
	// 工具栏
		menu -label "工具栏  ";
			menuItem -label "暂时等吧..." ;
		menu -label "环节  ";
			menuItem -label "继续等吧..." ;
		menu -label "按钮  ";
			menuItem -label "创建按钮  " -c "slPPToolsCommonCreatWin";
			menuItem -label "编辑按钮  " -c "";
			menuItem -label "删除按钮  " -c "";

		string $mainColumnLayout = `columnLayout -adjustableColumn true -rs 4 `;
	
	//Tips栏
			symbolButton -image ($tipsPath+$tipsFiles[$tipsIndex]) -command ("");
			setParent ..;
	
	//通用工具栏
			frameLayout -label "通用工具栏" -bv false  -cll true PPToolsWindow_toolbar;
				tabLayout PPToolsWindow_toolbar_tab;
					formLayout -h 100 PPToolsWindow_toolbar_form;
						shelfLayout -cwh 50 50 -st "iconAndTextVertical" PPToolsWindow_toolbar_shelf;
						setParent ..;
					formLayout -edit
						-af		PPToolsWindow_toolbar_shelf		"top"		1 
						-af		PPToolsWindow_toolbar_shelf		"left"		1
						-af		PPToolsWindow_toolbar_shelf		"right"		1
						-af		PPToolsWindow_toolbar_shelf		"bottom"	1
					PPToolsWindow_toolbar_form;
					setParent ..;
				tabLayout -edit -tv true
					-tabLabel PPToolsWindow_toolbar_form "default"
				PPToolsWindow_toolbar_tab;
				setParent ..;
			setParent ..;

	/*
	//环节工具栏
			string $specialFR = `frameLayout -label "环节工具栏" -labelAlign "top"  -cc "" -cll true  -borderStyle "etchedIn"`;
				tabLayout PPToolsWindow_sp_tab;
					//模型
					formLayout -h 200 PPToolsWindow_sp_model;
						shelfLayout -cwh 50 50 -st "iconAndTextVertical" PPToolsWindow_sp_model_shelf;
							shelfButton -annotation "please select correct path" -style "iconAndTextVertical" -image1 "commandButton.xpm" -l "模型" -fn "boldLabelFont";
						setParent ..;
					formLayout -edit
						-af		PPToolsWindow_sp_model_shelf		"top"		1 
						-af		PPToolsWindow_sp_model_shelf		"left"		1
						-af		PPToolsWindow_sp_model_shelf		"right"		1
						-af		PPToolsWindow_sp_model_shelf		"bottom"	1
					PPToolsWindow_sp_model;
					setParent ..;
					
					//设置
					formLayout -h 200 PPToolsWindow_sp_rig;
						shelfLayout -cwh 50 50 -st "iconAndTextVertical" PPToolsWindow_sp_rig_shelf;
							shelfButton -annotation "please select correct path" -style "iconAndTextVertical" -image1 "commandButton.xpm" -l "设置" -fn "boldLabelFont";
						setParent ..;
					formLayout -edit
						-af		PPToolsWindow_sp_rig_shelf		"top"		1 
						-af		PPToolsWindow_sp_rig_shelf		"left"		1
						-af		PPToolsWindow_sp_rig_shelf		"right"		1
						-af		PPToolsWindow_sp_rig_shelf		"bottom"	1
					PPToolsWindow_sp_rig;
					setParent ..;

				tabLayout -edit
					-tabLabel PPToolsWindow_sp_model "模型"
					-tabLabel PPToolsWindow_sp_rig	 "设置"
				PPToolsWindow_sp_tab;
				setParent ..;
			setParent ..;*/

	//输出信息栏
			string $outputFR = `frameLayout -h 200 -label "输出信息" -labelAlign "top"  -cc "" -cll true  -borderStyle "etchedIn"`;
			setParent ..;
		

	showWindow PPToolsWindow;
}

global proc slPPToolsCommonCreatWin()
{
	if (`window -exists slPPToolsCommonCreatWindow`) {
        deleteUI -window slPPToolsCommonCreatWindow;
    }
	
    // 通用工具栏按钮创建面板
    window  -resizeToFitChildren true -s true -mxb false -mnb false -title "创建按钮" slPPToolsCommonCreatWindow;
		columnLayout -adjustableColumn true -rs 4 ;
			text -label "按钮名称" -align "left";
			textField slPPToolsCommonCreatWindow_name;
			text -label "按钮功能说明" -align "left";
			textField slPPToolsCommonCreatWindow_anno;
			
			text -label "按钮图标" -align "left";
			string $picFO = `formLayout `;
				picture -image "commandButton.xpm"	slPPToolsCommonCreatWindow_pic;
				string $picBut = `button -label "选择图标" -c "slPPToolsCommonPicBut"`;
			setParent ..;
			formLayout -edit 
				-af slPPToolsCommonCreatWindow_pic	 "top"	1
				-af slPPToolsCommonCreatWindow_pic	 "left"	1

				-af $picBut	"top"	1
				-ac $picBut "left"	1	slPPToolsCommonCreatWindow_pic
			$picFO;
			
			text -label "按钮功能/程序" -align "left";
			scrollField -wordWrap true -text "//请添加需要的Mel，参照MayaShelf方法\n" -h 200 slPPToolsCommonCreatWindow_input;
			button -label "确认" -c "slPPToolsCommonCreat";
		setParent ..;
	showWindow slPPToolsCommonCreatWindow;
}

global proc slPPToolsCommonPicBut()
{
	string $newPic = `xpmPicker -fn "" -parent ""`;
	if ($newPic != "")
	{
		picture -e -image $newPic slPPToolsCommonCreatWindow_pic;
	}
}

global proc slPPToolsCommonCreat()
{
	string $shelfName = `textField -q -text slPPToolsCommonCreatWindow_name`;
	string $shelfAnno = `textField -q -text slPPToolsCommonCreatWindow_anno`;
	string $shelfPic = `picture -q -image slPPToolsCommonCreatWindow_pic`;
	string $shelfCmd = `scrollField -q -text slPPToolsCommonCreatWindow_input`;
	
	shelfButton -style "iconAndTextVertical" -fn "boldLabelFont" -l $shelfName -annotation $shelfAnno  -image1 $shelfPic -c $shelfCmd -p PPToolsWindow_com_shelf;
	
	deleteUI slPPToolsCommonCreatWindow;
}