
global proc cl_replaceReference()

{
	string $refPaths[]=`file -q -r`;
	for($ref in $refPaths)
	{
	    
	    string $refRN = `file -q -rfn $ref`;
	    string $animfile =`match "ms_anim" $ref`;
	    if (size($animfile)!=0)
	    {
		string $newrefname = `substitute "anim" $ref "cache"`;
		string $full =`workspace -expandName $newrefname`;
		
	   if (`filetest -f $full`)
		{
			file -loadReference $refRN  -type "mayaAscii" -options "v=0" $newrefname;
		}
	    }

	}
}


