

global proc cl_RenderTools_Create_Layer_UI_MR()
{
    // Get the dialog's formLayout.
    string $form = `setParent -q`;

    formLayout -e -width 20 $form;

	string $t = `text -l "层名"`;
    textField -w 30 "cl_RenderTools_Create_Layer_name";
		popupMenu -button 1;
			menuItem -label "Beauty" -command "textField -edit -text \"Beauty\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "BW" -command "textField -edit -text \"BW\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Light" -command "textField -edit -text \"Light\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Depth" -command "textField -edit -text \"Depth\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Idpass01" -command "textField -edit -text \"Idpass\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Idpass02" -command "textField -edit -text \"Idpass\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Eye" -command "textField -edit -text \"Eye\" \"cl_RenderTools_Create_Layer_name\"";
		popupMenu -button 3;
			menuItem -label "Beauty" -command "textField -edit -text \"beauty\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "BW" -command "textField -edit -text \"BW\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Light" -command "textField -edit -text \"Light\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Depth" -command "textField -edit -text \"Depth\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Idpass01" -command "textField -edit -text \"Idpass\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Idpass" -command "textField -edit -text \"Idpass\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "Eye" -command "textField -edit -text \"Eye\" \"cl_RenderTools_Create_Layer_name\"";

    setFocus "cl_RenderTools_Create_Layer_name";
    string $b1 = `button -l "建层"    -c "cl_RenderTools_Create_Layer_Button();layoutDialog -dismiss \"Abort\""`;

	formLayout -edit
		-attachForm            $t   "top"    5
		-attachForm            $t   "left"   5
		-attachNone            $t   "bottom"
		-attachForm            $t   "right"  5   	
		
		-attachControl         "cl_RenderTools_Create_Layer_name"   "top"    5 $t
		-attachForm            "cl_RenderTools_Create_Layer_name"   "left"   5
		-attachNone            "cl_RenderTools_Create_Layer_name"   "bottom"
		-attachForm            "cl_RenderTools_Create_Layer_name"   "right"  5
		
		-attachControl         $b1  "top"    5 "cl_RenderTools_Create_Layer_name"
		-attachForm            $b1  "left"   25
		-attachNone            $b1  "bottom"
		-attachForm            $b1  "right"  25 

    $form;
    
}
global proc cl_RenderTools_Create_Layer_UI_MS()
{
    // Get the dialog's formLayout.
    string $form = `setParent -q`;

    formLayout -e -width 20 $form;

	string $t = `text -l "层名"`;
    textField -w 30 "cl_RenderTools_Create_Layer_name";
		popupMenu -button 1;
			menuItem -label "ExpLine" -command "textField -edit -text \"ExpLine\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "OutLine" -command "textField -edit -text \"OutLine\" \"cl_RenderTools_Create_Layer_name\"";
		popupMenu -button 3;
			menuItem -label "ExpLine" -command "textField -edit -text \"ExpLine\" \"cl_RenderTools_Create_Layer_name\"";
			menuItem -label "OutLine" -command "textField -edit -text \"OutLine\" \"cl_RenderTools_Create_Layer_name\"";

    setFocus "cl_RenderTools_Create_Layer_name";
    string $b1 = `button -l "建层"    -c "cl_RenderTools_Create_Layer_Button();layoutDialog -dismiss \"Abort\""`;

	formLayout -edit
		-attachForm            $t   "top"    5
		-attachForm            $t   "left"   5
		-attachNone            $t   "bottom"
		-attachForm            $t   "right"  5   	
		
		-attachControl         "cl_RenderTools_Create_Layer_name"   "top"    5 $t
		-attachForm            "cl_RenderTools_Create_Layer_name"   "left"   5
		-attachNone            "cl_RenderTools_Create_Layer_name"   "bottom"
		-attachForm            "cl_RenderTools_Create_Layer_name"   "right"  5
		
		-attachControl         $b1  "top"    5 "cl_RenderTools_Create_Layer_name"
		-attachForm            $b1  "left"   25
		-attachNone            $b1  "bottom"
		-attachForm            $b1  "right"  25 

    $form;
    
}

global proc cl_RenderTools_Create_Layer_Button()
{
	global string $cl_RenderTools_Create_Layer_Name;
	$cl_RenderTools_Create_Layer_Name=` textField -q -tx "cl_RenderTools_Create_Layer_name"`;
	
}

global proc cl_RenderTools_MR_settings()
{
	source "//file-cluster/GDC/Resource/Support/Maya/scripts/zzjSetMentalrayQuality.mel";
	zzjSetMentalrayQuality("calimero");
	setMayaSoftwareFrameExt(3, 0);
        setAttr miDefaultOptions.contrastR 0.02;
        setAttr miDefaultOptions.contrastG 0.02;
        setAttr miDefaultOptions.contrastB 0.02;
        setAttr miDefaultOptions.contrastA 0.02;
	setAttr "miDefaultOptions.jitter" 1;
	setAttr  defaultRenderGlobals.extensionPadding 4;
	setAttr "miDefaultOptions.minSamples" 0;
	setAttr "miDefaultOptions.maxSamples" 2;
        setAttr "miDefaultOptions.filter" 2;
	setAttr "defaultRenderGlobals.imageFormat" 32;
}

global proc cl_RenderTools_MR()
{
	global string $cl_RenderTools_Create_Layer_Name;
	$cl_RenderTools_Create_Layer_Name="";
	layoutDialog -ui "cl_RenderTools_Create_Layer_UI_MR" -t "创建Mentalray渲染层";
	
	if ($cl_RenderTools_Create_Layer_Name=="")	return;
	cl_RenderTools_MR_settings;
	string $createRenderLayer=`createRenderLayer -makeCurrent -name $cl_RenderTools_Create_Layer_Name`;
	string $objselect[]=`ls -sl`;

	if ($cl_RenderTools_Create_Layer_Name == "Beauty")
	{
		string $lightsShape[] =`ls -lights`;
		for ($i=0;$i<size($lightsShape);$i++)
		{
			
			if (size($lightsShape)==0)
			{
				continue;
			}
			string $lights[]=` listRelatives -parent $lightsShape[$i]`;
			for($light in $lights)
			{
			select $light;
			HideSelectedObjects;
			}
	for ($obj in $objselect)
	{
		string $Iris = `match "MSH_iris_"$obj`;
		if (size($Iris)!=0 )
		    {
			select $obj;
			HideSelectedObjects;
		    }

	}
	}
		
		setAttr "defaultRenderGlobals.enableDefaultLight" 0;

	}

	if ($cl_RenderTools_Create_Layer_Name == "BW")
	{
	//	renderLayerBuiltinPreset occlusion $newLayer;
			select $objselect;
			source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_Render_BWshader.mel";
			cl_Render_BWshader;
			

	}
	if ($cl_RenderTools_Create_Layer_Name == "Light")
	{
			select $objselect;
			source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_materialtra_Assign.mel";
			cl_material_Lambert;   
			
	}
	if ($cl_RenderTools_Create_Layer_Name == "Depth")
	{
			select $objselect;
			source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_materialtra_Depth.mel";
			cl_material_Depth;  
			
			
	}
	if ($cl_RenderTools_Create_Layer_Name == "Eye")
	{
			for ($obj in $objselect)
			{
			string $Iris = `match "MSH_iris_"$obj`;
				
				if (size($Iris)==0)
				{
				select $obj;
				source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_materialtra_Assign.mel";
				cl_material_mat; 
				}
			}  
	
	}



}
global proc cl_RenderTools_MS()
{
	global string $cl_RenderTools_Create_Layer_Name;
	$cl_RenderTools_Create_Layer_Name="";
	layoutDialog -ui "cl_RenderTools_Create_Layer_UI_MS" -t "创建角色2D线渲染层";
	
	if ($cl_RenderTools_Create_Layer_Name=="")	return;
	
	$cl_RenderTools_Create_Layer_Name+="";
	string $createRenderLayer=`createRenderLayer -makeCurrent -name $cl_RenderTools_Create_Layer_Name`;
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	setAttr( "defaultRenderGlobals.currentRenderer" ) -typ "string" "mayaSoftware";
	setMayaSoftwareFrameExt(3, 0);
        setAttr  defaultRenderGlobals.extensionPadding 4;
	setAttr "defaultRenderQuality.pixelFilterType" 4;
	setAttr "defaultRenderQuality.pixelFilterWidthX" 3;
        setAttr "defaultRenderQuality.pixelFilterWidthY" 3;
	setAttr "defaultRenderGlobals.imageFormat" 32;
	string $objselect[] =`ls -sl`;
	if ($cl_RenderTools_Create_Layer_Name == "ExpLine")
	{
		select $objselect;
		source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_materialtra_Assign.mel";
		cl_material_mat;
		cl_RenderTools_HideToon($objselect);
		for ($obj in $objselect)
		{
			string $Iris = `match "MSH_iris_"$obj`;
			if (size($Iris)!=0 )
			    {
				select $obj;
				HideSelectedObjects;
			    }
		}
		
	}
	if ($cl_RenderTools_Create_Layer_Name == "OutLine")
	{
		select $objselect;
		source "//file-cluster/GDC/Resource/Support/Maya/projects/Calimero/render/cl_materialtra_Assign.mel";
		cl_material_mat;
		cl_RenderTools_HideStroke($objselect); 
		for ($obj in $objselect)
		{
			string $Iris = `match "MSH_iris_"$obj`;
			if (size($Iris)!=0 )
			    {
				select $obj;
				HideSelectedObjects;
			    }

		}
		 
	}
        	
}

global proc cl_RenderTools_HideStroke(string $obj[])
{
	
	string $hideGroups[]={};
	int $i =0;
	for ($p in $obj)
	{
		if (`gmatch  $p "*stroke*"`)		$hideGroups[$i++]=$p;
		

	}
	
	for ($hg in $hideGroups)
	{
		evalDeferred ("setAttr -lock 0  "+$hg + ".visibility");
		evalDeferred ("setAttr -k 1  "+$hg + ".visibility");
		CBdeleteConnection  ($hg +".v");	
		setAttr  ($hg +".v") 0;		
	}

	
}
global proc cl_RenderTools_HideToon(string $obj[])
{
	
	string $hideGroups[]={};
	int $i =0;
	for ($p in $obj)
	{
		if (`gmatch  $p "*pfxToon*"`)		$hideGroups[$i++]=$p;
		

	}
	
	for ($hg in $hideGroups)
	{
		evalDeferred ("setAttr -lock 0  "+$hg + ".visibility");
		evalDeferred ("setAttr -k 1  "+$hg + ".visibility");
		CBdeleteConnection  ($hg +".v");	
		setAttr  ($hg +".v") 0;		
	}

	
}



