
global proc cl_keylight()
{
	string $selectkeylight[]=`ls -sl`;
	for ($keylight in $selectkeylight)

	{
		string $keylightbuf[]=`listHistory $keylight`;
		string $keylightcolor = $keylightbuf[0] +".color";
		setAttr $keylightcolor -type double3 1 0 0;
	}

}
global proc cl_rimlight()
{
	string $selectrimlight[]=`ls -sl`;
	for ($rimlight in $selectrimlight)
	{
		string $rimlightbuf[]=`listHistory $rimlight`;
	        string $rimlightcolor = $rimlightbuf[0] +".color";
	        setAttr $rimlightcolor -type double3 0 0 1;
	}
}
global proc cl_fillight()
{
	string $selectfillight[]=`ls -sl`;
	for ($fillight in $selectfillight)

	{
		string $fillightbuf[]=`listHistory $fillight`;
		string $fillightcolor = $fillightbuf[0] +".color";
		setAttr $fillightcolor -type double3 0 1 0;
	}

}

