//proc pour la camera sur le rig facial
global proc string[] s100CFRFcreateCamera()
{
	//$prefix = "MA_C_WillyOriginal_01:" ;
	$cameraName = "cForRigFaciale";
	$cameraNameGrp = "cForRigFaciale_grp";
	if (`objExists "camForRigFaciale_grp"`)
	{
		delete "camForRigFaciale_grp" ;
    }

	if (`objExists $cameraNameGrp`)
	{
		delete $cameraNameGrp ;
    }

	if (`objExists $cameraName`)
	{
		delete $cameraName ;
    }

	if (`objExists $cameraNameGrp`)
	{
		delete $cameraNameGrp ;
    }
	if (`objExists "full_grp"`)
    {

    }else{
		group -em -n "full_grp" ;
    }

	string $cameraPanel[] = `camera -o 1`;
	string $cam = `rename $cameraPanel[0] $cameraName`;
	$list = `listRelatives -s -type "camera" $cam`;

	string $cameraShape = $list[0];

	setAttr -lock 1 ($cameraShape +".orthographicWidth") 4.6;


	string $grp = `group -em -n $cameraNameGrp` ;
	parent $cam $grp ;

	string $return[] = {$grp,$cam , $cameraShape};
	setAttr($grp +".v") 0 ;
		parent $cameraNameGrp "full_grp" ;

	return $return ;
 }


// Constrain camera group given object (nurbsCurve)
// 	s100CFRFconstraintCameraToFacialRig($returnCamera[0],$obj) ;
// 	string $grp = $returnCamera[0];
// 	string $object = $obj;
//
global proc s100CFRFconstraintCameraToFacialRig(string $grp ,string $object)
{
	if (`objExists ($object+".cp")`) // object has controlPoints = is deformable
	{
		string $sel[] = `ls -sl`;

		select -r $object;
		$clus = `cluster -envelope 1 `;

		$lien_cc = `pointConstraint -weight 1 $clus[1] $grp`;
		delete $clus ;
		//$lien_cc = `parentConstraint -mo  -weight 1 $object $grp`;

		// QA : new technic : positionning camera in the center of curve, oriented like it
		delete(`pointConstraint -mo -weight 1 $object $grp`);
		delete(`orientConstraint  -weight 1 $object $grp`);
		// then temporary parenting it to the curve to be able to translate it back 2 units in Z axis:
		string $oldParent = firstParentOf($grp);
		string $new[] = `parent $grp $object`;
		setAttr($new[0]+".tz") 2 ;
		// then back to former parent and final constraints
		$new = `parent $new[0] $oldParent`;
		$grp = $new[0];

		$lien_ppc = `parentConstraint -mo -weight 1 $object $grp`;
		$list = sort(`listRelatives -c -type "transform" $grp `);

		lockAndHiddeAll($grp) ;
		lockAndHiddeAll($list[0]) ;

		select -r $sel;
    }
	else
		print ("// '"+$object+"' is not a deformable object to constrain '"+$grp+"' to! - skipped\n");
}


global proc s100CFRFisolateSelect(string $toIso)
{
	string $var[] = `ls -sl` ;
	isolateSelect -state 0 s100CFRFModelPanel;

	select $toIso;
	isolateSelect -state 1 s100CFRFModelPanel;

	if(size($var) >0)
	{
 	   select $var;
    }else{
		select -cl ;
    }
}

global proc string s100CFRFCreateCamAndAttachIt()
{
	string $returnCamera[] = `s100CFRFcreateCamera`;

	if(`optionMenu  -ex asSelectorbipedOptionMenu`)
	{
		if(size(`optionMenu -q -itemListShort  asSelectorbipedOptionMenu `) > 0)
		{
			string $char = `optionMenu -q -v  asSelectorbipedOptionMenu`;
			$cam = "constru_02_curv" ;
			string $cameraTmp[] = `ls ($char + $cam ) ( $char +"*:*:*" + $cam )  ( $char +"*:*" + $cam ) ("*:*:"+ $char + $cam ) ("*:"+ $char + $cam ) ("*:*:"+ $char + $cam ) ` ;
			$cameraTmp = stringArrayRemoveDuplicates($cameraTmp);

			if(size($cameraTmp) == 0 )
			{
				$cam = "constru_Facial" ;
				$cameraTmp = `ls ($char + $cam ) ( $char +"*:*:*" + $cam )  ( $char +"*:*" + $cam ) ("*:*:"+ $char + $cam ) ("*:"+ $char + $cam ) ("*:*:"+ $char + $cam ) ` ;
			}
			$cameraTmp = stringArrayRemoveDuplicates($cameraTmp);

			$obj = $cameraTmp[0];
			//$cam = "facial_oGrp" ;
			//string $cameraTmp[] = `ls ($char + $cam ) ( $char +"*:*:*" + $cam )  ( $char +"*:*" + $cam ) ("*:*:"+ $char + $cam ) ("*:"+ $char + $cam ) ("*:*:"+ $char + $cam ) ` ;
			//$objToIso = $cameraTmp[0];
			string $objToIso = firstParentOf(firstParentOf($obj));

			$ch = 0 ;
			string $toModif ;
			if(`objExists $obj`)
			{
				if(` objExists ($char +"facial_oGrp" ) `)
				{
					$list = `listConnections -type "parentConstraint" ($char +"facial_oGrp" ) `	;
					$list = stringArrayRemoveDuplicates($list);
					if(size($list) > 0 )
					{
						$listAttr = `listAttr -ud   $list[0] `;
						if(size($listAttr) > 0 )
						{
							$toModif = ($list[0] +"."+ $listAttr[0] )  ;
							setAttr $toModif 0 ;
							$ch = 1 ;
						}
					}
				}

				s100CFRFconstraintCameraToFacialRig($returnCamera[0],$obj) ;
				s100CFRFAdustOrthographicSetup($returnCamera[2], $obj) ;
				if(`objExists $objToIso`)
					s100CFRFisolateSelect( $objToIso);

				if($ch )
				{
					setAttr $toModif 1 ;
				}
			}
			else
				print ("// No object ("+$cam+") found to constrain facial UI camera to.. \n");
        }
    }
	return $returnCamera[1];
}


global proc s100CFRFAdustOrthographicSetup(string $cam, string $curv)
{
	select ($curv +".cv[0]") ;
	$cls1 = `newCluster " -envelope 1" `;
	select ($curv +".cv[2]") ;
	$cls2 = `newCluster " -envelope 1" `;
	$dist = ((getDistance($cls1[1], $cls2[1])) / 9.2 ) * 4.500;
	setAttr -l 0 ($cam + ".orthographicWidth")  ;
	setAttr -l 0 ($cam + ".orthographicWidth")  $dist;
	setAttr -l 1($cam + ".orthographicWidth")  ;
	delete $cls1 $cls2 ;
}



global proc s100CFRFCreateCamAndAttachItAcutalize()
{
	string $rCamera = `s100CFRFCreateCamAndAttachIt`;
	modelPanel -e -camera $rCamera s100CFRFModelPanel;
}



global proc s100CFRFRefreshTabLayout()
{
	$tab = `tabLayout -q -selectTab asSelectorbipedTabLayout`;
	int $height = 344 ;
	int $w = 334 ;
	if($tab == "s100CFRFLayout")
	{
		$hT = `	frameLayout -q -h  s100CFRFLayout`;

		$height = $hT + 105;
		$w = 450;
		s100CFRFCreateCamAndAttachIt ;
		modelPanel -e -camera "cForRigFaciale" s100CFRFModelPanel;
	}
	if($tab == "asSelectorbipedFormLayout")
	{
		$height = 344 ;
		$w = 334 ;
	}
	window -e -sizeable false -h $height -w $w  asSelectorbiped;
}


global proc s100CFRFcreateLayout()
{
	if(`objExists "camForRigFaciale"`)
		delete   "camForRigFaciale" ;

	string $rCamera = `s100CFRFCreateCamAndAttachIt`;

	if(`frameLayout -ex s100CFRFLayout`)
		deleteUI s100CFRFLayout ;
	frameLayout -height 800  -p asSelectorbipedTabLayout -lv 0 s100CFRFLayout;


	if(`modelPanel -ex s100CFRFModelPanel`)
		deleteUI -panel  s100CFRFModelPanel;
	modelPanel -menuBarVisible 0  -p s100CFRFLayout -camera $rCamera s100CFRFModelPanel;

	modelEditor -e -pm 0 -m 1 -hud 0 -grid 0 s100CFRFModelPanel ;
	modelEditor -e  -viewSelected 0 s100CFRFModelPanel ;
	tabLayout -e -tabLabel s100CFRFLayout "facial" asSelectorbipedTabLayout ;
}

	/*
	modelPanel -e -p s100CFRFLayout s100CFRFModelPanel
	deleteUI window1
	*/


global proc s100CFRFdeleteCam()
{
	if(`objExists "camForRigFaciale_grp"`)
		delete "camForRigFaciale_grp";
}


	//end add proc for rig camera



	//modif proc AS pour UI
	global proc s100asSelectorbiped ()
	{
		if (`window -q -ex asSelectorbiped`)
			deleteUI asSelectorbiped;

		if (`waitCursor -q -state`==0)
			waitCursor -st 1;

		string $asSelectorScriptLocation=`asSelectorScriptLocation`;
		string $asIconLocation=$asSelectorScriptLocation+"biped/";
		string $ext=".xpm";
		if (`asMayaVersionAsFloat`>=2011)
			$ext=".png";
		if (`about -mac`)
			$ext=".iff";
		window -mb 1 -t biped asSelectorbiped;
		menu -l Edit;
			menuItem -l "Refresh All UI (long)" -c "s100asSelectorbiped";
			menuItem -l "Refresh only character list" -c "s100asPopulateNameSpaceMenu asSelectorbiped;";
			menuItem -l Filter -c "asFilterNameSpaceMenuUI asSelectorbiped";
			setParent..;
		menu -l Display;
			menuItem -l "Controls" -c "asControlsVisibilityToggle";
			menuItem -l "Set HotKey" -c "asSetupControlVisibilityHotKeyDialog";
			menuItem -d 1;
			menuItem -l "Joints" -c "asJointsVisibilityToggle";
			setParent..;
		menu -l Pose -aob 1;
			menuItem -l Copy -c "asCopyToClipBloard asSelectorbiped 0";
			menuItem -l Paste -en 0 asSelectorbipedPosePaste;
			menuItem -d 1;
			menuItem -l Reset -c "asGoToBuildPose asSelectorbiped";
			menuItem -l Mirror -c "asMirror asSelectorbiped";
			menuItem -optionBox 1 -c "asMirrorOptions asSelectorbiped";
			setParent..;
		menu -l Anim;
			menuItem -l Copy -c "asCopyToClipBloard asSelectorbiped 1";
			menuItem -l Paste -en 0 asSelectorbipedAnimPaste;
		menu -l Dynamics;
			menuItem -l Add -c "asDynAdd asSelectorbiped";
			menuItem -l Bake -c "asDynBake asSelectorbiped";
		menu -l Facial;
			menuItem -l "tear off camera on head" -c "s100asAddHeadCamForSelectedCharacter"; // -c "s100asAddHeadCam";


		columnLayout -adj 1;
		rowLayout -nc 4 -adj 1 -cat 1 right 0 -cw 2 30 -cw 3 80 -cw 4 60;
		optionMenu -cc ("asSelChange;s100CFRFCreateCamAndAttachItAcutalize") asSelectorbipedOptionMenu;
		button -l set -c "asSetNameSpaceFromSelection asSelectorbiped";
		checkBox -v `optionVar -q asShowSelection` -onc "asSelChangeToggle;optionVar -iv asShowSelection 1" -ofc "asSelChangeToggle;optionVar -iv asShowSelection 0" -l Selection asSelectorbipedSelectionCheckBox;
		checkBox -v `optionVar -q asShowKeyed` -onc "asSelChangeToggle;optionVar -iv asShowKeyed 1" -ofc "asSelChangeToggle;optionVar -iv asShowKeyed 0" -l Keyed asSelectorbipedKeyedCheckBox;
		setParent..;
		tabLayout -cc s100CFRFRefreshTabLayout asSelectorbipedTabLayout;
		formLayout asSelectorbipedFormLayout;
		tabLayout -e -tabLabel asSelectorbipedFormLayout "body" asSelectorbipedTabLayout;

		//Controls Begin//
		if (`asMayaVersionAsFloat`>=2011)
			image -en 0 -w 320 -h 240 -i ($asIconLocation+"biped_background"+$ext) "asSelectorbipedBGPicture";
		else
			if (!`about -linux`)
				iconTextButton -en 0 -w 320 -h 240 -i ($asIconLocation+"biped_background.xpm") -di ($asIconLocation+"biped_background.xpm") "asSelectorbipedBGPicture";
		iconTextButton -w 21 -h 21 -i ($asIconLocation+"biped_49_43_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKWrist_R\"};" -ann "FKWrist_R;" "asSelectorbiped:49:43";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKWrist_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKWrist_R\"};";
		iconTextButton -w 21 -h 21 -i ($asIconLocation+"biped_250_43_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKWrist_L\"};" -ann "FKWrist_L;" "asSelectorbiped:250:43";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKWrist_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKWrist_L\"};";
		iconTextButton -w 8 -h 17 -i ($asIconLocation+"biped_156_38_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKNeck_M\"};" -ann "FKNeck_M;" "asSelectorbiped:156:38";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKNeck_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKNeck_M\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_73_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegBall_R\"};" -ann "IKLegBall_R;" "asSelectorbiped:73:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegBall_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegBall_R\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_234_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegBall_L\"};" -ann "IKLegBall_L;" "asSelectorbiped:234:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegBall_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegBall_L\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_55_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegToe_R\"};" -ann "IKLegToe_R;" "asSelectorbiped:55:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegToe_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegToe_R\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_252_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegToe_L\"};" -ann "IKLegToe_L;" "asSelectorbiped:252:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegToe_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegToe_L\"};";
		iconTextButton -w 24 -h 18 -i ($asIconLocation+"biped_288_10_OffK0"+$ext) -iol "ALL"
			-c "asSelect \"biped\" {\"ControlSet\"};" -ann "ControlSet elements (phonems and dyn joints among them)" "asSelectorbiped:288:10";
		popupMenu;
			// QA addendum:
			menuItem -l "Smart Select ALL"  -c "asSelect \"biped\" {\"ControlSet\"}; select -d (s100DMlistDynJointsByNameSpace(asGetNameSpace(\"biped\"))); select -d (s100_getLipSyncCtrls(asGetNameSpace(\"biped\")));"
			-ann "selects all related 'ControlSet' elements BUT phonems AND dyn joints !" "asSelectorbiped:288:10";
			menuItem -d 1;
			menuItem -to 1 -l Key -c "asKey \"biped\" {\"ControlSet\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"ControlSet\"};";




		/*
		iconTextButton -w 24 -h 18 -i ($asIconLocation+"biped_288_10_OffK0"+$ext) -iol "smart\nALL"
			-c "asSelect \"biped\" {\"ControlSet\"}; select -d s100DMlistDynJointsByNameSpace(asGetNameSpace(\"biped\")); select -d s100_getLipSyncCtrls(asGetNameSpace(\"biped\"));"
			-ann "ControlSet elements BUT phonems AND dyn joints !" "asSelectorbiped:288:10";
		*/


		// QA addendum:
		iconTextButton -w 24 -h 18 -i ($asIconLocation+"biped_288_30_OffK0"+$ext) -iol "traj" -c "asSelect \"biped\" {\"traj\"};" -ann "ControlSet" "asSelectorbiped:288:30";
		popupMenu; //
			menuItem -l Key -c "asKey \"biped\" {\"traj\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"traj\"};";
		iconTextButton -w 24 -h 18 -i ($asIconLocation+"biped_288_50_OffK0"+$ext) -iol "fly"
			-c "asSelect \"biped\" {\"fly\"};" -ann "ControlSet" "asSelectorbiped:288:50";
		popupMenu; //
			menuItem -l Key -c "asKey \"biped\" {\"fly\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"fly\"};";

		iconTextButton -w 50 -h 16 -i ($asIconLocation+"biped_26_180_OffK0"+$ext) -iol "fingers" -c "asSelect \"biped\" {\"Fingers_R\"};" -ann "fingers" "asSelectorbiped:26:180";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"fingers\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"fingers\"};";
		iconTextButton -w 50 -h 16 -i ($asIconLocation+"biped_244_180_OffK0"+$ext) -iol "fingers" -c "asSelect \"biped\" {\"Fingers_L\"};" -ann "fingers" "asSelectorbiped:244:180";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"fingers\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"fingers\"};";
		iconTextButton -w 15 -h 15 -i ($asIconLocation+"biped_209_92_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIKSpine_M\"};" -ann "FKIKSpine_M;" "asSelectorbiped:209:92";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIKSpine_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIKSpine_M\"};";
		iconTextButton -w 30 -h 30 -i ($asIconLocation+"biped_104_96_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"HipSwingerRoot_M\"};" -ann "HipSwingerRoot_M;" "asSelectorbiped:104:96";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"HipSwingerRoot_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"HipSwingerRoot_M\"};";
		iconTextButton -w 34 -h 18 -i ($asIconLocation+"biped_103_73_OffK0"+$ext) -iol "spine" -c "asSelect \"biped\" {\"FKChest_M\",\"FKBackB_M\",\"FKBackA_M\"};" -ann "spine" "asSelectorbiped:103:73";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"spine\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"spine\"};";
		iconTextButton -w 23 -h 23 -i ($asIconLocation+"biped_47_8_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKArm_R\"};" -ann "IKArm_R;" "asSelectorbiped:47:8";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKArm_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKArm_R\"};";
		iconTextButton -w 23 -h 23 -i ($asIconLocation+"biped_250_8_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKArm_L\"};" -ann "IKArm_L;" "asSelectorbiped:250:8";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKArm_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKArm_L\"};";
		iconTextButton -w 38 -h 46 -i ($asIconLocation+"biped_30_131_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKWrist_R\"};" -ann "FKWrist_R;" "asSelectorbiped:30:131";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKWrist_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKWrist_R\"};";
		iconTextButton -w 38 -h 46 -i ($asIconLocation+"biped_252_131_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKWrist_L\"};" -ann "FKWrist_L;" "asSelectorbiped:252:131";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKWrist_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKWrist_L\"};";
		iconTextButton -w 11 -h 20 -i ($asIconLocation+"biped_69_146_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger1_R\"};" -ann "FKThumbFinger1_R;" "asSelectorbiped:69:146";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger1_R\"};";
		iconTextButton -w 11 -h 20 -i ($asIconLocation+"biped_240_146_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger1_L\"};" -ann "FKThumbFinger1_L;" "asSelectorbiped:240:146";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger1_L\"};";
		iconTextButton -w 13 -h 8 -i ($asIconLocation+"biped_70_137_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger2_R\"};" -ann "FKThumbFinger2_R;" "asSelectorbiped:70:137";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger2_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger2_R\"};";
		iconTextButton -w 13 -h 8 -i ($asIconLocation+"biped_237_137_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger2_L\"};" -ann "FKThumbFinger2_L;" "asSelectorbiped:237:137";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger2_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger2_L\"};";
		iconTextButton -w 17 -h 12 -i ($asIconLocation+"biped_73_124_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger3_R\"};" -ann "FKThumbFinger3_R;" "asSelectorbiped:73:124";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger3_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger3_R\"};";
		iconTextButton -w 17 -h 12 -i ($asIconLocation+"biped_230_124_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKThumbFinger3_L\"};" -ann "FKThumbFinger3_L;" "asSelectorbiped:230:124";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKThumbFinger3_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKThumbFinger3_L\"};";
		iconTextButton -w 10 -h 15 -i ($asIconLocation+"biped_60_115_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger1_R\"};" -ann "FKIndexFinger1_R;" "asSelectorbiped:60:115";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger1_R\"};";
		iconTextButton -w 10 -h 15 -i ($asIconLocation+"biped_250_115_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger1_L\"};" -ann "FKIndexFinger1_L;" "asSelectorbiped:250:115";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger1_L\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_64_99_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger2_R\"};" -ann "FKIndexFinger2_R;" "asSelectorbiped:64:99";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger2_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger2_R\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_246_99_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger2_L\"};" -ann "FKIndexFinger2_L;" "asSelectorbiped:246:99";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger2_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger2_L\"};";
		iconTextButton -w 10 -h 16 -i ($asIconLocation+"biped_49_114_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger1_R\"};" -ann "FKMiddleFinger1_R;" "asSelectorbiped:49:114";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger1_R\"};";
		iconTextButton -w 10 -h 16 -i ($asIconLocation+"biped_261_114_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger1_L\"};" -ann "FKMiddleFinger1_L;" "asSelectorbiped:261:114";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger1_L\"};";
		iconTextButton -w 11 -h 13 -i ($asIconLocation+"biped_48_98_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger2_R\"};" -ann "FKMiddleFinger2_R;" "asSelectorbiped:48:98";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger2_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger2_R\"};";
		iconTextButton -w 11 -h 13 -i ($asIconLocation+"biped_261_98_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger2_L\"};" -ann "FKMiddleFinger2_L;" "asSelectorbiped:261:98";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger2_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger2_L\"};";
		iconTextButton -w 11 -h 15 -i ($asIconLocation+"biped_48_80_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger3_R\"};" -ann "FKMiddleFinger3_R;" "asSelectorbiped:48:80";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger3_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger3_R\"};";
		iconTextButton -w 11 -h 15 -i ($asIconLocation+"biped_261_80_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleFinger3_L\"};" -ann "FKMiddleFinger3_L;" "asSelectorbiped:261:80";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleFinger3_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleFinger3_L\"};";
		iconTextButton -w 10 -h 15 -i ($asIconLocation+"biped_37_115_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger1_R\"};" -ann "FKRingFinger1_R;" "asSelectorbiped:37:115";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger1_R\"};";
		iconTextButton -w 10 -h 15 -i ($asIconLocation+"biped_273_115_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger1_L\"};" -ann "FKRingFinger1_L;" "asSelectorbiped:273:115";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger1_L\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_34_99_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger2_R\"};" -ann "FKRingFinger2_R;" "asSelectorbiped:34:99";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger2_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger2_R\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_276_99_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger2_L\"};" -ann "FKRingFinger2_L;" "asSelectorbiped:276:99";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger2_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger2_L\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_32_84_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger3_R\"};" -ann "FKRingFinger3_R;" "asSelectorbiped:32:84";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger3_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger3_R\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_278_84_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKRingFinger3_L\"};" -ann "FKRingFinger3_L;" "asSelectorbiped:278:84";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKRingFinger3_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKRingFinger3_L\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_26_120_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger1_R\"};" -ann "FKPinkyFinger1_R;" "asSelectorbiped:26:120";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger1_R\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_284_120_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger1_L\"};" -ann "FKPinkyFinger1_L;" "asSelectorbiped:284:120";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger1_L\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_22_109_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger2_R\"};" -ann "FKPinkyFinger2_R;" "asSelectorbiped:22:109";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger2_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger2_R\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_288_109_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger2_L\"};" -ann "FKPinkyFinger2_L;" "asSelectorbiped:288:109";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger2_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger2_L\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_18_98_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger3_R\"};" -ann "FKPinkyFinger3_R;" "asSelectorbiped:18:98";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger3_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger3_R\"};";
		iconTextButton -w 10 -h 10 -i ($asIconLocation+"biped_292_98_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKPinkyFinger3_L\"};" -ann "FKPinkyFinger3_L;" "asSelectorbiped:292:98";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKPinkyFinger3_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKPinkyFinger3_L\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_67_85_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger3_R\"};" -ann "FKIndexFinger3_R;" "asSelectorbiped:67:85";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger3_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger3_R\"};";
		iconTextButton -w 10 -h 13 -i ($asIconLocation+"biped_243_85_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIndexFinger3_L\"};" -ann "FKIndexFinger3_L;" "asSelectorbiped:243:85";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIndexFinger3_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIndexFinger3_L\"};";
		iconTextButton -w 14 -h 13 -i ($asIconLocation+"biped_141_42_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKScapula_R\"};" -ann "FKScapula_R;" "asSelectorbiped:141:42";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKScapula_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKScapula_R\"};";
		iconTextButton -w 14 -h 13 -i ($asIconLocation+"biped_165_42_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKScapula_L\"};" -ann "FKScapula_L;" "asSelectorbiped:165:42";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKScapula_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKScapula_L\"};";
		iconTextButton -w 34 -h 20 -i ($asIconLocation+"biped_105_46_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKShoulder_R\"};" -ann "FKShoulder_R;" "asSelectorbiped:105:46";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKShoulder_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKShoulder_R\"};";
		iconTextButton -w 34 -h 20 -i ($asIconLocation+"biped_181_46_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKShoulder_L\"};" -ann "FKShoulder_L;" "asSelectorbiped:181:46";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKShoulder_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKShoulder_L\"};";
		iconTextButton -w 32 -h 15 -i ($asIconLocation+"biped_71_47_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKElbow_R\"};" -ann "FKElbow_R;" "asSelectorbiped:71:47";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKElbow_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKElbow_R\"};";
		iconTextButton -w 32 -h 15 -i ($asIconLocation+"biped_217_47_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKElbow_L\"};" -ann "FKElbow_L;" "asSelectorbiped:217:47";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKElbow_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKElbow_L\"};";
		iconTextButton -w 42 -h 32 -i ($asIconLocation+"biped_139_3_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKHead_M\",\"FKHead1_M\"};" -ann "FKHead_M;" "asSelectorbiped:139:3";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKHead_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKHead_M\"};";
		iconTextButton -w 15 -h 15 -i ($asIconLocation+"biped_117_13_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIKArm_R\"};" -ann "FKIKArm_R;" "asSelectorbiped:117:13";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIKArm_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIKArm_R\"};";
			menuItem -d 1;
			menuItem -l Align -sm 1;
				menuItem -l FK2IK -c "asAlignFK2IK \"biped\" {\"FKIKArm_R\"}";
				menuItem -l IK2FK -c "asAlignIK2FK \"biped\" {\"FKIKArm_R\"}";
				setParent -menu ..;
			menuItem -l Switch -sm 1;
				menuItem -l FK2IK -c "asSwitchFK2IK \"biped\" {\"FKIKArm_R\"}";
				menuItem -l IK2FK -c "asSwitchIK2FK \"biped\" {\"FKIKArm_R\"}";
		iconTextButton -w 15 -h 15 -i ($asIconLocation+"biped_188_13_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIKArm_L\"};" -ann "FKIKArm_L;" "asSelectorbiped:188:13";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIKArm_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIKArm_L\"};";
			menuItem -d 1;
			menuItem -l Align -sm 1;
				menuItem -l FK2IK -c "asAlignFK2IK \"biped\" {\"FKIKArm_L\"}";
				menuItem -l IK2FK -c "asAlignIK2FK \"biped\" {\"FKIKArm_L\"}";
				setParent -menu ..;
			menuItem -l Switch -sm 1;
				menuItem -l FK2IK -c "asSwitchFK2IK \"biped\" {\"FKIKArm_L\"}";
				menuItem -l IK2FK -c "asSwitchIK2FK \"biped\" {\"FKIKArm_L\"}";
		iconTextButton -w 21 -h 22 -i ($asIconLocation+"biped_85_9_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"PoleArm_R\"};" -ann "PoleArm_R;" "asSelectorbiped:85:9";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"PoleArm_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"PoleArm_R\"};";
		iconTextButton -w 21 -h 22 -i ($asIconLocation+"biped_214_9_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"PoleArm_L\"};" -ann "PoleArm_L;" "asSelectorbiped:214:9";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"PoleArm_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"PoleArm_L\"};";
		iconTextButton -w 20 -h 41 -i ($asIconLocation+"biped_138_141_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKHip_R\"};" -ann "FKHip_R;" "asSelectorbiped:138:141";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKHip_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKHip_R\"};";
		iconTextButton -w 20 -h 41 -i ($asIconLocation+"biped_162_141_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKHip_L\"};" -ann "FKHip_L;" "asSelectorbiped:162:141";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKHip_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKHip_L\"};";
		iconTextButton -w 18 -h 31 -i ($asIconLocation+"biped_140_184_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKKnee_R\"};" -ann "FKKnee_R;" "asSelectorbiped:140:184";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKKnee_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKKnee_R\"};";
		iconTextButton -w 18 -h 31 -i ($asIconLocation+"biped_162_184_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKKnee_L\"};" -ann "FKKnee_L;" "asSelectorbiped:162:184";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKKnee_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKKnee_L\"};";
		iconTextButton -w 19 -h 19 -i ($asIconLocation+"biped_139_219_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKAnkle_R\"};" -ann "FKAnkle_R;" "asSelectorbiped:139:219";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKAnkle_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKAnkle_R\"};";
		iconTextButton -w 19 -h 19 -i ($asIconLocation+"biped_162_219_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKAnkle_L\"};" -ann "FKAnkle_L;" "asSelectorbiped:162:219";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKAnkle_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKAnkle_L\"};";
		iconTextButton -w 15 -h 13 -i ($asIconLocation+"biped_123_225_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleToe1_R\"};" -ann "FKMiddleToe1_R;" "asSelectorbiped:123:225";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleToe1_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleToe1_R\"};";
		iconTextButton -w 15 -h 13 -i ($asIconLocation+"biped_182_225_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKMiddleToe1_L\"};" -ann "FKMiddleToe1_L;" "asSelectorbiped:182:225";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKMiddleToe1_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKMiddleToe1_L\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_89_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegHeel_R\"};" -ann "IKLegHeel_R;" "asSelectorbiped:89:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegHeel_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegHeel_R\"};";
		iconTextButton -w 13 -h 13 -i ($asIconLocation+"biped_218_221_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLegHeel_L\"};" -ann "IKLegHeel_L;" "asSelectorbiped:218:221";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLegHeel_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLegHeel_L\"};";
		iconTextButton -w 23 -h 23 -i ($asIconLocation+"biped_103_195_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLeg_R\"};" -ann "IKLeg_R;" "asSelectorbiped:103:195";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLeg_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLeg_R\"};";
		iconTextButton -w 23 -h 23 -i ($asIconLocation+"biped_194_195_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKLeg_L\"};" -ann "IKLeg_L;" "asSelectorbiped:194:195";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKLeg_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKLeg_L\"};";
		iconTextButton -w 21 -h 22 -i ($asIconLocation+"biped_104_168_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"PoleLeg_R\"};" -ann "PoleLeg_R;" "asSelectorbiped:104:168";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"PoleLeg_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"PoleLeg_R\"};";
		iconTextButton -w 21 -h 22 -i ($asIconLocation+"biped_195_168_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"PoleLeg_L\"};" -ann "PoleLeg_L;" "asSelectorbiped:195:168";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"PoleLeg_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"PoleLeg_L\"};";
		iconTextButton -w 15 -h 15 -i ($asIconLocation+"biped_107_146_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIKLeg_R\"};" -ann "FKIKLeg_R;" "asSelectorbiped:107:146";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIKLeg_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIKLeg_R\"};";
			menuItem -d 1;
			menuItem -l Align -sm 1;
				menuItem -l FK2IK -c "asAlignFK2IK \"biped\" {\"FKIKLeg_R\"}";
				menuItem -l IK2FK -c "asAlignIK2FK \"biped\" {\"FKIKLeg_R\"}";
				setParent -menu ..;
			menuItem -l Switch -sm 1;
				menuItem -l FK2IK -c "asSwitchFK2IK \"biped\" {\"FKIKLeg_R\"}";
				menuItem -l IK2FK -c "asSwitchIK2FK \"biped\" {\"FKIKLeg_R\"}";
		iconTextButton -w 15 -h 15 -i ($asIconLocation+"biped_198_146_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKIKLeg_L\"};" -ann "FKIKLeg_L;" "asSelectorbiped:198:146";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKIKLeg_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKIKLeg_L\"};";
			menuItem -d 1;
			menuItem -l Align -sm 1;
				menuItem -l FK2IK -c "asAlignFK2IK \"biped\" {\"FKIKLeg_L\"}";
				menuItem -l IK2FK -c "asAlignIK2FK \"biped\" {\"FKIKLeg_L\"}";
				setParent -menu ..;
			menuItem -l Switch -sm 1;
				menuItem -l FK2IK -c "asSwitchFK2IK \"biped\" {\"FKIKLeg_L\"}";
				menuItem -l IK2FK -c "asSwitchIK2FK \"biped\" {\"FKIKLeg_L\"}";
		iconTextButton -w 38 -h 18 -i ($asIconLocation+"biped_141_102_OnK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKBackA_M\"};" -ann "FKBackA_M;" "asSelectorbiped:141:102";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKBackA_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKBackA_M\"};";
		iconTextButton -w 38 -h 18 -i ($asIconLocation+"biped_141_80_OnK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKBackB_M\"};" -ann "FKBackB_M;" "asSelectorbiped:141:80";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKBackB_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKBackB_M\"};";
		iconTextButton -w 38 -h 18 -i ($asIconLocation+"biped_141_58_OnK0"+$ext) -iol "" -c "asSelect \"biped\" {\"FKChest_M\"};" -ann "FKChest_M;" "asSelectorbiped:141:58";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKChest_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKChest_M\"};";
		iconTextButton -w 17 -h 17 -i ($asIconLocation+"biped_189_111_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKSpine0_M\"};" -ann "IKSpine0_M;" "asSelectorbiped:189:111";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKSpine0_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKSpine0_M\"};";
		iconTextButton -w 17 -h 17 -i ($asIconLocation+"biped_189_91_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKSpine2_M\"};" -ann "IKSpine2_M;" "asSelectorbiped:189:91";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKSpine2_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKSpine2_M\"};";
		iconTextButton -w 17 -h 17 -i ($asIconLocation+"biped_189_70_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"IKSpine4_M\"};" -ann "IKSpine4_M;" "asSelectorbiped:189:70";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"IKSpine4_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"IKSpine4_M\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_126_159_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendHip_R\"};" -ann "BendHip_R;" "asSelectorbiped:126:159";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendHip_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendHip_R\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_183_159_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendHip_L\"};" -ann "BendHip_L;" "asSelectorbiped:183:159";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendHip_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendHip_L\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_83_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendElbow_R\"};" -ann "BendElbow_R;" "asSelectorbiped:83:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendElbow_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendElbow_R\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_226_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendElbow_L\"};" -ann "BendElbow_L;" "asSelectorbiped:226:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendElbow_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendElbow_L\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_98_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"Bend0Elbow_R\"};" -ann "Bend0Elbow_R;" "asSelectorbiped:98:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"Bend0Elbow_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"Bend0Elbow_R\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_211_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"Bend0Elbow_L\"};" -ann "Bend0Elbow_L;" "asSelectorbiped:211:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"Bend0Elbow_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"Bend0Elbow_L\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_113_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendShoulder_R\"};" -ann "BendShoulder_R;" "asSelectorbiped:113:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendShoulder_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendShoulder_R\"};";
		iconTextButton -w 11 -h 11 -i ($asIconLocation+"biped_196_35_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"BendShoulder_L\"};" -ann "BendShoulder_L;" "asSelectorbiped:196:35";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"BendShoulder_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"BendShoulder_L\"};";
		iconTextButton -w 33 -h 18 -i ($asIconLocation+"biped_7_10_OffK0"+$ext) -iol "Main" -c "asSelect \"biped\" {\"Main\"};" -ann "Main;" "asSelectorbiped:7:10";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"Main\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"Main\"};";
		iconTextButton -w 48 -h 18 -i ($asIconLocation+"biped_136_122_OffK0"+$ext) -iol "" -c "asSelect \"biped\" {\"Center_M\"};" -ann "Center_M;" "asSelectorbiped:136:122";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"Center_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"Center_M\"};";
		iconTextButton -w 22 -h 18 -i ($asIconLocation+"biped_18_29_OffK0"+$ext) -iol "Aim" -c "asSelect \"biped\" {\"AimEye_M\"};" -ann "AimEye_M;" "asSelectorbiped:18:29";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"AimEye_M\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"AimEye_M\"};";
		iconTextButton -w 11 -h 16 -i ($asIconLocation+"biped_18_46_OffK0"+$ext) -iol "R" -c "asSelect \"biped\" {\"FKEye_R\"};" -ann "FKEye_R;" "asSelectorbiped:18:46";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKEye_R\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKEye_R\"};";
		iconTextButton -w 11 -h 16 -i ($asIconLocation+"biped_29_46_OffK0"+$ext) -iol "L" -c "asSelect \"biped\" {\"FKEye_L\"};" -ann "FKEye_L;" "asSelectorbiped:29:46";
		popupMenu;
			menuItem -l Key -c "asKey \"biped\" {\"FKEye_L\"};";
			menuItem -l LinearKey -c "asLinearKey \"biped\" {\"FKEye_L\"};";

		setParent..;
		if (`about -linux`)
				iconTextButton -en 1 -w 320 -h 240 -i ($asIconLocation+"biped_background.xpm") -di ($asIconLocation+"biped_background.xpm") "asSelectorbipedBGPicture";
		//Controls End//

		formLayout -e
			-af "asSelectorbiped:49:43" left 49
			-af "asSelectorbiped:49:43" top 43
			-af "asSelectorbiped:250:43" left 250
			-af "asSelectorbiped:250:43" top 43
			-af "asSelectorbiped:156:38" left 156
			-af "asSelectorbiped:156:38" top 38
			-af "asSelectorbiped:73:221" left 73
			-af "asSelectorbiped:73:221" top 221
			-af "asSelectorbiped:234:221" left 234
			-af "asSelectorbiped:234:221" top 221
			-af "asSelectorbiped:55:221" left 55
			-af "asSelectorbiped:55:221" top 221
			-af "asSelectorbiped:252:221" left 252
			-af "asSelectorbiped:252:221" top 221
			-af "asSelectorbiped:288:10" left 288
			-af "asSelectorbiped:288:10" top 10

			// QA :
			-af "asSelectorbiped:288:30" left 288
			-af "asSelectorbiped:288:30" top 30
			-af "asSelectorbiped:288:50" left 288
			-af "asSelectorbiped:288:50" top 50


			-af "asSelectorbiped:26:180" left 26
			-af "asSelectorbiped:26:180" top 180
			-af "asSelectorbiped:244:180" left 244
			-af "asSelectorbiped:244:180" top 180
			-af "asSelectorbiped:209:92" left 209
			-af "asSelectorbiped:209:92" top 92
			-af "asSelectorbiped:104:96" left 104
			-af "asSelectorbiped:104:96" top 96
			-af "asSelectorbiped:103:73" left 103
			-af "asSelectorbiped:103:73" top 73
			-af "asSelectorbiped:47:8" left 47
			-af "asSelectorbiped:47:8" top 8
			-af "asSelectorbiped:250:8" left 250
			-af "asSelectorbiped:250:8" top 8
			-af "asSelectorbiped:30:131" left 30
			-af "asSelectorbiped:30:131" top 131
			-af "asSelectorbiped:252:131" left 252
			-af "asSelectorbiped:252:131" top 131
			-af "asSelectorbiped:69:146" left 69
			-af "asSelectorbiped:69:146" top 146
			-af "asSelectorbiped:240:146" left 240
			-af "asSelectorbiped:240:146" top 146
			-af "asSelectorbiped:70:137" left 70
			-af "asSelectorbiped:70:137" top 137
			-af "asSelectorbiped:237:137" left 237
			-af "asSelectorbiped:237:137" top 137
			-af "asSelectorbiped:73:124" left 73
			-af "asSelectorbiped:73:124" top 124
			-af "asSelectorbiped:230:124" left 230
			-af "asSelectorbiped:230:124" top 124
			-af "asSelectorbiped:60:115" left 60
			-af "asSelectorbiped:60:115" top 115
			-af "asSelectorbiped:250:115" left 250
			-af "asSelectorbiped:250:115" top 115
			-af "asSelectorbiped:64:99" left 64
			-af "asSelectorbiped:64:99" top 99
			-af "asSelectorbiped:246:99" left 246
			-af "asSelectorbiped:246:99" top 99
			-af "asSelectorbiped:49:114" left 49
			-af "asSelectorbiped:49:114" top 114
			-af "asSelectorbiped:261:114" left 261
			-af "asSelectorbiped:261:114" top 114
			-af "asSelectorbiped:48:98" left 48
			-af "asSelectorbiped:48:98" top 98
			-af "asSelectorbiped:261:98" left 261
			-af "asSelectorbiped:261:98" top 98
			-af "asSelectorbiped:48:80" left 48
			-af "asSelectorbiped:48:80" top 80
			-af "asSelectorbiped:261:80" left 261
			-af "asSelectorbiped:261:80" top 80
			-af "asSelectorbiped:37:115" left 37
			-af "asSelectorbiped:37:115" top 115
			-af "asSelectorbiped:273:115" left 273
			-af "asSelectorbiped:273:115" top 115
			-af "asSelectorbiped:34:99" left 34
			-af "asSelectorbiped:34:99" top 99
			-af "asSelectorbiped:276:99" left 276
			-af "asSelectorbiped:276:99" top 99
			-af "asSelectorbiped:32:84" left 32
			-af "asSelectorbiped:32:84" top 84
			-af "asSelectorbiped:278:84" left 278
			-af "asSelectorbiped:278:84" top 84
			-af "asSelectorbiped:26:120" left 26
			-af "asSelectorbiped:26:120" top 120
			-af "asSelectorbiped:284:120" left 284
			-af "asSelectorbiped:284:120" top 120
			-af "asSelectorbiped:22:109" left 22
			-af "asSelectorbiped:22:109" top 109
			-af "asSelectorbiped:288:109" left 288
			-af "asSelectorbiped:288:109" top 109
			-af "asSelectorbiped:18:98" left 18
			-af "asSelectorbiped:18:98" top 98
			-af "asSelectorbiped:292:98" left 292
			-af "asSelectorbiped:292:98" top 98
			-af "asSelectorbiped:67:85" left 67
			-af "asSelectorbiped:67:85" top 85
			-af "asSelectorbiped:243:85" left 243
			-af "asSelectorbiped:243:85" top 85
			-af "asSelectorbiped:141:42" left 141
			-af "asSelectorbiped:141:42" top 42
			-af "asSelectorbiped:165:42" left 165
			-af "asSelectorbiped:165:42" top 42
			-af "asSelectorbiped:105:46" left 105
			-af "asSelectorbiped:105:46" top 46
			-af "asSelectorbiped:181:46" left 181
			-af "asSelectorbiped:181:46" top 46
			-af "asSelectorbiped:71:47" left 71
			-af "asSelectorbiped:71:47" top 47
			-af "asSelectorbiped:217:47" left 217
			-af "asSelectorbiped:217:47" top 47
			-af "asSelectorbiped:139:3" left 139
			-af "asSelectorbiped:139:3" top 3
			-af "asSelectorbiped:117:13" left 117
			-af "asSelectorbiped:117:13" top 13
			-af "asSelectorbiped:188:13" left 188
			-af "asSelectorbiped:188:13" top 13
			-af "asSelectorbiped:85:9" left 85
			-af "asSelectorbiped:85:9" top 9
			-af "asSelectorbiped:214:9" left 214
			-af "asSelectorbiped:214:9" top 9
			-af "asSelectorbiped:138:141" left 138
			-af "asSelectorbiped:138:141" top 141
			-af "asSelectorbiped:162:141" left 162
			-af "asSelectorbiped:162:141" top 141
			-af "asSelectorbiped:140:184" left 140
			-af "asSelectorbiped:140:184" top 184
			-af "asSelectorbiped:162:184" left 162
			-af "asSelectorbiped:162:184" top 184
			-af "asSelectorbiped:139:219" left 139
			-af "asSelectorbiped:139:219" top 219
			-af "asSelectorbiped:162:219" left 162
			-af "asSelectorbiped:162:219" top 219
			-af "asSelectorbiped:123:225" left 123
			-af "asSelectorbiped:123:225" top 225
			-af "asSelectorbiped:182:225" left 182
			-af "asSelectorbiped:182:225" top 225
			-af "asSelectorbiped:89:221" left 89
			-af "asSelectorbiped:89:221" top 221
			-af "asSelectorbiped:218:221" left 218
			-af "asSelectorbiped:218:221" top 221
			-af "asSelectorbiped:103:195" left 103
			-af "asSelectorbiped:103:195" top 195
			-af "asSelectorbiped:194:195" left 194
			-af "asSelectorbiped:194:195" top 195
			-af "asSelectorbiped:104:168" left 104
			-af "asSelectorbiped:104:168" top 168
			-af "asSelectorbiped:195:168" left 195
			-af "asSelectorbiped:195:168" top 168
			-af "asSelectorbiped:107:146" left 107
			-af "asSelectorbiped:107:146" top 146
			-af "asSelectorbiped:198:146" left 198
			-af "asSelectorbiped:198:146" top 146
			-af "asSelectorbiped:141:102" left 141
			-af "asSelectorbiped:141:102" top 102
			-af "asSelectorbiped:141:80" left 141
			-af "asSelectorbiped:141:80" top 80
			-af "asSelectorbiped:141:58" left 141
			-af "asSelectorbiped:141:58" top 58
			-af "asSelectorbiped:189:111" left 189
			-af "asSelectorbiped:189:111" top 111
			-af "asSelectorbiped:189:91" left 189
			-af "asSelectorbiped:189:91" top 91
			-af "asSelectorbiped:189:70" left 189
			-af "asSelectorbiped:189:70" top 70
			-af "asSelectorbiped:126:159" left 126
			-af "asSelectorbiped:126:159" top 159
			-af "asSelectorbiped:183:159" left 183
			-af "asSelectorbiped:183:159" top 159
			-af "asSelectorbiped:83:35" left 83
			-af "asSelectorbiped:83:35" top 35
			-af "asSelectorbiped:226:35" left 226
			-af "asSelectorbiped:226:35" top 35
			-af "asSelectorbiped:98:35" left 98
			-af "asSelectorbiped:98:35" top 35
			-af "asSelectorbiped:211:35" left 211
			-af "asSelectorbiped:211:35" top 35
			-af "asSelectorbiped:113:35" left 113
			-af "asSelectorbiped:113:35" top 35
			-af "asSelectorbiped:196:35" left 196
			-af "asSelectorbiped:196:35" top 35
			-af "asSelectorbiped:7:10" left 7
			-af "asSelectorbiped:7:10" top 10
			-af "asSelectorbiped:136:122" left 136
			-af "asSelectorbiped:136:122" top 122
			-af "asSelectorbiped:18:29" left 18
			-af "asSelectorbiped:18:29" top 29
			-af "asSelectorbiped:18:46" left 18
			-af "asSelectorbiped:18:46" top 46
			-af "asSelectorbiped:29:46" left 29
			-af "asSelectorbiped:29:46" top 46
			asSelectorbipedFormLayout;


		s100CFRFcreateLayout;

		s100asPopulateNameSpaceMenu "asSelectorbiped";
		asShowSelJob;
		asSelChange;
		window -e -sizeable 0  -w 334 -h 344 asSelectorbiped;

		if (`waitCursor -q -state`)
			waitCursor -st 0;

		//s100CFRFRefreshTabLayout ;
		showWindow;
	}


//     AdvancedSkeleton
//     Version 3.5
//
//
// AdvancedSkeleton is is a collection of Maya tools for doing character setup.
//
// INSTALLATION:
// Run the SETUP file (setup.exe)
// Choose the Destination Folder.
// NOTE: destination folder must be your Maya user directory
// eg: C:\Users\$user\Documents\maya\2011\
// Continue installation.
// Start Maya.
// Now you will find a new Shelf called 'advancedSkeleton':
//
// For detailed instructions go to: www.animationstudios.com.au
//
// Copyright (C)2010 Animation Studios
//
// email: support@animationstudios.com.au
// Last Modified 13/08/2010

//s100asSelectorbiped;


	//add pour la camera sur la tete

	// $name = "asSelectorbiped";
	// s100asPopulateNameSpaceMenu ( $name)

	global proc s100asPopulateNameSpaceMenu (string $name)
	{
		string $optionMenu=$name+"OptionMenu";
		string $nameSpacesList[]=`namespaceInfo -lon`;
		$nameSpacesList = `stringArrayRemove {"UI","shared"} $nameSpacesList`;

		// adding an empty namespace to be able to work with no ref :
		$nameSpacesList[size($nameSpacesList)]="";
		$nameSpacesList=`sort $nameSpacesList`;

		// clearing items for optionMenu:
		string $itemList[]=`optionMenu -q -ils $optionMenu`;
		for ($item in $itemList)
			deleteUI $item;

		string $out[] ;
		$i= 0 ;
		for ($nameSpace in $nameSpacesList) // $nameSpace = $nameSpacesList[0]
		{
			// QA change : looking for attribute ".meshDisplay" (from S100 patches) on "Main" now as well,
			// not only ".version" (from advanced skeleton)
			string $specAttr = "version";
			$ls = `ls ($nameSpace+":Main."+$specAttr) ($nameSpace+":*:Main."+$specAttr) ($nameSpace+":*:*:Main."+$specAttr)` ;
			if(size($ls) == 0)
			{
				$specAttr = "meshDisplay";
				$ls = `ls ($nameSpace+":Main."+$specAttr) ($nameSpace+":*:Main."+$specAttr) ($nameSpace+":*:*:Main."+$specAttr)` ;
            }
			if(size($ls) > 0)
			{
				// adding a starting ":" in case of empty/root namespace:
				if ($ls[0]==("Main."+$specAttr))
					$ls[0] = ":"+$ls[0];

				$out[$i] = $nameSpace = substituteAllString($ls[0] ,(":Main."+$specAttr),"") ;
				$i++;
			}
		}
		$nameSpacesListN = stringArrayRemoveDuplicates($out);
		for ($nameSpace in $nameSpacesListN)
			menuItem -p $optionMenu -l ($nameSpace+":");

		if (!`optionMenu -q -ni ($name+"OptionMenu")`)
		{
			if ($name=="asUtilities" || `gmatch $name "asPoser*"`)
				menuItem -p $optionMenu -l "None";
			else
				menuItem -p $optionMenu -l ":";
		}
	}


global proc s100asAddHeadCam()
{
	string $cam = `s100asAddHeadCamGetNameCamera`;
	if(`optionMenu  -ex asSelectorbipedOptionMenu`)
	{
		string $char = `optionMenu -q -v  asSelectorbipedOptionMenu`;
		string $cameraTmp[] = `ls ($char + $cam ) ( $char +"*:*:*" + $cam )  ( $char +"*:*" + $cam ) ("*:*:"+ $char + $cam ) ("*:"+ $char + $cam ) ("*:*:"+ $char + $cam ) ` ;
		string $camera = ($char + $cam ) ;
		$camera = $cameraTmp[0];
		if(`objExists $camera`)
		{
			s100asAddHeadCreatePanel($char, $camera, "camera") ;
		}else{
			warning ("no facial camera inside the character " + 	$char ) ;
		}

    }
}


global proc s100asAddHeadResetCam(string $camera)
{
	if(`objExists $camera`)
	{
		setAttr ($camera +".tx") 0 ;
		setAttr ($camera +".ty") 0 ;
		setAttr ($camera +".tz") 0 ;
    }
}


// string $seeThruType = "camera" or "light"
// string $char = "local";
// string $camera = "root_ctrl";
//
global proc s100asAddHeadCreatePanel(string $char, string $camera, string $seeThruType )
{
	//get sel to get it back latter
	//$char = "C_MayaOriginal_01_01:"
	//$camera = "C_MayaOriginal_01_01:facial_cam"
	string $var[] = `ls -sl`;

	$sub =substituteAllString($char ,":" ,"_");
	$uiName = ($sub +"SeeThruCam") ;

		if(`window -exists $uiName`)
			deleteUI   $uiName ;

	// checking if we work with a camera or a light :
	string $cameraShape = $camera;
	if ($seeThruType == "light")
	{
		string $shapes[] = `listRelatives -s -ni -type "spotLight" $camera`; // $camera = $thruCam; $camera = "root_ctrl"
		if (size($shapes))
			$cameraShape = $shapes[0];
		else
			$cameraShape = "";
    }
	// if we're with a light and no spotLight is foundable : stopping..
	if (size($cameraShape)==0)
	{
		warning ("no camera or light is foundable with passed arguments, stopping.");
		return;
    }


	// WINDOW :

	window -h 200 -w 200 $uiName ;
	$lay = `formLayout`;


	$but = "";
	if ($seeThruType == "camera")
		$but = `button -l "reset Cam" -c ("s100asAddHeadResetCam(\"" + $camera +"\")") `; // button -e -en 1 $but;
	else if ($seeThruType == "light")
		$but = `button -l "select Light" -c ("select -r (\"" + $camera +"\")") `; // button -e -en 0 $but;


	//$model = `modelPanel -menuBarVisible 0 -p $lay -camera $cameraShape `;
	$model = `modelPanel -menuBarVisible 0 -p $lay -camera persp `;
	lookThru -nc 0.001 -fc 1000 $cameraShape $model;

		formLayout -e
		-attachForm $but "top" 5
		-attachForm $but "left" 5
		-attachForm $but "right" 5

		-attachControl $model "top" 5 $but
		-attachForm $model "bottom" 5
		-attachForm $model "left" 5
		-attachForm $model "right" 5
		$lay ;

	//preference d affichage
		$text = 0 ;
		if(`objExists ($char + "geoCacheSet")` && $seeThruType == "camera")
			$text = 1 ;
		int $lighted = 0;
		if ($seeThruType == "light")
			$lighted = 1;

		modelEditor -e 	-wireframeOnShaded 0
						-displayAppearance "smoothShaded"
						-dynamics 0
						-shadows 0
						-lights $lighted
						-displayTextures $text
						-pm 1
						-nurbsCurves 0
						-nurbsSurfaces 1
						-m 0
						-hud 0
						-grid 0
						$model ;

	//enleve le safe frame
	if($seeThruType == "camera")
		camera -e -displayFilmGate 0 -displayResolution 0 -overscan 1.0 $camera;

	//selection isolee sur le perso
		if(`objExists ($char + "geoCacheSet")` && $seeThruType == "camera")
		{
			select ($char + "geoCacheSet");
			isolateSelect -state 1 $model;
		}

	window -e  -h 300 -w 300 $uiName ;

	showWindow ;


	if(`objExists ($char + "geoCacheSet")` && $seeThruType == "camera")
	{
		scriptJob -uiDeleted $uiName ("modelEditor -e  -viewSelected 0 "+$model+" ; deleteUI "+$model +";");
	}
	//get back selection
	if(size($var) > 0)
	{
		select $var ;
    }else{
		select -cl;
    }
}

// nom de la camera dans le rig si elle existe,
//
global proc string s100asAddHeadCamGetNameCamera()
{
	return "facial_cam";
}

global proc s100asAddHeadCamForSelectedCharacter()
{
	string $thruCam = "";
	string $cam = `s100asAddHeadCamGetNameCamera`;
	string $lgtAttr = "*.s100_isLightCamera";
	string $seeThruType = "camera";

	string $var[] = `ls -sl`;
	if(size($var) > 0 )
	{
		string $arr[] = stringToStringArray($var[0] , ":") ;
		if(`gmatch $arr[0] "*C_*"` ||  `gmatch $arr[0] "*P_*"`)
		{
			string $char = $arr[0] +":";
			string $cameraTmp[] = `ls ($char+$cam) ($char+"*:*:*"+$cam) ($char+"*:*"+$cam ) ("*:*:"+$char+$cam) ("*:"+$char+$cam) ("*:*:"+$char+$cam) ` ;
			if(size($cameraTmp))
				$thruCam = $cameraTmp[0];
			else
			{
				warning ("no facial camera inside the selected character or props '"+$char+"'. Is there a LightCamera ?" ) ;
				// sinon, on recherche une light qui porte l'attribut "s100_isLightCamera"
				string $lightCamTmp[] = `ls -o ($char+$lgtAttr) ($char+"*:*:*"+$lgtAttr) ($char+"*:*"+$lgtAttr) ("*:*:"+$char+$lgtAttr) ("*:"+$char+$lgtAttr) ("*:*:"+$char+$lgtAttr)`;
				if(size($lightCamTmp))
				{
					$thruCam = $lightCamTmp[0];
					$seeThruType = "light";
                }
			}
		}
		else
			warning "you must select a Character or Props in reference";
	}
	else
	{
		if (`objExists $cam`)
			$thruCam = $cam;
	}

	if(size($thruCam))
		print ("// Will use facial camera '"+$thruCam+"'...\n");
	else
	{
		print ("// No facial camera inside the scene. Is there a LightCamera ?.." ) ;
		string $lightCamTmp[] = `ls -o ($lgtAttr) `;
		if(size($lightCamTmp))
		{
			$thruCam = $lightCamTmp[0];
			$seeThruType = "light";
			print " Yes ! :)\n";
        }
		else
			print " Nope :(\n";
	}

	if(size($thruCam))
		s100asAddHeadCreatePanel("local", $thruCam, $seeThruType) ;
	else
		warning "No facial camera or see-thru light found in the (referenced expected) selection nor the scene!";
}



global proc s100AsModCreateFacialCam()
{
	string $list2[] = `ls "Head_M" "Head*_M" "*:Head_M" "*:*:Head_M"`;
	$nameSpace = substituteAllString($list2[0] , "Head_M","") ;
	string $list3[] = `ls "Hair_M" "Hair*_M" "*:Hair_M" "*:*:Hair_M" "Head_End_M" "*:Head_End_M"`;

	$upV = $list3[0] ;
	$chFailed = 0 ;
	string $return ;
	if(!`objExists "facial_cam"`)
	{
		if(`objExists  $list2[0]`)
		{
			if(`objExists  $upV`)
			{
				float $dist = `getAttr ($upV +".tx" )`/ 2 ;
				s100AsModCreateFacialCamWithArg($list2[0],$upV , $dist ) ;
			}
			else
			{
				$return = "no up vector object";
				$chFailed = 1 ;
			}

		}
		else
		{
			$return = "no object for constraint";
			$chFailed = 1 ;
        }
    }
	else
	{
		//$return = "camera facial_cam already exists, delete it";
		$chFailed = 2 ;
    }

	if($chFailed > 0)
	{
		if($chFailed == 1 )
		{
			$conf = `confirmDialog -title "problem creating camera facial" -message "Unable to create facial cam,do you want to create Helper for it?"
			-button "Yes" -button "No" -defaultButton "Yes"
			-cancelButton "No" -dismissString "No" `;

			if($conf == "Yes")
			{
					$consUp = `createNode -n "facialCam_aim_locShape" locator`;
					$upUp = `createNode -n "facialCam_up_locShape" locator`;
					s100AsModCreateFacialCamWithArg($consUp,$upUp , 3 ) ;
			}
        }
		warning $return ;
    }
}



global proc s100AsModCreateFacialCamWithArg(string $toConstraint,string $upV, float $dist)
{
	$ch = 1 ;
	string $ls[] = `ls "facial_cam" "*:facial_cam" "*:*:facial_cam"`;

	if(size($ls) == 0  && $ch)
	{
		if(!`objExists "facialCam_grp"`)
		{
			if(!`objExists "full_grp"`)
				$ch  = 0 ;

			if(!`objExists "deform_grp"`)
				group -em -n 	"deform_grp" -p  "full_grp" ;

			if($ch)
			{
				print "\n--create facialCam_grp";
				group -em -n "facialCam_grp" -p "deform_grp" ; xform -os -piv 0 0 0;
				if(!`objExists "facialCam_oGrp"  `)
					group -em -n "facialCam_oGrp" -p "facialCam_grp" ; xform -os -piv 0 0 0;
				setAttr -k 0  -l 1 ("facialCam_grp.v") 0;
			}
		}
		if(size($ls) == 0  && $ch)
		{
			print "\n--create facial_cam";
			string $cam[] = `camera  -centerOfInterest 5 -focalLength 35 -lensSqueezeRatio 1 -cameraScale 1 -horizontalFilmAperture 1.41732 -horizontalFilmOffset 0 -verticalFilmAperture 0.94488 -verticalFilmOffset 0 -filmFit Fill -overscan 1 -motionBlur 0 -shutterAngle 144 -nearClipPlane 0.01 -farClipPlane 1000 -orthographic 0 -orthographicWidth 30 `; objectMoveCommand; cameraMakeNode 1 "";
			rename  $cam[0] "facial_cam";
			parent "facial_cam" "facialCam_oGrp" ;
		}
    }
	else
	{
		$list = `listRelatives -p "facial_cam"`;
		if($list[0] != "facialCam_oGrp")
		if(!`objExists "facialCam_oGrp"  `)
		{
			group -em -n "facialCam_oGrp" -p "facialCam_grp" ; xform -os -piv 0 0 0;
			parent "facial_cam" "facialCam_oGrp" ;
        }
		print "\n----facial camera already exists, skipped";
    }

	$list2[0] = $toConstraint ;

	if(size($list2) > 0)
	{
		$nameSpace = substituteAllString($list2[0] , "Head_M","") ;
		string $list[] = `listConnections -type parentConstraint "facialCam_grp"` ;
		if(size($list) ==0)
		{
			$grp = `createNode transform`;
			parent $grp $list2[0] ;
			setAttr ($grp +".tx") ($dist);setAttr ($grp +".ty") 13; setAttr ($grp +".tz") 0;

			print "\n--create parent constraint to facialCam_grp";
			$pa = `pointConstraint  $grp  "facialCam_grp"`;
			delete $pa ;

			$pa = `parentConstraint -maintainOffset $list2[0]  "facialCam_grp"`;
			delete $grp ;
		}

		string $list[] = `listConnections -type scaleConstraint "facialCam_grp"` ;
		if(size($list) ==0)
		{
			if(!`getAttr ("facialCam_grp.sx")`)
			{
				print "\n--create scale constraint to facialCam_grp";
				scaleConstraint $list2[0]  "facialCam_grp"  ;
			}
		}

		lockAndHiddeAll("facialCam_grp") ;
		lockAll("facialCam_oGrp");
		string $list[] = `listConnections -type aimConstraint "facial_cam"` ;
		if(size($list) ==0)
		{
			$aim = `aimConstraint -offset 0 0 0 -weight 1 -aimVector 0 0 -1 -upVector 0 1 0 -worldUpType "object" -worldUpObject $upV $toConstraint  "facial_cam" `;
			setAttr -k 0  -l 1 ("facial_cam.rx");
			setAttr -k 0  -l 1 ("facial_cam.ry");
			setAttr -k 0  -l 1 ("facial_cam.rz");
			setAttr -k 0  -l 1 ("facial_cam.sx");
			setAttr -k 0  -l 1 ("facial_cam.sy");
			setAttr -k 0  -l 1 ("facial_cam.sz");
			setAttr -k 0  -l 1 ("facial_cam.v");

			setAttr -l 1  ($aim[0] +".ox") ;
			setAttr -l 1  ($aim[0] +".oy") ;
			setAttr -l 1  ($aim[0] +".oz") ;
			setAttr -l 1  ($aim[0] +".w0") ;
		}
	}
}



global proc string [] s100_getLipSyncCtrls(string $nameSpace )
{
	if (!endsWith($nameSpace,":"))
		$nameSpace = $nameSpace+":";

	string $list[] = {"A_mouth_ctrl", "M_B_P_mouth_ctrl", "U_Ou_mouth_ctrl", "O_mouth_ctrl"} ;
	string $ret[] = {} ;

	for($i = 0 ; $i < size($list) ;$i++)
	{
		string $toto = $nameSpace+$list[$i];
		if (objExists($toto))
			$ret[size($ret)] = $toto ;
    }
	return $ret ;
}




//     AdvancedSkeleton modified by s100
//     Version 3.5
//
//
// AdvancedSkeleton is is a collection of Maya tools for doing character setup.
//
// INSTALLATION:
// Run the SETUP file (setup.exe)
// Choose the Destination Folder.
// NOTE: destination folder must be your Maya user directory
// eg: C:\Users\$user\Documents\maya\2011\
// Continue installation.
// Start Maya.
// Now you will find a new Shelf called 'advancedSkeleton':
//
// For detailed instructions go to: www.animationstudios.com.au
//
// Copyright (C)2010 Animation Studios
//
// email: support@animationstudios.com.au
// Last Modified 13/08/2010

//s100asSelectorbiped;