global proc int s100VMgetifRefIsLock(string $obj)
{
//$obj = "MA_L_GroundModule2_01:V_Coprinus_Hi_01:cap_01_msh"
$ch = 0 ;
	if(`objExists "VM_manage_scN"`)
	{
		if(`attributeExists "forceAssets" "VM_manage_scN"`)
		{
		$ref = `referenceQuery -referenceNode $obj` ;
		$getAttrName = `getAttr -asString  ( "VM_manage_scN.forceAssets") `;
		$array = stringToStringArray($getAttrName, ";") ;

			for($i = 0 ; $i < size($array) ; $i++)
			{
				if(	$array[$i] == $ref)
				{
				$ch = 1 ;
				break ;
                }
            }

        }

	}

return $ch ;

}