//////////////////////////////////////////////////////////
//
//	Script Name: HbSK2ArmRepair
//	Author: Justin.Chan
//	Created: 2011/09/21
//
//	Update/Change: 
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc HbSK2ArmRepair()
{
	string $arm[] = `ls "LeftArm_rig_elbow" "RightArm_rig_elbow" "*:LeftArm_rig_elbow" "*:RightArm_rig_elbow"`;
	if (size ($arm)>1)
		{
		for ($aa in $arm)
			{
			setAttr ($aa+".preferredAngleY") 14;
			}		
		}
}
HbSK2ArmRepair;