/// Copyright (C) 2000-2007 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2007/02/26
///
/// Description: littleTike项目渲染环节自动分层工具（包含子程序ezBackgroundRenderLayer.mel，ezCharacterRenderLayer.mel等）
///

global proc ltAutoCreateRL()
{
	
	source "ltAssignMaterial.mel";
	ltCreateMaterialNode();	
	miCreateDefaultNodes();
	miCreateOtherOptionsNodesForURG();
	
	string $vis[] = ezRGLock();
	if(`window -exists lt_createRL_win`)
		deleteUI lt_createRL_win;
	window -title "Create RenderLayers(LT) v1" -mb true  -s true -resizeToFitChildren true lt_createRL_win;
		
		menu -label "Help";
			menuItem -label "Help on AutoCreateRL..." -command "zjHelpCallback ltAutoCreateRL";
		
			string $columnLayout = `columnLayout -adjustableColumn true -rs 10`;
				string $charFrLayout = `frameLayout -label "Character render layer" -labelAlign "top" -cll false  -borderStyle "etchedIn"`;
					string $charFoLayout = `formLayout`;
						string $createRL = `button -l "创建角色相关渲染层"  -h 30 -command "lt_createCharRL"`;
						string $charButton = `button -l "选择角色加入渲染层" -h 30 -command "lt_addCharRL"`;
						string $propButton = `button -l "选择相关道具加入渲染层" -h 30 -command "lt_addPropRL"`;
						string $matteButton = `button -l "选择matte物体加入渲染层"  -h 30 -command "lt_addMatteRL"`;
						string $lightButton = `button -l "选择Light加入渲染层"  -h 30 -command "lt_addLightRL(\"character\")"`;
						setParent ..;
					formLayout -edit
						-attachForm	$createRL		"top"		10
						-attachForm	$createRL		"left"		20
						-attachForm	$createRL		"right"		20
						
						-attachControl	$charButton		"top"		10	$createRL
						-attachForm	$charButton		"left"		20
						-attachForm	$charButton		"right"		20
										
						-attachControl	$propButton		"top"		10	$charButton
						-attachForm	$propButton		"left"		20
						-attachForm	$propButton		"right"		20
						
						-attachControl	$matteButton		"top"		10	$propButton
						-attachForm	$matteButton		"left"		20
						-attachForm	$matteButton		"right"		20

						-attachControl	$lightButton		"top"		10	$matteButton
						-attachForm	$lightButton		"left"		20
						-attachForm	$lightButton		"right"		20
						-attachForm	$lightButton		"bottom"	10
					$charFoLayout;
				setParent ..;
				
				string $bgFrLayout = `frameLayout -label "Background&Shadow render layer" -labelAlign "top" -cll false  -borderStyle "etchedIn"`;
					string $bgFoLayout = `formLayout`;
						string $bgButton = `button -l "选择场景及相关道具创建渲染层(BG)"  -h 30 -command "lt_createBGRL"`;
						string $castButton = `button -l "Casts Obj"  -h 30 -command "lt_createShadowRL(1)"`;
						string $receButton = `button -l "RecesObj Lights"  -h 30 -command "lt_createShadowRL(2)"`;
						string $depthButton = `button -l "选择物体创建景深渲染层(Depth)"  -h 30 -command "lt_createDepthRL"`;
						string $skyButton = `button -l "选择物体创建天空渲染层(Sky)"  -h 30 -command "lt_createSkyRL"`;
						string $depthtemp = `button -l "面片树场景用(Depth)"  -h 30 -command "lt_createDepthTemp"`;
						string $lightcauBut = `button -l "海底场景用焦散层"  -h 30 -command "ltRenderLightcau"`;
						setParent ..;
					formLayout -edit
						-attachForm	$bgButton		"top"		10
						-attachForm	$bgButton		"left"		20
						-attachForm	$bgButton		"right"		20

						-attachControl	$castButton		"top"		10	$bgButton
						-attachForm	$castButton		"left"		20
						-attachPosition	$castButton		"right"		0	47

						-attachControl	$receButton		"top"		10	$bgButton
						-attachControl	$receButton		"left"		10	$castButton
						-attachPosition	$receButton		"right"		0	94
						
						-attachControl	$depthButton		"top"		10	$castButton
						-attachForm	$depthButton		"left"		20
						-attachForm	$depthButton		"right"		20

						-attachControl	$skyButton		"top"		10	$depthButton
						-attachForm	$skyButton		"left"		20
						-attachForm	$skyButton		"right"		20

						-attachControl	$depthtemp		"top"		10	$skyButton
						-attachForm	$depthtemp		"left"		20
						-attachForm	$depthtemp		"right"		20

						-attachControl	$lightcauBut		"top"		10	$depthtemp
						-attachForm	$lightcauBut		"left"		20
						-attachForm	$lightcauBut		"right"		20
						-attachForm	$lightcauBut		"bottom"	10

					$bgFoLayout;
				setParent ..;	
				
				string $materialFrLayout = `frameLayout -label "" -labelAlign "top" -cll false  -borderStyle "etchedIn"`;
					string $materialFoLayout = `formLayout`;
						string $materialButton = `button -l "Material 工具"  -h 30 -command "ltAssignMaterial"`;
						
						string $mayaLayer = `button -l "自定义mayasoftware渲染层"  -h 30 -command "ltMayaSoftwareRG"`;
						string $mayaLayerLock = `button -l $vis[0]  -h 30 _mayaBut`;
						button -e -command ("ezUpdateLock(\"maya\")") $mayaLayerLock; 




						
						string $mentalLayer = `button -l "自定义mentalray渲染层"  -h 30 -command "ltMentalRayRG(\"\")"`;
						string $mentalLayerLcok = `button  -l $vis[1]  -h 30 _mentalBut`;
						button -e -command ("ezUpdateLock(\"mental\")") $mentalLayerLcok; 
						setParent ..;
					formLayout -edit
						-attachForm	$materialButton		"top"		10
						-attachForm	$materialButton		"left"		20
						-attachForm	$materialButton		"right"		20

						-attachControl	$mayaLayer		"top"		10	$materialButton
						-attachForm	$mayaLayer		"left"		20
						-attachPosition	$mayaLayer		"right"		0	70
						
						-attachControl	$mentalLayer		"top"		10	$mayaLayer
						-attachForm	$mentalLayer		"left"		20
						-attachPosition	$mentalLayer		"right"		0	70
						-attachForm	$mentalLayer		"bottom"	10
						
						-attachControl	$mayaLayerLock		"top"		10	$materialButton
						-attachControl	$mayaLayerLock		"left"		10	$mayaLayer
						-attachPosition	$mayaLayerLock		"right"		0	93


						-attachControl	$mentalLayerLcok	"top"		10	$mayaLayer
						-attachControl	$mentalLayerLcok	"left"		10	$mentalLayer
						-attachPosition	$mentalLayerLcok	"right"		0	93
						-attachForm	$mentalLayerLcok	"bottom"	10
					$materialFoLayout;
				setParent ..;		
		
	showWindow lt_createRL_win;

	string $shapes[] = `ls "*:*_me1" "*_me1" "*:*pupil1" "*pupil1"`;
	for ($shape in $shapes )
	{
		//string $tran[] = `pickWalk -d up $shape`;
		setAttr ($shape+".visibility") 0;
	}

	source "ltCharacterRenderLayer.mel";
	source "ltBackgroundRenderLayer.mel";
	select -cl;
}


global proc ltMayaSoftwareRG()
{
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	setAttr defaultRenderGlobals.currentRenderer -type "string" "mayaSoftware";

	editRenderLayerAdjustment "defaultRenderQuality.edgeAntiAliasing";
	setAttr "defaultRenderQuality.edgeAntiAliasing" 0;
	editRenderLayerAdjustment "defaultRenderQuality.shadingSamples";
	setAttr "defaultRenderQuality.shadingSamples" 2;
	editRenderLayerAdjustment "defaultRenderQuality.maxShadingSamples";
	setAttr "defaultRenderQuality.maxShadingSamples" 8;

	editRenderLayerAdjustment "defaultRenderQuality.useMultiPixelFilter";
	setAttr "defaultRenderQuality.useMultiPixelFilter" 1;
	editRenderLayerAdjustment "defaultRenderQuality.pixelFilterType";
	setAttr "defaultRenderQuality.pixelFilterType" 2;
	editRenderLayerAdjustment "defaultRenderQuality.pixelFilterWidthX";
	setAttr "defaultRenderQuality.pixelFilterWidthX" 2.2;
	editRenderLayerAdjustment "defaultRenderQuality.pixelFilterWidthY";
	setAttr "defaultRenderQuality.pixelFilterWidthY" 2.2;

	editRenderLayerAdjustment "defaultRenderQuality.redThreshold";
	setAttr "defaultRenderQuality.redThreshold" 0.4;
	editRenderLayerAdjustment "defaultRenderQuality.greenThreshold";
	setAttr "defaultRenderQuality.greenThreshold" 0.3;
	editRenderLayerAdjustment "defaultRenderQuality.blueThreshold";
	setAttr "defaultRenderQuality.blueThreshold" 0.6;
}


global proc ltMentalRayRG(string $ao)
{
	if (`pluginInfo -query -loaded "Mayatomr.mll"`)
	{
		editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
		setAttr defaultRenderGlobals.currentRenderer -type "string" "mentalRay" ;

		editRenderLayerAdjustment "miDefaultOptions.minSamples";
		setAttr "miDefaultOptions.minSamples" 0;			
		editRenderLayerAdjustment "miDefaultOptions.maxSamples";
		setAttr "miDefaultOptions.maxSamples" 2;

		
		editRenderLayerAdjustment "miDefaultOptions.filter";
		editRenderLayerAdjustment "miDefaultOptions.filterWidth";
		editRenderLayerAdjustment "miDefaultOptions.filterHeight";
		setAttr "miDefaultOptions.filter" 2;

		editRenderLayerAdjustment "miDefaultOptions.contrastR";
		setAttr "miDefaultOptions.contrastR" 0.1;
		editRenderLayerAdjustment "miDefaultOptions.contrastG";
		setAttr "miDefaultOptions.contrastG" 0.1;
		editRenderLayerAdjustment "miDefaultOptions.contrastB";
		setAttr "miDefaultOptions.contrastB" 0.1;
		editRenderLayerAdjustment "miDefaultOptions.contrastA";
		setAttr "miDefaultOptions.contrastA" 0.1;

		editRenderLayerAdjustment "miDefaultOptions.sampleLock";
		setAttr "miDefaultOptions.sampleLock" 1;

		editRenderLayerAdjustment "miDefaultOptions.rayTracing";
		setAttr "miDefaultOptions.rayTracing" 1;
		
		editRenderLayerAdjustment "miDefaultOptions.maxReflectionRays";
		setAttr "miDefaultOptions.maxReflectionRays" 0;
		
		editRenderLayerAdjustment "miDefaultOptions.maxRefractionRays";
		setAttr "miDefaultOptions.maxRefractionRays" 0;
		
		editRenderLayerAdjustment "miDefaultOptions.maxRayDepth";
		setAttr "miDefaultOptions.maxRayDepth" 2;

		editRenderLayerAdjustment "miDefaultOptions.maxShadowRayDepth";
		setAttr "miDefaultOptions.maxShadowRayDepth" 2;

		editRenderLayerAdjustment "mentalrayGlobals.passAlphaThrough";
		setAttr "mentalrayGlobals.passAlphaThrough" 1;
	}
}

global proc ezUpdateLock(string $button)
{
	string $vis[];

	if ($button == "maya")
	{
		$vis = ezRGLock();
		ezMayaSoftwareRGLock($vis[0]);
		$vis = ezRGLock();
		button -e -l $vis[0]  _mayaBut;
	}
	else 
	{
		$vis = ezRGLock();
		ezMentalRayRGLock($vis[1]);
		$vis = ezRGLock();
		button -e -l $vis[1]  _mentalBut;
	}
}

global proc string[] ezRGLock()
{
	string $vis[];
	string $mayaRGAttr[]={"edgeAntiAliasing","shadingSamples","maxShadingSamples","useMultiPixelFilter","pixelFilterType","pixelFilterWidthX","pixelFilterWidthY",
			  "redThreshold","greenThreshold","blueThreshold"};
	string $mentalRGAttr[]={"minSamples","maxSamples","filter","filterWidth","filterHeight","contrastR","contrastG","contrastB","contrastA","sampleLock","rayTracing",
				"maxReflectionRays","maxRefractionRays","maxRayDepth","maxShadowRayDepth"};
	
	for ($tem in $mayaRGAttr)
	{
		$vis[0] = "锁Lock";
		int $temp = `getAttr -l ("defaultRenderQuality."+$tem)`;
		if ($temp == 1)
		{
			$vis[0] = "解锁Unlock";
			break;
		}
	}
	for ($tem in $mentalRGAttr)
	{
		$vis[1] = "锁Lock";
		int $temp = `getAttr -l ("miDefaultOptions."+$tem)`;
		if ($temp == 1)
		{
			$vis[1] = "解锁Unlock";
			break;
		}
	}
	return $vis;
}

global proc ezMayaSoftwareRGLock(string $adj)
{
	if ($adj == "锁Lock")
		$lock = true ;
	else 
		$lock = false;

	setAttr -l $lock "defaultRenderQuality.edgeAntiAliasing";
	setAttr -l $lock "defaultRenderQuality.shadingSamples" ;
	setAttr -l $lock "defaultRenderQuality.maxShadingSamples" ;
	setAttr -l $lock "defaultRenderQuality.useMultiPixelFilter";
	setAttr -l $lock "defaultRenderQuality.pixelFilterType";
	setAttr -l $lock "defaultRenderQuality.pixelFilterWidthX" ;
	setAttr -l $lock "defaultRenderQuality.pixelFilterWidthY" ;
	setAttr -l $lock "defaultRenderQuality.redThreshold" ;
	setAttr -l $lock "defaultRenderQuality.greenThreshold" ;
	setAttr -l $lock "defaultRenderQuality.blueThreshold" ;
}

global proc ezMentalRayRGLock(string $adj)
{
	if ($adj == "锁Lock")
		$lock = true ;
	else 
		$lock = false;

	setAttr -l $lock "miDefaultOptions.minSamples" ;			
	setAttr -l $lock "miDefaultOptions.maxSamples" ;
	setAttr -l $lock "miDefaultOptions.filter" ;
	setAttr -l $lock "miDefaultOptions.filterWidth" ;
	setAttr -l $lock "miDefaultOptions.filterHeight" ;
	setAttr -l $lock "miDefaultOptions.contrastR" ;
	setAttr -l $lock "miDefaultOptions.contrastG" ;
	setAttr -l $lock "miDefaultOptions.contrastB" ;
	setAttr -l $lock "miDefaultOptions.contrastA" ;
	setAttr -l $lock "miDefaultOptions.sampleLock" ;
	setAttr -l $lock "miDefaultOptions.rayTracing" ;
	setAttr -l $lock "miDefaultOptions.maxReflectionRays" ;
	setAttr -l $lock "miDefaultOptions.maxRefractionRays" ;
	setAttr -l $lock "miDefaultOptions.maxRayDepth" ;
	setAttr -l $lock "miDefaultOptions.maxShadowRayDepth" ;
	setAttr -l $lock "mentalrayGlobals.passAlphaThrough" ;
}


global proc lt_addLightRL(string $layer)
{

	string $lights[] = `ls -sl`;

	layerEditorLayerButtonSelect 0 $layer;
	updateHighlightSelectIcon;
	editRenderLayerMembers  $layer $lights;
}