global proc ltSceneTree()
{
	string $cams = `lookThru -q`;
	float $ry = `getAttr ($cams+".ry")`;

	string $treeLoc = "ltTreeLoc";
	if (!`objExists $treeLoc`)
	{
		 spaceLocator -p 0 0 0 -name ltTreeLoc;
	}

	string $objs[] = `ls -type mesh "*tree*" "*:*tree*"`;
	for ($obj in $objs)
	{
		if (!`getAttr ($obj+".castsShadows")`)
		{	
			string $tree[] = `pickWalk -d up $obj`;
			string $attr[] = `listConnections -plugs true ($tree[0]+".ry")`;
			if (!`objExists $attr[0]`)
			{
				connectAttr -f ($treeLoc+".ry") ($tree[0]+".ry");
			}
		}
	}

	setAttr ($treeLoc+".ry") $ry;
	select -r $treeLoc;
}