global proc lzyRomaChrOcc()
{

if(`pluginInfo -q -loaded "//file-cluster/GDC/Resource/Support/AnimalLogic/mayaman2.0.15/plugins/2008/MayaMan.mll"`)
{
	//set MayaMan Global Illumination Attr
	source makeMayaManMenu.mel; 
	setupMayaManMenu();

	setAttr "MayaManNugget.AmbOccOn" 1;
	setAttr "MayaManNugget.RadianceOn" 1;
	setAttr "MayaManNugget.IndirectIntensity" 1.1;
	setAttr "MayaManNugget.IndirectMaxHitDistOn" 1;
	setAttr "MayaManNugget.IndirectMaxHitDist" 500;
	setAttr "MayaManNugget.RadMaxVariation" 0.002;
	setAttr "MayaManNugget.IndirectBackground" -type double3 1 1 1 ;
	setAttr "MayaManNugget.IndirectShadow" -type double3 0 0 0 ;

	setAttr "MayaManNugget.EnableIndirectRayVisibility" 1;
	setAttr "MayaManNugget.RadMaxError" 0.1;
	setAttr "MayaManNugget.RadMaxPixelDist" 10;
	setAttr "MayaManNugget.RadSamples" 512;
	setAttr "MayaManNugget.IndirectSpecular" 0;
	setAttr "MayaManNugget.RadianceVisCullSize" 0;


	//delete all light
	string $lights[]=`ls -type "light"`;
	if(`size $lights`>0)
	{
		for($eachLight in $lights)
		{
			select $eachLight;
			pickWalk -d up;
			doDelete;
		}
	}


	//turn cameras background color to white
	string $cameras[]=`ls -type "camera"`;
	for($eachCamera in $cameras)
	{
		setAttr ($eachCamera + ".backgroundColor") -type double3 1 1 1 ;
	}


	//create occNode
	if(`objExists Mayaman_Occ_Shader`)
	{select -r Mayaman_Occ_Shader;doDelete;}
	createNode "lambert" -n "Mayaman_Occ_Shader";
	setAttr "Mayaman_Occ_Shader.color" -type double3 1 1 1 ;
	setAttr "Mayaman_Occ_Shader.diffuse" 1;


	//list all lambert
	string $shadingEngineList[] = `ls -exactType "shadingEngine"`;

	for($eachShadingEngine in $shadingEngineList)
	{
		if(($eachShadingEngine == "initialParticleSE")||($eachShadingEngine == "initialShadingGroup"))
			continue;
		connectAttr -force Mayaman_Occ_Shader.outColor ($eachShadingEngine + ".surfaceShader");
	}

}
else
{
	loadPlugin "//file-cluster/GDC/Resource/Support/AnimalLogic/mayaman2.0.15/plugins/2008/MayaMan.mll";
	pluginInfo -edit -autoload true "//file-cluster/GDC/Resource/Support/AnimalLogic/mayaman2.0.15/plugins/2008/MayaMan.mll";
	lzyRomaChrOcc();
}


}