global proc py_insertPluggy(){
	python ("try:\n\treload(ins)\nexcept:\n\timport RBW.MC.texturing.insertPluggy as ins ");
	python ("ins.insertPluggy()");

	// 修改意大利的工具，添加IDMT的“补”，huangzhongwei@idmt.com.cn, 20101210
	string $SLIncludePath = `getenv "PIPELINE_SCRIPTS"` + "/mel/plugins/windows/maya2008-32bit/mm_magic";
	if (`filetest -d $SLIncludePath`)
	{
		string $SLCodeNodes[] = `ls -type "SLCodeNode"`;
		for ($SLCodeNode in $SLCodeNodes)
		{
			string $str = `getAttr ($SLCodeNode + ".SLIncludePath")`;
			if ($str != $SLIncludePath)
			{
				setAttr -type "string" ($SLCodeNode + ".SLIncludePath") $SLIncludePath;
			}
		}
	}
}