global proc JH_earlyMornSun()
	{

///////////////////////////////////////////////////////////////////////////////
////Lightrig_earlyMornSun



////////////////////////////////////////////////BOUNCE_FLOOR_spot////////////////////////////
	setAttr "BOUNCE_FLOOR_spotShape.colorR" 0.699;
	setAttr "BOUNCE_FLOOR_spotShape.colorG" 0.492396;
	setAttr "BOUNCE_FLOOR_spotShape.colorB" 0.277503;
	setAttr "BOUNCE_FLOOR_spotShape.intensity" 0.15;
	setAttr "BOUNCE_FLOOR_spotShape.coneAngle" 60;
	setAttr "BOUNCE_FLOOR_spotShape.penumbraAngle" 5;
	setAttr "BOUNCE_FLOOR_spotShape.dropoff" 0;
	setAttr "BOUNCE_FLOOR_spotShape.emitDiffuse" 1;
	setAttr "BOUNCE_FLOOR_spotShape.emitSpecular" 0;
	setAttr BOUNCE_FLOOR_spotShape.decayRate 0;
	setAttr "BOUNCE_FLOOR_spot.visibility" 1;
//transforms
		setAttr "BOUNCE_FLOOR_spot.translateX" 141.663;
		setAttr "BOUNCE_FLOOR_spot.translateY" -52.531;
		setAttr "BOUNCE_FLOOR_spot.translateZ" 109.636;
		setAttr "BOUNCE_FLOOR_spot.rotateX" 22.8;
		setAttr "BOUNCE_FLOOR_spot.rotateY" 53.2;
		setAttr "BOUNCE_FLOOR_spot.rotateZ" 0;


////////////////////////////////////////////SKY_AMBIENT_spot///////////////////////////////////
	setAttr "SKY_AMBIENT_spotShape.colorR"  0.65;
	setAttr "SKY_AMBIENT_spotShape.colorG" 0.444247;
	setAttr "SKY_AMBIENT_spotShape.colorB" 0.1963 ;
	setAttr "SKY_AMBIENT_spotShape.intensity" 0.2;
	setAttr "SKY_AMBIENT_spotShape.coneAngle" 40;
	setAttr "SKY_AMBIENT_spotShape.penumbraAngle" 0;
	setAttr "SKY_AMBIENT_spotShape.dropoff" 0;
	setAttr "SKY_AMBIENT_spotShape.emitDiffuse" 1;
	setAttr "SKY_AMBIENT_spotShape.emitSpecular" 0;
	setAttr SKY_AMBIENT_spotShape.decayRate 0;
	setAttr "SKY_AMBIENT_spot.visibility" 1;

//transforms
		setAttr "SKY_AMBIENT_spot.translateX" -38.677;
		setAttr "SKY_AMBIENT_spot.translateY" 48.418;
		setAttr "SKY_AMBIENT_spot.translateZ" 103.722;
		setAttr "SKY_AMBIENT_spot.rotateX" -25.2;
		setAttr "SKY_AMBIENT_spot.rotateY" -35.2;
		setAttr "SKY_AMBIENT_spot.rotateZ" 0;


///////////////////////////////////////////SUN_DIRECT_spot////////////////////////////////////
	setAttr "SUN_DIRECT_spotShape.colorR" 1;
	setAttr "SUN_DIRECT_spotShape.colorG" 0.81085;
	setAttr "SUN_DIRECT_spotShape.colorB" 0.612;
	setAttr "SUN_DIRECT_spotShape.intensity" 1;

//shadows
	setAttr "SUN_DIRECT_spotShape.useRayTraceShadows" 1;
	setAttr "SUN_DIRECT_spotShape.lightRadius" 20;
	setAttr "SUN_DIRECT_spotShape.shadowRays" 40;
	setAttr "SUN_DIRECT_spotShape.rayDepthLimit" 2;


	setAttr "SUN_DIRECT_spotShape.shadColorR" 0;
	setAttr "SUN_DIRECT_spotShape.shadColorG" 0;
	setAttr "SUN_DIRECT_spotShape.shadColorB" 0;
	setAttr "SUN_DIRECT_spotShape.coneAngle" 30;
	setAttr "SUN_DIRECT_spotShape.penumbraAngle" 2;
	setAttr "SUN_DIRECT_spotShape.dropoff" 1;
	setAttr "SUN_DIRECT_spotShape.emitDiffuse" 1;
	setAttr "SUN_DIRECT_spotShape.emitSpecular" 1;
	setAttr SUN_DIRECT_spotShape.decayRate 0;
	setAttr "SUN_DIRECT_spot.visibility" 1;

//transforms
		setAttr "SUN_DIRECT_spot.translateX" 83.759;
		setAttr "SUN_DIRECT_spot.translateY" 71.345;
		setAttr "SUN_DIRECT_spot.translateZ" 115.394;
		setAttr "SUN_DIRECT_spot.rotateX" -30.2;
		setAttr "SUN_DIRECT_spot.rotateY" -322.8;
		setAttr "SUN_DIRECT_spot.rotateZ" 0;





///////////////////////////////////SUN_SHADOW_spot//////////////////////////////////
		setAttr "SUN_SHADOW_spotShape.colorR" 1;
		setAttr "SUN_SHADOW_spotShape.colorG" 1;
		setAttr "SUN_SHADOW_spotShape.colorB" 1;
		setAttr "SUN_SHADOW_spotShape.intensity" 1;
		setAttr "SUN_SHADOW_spotShape.useRayTraceShadows" 1;
		
//shadows
		setAttr "SUN_SHADOW_spotShape.shadColorR" -10;
		setAttr "SUN_SHADOW_spotShape.shadColorG" -10;
		setAttr "SUN_SHADOW_spotShape.shadColorB" -10;
		
		setAttr "SUN_SHADOW_spotShape.coneAngle" 30;
		setAttr "SUN_SHADOW_spotShape.penumbraAngle" 2;
		setAttr "SUN_SHADOW_spotShape.dropoff" 1;
		setAttr "SUN_SHADOW_spotShape.emitDiffuse" 0;
		setAttr "SUN_SHADOW_spotShape.emitSpecular" 0;
		setAttr SUN_SHADOW_spotShape.decayRate 0;
		setAttr "SUN_SHADOW_spot.visibility" 0;



//////////////////////////////////SUN_SHADOW_spot_guide//////////////////////////
string $guide[] = `ls -type "mesh" ("*SUN_SHADOW_spot_guide*")`;
  int $sizeGuide = size($guide);
if ($sizeGuide == 1)
	{

	setAttr "SUN_SHADOW_spot_guide.translateX" -32.061;
	setAttr "SUN_SHADOW_spot_guide.translateY" 24.176;
	setAttr "SUN_SHADOW_spot_guide.translateZ" 56.438;
	
	setAttr "SUN_SHADOW_spot_guide.rotateX" 68.8;
	setAttr "SUN_SHADOW_spot_guide.rotateY" -389.6;
	setAttr "SUN_SHADOW_spot_guide.rotateZ" 0;
	
	setAttr "SUN_SHADOW_spot_guide.scaleX" 1;
	setAttr "SUN_SHADOW_spot_guide.scaleY" 34.81;
	setAttr "SUN_SHADOW_spot_guide.scaleZ" 1;
	setAttr "SUN_SHADOW_spot_guide.visibility" 0;
	}


////////////////////////////////SUN_SUBTRACT_spot////////////////////////////////
	setAttr "SUN_SUBTRACT_spotShape.colorR" 1;
	setAttr "SUN_SUBTRACT_spotShape.colorG" 0.888;
	setAttr "SUN_SUBTRACT_spotShape.colorB" 0.781;

	setAttr "SUN_SUBTRACT_spotShape.intensity" -0.35;
	setAttr "SUN_SUBTRACT_spotShape.useRayTraceShadows" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorR" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorG" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorB" 0;
	
	setAttr "SUN_SUBTRACT_spotShape.useDepthMapShadows" 0;
	setAttr "SUN_SUBTRACT_spotShape.dmapBias" 0.001;
	setAttr "SUN_SUBTRACT_spotShape.coneAngle" 30;
	
	setAttr "SUN_SUBTRACT_spotShape.penumbraAngle" 5;
	setAttr "SUN_SUBTRACT_spotShape.dropoff" 2;
	setAttr "SUN_SUBTRACT_spotShape.emitDiffuse" 1;
	setAttr "SUN_SUBTRACT_spotShape.emitSpecular" 0;
	setAttr SUN_SUBTRACT_spotShape.decayRate 0;
	setAttr "SUN_SUBTRACT_spot.visibility" 0;



/////////////////////////////////RIM_LIGHT_directional//////////////////////////////
		setAttr "RIM_LIGHT_directionalShape.colorR" 1;
		setAttr "RIM_LIGHT_directionalShape.colorG" 0.86987 ;
		setAttr "RIM_LIGHT_directionalShape.colorB" 0.714;

		setAttr "RIM_LIGHT_directionalShape.useRayTraceShadows" 1;
		setAttr "RIM_LIGHT_directionalShape.shadColorR" 0;
		setAttr "RIM_LIGHT_directionalShape.shadColorG" 0;
		setAttr "RIM_LIGHT_directionalShape.shadColorB" 0;

	setAttr "RIM_LIGHT_directionalShape.rimIntensity" 1.2;
	setAttr "RIM_LIGHT_directionalShape.start" 0;
	setAttr "RIM_LIGHT_directionalShape.end" 1;
	setAttr "RIM_LIGHT_directionalShape.emitDiffuse" 1;
	setAttr "RIM_LIGHT_directionalShape.emitSpecular" 1;
	setAttr "RIM_LIGHT_directional.visibility" 1;

		setAttr "RIM_LIGHT_directionalShape.lightAngle" 8;
		setAttr "RIM_LIGHT_directionalShape.shadowRays" 45;
		setAttr "RIM_LIGHT_directionalShape.rayDepthLimit" 1;

//transforms
		setAttr "RIM_LIGHT_directional.translateX" 20.252;
		setAttr "RIM_LIGHT_directional.translateY" 19.239;
		setAttr "RIM_LIGHT_directional.translateZ" 26.093;
		
		setAttr "RIM_LIGHT_directional.rotateX" -25.875;
		setAttr "RIM_LIGHT_directional.rotateY" 201.561;
		setAttr "RIM_LIGHT_directional.rotateZ" -90.083;

//RIM_LIGHT2_directional
setAttr "RIM_LIGHT2_directional.visibility" 0;
}