global proc JH_nightMid()
	{

///////////////////////////////////////////////////////////////////////////////
//Lightrig_nightMid

////////////////////////////////////////////////BOUNCE_FLOOR_spot////////////////////////////
	setAttr "BOUNCE_FLOOR_spotShape.colorR" 0.166141;
	setAttr "BOUNCE_FLOOR_spotShape.colorG"  0.207119;
	setAttr "BOUNCE_FLOOR_spotShape.colorB" 0.337;
	setAttr "BOUNCE_FLOOR_spotShape.intensity" 0.2;
	setAttr "BOUNCE_FLOOR_spotShape.coneAngle" 60;
	setAttr "BOUNCE_FLOOR_spotShape.penumbraAngle" 5;
	setAttr "BOUNCE_FLOOR_spotShape.dropoff" 0;
	setAttr "BOUNCE_FLOOR_spotShape.emitDiffuse" 1;
	setAttr "BOUNCE_FLOOR_spotShape.emitSpecular" 0;
	setAttr BOUNCE_FLOOR_spotShape.decayRate 0;
	setAttr "BOUNCE_FLOOR_spot.visibility" 1;
//transforms
		setAttr "BOUNCE_FLOOR_spot.translateX" 117.545;
		setAttr "BOUNCE_FLOOR_spot.translateY" -65.229;
		setAttr "BOUNCE_FLOOR_spot.translateZ" 55.718;
		setAttr "BOUNCE_FLOOR_spot.rotateX" 31.8;
		setAttr "BOUNCE_FLOOR_spot.rotateY" 67.2;
		setAttr "BOUNCE_FLOOR_spot.rotateZ" 0;



////////////////////////////////////////////SKY_AMBIENT_spot///////////////////////////////////
	setAttr "SKY_AMBIENT_spotShape.colorR"  0.245265;
	setAttr "SKY_AMBIENT_spotShape.colorG" 0.337173;
	setAttr "SKY_AMBIENT_spotShape.colorB" 0.591  ;
	setAttr "SKY_AMBIENT_spotShape.intensity" 0.3;
	setAttr "SKY_AMBIENT_spotShape.coneAngle" 40;
	setAttr "SKY_AMBIENT_spotShape.penumbraAngle" 0;
	setAttr "SKY_AMBIENT_spotShape.dropoff" 0;
	setAttr "SKY_AMBIENT_spotShape.emitDiffuse" 1;
	setAttr "SKY_AMBIENT_spotShape.emitSpecular" 0;
	setAttr SKY_AMBIENT_spotShape.decayRate 0;
	setAttr "SKY_AMBIENT_spot.visibility" 1;

//transforms
		setAttr "SKY_AMBIENT_spot.translateX" -33.245;
		setAttr "SKY_AMBIENT_spot.translateY" 51.709;
		setAttr "SKY_AMBIENT_spot.translateZ" 106.032;
		setAttr "SKY_AMBIENT_spot.rotateX" -28.2;
		setAttr "SKY_AMBIENT_spot.rotateY" -21.2;
		setAttr "SKY_AMBIENT_spot.rotateZ" 0;



///////////////////////////////////////////SUN_DIRECT_spot////////////////////////////////////
	setAttr "SUN_DIRECT_spotShape.colorR" 0.11457;
	setAttr "SUN_DIRECT_spotShape.colorG" 0.333502 ;
	setAttr "SUN_DIRECT_spotShape.colorB" 0.67;
	setAttr "SUN_DIRECT_spotShape.intensity" 1;

//shadows
	setAttr "SUN_DIRECT_spotShape.useRayTraceShadows" 1;
	setAttr "SUN_DIRECT_spotShape.lightRadius" 8;
	setAttr "SUN_DIRECT_spotShape.shadowRays" 40;
	setAttr "SUN_DIRECT_spotShape.rayDepthLimit" 2;



	setAttr "SUN_DIRECT_spotShape.shadColorR" 0.0539;
	setAttr "SUN_DIRECT_spotShape.shadColorG" 0.0970217;
	setAttr "SUN_DIRECT_spotShape.shadColorB" 0.14;
	setAttr "SUN_DIRECT_spotShape.coneAngle" 30;
	setAttr "SUN_DIRECT_spotShape.penumbraAngle" 2;
	setAttr "SUN_DIRECT_spotShape.dropoff" 1;
	setAttr "SUN_DIRECT_spotShape.emitDiffuse" 1;
	setAttr "SUN_DIRECT_spotShape.emitSpecular" 1;
	setAttr SUN_DIRECT_spotShape.decayRate 0;
	setAttr "SUN_DIRECT_spot.visibility" 1;

//transforms
		setAttr "SUN_DIRECT_spot.translateX" 83.759;
		setAttr "SUN_DIRECT_spot.translateY" 71.345;
		setAttr "SUN_DIRECT_spot.translateZ" 115.394;
		setAttr "SUN_DIRECT_spot.rotateX" -30.2;
		setAttr "SUN_DIRECT_spot.rotateY" -322.8;
		setAttr "SUN_DIRECT_spot.rotateZ" 0;




///////////////////////////////////SUN_SHADOW_spot//////////////////////////////////
		setAttr "SUN_SHADOW_spotShape.colorR" 1;
		setAttr "SUN_SHADOW_spotShape.colorG" 1;
		setAttr "SUN_SHADOW_spotShape.colorB" 1;
		setAttr "SUN_SHADOW_spotShape.intensity" 1;
		setAttr "SUN_SHADOW_spotShape.useRayTraceShadows" 1;
		
//shadows
		setAttr "SUN_SHADOW_spotShape.shadColorR" -10;
		setAttr "SUN_SHADOW_spotShape.shadColorG" -10;
		setAttr "SUN_SHADOW_spotShape.shadColorB" -10;
		
		setAttr "SUN_SHADOW_spotShape.coneAngle" 30;
		setAttr "SUN_SHADOW_spotShape.penumbraAngle" 2;
		setAttr "SUN_SHADOW_spotShape.dropoff" 1;
		setAttr "SUN_SHADOW_spotShape.emitDiffuse" 0;
		setAttr "SUN_SHADOW_spotShape.emitSpecular" 0;
		setAttr SUN_SHADOW_spotShape.decayRate 0;
		setAttr "SUN_SHADOW_spot.visibility" 0;



//////////////////////////////////SUN_SHADOW_spot_guide//////////////////////////
string $guide[] = `ls -type "mesh" ("*SUN_SHADOW_spot_guide*")`;
  int $sizeGuide = size($guide);
if ($sizeGuide == 1)
	{

	setAttr "SUN_SHADOW_spot_guide.translateX" -32.061;
	setAttr "SUN_SHADOW_spot_guide.translateY" 24.176;
	setAttr "SUN_SHADOW_spot_guide.translateZ" 56.438;
	
	setAttr "SUN_SHADOW_spot_guide.rotateX" 68.8;
	setAttr "SUN_SHADOW_spot_guide.rotateY" -389.6;
	setAttr "SUN_SHADOW_spot_guide.rotateZ" 0;
	
	setAttr "SUN_SHADOW_spot_guide.scaleX" 1;
	setAttr "SUN_SHADOW_spot_guide.scaleY" 34.81;
	setAttr "SUN_SHADOW_spot_guide.scaleZ" 1;
	setAttr "SUN_SHADOW_spot_guide.visibility" 0;
	}


////////////////////////////////SUN_SUBTRACT_spot////////////////////////////////
	setAttr "SUN_SUBTRACT_spotShape.colorR" 1;
	setAttr "SUN_SUBTRACT_spotShape.colorG" 0.888;
	setAttr "SUN_SUBTRACT_spotShape.colorB" 0.781;

	setAttr "SUN_SUBTRACT_spotShape.intensity" -0.35;
	setAttr "SUN_SUBTRACT_spotShape.useRayTraceShadows" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorR" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorG" 0;
	setAttr "SUN_SUBTRACT_spotShape.shadColorB" 0;
	
	setAttr "SUN_SUBTRACT_spotShape.useDepthMapShadows" 0;
	setAttr "SUN_SUBTRACT_spotShape.dmapBias" 0.001;
	setAttr "SUN_SUBTRACT_spotShape.coneAngle" 30;
	
	setAttr "SUN_SUBTRACT_spotShape.penumbraAngle" 5;
	setAttr "SUN_SUBTRACT_spotShape.dropoff" 2;
	setAttr "SUN_SUBTRACT_spotShape.emitDiffuse" 1;
	setAttr "SUN_SUBTRACT_spotShape.emitSpecular" 0;
	setAttr SUN_SUBTRACT_spotShape.decayRate 0;
	setAttr "SUN_SUBTRACT_spot.visibility" 1;



/////////////////////////////////RIM_LIGHT_directional//////////////////////////////
		setAttr "RIM_LIGHT_directionalShape.colorR" 0.32494 ;
		setAttr "RIM_LIGHT_directionalShape.colorG" 0.584903 ;
		setAttr "RIM_LIGHT_directionalShape.colorB" 0.844;

		setAttr "RIM_LIGHT_directionalShape.useRayTraceShadows" 1;
		setAttr "RIM_LIGHT_directionalShape.shadColorR" 0;
		setAttr "RIM_LIGHT_directionalShape.shadColorG" 0;
		setAttr "RIM_LIGHT_directionalShape.shadColorB" 0;

	setAttr "RIM_LIGHT_directionalShape.rimIntensity" 1.2;
	setAttr "RIM_LIGHT_directionalShape.start" 0;
	setAttr "RIM_LIGHT_directionalShape.end" 1;
	setAttr "RIM_LIGHT_directionalShape.emitDiffuse" 1;
	setAttr "RIM_LIGHT_directionalShape.emitSpecular" 1;
	setAttr "RIM_LIGHT_directional.visibility" 1;

		setAttr "RIM_LIGHT_directionalShape.lightAngle" 0;
		setAttr "RIM_LIGHT_directionalShape.shadowRays" 1;
		setAttr "RIM_LIGHT_directionalShape.rayDepthLimit" 2;

//transforms
		setAttr "RIM_LIGHT_directional.translateX" 17.819;
		setAttr "RIM_LIGHT_directional.translateY" 18.855;
		setAttr "RIM_LIGHT_directional.translateZ" 29.172;

		setAttr "RIM_LIGHT_directional.rotateX" -9.797;
		setAttr "RIM_LIGHT_directional.rotateY" 202.843;
		setAttr "RIM_LIGHT_directional.rotateZ" -0.296;

//RIM_LIGHT2_directional
setAttr "RIM_LIGHT2_directional.visibility" 0;
}