//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-1-7
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-1-14
//	Description:
//				
//////////////////////////////////////////////////////////

global proc llRenderToolsLayout()
{
	//setup mentalray render 
	if (!`pluginInfo -query -loaded "Mayatomr.mll"`) loadPlugin "Mayatomr.mll";
	miCreateDefaultNodes();
	miCreateOtherOptionsNodesForURG();
	setAttr defaultRenderGlobals.currentRenderer -type "string" "mentalRay" ;
	
	string $path = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\icons\\StrawBerry\\Render\\";
	string $newPath = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\projects\\LilLarikkins\\import\\";
	
	if (`window -ex llRenderToolsLayoutUI`)
	{
		deleteUI llRenderToolsLayoutUI;
	}
	
	window -title "LilLarikkins Render Tools                           WHO" -in "LL RT" -menuBar true  -mxb false -s true  -resizeToFitChildren true llRenderToolsLayoutUI;
		menu -label "Help";
			menuItem -label "Help on Render Tools..." -command "";

		string $mainColumnLayout = `columnLayout -adjustableColumn true -rs 10 llRenderToolsLayoutUI_main`;

			string $mainImage = `symbolButton -image ($newPath+"LilLarikkins.bmp") -command ""`;

			// Mini Tools
			string $LittleTools = `frameLayout -label "Little Tools" -labelAlign "top" -cl true  -cll true  -borderStyle "etchedIn" llRenderToolsLayoutUI_test`;
				frameLayout -e -cc ("llRenderToolsLayoutFrameResize "+$LittleTools)  -ec ""  $LittleTools;
				rowColumnLayout	 -numberOfColumns 5 -cw 1 60 -cw 2 60 -cw 3 60 -cw 4 60 -cw 5 60;
					button -h 25 -l "LightSetup"	-c "llRenderLightSetup"			-ann "灯光工具(面板)";
					button -h 25 -l "Refresh"		-c "eyRenderRehyperShade"		-ann "刷新场景材质(重连物体材质)";
					button -h 25 -l "2DBG"		-c "llRenderImageplane"			-ann "给当前视图的相机添加2D背景图(需手动调整大小及位置)";
				setParent ..;
			setParent ..;

			//Material Tools
			string $MaterrialTools = `frameLayout -label "Materrial Tools" -labelAlign "top" -cl true  -cll true  -borderStyle "etchedIn"`;
				frameLayout -e -cc ("llRenderToolsLayoutFrameResize "+$MaterrialTools)   -ec ""  $MaterrialTools;
				rowColumnLayout	 -numberOfRows 1 -rh 1 40;
					symbolButton -ann "ColorB"	-image ($path+"colorB.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorB\")";
					symbolButton -ann "ColorR"	-image ($path+"colorR.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorR\")";
					symbolButton -ann "ColorG"	-image ($path+"colorG.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorG\")";
					symbolButton -ann "ColorA"	-image ($path+"colorA.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorA\")";
					symbolButton -ann "Matte"	-image ($path+"matte.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"matte\")";
					symbolButton -ann "Depth"	-image ($path+"depth.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"depth\")";
					symbolButton -ann "Shadow" -image ($path+"shadow.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"shadow\")";
					symbolButton -ann "AO"		-image ($path+"AO.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"AO\")";
					symbolButton -ann "Lambert" -image ($path+"lambert.xpm")		-command "ezRenderMainLayoutMaterial_Assign(\"lambert\")";
				setParent ..;
			setParent ..;

			// Render Tools
			string $RenderLayerTools = `frameLayout -label "Creat RenderLayer Tools" -labelAlign "top" -cl true -cll true -cc "" -borderStyle "etchedIn"`;
				frameLayout -e -cc ("llRenderToolsLayoutFrameResize "+$RenderLayerTools)  -ec ""  $RenderLayerTools;
				//string $tab = `tabLayout  -cc ""`;
					string $tools = `rowColumnLayout -nc 2 -cw 1 145 -cw 2 145  -cs 2 5`;
						string $b1 = `button -h 30 -l "Color"			-c "llRenderColorLayer"`;
						string $b2 = `button -h 30 -l "Occlusion"		-c "llRenderOccLayer"`;
						string $b3 = `button -h 30 -l "Shadow"		-c "llRenderShadowLayer"`;
						string $b4 = `button -h 30 -l "Line"			-c "llRenderLineLayer"`;
					//setParent ..;
					/*tabLayout -edit 
						-tl	$tools	"单独分层"	
					$tab;*/
				setParent ..;
			setParent ..;
			
			string $camFront	= `button -l "CLOSE"  -w 100 -h 30 -command "deleteUI llRenderToolsLayoutUI"`;
	
	showWindow llRenderToolsLayoutUI;
	window -e -w 340 -h 319 llRenderToolsLayoutUI;

	//Material Tools
	source "ezRenderMainLayoutMaterial.mel";

	if (`objExists defaultRenderGlobals`)
	{
		setAttr defaultRenderGlobals.numCpusToUse 0 ;
	}
}

global proc llRenderToolsLayoutFrameResize(string $layout)
{
	int $original = 0;
	string $children[]  = `frameLayout -q -ca $layout`;
	string $cmd = `objectTypeUI $children[0]` + " -q -h " +$children[0];
	float $height = eval($cmd);

	
	float $winHeight = `window -q -h llRenderToolsLayoutUI`;
	window -e -h ($winHeight-$height) llRenderToolsLayoutUI;

}