//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-1-5
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-1-5
//	Description:
//				
//////////////////////////////////////////////////////////

global proc llRenderLightSetup()
{
	string $helppath = "//file-cluster/GDC/Resource/Support/Maya/projects/LilLarikkins/docs/";
	string $helpfile = "Light Setup工具说明.mht";
	
	if (`window -ex llRenderLightSetupUI`)
		deleteUI llRenderLightSetupUI;
	
	window -title "Light Setup" -mb true llRenderLightSetupUI;
		menu -label "帮助";
			menuItem -label "说明" -c ("llHelpDocs \""+$helppath+$helpfile+"\"");
		columnLayout -adj true;
		button -h 30 -l "Import Light" -c "llRenderLightSetupImport";
		separator -st "double" -h 10;
		rowColumnLayout -nc 3 ;
			button -h 40 -l "Afternoon"		-c "llRenderLightSetupTime \"Afternoon\"";
			button -h 40 -l "dawn"			-c "llRenderLightSetupTime \"dawn\"";
			button -h 40 -l "dawnBackLight"	-c "llRenderLightSetupTime \"dawnBackLight\"";
			button -h 40 -l "earlyMornSun"		-c "llRenderLightSetupTime \"earlyMornSun\"";
			button -h 40 -l "MidMorningSun"	-c "llRenderLightSetupTime \"MidMorningSun\"";
			button -h 40 -l "NightDark"		-c "llRenderLightSetupTime \"NightDark\"";
			button -h 40 -l "nightMid"			-c "llRenderLightSetupTime \"nightMid\"";
			button -h 40 -l "noon"			-c "llRenderLightSetupTime \"noon\"";
			setParent ..;
		setParent ..;
	showWindow;
}

global proc llRenderLightSetupImport()
{
	string $filepath = "//file-cluster/GDC/Resource/Support/Maya/projects/LilLarikkins/import/";
	
	string $lightGroups[] = `ls "LilLarikkins_Lights"`;
	if (size($lightGroups) == 0)
		file -import -type "mayaAscii" -rpr "Lightrig_default" -options "v=0;p=17"  -pr -loadReferenceDepth "all" ($filepath+"Lightrig_default.ma");
	print "Lighting Imported!";
}

global proc llRenderLightSetupTime(string $time)
{
	string $cmd = "JH_"+$time;
	catch(`eval $cmd`);
	print $time;
}

global proc llHelpDocs(string $file)
{
	if (!`filetest -f $file`)
		return ;

	$file = substituteAllString($file, "/", "\\");
	system ("load " + $file);
}