
global proc HhP5ProxyToolsUI()
{
	source "//file-cluster/GDC/Resource/Support/Maya/projects/HolyP5/HHP5ModLibrary.mel";
	source "//file-cluster/GDC/Resource/Support/Maya/projects/HolyP5/HhColorScatterTools.mel";
	source zwSelectInstance.mel;
	separator -style "none" -height 6 HhP5ProxyToolsHeader;

	frameLayout -l "渲染代理创建工具"  -collapsable true -cl 1 -width 420 HhP5ProxyFL;
		columnLayout -adjustableColumn true ;
				scrollField -wordWrap true -h 60 -bgc 1 1 0
					-text "1、打开模型库中文件，按要求创建高低模（注意需要在高模路径中，注意文件及模型正确命名）；\n2、按需要点击不同渲染器按钮，创建相应渲染代理";
				button  -label "渲染代理创建工具" -h 40   -command "python\"execfile('//file-cluster/GDC/Resource/Support/Maya/projects/HolyP5/HhRenderProxyToolsUI.py')\"";
		setParent ..;
		setParent ..;
	separator -style "single";

	frameLayout   -label "渲染代理库"    -collapsable true -cl 1  -width 420  HhP5ProxyLiberyFL ;
			columnLayout  -adjustableColumn true  ;
				scrollField -wordWrap true -h 30 -bgc 1 1 0
					   -tx  "注意:正确选择不同渲染器的渲染代理";
				button -label "渲染代理库" -h 40   -command "HHP5ModLibrary();";

		setParent ..;
		setParent ..;
		separator -style "single";

		


	// Initialization
}
