global proc XY_HhFbxExr()
{
	string $obj[]=`ls -sl`;
	source "//file-cluster/GDC/Resource/Support/Maya/projects/Sk3/HhRenderTools.mel";
	source zwCopyTextureImage.mel;
	string $shortname=`file -q -sn -shn`;
	string $fbxname=`match "[^.]+" $shortname`+".fbx";
	string $shortP=`match "[^_]+" $shortname`;
	string $path="L:/Projects/DomesticProject/XingYungu/XingYungu_Scratch/TD/Unity/Assets/";
	string $buff[];
	tokenize $shortname "_" $buff;
	string $source;
	if($shortP=="xy")
	{
		if(`match "an" $shortname`!="")
		{
			$source=$buff[1]+"_"+$buff[2]+"_an";
			string $filepath=$path+$source;
		}
		else
		{
			$source=$buff[1]; 
		}
		string $filepath=$path+$source;
		if(`filetest -d $filepath`==0)
		{

			sysFile  -md $filepath;
			sysFile  -md ($filepath+"/Textures");
		}
		string $fd=$path+$source+"/"+$fbxname;
		zwCopyTextureImage(3, {"file", "fileTextureName", ($filepath+"/Textures"), "1", 0, "1", 100, "XingYungu", "1", "0"});
		file -force -options "v=0" -typ "FBX export" -pr -es $fd;

	}
	else
	{
		error "请正确命名星云谷项目文件名称";

	}
}

global proc XY_HhFbxExrLocal()
{
	string $obj[]=`ls -sl`;
	source "//file-cluster/GDC/Resource/Support/Maya/projects/Sk3/HhRenderTools.mel";
	source zwCopyTextureImage.mel;
	string $shortname=`file -q -sn -shn`;
	string $fbxname=`match "[^.]+" $shortname`+".fbx";
	string $shortP=`match "[^_]+" $shortname`;
	string $path="D:/Unity/Assets/";
	string $buff[];
	tokenize $shortname "_" $buff;
	string $source;
	if($shortP=="xy")
	{
		if(`match "an" $shortname`!="")
		{
			$source=$buff[1]+"_"+$buff[2]+"_an";
		}
		else
		{
			$source=$buff[1]; 
		}
		string $filepath=$path+$source;
		if(`filetest -d $filepath`==0)
		{

			sysFile  -md $filepath;
			sysFile  -md ($filepath+"/Textures");
		}
		string $fd=$path+$source+"/"+$fbxname;
		zwCopyTextureImage(3, {"file", "fileTextureName", ($filepath+"/Textures"), "1", 0, "1", 100, "XingYungu", "1", "0"});
		file -force -options "v=0" -typ "FBX export" -pr -es $fd;

	}
	else
	{
		error "请正确命名星云谷项目文件名称";

	}
}