global proc nj_Ani_UtilityTools_Hide_Deforms()
{
	global int $nj_Ani_UtilityTools_Hide_Deforms;
	string $deforms[]=`ls "head_ctrl" "*:head_ctrl" "*:*:head_ctrl"`;
	if ($nj_Ani_UtilityTools_Hide_Deforms==0)
	{
		for ($d in $deforms)  setAttr ($d+".facialCtrlPlane_vis") 0;
		$nj_Ani_UtilityTools_Hide_Deforms=1;
	}

	else if ($nj_Ani_UtilityTools_Hide_Deforms==1)
	{
		for ($d in $deforms)  setAttr ($d+".facialCtrlPlane_vis") 1;
		$nj_Ani_UtilityTools_Hide_Deforms=0;
	}
}


global proc nj_Ani_Exchange_To_A_Model()
{
	string $sl[]=`ls -sl `;
	for ($s in $sl)
	{
		$s="'"+$s+"'";
		string $xxx[]=python($s+".split(':')");
		int $size =`size $xxx`-1;
		string $Master="";
		for ($i=0;$i<$size;$i++)
		{
			$Master+=$xxx[$i];
			$Master+=":";
		}
		$Master+="Master";
		if (`attributeExists "AMOD" $Master` )
		{
			int $mod =1- `getAttr ($Master+".AMOD")`;
			setAttr ($Master+".AMOD") $mod;
		}
	}

}
