//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc njAnimGetAssetReference()
{
	string $sceneName = `file -q -sn -shn`;


	//获取镜头的asset连接的前期文件
	string $asset = `idmtService "GetAssetNameInAnim" ($sceneName+"|")`;
	string $buff[]={};
	int $num = `tokenize $asset "|" $buff`;
	string $newfile[]={};
	string $addfile[] = {};
	for($i=1;$i<$num;)
	{
	    if (endsWith($buff[$i],"Tornado"))
	    {
		$addfile[size($addfile)] = $buff[$i];
	    }
	    else
	    {
		$newfile[size($newfile)] = $buff[$i];
	    }
	    $i=$i+2;
	}

	string $refFiles[]=  `file -q -r`;
	for ($file in $refFiles)
	{
		if (match("Tornado",$file) == "")
		{
			string $refnode = `referenceQuery -rfn $file`;
			
			clear $buff;
			$num = `tokenize $file "\\/" $buff`;
			for ($nfile in $newfile)
			{
				string $code = `substring $nfile 1 10`;
				//print $code;
				if (match($code,$buff[$num-1]) == $code && match($nfile,$buff[$num-1]) != $nfile)
				{
					string $buff1[] = stringToStringArray($buff[$num-1],"_");
					$nfile = `substituteAllString $buff[$num-1] $buff1[1] $nfile`;
					clear $buff1;
					$buff1=stringToStringArray($nfile,"{}");
					$nfile=$buff1[0];
					
					string $newpath = `idmtService "GetAssetPath" $nfile`;
					//print ($newpath+"\n");
					//print ($nfile+"\n");
					if (`filetest -r $newpath`)
					{
						file -lr $refnode $newpath;
					}
					break;
				}
			}
		}
		else
		{
			//print $file;
			string $refnode = `referenceQuery -rfn $file`;
			
			clear $buff;
			$num = `tokenize $file "\\/" $buff`;
			for ($nfile in $addfile)
			{
				string $code = `substring $nfile 1 10`;
				if (match($code,$buff[$num-1]) == $code && match($nfile,$buff[$num-1]) == $nfile)
				{
					//print $nfile;
					$addfile = stringArrayRemove({$nfile},$addfile);
					break;
				}
			}
		}
	}

	print $addfile;
	if (size($addfile))
	{
		for ($afile in $addfile)
		{
			string $newpath = `idmtService "GetAssetPath" ("nj_"+$afile+"_h_ms_anim.ma")`;
			if (`filetest -r $newpath`)
			{
				slImportRef $newpath "mayaAscii";
			}
		}
	}
}