//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2011-3-9
//
//	Update/Change: WansHoulOng
//	Last Updated: 2011-3-9
//	Description:
//				
//////////////////////////////////////////////////////////
python("execfile('//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/edo_lockAndUnlockTransform.py')");

global proc njAnimCpoyAnimationWithControls()
{
      source "//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/edo_setAnimCurveRotationInterpolationToNone.mel";
    edo_setAnimCurveRotationInterpolationToNone();
	string $sel[] = `ls -sl`;
	if (size($sel) != 2)
	{
		error "请先选择导出角色，再选择导入的角色!";
	}
	string $buff[] = stringToStringArray($sel[0],":");
	string $old="";
	if (size($buff)==1)
	{
		clear $buff;
		$buff = stringToStringArray($sel[0],"_");
		$old = $buff[0]+"_";
	}
	else 
	{
		$old = `substituteAllString $sel[0] $buff[size($buff)-1] ""`;
	}
	clear $buff;
	$buff = stringToStringArray($sel[1],":");
	string $new = `substituteAllString $sel[1] $buff[size($buff)-1] ""`;

	
	slAnimExportImportForSetMainLayout;
	radioButtonGrp -e -select 3 window_slAnimCopyAnimation_ct;
	slAnimCopyAnimations;

	//
	if (objExists($old+"Chest_Ctrl") && attributeExists("leftArm",($old+"Chest_Ctrl")) && objExists($new+"LfArm_Switch"))
	{
		
		if (getAttr($old+"Chest_Ctrl.leftArm")==10)
		{
			setAttr ($new+"LfArm_Switch.IKFK")  1;
		}
		else if (getAttr($old+"Chest_Ctrl.leftArm")==0)
		{
			setAttr ($new+"LfArm_Switch.IKFK")  0;
		}
		
		if (getAttr($old+"Chest_Ctrl.rightArm")==10)
		{
			setAttr ($new+"RtArm_Switch.IKFK")  1;
		}
		else if (getAttr($old+"Chest_Ctrl.rightArm")==0)
		{
			setAttr ($new+"RtArm_Switch.IKFK")  0;
		}
		
	}
	if (objExists($old+"Pelvis_Ctrl") && attributeExists("leftLeg",($old+"Pelvis_Ctrl")) && objExists($new+"LfLeg_Switch"))
	{
		
		if (getAttr($old+"Pelvis_Ctrl.leftLeg")==10)
		{
			setAttr ($new+"LfLeg_Switch.IKFK")  1;
		}
		else if (getAttr($old+"Pelvis_Ctrl.leftLeg")==0)
		{
			setAttr ($new+"LfLeg_Switch.IKFK")  0;
		}
		
		if (getAttr($old+"Pelvis_Ctrl.rightLeg")==10)
		{
			setAttr ($new+"RtLeg_Switch.IKFK")  1;
		}
		else if (getAttr($old+"Pelvis_Ctrl.rightLeg")==0)
		{
			setAttr ($new+"RtLeg_Switch.IKFK")  0;
		}
		
	}


	string $confile = "//file-cluster/GDC/Resource/Support/Maya/projects/Ninjago/controls.txt";
	$fileId = `fopen $confile "r"`;
	string $content = `fgetline $fileId`;
	while (size($content) > 0 )
	{
		clear $buff;
		int $num = `tokenize $content "\t \n" $buff`;
		string $oldCon = $old+$buff[0];
		string $newCon = $new+$buff[1];
		string $list[] = `ls  ($old+"*"+$buff[0])`;
		for ($item in $list)
		{
			if (endsWith($item,$oldCon))
			{
				string $ac[] = `listConnections -type animCurve -s 1 -d 0 $item`;
				if (size($ac))
				{
					$oldCon = $item;
				}
			}
		}
		if (`objExists $oldCon` && `objExists $newCon`)
		{
			  select -r $oldCon;select -add $newCon;
			  slAnimCopyAnimations;
			  //added by Edward.Sun on 25th September
			  //$oldCon="aaa";
			  //$newCon="bbb";
			  //string $cmd=("edo_AnimCopyAnimations('"+$oldCon+"','"+$newCon+"','slAnimCopyAnimations()')");
			  //python($cmd);
			  //=====================================
		}
		$content = `fgetline $fileId`;
	}
	fclose $fileId;
	deleteUI window_slAnimExportImport;
};