//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2011-1-11
//
//	Update/Change: WansHoulOng
//	Last Updated: 2011-1-11
//	Description:
//				
//////////////////////////////////////////////////////////

global proc njAnimReplaceMbToMa()
{
	string $referenceFiles[] = `file -q -r`;
	for ($rf in $referenceFiles)
	{
		string $referenceNode = `referenceQuery -rfn $rf`;
		string $buff[] = stringToStringArray($rf,"{}");
		if (endsWith($buff[0],".ma"))
		{
			string $newFile = `substituteAllString $buff[0] ".ma" ".mb"`;
			if (`filetest -r $newFile`)
			{
				//print $newFile;
				file -lr $referenceNode $newFile;
			}
		}
	}
}

global proc njAnimRepairReference()
{
	string $confirm = `confirmDialog -title "Confirm" -message ""
				    -button "2.5分钟" -button "新集" -button "取消" -defaultButton "取消"
				    -cancelButton "取消" -dismissString "取消"`;
	
	
	if ($confirm == "新集")
	{
		string $referenceFiles[] = `file -q -r`;
		for ($rf in $referenceFiles)
		{
			string $referenceNode = `referenceQuery -rfn $rf`;
			string $buff[] = stringToStringArray($rf,"{}");

			string $newFile = `idmtService "GetAssetPath" $buff[0]`;
			if (match("c006001Loyd",$buff[0]) == "c006001Loyd")
			{
				string $newChar = `substituteAllString $buff[0] "c006001Loyd" "c006001Lloyd"`;
				$newFile = `idmtService "GetAssetPath" $newChar`;
			}
			if (substituteAllString($buff[0],"/","\\") != $newFile)
			{
				if (`filetest -r $newFile`)
				{
					file -lr $referenceNode $newFile;
				}
			}
		}
	}
}
