//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc njAnimRemoveRef()
{
	string $sl[] = `ls -sl`;
	for ($item in $sl)
	{
		if (`referenceQuery -inr $item`)
		{
			string $refFile = `referenceQuery -f  $item`;
			//string $refNode = `referenceQuery -rfn $item`;
			file -rr $refFile;
		}
	}
}