
global proc s100combineAllDescendanteShape()
{


$sel = `ls -sl`;
	for($selT in $sel)
	{

	$var = `listRelatives -ad   $selT `;


		for($tmp in $var)
		{
		$type = `nodeType $tmp `;

			if($type == "transform")
			{
			$list = `listConnections -s 1 -d 0 $tmp  ` ;
				if(size($list ) > 0 )

					delete $list;
            }
		makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 $tmp;

        }

		for($tmp in $var)
		{
		$type = `nodeType $tmp `;

			if($type == "nurbsCurve")
				parent -s -r  $tmp  $selT ;

		}


	$var = `listRelatives -ad -type "transform"   $selT `;
		if(size($var) >0)
			delete $var ;

    }


select $sel ;

}


global proc s100combineAllDescendanteShapeUI()
{
string $window = `window -title "Long Name"
       -iconName "Short Name"
       -widthHeight 200 55`;
columnLayout -adjustableColumn true;
text -label "select the top group with the shape to combine";
       button -c s100combineAllDescendanteShape -label "combine All Descendente Shape";
setParent ..;

window -e  -resizeToFitChildren 1  $window ;
showWindow $window;


}