global proc s100FileManagerRemShotFolderUI()
{

string $folders[] ;
$folders = ` s100FileManagerGetShotFolder `;
string $prod  = `optionMenu -q -v s100FileManagerUIOMProd`;
string $ep  = `optionMenu -q -v s100FileManagerUIOMEpisode`;
string $sq  = `optionMenu -q -v s100FileManagerUIOMSequence`;
string $dept  = `optionMenu -q -v s100FileManagerUIOMDepartement`;
string $arrTmp[]  = `textScrollList -q -si  s100FileManagerUITSShoot` ;
string $shoot = $arrTmp[0];


if (size($arrTmp) > 0 )
{
if(`window -ex 	s100FileManagerRemShotFolderUI`)
	deleteUI s100FileManagerRemShotFolderUI;


int $heigh = 350 ;
int $width = 170;
window -title "s100 Rem Shoot"   s100FileManagerRemShotFolderUI;
formLayout  s100ProdManagerAddEPUIFLMain;


$textName = `text -label "Shoot : "` ;
$textProd = `text -l "Prod :"`;
$textEp  = `text -l "Episode :"`;
$textSq  = `text -l "Sequence :"`;
$textDept = `text -l "Department :"`;

$textFieldProd = `textField -ed 0 -tx $prod -w  155 s100FileManagerRemShotFolderUITFNameProd  `;
$textFieldEp = `textField -ed 0 -tx $ep -w  155 s100FileManagerRemShotFolderUITFNameEp  `;
$textFieldSq = `textField -ed 0 -tx $sq -w  155 s100FileManagerRemShotFolderUITFNameSq  `;
$textFieldDept = `textField -ed 0 -tx $dept -w  155 s100FileManagerRemShotFolderUITFNameDept  `;
$textFieldNamePref = `textField -ed 0 -tx $shoot -w  155 s100FileManagerRemShotFolderUITFNamePref  `;



$separator = `separator -w 155`;


$butCrea = `button -w 155 -c s100ASConfirmUIPasswordRemSh -label "remove Shoot" -w ($width *.8)` ;

$side = 5 ;

formLayout -e


	-attachForm   $textProd "top" 5
	-attachForm $textProd "left" 5

	-attachControl   $textFieldProd "top" 5 $textProd
	-attachForm $textFieldProd "left" 5


	-attachControl   $textEp "top" 5 $textFieldProd
	-attachForm $textEp "left" 5

	-attachControl   $textFieldEp "top" 5 $textEp
	-attachForm $textFieldEp "left" 5


	-attachControl   $textSq "top" 5 $textFieldEp
	-attachForm $textSq "left" 5

	-attachControl   $textFieldSq "top" 5 $textSq
	-attachForm $textFieldSq "left" 5

	-attachControl   $textDept "top" 5 $textFieldSq
	-attachForm $textDept "left" 5

	-attachControl   $textFieldDept "top" 5 $textDept
	-attachForm $textFieldDept "left" 5


//

	-attachControl   $textName "top" 5 $textFieldDept
	-attachForm $textName "left" 5

	-attachControl   $textFieldNamePref "top" 5 $textName
	-attachForm $textFieldNamePref "left" 5

	-attachControl   $separator "top" 5  $textFieldNamePref

	-attachControl   $butCrea "top" 5 $separator


s100ProdManagerAddEPUIFLMain ;

window -e -h $heigh  -w $width  -sizeable 0  s100FileManagerRemShotFolderUI;
	showWindow;


}else{
	warning "select a shoot" ;
}



}

global proc s100ASConfirmUIPasswordRemSh()
{
if(`window -ex 	s100ASConfirmUIPassword`)
	deleteUI s100ASConfirmUIPassword;


window -title "Password protection AS"   s100ASConfirmUIPassword;
columnLayout -adj 1 ;
text -l "Password protection";
text -l "ask to your lead";
separator -h 20 ;

text -al "center"  -l  "put the password" ;

textField s100ASConfirmUIPasswordTFPassword ;
button -c s100ASConfirmPasswordReturnRemSh -l "OK" ;

window -e -resizeToFitChildren 1 s100ASConfirmUIPassword ;
showWindow s100ASConfirmUIPassword ;


}

global proc string s100ASConfirmPasswordReturnRemSh()
{
$return = `textField -q -tx s100ASConfirmUIPasswordTFPassword `;
$pass = ` s100FileManagerGetPassword `;
	if ($return != "")
	{
		if ($return == $pass)
		{
		s100FileManagerRemShotFolder ;
		deleteUI s100ASConfirmUIPassword;
		deleteUI s100FileManagerRemShotFolderUI;

        }else{

		warning "password is not good" ;
        }
    }else{
	warning "password is empty" ;
    }


	return $return ;

}




global proc s100FileManagerRemShotFolder()
{

$numb = `textField -q -tx s100FileManagerRemShotFolderUITFNamePref  `;
string $prod  =  `textField -q -tx s100FileManagerRemShotFolderUITFNameProd  `;
string $ep  =  `textField -q -tx s100FileManagerRemShotFolderUITFNameEp  `;
string $sq  = `textField -q -tx s100FileManagerRemShotFolderUITFNameSq  `;
string $dept  = `textField -q -tx s100FileManagerRemShotFolderUITFNameDept  `;

$folder = sort( `s100assetManagerGetDeptTemp($prod)` );


$path =s100assetManagerGetEpPath($prod);
$path += $ep + "/";


	for ($tmp in $folder)
	{
	$npath = $path + $tmp + "/" + $sq + "/" + $numb +"" ;
	$sub = substituteAllString($npath , "/" , "\\") ;
	system("RD " + $sub + "/S /Q" )     ;
    }


s100FileManagerRefreshUIChangeDept ;




}

