//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WanShouLong
//	Created: 8/1/2008
//
//	Update/Change: WanShouLong
//	Last Updated: 8/1/2008
//	Description:
//				BubbleGuppies项目角色眨眼工具
//				
//////////////////////////////////////////////////////////

global proc buAminBlink()
{
	string $path = "//File-cluster/gdc/Resource/Support/Maya/icons/BubbleGuppies/anim/";
	
	if (`window -ex buAminBlinkWindow`)
		deleteUI buAminBlinkWindow;
	
	window -title "Blink" -in "Blink" -mxb false buAminBlinkWindow;
		columnLayout -rs 2;
			rowColumnLayout  -nc 3 -cs 1 10 -cw 1 80 -cw 2 50 -cw 3 50;
				checkBox -label "All:" -value 1 -cc "buAminBlinkSide(\"all\")" buAminBlinkWindow_all;
				checkBox -label "Left" -value 0 -cc "buAminBlinkSide(\"left\")" buAminBlinkWindow_left;
				checkBox -label "Right" -value 0 -cc "buAminBlinkSide(\"right\")" buAminBlinkWindow_right;
			setParent ..;
			
			separator -st "double" -w 200;
			
			iconTextButton -image ($path+"UpLidDn.bmp")			-w 200 -iol "UpLidDn-LwLidUp"	-c "buAnimBlinkControls(\"UpLidDn-LwLidUp\")";
			iconTextButton -image ($path+"SmileEyeClose.bmp")	-w 200 -iol "SmileEyeClose"		-c "buAnimBlinkControls(\"SmileEyeClose\")";
			iconTextButton -image ($path+"SmileEyeCloseDn.bmp") -w 200 -iol "SmileEyeCloseDn"	-c "buAnimBlinkControls(\"SmileEyeCloseDn\")";
			iconTextButton -image ($path+"AngryEyeClose.bmp")	-w 200 -iol "AngryEyeClose"		-c "buAnimBlinkControls(\"AngryEyeClose\")";
			iconTextButton -image ($path+"AngleClose.bmp")		-w 200 -iol "AngleClose"		-c "buAnimBlinkControls(\"AngleClose\")";
			iconTextButton -image ($path+"SadClose.bmp")		-w 200 -iol "SadClose"			-c "buAnimBlinkControls(\"SadClose\")";
			iconTextButton -image ($path+"EyeCloseLow.bmp")		-w 200 -iol "EyeCloseLow"		-c "buAnimBlinkControls(\"EyeCloseLow\")";
			iconTextButton -image ($path+"MrGroup.bmp")			-w 200 -iol "MrGroup"			-c "buAnimBlinkControlsForMrGroup";
			iconTextButton -image ($path+"LittleFish.bmp")		-w 200 -iol "LittleFish"		-c "buAnimBlinkControlsForLittleFish";
			iconTextButton -image ($path+"avieyeclose.bmp")		-w 200 -iol "AviFishClose"		-c "buavieyelinkFish" ;
			

	showWindow buAminBlinkWindow;
	window -e -w 207 -h 720 buAminBlinkWindow;
}


global proc buAnimBlinkControls(string $types)
{
	string $side[] = {"Lf","Rt"};
	
	if (!`checkBox -q -v buAminBlinkWindow_all`)
	{
		if (!`checkBox -q -v buAminBlinkWindow_left`)
			$side = stringArrayRemove({"Lf"},$side);
		if (!`checkBox -q -v buAminBlinkWindow_right`)
			$side = stringArrayRemove({"Rt"},$side);
	}

	string $allcons[] = {"UpLidDn","LwLidUp","SmileEyeClose","SmileEyeCloseDn","AngryEyeClose","AngleClose","SadClose","SmileLwLid","WorryUpLid",
						 "SurpriseEye","NarrowEye","EyeCloseLow"};

	
	string $sl[] = `ls -sl`;
	if (!size($sl))
		error "请选择角色任一部分！";
	
	string $buff[];
	tokenize $sl[0] ":" $buff;
	string $facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "Facial_Ctrl";

	float $time = `currentTime -q `;
	
	clear $buff;
	tokenize $types "-" $buff;
	string $keycons[] = $buff;
	
	for ($con in $allcons)
	{
		if (stringArrayCount($con,$keycons) && `objExists ($facial+"."+$side[0]+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+$side[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1) -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)				-v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)				-v $orval	($facial+"."+$si+$con);
			}
		}
		else if (`objExists ($facial+"."+$side[0]+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+$side[0]+$con)`;
				
				setKeyframe -t	$time					-v $orval		($facial+"."+$si+$con);
				setKeyframe	-t ($time+1) -t ($time+2) 	-v 0			($facial+"."+$si+$con);
				setKeyframe	-t ($time+3)			 	-v ($orval/2.0)	($facial+"."+$si+$con);
				setKeyframe -t ($time+4)				-v $orval		($facial+"."+$si+$con);
			}
		}
		else if (stringArrayCount($con,$keycons) && `objExists ($facial+"."+tolower($side[0])+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+tolower($side[0])+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1) -t ($time+2)	-v 1		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)				-v 0.25		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+4)				-v $orval	($facial+"."+tolower($si)+$con);
			}
		}
	}
	select -r $facial;
}

global proc buAminBlinkSide(string $side)
{
	int $state;
	
	switch ($side)
	{
		case "all" :
			$state = `checkBox -q -v buAminBlinkWindow_all`;
			checkBox -e -v 0 buAminBlinkWindow_left;
			checkBox -e -v 0 buAminBlinkWindow_right;
			break;
		case "left" :
		case "right" :
			checkBox -e -v 0 buAminBlinkWindow_all;
			break;
	
	}
}

global proc buAnimBlinkControlsForMrGroup()
{
	string $side[] = {"L","R"};
	string $side1[] = {"left","right"};

	string $sl[] = `ls -sl`;
	if (!size($sl))
		error "请选择角色任一部分！";
	
	string $buff[];
	tokenize $sl[0] ":" $buff;
	string $facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "Facial_Ctrl";

	float $time = `currentTime -q `;

	string $cons[] = {"Eye_Blink","Blink"};
	for ($con in $cons)
	{
		if (`objExists ($facial+"."+$side[0]+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+$side[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				//setKeyframe -t  ($time+1)				-v 0.5		($facial+"."+$si+$con);
				setKeyframe -t ($time+1) -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  				-v 0.32		($facial+"."+$si+$con);
				setKeyframe -t ($time+5)  				-v 0.12		($facial+"."+$si+$con);
				setKeyframe -t ($time+6)  				-v $orval	($facial+"."+$si+$con);
				float $timed=$time+6;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$side1[0]+$con)`)
		{
			for ($si in $side1)
			{
				float $orval = `getAttr ($facial+"."+$side1[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				//setKeyframe -t  ($time+1)				-v 0.5		($facial+"."+$si+$con);
				setKeyframe -t ($time+1) -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  				-v 0.32		($facial+"."+$si+$con);
				setKeyframe -t ($time+5)  				-v 0.12		($facial+"."+$si+$con);
				setKeyframe -t ($time+6)  				-v $orval	($facial+"."+$si+$con);
				float $timed=$time+6;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
	}
	select -r $facial;
}

global proc buAnimBlinkControlsForLittleFish()
{
	string $side[] = {"Left","Right"};
	string $side1[] = {"L","R"};
	
	string $sl[] = `ls -sl`;
	if (!size($sl))
		error "请选择角色任一部分！";
	
	string $buff[];
	tokenize $sl[0] ":" $buff;
	string $facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "Facial_Ctrl";
	if (!`objExists $facial`)
	{
		$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_Ctrl";
		if (!`objExists $facial`)
		{
			$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_ctrl";
		}
	}

	float $time = `currentTime -q `;

	string $cons[] = {"Blink","EyeBlink","_EYE_BLINK"};
	for ($con in $cons)
	{
		if (`objExists ($facial+"."+$side[0]+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+$side[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  -ott "linear"	-v 0.3		($facial+"."+$si+$con);
				setKeyframe -t ($time+5)  -itt "linear"	-v $orval	($facial+"."+$si+$con);
				float $timed=$time+5;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+tolower($side[0])+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+tolower($side[0])+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)  -ott "linear"	-v 0.3		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+5)  -itt "linear"	-v $orval	($facial+"."+tolower($si)+$con);
				float $timed=$time+5;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$side1[0]+$con)`)
		{
			for ($si in $side1)
			{
				float $orval = `getAttr ($facial+"."+$side1[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  				-v 0.3		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  				-v 0.125	($facial+"."+$si+$con);
				setKeyframe -t ($time+5)  				-v $orval	($facial+"."+$si+$con);
				float $timed=$time+5;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
	}
	select -r $facial;
}



global proc buavieyelinkFish()
{
	string $side[] = {"Lf"};
	string $sidea[] = {"Rt"};
	string $side1[] = {"L","R"};
	string $side2[] = {"Lf"};
	string $side3[] = {"Rf"};
	string $sl[] = `ls -sl`;
	if (!size($sl))
		error "请选择角色任一部分！";
	
	string $buff[];
	tokenize $sl[0] ":" $buff;
	string $facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "Facial_Ctrl";
	if (!`objExists $facial`)
	{
		$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_Ctrl";
		if (!`objExists $facial`)
		{
			$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_ctrl";
		}
	}
	int $lfnum=`getAttr ($facial+".LfEyeBig")`;
	int $rfnum=`getAttr ($facial+".RtEyeBig")`;
	


	float $time = `currentTime -q `;

	string $cons[] ={"BigClose"};
	string $consa[] ={"EyeClose"};
	if ($lfnum==1)
	{
		for ($con in $cons)
		{
		if (`objExists ($facial+"."+$side2[0]+$con)`)
		{
			for ($si in $side2)
			{
				float $orval = `getAttr ($facial+"."+$side2[0]+$con)`;
				
				setKeyframe -t  $time	-v $orval		($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+tolower($side2[0])+$con)`)
		{
			for ($si in $side2)
			{
				float $orval = `getAttr ($facial+"."+tolower($side2[0])+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+tolower($si)+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$side1[0]+$con)`)
		{
			for ($si in $side1)
			{
				float $orval = `getAttr ($facial+"."+$side1[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  				-v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  				-v $orval	($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		}
	

	}
	else if ($lfnum==0)
	
	{
		for ($con in $consa)
		{
		if (`objExists ($facial+"."+$sidea[0]+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+$sidea[0]+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+tolower($sidea[0])+$con)`)
		{
			for ($si in $side)
			{
				float $orval = `getAttr ($facial+"."+tolower($sidea[0])+$con)`;
				
				setKeyframe -t  $time	-v $orval		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+tolower($si)+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$sidea[0]+$con)`)
		{
			for ($si in $side1)
			{
				float $orval = `getAttr ($facial+"."+$sidea[0]+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  	-v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  	-v $orval	($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		}
	
	}
	
	select -r $facial;
	buavieyelinkFishrt;
}


global proc buavieyelinkFishrt()
{
	
	
	string $side3[] = {"Rf"};
	string $side5[] = {"Rt"};
	string $sl[] = `ls -sl`;
	if (!size($sl))
		error "请选择角色任一部分！";
	
	string $buff[];
	tokenize $sl[0] ":" $buff;
	string $facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "Facial_Ctrl";
	if (!`objExists $facial`)
	{
		$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_Ctrl";
		if (!`objExists $facial`)
		{
			$facial = `substring $sl[0] 1 (size($sl[0])-size($buff[size($buff)-1]))` + "facial_ctrl";
		}
	}
	int $lfnum=`getAttr ($facial+".LfEyeBig")`;
	int $rfnum=`getAttr ($facial+".RtEyeBig")`;
	


	float $time = `currentTime -q `;

	string $cons[] ={"BigClose"};
	string $consa[] ={"EyeClose"};
	
	if ($rfnum==1)
	{
	
	for ($con in $cons)
	{
		if (`objExists ($facial+"."+$side3[0]+$con)`)
		{
			for ($si in $side3)
			{
				float $orval = `getAttr ($facial+"."+$side3[0]+$con)`;
				
				setKeyframe -t  $time	-v $orval		($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+tolower($side3[0])+$con)`)
		{
			for ($si in $side3)
			{
				float $orval = `getAttr ($facial+"."+tolower($side3[0])+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+tolower($si)+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$side3[0]+$con)`)
		{
			for ($si in $side3)
			{
				float $orval = `getAttr ($facial+"."+$side3[0]+$con)`;
				
				setKeyframe -t  $time					-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1		($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  				-v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  				-v $orval	($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
	
	}

	}
	else
	{
	for ($con in $consa)
	{
		if (`objExists ($facial+"."+$side5[0]+$con)`)
		{
			for ($si in $side5)
			{
				float $orval = `getAttr ($facial+"."+$side5[0]+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+tolower($side5[0])+$con)`)
		{
			for ($si in $side5)
			{
				float $orval = `getAttr ($facial+"."+tolower($side5[0])+$con)`;
				
				setKeyframe -t  $time	-v $orval		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+3)  -v 0.25		($facial+"."+tolower($si)+$con);
				setKeyframe -t ($time+4)  -v $orval		($facial+"."+tolower($si)+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
		else if (`objExists ($facial+"."+$side5[0]+$con)`)
		{
			for ($si in $side5)
			{
				float $orval = `getAttr ($facial+"."+$side5[0]+$con)`;
				
				setKeyframe -t  $time		-v $orval	($facial+"."+$si+$con);
				setKeyframe -t ($time+1)  -t ($time+2)	-v 1	($facial+"."+$si+$con);
				setKeyframe -t ($time+3)  	-v 0.25		($facial+"."+$si+$con);
				setKeyframe -t ($time+4)  	-v $orval	($facial+"."+$si+$con);
				float $timed=$time+4;
				selectKey -add -k -t ($time+":"+$timed) $facial;
				keyTangent -itt linear -ott linear;
			}
		}
	}
	}
	select -r $facial;
}
