global proc buAminTransform()
{
	string $buff[];
	
	string $chars[] = `ls "*:Character"`;
	string $deema;
	
	for ($char in $chars)
	{
		int $num = `tokenize $char ":" $buff`;

		tokenize $buff[0] "_" $buff;

		if (startsWith($buff[1],"c001"))
		{
			$deema = $char;
		}
	}

	tokenize $deema ":" $buff;
	string $pre = `substring $deema 1 (size($deema)-size($buff[1]))`;
	string $tail = $pre + "Tail_ctrl";

	if (`objExists $tail`)
	{
		string $at = "slAnimTransform";
		if (!`objExists $at`)
			sphere -name $at;

		copyKey -at "Flutter" $tail;
		pasteKey -at "translateX" $at;

		copyKey -at "Flap" $tail;
		pasteKey -at "translateY" $at;

		cutKey -cl -t ":" -f ":" -at "Flutter" -at "Flap" $tail;

		copyKey -at "translateX" $at;
		pasteKey -at "Flap" $tail;
		
		copyKey -at "translateY" $at;
		pasteKey -at "Flutter" $tail;

		delete $at;
	}
}