//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////


global proc buAnimReplaceDeema117()
{
	string $referenceFiles[] = `file -q -r`;
	for ($file in $referenceFiles )
	{
		string $referenceNode = `referenceQuery -rfn $file`;

		string $buff[];
		int $num = `tokenize $file "{}" $buff`;
		string $old = $buff[0];
		string $new;
		
		if (endsWith($old,"bu_c001042deemalunchdance_h_ms_anim.mb"))
		{
			$new = substituteAllString($old,"bu_c001042deemalunchdance_h_ms_anim.mb","bu_c001042deemalunchdance_forold_h_ms_anim.mb");
		}
		
		if (`filetest -r $new`)
		{
			file -lr $referenceNode $new;
		}
	}
}