global proc buAnimLipsTool()
{
	string $buff[];
	//选择角色控制线组
	string $sel[] = `ls -sl`;
	if (size($sel) != 1)
		error "请选择导入口型的角色!";
	tokenize $sel[0] ":" $buff;
	string $pre = `substring $sel[0] 1 (size($sel[0])-size($buff[size($buff)-1]))`;
	string $mouth = $pre + "Mouth";
	// 角色名字添加 
	string $cuff[];
	tokenize $pre "_" $cuff;
	string $mat=`match "[a-z]" $cuff[1]`+`match "[0-9]+" $cuff[1]`;
	int	$sz=`size $cuff[1]`-`size $mat`;
	string $chname=endString($cuff[1], $sz);
	//文件名字
	string $filename = `file -q -sn -shn`;
	if (!size($filename))
		return ;
	tokenize $filename "_" $buff;
	string $episode = $buff[1];
	string $shot[0]={$buff[2]};
	//$shot[0] = `substring $buff[2] 1 4`;
	
	
	
	string $get = `idmtService "GetAnimByFilename" $filename`;
	int $num = `tokenize $get "|" $buff`;
	if ($num == 7)
	{
		tokenize $buff[6] "*" $buff;
		$shot = $buff;
	}
	int $start = `playbackOptions -q -min`;
	int $curtime;

	string $path = "//File-cluster/gdc/Projects/BubbleGuppies/BubbleGuppies_Scratch/Animation/LipsFile/"+$episode+"/";
	
	



	string $tFolder[] = `getFileList -fld $path`;
	if (size($tFolder) != 0) $path += ($tFolder[0]+"/");
	$tFolder = `getFileList -fld $path`;
	if (size($tFolder) != 0) $path += ($tFolder[0]+"/");

	string $lipsFile;
	for ($i=0;$i<size($shot);$i++)
	{
		string $files[] = `getFileList -fld $path -fs ($episode+"_"+$shot[$i]+"_*"+$chname+"*_"+"*.txt")`;
		
		if (`size $files`==1)
		{
		string $files[] = `getFileList -fld $path -fs ($episode+"_"+$shot[$i]+"_*"+$chname+"*_"+"*.txt")`;
		
		if ($i)
			$start = $curtime;
		if (size($files) && `attributeExists "MouthTemp" $mouth`)
			{
			cutKey -cl -t ($start+":") -f ":" -at "MouthTemp" $mouth;

			$lipsFile = $path + $files[size($files)-1];
			
			$fileId = `fopen $lipsFile "r"`;
			$nextLine = `fgetline $fileId`;
			$nextLine = `fgetline $fileId`;
			while (size($nextLine)>0)
			{
				int $num = `tokenize $nextLine " \n" $buff`;
				if ($num == 2)
				{
					int $time = (int)$buff[0];
					int $val = (int)`substring $buff[1] 2 (size($buff[1]))`;
					
					setKeyframe -t ($start+$time-1) -v $val -ott "step" -at "MouthTemp" $mouth;
				}
				$curtime = $start + (int)$buff[0]-1;
				$nextLine = `fgetline $fileId`;
			}
			fclose $fileId;

			print ($files[0]+"导入口型成功");
			}
		}
		
		else
		{
			
			string $files[] = `getFileList -fld $path -fs ($episode+"_"+$shot[$i]+"*.txt")`;
			
		if ($i)
			$start = $curtime;
		if (size($files) && `attributeExists "MouthTemp" $mouth`)
			{
			cutKey -cl -t ($start+":") -f ":" -at "MouthTemp" $mouth;

			$lipsFile = $path + $files[size($files)-1];
			
			$fileId = `fopen $lipsFile "r"`;
			$nextLine = `fgetline $fileId`;
			$nextLine = `fgetline $fileId`;
			while (size($nextLine)>0)
			{
				//print ($nextLine+"\n");
				int $num = `tokenize $nextLine " \n" $buff`;
				if ($num == 2)
				{
					int $time = (int)$buff[0];
					int $val = (int)`substring $buff[1] 2 (size($buff[1]))`;
					
					setKeyframe -t ($start+$time-1) -v $val -ott "step" -at "MouthTemp" $mouth;
				}
				$curtime = $start + (int)$buff[0]-1;
				$nextLine = `fgetline $fileId`;
			}
			fclose $fileId;

			print ($files[0]+"导入口型成功!");
			}
		}
	}
	
	
}