global proc buAnimEyesView()
{
	int $original;
	string $rigctrls[] = `ls "*rig_ctrl" "*:rig_ctrl" "*:*:rig_ctrl"`;
	for ($ctrl in $rigctrls)
	{
		if (`objExists ($ctrl+".View")`)
			$original = `getAttr ($ctrl+".View")`;

		if (!$original)
		{
			$original = 1;
			break;
		}
		$original = 0;
	}

	for ($ctrl in $rigctrls)
	{
		if (`objExists ($ctrl+".View")`)
			setAttr ($ctrl+".View") $original;
	}
}