global proc buAnimBBSWin()
{
	if (`window -ex buAnimBBSWin`)
		deleteUI buAnimBBSWin;

	window -title "泡泡" -in "泡泡" -mxb false -mnb false buAnimBBSWin;
		columnLayout -rs 5;	
			button -label "出现"	-w 100 -c "buAnimBBS(1)";
			button -label "消失"	-w 100 -c "buAnimBBS(2)";
	showWindow buAnimBBSWin;
}



global proc buAnimBBS(int $type)
{
	string $bbs[] = `ls -sl`;
	if (!`objExists $bbs[0]`)
		error "请选择泡泡物体";

	
	float $curtime = `currentTime -q `;


	if ($type == 1)
	{
		cutKey -cl -t (($curtime-1)+":"+($curtime+7)) -f ":" -at "scaleX" -at "scaleY" -at "scaleZ" -at "visibility" $bbs[0];

		setKeyframe -t ($curtime-1)		-v 1.08	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t $curtime			-v 1.08	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+1)		-v 1.15	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+2)		-v 1.04	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+3)		-v 1.00	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];

		setKeyframe -t ($curtime-1)		-v 0		 -ott "step" -at "visibility" $bbs[0];
		setKeyframe -t $curtime			-v 1		 -ott "step" -at "visibility" $bbs[0];
	}
	else if ($type == 2)
	{
		cutKey -cl -t (($curtime-1)+":"+($curtime+7)) -f ":" -at "scaleX" -at "scaleY" -at "scaleZ" -at "visibility" $bbs[0];
		
		
		setKeyframe -t $curtime			-v 1.0	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+1)		-v 0.95	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+2)		-v 0.90	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+3)		-v 0.99	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];
		setKeyframe -t ($curtime+4)		-v 1.15	-itt "plateau" -ott "plateau" -at "scaleX" -at "scaleY" -at "scaleZ" $bbs[0];

		setKeyframe -t $curtime			-v 1		 -ott "step" -at "visibility" $bbs[0];
		setKeyframe -t ($curtime+5)		-v 0		 -ott "step" -at "visibility" $bbs[0];
	}
}