//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WanShouLong
//	Created: 
//
//	Update/Change: WanShouLong
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////


global proc buAnimRepairRotateAxis()
{
	string $sl[] = `ls -sl`;
	if (!`size($sl)`)
		error " !!! ";
	
	//string $ro = "rotate";
	string $attrs[] = {"X","Y","Z"};
	for ($head in $sl)
	{
		for ($attr in $attrs)
		{
			float $times[] = `keyframe -q -tc {($head+".rotate"+$attr),($head+".rotateAxis"+$attr)}`;
			string $stimes[];
			for ($time in $times)
			{
				$stimes[size($stimes)] = (string)$time;
			}
			$stimes = stringArrayRemoveDuplicates($stimes);
			clear $times;
			for ($time in $stimes)
			{
				$times[size($times)] = (float)$time;
			}

			float $val[] = {};
			
			for ($time in $times)
			{
				float $ro = `getAttr -time $time ($head+".rotate"+$attr)`;
				float $ax = `getAttr -time $time ($head+".rotateAxis"+$attr)`;
				$val[size($val)] = $ro+$ax;
				//setKeyframe -t $time -v ($ro+$ax) ($head+".rotate"+$attr);
				//keyframe -e -t $time -r -vc $ax ($head+".rotate"+$attr);
				//print ((string)$time+"---"+(string)$ro+"---"+(string)$ax+"\n");
			}
			cutKey -cl -t ":" -f ":" -at ("rotate"+$attr) $head;
			for ($i=0;$i<size($times);$i++ )
			{
				//print ($attr+"---"+(string)$times[$i]+"---"+(string)$val[$i]+"\n");
				setKeyframe -t $times[$i] -v $val[$i] ($head+".rotate"+$attr);
			}
			cutKey -cl -t ":" -f ":" -at ("rotateAxis"+$attr) $head;
			setAttr ($head+".rotateAxis"+$attr) 0 ;
		}
	}
}