//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc buEffectShakeAnim()
{
	string $shakeObjs[] = `ls -l -sl`;
	float $sframe = `playbackOptions -q -min`;
	float $eframe = `playbackOptions -q -max`;
	for ($obj in $shakeObjs)
	{
		for ($i=$sframe;$i<$eframe;$i=$i+15 )
		{
			float $rotateX = 15*rand(-1,1);
			float $rotateY = 15*rand(-1,1);
			float $rotateZ = 15*rand(-1,1);
			setKeyframe -t $i -v $rotateX  ($obj+".rx");
			setKeyframe -t $i -v $rotateY  ($obj+".ry");
			setKeyframe -t $i -v $rotateZ  ($obj+".rz");
		}
	}
}