
proc int hjHardwaretexture()
{
int $value1 =`checkBoxGrp -q -value1 hjHawGrp`;
int $value2 =`checkBoxGrp -q -value2 hjHawGrp`;
int $value3 =`checkBoxGrp -q -value3 hjHawGrp`;
if (($value1+$value2)>2)
{
error "只能选择一种级别";

}


if($value1==1)
	{
	
	return 32;
	}
 else if ($value2==1)
	{
	
	return 64;
	}
 else 
	{
	
	return 128;
	}
}


global proc hjhardwareset()
{
int $imsize=`hjHardwaretexture`;
string $lstexture[]=`ls -textures`;
for ($i in $lstexture)
{
if (`attributeExists "resolution" $i`) 
{
 setAttr ($i+".resolution") $imsize;
} 
else
{
addAttr -ln resolution -at long -dv 32 $i;  
setAttr ($i+".resolution") 32;
}
}

}



global proc buHardwaresetmap()
{
string $myw=`window -width 300 -height 200 HawmyUI`;
frameLayout -label "设置硬件贴图显示精度" -labelAlign "bottom" -borderStyle "etchedOut" ;
columnLayout -adjustableColumn true;
    
   checkBoxGrp -numberOfCheckBoxes 3 -label "贴图显示级别" -labelArray3 "低" "中" "高" -value1 on hjHawGrp;
   button -label "设置"  -align "center" -c hjhardwareset;
  setParent ..;

showWindow $myw;


}
