global proc hjCachedisplay()
{
		
		$sc = `selectionConnection -lst`;
		string $sce[] = `ls -long -type "diskCache"`;
		
		for ($node1 in $sce) 
		{ 
		selectionConnection -e -select $node1 $sc;
		} 
	    print $sce;
		if ( `window -exists HjcacheUI` ) deleteUI HjcacheUI;
		$win=`window     -title "Display Cache" -wh 208 550 -maximizeButton 0 -sizeable 1 HjcacheUI`;
		$frame=`frameLayout -labelVisible false`;
		string $panel = `outlinerPanel`;
		string $outliner = `outlinerPanel -query -outlinerEditor $panel`;
		outlinerEditor -e -dag 0 -mlc $sc -selectionConnection "modelList" $outliner;
		showWindow $win;
}
