global proc slObjectShadingEngine()
{
	string $objs[] = `ls -sl`;
	if (!size($objs))
		return ;

	string $buff[];
	
	int $num = `tokenize $objs[0] ":" $buff`;
	string $pre = `substring $objs[0] 1 (size($objs[0])-size($buff[$num-1]))`;

	string $reffile = `referenceQuery -filename $objs[0]`;

	for ($obj in $objs)
	{
		
	}
}

global proc string slObjectShadingEngineCmd(string $obj)
{
	string $CMD;
	
	string $buff[];
	int $num = `tokenize $obj ":" $buff`;
	string $pre = `substring $obj 1 (size($obj)-size($buff[$num-1]))`;
	string $filename = `substring $obj (size($obj)-size($buff[$num-1])+1) (size($obj))`;

	string $path = `internalVar -userTmpDir`;

	string $source[] = `listConnections -type shadingEngine -plugs true -s true -d false $obj`;
	string $sourceD[];
	for ($s in $source)
	{
		string $c[] = `listConnections -plugs true $s`;
		$sourceD[size($sourceD)] = $c[0];
	}

	string $dest[] = `listConnections -type shadingEngine -plugs true -s false -d true $obj`;
	string $destD[];
	for ($d in $dest)
	{
		string $c[] = `listConnections -plugs true $d`;
		$destD[size($destD)] = $c[0];
	}

	return $CMD;
}