		
		
		float $rep = `intSliderGrp  -q -v buAnimSwimWindow_rep`;
		float $ran = `floatSliderGrp  -q -v buAnimSwimWindow_ran`;
		float $fre = (int)(`intSliderGrp -q -v buAnimSwimWindow_fre`/2.0);
		int $curtime = `currentTime -q`;
		
		string $buff[];
		int $num = `tokenize $char[0] ":" $buff`;
		string $pre = `substring $char[0] 1 (size($char[0])-size($buff[$num-1]))`;

		string $attr[] = {"rotateX","rotateY","rotateZ"};
		for ($i=0;$i<size($attr);$i++)
		{
			if (`objExists ($pre+"spine1_ctrl")` && $i != 1)
			{
				float $time = (int)(21.0/25.0*$fre);
				
				float $curval = `getAttr ($pre+"spine1_ctrl."+$attr[$i])`;
				cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"spine1_ctrl");
				
				setKeyframe -t $curtime				-v ($curval+0.2*$ran)				-itt "spline"	-ott "spline"		($pre+"spine1_ctrl."+$attr[$i]);
				for ($j=1;$j<=$rep;$j++ )
				{
					setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-0.3*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine1_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$time+$fre+$fre*2*($j-1))		-v ($curval+0.3*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine1_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+0.2*$ran)	-itt "spline"	-ott "spline"		($pre+"spine1_ctrl."+$attr[$i]);
				}
			}
			if (`objExists ($pre+"spine2_ctrl")` && $i != 1)
			{
				float $time = (int)(22.0/25.0*$fre);
				
				float $curval = `getAttr ($pre+"spine2_ctrl."+$attr[$i])`;
				cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"spine2_ctrl");
				
				setKeyframe -t $curtime				-v ($curval+0.5*$ran)				-itt "spline"	-ott "spline"		($pre+"spine2_ctrl."+$attr[$i]);
				for ($j=1;$j<=$rep;$j++ )
				{
					setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-0.6*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine2_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$time+$fre+$fre*2*($j-1))		-v ($curval+0.6*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine2_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+0.5*$ran)	-itt "spline"	-ott "spline"		($pre+"spine2_ctrl."+$attr[$i]);
				}
			}
			if (`objExists ($pre+"spine3_ctrl")` && $i != 1)
			{
				float $time = (int)(23.0/25.0*$fre);
				
				float $curval = `getAttr ($pre+"spine3_ctrl."+$attr[$i])`;
				cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"spine3_ctrl");
				
				setKeyframe -t $curtime				-v ($curval+4.4*$ran)				-itt "spline"	-ott "spline"		($pre+"spine3_ctrl."+$attr[$i]);
				for ($j=1;$j<=$rep;$j++ )
				{
					setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-4.5*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine3_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$time+$fre+$fre*2*($j-1))		-v ($curval+4.5*$ran)	-itt "plateau"	-ott "plateau"		($pre+"spine3_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+4.4*$ran)	-itt "spline"	-ott "spline"		($pre+"spine3_ctrl."+$attr[$i]);
				}
			}
			if (`objExists ($pre+"upfin2_ctrl")` && $i == 3)
			{
				float $time = $fre;
				
				float $curval = `getAttr ($pre+"upfin2_ctrl."+$attr[$i])`;
				cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"upfin2_ctrl");
				
				setKeyframe -t $curtime				-v ($curval+2*$ran)				-itt "plateau"	-ott "plateau"		($pre+"upfin2_ctrl."+$attr[$i]);
				for ($j=1;$j<=$rep;$j++ )
				{
					setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-2*$ran)		-itt "plateau"	-ott "plateau"		($pre+"upfin2_ctrl."+$attr[$i]);
					setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+2*$ran)		-itt "plateau"	-ott "plateau"		($pre+"upfin2_ctrl."+$attr[$i]);
				}
			}
			if (`objExists ($pre+"uptail_ctrl")`)
			{
				float $time = (int)(24.0/25.0*$fre);
				
				if ($i == 1)
				{
					float $curval = `getAttr ($pre+"uptail_ctrl."+$attr[$i])`;
					cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"uptail_ctrl");
					
					setKeyframe -t $curtime				-v ($curval+1.8*$ran)				-itt "spline"	-ott "spline"		($pre+"uptail_ctrl."+$attr[$i]);
					for ($j=1;$j<=$rep;$j++ )
					{
						setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-1.9*$ran)		-itt "plateau"	-ott "plateau"		($pre+"uptail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$time+$fre+$fre*2*($j-1))		-v ($curval+1.9*$ran)		-itt "plateau"	-ott "plateau"		($pre+"uptail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+1.8*$ran)		-itt "spline"	-ott "spline"		($pre+"uptail_ctrl."+$attr[$i]);
					}
				}
				else
				{
					float $curval = `getAttr ($pre+"uptail_ctrl."+$attr[$i])`;
					cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"uptail_ctrl");
					
					setKeyframe -t $curtime				-v ($curval+2.9*$ran)				-itt "spline"	-ott "spline"		($pre+"uptail_ctrl."+$attr[$i]);
					for ($j=1;$j<=$rep;$j++ )
					{
						setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-3*$ran)		-itt "plateau"	-ott "plateau"		($pre+"uptail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$time+$fre+$fre*2*($j-1))		-v ($curval+3*$ran)		-itt "plateau"	-ott "plateau"		($pre+"uptail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+2.9*$ran)	-itt "spline"	-ott "spline"		($pre+"uptail_ctrl."+$attr[$i]);
					}
				}
			}
			if (`objExists ($pre+"downtail_ctrl")`)
			{
				float $time = $fre;
				
				if ($i == 1)
				{
					float $curval = `getAttr ($pre+"downtail_ctrl."+$attr[$i])`;
					cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"downtail_ctrl");
					
					setKeyframe -t $curtime				-v ($curval+1*$ran)				-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					for ($j=1;$j<=$rep;$j++ )
					{
						setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-1*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+1*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					}
				}
				else if ($i == 2)
				{
					float $curval = `getAttr ($pre+"downtail_ctrl."+$attr[$i])`;
					cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"downtail_ctrl");
					
					setKeyframe -t $curtime				-v ($curval-4.8*$ran)				-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					for ($j=1;$j<=$rep;$j++ )
					{
						setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval+4.8*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval-4.8*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					}
				}
				else
				{
					float $curval = `getAttr ($pre+"downtail_ctrl."+$attr[$i])`;
					cutKey -cl -t ($curtime+"") -f "" -at $attr[$i] ($pre+"downtail_ctrl");
					
					setKeyframe -t $curtime				-v ($curval+3*$ran)				-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					for ($j=1;$j<=$rep;$j++ )
					{
						setKeyframe -t ($curtime+$time+$fre*2*($j-1))			-v ($curval-3*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
						setKeyframe -t ($curtime+$fre*2*$j)						-v ($curval+3*$ran)		-itt "plateau"	-ott "plateau"		($pre+"downtail_ctrl."+$attr[$i]);
					}
				}
			}

		}
		
