# -*- coding: utf-8 -*-

# Form implementation generated from reading myuis file 'UI_Main.myuis'
#
# Created: Sat Jul 25 12:55:44 2015
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1027, 749)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.centralLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.centralLayout.setSpacing(3)
        self.centralLayout.setMargin(3)
        self.centralLayout.setObjectName(_fromUtf8("centralLayout"))
        self.frame_left = QtGui.QFrame(self.centralwidget)
        self.frame_left.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_left.setObjectName(_fromUtf8("frame_left"))
        self.Layout_left = QtGui.QVBoxLayout(self.frame_left)
        self.Layout_left.setSpacing(3)
        self.Layout_left.setMargin(3)
        self.Layout_left.setObjectName(_fromUtf8("Layout_left"))
        self.label = QtGui.QLabel(self.frame_left)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.Layout_left.addWidget(self.label)
        self.QGraphicsView_Main = GSView(self.frame_left)
        self.QGraphicsView_Main.setObjectName(_fromUtf8("QGraphicsView_Main"))
        self.Layout_left.addWidget(self.QGraphicsView_Main)
        self.centralLayout.addWidget(self.frame_left)
        self.frame_right = QtGui.QFrame(self.centralwidget)
        self.frame_right.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_right.setObjectName(_fromUtf8("frame_right"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_right)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.toolBox = QtGui.QToolBox(self.frame_right)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setFrameShape(QtGui.QFrame.Box)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 484, 665))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page.setFont(font)
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.QDoubleSpinBox_tx = QtGui.QDoubleSpinBox(self.page)
        self.QDoubleSpinBox_tx.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.QDoubleSpinBox_tx.setDecimals(2)
        self.QDoubleSpinBox_tx.setMinimum(-999999999.0)
        self.QDoubleSpinBox_tx.setMaximum(999999999.0)
        self.QDoubleSpinBox_tx.setObjectName(_fromUtf8("QDoubleSpinBox_tx"))
        self.gridLayout.addWidget(self.QDoubleSpinBox_tx, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.QDoubleSpinBox_ty = QtGui.QDoubleSpinBox(self.page)
        self.QDoubleSpinBox_ty.setMinimum(-999999999.0)
        self.QDoubleSpinBox_ty.setMaximum(999999999.0)
        self.QDoubleSpinBox_ty.setObjectName(_fromUtf8("QDoubleSpinBox_ty"))
        self.gridLayout.addWidget(self.QDoubleSpinBox_ty, 2, 2, 1, 1)
        self.QDoubleSpinBox_tz = QtGui.QDoubleSpinBox(self.page)
        self.QDoubleSpinBox_tz.setMinimum(-999999999.0)
        self.QDoubleSpinBox_tz.setMaximum(999999999.0)
        self.QDoubleSpinBox_tz.setObjectName(_fromUtf8("QDoubleSpinBox_tz"))
        self.gridLayout.addWidget(self.QDoubleSpinBox_tz, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.QCheckBox_autocam = QtGui.QCheckBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QCheckBox_autocam.setFont(font)
        self.QCheckBox_autocam.setChecked(True)
        self.QCheckBox_autocam.setObjectName(_fromUtf8("QCheckBox_autocam"))
        self.verticalLayout_4.addWidget(self.QCheckBox_autocam)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 484, 665))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page_2.setFont(font)
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.QCheckBox_Maya_Selection = QtGui.QCheckBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QCheckBox_Maya_Selection.setFont(font)
        self.QCheckBox_Maya_Selection.setChecked(True)
        self.QCheckBox_Maya_Selection.setObjectName(_fromUtf8("QCheckBox_Maya_Selection"))
        self.verticalLayout.addWidget(self.QCheckBox_Maya_Selection)
        self.QCheckBox_Control_Moveable = QtGui.QCheckBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QCheckBox_Control_Moveable.setFont(font)
        self.QCheckBox_Control_Moveable.setChecked(True)
        self.QCheckBox_Control_Moveable.setObjectName(_fromUtf8("QCheckBox_Control_Moveable"))
        self.verticalLayout.addWidget(self.QCheckBox_Control_Moveable)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.QSlider_CT_Opacity_Selected = QtGui.QSlider(self.page_2)
        self.QSlider_CT_Opacity_Selected.setMaximum(100)
        self.QSlider_CT_Opacity_Selected.setSingleStep(10)
        self.QSlider_CT_Opacity_Selected.setPageStep(20)
        self.QSlider_CT_Opacity_Selected.setProperty("value", 100)
        self.QSlider_CT_Opacity_Selected.setOrientation(QtCore.Qt.Horizontal)
        self.QSlider_CT_Opacity_Selected.setObjectName(_fromUtf8("QSlider_CT_Opacity_Selected"))
        self.gridLayout_2.addWidget(self.QSlider_CT_Opacity_Selected, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.QSlider_BG_Opacity = QtGui.QSlider(self.page_2)
        self.QSlider_BG_Opacity.setMaximum(100)
        self.QSlider_BG_Opacity.setSingleStep(10)
        self.QSlider_BG_Opacity.setPageStep(20)
        self.QSlider_BG_Opacity.setProperty("value", 100)
        self.QSlider_BG_Opacity.setOrientation(QtCore.Qt.Horizontal)
        self.QSlider_BG_Opacity.setObjectName(_fromUtf8("QSlider_BG_Opacity"))
        self.gridLayout_2.addWidget(self.QSlider_BG_Opacity, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.QTableWidget_Data = QtGui.QTableWidget(self.page_2)
        self.QTableWidget_Data.setLineWidth(1)
        self.QTableWidget_Data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.QTableWidget_Data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.QTableWidget_Data.setAutoScroll(True)
        self.QTableWidget_Data.setAutoScrollMargin(10)
        self.QTableWidget_Data.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.QTableWidget_Data.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.QTableWidget_Data.setShowGrid(True)
        self.QTableWidget_Data.setGridStyle(QtCore.Qt.SolidLine)
        self.QTableWidget_Data.setWordWrap(True)
        self.QTableWidget_Data.setObjectName(_fromUtf8("QTableWidget_Data"))
        self.QTableWidget_Data.setColumnCount(1)
        self.QTableWidget_Data.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.QTableWidget_Data.setHorizontalHeaderItem(0, item)
        self.QTableWidget_Data.horizontalHeader().setCascadingSectionResizes(True)
        self.QTableWidget_Data.horizontalHeader().setSortIndicatorShown(False)
        self.QTableWidget_Data.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.QTableWidget_Data)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.QPushButton_Duplicate = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPushButton_Duplicate.setFont(font)
        self.QPushButton_Duplicate.setObjectName(_fromUtf8("QPushButton_Duplicate"))
        self.horizontalLayout.addWidget(self.QPushButton_Duplicate)
        self.QPushButton_Delete = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.QPushButton_Delete.setFont(font)
        self.QPushButton_Delete.setObjectName(_fromUtf8("QPushButton_Delete"))
        self.horizontalLayout.addWidget(self.QPushButton_Delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.QPushButton_IMPORT = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QPushButton_IMPORT.setFont(font)
        self.QPushButton_IMPORT.setObjectName(_fromUtf8("QPushButton_IMPORT"))
        self.verticalLayout.addWidget(self.QPushButton_IMPORT)
        self.QPushButton_EXPORT = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QPushButton_EXPORT.setFont(font)
        self.QPushButton_EXPORT.setObjectName(_fromUtf8("QPushButton_EXPORT"))
        self.verticalLayout.addWidget(self.QPushButton_EXPORT)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.QPushButton_test = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QPushButton_test.setFont(font)
        self.QPushButton_test.setObjectName(_fromUtf8("QPushButton_test"))
        self.verticalLayout_3.addWidget(self.QPushButton_test)
        self.QPushButton_test2 = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QPushButton_test2.setFont(font)
        self.QPushButton_test2.setObjectName(_fromUtf8("QPushButton_test2"))
        self.verticalLayout_3.addWidget(self.QPushButton_test2)
        self.verticalLayout_3.setStretch(0, 1)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.toolBox)
        self.centralLayout.addWidget(self.frame_right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "测试表情面板", None))
        self.label.setText(_translate("MainWindow", "---------------------------标题---------------------------", None))
        self.label_2.setText(_translate("MainWindow", " TX:", None))
        self.label_3.setText(_translate("MainWindow", " TY: ", None))
        self.label_4.setText(_translate("MainWindow", " TZ: ", None))
        self.QCheckBox_autocam.setText(_translate("MainWindow", "自动切换摄像机", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "=======动画(规划中)=======", None))
        self.QCheckBox_Maya_Selection.setText(_translate("MainWindow", "并联Maya选择物体", None))
        self.QCheckBox_Control_Moveable.setText(_translate("MainWindow", "控制器是否可移动", None))
        self.label_6.setText(_translate("MainWindow", "背景透明度：", None))
        self.label_5.setText(_translate("MainWindow", "所选控制器透明度：", None))
        item = self.QTableWidget_Data.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称", None))
        item = self.QTableWidget_Data.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "图片类型", None))
        item = self.QTableWidget_Data.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "位置：X", None))
        item = self.QTableWidget_Data.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "位置：Y", None))
        item = self.QTableWidget_Data.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "缩放：", None))
        item = self.QTableWidget_Data.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "透明度：", None))
        item = self.QTableWidget_Data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "数值", None))
        self.QPushButton_Duplicate.setText(_translate("MainWindow", "复制", None))
        self.QPushButton_Delete.setText(_translate("MainWindow", "删除", None))
        self.QPushButton_IMPORT.setText(_translate("MainWindow", "导入数据", None))
        self.QPushButton_EXPORT.setText(_translate("MainWindow", "导出数据", None))
        self.QPushButton_test.setText(_translate("MainWindow", "test", None))
        self.QPushButton_test2.setText(_translate("MainWindow", "test2", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "=======设置(建设中)=======", None))
import GS__View;reload(GS__View)
from GS__View import GSView
