//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 12/10/2012
//
//	Update/Change: WansHoulOng
//	Last Updated: 12/10/2012
//	Description:
//				将locator替换为nubs控制器
//////////////////////////////////////////////////////////


global proc caModelLocToNubs()
{
	string $locs[] = `ls -type locator`;
	for($item in $locs)
	{
		//获取transform节点
		string $trans[] = `listRelatives -f -p $item`;
		float $piv[] = `xform -q -ws -piv $trans[0]`;
		
		//创建nubs线圈
		string $cons[] = `circle -c 0 0 0 -nr 0 1 0 -sw 360 -r 20 -d 3 -ut 0 -tol 0.01 -s 8 -ch 1`;
		setAttr ($cons[0]+".tx") $piv[0];
		setAttr ($cons[0]+".ty") $piv[1];
		setAttr ($cons[0]+".tz") $piv[2];
		makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 $cons[0]; 
		
		//获取父节点
		string $parent[] = `listRelatives -f -p $trans[0]`;
		parent $cons[0] $parent[0];

		//获取子节点
		string $children[] = `listRelatives -f -c -type transform $trans[0]`;
		//print $children;
		//print "--------\n";
		if (size($children))
			parent $children $cons[0];

		//改名
		string $buff[] = stringToStringArray($trans[0],"|");
		string $locname = $buff[size($buff)-1];
		rename $trans[0] ($locname+"_loc");
		rename $cons[0] $locname;

		delete ($locname+"_loc");
	}
}