
global proc clUnlockNodes()
{
	source "//file-cluster/GDC/Resource/Support/Maya/scripts/cyBakeClothMain.mel";

	string $allNodes[]=`ls -type mesh -type nurbsSurface -type transform -type nParticle -type fluidShape`;
	
	for ($a in $allNodes)
	{
		if (`attributeExists "overrideEnabled" $a`)
		{
			string $connect= `connectionInfo -sfd ($a + ".overrideEnabled")`;
			myCBdeleteConnection ($a + ".overrideEnabled");
			setAttr ($a + ".overrideEnabled") 0;				
		}
		lockNode -lock off $a;
	}
}


