
global proc do3_skGrassCheck()
{
	string $temp_name_check[] = `ls -sl`;
	int $num_check = size($temp_name_check);

	string $temp_name_same[] = {};

	float $info_tx[] = {};
	float $info_ty[] = {};
	float $info_tz[] = {};

	for($i = 0 ; $i < $num_check ; $i++)
	{
		$info_tx[size($info_tx)] = `getAttr ($temp_name_check[$i]+".tx")`;
		$info_ty[size($info_ty)] = `getAttr ($temp_name_check[$i]+".ty")`;
		$info_tz[size($info_tz)] = `getAttr ($temp_name_check[$i]+".tz")`;
	}
	
	for($i =0 ; $i< $num_check ; $i++)
	{
		for($j = 1 ; $j < ($num_check-$i) ;$j++ )
		{
			if($info_tx[$i + $j] == $info_tx[$i] || $info_ty[$i + $j] == $info_ty[$i] || $info_tz[$i + $j] == $info_tz[$i])
			{
				$temp_name_same[size($temp_name_same)] = $temp_name_check[$i + $j];
			}
		}	
	}
	select $temp_name_same;
	delete $temp_name_same;
}
