//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: 
//	Created: 
//
//	Description:
//					
//////////////////////////////////////////////////////////


global proc do4_batchRenderLYFilesToolsUI()
{
	python("execfile('//file-cluster/gdc/Resource/Support/Maya/projects/DODIV/append_syspath.py')");
	python("import batch_Rnd_LYFiles_Tools_CMD as brlt");
	python("reload(brlt)");

	//python("import do3_renderToolsUICMDS as drtc");
	//python("import do3_modelAssignLambert as dmal");
	python("brlt.remove_batfile()");
	if (`window -exists batchRenderLYFilesUI`) deleteUI batchRenderLYFilesUI;
	string $window=`loadUI -uiFile "//file-cluster/gdc/Resource/Support/Python/2.6-x64/Lib/site-packages/idmt/maya/DOD/DODIV/batchRenderLYFilesUI.ui"`;
	windowPref  -topLeftCorner 200 150 $window;
	showWindow $window;

	python("brlt.config_brlf_f_ls()");
	
}


