global proc string s100VCRlocateRenderScene()
{
$prePath = `s100VCRlocateRenderSceneFolder `;

string $path = $prePath + "s100VCRtemplateSpriteScene.ma";



return $path ;

}

global proc string s100VCRlocateRenderSceneFolder()
{
global string $base_script_path;
$p = substituteAllString($base_script_path, ";","");
$p = substituteAllString($p, "//","/");

$path = ($p + "/utils/vegetationsTools/S100VCR/s100CVRtemplateSpriteScene/");
return $path ;

}

global proc string s100VCRlocateSpriteRefScene()
{
$prePath = `s100VCRlocateRenderSceneFolder `;
string $path = $prePath + "s100VCRtemplateSpriteSceneToCreateRefScene.ma";

return $path;

}