//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc maCGBGStaticMatte()
{
	editRenderLayerGlobals -crl "defaultRenderLayer";
	
	string $renderLayer[] = `ls -type renderLayer`;
	for ($rl in $renderLayer)
	{
		if (!`referenceQuery -inr $rl` && match("default",$rl)=="")
		{
			delete $rl;
		}
	}

	//初始化节点属性
	string $mats[] = `ls "*:*_blackhole_*" "*_blackhole_*"`;
	for($mat in $mats)
	{
		setAttr ($mat+".input") 0;
	}
}