//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc maCGRepairBtyXtra()
{
	//setAttr "defaultRenderGlobals.imageFormat" 32;
	
	string $mix[] = `ls "*_btyXtra*" "*:*_btyXtra*" "*:*:*_btyXtra*" "*:*:*:*_btyXtra*"`;
	string $BX[]={};
	for ($m in $mix)
	{
		if(objExists($m+".input"))
		{
			string $nodes = `getAttr ($m+".notes ")`;
			if(match("ExtraPass",$nodes)!="")
			{
				$BX[size($BX)]=$m;
			}
		}
	}

	string $renderLayers[] = `ls -type renderLayer "*"`;
	for ($rl in $renderLayers)
	{
		if (match("default",$rl)=="")
		{
			editRenderLayerGlobals -crl $rl;
			for ($m in $BX)
			{
				editRenderLayerAdjustment -layer $rl ($m+".input");
			}
			
			
			if (endsWith($rl,"beauty"))
			{
				for ($m in $BX)
				{
					editRenderLayerGlobals -crl $rl;
					//editRenderLayerAdjustment -layer $rl ($m+".input");
					setAttr ($m+".input") 0;
				}
			}
			else if (endsWith($rl,"xtraPass"))
			{
				for ($m in $BX)
				{
					editRenderLayerGlobals -crl $rl;
					//editRenderLayerAdjustment -layer $rl ($m+".input");
					setAttr ($m+".input") 1;
				}
			}
		}
	}

	maCGMatteOverride {};
}