//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc maRenderingJSNormalMapper()
{
	string $jsn[] = `ls -type "JS_NormalMapper"`;
	for($js in $jsn)
	{
		string $source[] = `listConnections -s 1 -d 0 $js`;
		string $dest[] = `listConnections -s 0 -d 1 -p 1 -c 1 $js`;
		if(size($dest) >= 2)
		{
			string $bump = `shadingNode -asUtility bump2d`;
			disconnectAttr $dest[0] $dest[1];
			if(size($source))
			{
				connectAttr -f ($source[0]+".outAlpha") ($bump+".bumpValue");
			}
			connectAttr -f ($bump+".outNormal") $dest[1];
		}
	}
	select -cl;
}