//作用于MG； FG； BG； Matte  4个sets组
//在各sets组分配正确members后，执行createScrNode_storeSetsMembers()，
//生成scriptNode 节点，保存各sets组信息，在文件load 的时候，正确的分配
//========================create ScriptNode for assignSetsMembers=======================
global proc zbCreateScrNode_storeSetsMembers()
{
if (`objExists "temScript"`)
 delete "temScript";
string $cmd_str = zbAssign_setsMembersCmd("FG") + zbAssign_setsMembersCmd("MG") + zbAssign_setsMembersCmd("BG") + zbAssign_setsMembersCmd("Matte");

string $nodeName =`scriptNode -st 2 -bs $cmd_str -n "temScript"`;
}


//========================get command string=======================================
global proc string zbAssign_setsMembersCmd(string $SetsName)
{
string $sel[] = `sets -q $SetsName`;
string $cmd = "sets -cl " + $SetsName + ";sets -add " +$SetsName +"{";
int $s = `sets -q -s $SetsName`;
if ($s !=0)
    {
    for($n=$s-1;$n>0;$n--)
    {
          
            $cmd  += "\"" + $sel[$n] + "\",";  
    }
    $cmd += "\"" + $sel[0] + "\"};";
    return $cmd;
    }
else
    return "";
}   
