global proc zzjImportRenderCam()
{
	string $longShotName=`file -q -sn `;
	
	string $shortShotName=`match "[^//]*$" $longShotName`;
	if (!`gmatch $shortShotName "lr_E*"`)	return;
	string $shotName[]=stringToStringArray($shortShotName,"_");
	string $cam_name=$shotName[0]+"_"+$shotName[1]+"_"+$shotName[2]+"_"+$shotName[3]+"_cam.ma";

	string $bakedCam[] = `ls -type camera	"*bakedShape" "*:*bakedShape" "*:*:*bakedShape"`;
	if (`size $bakedCam`)
	{
		for ($c in $bakedCam)
		{
			string $bakedCam_splitA[]=stringToStringArray($c,":");
			int $len = `size $bakedCam_splitA`;
			string $tmp=$bakedCam_splitA[$len-1];
			string $bakedCam_split[]=stringToStringArray($tmp,"_");
			
			if ($bakedCam_split[0]==$shotName[2] &&$bakedCam_split[1]==$shotName[3] )
			{
				print "文件中已经存在正确的摄像机";
				nj_ImportRenderCam_RenderableSet($c);
				return;
			}
		}
	}

	
	string $root_path= "//file-cluster/gdc/Projects/LORDoftheRINGS/Project/scenes/Animation";
	string $final_path= $root_path + "/episode_"+$shotName[1]+"/episode_camera/";
	string $file_list[]=`getFileList -fld $final_path -filespec "*.ma" `;
	
//	print $file_list;

	
	int $if_exist_cam = 0;
	for ($cam in $file_list)
	{
		if ($cam == $cam_name)
		{
			$if_exist_cam=1;
			break;
		}	
	}
	
	if ($if_exist_cam ==0 )	
	{warning "没有找到相应的摄像机，请检查maya文件名";	}
	else
	{
		string $cam_path = $final_path + $cam_name;
		file -r -type "mayaAscii" -namespace "CAM"  $cam_path;
		
		string $bakedCam[] = `ls -type camera	"*bakedShape" "*:*bakedShape" "*:*:*bakedShape"`;
		if (`size $bakedCam`)
		{
			for ($c in $bakedCam)
			{
				string $bakedCam_split[]=stringToStringArray($c,"_");
				int $bCS = `size $bakedCam_split`;
				if ($bakedCam_split[$bCS-2]==$shotName[3] &&$bakedCam_split[$bCS-3]==$shotName[2] &&$bakedCam_split[$bCS-4]==$shotName[1])
				{
					nj_ImportRenderCam_RenderableSet($c);
					return;
				}
			}
		}
	}
}

global proc nj_ImportRenderCam_RenderableSet(string $cam)
{
	string $allCam[] = `ls -type camera`;
	for ($c in $allCam)
	{
		if ($c ==$cam)	setAttr ($c+".renderable") 1;
		else setAttr ($c+".renderable") 0;
	}
}