global proc zzjSubstituteHead()
{
	source "channelBoxCommand.mel";
	string $sl[]=`ls -sl`;
	
//	测试是否有低模，是否有高模
	int $lowEnable=0;
	int $highEnable=0;
	int $cacheAEnable=0;
	
	int $lowDel=1;
	int $highDel=1;
	int $cacheADel=1;

	for ($a in $sl)
	{
		select -cl  ;
		select -r $a;
		int $faceCount[]=`polyEvaluate -f`;	
		if ($faceCount[0] ==221 && $lowEnable==0 && `referenceQuery -isNodeReferenced $a`==0)
		{
			string $lowHead[]=`ls "substituteHead_lowHead"`;
			if (`size $lowHead`==0)
			{
				file -import -type "mayaAscii" -rpr "lowHead" -options "v=0"  -pr -loadReferenceDepth "all" "//file-cluster/gdc/Projects/LORDoftheRINGS/LORDoftheRINGS_Scratch/TD/zzj/substituteHead/lowHead.ma";
				$lowEnable=1;							
			}
		}
		
		else if ($faceCount[0] ==678 && $highEnable==0 && `referenceQuery -isNodeReferenced $a`==0)
		{
			string $lowHead[]=`ls "substituteHead_highHead"`;
			if (`size $lowHead`==0)
			{
				file -import -type "mayaAscii" -rpr "highHead" -options "v=0"  -pr -loadReferenceDepth "all" "//file-cluster/gdc/Projects/LORDoftheRINGS/LORDoftheRINGS_Scratch/TD/zzj/substituteHead/highHead.ma";
				$highEnable=1;							
			}
		}	
			
		else if ($faceCount[0] ==542 && $cacheAEnable==0 && `referenceQuery -isNodeReferenced $a`==0)
		{
			string $lowHead[]=`ls "substituteHead_cacheA"`;
			if (`size $lowHead`==0)
			{
				file -import -type "mayaAscii" -rpr "cacheA" -options "v=0"  -pr -loadReferenceDepth "all" "//file-cluster/gdc/Projects/LORDoftheRINGS/LORDoftheRINGS_Scratch/TD/zzj/substituteHead/cacheA.ma";
				$cacheAEnable=1;							
			}
		}			
			
		
	}



	
//	传UV ，附材质
	for ($a in $sl)
	{
		select $a;
		int $faceCount[]=`polyEvaluate -f`;
		
		if ($faceCount[0] ==221 && `referenceQuery -isNodeReferenced $a`==0)
		{		
			//	传UV ,材质
			source "//file-cluster/GDC/Resource/Support/Maya/scripts/zjApplyMaterial.mel";			
			select -cl  ;
			
			select -r substituteHead_lowHead ;
			select -tgl $a;
			TransferUVMatSelProc 1 1;
			
			if (`confirmDialog -title "Confirm" -m "继续吗？" -b "Yes" -b "No" -cb  "No"`=="Yes") 
			{
				select -r $a ;
				instance;
				delete $a ;			
				$lowDel	=0;
			}
		}
		else if ($faceCount[0] ==678 && `referenceQuery -isNodeReferenced $a`==0)
		{
			//	传UV ,材质
			source "//file-cluster/GDC/Resource/Support/Maya/scripts/zjApplyMaterial.mel";			
			select -cl  ;
			select -r substituteHead_highHead ;
			select -tgl $a ;
			TransferUVMatSelProc 1 1;		
				
			select -r $a ;
			instance;
			delete $a ;		
		}
		else if ($faceCount[0] ==542 && `referenceQuery -isNodeReferenced $a`==0)
		{
			//	传UV ,材质
			source "//file-cluster/GDC/Resource/Support/Maya/scripts/zjApplyMaterial.mel";			
			select -cl  ;
			select -r substituteHead_cacheA ;
			select -tgl $a ;
			TransferUVMatSelProc 1 1;		
				
			select -r $a ;
			instance;
			delete $a ;		
		}
		else if ($faceCount[0] ==678 && `referenceQuery -isNodeReferenced $a`==1 && `gmatch $a "*MSH_armet_"`)
		{
			select -cl;
			select -r $a;
			pickWalk -d up;
			pickWalk -d up;
			string $sls[]=`ls -sl`;
			if (`gmatch $sls[0] "*Master"`&&  `attributeExists "armet_vis" $sls[0]`)
			{
				setAttr ($sls[0]+".armet_vis") 0;	
			}
		}
		
		else if ($faceCount[0] ==3122 && `referenceQuery -isNodeReferenced $a`==1 && `gmatch $a "*MSH_armet_"`)
		{
			string $a_split[]=stringToStringArray($a,":");
			string $a_Add="";
			for ($i =0;$i<`size $a_split`-1;$i++ )
			{
				$a_Add+=$a_split[$i];
				$a_Add+=":";
			}
			$a_Add+="MSH_armet__Ctrl";
			
			if (`attributeExists "armet_head_vis" $a_Add`)
			{
				CBdeleteConnection ($a_Add+".armet_head_vis");
				setAttr ($a_Add+".armet_head_vis") 0;	
			}
			if (`attributeExists "armet_palm_vis" $a_Add`)
			{
				CBdeleteConnection ($a_Add+".armet_palm_vis");
				setAttr ($a_Add+".armet_palm_vis") 1;	
			}
			
		}		
		
	}

//	删除模型	
	if (`objExists "substituteHead_lowHead"`&&$lowDel==1)	evalDeferred -lp "delete `ls \"substituteHead_lowHead\"`";
	if (`objExists "substituteHead_highHead"`&&$highDel==1)	evalDeferred -lp "delete `ls \"substituteHead_highHead\"`";
	if (`objExists "substituteHead_cacheA"`&&$cacheADel==1)	evalDeferred -lp "delete `ls \"substituteHead_cacheA\"`";

	select  $sl;

}
