global proc BrAnimationPlaybast()
{
	string $masters[] = `ls "*MASTER" "*:*MASTER" "*:*:*MASTER"`;
	for ($master in $masters)
	{
		if (`objExists ($master+".skeleton_vis")`)
		{
			setAttr ($master+".skeleton_vis") 1;
			setAttr ($master+".skinning_vis") 1;
			setAttr ($master+".skinProxy_vis") 0;
		}
	}
	
	string $skeleton[] =`ls -type displayLayer "*:*_*keleton" "*_*keleton"`;
	string $skin[] = `ls -type displayLayer "*:*_*kin" "*:*_*KIN" "*:*_*kinning" "*_*kin" "*_*KIN" "*_*kinning"`;
	string $skinproxy[] = `ls -type displayLayer "*:*_*kin*roxy" "*_*kin*roxy"`;
	for ($i=0;$i<size($skeleton);$i++)  
	{
		setAttr ( $skeleton[$i]+ ".v" ) 1;
		setAttr ( $skin[$i]+ ".v" ) 1;
		setAttr ( $skinproxy[$i]+ ".v" ) 0;
	}
	
	setNamedPanelLayout "Single Perspective View";
	string $modelPanel_ld = `getPanel -withFocus`;  
	string $camera_ld = `modelEditor -query -camera $modelPanel_ld`; 
	string $came_ld[] = `ls -ca "cam*" "CAM*"`;  
	lookThroughModelPanel $came_ld[0] $modelPanel_ld;
	select -cl;
	modelEditor -e -allObjects 0 $modelPanel_ld;
	modelEditor -e -nurbsSurfaces 1 $modelPanel_ld;
	modelEditor -e -polymeshes 1 $modelPanel_ld;
	performPlayblast 3;
}