proc string hjnamespace(string $name)
{
	
	string $hjnamelist[];
	string $hjnametest=`tokenize $name ":" $hjnamelist`;
	if(`size $hjnamelist`)
	{
	int    $hjsize=`size $hjnamelist`-1;
	
	for($i=0;$i<$hjsize;$i++)
	{
		string $hjnamels =$hjnamels+$hjnamelist[$i]+":";
	
		if($i==$hjsize-1)
		{
		return $hjnamels;
		
		}
	}
	}
    return "";
	
	
}

proc string hjnamegrb(string $names)
{
	
	string $hjnamelist[];
	string $hjnametest=`tokenize $names ":" $hjnamelist`;
	int    $hjsize=`size $hjnamelist`-1;
	
	string $hjgrp[];
	string $hjgrpname=`tokenize $hjnamelist[$hjsize] "_" $hjgrp`;
    int    $hjsizegrp=`size $hjgrp`-1;
	
	
	for($j=0;$j<$hjsizegrp;$j++ )
	{
		string $hjnamels =$hjnamels+$hjgrp[$j]+"_";
	           
	    if($j==$hjsizegrp-1)
		{
	    return $hjnamels;
		}
		
		
	}
	
	
}

global proc hjHairRefFile()
{
string 		$g[] = `ls -sl "*MASTER*" "*:*MASTER*" "*:*:*MASTER*" "*GRP*" "*:*GRP*" "*:*:*GRP*"`;
string 		$tem[];
tokenize 	$g[0] "MASTER" $tem;
string 		$hjhairname[]=`listRelatives -children $g[1]`;
string      $hjgrpname=`hjnamespace $hjhairname[0]`+`hjnamegrb $hjhairname[0]`;
            
//print 		$hjgrpname;
//string 		$hjhairlist[];
//tokenize 	$hjhairname[0] "_" $hjhairlist;
string 		$chaName=$tem[0];
string 		$hjName=$hjgrpname;

string $jointName[10]   = {($chaName + "pelvis") ,  
				($chaName + "chestA") ,   
				($chaName + "neckA") ,    
				($chaName + "head") ,     
				($chaName + "arm_left") ,    
				($chaName + "elbow_left") ,  
				($chaName + "arm_right") ,    
				($chaName + "elbow_right") ,  
				($chaName + "leg_left") ,    
				($chaName + "leg_right")};     
string $collideName[10]  = {($hjName+"root") , 
				($hjName+"spine") , 
				($hjName+"neck" ), 
				($hjName+"head") , 
				($hjName+"armLeft") ,
				($hjName+"elbowLeft") , 
				($hjName+"armRight") , 
				($hjName+"elbowRight") , 
				($hjName+"hipLeft") , 
				($hjName+"hipRight")};
for ($i = 0; $i<size($jointName); $i++)
		
{
	scaleConstraint -mo -weight 1 $jointName[$i] $collideName[$i];
	parentConstraint -mo -weight 1 $jointName[$i] $collideName[$i];

}

        
}

