global proc slAnimAddNosieLayout()
{
	if(`window -exists slAnimAddNosie`)
		deleteUI slAnimAddNosie;
	window -title "Add Noise" -mb true -s false slAnimAddNosie;
		menu -label "Help";
			menuItem -label "Help on Add Noise..." -command "zjHelpCallback slAddNoise";

		columnLayout -adjustableColumn true -rs 5;
			text -label "请选择需要添加noise的物体";
			textFieldGrp -label "Noise 强度:" -text 1 -cw2 100 100 intensity;
			textFieldGrp -label "Noise 频率:" -text 6 -cw2 100 100 frequency;
			checkBoxGrp	-ncb 3 -label "Noise 类型:" -labelArray3 "前后" "上下" "旋转" -v1 1 -v2 1 -v3 1 -cw4 100 50 50 50 style;
			button -label "添加 noise" -h 30 -command ("slAnimAddNosie");
			//button -label "删除 noise" -command ("");
		setParent ..;
	window -e -h 180 -w 300 slAnimAddNosie;
	showWindow slAnimAddNosie;
}


global proc slAnimAddNosie()
{
	string $object[] = `ls -sl`;
	if (!`objExists $object[0]`)
		error "!";
	string $parent[] = `listRelatives -p $object[0]`;
	if ($parent[0] !=  "noiseGroup" && $object[0] != "noiseGroup")
		group -n noiseGroup $object;
	
	cutKey -cl -t ":" -f ":" -at "tx" -at "ty" -at "tz" -at "rx" -at "ry" -at "rz" noiseGroup;
	
	string $ins = `textFieldGrp -q -text intensity`;
	string $fre = `textFieldGrp -q -text frequency`;
	int $type1 = `checkBoxGrp -q -v1 style`;
	int $type2 = `checkBoxGrp -q -v2 style`;
	int $type3 = `checkBoxGrp -q -v3 style`;

	int $sf = `playbackOptions -q -min`;
	int $ef = `playbackOptions -q -max`;

	for ($i=$sf; ;)
	{
		float $value = 0.5 ; //0.1*(float)$ins*(noise($i*rand(5)));
		if ($type1)
		{	
			setKeyframe  -t $i -v ($value*(float)$ins*(noise($i*rand(5)))) noiseGroup.tz;
		}
		if ($type2)
			setKeyframe  -t $i -v ($value*(float)$ins*(noise($i*rand(5)))) noiseGroup.ty;
		if ($type3)
		{
			setKeyframe  -t $i -v ($value*(float)$ins*(noise($i*rand(5)))) noiseGroup.rx;
			setKeyframe  -t $i -v ($value*(float)$ins*(noise($i*rand(5)))) noiseGroup.ry;
			setKeyframe  -t $i -v ($value*(float)$ins*(noise($i*rand(5)))) noiseGroup.rz;
		}
		
		if ($i>$ef)	break;
		$i = $i + (float)$fre;
	}
	select -r noiseGroup;
}