/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: ÕÚ Ÿ¡˙
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc string slBrGetChar()
{
	string $sl[]=`ls -sl`;
	if (!`objExists $sl[0]`)
		error "«Î—°‘ÒΩ«…´MASTER!";
	string $buffer1[],$buffer2[];
	string $char;
	
	tokenize $sl[0] ":" $buffer1;
	
	if (`size $buffer1`==2)
	{
		tokenize $buffer1[1] "_" $buffer2;
		$char = $buffer1[0] + ":" + $buffer2[0];
	}
	else if (`size $buffer1`==1)
	{
		tokenize $buffer1[0] "_" $buffer2;
		$char = $buffer2[0];
	}
	return $char;
}


global proc slBrEyesBlink()
{
	if(`window -exists br_eyesblink`)
		deleteUI br_eyesblink;
	window -title "Eyes Blink"   -resizeToFitChildren true br_eyesblink;

		string $form = `formLayout`;
				
//			intSliderGrp -field true -l "Offset"  -columnWidth 1 110 -columnWidth 2 60 -min 0 -max 20  -v 0 _Offest_Char;
			button -l "SetBlink" -w 80 -command "slBrSetBlink"  _SetBlink;
			button -l "CleanBlink" -w 80 -command "slBrCleanBlink" _CleanBlink;
			formLayout -edit
				-attachForm	_SetBlink                                               "bottom"	10
				-attachForm	_SetBlink 						"left"		10
				-attachPosition _SetBlink						"right"		0	50
				-attachForm	_CleanBlink                                              "bottom"	10
				-attachControl  _CleanBlink 						 "left"		5	_SetBlink
				-attachPosition _CleanBlink						 "right"	0	100
			$form;	
			

	showWindow br_eyesblink;
}

global proc slBrSetBlink()
{
//	string $char=`slBrGetChar`;
//	int $offset=`intSliderGrp -q -v _Offest_Char`;
	int $sFrame=`currentTime -q`;
	int $mFrame=$sFrame + 2;
	int $eFrame=$mFrame + 3;
	SetBlink ($sFrame,$mFrame,$eFrame);

}

global proc SetBlink(int $sFrame,int $mFrame,int $eFrame)
{
	string $char=`slBrGetChar`;
	string $RightEyes= ($char+"_Ctrl_R_Lids");
	string $LeftEyes= ($char+"_Ctrl_L_Lids");
	float $rt=`getAttr ($RightEyes+".translateY")`;
	float $lf=`getAttr ($LeftEyes+".translateY")`;

	setKeyframe -v $rt	-t $sFrame	-itt clamped	-ott clamped	-at "translateY"	$RightEyes;
	setKeyframe -v -1	-t $mFrame	-itt clamped	-ott clamped	-at "translateY"	$RightEyes;
	setKeyframe -v $rt	-t $eFrame	-itt clamped	-ott clamped	-at "translateY"	$RightEyes;

	setKeyframe -v $lf	-t $sFrame	-itt clamped	-ott clamped    -at "translateY"	$LeftEyes;
	setKeyframe -v -1	-t $mFrame	-itt clamped	-ott clamped    -at "translateY"	$LeftEyes;
	setKeyframe -v $lf	-t $eFrame	-itt clamped	-ott clamped    -at "translateY"	$LeftEyes;

}


global proc slBrCleanBlink()
{
	string $char=`slBrGetChar`;

	string $delete=`confirmDialog -title "warning" -message "This is delete all keyframe for eyes.YES to continue ,NO to back."
			-button "YES" -button "NO"  -defaultButton "NO" -cancelButton "No" -dismissString "No" `;
	
	
	if ($delete == "YES")
	{
		string $charCurve[]=`keyframe -q -name ($char+"_Ctrl_R_Lids.ty")`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
		}
		setAttr ($char+"_Ctrl_R_Lids.ty") 0;	
		
		string $charCurve[]=`keyframe -q -name ($char+"_Ctrl_L_Lids.ty")`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
		}
		setAttr ($char+"_Ctrl_L_Lids.ty") 0;	
	}
}




slBrEyesBlink;

