/// Copyright (C) 2000-2005 IDMT. All rights reserved.
///
/// Author: 万寿龙
///
/// Creation Date: 2006/11/15
///
/// Description: 
///


global proc string getChar()
{
	string $char[]=`ls -sl "*:*MASTER" "*MASTER"`;
		if (!`objExists $char[0]`)
		{
			error "请选择角色MASTER";
		}
	string $buffer[];
	tokenize $char[0] "_" $buffer;
	string $charName=$buffer[0];
		for ($i=1;$i<`size($buffer)`-1 ;$i++ )
		{
			$charName += "_" + $buffer[$i];
		}
	return $charName;
}

global proc slBrWings()
{
	if(`window -exists w_BrWings`)
		deleteUI w_BrWings;
	window -title "Wings"   -resizeToFitChildren true w_BrWings;

		string $form = `formLayout`;
				
			intSliderGrp -field true -l "Wings Duration" -columnWidth 1 110 -columnWidth 2 60 -min 3 -max 24  -v 12  _Length_Wings;
			intSliderGrp -field true -l "Wave" -columnWidth 1 110 -columnWidth 2 60 -min 1 -max 12  -v 3  _Wave;
			floatSliderGrp -field true -l "Min Angle"  -columnWidth 1 110 -columnWidth 2 60 -min 0 -max 60  -v 0   _MinAngle;
			floatSliderGrp -field true -l "Max Angle"  -columnWidth 1 110 -columnWidth 2 60 -min 0 -max 60  -v 60   _MaxAngle;
			intSliderGrp -field true -l "Circle"  -columnWidth 1 110 -columnWidth 2 60 -min 0 -max 80  -v 10 _Circle_Char;
			button -l "SetWings" -w 80 -command "br_SetWings"  _SetWings;
			button -l "CleanWings" -w 80 -command "br_CleanWings" _CleanWings;
			formLayout -edit
				-attachForm	_Length_Wings			       			"top"	5
				-attachForm	_Length_Wings						"left"	5
				-attachControl	_Wave							"top"	5	_Length_Wings				
				-attachForm	_Wave			      				"left"	5
				-attachControl	_MinAngle						"top"	5	_Wave				
				-attachForm	_MinAngle			      			"left"	5
				-attachControl	_MaxAngle						"top"	5	_MinAngle				
				-attachForm	_MaxAngle			      			"left"	5
				-attachControl	_Circle_Char						"top"	5	_MaxAngle				
				-attachForm	_Circle_Char			      			"left"	5
				-attachForm	_SetWings                                               "bottom"	10
				-attachForm	_SetWings 						"left"		10
				-attachPosition _SetWings						"right"		0	50
				-attachForm	_CleanWings                                              "bottom"	10
				-attachControl  _CleanWings 						 "left"		5	_SetWings
				-attachPosition _CleanWings						 "right"	0	100
			$form;	
	showWindow w_BrWings;
}

global proc br_SetWings()
{
	string $char=`getChar`;
	int $duration=`intSliderGrp -q -v _Length_Wings`;
	int $sFrame=`currentTime -q`;
	int $mFrame=$sFrame + $duration/2;
	int $eFrame=$sFrame + ($duration-1);
	if (`objExists ($char+"_wing1_l")`)
	{
		setWings1 ($sFrame,$mFrame,$eFrame,$duration);
	}
	else if (`objExists ($char+"_wingA_ani_0_l")`)
	{
		setWings2 ($sFrame,$mFrame,$eFrame,$duration);
	}
}

global proc setWings1(int $sFrame,int $mFrame,int $eFrame,int $duration)
{
	int $time=0;
	int $circle=`intSliderGrp -q -v _Circle_Char`;
	string $char=`getChar`;
	float  $min=-1*`floatSliderGrp -q -v _MinAngle`;
	float  $max=-1*`floatSliderGrp -q -v _MaxAngle`;
	int $wave=`intSliderGrp -q -v _Wave`;
	
	string $con1=$char+"_wing2_l.ry";
	string $charCurve[]=`keyframe -q -name $con1`;
	if (`objExists $charCurve[0]`)
	{
		$time=`selectKey -add -k -t (($sFrame+1)+":") $con1`;
	}

	for ($i=0;$i<($circle+1) ;$i++ )
	{
		setKeyframe -v ($min*0.9) -t ($sFrame+$i*($duration-1))  $con1;
		if ($time==1)
		{
			selectKey  -cl;
			selectKey -add -k -t (($sFrame+1)+":") $con1;
			cutKey -clear ;
			$time=0;
		}
		setKeyframe -v ($max*0.9) -t ($mFrame+$i*($duration-1))  $con1;
		setKeyframe -v ($min*0.9) -t ($eFrame+$i*($duration-1))  $con1;
	}
	string $con1Curve[]=`keyframe -q -name $con1`;
	keyTangent -e -itt flat -ott flat $con1Curve;

	
	
	
	string $con2=$char+"_wing1_l.ry";
	string $charCurve[]=`keyframe -q -name $con2`;
	if (`objExists $charCurve[0]`)
	{
		$time=`selectKey -add -k -t (($sFrame+1)+":") $con2`;
	}

	for ($i=0;$i<($circle+1) ;$i++ )
	{
		setKeyframe -v $min -t (($sFrame+$wave)+$i*($duration-1))  $con2;
		if ($time==1)
		{
			selectKey  -cl;
			selectKey -add -k -t ((($sFrame+$wave)+1)+":") $con2;
			cutKey -clear ;
			$time=0;
		}
		setKeyframe -v $max -t (($mFrame+$wave)+$i*($duration-1))  $con2;
		setKeyframe -v $min -t (($eFrame+$wave)+$i*($duration-1))  $con2;
	}
	string $con2Curve[]=`keyframe -q -name $con2`;
	keyTangent -e -itt flat -ott flat $con2Curve;
	print "OK";
	
}


global proc setWings2(int $sFrame,int $mFrame,int $eFrame,int $duration)
{
	int $time=0;
	int $circle=`intSliderGrp -q -v _Circle_Char`;
	string $char=`getChar`;
	float  $min=-1*`floatSliderGrp -q -v _MinAngle`;
	float  $max=-1*`floatSliderGrp -q -v _MaxAngle`;
	int $wave=`intSliderGrp -q -v _Wave`;
	
	string $con1=$char+"_wingA_ani_0_l.ry";
	string $charCurve[]=`keyframe -q -name $con1`;
	if (`objExists $charCurve[0]`)
	{
		$time=`selectKey -add -k -t (($sFrame+1)+":") $con1`;
	}

	for ($i=0;$i<($circle+1) ;$i++ )
	{
		setKeyframe -v $min -t ($sFrame+$i*($duration-1))  $con1;
		if ($time==1)
		{
			selectKey  -cl;
			selectKey -add -k -t (($sFrame+1)+":") $con1;
			cutKey -clear ;
			$time=0;
		}
		setKeyframe -v $max -t ($mFrame+$i*($duration-1))  $con1;
		setKeyframe -v $min -t ($eFrame+$i*($duration-1))  $con1;
	}
	string $con1Curve[]=`keyframe -q -name $con1`;
	keyTangent -e -itt flat -ott flat $con1Curve;

	
	
	
	string $con2=$char+"_wingB_ani_0_l.ry";
	string $charCurve[]=`keyframe -q -name $con2`;
	if (`objExists $charCurve[0]`)
	{
		$time=`selectKey -add -k -t (($sFrame+1)+":") $con2`;
	}

	for ($i=0;$i<($circle+1) ;$i++ )
	{
		setKeyframe -v ($min*0.5) -t (($sFrame+$wave)+$i*($duration-1))  $con2;
		if ($time==1)
		{
			selectKey  -cl;
			selectKey -add -k -t ((($sFrame+$wave)+1)+":") $con2;
			cutKey -clear ;
			$time=0;
		}
		setKeyframe -v ($max*0.5) -t (($mFrame+$wave)+$i*($duration-1))  $con2;
		setKeyframe -v ($min*0.5) -t (($eFrame+$wave)+$i*($duration-1))  $con2;
	}
	string $con2Curve[]=`keyframe -q -name $con2`;
	keyTangent -e -itt flat -ott flat $con2Curve;
	
	
	
	string $con3=$char+"_wingC_ani_0_l.ry";
	string $charCurve[]=`keyframe -q -name $con3`;
	if (`objExists $charCurve[0]`)
	{
		$time=`selectKey -add -k -t (($sFrame+1)+":") $con3`;
	}

	for ($i=0;$i<($circle+1) ;$i++ )
	{
		setKeyframe -v ($min/3) -t (($sFrame+$wave*2)+$i*($duration-1))  $con3;
		if ($time==1)
		{
			selectKey  -cl;
			selectKey -add -k -t ((($sFrame+$wave*2)+1)+":") $con3;
			cutKey -clear ;
			$time=0;
		}
		setKeyframe -v ($max/3) -t (($mFrame+$wave*2)+$i*($duration-1))  $con3;
		setKeyframe -v ($min/3) -t (($eFrame+$wave*2)+$i*($duration-1))  $con3;
	}
	string $con3Curve[]=`keyframe -q -name $con3`;
	keyTangent -e -itt flat -ott flat $con3Curve;
	print "OK";
}

global proc br_CleanWings()
{
	string $char=`getChar`;
	if (`objExists ($char+"_wing1_l")`)
	{
		CleanWings1;
	}
	else if (`objExists ($char+"_wingA_ani_0_l")`)
	{
		CleanWings2;
	}
}

global proc CleanWings1()
{
	string $char=`getChar`;
	string $con1=$char+"_wing1_l.ry";
	string $con2=$char+"_wing2_l.ry";

	string $delete=`confirmDialog -title "warning" -message "删除所有Wings关键帧点YES，否则点NO"
			-button "YES" -button "NO"  -defaultButton "NO" -cancelButton "No" -dismissString "No" `;
	
	
	if ($delete == "YES")
	{
		string $charCurve[]=`keyframe -q -name $con1`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
			setKeyframe -t -31 -t 0 -t 43 -v 0 $con1;
		}
		
		string $charCurve[]=`keyframe -q -name $con2`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
			setKeyframe -t -31 -t 0 -t 43 -v 0 $con2;
		}
		
	}
}


global proc CleanWings2()
{
	string $char=`getChar`;
	string $con1=$char+"_wingA_ani_0_l.ry";
	string $con2=$char+"_wingB_ani_0_l.ry";
	string $con3=$char+"_wingC_ani_0_l.ry";

	string $delete=`confirmDialog -title "warning" -message "删除所有Wings关键帧点YES，否则点NO"
			-button "YES" -button "NO"  -defaultButton "NO" -cancelButton "No" -dismissString "No" `;
	
	
	if ($delete == "YES")
	{
		string $charCurve[]=`keyframe -q -name $con1`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
			setKeyframe -t -31 -t 0 -t 43 -v 0 $con1;
		}
		
		string $charCurve[]=`keyframe -q -name $con2`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
			setKeyframe -t -31 -t 0 -t 43 -v 0 $con2;
		}
		
		string $charCurve[]=`keyframe -q -name $con3`;
		if (`objExists $charCurve[0]`)
		{
			delete $charCurve;
			setKeyframe -t -31 -t 0 -t 43 -v 0 $con3;
		}

	}
}
