global proc slEffectKeyInitialization()
{
	string $masters[] = `ls -sl`;
	if (!`objExists $masters[0]`)
		error "请选择角色MASTER！";
	
	for ($master in $masters)
	{
		currentTime 43;
		setKeyframe -time 0  -shape 1 $master;
		setKeyframe -time 43  -shape 1 $master;
		
		string $upper = `substitute "_MASTER" $master "_Upper_Body"`;
		if (!`objExists $upper`)
			$upper = `substitute "_MASTER" $master "_upperBodyCon"`;
		setKeyframe -time 0  -shape 1 $upper;
		setKeyframe -time 43  -shape 1 $upper;

		string $footLeft = `substitute "_MASTER" $master "_footCon_left"`;
		setKeyframe -time 0  -shape 1 $footLeft;
		setKeyframe -time 43  -shape 1 $footLeft;

		string $footRight = `substitute "_MASTER" $master "_footCon_right"`;
		setKeyframe -time 0  -shape 1 $footRight;
		setKeyframe -time 43  -shape 1 $footRight;
		
		string $set = `substitute "_MASTER" $master "_set"`	;
		if (!`objExists $set`)
			error "角色SET名字不正确！";
		string $obj[]=`sets -q -nodesOnly $set`;
		string $items[] = stringArrayRemove({$master,$upper,$footLeft,$footRight},$obj);
		
		currentTime 0;
		select -r $master;
		source "slResetPose.mel";slResetPose;
		setKeyframe -time 0 -shape 1 $items;
	}
}