global proc float RZcurveGetLength(string $curve)
{
/*
$curve = "VRGR_stern01_curv" ;
*/

	float $arc = `arclen -ch 0 $curve`;
	return $arc;


}



global proc float RZgetClosestLengthValueFromAObject(string $curveC, string $curveP)
{
/*
$curveC = "VRGR_leaf01_curv" ;
$curveP = "VRGR_stern01_curv" ;
*/
$poc = `createNode pointOnCurveInfo`;
connectAttr -f  ($curveC +".worldSpace") ($poc +".inputCurve");
$cls = `createNode closestPointOnSurface`;
$dup = `duplicate  -renameChildren -name "dupA" $curveP ` ;
setAttr -l 0 ($dup[0] +".tx") ;
setAttr ($dup[0] +".tx") 100 ;

$dup2 = `duplicate -renameChildren   -name "dupB" $curveP` ;
$loft = `loft -n "loftDup" $dup $dup2 `;
$list = `listRelatives -shapes $loft` ;

connectAttr -f ($list[0] +".worldSpace[0]") ($cls +".inputSurface") ;
connectAttr -f ($poc +".result.position") ($cls +".inPosition") ;
float $return = `getAttr ($cls +".parameterV")`;
delete $cls $poc $dup $dup2 $loft ;
$arcN = `arcLengthDimension  ($curveP +".u[" + $return +"]")`;

float $get = `getAttr ($arcN +".arcLength")`;
$listP = `listRelatives -p $arcN` ;
delete $listP ;
return $get ;
}

