global proc RZVRrefreshValueSelected()
{
string $all[] = `VRGRUIGetSelCol` ;
float $vAuto = 1;
float $vAnim = 0;


	if(size($all ) > 0 )
	{

	float $vAutoT = 0  ;
	float $vAnimT = 0 ;
	$j = 0 ;
		for($i = 0 ; $i < size($all) ; $i++ )
		{
		$vAutoT += `getAttr ($all[$i] + ".autoAnim")`;
		$vAnimT += `getAttr ($all[$i] + ".forceAnim")`;
		$j++ ;

        }


		$vAuto = $vAutoT / $j ;
		$vAnim = $vAnimT / $j ;



	floatSliderGrp -e -v $vAuto  RZVRGRFAA;
	floatSliderGrp -e -v $vAnim RZVRGRFFA;
		if(size($all ) > 1 )
		{


		text -e -l "Automatic*:" RZVRAutoT;
		text -e -l "Force*:" RZVRAnimT ;

		}else{

		text -e -l "Automatic:" RZVRAutoT;
		text -e -l "Force:" RZVRAnimT ;

        }


    }








}