//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc ydAnimExportCam()
{
	string $filename = `file -q -sn -shn`;
	string $buff[]=stringToStringArray($filename,"_");
	string $dir = "D:/YODA/"+$buff[0]+"/"+$buff[1];
	sysFile -md $dir;
	
	
	string $camer[]  =`ls -type camera "Q*_S*"`;
	for ($cam in $camer)
	{
		string $trans[] = `listRelatives -f -p $cam`;
		clear $buff;
		$buff = stringToStringArray($trans[0],"|");
		select -r $trans;
		file -force -options "v=0" -typ "mayaAscii" -pr -es ($dir+"/"+$buff[size($buff)-1]);
	}
	select -cl;
}