global proc ghl_createPro()
{
string $group_PRO=`group -em`;
xform -os -piv 0 0 0;
$group_PRO=`rename $group_PRO "Pro"`;
string $group_RIG=`group -em`;
xform -os -piv 0 0 0;
$group_RIG=`rename $group_RIG "RIG"`; 

string $group_MODEL=`group -em`;
xform -os -piv 0 0 0;
$group_MODEL=`rename $group_MODEL "MODEL"`; 

string $group_deformers=`group -em`;
xform -os -piv 0 0 0;
$group_deformers=`rename $group_deformers "DEFORMERS"`; 

string $group_MASTER_GRP=`group -em`;
xform -os -piv 0 0 0;
$group_MASTER_GRP=`rename $group_MASTER_GRP "Master_GRP"`; 
//
string $circle[]=`circle -c 0 0 0 -nr 0 1 0 -sw 360 -r 1 -d 3 -ut 0 -tol 0.01 -s 8 -ch 1`;
scale -r 6 6 6 ;
DeleteHistory;
makeIdentity -apply true -t 1 -r 1 -s 1 -n 0;
//
string $master=`rename $circle[0] "Master"`;
setAttr ($master+"Shape.overrideEnabled") 1;
setAttr ($master+"Shape.overrideColor") 13;
//

parent  $master $group_MASTER_GRP;
parent  $group_MASTER_GRP $group_RIG ;

parent  $group_RIG  $group_PRO;
parent  $group_MODEL $group_PRO;
parent $group_deformers $group_PRO;
}
