 //s100PCUIRefreshScroll(150) ;
global proc s100PCUIRefreshScroll(int $h)
{
$h = 200 ;
string $child[] = `gridLayout -q -childArray   s100PCUIFLLightMSLCL `;

	for($tmp in $child)
	{
	deleteUI $tmp ;
    }



$fTest= `s100VSMlocateRenderSceneFolder` ;

	$pathImage = `s100VSMlocateImageFolder `;
	string $images[] = `getFileList -folder  $pathImage -filespec "*.bmp" `;
	$pathPreset = `s100VSMlocatePresetFolder `;


	for($i = 0 ; $i < size($images) ; $i++)
	{
    $sub = substituteAllString($images[$i] , ".bmp", ".vsmp") ;

		if(`filetest -e ($pathPreset + $sub)` )
		{
		$subN =substituteAllString($images[$i],".bmp","");
		iconTextButton  -imageOverlayLabel $subN -p s100PCUIFLLightMSLCL -c ("s100PCLoadTemplate(\""+$subN+"\")")  -w 120  -h 140 -i ($pathImage +$images[$i])	;

        }else{
		warning ("preset " + $sub + " does not exist ! " ) ;
        }
	}

gridLayout -e -h 300 s100PCUIFLLightMSLCL ;
scrollLayout -e  -h $h  s100PCUIFLLightMSL ;
gridLayout -e -h 300 s100PCUIFLLightMSLCL ;

scrollLayout -e  -h $h  s100PCUIFLLightMSL ;
}


global proc  s100PCLoadTemplate(string $name)
{
//$name = "Day" ;
$pathPreset = `s100VSMlocatePresetFolder `;

$pr = $pathPreset + $name +".vsmp" ;
$vers = `s100returnDifferentAttributForLightAmbiance`;
//$name = "Day" ;
string $value[] = s100VSMreadPresetFile($name) ;
$ch = `filetest -e $pr ` ;

string $passes[] = `s100PCgetAllLights`;

				if($ch == 1 )
				{
					for($i = 0 ; $i < size($vers) ; $i++)
					{
					//print $i ;

					if(`gmatch $vers[$i] "sunDirection*"`)
						{
							for($j = 0 ; $j < size($passes) ; $j++)
							{
							float $tm ;
							$tm = $value[$i]  ;
								if(`gmatch $passes[$j] "sunDirection*"`)
								{
								string $Arra[] = stringToStringArray($vers[$i] ,"." ) ;
								string $lights[] = `listRelatives -s $passes[$j] `;
								$tm = $value[$i]  ;


       							$vers[$i] = $lights[0] +"."+$Arra[1];
                        		}


							setAttr $vers[$i] $tm ;
                            }


                        }


					}
					print "\preset Apply";

				}


string $lightCh[] = `ls -type "light" "*Chara*" `;
	for($tmp in $lightCh)
	{
	float $get = `getAttr ($tmp +".intensity") ` 	;
	$get /= 7 ;
	setAttr ($tmp +".intensity") $get;


    }



}
