global proc s100FAMprePublishAction()
{
	s100SPUnSmoothAll;
	s100wireframe;

	s100_unlockCurrentScene;

	//Unlocking nodes, problem for maya ascii 2010

	string $ln[] = {"defaultObjectSet","time1","renderPartition","renderGlobalsList1","defaultShaderList1","postProcessList1","initialShadingGroup","initialParticleSE","defaultLightSet","defaultHardwareRenderGlobals"};
	for($i in $ln)
	{
		lockNode -lock false $i;
	}

	//check si le fichier est un character
/*	string $file = `file -q -sceneName -shortName` ;
	if(`gmatch $file "*_C_*"`)
		s100AsModCreateFacialCam ;
*/
}

global proc s100FAMprePublishActionShot()
{
	//python("import s100API.performing as _perf");
	//python("_perf.set_tkVersion()");
	//s100SPUnSmoothAll;
	s100wireframe;
	s100_unlockCurrentScene;
}


global proc s100wireframe()
{
	string $modelPanels[] = `getPanel -type "modelPanel"`;

	for ($pane in $modelPanels){
		$modEd = `modelPanel -q -modelEditor $pane`;
		modelEditor -e -displayAppearance "wireframe" $modEd;
	}
}