global proc AEp_float2_to_vectorTemplate( string $nodeName )
{
	AEswatchDisplay $nodeName;
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout "Main" -collapse 0;
			editorTemplate -label "Input U" -addControl "input_U";
			editorTemplate -label "Input V" -addControl "input_V";
		editorTemplate -endLayout;

		AEdependNodeTemplate $nodeName;
		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
