global proc AEdie_int_modeNew( string $mod )
{
      attrEnumOptionMenuGrp
              -l "Object Mode:"
              -at $mod
              -ei 0 "TAG"
              -ei 1 "Name"
              -ei 2 "Label"
	die_int_mode;
}

global proc AEdie_int_modeReplace( string $mod )
{
  attrEnumOptionMenuGrp -e -at $mod die_int_mode;
}

global proc AEp_dielectric_interfaceTemplate( string $nodeName )
{
	AEswatchDisplay $nodeName;
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout "Main" -collapse 0;

			editorTemplate -label "Glass Material" -addControl "glass_mat";
			editorTemplate -label "Liquid Material" -addControl "liquid_mat";
			editorTemplate -label "Interface Material" -addControl "interface_mat";
			editorTemplate -addSeparator;
			editorTemplate -callCustom "AEdie_int_modeNew" "AEdie_int_modeReplace" "object_mode";
			editorTemplate -addSeparator;
			editorTemplate -label "Glass Name" -addControl "glass_name";
			editorTemplate -label "Liquid Name" -addControl "liquid_name";
			editorTemplate -addSeparator;
			editorTemplate -label "Glass Object" -addControl "glass_object";
			editorTemplate -label "Liquid Object" -addControl "liquid_object";
			editorTemplate -addSeparator;
			editorTemplate -label "Glass Label" -addControl "glass_label";
			editorTemplate -label "Liquid Label" -addControl "liquid_label";
			editorTemplate -addSeparator;			
			editorTemplate -label "Check Camera" -addControl "check_camera";
		editorTemplate -endLayout;
		
		editorTemplate -suppress "object_mode";

		AEdependNodeTemplate $nodeName;
		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
