global proc AEp_facing_ratioTemplate( string $nodeName )
{
	AEswatchDisplay $nodeName;
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout "Main" -collapse 0;
			editorTemplate -label "Color 1" -addControl "color1";
			editorTemplate -label "Color 2" -addControl "color2";
			editorTemplate -label "Gamma" -addControl "interpolation";
		editorTemplate -endLayout;

		AEdependNodeTemplate $nodeName;
		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}