
global proc s100VRGiveValueToAttrFromGradientOverLap()
{

s100VRGiveValueToAttrFromGradient("s100VRfalloffCurve2") ;
}

global proc s100VRGiveValueToAttrFromGradientAmp()
{

s100VRGiveValueToAttrFromGradient("s100VRfalloffCurve") ;
}

global proc s100VRGiveValueToAttrFromGradient(string $gradient)
{
/*
$gradient = "s100VRfalloffCurve2" ;
*/


string $attr ;
	if ($gradient == "s100VRfalloffCurve2")
	{
	$attr = "overLap";
	}else{
	$attr = "amplitude";

	}

$ob = `	textScrollList -q -selectItem s100VRAElistObject `;

string $var[] = `ls ("VR_" + $ob[0] + "*_wGrp")`;
float $iF ;
float $sF = size($var) ;
//print $var;
//print "\n\n\n\n";
	for ($i = 1 ; $i < size($var) + 1 ; $i++)
	{
	$iF = $i ;
	float $toGet = $iF  / $sF ;
	//gradientControlNoAttr  -e -currentKey .5 $gradient ;
	float $val = `gradientControlNoAttr  -vap $toGet -q $gradient `;
	$j = $i - 1 ;
	setAttr ($var[$j] +"." + $attr ) $val ;
	//print ("\n var :" + $var[$i] + "\n $val : " +$val ) ;
	//print $toGet;
	//$i++ ;

    }


}
