## +
## ===================================================================
## Copyright(C) 2010 - 2011 Basefount Technology (Hong Kong) Limited.
## and/or its licensors.  All rights reserved.
##
## The coded instructions, statements, computer programs, and/or
## related material (collectively the "Data") in these files contain
## unpublished information proprietary to Basefount Technology
## (Hong Kong) Limitd. ("Basefount") and/or its licensors, which is
## protected by Hong Kong copyright law and by international treaties.
##
## The Data is provided for use exclusively by You. You have the right 
## to use, modify, and incorporate this Data into other products for 
## purposes authorized by the Basefount software license agreement, 
## without fee.
##
## The copyright notices in the Software and this entire statement, 
## including the above license grant, this restriction and the 
## following disclaimer, must be included in all copies of the 
## Software, in whole or in part, and all derivative works of 
## the Software, unless such copies or derivative works are solely 
## in the form of machine-executable object code generated by a 
## source language processor.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. 
## BASEFOUNT DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR
## IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES
## OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR 
## PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE, OR 
## TRADE PRACTICE. IN NO EVENT WILL BASEFOUNTAIN AND/OR ITS LICENSORS 
## BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL, 
## DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF BASEFOUNTAIN 
## AND/OR ITS LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY 
## OR PROBABILITY OF SUCH DAMAGES.
##
## ===================================================================
## -

## +
## ===================================================================
##  Module Name: McdAgentManagerOldGUI.py
##
##  Description:
##    For managing agent in scene, globally.
##
## ===================================================================
## -

import maya.cmds as cmds
from McdGeneral import *

import McdAgentManager
reload(McdAgentManager)
from McdAgentManager import *


def McdAgentManagerOldGUI():
    
    winName = "McdAgentManagerOld"
    if cmds.window(winName, ex = True):
        cmds.deleteUI(winName)
    cmds.window(winName, title = "Agent Manager 2010",rtf =True,menuBar=True, width=200)
    
    cmds.menu( label='Options')
    cmds.menuItem( label='Refresh contents', c = "McdRefreshAgentManagerOld()")
    cmds.menuItem( label='Help' )
    cmds.menuItem( divider=True )
    cmds.menuItem( label='Exit', c = "McdExitAgentManagerOld()" )
    
    form = cmds.formLayout()
    tabs = cmds.tabLayout(innerMarginWidth=5, innerMarginHeight=5)
    cmds.formLayout( form, edit=True, attachForm=((tabs, 'top', 0), (tabs, 'left', 0), \
                                                (tabs, 'bottom', 0), (tabs, 'right', 0)) )
    
    #-------------------------  Initialize  -------------------------#
    McdAgentManagerStartUpSetup()
    
    #--------------------------  Main GUI  --------------------------#
    child0 = cmds.columnLayout(adj = True)
    
    cmds.rowColumnLayout(nc = 2, cw = [(1,120),(2,100)])
    activeName = McdGetActiveAgentName()
    cmds.text(l = "Agent Name In Global:")
    cmds.textField("agentManger_if_name", ed = False,  tx = activeName)
    cmds.setParent("..")

    
    cmds.rowColumnLayout(nc = 6, cw = [(1,50), (2, 100), (3, 40),(4,50),(5, 40),(6, 40)])
    cmds.text(l = "Status", align = "left", font = "smallBoldLabelFont")
    cmds.text(l = "Name", align = "left", font = "smallBoldLabelFont")
    cmds.text(l = "Color", align = "left", font = "smallBoldLabelFont")
    cmds.text(l = "")
    cmds.text(l = "")
    cmds.text(l = "")
    agentAndIdList2 = McdGetAllAgentTypeNIDWithColor()

    if agentAndIdList2 != None and agentAndIdList2 != []:
        for i in range(len(agentAndIdList2[0])):
            stri = str(i)
            cmds.textField("tf_am_stt" + stri, ed = False, tx = "")
            cmds.textField("tf_am_agtn" + stri, ed = False, tx = agentAndIdList2[0][i])
            colorRGB = setColorOfDraw(agentAndIdList2[1][i])
            cmds.button("btn_am_cid" + stri, l = "", bgc = colorRGB, c = "AM_ActivateOld(" + stri + ")")
            cmds.button("btn_am_act" + stri, l = "Activate", c = "AM_ActivateOld(" + stri + ")")
            cmds.button(l = "Modify", c = "AM_ModOld(" + stri + ")")
            cmds.button(l = "Delete", c = 'cmds.confirmDialog(t = "Not available", m = "Not available, please manually delete the Agent_XXX in Outliner")')
    
    McdMarkActiveAgent(agentAndIdList2)
    cmds.setParent("..")
    
    cmds.rowColumnLayout(nc = 15, cw = [(1,22),(2,22),(3,22),(4,22),(5,22),(6,22),(7,22),(8,22),\
                                      (9,22),(10,22),(11,22),(12,22),(13,22),(14,22),(15,22)])
    for i in range(15):
        stri = str(i)
        colorRGB = setColorOfDraw(i)
        cmds.button(l = "", c = "AM_setcolorOld(" + stri + ")", bgc = colorRGB)
    cmds.setParent("..")
    
    
    
    cmds.rowColumnLayout(nc = 4, cw = [(1,77),(2,77),(3,77),(4,77)])
    cmds.button(l = "Add Agent", c = "McdAddAgentGroupOld()")
    cmds.setParent("..")
    
    
    
    cmds.setParent("..")
    
    
    #------------------------------- Cricial Help --------------------------------#
    child1 = cmds.columnLayout(adj = True)
    cmds.text(l = "* List all the agents in scene", fn = "smallBoldLabelFont", align = "left")
    cmds.text(l = "      Agent: children groups of \"Miarmy_Contents\"", align = "left")
    cmds.text(l = '      Naming Convention: Agent_<agentName>' , align = "left")
    cmds.text(l = '      Attribute: each group has "colorID", "agentID" attribute.' , align = "left")
    cmds.text(l = "")
    cmds.text(l = "* Agents Manager Functions", fn = "smallBoldLabelFont", align = "left")
    cmds.text(l = "      Create, modify, delete agents group", align = "left")
    
    cmds.separator(h = 10)
    cmds.button(l = "Check detailed help")
    
    cmds.setParent( '..' )
    
    
    cmds.tabLayout( tabs, edit=True,tabLabel=((child0, "Logic Table"),(child1, "Quick Tips")))
    cmds.showWindow(winName)



def McdRefreshAgentManagerOld():
    McdAgentManagerOldGUI()

def McdExitAgentManagerOld():
    try:
        cmds.deleteUI("McdAgentManagerOld")
    except:
        pass


