
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushA_c_h.ma" "bushA_c_hi";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushA_c_p.ma" "bushA_c_prox";

proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushB_c_L.ma" "bushB_c_Low";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushB_c_h.ma" "bushB_c_hi";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushB_c_p.ma" "bushB_c_prox";

proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushC_c_L.ma" "bushC_c_Low";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushC_c_h.ma" "bushC_c_hi";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushC_c_p.ma" "bushC_c_prox";

proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushD_c_L.ma" "bushD_c_Low";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushD_c_h.ma" "bushD_c_hi";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushD_c_p.ma" "bushD_c_prox";

proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushE_c_L.ma" "bushE_c_Low";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushE_c_h.ma" "bushE_c_hi";
proxyAdd "bushA_c_LRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000004Bush/master/bushE_c_p.ma" "bushE_c_prox";














