proxyAdd "ot_s000018blacksmithhome_l_txRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000018blacksmithhome/texture/ot_s000018blacksmithhome_p_h_tx.mb" "s000018blacksmithhome_c_prox"; 
proxyAdd "ot_s000018blacksmithhome_l_txRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000018blacksmithhome/texture/ot_s000018blacksmithhome_m_tx.mb" "s000018blacksmithhome_c_md"; 
proxyAdd "ot_s000018blacksmithhome_l_txRN" "//file-cluster/GDC/Projects/OTTO/Project/scenes/sets/s000018blacksmithhome/texture/ot_s000018blacksmithhome_h_tx.mb" "s000018blacksmithhome_c_hi"; 

s000018blacksmithhome_c_Low











