global proc s100VMautoReplaceResolutionByLocation()
{
$c = `currentTime -q ` ;
$getA = `s100getListForAllPanel`;
s100HiddeForAllPanel ;


$getH = `floatSliderGrp -q -v  s100VMAutoSwitchResolutionLayProcFlHigh `;
$getL = `floatSliderGrp -q -v   s100VMAutoSwitchResolutionLayProcFlLow `;
$camRecup   = `textField -q -text s100VMAutoSwitchResolutionSelTF `;

$list =`s100VMlistVegetationPrefix`;
$listRef =`s100VMlistVegetationRefNode`;

string $version ="sprite1" ;


	float $iF2 ;
	float $maxF = size($list) ;
	  int $amount = 0;



string $resL[] ={"high3","low2","sprite2"};


	if(`objExists "VMAE_main_ctrl"`)
	{
	$resL ={"high2","low1","sprite1"};
    }


$s = `playbackOptions -q -minTime   `;
$e = `playbackOptions -q -maxTime    `;

string $ResToReplace[] ;
int  $ResToReplaceInt[] ;
		for($j = 0 ; $j < size($list) ; $j++)
		{
		$ResToReplaceInt[$j] = 4 ;
        }


     progressWindow
	 	-max 100
         -title ("Checking Resolution for Veg ")
         -progress $amount
         -status "% done : 0%"
         -isInterruptable false;
$z = 0 ;
$last = $e - $s ;
	for($i = $s ; $i <= $e ; $i++)
	{
	currentTime $i ;

	$amount = ($z  / $last ) * 100  ;

			progressWindow -edit
				 -progress $amount
				 -status ("checking : "+$amount+"%");




		for($j = 0 ; $j < size($list) ; $j++)
		{
			if($ResToReplaceInt[$j] > 0)
			{
				if($ResToReplaceInt[$j] > 1)
				{

				$root = $list[$j] + "root_ctrl" ;
				float $dist = 0 ;
					if(`objExists $root`)
						$dist = getDistance($root, $camRecup );

					if($dist < $getL)
					{
					$ResToReplaceInt[$j] = 1 ;

						if($dist < $getH)
						{
						$ResToReplaceInt[$j] = 0 ;
						}


					}
					if($dist > $getL)
					{
					$ResToReplaceInt[$j] = 2  ;
					}

                }

            }
        }

	$z++;
    }
/*
print "\n $number : \n " ;
print $ResToReplaceInt ;
*/

	//print $ResToReplaceInt ;
	progressWindow -endProgress ;

     progressWindow
	 	-max 100
         -title ("switching Resolution for Veg ")
         -progress $amount
         -status "% done : 0%"
         -isInterruptable false;

	for($j = 0 ; $j < size($listRef); $j++)
	{
	$resL ={"high3","low2","sprite2"};


		if(`objExists "VMAE_main_ctrl"`)
		{
		$resL ={"high2","low1","sprite1"};
		}

	$ch = s100VMcheckIfResExists($listRef[$j] , $resL[0] ) ;

	if($ch == 0 )
		{
		$resL[0] = "high1";
		}

	$ch2 = s100VMcheckIfResExists($listRef[$j] , $resL[1] ) ;



		if($ResToReplaceInt[$j] == 4 )
			$ResToReplaceInt[$j] = 2 ;
		if($ResToReplaceInt[$j] == 1 )
		{
			if($ch2 == 0)
			{
			$ResToReplaceInt[$j] = 0 ;
            }
        }

	int $k = $ResToReplaceInt[$j] ;

	$ResToReplace[$j] = $resL[$k]   ;

	}

//print $ResToReplace ;


s100RestoreForAllPanel($getA ) ;

	for($i = 0 ; $i < size($list) ; $i++)
	{

	$iF2 = $i ;
	$amount = ($iF2 / $maxF) * 100  ;
	$root = $list[$i] + "root_ctrl" ;

			progressWindow -edit
				 -progress $amount
				 -status ("switching : "+$amount+"%");
	//print ("\n resTOswitch : ---------------- \n" + $version + " for " +$root );






	s100VMswitchResolution($root , $listRef[$i], $ResToReplace[$i] );
    }

	if(`objExists  "VM_guide_grp" `)
		delete "VM_guide_grp" ;


/*
print "\n $ResToReplace : \n " ;
print $ResToReplace ;


print "\n ref : \n " ;
print $listRef ;
*/
currentTime $c  ;
progressWindow -endProgress;


print ("\nAuto Replace Succed");
}