global proc s100rebuiltFactLate()
{
$worldA = "world_anim_grp";
$varC1= `listRelatives -c  $worldA` ;
float $div;

	for($i = 0 ; $i < size($varC1) ; $i++)
	{
	$listAllC = sort(`listRelatives -ad -fullPath $varC1[$i]`);
	print $listAllC ;
	int $numbTree = 0 ;
		for($j = 0 ; $j < size($listAllC) ; $j++)
		{
		string $array[] = stringToStringArray($listAllC[$j] ,"|") ;
		if(size($array) > $numbTree)
			$numbTree = size($array) ;

        }

	$listAll = sort(`listRelatives -ad  $varC1[$i]`);

	float $jF ;
	float $nTF ;


		for($j = size($listAllC) - 1 ; $j >= 0 ; $j--)
		{
		$jF = $j ;
		$nTF =   $numbTree  ;
		$div =$jF /$nTF ;
		print $div ;
			if($div > 1)
				$div = 1;

		//$div = 0 ;
			if(`attributeExists "overLap" $listAllC[$j]`)
				setAttr ($listAllC[$j] + ".overLap") $div ;
        }





    }







}

//s100rebuiltFactLate ;