global proc s100VRUI()
{
	if(`window -ex 	s100VRUI`)
		deleteUI s100VRUI;

	window -title "studio 100 Vegetations AutoRig"  -h 400  s100VRUI;
	columnLayout -adjustableColumn true s100VRUICLMain;


menuBarLayout s100VRUIMLMain;

    menu -en 0 -label "Edit" -helpMenu true;
	    menuItem -en 1 -c s100VRCleanVRUI   -label "clean";



    menu -en 0 -label "Help" -helpMenu true;
	    menuItem -en 1 -c s100VRUI   -label "refresh";
        menuItem -en 0   -label "help";
        menuItem -en 0  -label "About...";

    setParent ..;


		window -e -h 575 -w 460 -sizeable 0  s100VRUI;
	showWindow;


formLayout s100VRUIFLMain;

	$txLibray = `text -l "Asset Name :"`;
	$prodMenu = `textField -w 200 -ed 0 s100VRUITFAssetName`;
	$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;
	$editAN = `button -en 0 -w 50  -l "edit" -c s100VREditNameUI s100VREditNameBt `;


	$ico1 =`iconTextButton -annotation "Polygon Edges to Curve" -i "menuIconModify.xpm" -c CreateCurveFromPoly  `;
	$ico2= `iconTextButton -annotation "CV Curve Tool" -i "curveCV.xpm" -c CVCurveTool `;
	$ico3= `iconTextButton -annotation "Rebuild Curve" -i "rebuildCurve.xpm" -c RebuildCurveOptions  `;
	$ico4= `iconTextButton -annotation "create locator" -i "locator.xpm" -c CreateLocator  `;


	$tx = `text -label "tools"`;

$tab = `tabLayout -innerMarginWidth 5 -innerMarginHeight 5 s100VRUITLMain`;
formLayout -edit

	 //Prod
    -attachForm $txLibray "top"    10
    -attachForm $txLibray "left"   10
	-attachForm $prodMenu "top"    5
	-attachControl $prodMenu "left"   5 $txLibray
	-attachForm $newAN "top"    5
	-attachForm $editAN "top"    5
	-attachControl $newAN "left"   5 $prodMenu
	-attachControl $editAN "left"   5 $newAN


    -attachControl s100VRUITLMain "top"   5 $prodMenu
     -attachForm s100VRUITLMain "left"   0
     -attachForm s100VRUITLMain "bottom" 0
     -attachForm s100VRUITLMain "right" 50


	     -attachForm $tx "top"   35

	    -attachControl $ico1 "top"   0 $tx
	    -attachControl $ico2 "top"   0 $ico1
	    -attachControl $ico3 "top"   0 $ico2
	    -attachControl $ico4 "top"   0 $ico3

	     -attachControl $tx "left"   12 s100VRUITLMain
	     -attachControl $ico1 "left"   0 s100VRUITLMain
	     -attachControl $ico2 "left"   0 s100VRUITLMain
	     -attachControl $ico3 "left"   0 s100VRUITLMain
	     -attachControl $ico4 "left"   0 s100VRUITLMain

	 	  -attachForm s100VRUITLMain "left"  5


     s100VRUIFLMain;

	$weBt = 185 ;

	$weTx = 360 ;
	 formLayout -h 450 s100VRFLFlower;




	$textAutoRig = `text -l  "Auto Rig : " `;
	//$txFlSCurv= `text -label "select a curve first, then click on :" `;
	$btAddCurvPip = `button -w $weBt -l "add Curve/loc to Auto Rig or modify it" -c s100VRaddVegetationToAutoRigUI`;
	$btRemCurvPip = `button -w $weBt -l "rem Curve/loc from Auto Rig " -c s100VRRemGuideFromAR`;
	$sep1 = `separator -w $weTx`;

	$btShowAllAR = `button -w $weBt -l "show all auto rig" -c s100VRShowAllAR`;
	$btHideAllAR = `button -w $weBt -l "hide all auto rig" -c s100VRHideAllAR`;


	$btIsolateAR = `button -w $weBt -l "Isolate auto rig selected" -c s100VRIsolateSelectedAR`;


	$tx = "select a curve first or a locator , then click on :" ;

	$txFlSCurv = `scrollField  -w $weTx  -editable 0 -wordWrap 1 -text $tx ` ;




	$textRig = `text -l  "Rig : " `;


	$txE = "when you have finish your auto rig" ;
	$txRigIT = `scrollField  -w $weTx  -editable 0 -wordWrap 1 -text $txE ` ;

	$buttonRig = `button -w $weBt -l "rig it!" -c s100VRRigIt`;
	formLayout -e


	-attachForm $textAutoRig "top"    5
    -attachForm $textAutoRig "left"    5

    -attachControl $txFlSCurv "top"    5 $textAutoRig
    -attachForm $txFlSCurv "left"    5


	-attachControl $btAddCurvPip "top"   5 $txFlSCurv
	-attachControl $btRemCurvPip "top"   5 $txFlSCurv
	-attachControl $btRemCurvPip "left"   5 $btAddCurvPip

	-attachControl $sep1 "top"   5 $btRemCurvPip



	-attachControl $btShowAllAR "top"   5 $sep1

	-attachControl $btHideAllAR "top"   5 $sep1
	-attachControl $btHideAllAR "left"   5 $btShowAllAR


	-attachControl $btIsolateAR "top"   5 $btShowAllAR




	-attachForm $textRig "top" 200
	-attachControl $txRigIT "top" 5 $textRig
	-attachControl $buttonRig "top"   5 $txRigIT


	s100VRFLFlower;
setParent .. ;
s100VRUIAELayout ;



s100VRrefreshUI;


}
global proc s100VRUIAELayout()
{

	$weBt = 185 ;
	$weTx = 370 ;

	setParent s100VRUITLMain ;

if(`formLayout -ex s100VRATEffect`)
	{
	deleteUI s100VRATEffect ;
    }

	 formLayout -h 450 s100VRATEffect;

$prog = `progressBar -w $weTx s100VRUIAELayoutPB`;

$buttonAE1 = `button  -w $weBt  -l "add / refresh AE" -c s100VRcreateAttributControlAE `;
$buttonDeleteAE = `button -w $weBt  -l "delete AE" -c s100VRDeleteAE `;
$sep = `separator -w $weTx ` ;

$text = `text -l "randomize time"` ;
$tMin =  `text -l "min:"` ;
$tMax =  `text -l "max:"` ;

$minRand = `floatField -w 50 -v -10   s100VRminRandFG`;
$maxRand = `floatField -w 50  -v 10   s100VRmaxRandFG`;

$butRandomize = `button -en 0 -w $weBt  -l "Randomize Vegetation" -c s100VRRandomize `;
$sep1 = `separator -w $weTx ` ;


$ctrl = "VRAE_main_ctrl" ;

//$newAN = `button -en 1 -w 50  -l "new" -c s100VRNewName s100VRNewNameBt`;

	 formLayout -e
  	 -attachForm $prog "top" 5
  	 -attachControl $buttonAE1 "top" 5 $prog
  	 -attachControl $buttonDeleteAE "top" 5 $prog

 	 -attachForm $prog "left" 0
	 -attachForm $buttonAE1 "left" 0
	 -attachControl $buttonDeleteAE "left" 0 $buttonAE1
	 -attachControl $sep "top" 5 $buttonAE1
	 -attachControl $text "top" 5 $sep

	 -attachControl $tMin "top" 5 $text
	 -attachControl $tMax "top" 5 $text


 	 -attachControl $minRand "top" 5 $text
	 -attachControl $minRand "left" 5 $tMin



	 -attachControl $tMax "left" 5 $minRand

 	 -attachControl $maxRand "top" 5 $text
	 -attachControl $maxRand "left" 5 $tMax

 	 -attachControl $butRandomize "top" 5 $text
	  	 -attachControl $butRandomize "left" 5 $maxRand

 	 -attachControl $sep1 "top" 5 $butRandomize


	 s100VRATEffect;


	if(`objExists $ctrl`)
	{
		$textC = `text -l "Main Controler"` ;

    	$fRotY = `attrFieldSliderGrp -min -180 -max 180 -at ($ctrl +".rotateY")`;


		//$fAmp = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".amplitude")`;



		$fAmp = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".amplitude")`;
		$fFreq = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".frequence")`;
		$fRot = `attrFieldSliderGrp -min 0 -max 10 -at ($ctrl +".wingsRot")`;


		 formLayout -e
		 -attachControl $textC "top" 5 $sep1
		 -attachControl $fRotY "top" 5 $textC
		 -attachControl $fAmp "top" 5 $fRotY


		 -attachControl $fFreq "top" 0 $fAmp
		 -attachControl $fRot "top" 0 $fFreq


		 s100VRATEffect;

	}


//tabLayout -
     tabLayout -edit
	 -tabLabel s100VRFLFlower "autoRig"

 	 -tabLabel s100VRATEffect "atmosphereEffect"

         s100VRUITLMain;

}


//s100VRUI ;

s100VRUIAELayout;