
global proc  s100FileManagerUIAssetLayout()
{
     string $assetLayout = `formLayout -height 460 s100FileManagerUIFLAsset`;

global string  $base_script_path;
$path = substituteAllString ($base_script_path , ";","");
$path += "/images/s100FilesManager/";
$thumbImage = $path + "MA_C_MayaOriginal_01.jpg" ;

$imageTopFolder = $path + "topFolder.bmp" ;
$imageParFolder =  $path + "parentFolder.bmp" ;


$dist = 25 ;
$distBis = 4 ;
$distSide2 = 35 ;
$distSep = 15 ;
//create Button

	//text library
	$txLibray = `text -l "LIBRARY" `;

	//type Menu
	$typeText = `text -l "TYPE : "`;
	$typeMenu = `optionMenu   s100FileManagerUIOMType` ;

	//sub TEXT
	$widthSub = 95 ;
	$subText = `text -l "SUB :"`;
	$subField = `optionMenu  s100FileManagerUIOPSub` ;


	//NAME TEXT
	$widthName = 165 ;
	$nameText = `text -l "NAME :"`;
	$nameField = `optionMenu  s100FileManagerUIOPName` ;

	//STATE TEXT
	$stateText = `text -l "STATE :"`;
	$stateMenu = `optionMenu   s100FileManagerUIOMState` ;

	//Version TEXT
	$widthVersion = 30 ;
	$IncAsText = `text -l "Vers :"`;
	$IncAsField = `optionMenu  s100FileManagerUIOMVersion` ;


	//LevelOfDetail TEXT
	$lodText = `text -l "LOD :"`;
	$lodMenu = `optionMenu   s100FileManagerUIOMLod` ;

	//separator
	$sideSep = 490 ;
	$sep1 = `separator -w  $sideSep `;
	$sep2 = `separator -w  $sideSep `;


	//path TEXT
	$widthPath = 470 ;

	$pathText = `text -l "PATH :"`;
	$pathAssetMenu = `textField -w  $widthPath -ed 0  s100FileManagerUITFPathAsset` ;


	//explore Windows
	$listH = 170 ;
	$takeWidth = 340 ;

	$exploreField = `textScrollList -w $takeWidth -height $listH s100FileManagerUITSExplore`;
	$sep3 = `separator -w  ($takeWidth + 35)  `;

	$sep4 = `separator -w  ($takeWidth + 35) `;


	//thumbnails
	$thumbH = 150 ;
	$thumbW = 150 ;
	$thumbImage = `image -h $thumbH -w $thumbW  -i $thumbImage s100FileManagerUIIThumbnails` ;



	//thumbnailsTopFolder
	$thumbH = 20 ;
	$thumbW = 20 ;
	$topFolderButton = `nodeIconButton -style "iconOnly"
    -image1 $imageTopFolder
	-h $thumbH
	-w $thumbH
	-annotation "top Folder"
		   s100FileManagerUINBTopFolder` ;



	//thumbnailsPArentFolder02

	$parentFolderButton = `nodeIconButton -style "iconOnly"
    -image1 $imageParFolder
	-h 20
	-w 20
	-annotation "parent Folder"
	   s100FileManagerUINBParentFolder` ;



//////////////////////////////////////////////////////////
	//buttons
$widthBut1 = 95 ;
$widthBut2 = 150 ;

		// add sub

	$addSubButton = `button -w $widthBut1 -label "Add Sub"` ;


		// add Name

	$addNameButton = `button -w $widthBut1 -label "Add Name"` ;

		// add Version

	$addVersButton = `button -w $widthBut1 -label "Add Version"` ;


		//top Folder
	$TopFolderButton = `button -w $widthBut2 -label "Top Folder"` ;

		//Open LAst

	$openButtonLast = `button -w $widthBut2 -label "Open Last"` ;

		//Open Wip

	$openButtonWip = `button -w $widthBut2 -label "Open Wip"` ;



		//Publish

	$publishButton = `button -w $widthBut2 -label "Publish"` ;


		//Save Wip

	$saveButtonWip = `button -w $widthBut2 -label "Save Wip"` ;


//////////////////////////////////////////////////////////


$smallDist = 5 ;

//Library
$ligne1 = 5 ;
$ligne1bis = 5 - $distBis ;
$ligne1tmp = $ligne1 + $dist ;

//name
$ligne2 = $ligne1 + $dist + 15 ;
$ligne2bis = $ligne2 - $distBis ;

//type
$side1 = 5 ;
$side2 = $side1 + $distSide2 + 15  ;

//sub
$side2t = $side1 + 150  ;
$side2t2 =  $side2t + 50 ;

//name
$side3 = $side2t2 + $widthSub + 50  ;
$side4 = $side3 + 40 ;

//vers
$side5 = $side1  ;
$side6 = $side2;

//state
$side7 = $side2t ;
$side8 = $side2t2 ;

//lod
$side9 = $side3 ;
$side10 = $side4 ;

//path separator
$ligne3 = $ligne2 + $dist  ;

//path
$ligne4 = $ligne3 + $distSep  ;
$ligne4bis = $ligne4 - $distBis ;

//path
$sideLigne4 = 38 ;
$sideLigne4Bis = $sideLigne4 + 38 ;

//separator
$ligne5 = $ligne4 + $dist ;

//explore
$ligne6 = $ligne5 + $smallDist ;


//button Explorer

$ligne6bis = $ligne6 + $thumbH + 2 ;
$sideButtonExplorer = $side1 + $takeWidth + 5 ;


//separator
$ligne7 = $ligne6 + $listH + $smallDist ;

//thumbnai
$ligne8 = $ligne7 + $smallDist ;


//////////////////////////////////////////////////////////

	//button Right

	$spaceBut = 22 ;
	$smallSepBut  = 10 ;
	$ligBut1 = 25;
	$sideBut1 = 0 ;
	$ligBut2 = $ligBut1 + $spaceBut ;
	$ligBut3 = 	 $ligBut2 + $spaceBut ;

$lig2But1 = $ligne6  + $smallSepBut ;
$lig2But2 = $lig2But1 + $spaceBut + $smallSepBut  ;
$lig2But3 = $lig2But2 + $spaceBut ;
$lig2But4 = $lig2But3 + $spaceBut  + $smallSepBut  ;
$lig2But5 = $lig2But4 + $spaceBut;
$side2But1 = $sideButtonExplorer + 40 ;

formLayout -edit

	//add sub
    -attachForm $addSubButton "top"    $ligBut1
    -attachForm $addSubButton "right"   $sideBut1

	//add Name
    -attachForm $addNameButton "top"    $ligBut2
    -attachForm $addNameButton "right"   $sideBut1

	//add Version
    -attachForm $addVersButton "top"    $ligBut3
    -attachForm $addVersButton "right"   $sideBut1

////////////////////////////

		//top Folder
    -attachForm $TopFolderButton "top"    $lig2But1
    -attachForm $TopFolderButton "left"   $side2But1

		//Open LAst
    -attachForm $openButtonLast "top"    $lig2But2
    -attachForm $openButtonLast "left"   $side2But1

		//Open Wip
    -attachForm $openButtonWip "top"    $lig2But3
    -attachForm $openButtonWip "left"   $side2But1


			//Publish
    -attachForm $publishButton "top"    $lig2But4
    -attachForm $publishButton "left"   $side2But1


			//save Wip
    -attachForm $saveButtonWip "top"    $lig2But5
    -attachForm $saveButtonWip "left"   $side2But1



////////////////////////////
	//text library

    -attachForm $txLibray "top"    0
    -attachForm $txLibray "right"   (15)


	//type menu
    -attachForm $typeText "top"    $ligne1
    -attachForm $typeText "left"   $side1
    -attachForm $typeMenu "top"    $ligne1bis
    -attachForm $typeMenu "left"   $side2


	//sub Field

    -attachForm $subText "top"    $ligne1
    -attachForm $subText "left"   $side2t

    -attachForm $subField "top"    $ligne1bis
    -attachForm $subField "left"   $side2t2

	//name Field

    -attachForm $nameText "top"    $ligne1
    -attachForm $nameText "left"   $side3

    -attachForm $nameField "top"    $ligne1bis
    -attachForm $nameField "left"   $side4


	//separator

    -attachForm $sep1 "top"    $ligne1tmp
    -attachForm $sep1 "left"   $side2

	//version Field

    -attachForm $IncAsText "top"    $ligne2
    -attachForm $IncAsText "left"   $side5

    -attachForm $IncAsField "top"    $ligne2bis
    -attachForm $IncAsField "left"   $side6

	//state Field

    -attachForm $stateText "top"    $ligne2
    -attachForm $stateText "left"   $side7

    -attachForm $stateMenu "top"    $ligne2bis
    -attachForm $stateMenu "left"   $side8

	//LevelOfDetail Field

    -attachForm $lodText "top"    $ligne2
    -attachForm $lodText "left"   $side9

    -attachForm $lodMenu "top"    $ligne2bis
    -attachForm $lodMenu "left"   $side10

	//separator

    -attachForm $sep2 "top"    $ligne3
    -attachForm $sep2 "left"   $side2

	//path Field

    -attachForm $pathText "top"    $ligne4
    -attachForm $pathText "left"   $sideLigne4

    -attachForm $pathAssetMenu "top"    $ligne4bis
    -attachForm $pathAssetMenu "left"   $sideLigne4Bis


	//separator

    -attachForm $sep3 "top"    $ligne5
    -attachForm $sep3 "left"   $side1


	//explorer

    -attachForm $exploreField "top"    $ligne6
    -attachForm $exploreField "left"   $side1


	//explorer button top

    -attachForm $topFolderButton "top"    $ligne6
    -attachForm $topFolderButton "left"   $sideButtonExplorer


	//explorer button folder

    -attachForm $parentFolderButton "top"    $ligne6bis
    -attachForm $parentFolderButton "left"   $sideButtonExplorer


	//separator

    -attachForm $sep4 "top"    $ligne7
    -attachForm $sep4 "left"   $side1

	//thumbnail

    -attachForm $thumbImage "top"    $ligne8
    -attachForm $thumbImage "left"   $side1






s100FileManagerUIFLAsset ;

	     setParent ..;



}
