global proc s100FileManagerRefreshUI()
{


s100FileManagerUIRefreshEpisode ;
s100FileManagerUIRefreshSequence ;
s100FileManagerUIRefreshDepartment ;
s100FileManagerUIRefreshShoot ;
s100FileManagerUIRefreshTake;
s100FileManagerUIRefreshInc;
s100FileManagerUIRefreshButton ;
}

global proc s100FileManagerUIRefreshPath()
{
string $path ;
string $prod  = `optionMenu -q -v s100FileManagerUIOMProd`;
string $ep = "" ;
string $sq = "" ;
string $dept = "" ;
string $shoot = "";
string $take = "";

	if(size($prod)>0)
	{
	$path =s100assetManagerGetEpPath($prod) ;
	string $ep  = `optionMenu -q -v s100FileManagerUIOMEpisode`;
				if(size($ep)> 0)
				{
				$path += $ep + "/" ;

				string $dept  = `optionMenu -q -v s100FileManagerUIOMDepartement`;
					if(size($dept)>0)
					{
					$path += $dept + "/" ;
					string $sq  = `optionMenu -q -v s100FileManagerUIOMSequence`;
						if(size($sq)>0)
						{
						$path += $sq + "/" ;

						string $arrTmp[]  = `textScrollList -q -si  s100FileManagerUITSShoot` ;
						string $shoot = $arrTmp[0];
							if(size($shoot) > 0)
							{
							$path += $shoot + "/" ;
							string $arrTmp[]  = `textScrollList -q -si  s100FileManagerUITSTake` ;
							string $take = $arrTmp[0];
								if(size($take) > 0)
								{
								$path += $take + "/" ;

                                }


                            }
                        }
                    }

                }
    }

	textField -e -tx $path  s100FileManagerUITFpath ;
s100FileManagerUIRefreshButton ;



}

global proc s100FileManagerUIChangeProd()
{
s100FileManagerUIRefreshEpisode ;
s100FileManagerUIRefreshSequence ;
s100FileManagerUIRefreshDepartment ;
s100FileManagerUIRefreshShoot ;
s100FileManagerUIRefreshPath ;

}

global proc s100FileManagerRefreshUIChangeEp()
{
s100FileManagerUIRefreshSequence ;
s100FileManagerUIRefreshDepartment ;
s100FileManagerUIRefreshShoot ;
s100FileManagerUIRefreshTake ;

s100FileManagerUIRefreshPath;
textScrollList -e -ra  s100FileManagerUITSTake ;
s100FMRefreshPublishButton;

}

global proc s100FileManagerRefreshUIChangeSq()
{
s100FileManagerUIRefreshDepartment ;
s100FileManagerUIRefreshShoot ;
s100FileManagerUIRefreshTake ;
s100FileManagerUIRefreshPath;
textScrollList -e -ra  s100FileManagerUITSTake ;
s100FMRefreshPublishButton;

}

global proc s100FileManagerRefreshUIChangeSc()
{
s100FileManagerUIRefreshTake ;
s100FileManagerUIRefreshPath ;
s100FileManagerUIRefreshInc ;
s100FMRefreshPublishButton;
s100FMPrintNoteForShot;

}

global proc s100FileManagerRefreshUIChangeTk()
{
s100FileManagerUIRefreshPath ;
s100FileManagerUIRefreshInc ;
s100FileManagerUIRefreshButton;
s100FMPrintNoteForShot;


}

global proc s100FMRefreshPublishButton()
{
	string $take = "";
	string $arrTmp[]  = `textScrollList -q -si  s100FileManagerUITSTake` ;
	string $take = $arrTmp[0];
	int $pub ;

	int $check = 0;
	float $v1;
	float $v2;
	float $v3;
	$v1=$v2 = $v3 = 0 ;

	if (size($arrTmp) >0)
		$check++;

	$label = "PUBLISH";
	$pub =  `s100ASQueryShotPublished`;
	string $annot ;
	$check+= $pub;
	string $chSt = $check ;
		switch($chSt){
		case "0" :
		$label = "PUBLISH";
		$annot = "";
		$v1=$v2 = $v3 = 1 ;
		break;
		case "1" :
		$label = "PUBLISH";
		$v1 = .9 ;
		$annot = "this file has not been published yet";
		break;
		case "2" :
		$label = "PUBLISH";
		$v2 = .9 ;
		$annot = "this file has been published";
		break;
		}


button -e -label $label -backgroundColor $v1 $v2 $v3 -ann $annot   s100FileManagerUIBTShotPublish;


}

global proc s100FileManagerRefreshUIChangeDept()
{
s100FileManagerUIRefreshPath ;
$selectProd = `textScrollList -q -si  s100FileManagerUITSShoot` ;



s100FileManagerUIRefreshShoot ;



	if (size($selectProd) > 0 )
	{


	$check = `textScrollList -q -exists $selectProd s100FileManagerUITSShoot `;
		if ($check == 1 )
		{
		textScrollList -e -si $selectProd s100FileManagerUITSShoot ;
		s100FileManagerUIRefreshTake ;

        }
	textScrollList -e -ra  s100FileManagerUITSTake ;

    }





}
global proc s100FileManagerUIRefreshTake()
{
string $folders[] ;
$folders = s100FileManagerGetTakeFolder() ;

global string $base_prodFilesSystem ;


textScrollList -e -ra  s100FileManagerUITSTake ;

$files = $folders;
$filesSort = sort($files) ;
$size = size($filesSort) ;
//textScrollList -e -numberOfRows $size  s100ProdManagerUITSProd ;
$sel = `textScrollList -q -selectItem  s100FileManagerUITSShoot` ;

	if (size($sel) > 0)
	{

		for ($i =0 ; $i < size($filesSort) ; $i++)
		{
		$tmpName = substituteAllString ($filesSort[$i] , ".txt" , "" ) ;
		textScrollList -e -append $tmpName  s100FileManagerUITSTake ;
		}


	}
}

global proc s100FileManagerUIRefreshInc()
{

$inc = `s100FileManagerGetInc`;


textScrollList -e -ra  s100FileManagerUITSInc ;


//textScrollList -e -numberOfRows $size  s100ProdManagerUITSProd ;
	for ($i =0 ; $i < size($inc) ; $i++)
	{
 	textScrollList -e -append $inc[$i]  s100FileManagerUITSInc ;
    }



}

global proc s100FileManagerUIRefreshShoot()
{
string $folders[] ;
$folders = s100FileManagerGetShotFolder() ;

global string $base_prodFilesSystem ;


textScrollList -e -ra  s100FileManagerUITSShoot ;

$files = $folders;
$filesSort = sort($files) ;
$size = size($filesSort) ;
//textScrollList -e -numberOfRows $size  s100ProdManagerUITSProd ;
	for ($i =0 ; $i < size($filesSort) ; $i++)
	{
	$tmpName = substituteAllString ($filesSort[$i] , ".txt" , "" ) ;
 	textScrollList -e -append $tmpName  s100FileManagerUITSShoot ;
    }



}

global proc s100FileManagerUIRefreshDepartment()
{
string $prod  = `optionMenu -q -v s100FileManagerUIOMProd`;



$folder = sort( `s100assetManagerGetDeptTemp($prod)` );


$test = `optionMenu -q -itemListLong s100FileManagerUIOMDepartement`;


	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100FileManagerUIOMDepartement;
	}


}

global proc s100FileManagerUIRefreshSequence()
{
string $prod  = `optionMenu -q -v s100FileManagerUIOMProd`;
string $ep  = `optionMenu -q -v s100FileManagerUIOMEpisode`;


$folder = s100ASGetAllSqFolders($prod,$ep) ;

$test = `optionMenu -q -itemListLong s100FileManagerUIOMSequence`;


	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100FileManagerUIOMSequence;
	}



}

global proc s100FileManagerUIRefreshEpisode()
{
string $prod  = `optionMenu -q -v s100FileManagerUIOMProd`;


$folder = s100ASListEp($prod) ;

$test = `optionMenu -q -itemListLong s100FileManagerUIOMEpisode`;
	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100FileManagerUIOMEpisode;
	}





}

global proc s100FileManagerUIRefreshProd()
{
global string $base_prodFilesSystem ;



$files = `getFileList -folder ($base_prodFilesSystem + "prod/" )  -filespec "*.txt"`;
$filesSort = sort($files) ;
$size = size($filesSort) ;



$folder = $filesSort ;

$test = `optionMenu -q -itemListLong s100FileManagerUIOMProd`;
	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $folder)
	{
	$ren = substituteAllString($tmp , ".txt" , "") ;
	menuItem -label $ren  -p s100FileManagerUIOMProd;
	}




}


global proc s100FileManagerRefreshUIChangeInc()
{
s100FMPrintNoteForShot;
s100FileManagerUIRefreshButton ;

}

global proc s100FileManagerUIRefreshButton()
{
	button -e -bgc 1 1 1  s100FileManagerUIBTShotPublish;
s100FMRefreshPublishButton ;
 $prod  = `optionMenu -q -numberOfItems  s100FileManagerUIOMProd`;
 $ep  = `optionMenu -q -numberOfItems  s100FileManagerUIOMEpisode`;
 $sq  = `optionMenu -q -numberOfItems s100FileManagerUIOMSequence`;
 $dept  = `optionMenu -q -numberOfItems  s100FileManagerUIOMDepartement`;

	if($prod > 0)
	{
			if($ep > 0)
			{
				if($sq > 0)
				{
					if($dept > 0)
					{
					button -e -en 1  s100FileManagerUIBTShotAdd;

					}else{

					button -e -en 0  s100FileManagerUIBTShotAdd;

                    }

				}else{
				button -e -en 0  s100FileManagerUIBTShotAdd;

                }
            }else{
			button -e -en 0  s100FileManagerUIBTShotAdd;

            }
    }else{
	button -e -en 1  s100FileManagerUIBTShotAdd;

    }


$selShot = `textScrollList -q -si  s100FileManagerUITSShoot` ;

if (size($selShot) == 0 )
	{
	button -e -en 0  s100FileManagerUIBTShotRem;

	button -e -en 0  s100FileManagerUIBTTakeAdd;
	button -e -en 0 s100FileManagerUIBTShotEditNotes;

    }else{
	button -e -en 1  s100FileManagerUIBTShotRem;
	button -e -en 1  s100FileManagerUIBTTakeAdd;
	button -e -en 1 s100FileManagerUIBTShotEditNotes;

    }





$selTake = `textScrollList -q -si  s100FileManagerUITSTake` ;

if (size($selTake) == 0 )
	{



	button -e -en 0  s100FileManagerUIBTTakeRem;



	button -e -en 0  s100FileManagerUIBTShotPublish;
	button -e -en 0  s100FileManagerUIBTShotSaveWip;

	button -e -en 0  s100FileManagerUIBTShotLoadLast;
	button -e -en 0  s100FileManagerUIBTShotLoadSel;

	button -e -en 0  s100FileManagerUIBTShotViewBlast;
	button -e -en 0  s100FileManagerUIBTShotCreateBlast;

s100FMRefreshPublishButton;

    }else{

	button -e -en 1  s100FileManagerUIBTTakeRem;



	button -e -en 1  s100FileManagerUIBTShotPublish;
	button -e -en 1  s100FileManagerUIBTShotSaveWip;

	button -e -en 1  s100FileManagerUIBTShotLoadLast;
	button -e -en 1  s100FileManagerUIBTShotLoadSel;

s100FMRefreshPublishButton;


    }

}
