//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc zmRenderMouth()
{
	source "ezRenderMainLayoutMaterial.mel";
	
	string $reffiles[] = `file -q -r`;
	for ($file in $reffiles)
	{
		string $buff[];
		int $num = `tokenize $file "\/" $buff`;
		$num = `tokenize $buff[$num-1] "{}" $buff`;
		string $char = $buff[0];
	
		string $teeth[]={};
		string $tongue[]={};
		string $mouthface[]={};
		switch ($char)
		{
			case "zm_C001001EdRhino_h_ms_anim.mb" :
				$teeth = {"MSH_teeth_down","MSH_teeth_up"};
				$tongue = {"MSH_tongue"};
				$mouthface = {"MSH_head.f[231:243]","MSH_head.f[245:247]","MSH_head.f[325:328]","MSH_head.f[339:342]","MSH_head.f[370:377]","MSH_head.f[398:401]",
							"MSH_head.f[413:416]","MSH_head.f[503:506]","MSH_head.f[554:557]","MSH_head.f[594:597]","MSH_head.f[644:652]","MSH_head.f[659:662]",
							"MSH_head.f[668:676]","MSH_head.f[680:683]","MSH_head.f[748:837]","MSH_head.f[1069:1081]","MSH_head.f[1083:1085]",
							"MSH_head.f[1163:1166]","MSH_head.f[1177:1180]","MSH_head.f[1208:1215]","MSH_head.f[1236:1239]","MSH_head.f[1251:1254]",
							"MSH_head.f[1341:1344]","MSH_head.f[1392:1395]","MSH_head.f[1432:1435]","MSH_head.f[1482:1490]","MSH_head.f[1497:1500]",
							"MSH_head.f[1506:1514]","MSH_head.f[1518:1521]","MSH_head.f[1586:1675]"};
				break;
			case "zm_C002001FritzLion_h_ms_anim.mb" :
				$teeth = {"MSH_teeth_down","MSH_teeth_up"};
				$tongue = {"MSH_tongue"};
				$mouthface = {"MSH_head.f[773:927]","MSH_head.f[1450:1604]","MSH_head.f[1621:1752]","MSH_head.f[1757:1766]"};
				break;
			case "zm_C003001FumiMonkey_h_ms_anim.mb" :
				$teeth = {"MSH_teeth_DWN_","MSH_teeth_UP_"};
				$tongue = {"MSH_tongue_"};
				$mouthface = {"MSH_head.f[41]","MSH_head.f[49]","MSH_head.f[98:177]","MSH_head.f[181:182]","MSH_head.f[185:188]","MSH_head.f[197:202]",
							"MSH_head.f[216:217]","MSH_head.f[219:221]","MSH_head.f[223:225]","MSH_head.f[227]","MSH_head.f[444:445]","MSH_head.f[450:456]",
							"MSH_head.f[529:540]","MSH_head.f[1280]","MSH_head.f[1288]","MSH_head.f[1337:1416]","MSH_head.f[1418:1419]","MSH_head.f[1422:1425]",
							"MSH_head.f[1434:1439]","MSH_head.f[1453:1454]","MSH_head.f[1456:1458]","MSH_head.f[1460:1462]","MSH_head.f[1464]",
							"MSH_head.f[1593:1594]","MSH_head.f[1599:1605]","MSH_head.f[1678:1689]","MSH_head.f[2280:2307]"};
				break;
			case "zm_C004001NigelBadger_h_ms_anim.mb" :
				$teeth = {"MSH_tooth"};
				$tongue = {"MSH_tongue"};
				$mouthface = {"MSH_head.f[509:626]","MSH_head.f[677:697]","MSH_head.f[704:712]","MSH_head.f[1305:1422]","MSH_head.f[1473:1493]","MSH_head.f[1500:1508]"};
				break;
			case "zm_C005001NedBird_h_ms_anim.mb" :
				$teeth = {};
				$tongue = {"MSH_tongue"};
				$mouthface = {"MSH_head.f[536:645]","MSH_head.f[1083]","MSH_head.f[1164:1278]","MSH_head.f[1309:1318]","MSH_head.f[1367]","MSH_head.f[1460:1465]",
							"MSH_head.f[1467:1580]","MSH_head.f[2018]","MSH_head.f[2099:2213]","MSH_head.f[2244:2253]","MSH_head.f[2302]","MSH_head.f[2395:2400]",
							"MSH_head.f[2402:2405]"};
				break;
		}

		string $ns = `file -q -ns $file`;
		select -cl;
		if (size($teeth))
		{
			for ($f in $teeth)
			{
				select -add ($ns+":"+$f);
			}
			ezRenderMainLayoutMaterial_Assign("colorR");
		}


		select -cl;
		if (size($tongue))
		{
			for ($f in $tongue)
			{
				select -add ($ns+":"+$f);
			}
			ezRenderMainLayoutMaterial_Assign("colorG");
		}

		select -cl;
		if (size($mouthface))
		{
			for ($f in $mouthface)
			{
				select -add ($ns+":"+$f);
			}
			ezRenderMainLayoutMaterial_Assign("colorB");
		}
	}
	select -cl;
}

global proc zmRenderMouthLayer()
{
	source "ezRenderMainLayoutMaterial.mel";
	
	
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}	
	string $objShape[] = `ls -sl`;
	string $renderLayer = `createRenderLayer -name "RGBA" -makeCurrent -noRecurse $objShape`;
	
	editRenderLayerGlobals -currentRenderLayer $renderLayer;
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";

	ezRenderMainLayoutMaterial_Assign("matte");
	//ÑÀ³Ý£¬ÉàÍ·£¬¿ÚÇ»
	zmRenderMouth;
}