global proc  s100putVersion()
{

string $tk = `s100ReturnTkName`;
string $file = `file -q -sn -shortName ` ;

/*
	if(!`gmatch $file "*Rendering*" ` )
	{
	$tmp =  	stringToStringArray ($file , "_" ) ;
	$tk = ($tmp[4] + "_" + $tk ) ;

    }
*/

setAttr -type "string" defaultRenderGlobals.renderVersion $tk;

	//python("import s100API.performing as perf");
	//python("perf.set_tkVersion()");
}



global proc string   s100ReturnTkName()
{
string $return = "TkUnknow" ;

$file = `file -q -sceneName -shortName  `;


	if(size($file) > 0)
	{
	string $arrayt[] = stringToStringArray($file , "." ) ;

	string $array[] = stringToStringArray($arrayt[0] , "_" ) ;


		if(`gmatch $array[5] "Tk*"`)
		{
		$return = 	$array[5] ;
			if(size($array[6]) >0 )
			{
			$return += "_" + $array[6] ;
            }
        }

    }
return $return ;
}