//string gestion


global proc string  s100capitalizeFirstLetter(string $name)
{
$first = startString($name, 1) ;
$noFirst = substring($name, 2 , 10000) ;
$cap = capitalizeString($first ) ;
$complete = ($cap + $noFirst );
return $complete;


}


global proc s100sep()
{
print ("\n----------------------------\n" ) ;
}



global proc string s100CapitalizeAllString(string $string)
{


string $return ="" ;
	for($i = 0 ; $i < size($string); $i++)
	{

	$start = startString($string, ($i +1)) ;
	$end = endString($start , 1) ;


	$cap= capitalizeString($end);
	$return += $cap;


    }

return $return ;
}

