global proc s100deleteAllFloatingWindow(string $rem[])
{
	string $test[] = `lsUI -type "window"`;
	 string $toRem[] = {"CommandWindow","MayaWindow","ColorEditor"} ;
	string $arr[] = stringArrayRemove($toRem, $test) ;
		if(size($rem) >0)
			$arr = stringArrayRemove($rem, $arr) ;


		for($tmp in  $arr )

			deleteUI $tmp ;
	lsUI   -menus  ;
}




global proc s100deleteAllFloatingWindowMan()
{
	s100deleteAllFloatingWindow({""}) ;
}



global proc s100deleteMainFloatingWindow(string $rem[])
{
	string $test[] = `lsUI -type "window"`;
	string $toRem[] = {"CommandWindow","MayaWindow","ColorEditor","s100FileManagerUI"} ;
	string $arr[] = stringArrayRemove($toRem, $test) ;
		if(size($rem) >0)
			$arr = stringArrayRemove($rem, $arr) ;


		for($tmp in  $arr )

			deleteUI $tmp ;
	lsUI   -menus  ;
}




global proc s100deleteMainFloatingWindowMan()
{
	s100deleteMainFloatingWindow({""}) ;
}

