global proc string[] s100checkSameNameIsScene()
{
$var = `ls `;
string $vart;
string $return[] ;
$j = 0 ;
	for ($vart in $var)
	{
		if(`gmatch $vart ("*|*")`)
		{
			//print ("\n same name on " + $vart +"\n" )  ;
		$return[$j] = $vart ;
		$j++;

        }
    }

return $return ;
}



global proc s100checkSameName()
{
	if(`window -exists s100checkSameNameUI`)
		deleteUI s100checkSameNameUI ;

window -h 400 -w 400 s100checkSameNameUI ;
columnLayout -adj 1 s100checkSameNameUICL;
scrollField -h 320 -editable false -wordWrap true s100checkSameNameUISF;

button -c s100checkSameNameUIRefresh -l "refresh List" ;
button -c s100SlectSameNameUIRefresh -l "select List" ;


window -e -h 400 -w 400 s100checkSameNameUI ;
showWindow s100checkSameNameUI ;

s100checkSameNameUIRefresh ;

}

global proc s100SlectSameNameUIRefresh()
{
select `s100checkSameNameIsScene` ;
}

global proc s100checkSameNameUIRefresh()
{
string $list[] = `s100checkSameNameIsScene`;

	if(size($list) == 0)
	{
	$list[0] = "no object with same name in this scene ! Good " ;
	}

scrollField -e -clear s100checkSameNameUISF;
string $toPut;

	for($i = 0 ; $i <size($list) ; $i++)
	{
	$toPut += $list[$i] ;
	$toPut += "\n" ;
    }

scrollField -e -text $toPut s100checkSameNameUISF;

}