global proc string s100returnRootPathForAnAsset(string $file)
{
$dir = dirname($file) ;
string $fileA[]  =  stringToStringArray($file, "/") ;
$ch = 0 ;
$i = 0 ;
string $returnPath;
	while($ch == 0)
	{
		$ch = `gmatch $fileA[$i] "MA_?_*"`;
   		$returnPath += $fileA[$i] ;
		$returnPath += "/" ;

			if($i >= size($fileA) )
			{
			break ;
            }

		$i++;



    }
return  $returnPath;
}
global proc string s100returnRootPathForAnShot(string $file)
{
//$file = `file -q -sn `
$dir = dirname($file) ;
string $fileA[]  =  stringToStringArray($file, "/") ;
$ch = 0 ;
$i = 0 ;
string $returnPath;
	while($ch == 0)
	{
		$ch = `gmatch $fileA[$i] "Sc*"`;
   		$returnPath += $fileA[$i] ;
		$returnPath += "/" ;

			if($i >= size($fileA) )
			{
			break ;
            }

		$i++;



    }
return  $returnPath;
}
