//´´½¨Anorld Occ²ã
global proc skRenderTools_Anorld_Occ()
{
    if(`objExists("ZIDMT_AnorldOcc")`)
    {
        catch(`delete "ZIDMT_AnorldOcc"`);
    }
    
    if(`objExists("Occ")`)
    {
        catch(`delete "Occ"`);
    }

    $obj = `ls -sl`;

	string $renderLayer_infoFringe = "Occ";
	createRenderLayer -makeCurrent -name $renderLayer_infoFringe -noRecurse $obj;
    
	string $shader = `shadingNode -asShader aiAmbientOcclusion -name ("ZIDMT_ArnoldOcc")`;
	setAttr ($shader+ ".samples") 4;


	select $obj;
	hyperShade -assign $shader;
	string $shaderName[] =`listConnections -type shadingEngine $shader`;
	connectAttr -force ($shaderName[0]+".message") ($renderLayer_infoFringe + ".shadingGroupOverride") ;
	lockNode -lock off $shaderName[0];
	rename $shaderName[0] ("Arnold_Occ_Set");
	
	unifiedRenderGlobalsWindow;
	setAttr "defaultRenderGlobals.currentRenderer" -type "string" "arnold";
	
	evalDeferred -lowestPriority "skRenderTools_Arnold_Occ_Set";
	
}

global proc skRenderTools_Arnold_Occ_Set()
{
	editRenderLayerAdjustment "defaultArnoldDriver.halfPrecision";
	setAttr "defaultArnoldDriver.halfPrecision" 1;
	editRenderLayerAdjustment "defaultArnoldDriver.tiled";
	setAttr "defaultArnoldDriver.tiled" 0;
	editRenderLayerAdjustment "defaultArnoldDriver.autocrop";
	setAttr "defaultArnoldDriver.autocrop" 1;
	editRenderLayerAdjustment "defaultArnoldRenderOptions.AASamples";
	setAttr "defaultArnoldRenderOptions.AASamples" 4;
}

skRenderTools_Anorld_Occ();