//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc hfAnimReconnectAnimCurveForSet()
{
	string $sel[] = `ls -sl`;
	string $buff[]  =stringToStringArray($sel[0],":");
	string $pre = $buff[0]+":";
	string $animCurves[]  = `ls -type animCurve ($pre+"*")`;
	for($ac in $animCurves)
	{
	    clear $buff;
	    $buff = stringToStringArray($ac,"_");
	    string $old = substituteAllString($ac,("_"+$buff[size($buff)-1]),"");
	    string $attr = $buff[size($buff)-1];
	    string $new = substituteAllString($old,":",":*")+"*";
	    string $objs[]=  `ls -type transform $new`;
	    if (size($objs))
	    {
		catchQuiet(`connectAttr -f ($ac+".output") ($objs[0]+"."+$attr)`);
	    }
	}
}