//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc hfCGGlassMat()
{
	string $sel[] = `ls -sl`;
	if (!size($sel))
		error "没有选择任何物体!";

	
	string $glassSG = "Glass:pasted__mia_material_x_passes23SG";
	if (!objExists($glassSG))
		file -import -type "mayaBinary" -ra true -namespace "Glass" -options "v=0"  -pr -loadReferenceDepth "all" "//file-cluster/GDC/Projects/HeroFactory/HeroFactory_Scratch/Modeling/glass shader/re_glass/glasss_1140.mb"; 
	
	catch(`sets -e -forceElement $glassSG $sel`);
}