

global proc s100prodManagerCreateBaseDepFolders(string $prod, string $optionScn,  string $optionSqn)
{
if(size($optionScn)>0 && size($optionSqn)>0)
	{
	global string $base_prodFilesSystem ;

	$optionScn = `optionMenu -q -value $optionScn`;
	$optionSqn = `optionMenu -q -value $optionSqn`;
	print ("\n" + $optionScn);
	//string $Lib[] ;
	//$Lib = `s100AMsourceBaseDept`;

	$pathScn = $base_prodFilesSystem + "folderList/001_deptScn/"   ;
		if($optionScn == "custom")
			$pathScn += "folderCreate.txt";
		else
			$pathScn += $optionScn+".txt";

	$pathSqn = $base_prodFilesSystem + "folderList/002_deptSqc/"   ;
		if($optionSqn == "custom")
			$pathSqn += "folderCreate.txt";
		else
			$pathSqn += $optionSqn + ".txt";


	$listFolderAddOpen = `fopen $pathScn "r"`;
	$pathScn = `fread $listFolderAddOpen $pathScn`;
	fclose $listFolderAddOpen;

	$listFolderAddOpen = `fopen $pathSqn "r"`;
	$pathSqn = `fread $listFolderAddOpen $pathSqn`;
	fclose $listFolderAddOpen;


	$path = $base_prodFilesSystem + "prod/"   ;
	$path += $prod;

	$deptScn= "/deptScn.txt";
	$deptSqc= "/deptSqc.txt";




	//string $s = stringArrayToString($Lib,"|");

		$fileId=`fopen ($path + $deptScn) "w" `;
		$write =`fwrite $fileId $pathScn`;
		fclose $fileId ;

		$fileId=`fopen ($path +$deptSqc) "w" `;
		$write =`fwrite $fileId $pathSqn`;
		fclose $fileId ;
	}
}



