import maya .cmds as cmds
cmds.setAttr('Lf_Arm5_jnt.tx',keyable = True,lock=0)
cmds.setAttr('Lf_Arm5_jnt.ty',keyable = True,lock=0)
cmds.setAttr('Lf_Arm5_jnt.tz',keyable = True,lock=0)
cmds.disconnectAttr('Lf_elbow_drv_jnt.translateX','Lf_Arm5_jnt.translateX')
cmds.setAttr('LfupArm2_bend.tx',keyable = True,lock=0)
cmds.setAttr('LfupArm2_bend.ty',keyable = True,lock=0)
cmds.setAttr('LfupArm2_bend.tz',keyable = True,lock=0)
cmds.setAttr('LfupArm2_bend.visibility',keyable = True,lock=0)
cmds.setAttr('LfupArm2_bend.visibility',1)
cmds.group('LfupArm2_bend',n='LfupArm2_bend_GRP')
cmds.pointConstraint('Lf_elbow_drv_jnt','LfupArm2_bend_GRP',mo=1)
cmds.delete('LfupArm2_bend_pointConstraint1')
cmds.setAttr('Lfelbow0_bend.tx',keyable = True,lock=0)
cmds.setAttr('Lfelbow0_bend.ty',keyable = True,lock=0)
cmds.setAttr('Lfelbow0_bend.tz',keyable = True,lock=0)
cmds.setAttr('Lfelbow0_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Lfelbow0_bend.visibility',0)
cmds.pointConstraint('LfupArm2_bend','Lfelbow0_bend',mo=1)
#####cmds.group('Lf_Arm5_jnt',n='Lf_Arm5_jnt_GRP')
cmds.pointConstraint('LfupArm2_bend','Lf_Arm5_jnt',mo=1)


cmds.setAttr('Rt_Arm5_jnt.tx',keyable = True,lock=0)
cmds.setAttr('Rt_Arm5_jnt.ty',keyable = True,lock=0)
cmds.setAttr('Rt_Arm5_jnt.tz',keyable = True,lock=0)
cmds.disconnectAttr('Rt_elbow_drv_jnt.translateX','Rt_Arm5_jnt.translateX')
cmds.setAttr('RtupArm2_bend.tx',keyable = True,lock=0)
cmds.setAttr('RtupArm2_bend.ty',keyable = True,lock=0)
cmds.setAttr('RtupArm2_bend.tz',keyable = True,lock=0)
cmds.setAttr('RtupArm2_bend.visibility',keyable = True,lock=0)
cmds.setAttr('RtupArm2_bend.visibility',1)
cmds.group('RtupArm2_bend',n='RtupArm2_bend_GRP')
cmds.pointConstraint('Rt_elbow_drv_jnt','RtupArm2_bend_GRP',mo=1)
cmds.delete('RtupArm2_bend_pointConstraint1')
cmds.setAttr('Rtelbow0_bend.tx',keyable = True,lock=0)
cmds.setAttr('Rtelbow0_bend.ty',keyable = True,lock=0)
cmds.setAttr('Rtelbow0_bend.tz',keyable = True,lock=0)
cmds.setAttr('Rtelbow0_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Rtelbow0_bend.visibility',0)
cmds.pointConstraint('RtupArm2_bend','Rtelbow0_bend',mo=1)
############cmds.group('Rt_Arm5_jnt',n='Rt_Arm5_jnt_GRP')
cmds.pointConstraint('RtupArm2_bend','Rt_Arm5_jnt',mo=1)



cmds.setAttr('Lf_Leg5_jnt.tx',keyable = True,lock=0)
cmds.setAttr('Lf_Leg5_jnt.ty',keyable = True,lock=0)
cmds.setAttr('Lf_Leg5_jnt.tz',keyable = True,lock=0)
cmds.disconnectAttr('Lf_knee_drv_jnt.translateX','Lf_Leg5_jnt.translateX')
cmds.setAttr('Lfleg2_bend.tx',keyable = True,lock=0)
cmds.setAttr('Lfleg2_bend.ty',keyable = True,lock=0)
cmds.setAttr('Lfleg2_bend.tz',keyable = True,lock=0)
cmds.setAttr('Lfleg2_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Lfleg2_bend.visibility',1)
cmds.group('Lfleg2_bend',n='Lfleg2_bend_GRP')
cmds.pointConstraint('Lf_knee_drv_jnt','Lfleg2_bend_GRP',mo=1)
cmds.delete('Lfleg2_bend_pointConstraint1')
cmds.setAttr('Lfknee0_bend.tx',keyable = True,lock=0)
cmds.setAttr('Lfknee0_bend.ty',keyable = True,lock=0)
cmds.setAttr('Lfknee0_bend.tz',keyable = True,lock=0)
cmds.setAttr('Lfknee0_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Lfknee0_bend.visibility',0)
cmds.pointConstraint('Lfleg2_bend','Lfknee0_bend',mo=1)
###############cmds.group('Lf_Leg5_jnt',n='Lf_Leg5_jnt_GRP')
cmds.pointConstraint('Lfleg2_bend','Lf_Leg5_jnt',mo=1)


cmds.setAttr('Rt_Leg5_jnt.tx',keyable = True,lock=0)
cmds.setAttr('Rt_Leg5_jnt.ty',keyable = True,lock=0)
cmds.setAttr('Rt_Leg5_jnt.tz',keyable = True,lock=0)
cmds.disconnectAttr('Rt_knee_drv_jnt.translateX','Rt_Leg5_jnt.translateX')
cmds.setAttr('Rtleg2_bend.tx',keyable = True,lock=0)
cmds.setAttr('Rtleg2_bend.ty',keyable = True,lock=0)
cmds.setAttr('Rtleg2_bend.tz',keyable = True,lock=0)
cmds.setAttr('Rtleg2_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Rtleg2_bend.visibility',1)
cmds.group('Rtleg2_bend',n='Rtleg2_bend_GRP')
cmds.pointConstraint('Rt_knee_drv_jnt','Rtleg2_bend_GRP',mo=1)
cmds.delete('Rtleg2_bend_pointConstraint1')
cmds.setAttr('Rtknee0_bend.tx',keyable = True,lock=0)
cmds.setAttr('Rtknee0_bend.ty',keyable = True,lock=0)
cmds.setAttr('Rtknee0_bend.tz',keyable = True,lock=0)
cmds.setAttr('Rtknee0_bend.visibility',keyable = True,lock=0)
cmds.setAttr('Rtknee0_bend.visibility',0)
cmds.pointConstraint('Rtleg2_bend','Rtknee0_bend',mo=1)
##########cmds.group('Rt_Leg5_jnt',n='Rt_Leg5_jnt_GRP')
cmds.pointConstraint('Rtleg2_bend','Rt_Leg5_jnt',mo=1)

cmds.connectAttr('waist_Ctrl.second_vis','LfupArm2_bend.visibility' )
cmds.connectAttr('waist_Ctrl.second_vis','RtupArm2_bend.visibility' )
cmds.connectAttr('waist_Ctrl.second_vis','Lfleg2_bend.visibility' )
cmds.connectAttr('waist_Ctrl.second_vis','Rtleg2_bend.visibility' )

