import maya.cmds as cmds
LR = ['Lf','Rt','Lf1','Lf2','Rt1','Rt2']
for lr in LR:
    if cmds.objExists(lr+'_Arm5_jnt'):
        cmds.setAttr(lr+'_Arm5_jnt.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'_Arm5_jnt.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'_Arm5_jnt.tz',keyable = True,lock=0)
        cmds.disconnectAttr(lr+'_elbow_drv_jnt.translateX',lr+'_Arm5_jnt.translateX')
        cmds.setAttr(lr+'upArm2_bend.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'upArm2_bend.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'upArm2_bend.tz',keyable = True,lock=0)
        cmds.setAttr(lr+'upArm2_bend.visibility',keyable = True,lock=0)
        cmds.setAttr(lr+'upArm2_bend.visibility',1)
        cmds.group(lr+'upArm2_bend',n=lr+'upArm2_bend_GRP')
        cmds.pointConstraint(lr+'_elbow_drv_jnt',lr+'upArm2_bend_GRP',mo=1)
        cmds.delete(lr+'upArm2_bend_pointConstraint1')
        cmds.setAttr(lr+'elbow0_bend.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'elbow0_bend.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'elbow0_bend.tz',keyable = True,lock=0)
        cmds.setAttr(lr+'elbow0_bend.visibility',keyable = True,lock=0)
        cmds.setAttr(lr+'elbow0_bend.visibility',0)
        cmds.pointConstraint(lr+'upArm2_bend',lr+'elbow0_bend',mo=1)
        #####cmds.group(lr+'_Arm5_jnt',n=lr+'_Arm5_jnt_GRP')
        cmds.pointConstraint(lr+'upArm2_bend',lr+'_Arm5_jnt',mo=1)
        cmds.connectAttr('waist_Ctrl.second_vis',lr+'upArm2_bend.visibility' )  
              
    if cmds.objExists(lr+'_Leg5_jnt'):
        cmds.setAttr(lr+'_Leg5_jnt.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'_Leg5_jnt.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'_Leg5_jnt.tz',keyable = True,lock=0)
        cmds.disconnectAttr(lr+'_knee_drv_jnt.translateX',lr+'_Leg5_jnt.translateX')
        cmds.setAttr(lr+'leg2_bend.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'leg2_bend.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'leg2_bend.tz',keyable = True,lock=0)
        cmds.setAttr(lr+'leg2_bend.visibility',keyable = True,lock=0)
        cmds.setAttr(lr+'leg2_bend.visibility',1)
        cmds.group(lr+'leg2_bend',n=lr+'leg2_bend_GRP')
        cmds.pointConstraint(lr+'_knee_drv_jnt',lr+'leg2_bend_GRP',mo=1)
        cmds.delete(lr+'leg2_bend_pointConstraint1')
        cmds.setAttr(lr+'knee0_bend.tx',keyable = True,lock=0)
        cmds.setAttr(lr+'knee0_bend.ty',keyable = True,lock=0)
        cmds.setAttr(lr+'knee0_bend.tz',keyable = True,lock=0)
        cmds.setAttr(lr+'knee0_bend.visibility',keyable = True,lock=0)
        cmds.setAttr(lr+'knee0_bend.visibility',0)
        cmds.pointConstraint(lr+'leg2_bend',lr+'knee0_bend',mo=1)
        ###############cmds.group(lr+'_Leg5_jnt',n=lr+'_Leg5_jnt_GRP')
        cmds.pointConstraint(lr+'leg2_bend',lr+'_Leg5_jnt',mo=1)
        cmds.connectAttr('waist_Ctrl.second_vis',lr+'leg2_bend.visibility' )