// Copyright (C) 1997-2006 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// Maya Mel UI Configuration File.
//
//  This script is machine generated.  Edit at your own risk.
//
//

if (`paneLayout -exists $gMainPane`) {

	global int $gUseScenePanelConfig;
	int    $useSceneConfig = $gUseScenePanelConfig;
	int    $menusOkayInPanels = `optionVar -q allowMenusInPanels`;	int    $nVisPanes = `paneLayout -q -nvp $gMainPane`;
	int    $nPanes = 0;
	string $editorName;
	string $panelName;
	string $itemFilterName;
	string $panelConfig;

	//
	//  get current state of the UI
	//
	sceneUIReplacement -update $gMainPane;

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "allRenderClassifications"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 1 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 1 -neg 0 -t ""  allRenderClassifications;
	} else {
		itemFilterRender -edit -s 1 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 1 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "animCurveFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 1 -neg 0 -t "Examine connections"  animCurveFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 1 -neg 0 -t "Examine connections"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "cameraShapes"`;
	if ("" == $itemFilterName) {
		itemFilter -bt "camera" -bt "camera" -neg 0 -t ""  cameraShapes;
	} else {
		itemFilter -edit -cbt -bt "camera" -bt "camera" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "exclLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 1 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  exclLightShapes;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 1 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "expressionFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 0 -he 1 -hc 0 -neg 0 -t "Examine connections"  expressionFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 0 -he 1 -hc 0 -neg 0 -t "Examine connections"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "ignoreLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 1 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  ignoreLightShapes;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 1 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "imagePlanes"`;
	if ("" == $itemFilterName) {
		itemFilter -bt "imagePlane" -bt "imagePlane" -neg 0 -t ""  imagePlanes;
	} else {
		itemFilter -edit -cbt -bt "imagePlane" -bt "imagePlane" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "keyableFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 1 -srt 0 -he 0 -hc 0 -neg 0 -t ""  keyableFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 1 -srt 0 -he 0 -hc 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "lightShapesPostProcs"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  lightShapesPostProcs;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "lightShapesTextures"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  lightShapesTextures;
	} else {
		itemFilterRender -edit -s 0 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "linkedLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 1 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  linkedLightShapes;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 1 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "materials"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 1 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  materials;
	} else {
		itemFilterRender -edit -s 1 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "materialsTexturesLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 1 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  materialsTexturesLightShapes;
	} else {
		itemFilterRender -edit -s 1 -at 1 -t2d 0 -t3d 0 -tp 0 -l 1 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "noShaderGlow"`;
	if ("" == $itemFilterName) {
		itemFilter -bt "shaderGlow" -bt "shaderGlow" -neg 1 -t ""  noShaderGlow;
	} else {
		itemFilter -edit -cbt -bt "shaderGlow" -bt "shaderGlow" -neg 1 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "nonExclLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 1 -pp 0 -run 0 -neg 0 -t ""  nonExclLightShapes;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 1 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "postProc"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  postProc;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 1 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "renderUtilities"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 1 -neg 0 -t ""  renderUtilities;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 1 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "rotateFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "rotateFilterScript" -ss "" -neg 0 -t "Transform attributes"  rotateFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "rotateFilterScript" -ss "" -neg 0 -t "Transform attributes"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "scaleFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "scaleFilterScript" -ss "" -neg 0 -t "Transform attributes"  scaleFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "scaleFilterScript" -ss "" -neg 0 -t "Transform attributes"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "scaleRotateTranslateFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 1 -he 0 -hc 0 -neg 0 -t "Transform attributes"  scaleRotateTranslateFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 1 -he 0 -hc 0 -neg 0 -t "Transform attributes"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "shadingGroups"`;
	if ("" == $itemFilterName) {
		itemFilter -bt "shadingEngine" -bt "shadingEngine" -neg 0 -t ""  shadingGroups;
	} else {
		itemFilter -edit -cbt -bt "shadingEngine" -bt "shadingEngine" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "textures"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 1 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  textures;
	} else {
		itemFilterRender -edit -s 0 -at 1 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "textures2d"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  textures2d;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterRender" "textures3d"`;
	if ("" == $itemFilterName) {
		itemFilterRender -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  textures3d;
	} else {
		itemFilterRender -edit -s 0 -at 0 -t2d 0 -t3d 0 -tp 0 -l 0 -ll 0 -nil 0 -exl 0 -nxl 0 -pp 0 -run 0 -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilterAttr" "translateFilter"`;
	if ("" == $itemFilterName) {
		itemFilterAttr -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "translateFilterScript" -ss "" -neg 0 -t "Transform attributes"  translateFilter;
	} else {
		itemFilterAttr -edit -h 0 -r 0 -w 0 -k 0 -srt 0 -he 0 -hc 0 -bs "translateFilterScript" -ss "" -neg 0 -t "Transform attributes"  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "usesImageFile"`;
	if ("" == $itemFilterName) {
		itemFilter -bs "thingUsesImageFile" -ss "thingsUseImageFile" -neg 0 -t ""  usesImageFile;
	} else {
		itemFilter -edit -cbt -bs "thingUsesImageFile" -ss "thingsUseImageFile" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "SGLightShapes"`;
	if ("" == $itemFilterName) {
		itemFilter -un "lightShapesPostProcs" "shadingGroups" -neg 0 -t ""  SGLightShapes;
	} else {
		itemFilter -edit -cbt -un "lightShapesPostProcs" "shadingGroups" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "SGLightShapesTextures"`;
	if ("" == $itemFilterName) {
		itemFilter -un "lightShapesTextures" "shadingGroups" -neg 0 -t ""  SGLightShapesTextures;
	} else {
		itemFilter -edit -cbt -un "lightShapesTextures" "shadingGroups" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "allRenderNodes"`;
	if ("" == $itemFilterName) {
		itemFilter -un "allRenderClassifications" "shadingGroups" -neg 0 -t ""  allRenderNodes;
	} else {
		itemFilter -edit -cbt -un "allRenderClassifications" "shadingGroups" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "basicRenderNodes"`;
	if ("" == $itemFilterName) {
		itemFilter -un "materialsTexturesLightShapes" "shadingGroups" -neg 0 -t ""  basicRenderNodes;
	} else {
		itemFilter -edit -cbt -un "materialsTexturesLightShapes" "shadingGroups" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "cameraShapesImagePlanes"`;
	if ("" == $itemFilterName) {
		itemFilter -un "cameraShapes" "imagePlanes" -neg 0 -t ""  cameraShapesImagePlanes;
	} else {
		itemFilter -edit -cbt -un "cameraShapes" "imagePlanes" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "lightShapes"`;
	if ("" == $itemFilterName) {
		itemFilter -in "lightShapesPostProcs" "noShaderGlow" -neg 0 -t ""  lightShapes;
	} else {
		itemFilter -edit -cbt -in "lightShapesPostProcs" "noShaderGlow" -neg 0 -t ""  $itemFilterName;
	}

	$itemFilterName = `sceneUIReplacement -getNextFilter "itemFilter" "texturesSG"`;
	if ("" == $itemFilterName) {
		itemFilter -un "textures" "shadingGroups" -neg 0 -t ""  texturesSG;
	} else {
		itemFilter -edit -cbt -un "textures" "shadingGroups" -neg 0 -t ""  $itemFilterName;
	}

	$panelName = `sceneUIReplacement -getNextPanel "modelPanel" (localizedPanelLabel("Top View"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `modelPanel -unParent -l (localizedPanelLabel("Top View")) -mbv $menusOkayInPanels `;
			$editorName = $panelName;
            modelEditor -e 
                -camera "top" 
                -useInteractiveMode 0
                -displayLights "default" 
                -displayAppearance "wireframe" 
                -activeOnly 0
                -wireframeOnShaded 0
                -bufferMode "double" 
                -twoSidedLighting 1
                -backfaceCulling 0
                -xray 0
                -displayTextures 0
                -textureMaxSize 1024
                -sortTransparent 1
                -nurbsCurves 1
                -nurbsSurfaces 1
                -polymeshes 1
                -planes 1
                -lights 1
                -cameras 1
                -joints 1
                -ikHandles 1
                -deformers 1
                -dynamics 1
                -locators 1
                -dimensions 1
                -handles 1
                -pivots 1
                -textures 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		modelPanel -edit -l (localizedPanelLabel("Top View")) -mbv $menusOkayInPanels  $panelName;
		$editorName = $panelName;
        modelEditor -e 
            -camera "top" 
            -useInteractiveMode 0
            -displayLights "default" 
            -displayAppearance "wireframe" 
            -activeOnly 0
            -wireframeOnShaded 0
            -bufferMode "double" 
            -twoSidedLighting 1
            -backfaceCulling 0
            -xray 0
            -displayTextures 0
            -textureMaxSize 1024
            -sortTransparent 1
            -nurbsCurves 1
            -nurbsSurfaces 1
            -polymeshes 1
            -planes 1
            -lights 1
            -cameras 1
            -joints 1
            -ikHandles 1
            -deformers 1
            -dynamics 1
            -locators 1
            -dimensions 1
            -handles 1
            -pivots 1
            -textures 1
            $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "modelPanel" (localizedPanelLabel("Side View"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `modelPanel -unParent -l (localizedPanelLabel("Side View")) -mbv $menusOkayInPanels `;
			$editorName = $panelName;
            modelEditor -e 
                -camera "side" 
                -useInteractiveMode 0
                -displayLights "default" 
                -displayAppearance "wireframe" 
                -activeOnly 0
                -wireframeOnShaded 0
                -bufferMode "double" 
                -twoSidedLighting 1
                -backfaceCulling 0
                -xray 0
                -displayTextures 0
                -textureMaxSize 1024
                -sortTransparent 1
                -nurbsCurves 1
                -nurbsSurfaces 1
                -polymeshes 1
                -planes 1
                -lights 1
                -cameras 1
                -joints 1
                -ikHandles 1
                -deformers 1
                -dynamics 1
                -locators 1
                -dimensions 1
                -handles 1
                -pivots 1
                -textures 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		modelPanel -edit -l (localizedPanelLabel("Side View")) -mbv $menusOkayInPanels  $panelName;
		$editorName = $panelName;
        modelEditor -e 
            -camera "side" 
            -useInteractiveMode 0
            -displayLights "default" 
            -displayAppearance "wireframe" 
            -activeOnly 0
            -wireframeOnShaded 0
            -bufferMode "double" 
            -twoSidedLighting 1
            -backfaceCulling 0
            -xray 0
            -displayTextures 0
            -textureMaxSize 1024
            -sortTransparent 1
            -nurbsCurves 1
            -nurbsSurfaces 1
            -polymeshes 1
            -planes 1
            -lights 1
            -cameras 1
            -joints 1
            -ikHandles 1
            -deformers 1
            -dynamics 1
            -locators 1
            -dimensions 1
            -handles 1
            -pivots 1
            -textures 1
            $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "modelPanel" (localizedPanelLabel("Front View"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `modelPanel -unParent -l (localizedPanelLabel("Front View")) -mbv $menusOkayInPanels `;
			$editorName = $panelName;
            modelEditor -e 
                -camera "persp" 
                -useInteractiveMode 0
                -displayLights "default" 
                -displayAppearance "wireframe" 
                -activeOnly 0
                -wireframeOnShaded 0
                -bufferMode "double" 
                -twoSidedLighting 1
                -backfaceCulling 0
                -xray 0
                -displayTextures 0
                -textureMaxSize 1024
                -sortTransparent 1
                -nurbsCurves 1
                -nurbsSurfaces 1
                -polymeshes 1
                -planes 1
                -lights 1
                -cameras 1
                -joints 1
                -ikHandles 1
                -deformers 1
                -dynamics 1
                -locators 1
                -dimensions 1
                -handles 1
                -pivots 1
                -textures 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		modelPanel -edit -l (localizedPanelLabel("Front View")) -mbv $menusOkayInPanels  $panelName;
		$editorName = $panelName;
        modelEditor -e 
            -camera "persp" 
            -useInteractiveMode 0
            -displayLights "default" 
            -displayAppearance "wireframe" 
            -activeOnly 0
            -wireframeOnShaded 0
            -bufferMode "double" 
            -twoSidedLighting 1
            -backfaceCulling 0
            -xray 0
            -displayTextures 0
            -textureMaxSize 1024
            -sortTransparent 1
            -nurbsCurves 1
            -nurbsSurfaces 1
            -polymeshes 1
            -planes 1
            -lights 1
            -cameras 1
            -joints 1
            -ikHandles 1
            -deformers 1
            -dynamics 1
            -locators 1
            -dimensions 1
            -handles 1
            -pivots 1
            -textures 1
            $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "modelPanel" (localizedPanelLabel("Persp View"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `modelPanel -unParent -l (localizedPanelLabel("Persp View")) -mbv $menusOkayInPanels `;
			$editorName = $panelName;
            modelEditor -e 
                -camera "persp" 
                -useInteractiveMode 0
                -displayLights "default" 
                -displayAppearance "wireframe" 
                -activeOnly 0
                -wireframeOnShaded 0
                -bufferMode "double" 
                -twoSidedLighting 1
                -backfaceCulling 0
                -xray 0
                -displayTextures 0
                -textureMaxSize 1024
                -sortTransparent 1
                -nurbsCurves 1
                -nurbsSurfaces 1
                -polymeshes 1
                -planes 1
                -lights 1
                -cameras 1
                -joints 1
                -ikHandles 1
                -deformers 1
                -dynamics 1
                -locators 1
                -dimensions 1
                -handles 1
                -pivots 1
                -textures 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		modelPanel -edit -l (localizedPanelLabel("Persp View")) -mbv $menusOkayInPanels  $panelName;
		$editorName = $panelName;
        modelEditor -e 
            -camera "persp" 
            -useInteractiveMode 0
            -displayLights "default" 
            -displayAppearance "wireframe" 
            -activeOnly 0
            -wireframeOnShaded 0
            -bufferMode "double" 
            -twoSidedLighting 1
            -backfaceCulling 0
            -xray 0
            -displayTextures 0
            -textureMaxSize 1024
            -sortTransparent 1
            -nurbsCurves 1
            -nurbsSurfaces 1
            -polymeshes 1
            -planes 1
            -lights 1
            -cameras 1
            -joints 1
            -ikHandles 1
            -deformers 1
            -dynamics 1
            -locators 1
            -dimensions 1
            -handles 1
            -pivots 1
            -textures 1
            $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "outlinerPanel" (localizedPanelLabel("Outliner"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `outlinerPanel -unParent -l (localizedPanelLabel("Outliner")) -mbv $menusOkayInPanels `;
			$editorName = $panelName;
            outlinerEditor -e 
                -mainListConnection "worldList" 
                -selectionConnection "modelList" 
                -showShapes 0
                -showAttributes 0
                -showConnected 0
                -showAnimCurvesOnly 0
                -autoExpand 0
                -showDagOnly 1
                -ignoreDagHierarchy 0
                -expandConnections 0
                -showUnitlessCurves 1
                -showCompounds 1
                -showNumericAttrsOnly 0
                -highlightActive 1
                -autoSelectNewObjects 0
                -doNotSelectNewObjects 0
                -dropIsParent 1
                -transmitFilters 0
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		outlinerPanel -edit -l (localizedPanelLabel("Outliner")) -mbv $menusOkayInPanels  $panelName;
		$editorName = $panelName;
        outlinerEditor -e 
            -mainListConnection "worldList" 
            -selectionConnection "modelList" 
            -showShapes 0
            -showAttributes 0
            -showConnected 0
            -showAnimCurvesOnly 0
            -autoExpand 0
            -showDagOnly 1
            -ignoreDagHierarchy 0
            -expandConnections 0
            -showUnitlessCurves 1
            -showCompounds 1
            -showNumericAttrsOnly 0
            -highlightActive 1
            -autoSelectNewObjects 0
            -doNotSelectNewObjects 0
            -dropIsParent 1
            -transmitFilters 0
            $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "graphEditor" (localizedPanelLabel("Graph Editor"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "graphEditor" -l (localizedPanelLabel("Graph Editor")) -mbv $menusOkayInPanels `;

			$editorName = ($panelName+"OutlineEd");
            outlinerEditor -e 
                -mainListConnection "activeList" 
                -selectionConnection "graphEditor1FromOutliner" 
                -highlightConnection "activeList" 
                -showShapes 1
                -showAttributes 1
                -showConnected 1
                -showAnimCurvesOnly 1
                -autoExpand 1
                -showDagOnly 0
                -ignoreDagHierarchy 0
                -expandConnections 1
                -showUnitlessCurves 1
                -showCompounds 0
                -showNumericAttrsOnly 1
                -highlightActive 0
                -autoSelectNewObjects 1
                -doNotSelectNewObjects 0
                -dropIsParent 1
                -transmitFilters 1
                $editorName;

			$editorName = ($panelName+"GraphEd");
            animCurveEditor -e 
                -mainListConnection "graphEditor1FromOutliner" 
                -displayKeys 1
                -displayTangents 0
                -displayActiveKeys 0
                -displayActiveKeyTangents 1
                -displayInfinities 1
                -autoFit 0
                -snapTime "none" 
                -snapValue "none" 
                -smoothness "fine" 
                -resultSamples 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Graph Editor")) -mbv $menusOkayInPanels  $panelName;

			$editorName = ($panelName+"OutlineEd");
            outlinerEditor -e 
                -mainListConnection "activeList" 
                -selectionConnection "graphEditor1FromOutliner" 
                -highlightConnection "activeList" 
                -showShapes 1
                -showAttributes 1
                -showConnected 1
                -showAnimCurvesOnly 1
                -autoExpand 1
                -showDagOnly 0
                -ignoreDagHierarchy 0
                -expandConnections 1
                -showUnitlessCurves 1
                -showCompounds 0
                -showNumericAttrsOnly 1
                -highlightActive 0
                -autoSelectNewObjects 1
                -doNotSelectNewObjects 0
                -dropIsParent 1
                -transmitFilters 1
                $editorName;

			$editorName = ($panelName+"GraphEd");
            animCurveEditor -e 
                -mainListConnection "graphEditor1FromOutliner" 
                -displayKeys 1
                -displayTangents 0
                -displayActiveKeys 0
                -displayActiveKeyTangents 1
                -displayInfinities 1
                -autoFit 0
                -snapTime "none" 
                -snapValue "none" 
                -smoothness "fine" 
                -resultSamples 1
                $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "dopeSheetPanel" (localizedPanelLabel("Dope Sheet"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "dopeSheetPanel" -l (localizedPanelLabel("Dope Sheet")) -mbv $menusOkayInPanels `;

			$editorName = ($panelName+"OutlineEd");
            outlinerEditor -e 
                -mainListConnection "activeList" 
                -selectionConnection "dopeSheetPanel1OutlinerSelection" 
                -showShapes 1
                -showAttributes 1
                -showConnected 1
                -showAnimCurvesOnly 0
                -autoExpand 1
                -showDagOnly 0
                -ignoreDagHierarchy 0
                -expandConnections 1
                -showUnitlessCurves 0
                -showCompounds 1
                -showNumericAttrsOnly 1
                -highlightActive 0
                -autoSelectNewObjects 0
                -doNotSelectNewObjects 1
                -dropIsParent 1
                -transmitFilters 0
                $editorName;

			$editorName = ($panelName+"DopeSheetEd");
            dopeSheetEditor -e 
                -mainListConnection "dopeSheetPanel1FromOutliner" 
                -highlightConnection "dopeSheetPanel1OutlinerSelection" 
                -displayKeys 1
                -displayTangents 0
                -displayActiveKeys 0
                -displayActiveKeyTangents 0
                -displayInfinities 0
                -autoFit 0
                -snapTime "integer" 
                -snapValue "none" 
                -outliner "dopeSheetPanel1OutlineEd" 
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Dope Sheet")) -mbv $menusOkayInPanels  $panelName;

			$editorName = ($panelName+"OutlineEd");
            outlinerEditor -e 
                -mainListConnection "activeList" 
                -selectionConnection "dopeSheetPanel1OutlinerSelection" 
                -showShapes 1
                -showAttributes 1
                -showConnected 1
                -showAnimCurvesOnly 0
                -autoExpand 1
                -showDagOnly 0
                -ignoreDagHierarchy 0
                -expandConnections 1
                -showUnitlessCurves 0
                -showCompounds 1
                -showNumericAttrsOnly 1
                -highlightActive 0
                -autoSelectNewObjects 0
                -doNotSelectNewObjects 1
                -dropIsParent 1
                -transmitFilters 0
                $editorName;

			$editorName = ($panelName+"DopeSheetEd");
            dopeSheetEditor -e 
                -mainListConnection "dopeSheetPanel1FromOutliner" 
                -highlightConnection "dopeSheetPanel1OutlinerSelection" 
                -displayKeys 1
                -displayTangents 0
                -displayActiveKeys 0
                -displayActiveKeyTangents 0
                -displayInfinities 0
                -autoFit 0
                -snapTime "integer" 
                -snapValue "none" 
                -outliner "dopeSheetPanel1OutlineEd" 
                $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "hyperGraphPanel" (localizedPanelLabel("Hypergraph"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "hyperGraphPanel" -l (localizedPanelLabel("Hypergraph")) -mbv $menusOkayInPanels `;

			$editorName = ($panelName+"HyperGraphEd");
            hyperGraph -e 
                -orientation "horiz" 
                -animateTransition 0
                -showShapes 0
                -showDeformers 0
                -showExpressions 0
                -showConstraints 0
                -showUnderworld 0
                -showInvisible 0
                -transitionFrames 1
                -freeform 0
                -imageEnabled 0
                -graphType "DAG" 
                -updateSelection 1
                -updateNodeAdded 1
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Hypergraph")) -mbv $menusOkayInPanels  $panelName;

			$editorName = ($panelName+"HyperGraphEd");
            hyperGraph -e 
                -orientation "horiz" 
                -animateTransition 0
                -showShapes 0
                -showDeformers 0
                -showExpressions 0
                -showConstraints 0
                -showUnderworld 0
                -showInvisible 0
                -transitionFrames 1
                -freeform 0
                -imageEnabled 0
                -graphType "DAG" 
                -updateSelection 1
                -updateNodeAdded 1
                $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}


	$panelName = `sceneUIReplacement -getNextScriptedPanel "polyTexturePlacementPanel" (localizedPanelLabel("UV Texture Editor"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "polyTexturePlacementPanel" -l (localizedPanelLabel("UV Texture Editor")) -mbv $menusOkayInPanels `;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("UV Texture Editor")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "multiListerPanel" (localizedPanelLabel("Multilister"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "multiListerPanel" -l (localizedPanelLabel("Multilister")) -mbv $menusOkayInPanels `;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Multilister")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "renderWindowPanel" (localizedPanelLabel("Render View"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "renderWindowPanel" -l (localizedPanelLabel("Render View")) -mbv $menusOkayInPanels `;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Render View")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "shadingGroupEditor" (localizedPanelLabel("Shading Group Editor"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "shadingGroupEditor" -l (localizedPanelLabel("Shading Group Editor")) -mbv $menusOkayInPanels `;
			$editorName = ($panelName+"ShadingGroupEd");
            setEditor -e $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Shading Group Editor")) -mbv $menusOkayInPanels  $panelName;

			$editorName = ($panelName+"ShadingGroupEd");
            setEditor -e 
                $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "setEditor" (localizedPanelLabel("Set Editor"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "setEditor" -l (localizedPanelLabel("Set Editor")) -mbv $menusOkayInPanels `;

			$editorName = ($panelName+"SetEd");
            setEditor -e 
                $editorName;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Set Editor")) -mbv $menusOkayInPanels  $panelName;

			$editorName = ($panelName+"SetEd");
            setEditor -e 
                $editorName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "blendShapePanel" (localizedPanelLabel("Blend Shape"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			blendShapePanel -unParent -l (localizedPanelLabel("Blend Shape")) -mbv $menusOkayInPanels ;
		}
	} else {
		$label = `panel -q -label $panelName`;
		blendShapePanel -edit -l (localizedPanelLabel("Blend Shape")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextScriptedPanel "dynRelEdPanel" (localizedPanelLabel("Dynamic Relationships"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			$panelName = `scriptedPanel -unParent  -type "dynRelEdPanel" -l (localizedPanelLabel("Dynamic Relationships")) -mbv $menusOkayInPanels `;
		}
	} else {
		$label = `panel -q -label $panelName`;
		scriptedPanel -edit -l (localizedPanelLabel("Dynamic Relationships")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}

	$panelName = `sceneUIReplacement -getNextPanel "devicePanel" (localizedPanelLabel("Devices"))`;
	if ("" == $panelName) {
		if ($useSceneConfig) {
			devicePanel -unParent -l (localizedPanelLabel("Devices")) -mbv $menusOkayInPanels ;
		}
	} else {
		$label = `panel -q -label $panelName`;
		devicePanel -edit -l (localizedPanelLabel("Devices")) -mbv $menusOkayInPanels  $panelName;
		if (!$useSceneConfig) {
			panel -e -l $label $panelName;
		}
	}


	if ($useSceneConfig) {
        string $configName = `getPanel -cwl (localizedPanelLabel("Current Layout"))`;
        if ("" != $configName) {
			panelConfiguration -edit -label (localizedPanelLabel("Current Layout"))
				-sc false
				-configString "paneLayout -e -cn \"single\" -ps 1 100 100 $gMainPane;"
				-removeAllPanels
				-ap false
					(localizedPanelLabel("Front View"))
					"modelPanel"
					"$panelName = `modelPanel -unParent -l (localizedPanelLabel(\"Front View\")) -mbv $menusOkayInPanels `;\n$editorName = $panelName;\nmodelEditor -e \n    -camera \"persp\" \n    -useInteractiveMode 0\n    -displayLights \"default\" \n    -displayAppearance \"wireframe\" \n    -activeOnly 0\n    -wireframeOnShaded 0\n    -bufferMode \"double\" \n    -twoSidedLighting 1\n    -backfaceCulling 0\n    -xray 0\n    -displayTextures 0\n    -textureMaxSize 1024\n    -sortTransparent 1\n    -nurbsCurves 1\n    -nurbsSurfaces 1\n    -polymeshes 1\n    -planes 1\n    -lights 1\n    -cameras 1\n    -joints 1\n    -ikHandles 1\n    -deformers 1\n    -dynamics 1\n    -locators 1\n    -dimensions 1\n    -handles 1\n    -pivots 1\n    -textures 1\n    $editorName"
					"modelPanel -edit -l (localizedPanelLabel(\"Front View\")) -mbv $menusOkayInPanels  $panelName;\n$editorName = $panelName;\nmodelEditor -e \n    -camera \"persp\" \n    -useInteractiveMode 0\n    -displayLights \"default\" \n    -displayAppearance \"wireframe\" \n    -activeOnly 0\n    -wireframeOnShaded 0\n    -bufferMode \"double\" \n    -twoSidedLighting 1\n    -backfaceCulling 0\n    -xray 0\n    -displayTextures 0\n    -textureMaxSize 1024\n    -sortTransparent 1\n    -nurbsCurves 1\n    -nurbsSurfaces 1\n    -polymeshes 1\n    -planes 1\n    -lights 1\n    -cameras 1\n    -joints 1\n    -ikHandles 1\n    -deformers 1\n    -dynamics 1\n    -locators 1\n    -dimensions 1\n    -handles 1\n    -pivots 1\n    -textures 1\n    $editorName"
				$configName;

            setNamedPanelLayout (localizedPanelLabel("Current Layout"));
        }

        panelHistory -e -clear mainPanelHistory;
        setFocus `paneLayout -q -p1 $gMainPane`;
        sceneUIReplacement -deleteRemaining;
        sceneUIReplacement -clear;
	}

	playbackOptions -min 0 -max 900 ;
	rangeControl -e -min 0 -max 900 rangeControl1 ;
	timeControl -e -displaySound 1 -sound wrong $gPlayBackSlider;
}
