// Copyright (C) 1997-2006 Autodesk, Inc., and/or its licensors.
// All rights reserved.
//
// The coded instructions, statements, computer programs, and/or related
// material (collectively the "Data") in these files contain unpublished
// information proprietary to Autodesk, Inc. ("Autodesk") and/or its licensors,
// which is protected by U.S. and Canadian federal copyright law and by
// international treaties.
//
// The Data is provided for use exclusively by You. You have the right to use,
// modify, and incorporate this Data into other products for purposes authorized 
// by the Autodesk software license agreement, without fee.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. AUTODESK
// DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
// INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE 
// OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL AUTODESK AND/OR ITS
// LICENSORS BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
// DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF AUTODESK AND/OR ITS
// LICENSORS HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

// LICENSE AGREEMENT
// 
// PLEASE READ THIS AGREEMENT CAREFULLY.
// 
// ALIAS IS WILLING TO LICENSE THIS SOFTWARE AND ANY
// DOCUMENTATION THAT MAY BE PROVIDED THEREWITH (THE "SOFTWARE") TO YOU
// ONLY ON THE CONDITION THAT ALL OF THE TERMS CONTAINED IN THIS LICENSE
// AGREEMENT ARE ACCEPTED.
// 
// This is a license agreement and NOT an agreement for sale.
// Alias continues to own all copies of the Software and all
// intellectual property rights therein.  Your rights to use the Software
// are specified in this Agreement, and Alias retains all rights
// not expressly granted to you.
// 
// Alias grants to you a nonöexclusive, non-transferable license
// to use the Software, subject to the terms and conditions of this
// Agreement. Without the prior written consent of A|W, you may not: (i)
// copy, modify or transfer copies of the Software (except one copy for
// backup purposes); (ii) disassemble, decompile or unlock, reverse
// engineer or translate, or in any manner decode the Software for any
// reason; (iii) place the Software onto a server so that it is accessible
// via a public network such as the Internet; or (iv) sublicense, lease,
// distribute or rent the Software.  Alias and/or its suppliers
// and/or its licensors retain all right, title, and interest in and to the
// Software (including, without limitation, all trade secrets and
// intellectual property rights therein) furnished by Alias and
// to any backup copy thereof made by you.   You shall not remove any
// copyright or proprietary rights notice included in with the Software and
// shall reproduce all such notices on any backup copies made of the
// Software made by you.
// 
// THE SOFTWARE IS PROVIDED AS IS.  ALIAS DOES NOT WARRANT THAT
// THE SOFTWARE WILL MEET YOUR REQUIREMENTS OR THAT ITS OPERATION WILL BE
// UNINTERRUPTED OR ERROR-FREE. ALIAS MAKES NO WARRANTIES,
// EXPRESS, IMPLIED OR ARISING BY CUSTOM OR TRADE USAGE WITH RESPECT TO THE
// SOFTWARE, AND WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, TO THE
// EXTENT PERMITTED BY APPLICABLE LAW, SPECIFICALLY DISCLAIMS ANY IMPLIED
// WARRANTIES OF TITLE, NONINFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
// PARTICULAR PURPOSE. ALIAS SHALL HAVE NO LIABILITY IN CONTRACT,
// TORT OR OTHERWISE ARISING OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
// THIS AGREEMENT.  NO SUPPORT OR MAINTENANCE OF ANY KIND IS PROVIDED WITH
// RESPECT TO THE SOFTWARE.
// 
// This Agreement is effective until terminated.   If you breach of any of
// your obligations hereunder, Alias may terminate this Agreement
// and the license provided hereunder by giving written notice of
// termination to you, effective immediately upon its sending.  Upon
// termination, you must immediately cease all use of the Software and
// destroy all copies of the Software in your possession, custody or
// control.  This Agreement shall be governed by the substantive law of the
// Province of Ontario, Canada, without regard to its conflicts of law
// principles.  This Agreement shall be binding upon and enure to the
// benefit of the parties and their respective successors, assigns and
// legal representatives, provided, however, that your rights and
// obligations hereunder may not be assigned, sublicensed or otherwise
// transferred in whole or in part, without the prior written consent of
// Alias.
// 
// Limited. All rights reserved.
//
//
//  Alias Script File
//  MODIFY THIS AT YOUR OWN RISK
//
// ----------------------------------------------------------------------
// 
// edgeLength 
//
// Description: calculates length of poly edges
// 
// 
// Opens floating window displaying the length of selected poly edges, 
// Nurbs curves, or isoparms. Diplays combined length for multiple 
// selections. Invalid selections are ignored. Window updates with 
// selection change, until DONE is pressed. 
// 
// 
// 
// Creation Date: ( 08/14/00 ) 
// Last Update: () 
// 
// Input Arguments: NONE 
// 
// works with Maya Versions: 3.0

proc edgeLength () 
{ 
float $eLength = 0; 
float $totalLength = 0; 
string $sel; 
if( (`window -exists edgeLength_UI`) == true ) 
{ 
deleteUI edgeLength_UI ; 
//windowPref -remove edgeLength_UI; 
}
// list only poly edges, nurbs curves and isoparms 
string $selList[] = `filterExpand -sm 32 -sm 9 -sm 11 -sm 45` ; 
// calculate the total length of all valid selections 
for ($sel in $selList) 
{ 
$eLength = `arclen $sel`; 
$totalLength += $eLength; 
}
string $niceString = `swFloatToNiceString($totalLength)`;
string $edgeLengthString = "Total Length: " + $niceString + " "; 
if (size($selList) == 0) 
$edgeLengthString = "Nothing valid selected"; 
// create floating window 
window -rtf on -s off -title EdgeLength edgeLength_UI ; 
columnLayout;
text -label $edgeLengthString ; 
global string $edgeLength_btn1; 
button -label " DONE " -command killEdgeLength; 
showWindow edgeLength_UI ;
}



proc killEdgeLength() 
{ 
// get list of script jobs 
$jobList = `scriptJob -lj`; 
// get size of list 
int $last = `size $jobList` - 1; 
// extract last job from list 
string $lastJob = $jobList[$last]; 
// make sure last job is edgeLength 
string $match = match("edgeLength",$lastJob); 
if ($match == "edgeLength") 
{ 
// extract job ID number from string 
string $ID = `substring $lastJob 1 3`; 
string $match = match(":",$ID); 
// check to see if colan is attached to string 
if ($match == ":") 
{ 
$ID = `substring $lastJob 1 2`; 
} 
int $IDnum = $ID; 
scriptJob -kill $IDnum ; 
if (`window -exists edgeLength_UI`) deleteUI edgeLength_UI; 
} 
else print("ERROR : wrong job"); 
}

proc string swFloatToNiceString(float $swFloat) 
{ 
string $swReturn; 
string $swPrintData[];
if (($swFloat < 0.000001) && ( $swFloat > -0.000001)) $swReturn = "0.000000"; 
else
{ 
string $swTmp = $swFloat; 
tokenize $swTmp "." $swPrintData; 
if (size ($swPrintData) == 2) 
{
$swPrintData[1] = $swPrintData[1] + "000000"; 
$swReturn = $swPrintData[0] + "." + `substring $swPrintData[1] 1 4`; 
} 
else 
$swReturn = $swPrintData[0] + ".000000"; 
} 
return $swReturn;
}

edgeLength; 
int $edgeLength_ID = `scriptJob -e "SelectionChanged" edgeLength` ;


