global proc nj2016_xionngm()
{
	if(`window -ex xionngmwindow`)
	deleteUI xionngmwindow;
	window -t "choice" -wh 285 50 xionngmwindow;
	columnLayout;

	rowLayout -numberOfColumns 4;
	text -label "ctrat";
	textField -tx "0" min;
	text -label "end";
	textField -tx "10" max;
	setParent ..;
	button -label "Bake"-w 270 -command " bakehirl";
	showWindow xionngmwindow;

}

proc bakehirl()
{
string $sel[]=`ls -sl`;
string $aa[]=`duplicate -rr`;
select -r $sel ;
select -add $aa ;
blendShape -n "bake";
setAttr ("bake."+$aa[0]) 1;
setAttr ($sel[0]+".visibility") 0;
setKeyframe ($sel[0]+".visibility");

select -r $aa ;
float $MIN=`textField -q -tx min`;
float $MAX=`textField -q -tx max`;
bakeResults -simulation true -t ($MIN+":"+$MAX) -sampleBy 1 -disableImplicitControl true -preserveOutsideKeys true -sparseAnimCurveBake false -removeBakedAttributeFromLayer false -bakeOnOverrideLayer false -minimizeRotation true -controlPoints true -shape true $aa;
}
nj2016_xionngm();

