//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-7-8
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-7-8
//	Description:		如果有选择则删除选择物体的smooth节点，如果没选择则删除所有物体的smooth节点
//				
//////////////////////////////////////////////////////////


global proc slDelSmoothNode()
{
	string $objs[]= `ls -type polySmoothFace`;
	string $sel[] = `ls -sl -l`;
	if(size($sel))
	{
		for($sl in $sel)
		{
			string $history[] = `listHistory $sl`;
			for($his in $history)
			{
				if(nodeType($his) == "polySmoothFace")
					deleteIfNotReferenced($his);

			}
		}
	}
	else
	{
		for ($item in $objs)
		{
			deleteIfNotReferenced($item);

		}
	}
}