//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slAnimReplaceSLA()
{
	string $files[] = `idmtFileDialog -m -f "file(*.dat)|*.dat||"`;
	for ($file in $files)
	{
		string $replaced = "";
		$fileId = `fopen $file r`;
			string $nextLine = `fgetline $fileId`;
			$nextLine = `fgetline $fileId`;
			while (size($nextLine) > 0 )
			{
				if (`match "End..." $nextLine` == "")
				{
					string $start = `match "[^.]*" $nextLine`;
					string $newLine = `substituteAllString $nextLine ($start+".") ($start+" ")`;;
					$replaced += $newLine;
				}
				$nextLine = `fgetline $fileId`;
			}
		fclose $fileId;

		string $newfile = `substituteAllString $file ".dat" ""`;
		$fileId = `fopen $newfile w`;
			fprint $fileId $replaced;
		fclose $fileId;

		print ($file+"   done");
	}
}