//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2011-1-21
//
//	Update/Change: WansHoulOng
//	Last Updated: 2011-1-21
//	Description:
//			删除指定路径下所有子目录中的，指定文件夹
//			$folder       ------------   指定的路径
//			$delFoder  ------------   指定删除的文件夹名
//				
//////////////////////////////////////////////////////////

global proc slDelHistoryFolder(string $folder,string $delFolder)
{
	string $children[] = `getFileList -fld $folder`;
	for ($child in $children)
	{
		string $grandchildren[] = `getFileList -fld ($folder+"/"+$child+"/")`;
		if (size($grandchildren))
		{
			if ($delFolder == $child)
			{
				print ("del:---"+$folder+"/"+$child+"/\n");
				slDelFiles ($folder+"/"+$child+"/");
			}
			else
			{
				slDelHistoryFolder ($folder+"/"+$child+"/",$delFolder);
			}
		}
	}
}

global proc slDelFiles(string $folder)
{
	string $files[] = `getFileList -fld $folder`;
	for ($f in $files)
	{
		int $delFile = `sysFile -del ($folder+$f)`;
		if (!$delFile)
		{
			int $delFolder = `sysFile -red ($folder+$f)`;
			if (!$delFolder)
			{
				slDelFiles ($folder+$f+"/");
			}
		}
	}
	
	sysFile -red $folder;
}