//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-8-6
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:   根据贴图名字重命名节点名字
//			      如  TXT_ep001_bg01_color 节点则其使用的贴图为  wo_ep001_bg01_color_2k.tga  其中 wo为项目缩写，2k为贴图大小标识
//////////////////////////////////////////////////////////


global proc slModelRenameFileNode()
{
	string $fileNodes[] = `ls -type file`;
	for ($fn in $fileNodes)
	{
		setAttr ($fn+".filterType ") 0;
		string $imageName = `getAttr ($fn+".fileTextureName")`;
		string $buff[] = stringToStringArray($imageName,"/\\");
		string $buff1[] = stringToStringArray($buff[size($buff)-1],"_");

		string $rename = `substring $buff[size($buff)-1] (size($buff1[0])+2) (size($buff[size($buff)-1]))`;
		$rename = "TXT_"+ `substring $rename 1 (size($rename)-size($buff1[size($buff1)-1])-1)`;
		
		rename $fn $rename;
	}

	slModelRenameMaterial;
}

global proc slModelRenameMaterial()
{
	string $fileNodes[] = `ls -type file`;
	for ($fn in $fileNodes)
	{
		string $sources[] = `listConnections -s 0 -d 1 -p 1 ($fn+".outColor")`;
		if (size($sources) && endsWith($sources[0],".color"))
		{
			setAttr ($fn+".diffuse") 0;
			setAttr ($fn+".ambientColor") -type double3 1 1 1 ;	
			
			string $buff[];
			int $num = `tokenize $fn "_" $buff`;
			string $rename = "SHD_"+$buff[2];
			string $shd = `substring $sources[0] 1 (size($sources[0])-6)`;
			//print ($shd+"---"+$rename+"\n");
			
			
			rename $shd $rename;
		}
	}
}
