//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc string[] woAnimSelectToolsControls(string $part,string $side)
{
	string $allpart[] = {"earL","earR","armL","armR","legL","legR","handL","handR","feetL","feetR","body","head","master","special"};
	
	string $controls[];
	string $condition = $part+$side;
	switch ($condition)
	{
		case "earL" :
			$controls = {"ear_L_ctrl01","ear_L_ctrl02","ear_L_ctrl03","ear_L_ctrl04"};
			$controls = stringArrayCatenate($controls,{"ear_ctrl_L","ear_ctrl_L02","ear_ctrl_L03"});//sevenpoint
			$controls = stringArrayCatenate($controls,{"Lf_ear1_Ctrl","Lf_ear2_Ctrl","Lf_ear3_Ctrl"});//whitetail
			$controls = stringArrayCatenate($controls,{"Leftear_ctrl1","Leftear_ctrl2"});//evil
			break;
		case "earR" :
			$controls = {"ear_R_ctrl01","ear_R_ctrl02","ear_R_ctrl03","ear_R_ctrl04"};
			$controls = stringArrayCatenate($controls,{"ear_ctrl_R01","ear_ctrl_R02","ear_ctrl_R03"});//sevenpoint
			$controls = stringArrayCatenate($controls,{"Rt_ear1_Ctrl","Rt_ear2_Ctrl","Rt_ear3_Ctrl"});//whitetail
			$controls = stringArrayCatenate($controls,{"Rightear_ctrl1","Rightear_ctrl2"});//evil
			break;
		case "armL" :
			$controls = {"LfArm_Wrist_FK","LfArm_Elbow_FK","LfArm_UpArm_FK","Lf_shoulder","LfArm_Pole_ctrl","LfArm_Wrist_IK","LfArm_Switch"};
			$controls = stringArrayCatenate($controls,{"LeftLeg3_shoulder_ctrl1","LeftLeg3_Leg_Pole_Vector","LeftLeg3_IK_Leg","LeftLeg3_Toe_Pivot","LeftLeg3_Heel_Pivot","LeftLeg3_Upper_Leg","LeftLeg3_Lower_Leg","LeftLeg3_Foot","LeftLeg3_Toe"});//evil
			break;
		case "armR" :
			$controls = {"RtArm_Wrist_FK","RtArm_Elbow_FK","RtArm_UpArm_FK","Rt_shoulder","RtArm_Pole_ctrl","RtArm_Wrist_IK","RtArm_Switch"};
			$controls = stringArrayCatenate($controls,{"RightLeg3_shoulder_ctrl1","RightLeg3_Leg_Pole_Vector","RightLeg3_IK_Leg","RightLeg3_Toe_Pivot","RightLeg3_Heel_Pivot","RightLeg3_Upper_Leg","RightLeg3_Lower_Leg","RightLeg3_Foot","RightLeg3_Toe"});//evil
			break;
		case "legL" :
			$controls = {"LfLeg_Pole_ctrl","LfLeg_foot","LfLeg_Leg_IK","LfLeg_Leg_FK","LfLeg_Knee_FK","LfLeg_Ankle_FK","LfLegLeg_ball_FK","LfLeg_Switch"};
			$controls = stringArrayCatenate($controls,{"LeftLeg5_shoulder_ctrl1","LeftLeg5_Leg_Pole_Vector","LeftLeg5_IK_Leg","LeftLeg5_Toe_Pivot","LeftLeg5_Heel_Pivot","LeftLeg5_Upper_Leg","LeftLeg5_Lower_Leg","LeftLeg5_Foot","LeftLeg5_Toe"});//evil
			break;
		case "legR" :
			$controls = {"RtLeg_Pole_ctrl","RtLeg_foot","RtLeg_Leg_IK","RtLeg_Leg_FK","RtLeg_Knee_FK","RtLeg_Ankle_FK","RtLegLeg_ball_FK","RtLeg_Switch"};
			$controls = stringArrayCatenate($controls,{"RightLeg5_shoulder_ctrl1","RightLeg5_Leg_Pole_Vector","RightLeg5_IK_Leg","RightLeg5_Toe_Pivot","RightLeg5_Heel_Pivot","RightLeg5_Upper_Leg","RightLeg5_Lower_Leg","RightLeg5_Foot","RightLeg5_Toe"});//evil
			break;
		case "handL" :
			$controls = {"Lf_index1","Lf_index2","Lf_mid1","Lf_mid2","Lf_ring1","Lf_ring2","Lf_thumb1","Lf_thumb2","Lf_thumb3"};
			$controls = stringArrayCatenate($controls,{"LeftToe1_Toe_control","LeftToe2_Toe_control","LeftToe3_Toe_control","LeftToe4_Toe_control"});//evil
			$controls = stringArrayCatenate($controls,{"Lf_pinky1","Lf_pinky2","Lf_pinky3","Lf_index3","Lf_mid3","Lf_ring3","Lf_thumb3"});//wellie
			break;
		case "handR" :
			$controls = {"Rt_index1","Rt_index2","Rt_mid1","Rt_mid2","Rt_ring1","Rt_ring2","Rt_thumb1","Rt_thumb2","Rt_thumb3"};
			$controls = stringArrayCatenate($controls,{"RightToe1_Toe_control","RightToe2_Toe_control","RightToe3_Toe_control","RightToe4_Toe_control"});//evil
			$controls = stringArrayCatenate($controls,{"Rt_pinky1","Rt_pinky2","Rt_pinky3","Rt_index3","Rt_mid3","Rt_ring3","Rt_thumb3"});//wellie
			break;
		case "feetL" :
			$controls = {"Lf_Toe_index1","Lf_Toe_index2","Lf_Toe_index3","Lf_Toe_mid1","Lf_Toe_mid2","Lf_Toe_mid3","Lf_Toe_ring1","Lf_Toe_ring2","Lf_Toe_ring3","Lf_Toe_thumb1","Lf_Toe_thumb2","Lf_Toe_thumb3"};
			$controls = stringArrayCatenate($controls,{"LeftToe12_Toe_control","LeftToe13_Toe_control","LeftToe14_Toe_control"});//evil
			break;
		case "feetR" :
			$controls = {"Rt_Toe_index1","Rt_Toe_index2","Rt_Toe_mid1","Rt_Toe_mid2","Rt_Toe_ring1","Rt_Toe_ring2","Rt_Toe_thumb1","Rt_Toe_thumb2"};
			$controls = stringArrayCatenate($controls,{"RightToe12_Toe_control","RightToe13_Toe_control","RightToe14_Toe_control"});//evil
			break;
		case "body" :
			$controls = {"mid_waist_ikCtrl","top_waist_ikCtrl","waist_FK2_ctrl","waist_FK1_ctrl","root_waist_ikCtrl","waist_Ctrl","bingy_Ctrl"};
			$controls = stringArrayCatenate($controls,{"Spine2_Pelvis_IK","Spine2_Middle_IK","Spine2_Torso_IK","Spine2_Pelvis_FK","Spine2_Middle_FK","Spine2_Torso_FK","Upper_Body"});//evil
			break;
		case "head" :
			$controls = {"head_ctrl","neck_FK_ctrl"};
			$controls = stringArrayCatenate($controls,{"Head2_FK","Head2_Neck","Head2_Head_IK"});//evil
			break;
		case "master" :
			$controls = {"Character","Master"};
			break;
		case "special" :
			$controls = {"Tail_Base_Control","Tail_Control","TailSeg2_Control","TailSeg3_Control","TailSeg4_Control"};//evil
			break;
		case "all" :
			for ($pt in $allpart)
			{
				$controls = stringArrayCatenate($controls,woAnimSelectToolsControls($pt,""));
			}
			break;
	}
	return $controls;
}

global proc woAnimSelectToolsCommand(string $part,string $side,string $opm,string $shift)
{
	string $char = `optionMenu -q -v $opm`;
	string $pre= `substituteAllString $char "Character" ""`;

	string $add = " -r ";
	int $chbValue = `checkBox -q -v $shift`;
	if ($chbValue)
	{
		$add = " -tgl ";
	}
	string $cmd = "select "+$add;
	
	string $controls[] = woAnimSelectToolsControls($part,$side);
	string $charControls[]={};
	for ($ct in $controls)
	{
		$charControls[size($charControls)] = $pre+$ct;
		if (objExists($pre+$ct))
		{
			$cmd += $pre+$ct+" ";
		}
	}

	//sets -e -nw -forceElement test $controls[$i];
	eval($cmd);
}

global proc woAnimSelectTools()
{
	if (`window -ex woAnimSelectToolsUI`)
	{
		deleteUI woAnimSelectToolsUI;
	}

	window -title "Woodlies 选择工具" -s false woAnimSelectToolsUI;
		columnLayout ;
			string $opm = `optionMenu -label "Character:"`;
				menuItem -l "character";
				woAnimSelectToolsGetChar($opm);
			string $row1 = `rowColumnLayout -nc 2 -cs 2 50`;
				string $but1 = `button -l "刷新角色列表" -h 30 -c ("woAnimSelectToolsGetChar(\""+$opm+"\")")`;
				string $chb1 = `checkBox -l "shift功能" -h 30`;
			setParent ..;
			separator -height 10 -style "double" -w 400;
			string $row2 = `rowColumnLayout -nc 2 -cs 2 50 `;
				string $b1 = `button -l "左耳" -h 30 -c ("woAnimSelectToolsCommand(\"ear\",\"L\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b2 = `button -l "右耳" -h 30 -c ("woAnimSelectToolsCommand(\"ear\",\"R\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b3 = `button -l "左臂" -h 30 -c ("woAnimSelectToolsCommand(\"arm\",\"L\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b4 = `button -l "右臂" -h 30 -c ("woAnimSelectToolsCommand(\"arm\",\"R\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b5 = `button -l "左腿" -h 30 -c ("woAnimSelectToolsCommand(\"leg\",\"L\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b6 = `button -l "右腿" -h 30 -c ("woAnimSelectToolsCommand(\"leg\",\"R\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b7 = `button -l "左手" -h 30 -c ("woAnimSelectToolsCommand(\"hand\",\"L\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b8 = `button -l "右手" -h 30 -c ("woAnimSelectToolsCommand(\"hand\",\"R\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b9 = `button -l "左脚" -h 30 -c ("woAnimSelectToolsCommand(\"feet\",\"L\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b10 = `button -l "右脚" -h 30 -c ("woAnimSelectToolsCommand(\"feet\",\"R\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b11 = `button -l "身体" -h 30 -c ("woAnimSelectToolsCommand(\"body\",\"\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b12 = `button -l "头" -h 30 -c ("woAnimSelectToolsCommand(\"head\",\"\",\""+$opm+"\",\""+$chb1+"\")")`;
				string $b13 = `button -l "全选" -h 30 -c ("woAnimSelectToolsCommand(\"all\",\"\",\""+$opm+"\",\""+$chb1+"\")")`;
			setParent ..;
	showWindow woAnimSelectToolsUI;
	window -e -w 280 -h 310 woAnimSelectToolsUI;
}

global proc woAnimSelectToolsGetChar(string $opm)
{
	string $chars[] = `ls "*Character" "*:*Character" "*:*:*Character" "*:*:*:*Character"`;
	string $oldChars[] = `optionMenu -q -ill $opm`;
	deleteUI $oldChars;
	for ($char in $chars)
	{
		menuItem -l $char -p $opm;
	}
}

global proc woAnimSelectToolsSelectAll()
{
	
}
