//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc woAnimRepairTexture()
{
	string $files[] = `ls -type file`;
	for ($file in $files)
	{
		string $image = `getAttr ($file+".fileTextureName")`;
		if (!`filetest -r $image` && `referenceQuery -inr $file`)
		{
			string $buff[] = stringToStringArray($image,"\\/");
			string $imagename = $buff[size($buff)-1];
			
			string $reffile = `referenceQuery -f $file`;
			$buff = stringToStringArray($reffile,"\\/");
			$buff=stringToStringArray($buff[size($buff)-1],"_");
			string $char = $buff[1];

			string $path = "//file-cluster/gdc/Projects/Woodlies/Project/sourceimages/characters/"+$char+"/"+$imagename;
			if (`filetest -r $path`)
			{
				setAttr -type "string" ($file+".fileTextureName") $path;
			}
		}
	}
}