//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-3-25
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-3-25
//	Description:
//				
//////////////////////////////////////////////////////////

global proc woRenderLineLayerZZJ()
{
	if (!`pluginInfo -query -loaded "Mayatomr.mll"`) loadPlugin "Mayatomr.mll";
	miCreateDefaultNodes();
	miCreateOtherOptionsNodesForURG();	
	
	
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}	
	string $objShape[] = `ls -sl`;
	string $renderLayer = `createRenderLayer -name "inLine" -makeCurrent -noRecurse $objShape`;
	
	
	editRenderLayerGlobals -currentRenderLayer $renderLayer;
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	setAttr defaultRenderGlobals.currentRenderer -type "string" "mentalRay" ;

	/*//contours shader
	string $contours = `shadingNode -asShader surfaceShader -n propContours`;
	string $contoursSG = `sets -renderable true -noSurfaceShader true -empty -name propContoursSG`;
	connectAttr -f ($contours+".outColor") ($contoursSG+".surfaceShader");
	setAttr ($contours+".outColor") -type double3 1 1 1 ;
	setAttr ($contoursSG+".miContourEnable") 1;
	setAttr ($contoursSG+".miContourColor") -type double3 0 0 0 ;
	setAttr ($contoursSG+".miContourRelativeWidth") 1;
	setAttr ($contoursSG+".miContourWidth") 0.05;

	sets -e -forceElement $contoursSG $objShape;*/
	
	string $sg[] = `ls -type shadingEngine`;
	for ($item in $sg)
	{
		setAttr ($item + ".miContourEnable") 1;
		setAttr ($item + ".miContourRelativeWidth") 1;
		setAttr ($item + ".miContourWidth") 0.05;
		setAttr ($item + ".miContourColor") -type double3 0 0 0;
		setAttr ($item + ".miContourEnable") 1;
		setAttr ($item + ".miContourEnable") 1;
	}


	//renderSetting setup
	editRenderLayerAdjustment "miDefaultFramebuffer.contourEnable";
	setAttr "miDefaultFramebuffer.contourEnable" 1;
	setAttr "miDefaultFramebuffer.contourSamples" 3;
	setAttr "miDefaultFramebuffer.contourFilter" 2;
	setAttr "miDefaultFramebuffer.contourClearImage" 1;
	setAttr "miDefaultFramebuffer.contourClearColor" -type double3 1 1 1 ;

	string $contrast = `mrCreateCustomNode -asUtility "" contour_contrast_function_levels`;
	string $store = `mrCreateCustomNode -asUtility "" contour_store_function`;
	editRenderLayerAdjustment "miDefaultOptions.contourContrast";
	defaultNavigation -ce -source $contrast -destination miDefaultOptions.contourContrast;
	editRenderLayerAdjustment "miDefaultOptions.contourStore";
	defaultNavigation -ce -source $store -destination miDefaultOptions.contourStore;
	setAttr "miDefaultOptions.maxSamples" 3;

	setAttr ($contrast+".ndelta") 5;
	setAttr ($contrast+".zdelta") 5;
	setAttr ($contrast+".diff_index") 0;
	setAttr ($contrast+".diff_mat") 1;
	setAttr ($contrast+".contrast") 0;
	setAttr ($contrast+".diff_label") 0;
	
	select -cl;
}