//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-1-7
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-1-7
//	Description:
//				
//////////////////////////////////////////////////////////

global proc woRenderColorLayer()
{
	// turn default render layer off
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}
	
	// Put All geometry into render layers
	string $objShape[] = `ls -sl`;
	
	string $charPre = woRenderGetCharPre();
	string $buff[];
	int $num = `tokenize $charPre "_" $buff`;
	string $layerName = `substring $buff[1] 8 (size($buff[1]))`;
	//print $layerName;

	string $renderLayer = `createRenderLayer -name ($layerName+"_color") -makeCurrent`;
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	editRenderLayerMembers -noRecurse $renderLayer $objShape `ls -lights`;

}

