//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-6-4
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-6-4
//	Description:
//				
//////////////////////////////////////////////////////////

global proc woRenderToolsLayout()
{
	/*
	string $version = `zwAboutVersion`;
	if ((float)$version <2014.0 )
	{
		if (!`pluginInfo -query -loaded "Mayatomr.mll"`) loadPlugin "Mayatomr.mll";
		miCreateDefaultNodes();
		source "//file-cluster/GDC/Resource/Support/Maya/2012/scripts/mentalrayUI.mel";
		miCreateOtherOptionsNodesForURG();
	}
	*/
	//Hanhong 修改21014-03-22（原因maya2014 mr问题）
	
	string $path = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\icons\\StrawBerry\\Render\\";
	string $newPath = substituteAllString(`getenv "DEV_PATH"`, "/", "\\") + "\\Maya\\projects\\Woodlies\\import\\";
	
	if (`window -ex woRenderToolsLayoutUI`)
	{
		deleteUI woRenderToolsLayoutUI;
	}
	
	window -title "Woodlies Render Tools                             WHO" -in "WOW RT" -menuBar true  -mxb false -s true  -resizeToFitChildren true woRenderToolsLayoutUI;
		menu -label "Help";
			menuItem -label "Help on Render Tools..." -command "";

		string $mainColumnLayout = `columnLayout -adjustableColumn true -rs 10 woRenderToolsLayoutUI_main`;

			string $mainImage = `symbolButton -image ($newPath+"Woodlies.bmp") -command ""`;

			// Mini Tools
			string $LittleTools = `frameLayout -label "Little Tools" -labelAlign "top" -cl true  -cll true  -borderStyle "etchedIn" woRenderToolsLayoutUI_test`;
				frameLayout -e -cc ("woRenderToolsLayoutFrameResize "+$LittleTools)  -ec ""  $LittleTools;
				rowColumnLayout	 -numberOfColumns 5 -cw 1 60 -cw 2 60 -cw 3 60 -cw 4 60 -cw 5 60;
					button -h 25 -l "Refresh"		-c "eyRenderRehyperShade"		-ann "刷新场景材质(重连物体材质)";
					button -h 25 -l "LightFog"		-c "woRenderToolsLayoutImportLightFog"		-ann "导入灯光雾";
					button -h 25 -l "CharLight"	-c "woRenderToolsLayoutImportCharLight"		-ann "导入角色灯光（如果选择了角色控制器则自动约束）";
					button -h 25 -l "Show"		-c "ezRenderShow"		;
					button -h 25 -l "GetCam"		-c "source zwCameraImportExport.mel; zwGetCameraUI;"		;
				setParent ..;
			setParent ..;

			//Material Tools
			string $MaterrialTools = `frameLayout -label "Materrial Tools" -labelAlign "top" -cl true  -cll true  -borderStyle "etchedIn"`;
				frameLayout -e -cc ("woRenderToolsLayoutFrameResize "+$MaterrialTools)   -ec ""  $MaterrialTools;
				rowColumnLayout	 -numberOfRows 1 -rh 1 40;
					symbolButton -ann "ColorB"	-image ($path+"colorB.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorB\")";
					symbolButton -ann "ColorR"	-image ($path+"colorR.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorR\")";
					symbolButton -ann "ColorG"	-image ($path+"colorG.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorG\")";
					symbolButton -ann "ColorA"	-image ($path+"colorA.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"colorA\")";
					symbolButton -ann "Matte"	-image ($path+"matte.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"matte\")";
					symbolButton -ann "Depth"	-image ($path+"depth.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"depth\")";
					symbolButton -ann "Shadow" -image ($path+"shadow.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"shadow\")";
					symbolButton -ann "AO"		-image ($path+"AO.bmp")		-command "ezRenderMainLayoutMaterial_Assign(\"AO\")";
					symbolButton -ann "Lambert" -image ($path+"lambert.xpm")		-command "ezRenderMainLayoutMaterial_Assign(\"lambert\")";
					symbolButton -ann "White Surface" -image ($path+"colorA.bmp")		-command "source \"czSetRenderLayer.mel\"; whiteLayer false;";
					symbolButton -ann "White Surface with Contour" -image ($path+"Contour.bmp")		-command "source \"czSetRenderLayer.mel\"; whiteLayer true;";
				setParent ..;
			setParent ..;

			//RenderSetting 
			string $RenderSettingTools = `frameLayout -label "RenderSetting" -labelAlign "top" -cl true  -cll true  -borderStyle "etchedIn"`;
				frameLayout -e -cc ("woRenderToolsLayoutFrameResize "+$RenderSettingTools)   -ec ""  $MaterrialTools;
				rowColumnLayout	 -numberOfColumns 4 -cw 1 80 -cw 2 80 -cw 3 80  -cw 4 80;
					button -h 25 -l "Maya Software"		-c "woRenderToolsLayoutRenderSetting 1"	;
					button -h 25 -l "Mentalray"		-c "woRenderToolsLayoutRenderSetting 2"	;
					button -h 25 -l "" -vis 0;
					button -h 25 -l "" -vis 0;
					/*button -h 25 -l "远景"		-c ""	;
					button -h 25 -l "中景"		-c ""	;
					button -h 25 -l "半身"		-c ""	;
					button -h 25 -l "特写"		-c ""	;*/
				setParent ..;
			setParent ..;

			// Render Tools
			string $RenderLayerTools = `frameLayout -label "Creat RenderLayer Tools" -labelAlign "top" -cl true -cll true -cc "" -borderStyle "etchedIn"`;
				frameLayout -e -cc ("woRenderToolsLayoutFrameResize "+$RenderLayerTools)  -ec ""  $RenderLayerTools;
				rowColumnLayout -nc 6 -cw 1 20 -cw 2 20 -cw 3 120 -cw 4 50 -cw 5 20 -cw 6 120;
					separator -vis 0;
					checkBox -l "" woRenderLayer_amb;
					button -h 30 -bgc 1 0 0 -l "Amb" -c "woRenderToolsAmbLayer";
					separator -vis 0;
					checkBox -l "" woRenderLayer_color;
					button -h 30 -bgc 0 1 0 -l "Color" -c "woRenderColorLayer";
					separator -vis 0;
					checkBox -l "" woRenderLayer_idp;
					button -h 30 -bgc 1 0 0 -l "IDP" ;
					separator -vis 0;
					checkBox -l "" woRenderLayer_depth;
					button -h 30 -bgc 0 1 0 -l "Depth" -c "zwTaowaZConfirm";
					separator -vis 0;
					checkBox -l "" woRenderLayer_eyes;
					button -h 30 -bgc 1 0 0 -l "Eyes" -c "woMakeEyes";
					separator -vis 0;
					checkBox -l "" woRenderLayer_shadow;
					button -h 30 -bgc 0 1 0 -l "Shadow" -c "woRenderToolsShadowLayer";
					separator -vis 0;
					checkBox -l "" woRenderLayer_lines;
					string $b = `button -h 30 -bgc 1 0 0 -l "Lines" -c "woRenderToolsLineLayerDistance \"inLine\""`;
							popupMenu;
								menuItem -l "outLine"	-c "woRenderToolsLineLayerDistance \"outLine\"";
								//menuItem -l "inLine"	-c "woRenderToolsLineLayerDistance \"inLine\"";
					separator -vis 0;
					checkBox -l "" woRenderLayer_occshadow;
					button -h 30 -bgc 0 1 0 -l "OccShadow"  -c "woRenderToolsOccShadowLayer";
					separator -vis 0;
					checkBox -l "" -onc "woRenderToolsCheckBox 1 1" -ofc "woRenderToolsCheckBox 1 0";
					button -h 30 -bgc 1 0 0 -l "合并创建" ;
					separator -vis 0;
					checkBox -l "" -onc "woRenderToolsCheckBox 2 1" -ofc "woRenderToolsCheckBox 2 0";
					button -h 30 -bgc 0 1 0 -l "合并创建" ;
				/*//string $tab = `tabLayout  -cc ""`;
					string $tools = `rowColumnLayout -nc 2 -cw 1 145 -cw 2 145  -cs 2 5`;
						string $b1 = `button -h 30 -l "Color"			-c "woRenderColorLayer"`;
						string $b2 = `button -h 30 -l "Occlusion"		-c "woRenderOccLayer"`;
						string $b4 = `button -h 30 -l "Normal"		-c "ysNormalRenderLayer"`;
						string $b5 = `button -h 30 -l "Depth"			-c "eyDepthRenderLayer"`;
						string $b6 = `button -h 30 -l "Depth(L)"		-c "zwTaowaZConfirm"`;
						string $b7 = `button -h 30 -l "Line"			-c "woRenderToolsLayoutLineLayer"`;
							popupMenu;
								menuItem -l "outLine"	-c "woRenderLineLayer \"outLine\"";
								menuItem -l "inLine"	-c "woRenderLineLayer \"inLine\"";
						//string $b8 = `button -h 30 -l "Toon"			-c "woRenderToolsToonLayer"`;
						//string $b9 = `button -h 30 -l "Inline(new)"		-c "woRenderLineLayerZZJ"`;
						string $b10 = `button -h 30 -l "Edge"		-c "woRenderEdgeLayer"`;
						string $b11 = `button -h 30 -l "Eyes"		-c "woMakeEyes"`;
								setParent ..;
							setParent ..;
					//setParent ..;
					/*tabLayout -edit 
						-tl	$tools	"单独分层"	
					$tab;*/
				setParent ..;
			setParent ..;
			
			string $camFront	= `button -l "CLOSE"  -w 100 -h 30 -command "deleteUI woRenderToolsLayoutUI"`;
	
	showWindow woRenderToolsLayoutUI;
	window -e -w 340 -h 319 woRenderToolsLayoutUI;

	//Material Tools
	source "ezRenderMainLayoutMaterial.mel";

	//Depth
	source "eyRenderToolsUI.mel";

	if (`objExists defaultRenderGlobals`)
	{
		setAttr defaultRenderGlobals.numCpusToUse 0 ;
	}

}

global proc woRenderToolsLayoutFrameResize(string $layout)
{
	int $original = 0;
	string $children[]  = `frameLayout -q -ca $layout`;
	string $cmd = `objectTypeUI $children[0]` + " -q -h " +$children[0];
	float $height = eval($cmd);

	
	float $winHeight = `window -q -h woRenderToolsLayoutUI`;
	window -e -h ($winHeight-$height) woRenderToolsLayoutUI;

}

global proc woRenderToolsLayoutLineLayer()
{
	string $objShape[] = `ls -sl`;

	string $confirm = `confirmDialog -title "请选择距离" -b "远景" -b "中景" -b "半身" -b "特写"`;
	
	select -r $objShape;
	woRenderLineLayer "outLine" $confirm;
	print "---------------------------";
	print $confirm;
	select -r $objShape;
	woRenderLineLayer "inLine" $confirm;
}

global proc woRenderToolsToonLayer()
{
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}	
	string $objShape[] = `ls -sl`;
	string $renderLayer = `createRenderLayer -name "toonLine" -makeCurrent -noRecurse $objShape`;
}

global proc woRenderToolsLayoutImportLightFog()
{
	string $lightfog = "//file-cluster/GDC/Resource/Support/Maya/projects/Woodlies/import/wo_lightfog.mb";
	file -import -type "mayaBinary" -ra true -namespace "LightFog" -options "v=0;p=17"  -pr -loadReferenceDepth "all" $lightfog;
}

global proc woRenderToolsLayoutImportCharLight()
{
	string $char[] = `ls -sl`;
	string $charlight = "//file-cluster/GDC/Resource/Support/Maya/projects/Woodlies/import/wo_charlight.mb";
	file -import -type "mayaBinary" -ra true -namespace "CharLight" -options "v=0;p=17"  -pr -loadReferenceDepth "all" $charlight;

	if (size($char))
	{
		string $pres[] = `ls "CharLight*:*"`;
		string $buff[];
		int $num = `tokenize $pres[size($pres)-1] ":" $buff`;
		pointConstraint  -o 0 0 0  -w 1 $char[0] ($buff[0]+":Light_Group");
	}
}

global proc woRenderToolsLayoutRenderSetting(int $type)
{
	string $currentRL = `editRenderLayerGlobals -q -crl`;
	int $def=0;
	if (gmatch($currentRL,"*defaultRenderLayer"))
		$def = 1;
	switch ($type)
	{
		case 1 :
			setAttr "defaultRenderGlobals.currentRenderer" -type "string" "mayaSoftware";
			setAttr "defaultRenderQuality.edgeAntiAliasing" 0;
			setAttr "defaultRenderQuality.shadingSamples" 2;
			setAttr "defaultRenderQuality.maxShadingSamples" 8;
			setAttr "defaultRenderQuality.useMultiPixelFilter" 1;
			setAttr "defaultRenderQuality.pixelFilterType" 2;
			setAttr "defaultRenderQuality.pixelFilterWidthX" 2.2;
			setAttr "defaultRenderQuality.pixelFilterWidthY" 2.2;
			setAttr "defaultRenderQuality.redThreshold" 0.4;
			setAttr "defaultRenderQuality.greenThreshold" 0.3;
			setAttr "defaultRenderQuality.blueThreshold" 0.6;
			setAttr "defaultRenderQuality.enableRaytracing" 0;
			break;
		case 2 :
			setAttr "defaultRenderGlobals.currentRenderer" -type "string" "mentalRay" ;
			setAttr "miDefaultOptions.minSamples" 0;
			setAttr "miDefaultOptions.maxSamples" 2;
			setAttr "miDefaultOptions.filter" 2;
			setAttr "miDefaultOptions.rayTracing" 0;
			break;
		case 3 :
			setAttr "defaultRenderGlobals.currentRenderer" -type "string" "mentalRay" ;
			setAttr "miDefaultOptions.minSamples" 0;
			setAttr "miDefaultOptions.maxSamples" 2;
			setAttr "miDefaultOptions.filter" 2;
			setAttr "miDefaultOptions.rayTracing" 1;
			setAttr "miDefaultOptions.maxReflectionRays" 1;
			setAttr "miDefaultOptions.maxRefractionRays" 1;
			setAttr "miDefaultOptions.maxRayDepth" 2;
			setAttr "miDefaultOptions.maxShadowRayDepth" 2;			
			break;
	}
}

global proc woRenderToolsCheckBox(int $type ,int $on)
{
	string $ui[]={};
	switch ($type)
	{
		case 1 :
			$ui = {"woRenderLayer_amb","woRenderLayer_idp","woRenderLayer_eyes","woRenderLayer_lines"};
			break;
		case 2 :
			$ui = {"woRenderLayer_color","woRenderLayer_depth","woRenderLayer_shadow","woRenderLayer_occshadow"};
			break;
	}
	for ($item in $ui)
	{
		checkBox -e -v $on $item;
	}
}

global proc woRenderToolsAmbLayer()
{
	woRenderColorLayer();
	defaultAmbientLight(1, 0.45, 1,1,1, "0", 0,0,0, "1");
	string $light[] = `ls -sl`;
	setAttr ($light[0]+".color") -type double3 0 0 0;
	setAttr ($light[0]+".ambientShade") 1;

	string $crl = `editRenderLayerGlobals -q -crl`;
	editRenderLayerMembers -noRecurse $crl $light;

}

global proc woRenderToolsLineLayerDistance(string $type)
{
	string $objShape[] = `ls -sl`;

	string $confirm = `confirmDialog -title "请选择距离" -b "远景" -b "中景" -b "半身" -b "特写"`;
	
	select -r $objShape;
	woRenderLineLayer $type $confirm;
}

global proc woRenderToolsLineLayerDistanceSet(string $type)
{
	
}

global proc woRenderToolsShadowLayer()
{
	string $allShape[] = `ls -geometry`;
	//string $allTransform[] = `listRelatives -parent $allShape`;
	string $Top[] = `ls -sl`;
	string $shapes[] = `ls -dag $Top`;
	string $others[] = stringArrayRemove($shapes, $allShape);
	string $lightShape[] = `listRelatives -shapes $Top`;
	string $light[] = `ls -lights $lightShape`;
	int $countLights;
	// check light and selected objects
	if(size($Top) == 0)
	{
		confirmDialog -message "没有选择任何物体" -button "请选择接受投影的物体";
		return;		
	}	
	if(size($light)==0)
	{
		confirmDialog -message "没有选择灯光" -button "请选择投影灯光";
		return;
	}
	
	//Make cast render layer and overrides use background material 
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}		

	if(!(`objExists "cShadow"`))
	{
		string $cShadow = `shadingNode -asShader useBackground -name "cShadow"`;
		setAttr ($cShadow + ".reflectivity") 0;
		setAttr ($cShadow + ".reflectionLimit") 0;
		string $cShadowSG = `sets -renderable true -noSurfaceShader true -empty -name ($cShadow+"SG")`;
		connectAttr ($cShadow +".outColor") ( $cShadowSG +".surfaceShader");
		//layerEditorHandleNodeDrop "castShadow" $cShadow;
	}
	
	createRenderLayer -name "shadow";
	editRenderLayerMembers -noRecurse "shadow" $allShape;
	editRenderLayerGlobals -currentRenderLayer "shadow";
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	
	//Set up  visible attribute	
	for($item in $shapes)
	{
		if(`objExists ($item + ".primaryVisibility")`)
		{
			setAttr ($item + ".primaryVisibility") 1;
			setAttr ($item + ".castsShadows") 0;
			setAttr ($item + ".receiveShadows") 1;
		}
		sets -e -forceElement "cShadowSG" $item;
	}
	for($item in $others)
	{
		if(`objExists ($item + ".castsShadows")`)	
		{
			setAttr ($item + ".primaryVisibility") 0;
			setAttr ($item + ".castsShadows") 1;
			setAttr ($item + ".receiveShadows") 0;
		}
		sets -e -forceElement "cShadowSG" $item;
	}
}

global proc woRenderToolsOccShadowLayer()
{
	source "ezRenderMainLayoutMaterial.mel";
	
	string $allShape[] = `ls -geometry`;
	string $Top[] = `ls -sl`;
	string $shapes[] = `ls -dag $Top`;
	string $others[] = stringArrayRemove($shapes, $allShape);
	string $lightShape[] = `listRelatives -shapes $Top`;
	string $light[] = `ls -lights $lightShape`;
	int $countLights;
	if(size($Top) == 0)
	{
		confirmDialog -message "没有选择任何物体" -button "请选择接受投影的物体";
		return;		
	}	
	
	//Make cast render layer and overrides use background material 
	string $Array[] = `listConnections "renderLayerManager.renderLayerId"`;
	for($item in $Array)
	{
		if((`gmatch $item "*:*defaultRenderLayer*"`)||(`gmatch $item "*defaultRenderLayer*"`))
		setAttr ($item + ".renderable") 0;
	}		

	createRenderLayer -name "occShadow";
	editRenderLayerMembers -noRecurse "occShadow" $allShape;
	editRenderLayerGlobals -currentRenderLayer "occShadow";
	editRenderLayerAdjustment "defaultRenderGlobals.currentRenderer";
	woRenderToolsLayoutRenderSetting 3;
	
	//Set up  visible attribute	
	for($item in $shapes)
	{
		if(`objExists ($item + ".primaryVisibility")`)
		{
			setAttr ($item + ".primaryVisibility") 1;
			setAttr ($item + ".castsShadows") 0;
			setAttr ($item + ".receiveShadows") 1;
		}
		select -r $item;
		ezRenderMainLayoutMaterial_Assign "AO";
	}
	for($item in $others)
	{
		if(`objExists ($item + ".castsShadows")`)	
		{
			setAttr ($item + ".primaryVisibility") 0;
			setAttr ($item + ".castsShadows") 1;
			setAttr ($item + ".receiveShadows") 0;
		}
		select -r $item;
		ezRenderMainLayoutMaterial_Assign "AO";
	}

}