proc zzjWiCreateAmbFile()
{
	string $workSpaceDir = `workspace -q -rd` +"scenes/";
	string $fileName = `file -q -sceneName`;
	$fileName=`match "[a-z]*_[0-9]*_[0-9]*[a-z]*" $fileName`; 
	
	string $expHairNames[] = `ls -sl `;
	$expChrName = `match "wi_c[0-9]*" $expHairNames[0]`;
	$expChrName = `match "c[0-9]+" $expChrName `;
	$expChrName = zwGetCharacterNameById($expChrName);

	string $sprtAmbFileName = $workSpaceDir+$fileName+"_"+"l1"+$expChrName+"amb_lr_c001.mb";
	file -op "v=0;p=17" -typ "mayaBinary" -pr -es $sprtAmbFileName;

}
zzjWiCreateAmbFile;