//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2010-3-25
//
//	Update/Change: WansHoulOng
//	Last Updated: 2010-3-25
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slRenderCameraRender()
{
	string $cam = `lookThru -q`;
	
	float $keytimes[] = `keyframe -q -tc $cam`;
	string $times[];
	for ($k in $keytimes)
	{
		$times[size($times)] = $k;
	}
	$times = stringArrayRemoveDuplicates($times);


	string $facialDefaultPath = `fileBrowserDialog -m 4 -fc "slRenderCameraRenderCMD" -an "请选择存盘路径"`;
}

global proc slRenderCameraRenderCMD(string $filename,string $filetype)
{
	string $imagename = `file -q -sn -shn`;
	$imagename =`substring $imagename 1 (size($imagename)-3)`;
	
	
	string $cam = `lookThru -q`;
	
	float $keytimes[] = `keyframe -q -tc $cam`;
	string $times[];
	for ($k in $keytimes)
	{
		$times[size($times)] = $k;
	}
	$times = stringArrayRemoveDuplicates($times);

	string $renderLayer[] = `ls -type renderLayer`;
	string $render[];
	for ($rl in $renderLayer)
	{
		if ( `getAttr ($rl+".renderable")`)
		{
			$render[size($render)] = $rl;
		}
	}
	
	
	//setAttr defaultRenderGlobals.currentRenderer -type "string" "mayaSoftware" ;
	RenderViewWindow;
	renderWindowRenderCamera snapshot renderView $cam;
	//print ($cam+"\n");
	int $num = 10000 ;
	string $camattrs[];
	for ($t in $times)
	{
		currentTime $t;
		$num = $num+1;
		string $str = (string)$num;
		string $folder = `substring $str 2 5`;
		/*for ($rl in $render)
		{
			editRenderLayerGlobals -currentRenderLayer $rl;
			string $im = $filename+"/"+$folder+"/"+$rl+"/";
			sysFile -md $im;
		}*/
		
		
		
		//取相机参数 tx ty tz rx ry rz fl 
		string $attrcom="";
		string $attrs[] = {"tx","ty","tz","rx","ry","rz","fl"};
		for ($i=0;$i<size($attrs);$i++ )
		{
			$attrcom += getAttr ($cam+"."+$attrs[$i]);
		}

		//if (size($camattrs) == 0 || stringArrayCount($attrcom,$camattrs) ==0)
		//{
			//$camattrs[size($camattrs)] = $attrcom;
			//for ($rl in $render)
			//{
				//editRenderLayerGlobals -currentRenderLayer $rl;
				string $im = $filename+"/";
				$im = $im+$imagename+"_"+$folder;

				setAttr defaultRenderGlobals.outf 8;
				renderWindowRender redoPreviousRender renderView;
				renderWindowSaveImageCallback "renderView"  $im "JPEG";

				print ($im+"\n");
			//}

		//}
		
		

		/*for ($rl in $render)
		{
			editRenderLayerGlobals -currentRenderLayer $rl;
			string $im = $filename+"/"+$folder+"/"+$rl+"/";
			sysFile -md $im;
			$im = $im+$imagename+"_"+$rl+".iff";

			//renderWindowRender redoPreviousRender renderView;
			//renderWindowSaveImageCallback "renderView"  $im "image";

			print ($im+"\n");
		}*/
	}
	//print (size($times)+"----"+size($camattrs)+"\n");
	//print $camattrs;
}