global proc s100VRRemGuideFromAR()
{

$var = `ls -sl ` ;

$curve = $var[0] ;

$text = "Do you want to delete " + $curve + " from Auto Rig" ;

$conf = `confirmDialog -title "Confirm" -message $text
    -button "Yes" -button "No" -defaultButton "Yes"
    -cancelButton "No" -dismissString "No" `;

	if ($conf == "Yes")
	{
	s100VRRemGuideFromARCurve($curve) ;
   	}


}



global proc s100VRRemGuideFromARCurve(string $curve)
{


	$child = `listRelatives -c -type "transform" $curve ` ;
	$parent = `listRelatives -p  $curve ` ;
		if(size($child)> 0 )
			parent $child $parent ;


	$sub = substituteAllString($curve, "_curv","") ;


	$list = `ls ($sub +"*")`;
	$list2 = `listConnections $list  ` ;
	delete $list2 ;
	$list = `ls ($sub +"*")`;

	delete $list ;



 }




global proc s100VRRemDepandGuideFromARCurve(string $curve)
{




	$sub = substituteAllString($curve, "_curv","") ;

	$s = `listRelatives -s $curve` ;
	$s[1] = $curve ;

	$list = `ls ($sub +"*")`;
	$list2 = `listConnections $list  ` ;
	$list4 = stringArrayRemove($s,$list2);
	delete $list4 ;
	$list = `ls($sub +"*")`;
	$list3 = stringArrayRemove($s,$list);

	delete $list3;



 }
