global proc ezAnimShipRock()
{
	string $ship[] = `ls "*:*ss0047flagshipext_c_hi_ppflagshipext"`;
	if (!`objExists $ship[0]`)
		return ;
	
	
	string $master[] = `ls -sl`;
	for ($char in $master)
	{
		parentConstraint -mo -weight 1 $ship[0] $char;//-skipTranslate x -skipTranslate z -skipRotate x -skipRotate y -skipRotate z -weight 1 $ship[0] $char;
	}
	
	
	//float $start = `playbackOptions -q -minTime`;
	//float $end = `playbackOptions -q -maxTime`;

	int $iFrame =  43 ;
	
	float $rox = 1 ,$roz = 1;
	if (rand(-1,1)<0)	$rox = -1;
	if (rand(-1,1)<0)	$roz = -1;

	string $RXCurve[] =`keyframe -q -name ($ship[0]+".rx")`;
	if (`objExists $RXCurve[0]`)
		delete $RXCurve;
	setKeyframe -itt "spline" -ott "spline" -t $iFrame		-v 0		($ship[0]+".rx");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+46)		-v ($rox*-0.2)	($ship[0]+".rx");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+92)		-v 0		($ship[0]+".rx");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+138)	-v ($rox*0.2)	($ship[0]+".rx");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+184)	-v 0		($ship[0]+".rx");
	$RXCurve =`keyframe -q -name ($ship[0]+".rx")`;
	selectKey -r -k $RXCurve;setInfinity -pri cycle -poi cycle; select -cl;

	string $RZCurve[] =`keyframe -q -name ($ship[0]+".rz")`;
	if (`objExists $RZCurve[0]`)
		delete $RZCurve;
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame-11)		-v 0		($ship[0]+".rz");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+35)		-v ($roz*0.4)	($ship[0]+".rz");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+81)		-v 0		($ship[0]+".rz");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+127)	-v ($roz*-0.4)	($ship[0]+".rz");
	setKeyframe -itt "spline" -ott "spline" -t ($iFrame+173)	-v 0		($ship[0]+".rz");
	$RZCurve =`keyframe -q -name ($ship[0]+".rz")`;
	selectKey -r -k $RZCurve;setInfinity -pri cycle -poi cycle; select -cl;
}