/// Copyright (C) 2000-2009 IDMT. All rights reserved.
///
/// Author: 黄璧（重庆）
///
/// Creation Date: 2009/07/10
///
/// Description:后台批渲坏帧，yy提供坏帧数据,只用sw
global proc HbBadFrameRender()
{

	python("import tempfile");
	string $GetPath=`python("tempfile.gettempdir()")`;
	$exampleFileName=$GetPath+"\\YYBadFrameData.txt";
	$fileId=`fopen $exampleFileName "r"`;
	string $GetAllYYData;
	$GetAllYYData=`fread $fileId $GetAllYYData`;
	fclose $fileId;
	string $GetFileName=`file -q -sn -shn`;
	string $ImageName[];
	       $numTokens = `tokenize $GetFileName "." $ImageName`;
	string $BuffCam[];
	       $numTokens = `tokenize $GetFileName "-" $BuffCam`;
	string $GetRenderCam="";
	string $GetAllCams[]=`ls  -cameras`;
		for($everyCam in $GetAllCams)
		{
			int $GetCamRenderAble=`getAttr ($everyCam +".renderable")`;
			if ($GetCamRenderAble==1)
				$GetRenderCam=$everyCam;

		}
	string $buffer0[];
               $numTokens = `tokenize $GetAllYYData "*" $buffer0`;
	string $buffer[];
               $numTokens = `tokenize $buffer0[size($buffer0)-1] "\n" $buffer`;
	catch(`setAttr defaultRenderGlobals.animation 0`);			
	catch(`setAttr defaultRenderGlobals.periodInExt 1`);
		if (`getAttr defaultRenderGlobals.outFormatControl` == 1)
			catch(`setAttr defaultRenderGlobals.outFormatControl 0`);
	for($i=0;$i<size($buffer);$i++)
		{	
			string $bufferFrame[];
			       $numTokens = `tokenize $buffer[$i] ">>>" $bufferFrame`;
			       print ($bufferFrame[0]+".........\n");
			string $everyFrame[];
			       $numTokens = `tokenize $bufferFrame[1] "," $everyFrame`;
			int $quest=$everyFrame[0];
			if ($quest!=0)
			{
				string $GetAllFrame="";
				for ($kk in $everyFrame)
					{	
						string $everyFrame2[];
						       $numTokens = `tokenize $kk  "-" $everyFrame2`;
						if($numTokens==1)
						{
							$GetAllFrame=$GetAllFrame+$kk+"$";	
						}
						else if($numTokens>1)
						{
							for($ss=int($everyFrame2[0]);$ss<int($everyFrame2[1])+1;$ss++ )
							{
							$GetAllFrame=$GetAllFrame+$ss+"$";
							}
						}
					}
				string $everyFrameNeed[];
				       $numTokens = `tokenize $GetAllFrame "$" $everyFrameNeed`;
				sysFile -makeDir ($buffer0[$i]+"_ADD");
				for ($k=0;$k<size($everyFrameNeed);$k++)
					{
						print (">>>>>>>>>>>>"+$everyFrameNeed[$k]+"\n");
						int $NeedFrame=$everyFrameNeed[$k];
						currentTime $NeedFrame;
						string $GetImagePath=`render -layer $bufferFrame[0] $GetRenderCam`;
						string $destWindows=$buffer0[$i]+"_ADD/"+$ImageName[0]+"_"+$bufferFrame[0]+"."+$NeedFrame+".iff";
						sysFile -move $destWindows $GetImagePath; 

					}
			}
			else 
				print ($bufferFrame[0]+" Have No Problem\n");
		}
}