global proc s100ProdManagerUIRefresh()
{
string $selectProd[];
$selectProd = `textScrollList -q -si s100ProdManagerUITSProd` ;
string $selectEp;

s100ProdManagerUIRefreshProd ;



	if(size($selectProd) > 0 )
	{
		textScrollList -e -si $selectProd  s100ProdManagerUITSProd ;

		s100ProdManagerUIRefreshLibrary($selectProd[0]) ;
		s100ProdManagerUIRefreshLibraryOP ;
		s100ProdManagerUIRefreshEpPath ;
		$selectEp = `optionMenu -q -v   s100ProdManagerUIFormLayoutOPEP`;
		s100ProdManagerUIRefreshEpisode($selectProd[0]) ;
			if(size($selectEp) > 0 )
			 {
				optionMenu -e -v $selectEp  s100ProdManagerUIFormLayoutOPEP;
             }
		//s100ProdManagerUIRefreshDept($selectProd[0]) ;
		s100MPRefreshSqListSeq ;
		s100FileManagerRefreshUI;
	}


}

global proc s100ProdManagerUIRefreshSeq()
{
$selectProd = `textScrollList -q -si  s100ProdManagerUITSProd` ;

$prod  = $selectProd[0] ;
$ep = `optionMenu -q -v s100ProdManagerUIFormLayoutOPEP`;

$sqF = s100ASNormalizeAndReturnAllSqFolders( $prod ,  $ep) ;


$test = `optionMenu -q -itemListLong s100ProdManagerUIFormLayoutOPSeq`;
	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $sqF)
	{
	menuItem -label $tmp  -p s100ProdManagerUIFormLayoutOPSeq;
	}




}


global proc s100ProdManagerUIRefreshDept(string $prod)
{


$folder = sort( `s100assetManagerGetDeptTemp($prod)` );

$test = `optionMenu -q -itemListLong s100ProdManagerUIFormLayoutOPDepartment`;
	if (size($test) > 0 )
		deleteUI -mi $test  ;



	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100ProdManagerUIFormLayoutOPDepartment;
	}






}



global proc s100ProdManagerUIRefreshEpisode(string $prod)
{


$folder = s100ASListEp($prod) ;
$test = `optionMenu -q -itemListLong s100ProdManagerUIFormLayoutOPEP`;
	if (size($test) > 0 )
		deleteUI -mi $test  ;

	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100ProdManagerUIFormLayoutOPEP;
	}
}


global proc s100ProdManagerUIRefreshEpPath()
{
$select = `textScrollList -q -si  s100ProdManagerUITSProd` ;


$get = `s100assetManagerGetEpPath($select[0]) `;
textField -e -tx $get s100ProdManagerUIFormLayoutTFAbsPathEpisode;


}


global proc s100ProdManagerUIRefreshProd()
{
global string $base_prodFilesSystem ;

$select = `textScrollList -q -si  s100ProdManagerUITSProd` ;

//print $base_prodFilesSystem ;
textScrollList -e -ra    s100ProdManagerUITSProd ;

$files = `getFileList -folder ($base_prodFilesSystem + "prod/" )`;
$filesSort = sort($files) ;
$size = size($filesSort) ;
//textScrollList -e -numberOfRows $size  s100ProdManagerUITSProd ;
	for ($i =0 ; $i < size($filesSort) ; $i++)
	{
	$tmpName = substituteAllString ($filesSort[$i] , ".txt" , "" ) ;
 	textScrollList -e -append $tmpName  s100ProdManagerUITSProd ;
    }



	if (size($select) > 0 )
	{


	$check = `textScrollList -q -exists $select s100ProdManagerUITSProd `;
		if ($check == 1 )
		{
		textScrollList -e -si $select s100ProdManagerUITSProd ;
        }

    }



}





global proc s100ProdManagerUIRefreshLibrary(string $prod)
{
//$prod = $selectProd[0]
string $pathTab[0];
$pathTab = s100assetManagerGetProdPath($prod);
$path = $pathTab[0];


//$path += "/" + `s100AMsourceBank`;
$path += "/" + `s100AMsourceBankSub($prod)` +"/";

$folder = sort (`s100ListOnlyFolder($path) `);


optionMenu -q -itemListLong s100ProdManagerUIFormLayoutOPAsset;




	for ($tmp  in $folder)
	{
	menuItem -label $tmp  -p s100ProdManagerUIFormLayoutOPAsset;
	}







}

global proc s100ProdManagerUIRefreshLibraryOP()
{

$selectProd = `textScrollList -q -si  s100ProdManagerUITSProd` ;
string $pathTab[];
$pathTab = s100assetManagerGetProdPath($selectProd[0]);
$path = $pathTab[0];

//$path += "/" + `s100AMsourceBank`;

$path += "/" + $pathTab[1] +"/";

//$tmp  = `optionMenu -q -v s100ProdManagerUIFormLayoutOPAsset`;

//$path +=  $tmp ;


textField -e -text $path s100ProdManagerUIFormLayoutTFPathAsset ;

}


