global proc s100ProdManagerUI()
{

if(`window -ex 	s100ProdManagerUI`)
	deleteUI s100ProdManagerUI;

window -title "studio 100 Animation Prod Manager"  -h 400  s100ProdManagerUI;
columnLayout -adjustableColumn true s100ProdManagerUICLMain;
s100ProdManagerUIMenu ;
s100ProdManagerUIFormLayout;
s100ProdManagerUIRefresh ;
window -e -h 546 -w 660 -sizeable 0  s100ProdManagerUI;
	showWindow;


}




global proc s100OpenFolderAssetPath()
{
$path = `textField -q -tx s100ProdManagerUIFormLayoutTFPathAsset `;
system ("load " + $path) ;

}



global proc s100ProdManagerUIMenu()
{
menuBarLayout s100ProdManagerUIMLMain;
//menu -label "File";
 //       menuItem -label "Prod Manager";


   // menu -label "Edit";
        //menuItem -e-c s100ProdManagerPreferenceUI -label "Preference";




    menu -label "Help" -helpMenu true;
        menuItem -label "help";
        menuItem -label "About...";

    setParent ..;

}


global proc s100ProdManagerUIFormLayout()
{
formLayout s100ProdManagerUIFLMain;

$textProd = `text -font boldLabelFont -label " Prod " `;

//explore Prod

	$listH = 300 ;
	$takeWidth = 195 ;
	$butWidth = $takeWidth ;
	$prodExplorer = `textScrollList -selectCommand s100ProdManagerUIRefresh -w $takeWidth -height $listH s100ProdManagerUITSProd`;

	$sepProd = `separator -w  ($takeWidth )  `;

	$buttonAddProd = `button -c s100ProdManagerAddProdUI -w $butWidth -label "Add Prod"`;
	$buttonEditProd = `button -c s100ProdManagerEditProdUI -w $butWidth -label "Edit Prod"`;
	$buttonRemoveProd = `button -c s100ProdManagerRemProd -w $butWidth -label "Remove Prod"`;
	$buttonImportProd = `button -en 0 -w $butWidth -label "Import Prod"`;
	$buttonExportProd = `button -en 0 -w $butWidth -label "Export Prod"`;







//Library 3d

	$widthButtonAsset = 50 ;
	$widthSepAsset = $takeWidth ;

	$textLib = `text -w 50 -font boldLabelFont -label "Library " `;
	/*
	$textAsset = `text-w 90 -font fixedWidthFont -label "Asset " `;
	$sepAsset1 = `separator -w $widthSepAsset `;
	*/
	$assetOptMenu = `optionMenu -visible 0 -changeCommand s100ProdManagerUIRefreshLibraryOP  s100ProdManagerUIFormLayoutOPAsset `;
	/*
	$buttonAddAsset = `button -label "ADD" -c s100ProdManagerAddAssetTypePre  -w $widthButtonAsset `;
	$buttonRemAsset = `button -en 0 -label "REM" -w $widthButtonAsset `;
	*/
	$textPathAsset = `text -w 90 -font fixedWidthFont  -label " Path " `;
	$sepAsset2 = `separator -w $widthSepAsset `;

	$textFieldPathAsset = `textField -w $takeWidth -en 0 s100ProdManagerUIFormLayoutTFPathAsset`;

	$buttonEditAssetPath = `button -c s100OpenFolderAssetPath -label "VIEW" -w $widthButtonAsset `;


//Shot

	$textShoot = `text -font boldLabelFont -label " Shot " `;


	//Absolute path to Episode
	$textAbsEp = `text -label "Absolute Path To Episode" `;

	$sepAbsPath = `separator -w $widthSepAsset`;

	$absPathEp = `textField -w $takeWidth -en 0 s100ProdManagerUIFormLayoutTFAbsPathEpisode`;

	$absPathEpButton = `button -c s100ProdManagerEditEp -label "EDIT" -w $widthButtonAsset `;



//Episode

	$epText2 = `text -w 60 -font fixedWidthFont -l "Episode"`;
	$sepEp = `separator -w $widthSepAsset`;

	$textEp = `text -label "EP : " `;
	$epMenu = `optionMenu -changeCommand s100ProdManagerUIRefreshSeq  s100ProdManagerUIFormLayoutOPEP `;
	$epAdd  = `button -c s100ProdManagerAddEPPre -label "ADD" -w $widthButtonAsset `;
	//$epRem  = `button -en 0  -label "REM" -w $widthButtonAsset `;
	//$epMulti  = `button -en 0 -label "multiple Add" -h 15 -w ($widthButtonAsset *2 + 5 )  `;


//	sequence
	$seqText2 = `text -w 80 -font fixedWidthFont -l "Sequence"`;
	$sepSq = `separator -w $widthSepAsset`;
	$sqText = `text -l "Seq :" `;
	$sqMenu =  `optionMenu s100ProdManagerUIFormLayoutOPSeq `;
	$sqAdd  = `button -c s100ProdManagerAddSqPre -label "ADD" -w $widthButtonAsset `;
	//$sqRem  = `button -en 0  -label "REM" -w $widthButtonAsset `;
	//$sqMulti  = `button -en 0  -label "multiple Add"  -h 15  -w ($widthButtonAsset * 2 + 5  )  `;


	//



	/*
	//department
	$textDepartment = `text -w 90 -font fixedWidthFont -label "Department " `;
	$sepDept = `separator -w $widthSepAsset`;
	$depText = `text -l "Dept :" `;
	$depMenu = `optionMenu s100ProdManagerUIFormLayoutOPDepartment `;
	$depAdd = `button -c s100ProdManagerAddDeptPre -label "ADD" -w $widthButtonAsset `;
	$depRem = `button -en 0  -label "REM" -w $widthButtonAsset `;
	*/
	//

////////////////////////////////
//Layout
$widthBut = 22 ;
$sideCl1 = 10 ;
$sideCl1Button = $sideCl1  ;
$sideCl2 = $sideCl1 + $takeWidth + 20 ;
$sideCl3 = $sideCl2 + $takeWidth + 20 ;


$ligneTitle = 5 ;

$ligneProd = $ligneTitle + 20 ;

$ligneSepProd = $ligneProd + $listH + 10 ;

$ligneButProd = $ligneSepProd + 20 ;
$ligneButProd2 = $ligneButProd + $widthBut ;
$ligneButProd3 = $ligneButProd2 + $widthBut ;
$ligneButProd4 = $ligneButProd3 + $widthBut + 20 ;
$ligneButProd5 = $ligneButProd4 + $widthBut ;

//asset

$ligneAsset1 = $ligneTitle + 50 ;
$ligneAsset2 = $ligneAsset1 + 15 ;
$ligneAsset3 = $ligneAsset2 + 15 ;
$ligneAsset4 = $ligneAsset3 + 25 ;
$ligneAsset5 = $ligneAsset4 + 70 ;
$ligneAsset6 = $ligneAsset5 + 15 ;
$ligneAsset7 = $ligneAsset6 + 15 ;
$ligneAsset8 = $ligneAsset7 + 25 ;

$butAsset1 = $sideCl2 + ($takeWidth  - ($widthButtonAsset * 2  ) - 5 )   ;
$butAsset2 = $butAsset1 +$widthButtonAsset +  5 ;

//////////////////////

//shoot

$ligSh1 = $ligneTitle  + 20 ;
$ligSh2 = $ligSh1  + 15 ;
$ligSh3 = $ligSh2  + 15 ;
$ligSh4 = $ligSh3  + 25 ;
$ligSh5 = $ligSh4  + 25 ;
$ligSh6 = $ligSh5  + 25 ;

$butShot1 = $sideCl3 + ($takeWidth  - ($widthButtonAsset * 2  ) - 5 )   ;
$butShot2 = $butShot1 +$widthButtonAsset +  5 ;

formLayout -edit
//shot
	//text
    -attachForm $textShoot "top"    $ligneTitle
    -attachControl $textShoot "left" 20  $textFieldPathAsset

	//text Abs Path
    -attachControl $textAbsEp "top" 5 $textShoot
    -attachControl $textAbsEp "left" 20  $textFieldPathAsset

	//separator Abs Path
    -attachControl $sepAbsPath "top" 0 $textAbsEp
    -attachControl $sepAbsPath "left" 20  $textFieldPathAsset

	//textfield Abs Path
    -attachControl $absPathEp "top" 10  $sepAbsPath
    -attachControl $absPathEp "left" 20  $textFieldPathAsset

	//textfield Abs Path
    -attachControl $absPathEpButton "top"  2 $absPathEp
    -attachControl $absPathEpButton "left" 165  $textFieldPathAsset

		//episode


			//text

    -attachControl  $epText2     "top" 10 $absPathEpButton
    -attachControl $epText2 "left" 20  $textFieldPathAsset

			//separator

    -attachControl  $sepEp     "top" 0 $epText2
    -attachControl $sepEp "left" 20  $textFieldPathAsset

			//texte EP:

    -attachControl  $textEp     "top" 10 $sepEp
    -attachControl $textEp "left" 20  $textFieldPathAsset

			//EP menu

    -attachControl  $epMenu  "top" 5 $sepEp
    -attachControl $epMenu "left" 5 $textEp

			//EP add button

    -attachControl  $epAdd  "top" 2 $epMenu
    -attachControl $epAdd "left" 5 $epMenu

			//EP rem button

    //-attachControl  $epRem  "top" 2 $epMenu
    //-attachForm $epRem "left"   $butShot2

			//EP multi add button

    //-attachControl  $epMulti  "top" 2 $epRem
    //-attachForm $epMulti "left"   $butShot1


	//sequence
		//text

    -attachControl  $seqText2  "top" 20 $epAdd
    -attachControl $seqText2 "left" 20  $textFieldPathAsset

		//separator

    -attachControl  $sepSq  "top" 5 $seqText2
    -attachControl $sepSq "left" 20  $textFieldPathAsset

		//text

    -attachControl  $sqText  "top" 5 $sepSq
    -attachControl $sqText "left" 20  $textFieldPathAsset

		//menu

    -attachControl  $sqMenu  "top" 5 $sqText
    -attachControl $sqMenu "left"  5 $sqText


			//EP add button

    -attachControl  $sqAdd  "top" 2 $sqMenu
    -attachControl $sqAdd "left" 2  $sqMenu

			//EP rem button

   // -attachControl  $sqRem  "top" 2 $sqMenu
   // -attachForm $sqRem "left"   $butShot2

			//EP multi add button

   // -attachControl  $sqMulti  "top" 2 $sqRem
   //-attachForm $sqMulti "left"   $butShot1

//Asset

	//text
    -attachForm $textLib "top"    $ligneTitle
    -attachForm $textLib "left"   $sideCl2

	//Path
    -attachControl $textPathAsset "top" 5  $textLib
    -attachControl $textPathAsset "left" 15  $prodExplorer

	//separator
    -attachControl $sepAsset2 "top" 0 $textPathAsset
    -attachControl $sepAsset2 "left" 15  $prodExplorer

	//pathField
    -attachControl $textFieldPathAsset "top"  10  $sepAsset2
    -attachControl $textFieldPathAsset "left" 15  $prodExplorer

	//pathEdit
    -attachControl $buttonEditAssetPath "top" 2 $textFieldPathAsset
    -attachControl $buttonEditAssetPath "left" 160 $prodExplorer



//Prod
	//text
    -attachForm $textProd "top"    $ligneTitle
    -attachForm $textProd "left"   $sideCl1


	//explorer
    -attachControl $prodExplorer "top"  5  $textProd
    -attachForm $prodExplorer "left"   $sideCl1

	//separator
    -attachControl $sepProd "top"  10  $prodExplorer
    -attachForm $sepProd "left"   $sideCl1


	//buttons

			//Add Prod
		-attachControl $buttonAddProd "top" 5  $sepProd
		-attachForm $buttonAddProd "left"   $sideCl1Button

			//Edit Prod
		-attachControl $buttonEditProd "top" 0 $buttonAddProd
		-attachForm $buttonEditProd "left"   $sideCl1Button

			//Remove Prod
		-attachControl $buttonRemoveProd "top"  0 $buttonEditProd
		-attachForm $buttonRemoveProd "left"   $sideCl1Button

			//Import Prod
		-attachControl $buttonImportProd "top"  15  $buttonRemoveProd
		-attachForm $buttonImportProd "left"   $sideCl1Button


			//Export Prod
		-attachControl $buttonExportProd "top"  0  $buttonImportProd
		-attachForm $buttonExportProd "left"   $sideCl1Button


     s100ProdManagerUIFLMain;

	window -e -resizeToFitChildren 1 s100ProdManagerUI;

}




/*
s100ProdManagerUI ;
*/