//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc skRenderRaspberryAmbient()
{
	string $materials[] = `ls -type blinn "*sc003001raspberry_bead*" "*:*sc003001raspberry_bead*" "*:*:*sc003001raspberry_bead*"`;
	for ($m in $materials)
	{
		string $cons[] = `listConnections -s true -d false ($m+".ambientColorR")`;
		if (!`getAttr -l ($m+".ambientColorR")` && size($cons) == 0)
		{
			setAttr ($m+".ambientColorR") 0.6;
			setAttr ($m+".ambientColorG") 0.6;
			setAttr ($m+".ambientColorB") 0.6;
		}
	}
}