//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2008-11-3
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slAnimRepairShoulder()
{
	string $chars[] = `ls "*Character" "*:Character" "*:*:Character" "*:*:*:Character"`;

	for ($char in $chars )
	{
		string $buff[];
		int $num = `tokenize $char ":" $buff`;
		string $namespace = `substring $char 1 (size($char)-size($buff[$num-1]))`;

		if (`match "_sc015" $namespace` != "")
		{
			//ÓÒ¼ç°ò
			if (`objExists ($namespace+"RightArm_Shoulder1")` && `objExists ($namespace+"RightArm_Shoulder")`)
			{
				string $animcurves[] = `listConnections -type animCurve  ($namespace+"RightArm_Shoulder")`;
				for ($ac in $animcurves)
				{
					string $attr = `substring $ac (size($namespace+"RightArm_Shoulder")+2) (size($ac))`;

					string $dest[] = `listConnections -plugs true ($ac+".output")`;
					if (`objExists $dest[0]`)
						disconnectAttr ($ac+".output") $dest[0];

					orientConstraint -mo -weight 1  ($namespace+"RightArm_Shoulder1") ($namespace+"RightArm_Shoulder"); 
					connectAttr -f ($ac+".output") ($namespace+"RightArm_Shoulder1."+$attr);

				}
			}
			//×ó¼ç°ò
			if (`objExists ($namespace+"LeftArm_Shoulder1")` && `objExists ($namespace+"LeftArm_Shoulder")`)
			{
				string $animcurves[] = `listConnections -type animCurve  ($namespace+"LeftArm_Shoulder")`;
				for ($ac in $animcurves)
				{
					string $attr = `substring $ac (size($namespace+"LeftArm_Shoulder")+2) (size($ac))`;

					string $dest[] = `listConnections -plugs true ($ac+".output")`;
					if (`objExists $dest[0]`)
						disconnectAttr ($ac+".output") $dest[0];

					orientConstraint -mo -weight 1  ($namespace+"LeftArm_Shoulder1") ($namespace+"LeftArm_Shoulder"); 
					connectAttr -f ($ac+".output") ($namespace+"LeftArm_Shoulder1."+$attr);

				}
			}
		}
	}
}