//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 2008-11-3
//	Description:
//				关闭/开启所有角色的TFM的控制
//////////////////////////////////////////////////////////

global proc slAnimTFMOnOff()
{
	string $facemachines[] = `ls "*FM_data" "*:*FM_data" "*:*:*FM_data" "*:*:*:*FM_data"`;

	int $enable = 1,$nodestate = 0;
	for ($fm in $facemachines)
	{
		if (`objExists ($fm+".enableFaceMachine")`)
		{
			if (`getAttr ($fm+".enableFaceMachine")`)
			{
				$enable = 0;
				$nodestate = 1;
				break;
			} 
		}
	}

	for ($fm in $facemachines)
	{
		setAttr  ($fm+".enableFaceMachine") $enable;
		
		
		string $buff[];
		int $num = `tokenize $fm ":" $buff`;
		string $CharacterNamespace = `substring $fm 1 (size($fm)-size($buff[$num-1]))`;
		if ($num < 2)
		{
			$CharacterNamespace = "";
		}

		string $fmSkinClusters[] = `ls -type "fmSkinCluster" ($CharacterNamespace + "*")`;
		for($fmSkinCluster in $fmSkinClusters)
		{
			setAttr ($fmSkinCluster + ".nodeState") $nodestate;
		}
		
		string $fmRelativeBlends[] = `ls -type "fmRelativeBlend" ($CharacterNamespace + "*")`;
		for($fmRelativeBlend in $fmRelativeBlends) 
		{
			setAttr ($fmRelativeBlend + ".nodeState") $nodestate;
		}
	}

}