//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slModelSurfaceToModel()
{
	string $filepath = "//File-cluster/gdc/Projects/Strawberry/Strawberr_Scratch/TD/model/plant_lib/";
	if (!`filetest -r $filepath`)
		$filepath = "//File-cluster/gdc/Projects/Strawberry/Strawberry_Scratch/TD/model/plant_lib/";
	
	
	string $replaced[] = `ls -sl`;
	for ($tr in $replaced)
	{
		string $his[] = `listHistory -lv 1 $tr` ;
		string $shape = $his[0];

		string $sg[] = `listConnections -type shadingEngine $shape`;
		string $his[] = `listHistory $sg[0]`;
		for ($node in $his)
		{
			if (`nodeType $node` == "file")
			{
				string $imageName = `getAttr ($node+".fileTextureName")`;
				string $buff[];
				int $num = `tokenize $imageName "\/" $buff`;
				string $image = $buff[$num-1];
				$num = `tokenize $buff[$num-1] "." $buff`;
				$image = `substring $image 1 (size($image)-size($buff[$num-1])-1)`;
				string $file = $image + ".mb";

				print ($image+"\n");
				if (`filetest -r ($filepath+$file)`)
				{
					
				}
			}
		}
	}
}