//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2008-11-10
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slModelCreatTSMSet()
{
	//TSM
	sets -n TSM2Controls Character Upper_Body;
	
	//Head Controls
	sets -n Head_FK_Controls Head_Neck Head_FK;
	sets -n Head_IK_Controls Head_Head_IK;
	sets -n Head_Controls Head_FK_Controls Head_IK_Controls;
	sets -add TSM2Controls Head_Controls;

	//LeftArm Controls
	sets -n LeftArm_FK_Controls LeftArm_Shoulder LeftArm_Upper_Arm LeftArm_Lower_Arm LeftArm_HandTranslate LeftArm_Hand;
	sets -n LeftArm_IK_Controls LeftArm_Arm_IK LeftArm_Arm_Pole_Vector;
	sets -n LeftArm_Controls LeftArm_FK_Controls LeftArm_IK_Controls;
	sets -add TSM2Controls LeftArm_Controls;

	//LeftThumb Controls
	sets -n LeftThumb_Controls LeftThumb_finger_control LeftThumb_finger_IK;
	sets -add TSM2Controls LeftThumb_Controls;
	//LeftFinger1 Controls
	sets -n LeftFinger1_Controls LeftFinger1_finger_control LeftFinger1_finger_IK;
	sets -add TSM2Controls LeftFinger1_Controls;
	//LeftFinger2 Controls
	sets -n LeftFinger2_Controls LeftFinger2_finger_control LeftFinger2_finger_IK;
	sets -add TSM2Controls LeftFinger2_Controls;
	//LeftFinger3 Controls
	sets -n LeftFinger3_Controls LeftFinger3_finger_control LeftFinger3_finger_IK;
	sets -add TSM2Controls LeftFinger3_Controls;
	//LeftFinger4 Controls
	sets -n LeftFinger4_Controls LeftFinger4_finger_control LeftFinger4_finger_IK;
	sets -add TSM2Controls LeftFinger4_Controls;

	//LeftLeg Controls
	sets -n LeftLeg_FK_Controls LeftLeg_Upper_Leg LeftLeg_Lower_Leg  LeftLeg_Foot LeftLeg_Toe;
	sets -n LeftLeg_IK_Controls LeftLeg_Leg_Pole_Vector  LeftLeg_Standard_Pole_Vector LeftLeg_IK_Leg  LeftLeg_Toe_Pivot LeftLeg_Heel_Pivot;
	sets -n LeftLeg_Controls LeftLeg_FK_Controls LeftLeg_IK_Controls;
	sets -add TSM2Controls LeftLeg_Controls;

	//RightArm Controls
	sets -n RightArm_FK_Controls RightArm_Shoulder RightArm_Upper_Arm RightArm_Lower_Arm RightArm_HandTranslate RightArm_Hand;
	sets -n RightArm_IK_Controls RightArm_Arm_IK RightArm_Arm_Pole_Vector;
	sets -n RightArm_Controls RightArm_FK_Controls RightArm_IK_Controls;
	sets -add TSM2Controls RightArm_Controls;

	//RightThumb Controls
	sets -n RightThumb_Controls RightThumb_finger_control RightThumb_finger_IK;
	sets -add TSM2Controls RightThumb_Controls;
	//RightFinger1 Controls
	sets -n RightFinger1_Controls RightFinger1_finger_control RightFinger1_finger_IK;
	sets -add TSM2Controls RightFinger1_Controls;
	//RightFinger2 Controls
	sets -n RightFinger2_Controls RightFinger2_finger_control RightFinger2_finger_IK;
	sets -add TSM2Controls RightFinger2_Controls;
	//RightFinger3 Controls
	sets -n RightFinger3_Controls RightFinger3_finger_control RightFinger3_finger_IK;
	sets -add TSM2Controls RightFinger3_Controls;
	//RightFinger4 Controls
	sets -n RightFinger4_Controls RightFinger4_finger_control RightFinger4_finger_IK;
	sets -add TSM2Controls RightFinger4_Controls;

	//RightLeg Controls
	sets -n RightLeg_FK_Controls RightLeg_Upper_Leg RightLeg_Lower_Leg  RightLeg_Foot RightLeg_Toe;
	sets -n RightLeg_IK_Controls RightLeg_Leg_Pole_Vector  RightLeg_Standard_Pole_Vector RightLeg_IK_Leg  RightLeg_Toe_Pivot RightLeg_Heel_Pivot;
	sets -n RightLeg_Controls RightLeg_FK_Controls RightLeg_IK_Controls;
	sets -add TSM2Controls RightLeg_Controls;

	//Spine Controls
	sets -n Spine_FK_Controls Spine_Pelvis_FK Spine_Middle_FK Spine_Torso_FK;
	sets -n Spine_IK_Controls Spine_Torso_IK Spine_Middle_IK Spine_Pelvis_IK;
	sets -n Spine_Controls Spine_FK_Controls Spine_IK_Controls;
	sets -add TSM2Controls Spine_Controls;
}