//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slRenderCharacterControl()
{
	if (`window -ex slRenderCharacterControlWin`)
	{
		deleteUI slRenderCharacterControlWin;
	}
	
	window -title "Character Control" -menuBar true  -mxb false -s true  -resizeToFitChildren true slRenderCharacterControlWin;

		string $ccFrameLayout = `frameLayout -label "" -labelAlign "top" -cl false  -cll false -cc "" -borderStyle "etchedIn" `;
			string $ccColumnLayout = `columnLayout -adjustableColumn true ccColumnLayout`;
				string $ccFrameLayout1 = `frameLayout -label "" -labelAlign "top" -cl false  -cll false  -bv false -borderStyle "etchedIn" `;
					string $ccFormLayout = `formLayout `;
						string $charVis		= `button -l "Poly Hair"		 -w 52 -h 15 -command "slRenderCharacterControlShowAll  0"`;
						string $hairShadow		= `button -l "HairShadow"	 -w 72 -h 15 -command "slRenderCharacterControlShowAll  1"`;
						string $hairVis		= `button -l "Hair"			 -w 52 -h 15 -command "slRenderCharacterControlShowAll  2"`;
						string $smooth		= `button -l "Smooth"		 -w 52 -h 15 -command "slRenderCharacterControlShowAll  3"`;
					setParent ..;
					formLayout -edit
						-attachForm		$charVis			"top"		0
						-attachForm		$charVis			"left"		35

						-attachForm		$hairShadow		"top"		0
						-attachControl	$hairShadow		"left"		0	$charVis
						
						-attachForm		$hairVis			"top"		0
						-attachControl	$hairVis			"left"		0	$hairShadow
						
						-attachForm		$smooth			"top"		0
						-attachControl	$smooth			"left"		0	$hairVis
					$ccFormLayout;
				setParent ..;
				frameLayout -label "" -labelAlign "top" -cl false  -cll false  -bv false -borderStyle "etchedIn" ;
					rowColumnLayout	 -numberOfColumns 5 -cw 1 52 -cw 2 72 -cw 3 52 -cw 4 52 slRenderCharacterControlWin_charCon;
						string $master[] = `ls  "*:*Character" "*:*:*Character"`;
						for ($char in $master)
						{
							string $UB = `substring $char 1 (size($char)-9)`+"Upper_Body";
							string $charName = `substring $char 1 (size($char)-10)`;
							if (`objExists $UB`)
							{
								string $charAttr[] = `slRenderCharacterControlAttr $UB`;
								
								text -label $charName -ann  ("Char :  "+$charName)  ($char + "_name");
								
								checkBox  -label "" -enable 1 -value 1 
								-onCommand  ("slRenderCharacterControlHideShow "+$UB+" 7") 
								-offCommand  ("slRenderCharacterControlHideShow "+$UB+" 8") 
								($char + "_vis_con");

								checkBox  -label "" -enable 1 -value 1 
								-onCommand  ("slRenderCharacterControlHideShow "+$UB+" 1") 
								-offCommand  ("slRenderCharacterControlHideShow "+$UB+" 2") 
								($char + "_hairshadow_con");

								checkBox  -label "" -enable 1 -value 1 
								-onCommand  ("slRenderCharacterControlHideShow "+$UB+" 3") 
								-offCommand ("slRenderCharacterControlHideShow "+$UB+" 4") 
								($char + "_hair_con");

								checkBox  -label "" -enable 1 -value 1 
								-onCommand  ("slRenderCharacterControlHideShow "+$UB+" 5") 
								-offCommand  ("slRenderCharacterControlHideShow "+$UB+" 6") 
								($char + "_smooth_con");
								
							}
						}
						slRenderCharacterControlUpdate("all");
					setParent ..;
				setParent ..;
			setParent ..;

	//window -e -w 295 -h 118 slRenderCharacterControlWin;
	showWindow slRenderCharacterControlWin;
}

global proc slRenderCharacterControlHideShow(string $char , int $mode)
{
	string $attrs[] = `slRenderCharacterControlAttr $char`;

	string $CHR = `substring $char 1 (size($char)-10)`+"CHR";
	switch ($mode)
	{
		case 1 :
			setAttr ($char+"."+$attrs[0]) 0;
			setAttr ($char+"."+$attrs[1]) 1;
			setAttr ($char+"."+$attrs[2]) 0;
			break;
		case 2 :
			//setAttr ($char+"."+$attrs[0]) 1;
			setAttr ($char+"."+$attrs[1]) 0;
			//setAttr ($char+"."+$attrs[2]) 0;
			break;
		case 3 :
			setAttr ($char+"."+$attrs[0]) 0;
			setAttr ($char+"."+$attrs[1]) 0;
			setAttr ($char+"."+$attrs[2]) 1;
			break;
		case 4 :
			//setAttr ($char+"."+$attrs[0]) 1;
			//setAttr ($char+"."+$attrs[1]) 0;
			setAttr ($char+"."+$attrs[2]) 0;
			break;
		case 5 :
			setAttr ($char+"."+$attrs[3]) 1;
			break;
		case 6 :
			setAttr ($char+"."+$attrs[3]) 0;
			break;
		case 7 :
			//setAttr ($CHR+".visibility") 1;
			setAttr ($char+"."+$attrs[0]) 1;
			setAttr ($char+"."+$attrs[1]) 0;
			setAttr ($char+"."+$attrs[2]) 0;
			break;
		case 8 :
			//setAttr ($CHR+".visibility") 0;
			setAttr ($char+"."+$attrs[0]) 0;
			break;
	}

	string $character = `substring $char 1 (size($char)-10)`+"Character";
	slRenderCharacterControlUpdate($character);
}

global proc string[] slRenderCharacterControlAttr(string $char)
{
	string $attrPolyhair[] = {"poly_hair_Vis","poly_hair_vis","Poly_hair_Vis"};
	string $attrHairshadow[] = {"HAIR_shadow","hair_shadow","HairShadow_Vis","Hair_shadow"};
	string $attrHairvis[] = {"HAIRPfx_visibility","Hair_Pfx","HAIR_visibility","Hair_Visible"};
	string $attrSmooth[] = {"Smooth","smooth"};
	string $attrHairDYN[]= {"hair_DYN","HAIR_DYN","Hair_DYN"};

	string $charAttr[] = {"NULL","NULL","NULL","NULL","NULL"};
	for ($attr in $attrPolyhair)
	{
		if (`attributeExists $attr $char`)
			$charAttr[0] = $attr;
	}
	for ($attr in $attrHairshadow)
	{
		if (`attributeExists $attr $char`)
			$charAttr[1] = $attr;
	}
	for ($attr in $attrHairvis)
	{
		if (`attributeExists $attr $char`)
			$charAttr[2] = $attr;
	}
	for ($attr in $attrSmooth)
	{
		if (`attributeExists $attr $char`)
			$charAttr[3] = $attr;
	}
	for ($attr in $attrHairDYN)
	{
		if (`attributeExists $attr $char`)
			$charAttr[4] = $attr;
	}

	return $charAttr;
}

global proc slRenderCharacterControlUpdate(string $char)
{
	string $master[];
	if ($char == "all")
		$master = `ls  "*:*Character" "*:*:*Character"`;
	else
		$master[0] = $char;

	for ($char in $master)
	{
		string $UB = `substring $char 1 (size($char)-9)`+"Upper_Body";
		string $charName = `substring $char 1 (size($char)-10)`;

		string $buff[];
		tokenize $char ":" $buff;
		tokenize $buff[size($buff)-2] "_" $buff;
		string $name = `GetCharacterNameById $buff[0] $buff[1]`;

		if (`objExists $UB`)
		{
			string $charAttr[] = `slRenderCharacterControlAttr $UB`;

			text -e -label $name ($char + "_name");
			
			//int $vis = `getAttr ($charName+":CHR.visibility")`;
			//checkBox -e -value $vis  ($char + "_vis_con");

			int $phEnable,$phVis;
			if (`attributeExists $charAttr[0] $UB`)
			{
				$phEnable = 1;$phVis = `getAttr ($UB+"."+$charAttr[0])`;
			}
			else
			{
				$phEnable = 0;$phVis = 1;
			}
			checkBox -e  -enable $phEnable -value $phVis ($char + "_vis_con");
			
			int $hsEnable,$hsVis;
			if (`attributeExists $charAttr[1] $UB`)
			{
				$hsEnable = 1;$hsVis = `getAttr ($UB+"."+$charAttr[1])`;
			}
			else
			{
				$hsEnable = 0;$hsVis = 1;
			}
			checkBox -e  -enable $hsEnable -value $hsVis ($char + "_hairshadow_con");

			
			int $hEnable,$hVis;
			if (`attributeExists $charAttr[2] $UB`)
			{
				$hEnable = 1;$hVis = `getAttr ($UB+"."+$charAttr[2])`;
			}
			else
			{
				$hEnable = 0;$hVis = 1;
			}
			checkBox -e -enable $hEnable -value $hVis ($char + "_hair_con");

			int $sEnable,$sVis;
			if (`attributeExists $charAttr[3] $UB`)
			{
				$sEnable = 1;$sVis = `getAttr ($UB+"."+$charAttr[3])`;
			}
			else
			{
				$sEnable = 0;$sVis = 1;
			}
			checkBox -e -enable $sEnable -value $sVis ($char + "_smooth_con");
		}
	}
}

global proc slRenderCharacterControlShowAll(int $type)
{
	string $CBName;
	int $mod;
	switch ($type)
	{
		case 0 :
			$CBName = "_vis_con";
			$mod = 8;
			break;
		case 1 :
			$CBName = "_hairshadow_con";
			$mod = 2;
			break;
		case 2 :
			$CBName = "_hair_con";
			$mod = 4;
			break;
		case 3 :
			$CBName = "_smooth_con";
			$mod = 6;
			break;
	}
	
	
	string $master[] = `ls  "*:*Character" "*:*:*Character"`;
	int $get = 0;
	int $state;
	for ($char in $master)
	{
		if (`checkBox -ex ($char+$CBName)` && `checkBox -q -en ($char+$CBName)`)
		{
			string $UB = `substring $char 1 (size($char)-9)`+"Upper_Body";
			
			if ($get==0)
			{
				$state = 1 - (int)`checkBox -q -v ($char+$CBName)`;
				$get = 1;
			}
			
			checkBox -e -v $state ($char+$CBName);
			slRenderCharacterControlHideShow $UB ($mod-$state) ;
			
			
			/*string $CBCommand = ;
			//if ($state)
				//$CBCommand = `checkBox -q -onc ($char+$CBName)`;
			//else 
				$CBCommand = `checkBox -q -ofc ($char+$CBName)`;

			print ($CBCommand+"\n");
			//eval $CBCommand;*/
		}
	}
	
}