//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 2008-11-20
//
//	Update/Change: WansHoulOng
//	Last Updated: 2008-11-20
//	Description:
//				Camera Tools---切换场景视图的摄像机和RenderView窗口的摄像机
//////////////////////////////////////////////////////////

global proc slRenderCameraTools()
{
	if (`window -ex slRenderCameraToolsWin`)
	{
		deleteUI slRenderCameraToolsWin;
	}
	
	window -title "Camera Tools" -menuBar true  -mxb false -s true  -resizeToFitChildren true slRenderCameraToolsWin;
		string $CameraTools = `frameLayout -label "" -labelAlign "top" -cl false -cll false -cc "" -borderStyle "etchedIn"`;
			string $CameraToolsForm = `formLayout `;
				//Scene Camera
				string $camList = `optionMenuGrp -l "S:"  -columnWidth 1 20 -columnWidth 2 128   -cc "skRCTCamLoop(2,0)" slRenderCameraToolsWin_camList`;
				int $exCam = 0;
				//string $camera[] = `ls -type camera`;
				string $camera[] = `listCameras -perspective`;
				string $curCam = `lookThru -q `;
				for ($cam in $camera)
				{
					//string $cam[] = `listRelatives -p $camShape`;
					//if (!(startsWith($cam[0],"top") || startsWith($cam[0],"front") || startsWith($cam[0],"side")))
					//{
						menuItem -label $cam ;	
					//}
					if ($cam == $curCam)
						$exCam = 1;
				}
				if ($exCam)
					optionMenuGrp -edit -v $curCam $camList;
				else 
					optionMenuGrp -edit -v persp $camList;
				string $camFront	= `button -l "<<front"  -w 45 -h 25 -command "skRCTCamLoop(0,0)"`;
				string $camBack 	= `button -l "back >>"  -w 45 -h 25 -command "skRCTCamLoop(1,0)"`;
				
				//RenderView Camera
				string $rcamList = `optionMenuGrp -l "R:"  -columnWidth 1 20 -columnWidth 2 128  -cc "skRCTCamLoop(2,1)" slRenderCameraToolsWin_rcamList`;
				int $exCam = 0;
				for ($cam in $camera)
				{
					//string $cam[] = `listRelatives -p $camShape`;
					//if (!(startsWith($cam[0],"top") || startsWith($cam[0],"front") || startsWith($cam[0],"side")))
					//{
						menuItem -label $cam ;	
					//}
					if ($cam == $curCam)
						$exCam = 1;
				}
				if ($exCam)
					optionMenuGrp -edit -v $curCam $rcamList;
				else 
					optionMenuGrp -edit -v persp $rcamList;
				string $rcamFront	= `button -l "<<front"  -w 45 -h 25 -command "skRCTCamLoop(0,1)"`;
				string $rcamBack 	= `button -l "back >>"  -w 45 -h 25 -command "skRCTCamLoop(1,1)"`;
			setParent ..;
			formLayout -edit
				-attachForm		$camList			"top"		5
				-attachForm		$camList			"left"		0
				
				-attachControl	$camFront		"top"		5	$camList
				-attachForm		$camFront		"left"		20
				
				-attachControl	$camBack		"top"		5	$camList
				-attachControl	$camBack		"left"		10	$camFront

				-attachForm		$rcamList		"top"		5
				-attachForm		$rcamList		"left"		150	
				
				-attachControl	$rcamFront		"top"		5	$rcamList
				-attachForm		$rcamFront		"left"		170	
				
				-attachControl	$rcamBack		"top"		5	$rcamList
				-attachControl	$rcamBack		"left"		10	$rcamFront
			$CameraToolsForm;
		setParent ..;
	
	window -e -w 295 -h 118 slRenderCameraToolsWin;
	showWindow slRenderCameraToolsWin;
}

global proc skRCTCamLoop(int $mod,int $scene)
{
	if ($mod == 2)
	{
		string $select;
		if ($scene)
			$select = `optionMenuGrp -q -v slRenderCameraToolsWin_rcamList`;
		else 
			$select = `optionMenuGrp -q -v slRenderCameraToolsWin_camList`;
		
		if ($scene)
		{
			RenderViewWindow;
			renderWindowRenderCamera snapshot renderView $select;
			optionMenuGrp -e -v $select slRenderCameraToolsWin_rcamList;
		}
		else
		{	
			optionMenuGrp -e -v $select slRenderCameraToolsWin_camList;
			lookThru $select;
		}
	}
	else
	{
		/*string $default[] = {"top","front","side"};
		string $shapes[] = `ls -type camera`;
		string $cams[]={};

		for ($cam in $shapes)
		{
			$trans = `listRelatives -p $cam`;
			if (stringArrayCount($trans[0],$default) == 0)
			{
				$cams[size($cams)] = $trans[0];
			}
		}
		
		string $vis;
		if ($scene)
			$vis = `renderWindowEditor -q  -crc renderView`;
		else
			$vis = `lookThru -q`;
		string $curCam[] = `ls  $vis`;
		int $num = 0;
		for ($i=0;$i<size($cams) ;$i++ )
		{
			if ($cams[$i] == $curCam[0]) $num = $i;
		}
		
		if ($mod == 0)
		{
			if ($num == 0)
				$num = (size($cams)-1);
			else	$num = $num - 1;
		}
		else if ($mod == 1)
		{
			if ($num == (size($cams)-1))
				$num = 0;
			else	$num = $num + 1;	
		}*/

		int $curnum =0;
		int $totalnum = `optionMenuGrp -q -ni slRenderCameraToolsWin_camList`;
		if ($scene)
			$curnum = `optionMenuGrp -q -sl slRenderCameraToolsWin_rcamList`;
		else
			$curnum = `optionMenuGrp -q -sl slRenderCameraToolsWin_camList`;
		
		if ($mod == 0)
		{
			if ($curnum == 1)
				$curnum = $totalnum;
			else	
				$curnum = $curnum - 1;
		}
		else if ($mod == 1)
		{
			if ($curnum == $totalnum)
				$curnum = 1;
			else	
				$curnum = $curnum + 1;	
		}

		if ($scene)
		{	
			//RenderViewWindow;
			//renderWindowRenderCamera snapshot renderView  $cams[$num];
			optionMenuGrp -e -sl $curnum slRenderCameraToolsWin_rcamList;
			skRCTCamLoop(2,1);
		}
		else
		{
			//lookThru $cams[$num];
			optionMenuGrp -e -sl $curnum slRenderCameraToolsWin_camList;
			skRCTCamLoop(2,0);
		}

	}
}
