//////////////////////////////////////////////////////////
//
//	Script Name: 
//	Author: WansHoulOng
//	Created: 
//
//	Update/Change: WansHoulOng
//	Last Updated: 
//	Description:
//				
//////////////////////////////////////////////////////////

global proc slRenderHighRes()
{
	string $file = `file -q -sn`;
	
	string $filename = `file -q -sn -shn`;
	$filename = `substring $filename 1 (size($filename)-3)`;
	
	string $CurrentRenderLayer = `editRenderLayerGlobals -q -crl`;
	
	string $imagenamepre = $filename+"_"+$CurrentRenderLayer;

	float $imagewidth = `getAttr "defaultResolution.width"`;
	float $imageheight = `getAttr "defaultResolution.height"`;

	float $currenttime = `currentTime -q`;

	string $maya = `getenv "MAYA_LOCATION"`;
	string $proj = `workspace -q -fn`;

	int $segments = 4;

	string $cmd = $maya+"/bin/mayabatch.exe -render -s "+$currenttime+" -e "+$currenttime+" -b 1 -x "+$imagewidth+" -y "+$imageheight;

	string $cmdadd = " -proj "+$proj+" -rl "+$CurrentRenderLayer+" -rd d:/who "+$file;

	for ($i=1;$i<=$segments;$i++ )
	{
		float $piece = sqrt($segments);
		float $xl = 0+(($imagewidth/$piece)*fmod(($i-1),$piece));
		float $xr = $xl+$imagewidth/$piece-1;

		float $yl = 0+(($imageheight/$piece)*(int)(($i-1)/$piece));
		float $yh = $yl+$imageheight/$piece-1;

		string $sn = `substring ((string)(1000+$i)) 2 4`;

		string $batch = $cmd+" -xl "+$xl+" -xr "+$xr+" -yl "+$yl+" -yh "+$yh+" -im segment_"+$sn+$cmdadd;

		print ($batch+"\n");
		system $batch;
	}
}