global proc zjSkSetWing()
{
	string $sl[] = `ls -sl`;
	if (`objExists $sl[0]`)
	{
		string $buf[];
		clear $buf;
		tokenize $sl[0] ":" $buf;
		string $ns = $buf[0];
	
		source generateChannelMenu.mel;
		CBdeleteConnection ($ns + ":Character.swing_wing_loop");
		CBdeleteConnection ($ns + ":Character.frequency_wing_loop");
		CBdeleteConnection ($ns +":Character.wing_swing_up_scale");
		CBdeleteConnection ($ns +":Character.wing_swing_down_scale");
		setAttr ($ns + ":Character.swing_wing_loop") 88.482;
		setAttr ($ns + ":Character.frequency_wing_loop") 107.084;
		setAttr ($ns + ":Character.wing_swing_up_scale") 1;
		setAttr ($ns + ":Character.wing_swing_down_scale") 0.809;
	}
}
